export const setSeed = [
        {
            tcgId: 1,
            name: 'Base',
            id: 'base1',
            series: 'Base',
            printedTotal: 102,
            total: 102,
            ptcgoid: 'BS',
            releaseDate: new Date('1999/01/09'),
            logoUrl: 'https://images.pokemontcg.io/base1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/base1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Jungle',
            id: 'base2',
            series: 'Base',
            printedTotal: 64,
            total: 64,
            ptcgoid: 'JU',
            releaseDate: new Date('1999/06/16'),
            logoUrl: 'https://images.pokemontcg.io/base2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/base2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Wizards Black Star Promos',
            id: 'basep',
            series: 'Base',
            printedTotal: 53,
            total: 53,
            ptcgoid: 'PR',
            releaseDate: new Date('1999/07/01'),
            logoUrl: 'https://images.pokemontcg.io/basep/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/basep/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Fossil',
            id: 'base3',
            series: 'Base',
            printedTotal: 62,
            total: 62,
            ptcgoid: 'FO',
            releaseDate: new Date('1999/10/10'),
            logoUrl: 'https://images.pokemontcg.io/base3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/base3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Base Set 2',
            id: 'base4',
            series: 'Base',
            printedTotal: 130,
            total: 130,
            ptcgoid: 'B2',
            releaseDate: new Date('2000/02/24'),
            logoUrl: 'https://images.pokemontcg.io/base4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/base4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Team Rocket',
            id: 'base5',
            series: 'Base',
            printedTotal: 82,
            total: 83,
            ptcgoid: 'TR',
            releaseDate: new Date('2000/04/24'),
            logoUrl: 'https://images.pokemontcg.io/base5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/base5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Gym Heroes',
            id: 'gym1',
            series: 'Gym',
            printedTotal: 132,
            total: 132,
            ptcgoid: 'G1',
            releaseDate: new Date('2000/08/14'),
            logoUrl: 'https://images.pokemontcg.io/gym1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/gym1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Gym Challenge',
            id: 'gym2',
            series: 'Gym',
            printedTotal: 132,
            total: 132,
            ptcgoid: 'G2',
            releaseDate: new Date('2000/10/16'),
            logoUrl: 'https://images.pokemontcg.io/gym2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/gym2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Neo Genesis',
            id: 'neo1',
            series: 'Neo',
            printedTotal: 111,
            total: 111,
            ptcgoid: 'N1',
            releaseDate: new Date('2000/12/16'),
            logoUrl: 'https://images.pokemontcg.io/neo1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/neo1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Neo Discovery',
            id: 'neo2',
            series: 'Neo',
            printedTotal: 75,
            total: 75,
            ptcgoid: 'N2',
            releaseDate: new Date('2001/06/01'),
            logoUrl: 'https://images.pokemontcg.io/neo2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/neo2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Southern Islands',
            id: 'si1',
            series: 'Other',
            printedTotal: 18,
            total: 18,
            ptcgoid: undefined,
            releaseDate: new Date('2001/07/31'),
            logoUrl: 'https://images.pokemontcg.io/si1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/si1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Neo Revelation',
            id: 'neo3',
            series: 'Neo',
            printedTotal: 64,
            total: 66,
            ptcgoid: 'N3',
            releaseDate: new Date('2001/09/21'),
            logoUrl: 'https://images.pokemontcg.io/neo3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/neo3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Neo Destiny',
            id: 'neo4',
            series: 'Neo',
            printedTotal: 105,
            total: 113,
            ptcgoid: 'N4',
            releaseDate: new Date('2002/02/28'),
            logoUrl: 'https://images.pokemontcg.io/neo4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/neo4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Legendary Collection',
            id: 'base6',
            series: 'Other',
            printedTotal: 110,
            total: 110,
            ptcgoid: 'LC',
            releaseDate: new Date('2002/05/24'),
            logoUrl: 'https://images.pokemontcg.io/base6/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/base6/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Expedition Base Set',
            id: 'ecard1',
            series: 'E-Card',
            printedTotal: 165,
            total: 165,
            ptcgoid: 'EX',
            releaseDate: new Date('2002/09/15'),
            logoUrl: 'https://images.pokemontcg.io/ecard1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ecard1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Best of Game',
            id: 'bp',
            series: 'Other',
            printedTotal: 9,
            total: 9,
            ptcgoid: 'BP',
            releaseDate: new Date('2002/12/01'),
            logoUrl: 'https://images.pokemontcg.io/bp/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bp/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Aquapolis',
            id: 'ecard2',
            series: 'E-Card',
            printedTotal: 147,
            total: 182,
            ptcgoid: 'AQ',
            releaseDate: new Date('2003/01/15'),
            logoUrl: 'https://images.pokemontcg.io/ecard2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ecard2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Skyridge',
            id: 'ecard3',
            series: 'E-Card',
            printedTotal: 144,
            total: 182,
            ptcgoid: 'SK',
            releaseDate: new Date('2003/05/12'),
            logoUrl: 'https://images.pokemontcg.io/ecard3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ecard3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Ruby & Sapphire',
            id: 'ex1',
            series: 'EX',
            printedTotal: 109,
            total: 109,
            ptcgoid: 'RS',
            releaseDate: new Date('2003/07/01'),
            logoUrl: 'https://images.pokemontcg.io/ex1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Sandstorm',
            id: 'ex2',
            series: 'EX',
            printedTotal: 100,
            total: 100,
            ptcgoid: 'SS',
            releaseDate: new Date('2003/09/18'),
            logoUrl: 'https://images.pokemontcg.io/ex2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Dragon',
            id: 'ex3',
            series: 'EX',
            printedTotal: 97,
            total: 100,
            ptcgoid: 'DR',
            releaseDate: new Date('2003/11/24'),
            logoUrl: 'https://images.pokemontcg.io/ex3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Nintendo Black Star Promos',
            id: 'np',
            series: 'NP',
            printedTotal: 40,
            total: 40,
            ptcgoid: 'PR-NP',
            releaseDate: new Date('2003/10/01'),
            logoUrl: 'https://images.pokemontcg.io/np/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/np/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Team Magma vs Team Aqua',
            id: 'ex4',
            series: 'EX',
            printedTotal: 95,
            total: 97,
            ptcgoid: 'MA',
            releaseDate: new Date('2004/03/01'),
            logoUrl: 'https://images.pokemontcg.io/ex4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'EX Trainer Kit Latias',
            id: 'tk1a',
            series: 'EX',
            printedTotal: 10,
            total: 10,
            ptcgoid: undefined,
            releaseDate: new Date('2004/06/01'),
            logoUrl: 'https://images.pokemontcg.io/tk1a/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/tk1a/symbol.png'
        },
        {
            tcgId: 1,
            name: 'EX Trainer Kit Latios',
            id: 'tk1b',
            series: 'EX',
            printedTotal: 10,
            total: 10,
            ptcgoid: undefined,
            releaseDate: new Date('2004/06/01'),
            logoUrl: 'https://images.pokemontcg.io/tk1b/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/tk1b/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Hidden Legends',
            id: 'ex5',
            series: 'EX',
            printedTotal: 101,
            total: 102,
            ptcgoid: 'HL',
            releaseDate: new Date('2004/06/01'),
            logoUrl: 'https://images.pokemontcg.io/ex5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'FireRed & LeafGreen',
            id: 'ex6',
            series: 'EX',
            printedTotal: 112,
            total: 116,
            ptcgoid: 'RG',
            releaseDate: new Date('2004/09/01'),
            logoUrl: 'https://images.pokemontcg.io/ex6/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex6/symbol.png'
        },
        {
            tcgId: 1,
            name: 'POP Series 1',
            id: 'pop1',
            series: 'POP',
            printedTotal: 17,
            total: 17,
            ptcgoid: undefined,
            releaseDate: new Date('2004/09/01'),
            logoUrl: 'https://images.pokemontcg.io/pop1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pop1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Team Rocket Returns',
            id: 'ex7',
            series: 'EX',
            printedTotal: 109,
            total: 111,
            ptcgoid: 'TRR',
            releaseDate: new Date('2004/11/01'),
            logoUrl: 'https://images.pokemontcg.io/ex7/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex7/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Deoxys',
            id: 'ex8',
            series: 'EX',
            printedTotal: 107,
            total: 108,
            ptcgoid: 'DX',
            releaseDate: new Date('2005/02/01'),
            logoUrl: 'https://images.pokemontcg.io/ex8/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex8/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Emerald',
            id: 'ex9',
            series: 'EX',
            printedTotal: 106,
            total: 107,
            ptcgoid: 'EM',
            releaseDate: new Date('2005/05/01'),
            logoUrl: 'https://images.pokemontcg.io/ex9/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex9/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Unseen Forces',
            id: 'ex10',
            series: 'EX',
            printedTotal: 115,
            total: 145,
            ptcgoid: 'UF',
            releaseDate: new Date('2005/08/01'),
            logoUrl: 'https://images.pokemontcg.io/ex10/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex10/symbol.png'
        },
        {
            tcgId: 1,
            name: 'POP Series 2',
            id: 'pop2',
            series: 'POP',
            printedTotal: 17,
            total: 17,
            ptcgoid: undefined,
            releaseDate: new Date('2005/08/01'),
            logoUrl: 'https://images.pokemontcg.io/pop2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pop2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Delta Species',
            id: 'ex11',
            series: 'EX',
            printedTotal: 113,
            total: 114,
            ptcgoid: 'DS',
            releaseDate: new Date('2005/10/31'),
            logoUrl: 'https://images.pokemontcg.io/ex11/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex11/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Legend Maker',
            id: 'ex12',
            series: 'EX',
            printedTotal: 92,
            total: 93,
            ptcgoid: 'LM',
            releaseDate: new Date('2006/02/01'),
            logoUrl: 'https://images.pokemontcg.io/ex12/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex12/symbol.png'
        },
        {
            tcgId: 1,
            name: 'EX Trainer Kit 2 Plusle',
            id: 'tk2a',
            series: 'EX',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2006/03/01'),
            logoUrl: 'https://images.pokemontcg.io/tk2a/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/tk2a/symbol.png'
        },
        {
            tcgId: 1,
            name: 'EX Trainer Kit 2 Minun',
            id: 'tk2b',
            series: 'EX',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2006/03/01'),
            logoUrl: 'https://images.pokemontcg.io/tk2b/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/tk2b/symbol.png'
        },
        {
            tcgId: 1,
            name: 'POP Series 3',
            id: 'pop3',
            series: 'POP',
            printedTotal: 17,
            total: 17,
            ptcgoid: undefined,
            releaseDate: new Date('2006/04/01'),
            logoUrl: 'https://images.pokemontcg.io/pop3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pop3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Holon Phantoms',
            id: 'ex13',
            series: 'EX',
            printedTotal: 110,
            total: 111,
            ptcgoid: 'HP',
            releaseDate: new Date('2006/05/01'),
            logoUrl: 'https://images.pokemontcg.io/ex13/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex13/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Crystal Guardians',
            id: 'ex14',
            series: 'EX',
            printedTotal: 100,
            total: 100,
            ptcgoid: 'CG',
            releaseDate: new Date('2006/08/01'),
            logoUrl: 'https://images.pokemontcg.io/ex14/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex14/symbol.png'
        },
        {
            tcgId: 1,
            name: 'POP Series 4',
            id: 'pop4',
            series: 'POP',
            printedTotal: 17,
            total: 17,
            ptcgoid: undefined,
            releaseDate: new Date('2006/08/01'),
            logoUrl: 'https://images.pokemontcg.io/pop4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pop4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Dragon Frontiers',
            id: 'ex15',
            series: 'EX',
            printedTotal: 101,
            total: 101,
            ptcgoid: 'DF',
            releaseDate: new Date('2006/11/01'),
            logoUrl: 'https://images.pokemontcg.io/ex15/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex15/symbol.png'
        },
        {
            tcgId: 1,
            name: 'POP Series 5',
            id: 'pop5',
            series: 'POP',
            printedTotal: 17,
            total: 17,
            ptcgoid: undefined,
            releaseDate: new Date('2007/03/01'),
            logoUrl: 'https://images.pokemontcg.io/pop5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pop5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Power Keepers',
            id: 'ex16',
            series: 'EX',
            printedTotal: 108,
            total: 108,
            ptcgoid: 'PK',
            releaseDate: new Date('2007/02/02'),
            logoUrl: 'https://images.pokemontcg.io/ex16/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ex16/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Diamond & Pearl',
            id: 'dp1',
            series: 'Diamond & Pearl',
            printedTotal: 130,
            total: 130,
            ptcgoid: 'DP',
            releaseDate: new Date('2007/05/01'),
            logoUrl: 'https://images.pokemontcg.io/dp1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dp1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'DP Black Star Promos',
            id: 'dpp',
            series: 'Diamond & Pearl',
            printedTotal: 56,
            total: 56,
            ptcgoid: 'PR-DPP',
            releaseDate: new Date('2007/05/01'),
            logoUrl: 'https://images.pokemontcg.io/dpp/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dpp/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Mysterious Treasures',
            id: 'dp2',
            series: 'Diamond & Pearl',
            printedTotal: 123,
            total: 124,
            ptcgoid: 'MT',
            releaseDate: new Date('2007/08/01'),
            logoUrl: 'https://images.pokemontcg.io/dp2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dp2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'POP Series 6',
            id: 'pop6',
            series: 'POP',
            printedTotal: 17,
            total: 17,
            ptcgoid: undefined,
            releaseDate: new Date('2007/09/01'),
            logoUrl: 'https://images.pokemontcg.io/pop6/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pop6/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Secret Wonders',
            id: 'dp3',
            series: 'Diamond & Pearl',
            printedTotal: 132,
            total: 132,
            ptcgoid: 'SW',
            releaseDate: new Date('2007/11/01'),
            logoUrl: 'https://images.pokemontcg.io/dp3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dp3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Great Encounters',
            id: 'dp4',
            series: 'Diamond & Pearl',
            printedTotal: 106,
            total: 106,
            ptcgoid: 'GE',
            releaseDate: new Date('2008/02/01'),
            logoUrl: 'https://images.pokemontcg.io/dp4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dp4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'POP Series 7',
            id: 'pop7',
            series: 'POP',
            printedTotal: 17,
            total: 17,
            ptcgoid: undefined,
            releaseDate: new Date('2008/03/01'),
            logoUrl: 'https://images.pokemontcg.io/pop7/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pop7/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Majestic Dawn',
            id: 'dp5',
            series: 'Diamond & Pearl',
            printedTotal: 100,
            total: 100,
            ptcgoid: 'MD',
            releaseDate: new Date('2008/05/01'),
            logoUrl: 'https://images.pokemontcg.io/dp5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dp5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Legends Awakened',
            id: 'dp6',
            series: 'Diamond & Pearl',
            printedTotal: 146,
            total: 146,
            ptcgoid: 'LA',
            releaseDate: new Date('2008/08/01'),
            logoUrl: 'https://images.pokemontcg.io/dp6/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dp6/symbol.png'
        },
        {
            tcgId: 1,
            name: 'POP Series 8',
            id: 'pop8',
            series: 'POP',
            printedTotal: 17,
            total: 17,
            ptcgoid: undefined,
            releaseDate: new Date('2008/09/01'),
            logoUrl: 'https://images.pokemontcg.io/pop8/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pop8/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Stormfront',
            id: 'dp7',
            series: 'Diamond & Pearl',
            printedTotal: 100,
            total: 106,
            ptcgoid: 'SF',
            releaseDate: new Date('2008/11/01'),
            logoUrl: 'https://images.pokemontcg.io/dp7/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dp7/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Platinum',
            id: 'pl1',
            series: 'Platinum',
            printedTotal: 127,
            total: 133,
            ptcgoid: 'PL',
            releaseDate: new Date('2009/02/11'),
            logoUrl: 'https://images.pokemontcg.io/pl1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pl1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'POP Series 9',
            id: 'pop9',
            series: 'POP',
            printedTotal: 17,
            total: 17,
            ptcgoid: undefined,
            releaseDate: new Date('2009/03/01'),
            logoUrl: 'https://images.pokemontcg.io/pop9/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pop9/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Rising Rivals',
            id: 'pl2',
            series: 'Platinum',
            printedTotal: 111,
            total: 120,
            ptcgoid: 'RR',
            releaseDate: new Date('2009/05/16'),
            logoUrl: 'https://images.pokemontcg.io/pl2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pl2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Supreme Victors',
            id: 'pl3',
            series: 'Platinum',
            printedTotal: 147,
            total: 153,
            ptcgoid: 'SV',
            releaseDate: new Date('2009/08/19'),
            logoUrl: 'https://images.pokemontcg.io/pl3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pl3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Arceus',
            id: 'pl4',
            series: 'Platinum',
            printedTotal: 99,
            total: 111,
            ptcgoid: 'AR',
            releaseDate: new Date('2009/11/04'),
            logoUrl: 'https://images.pokemontcg.io/pl4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pl4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Pokémon Rumble',
            id: 'ru1',
            series: 'Other',
            printedTotal: 16,
            total: 16,
            ptcgoid: undefined,
            releaseDate: new Date('2009/12/02'),
            logoUrl: 'https://images.pokemontcg.io/ru1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/ru1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'HeartGold & SoulSilver',
            id: 'hgss1',
            series: 'HeartGold & SoulSilver',
            printedTotal: 123,
            total: 124,
            ptcgoid: 'HS',
            releaseDate: new Date('2010/02/10'),
            logoUrl: 'https://images.pokemontcg.io/hgss1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/hgss1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'HGSS Black Star Promos',
            id: 'hsp',
            series: 'HeartGold & SoulSilver',
            printedTotal: 25,
            total: 25,
            ptcgoid: 'PR-HS',
            releaseDate: new Date('2010/02/10'),
            logoUrl: 'https://images.pokemontcg.io/hsp/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/hsp/symbol.png'
        },
        {
            tcgId: 1,
            name: 'HS—Unleashed',
            id: 'hgss2',
            series: 'HeartGold & SoulSilver',
            printedTotal: 95,
            total: 96,
            ptcgoid: 'UL',
            releaseDate: new Date('2010/05/12'),
            logoUrl: 'https://images.pokemontcg.io/hgss2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/hgss2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'HS—Undaunted',
            id: 'hgss3',
            series: 'HeartGold & SoulSilver',
            printedTotal: 90,
            total: 91,
            ptcgoid: 'UD',
            releaseDate: new Date('2010/08/18'),
            logoUrl: 'https://images.pokemontcg.io/hgss3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/hgss3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'HS—Triumphant',
            id: 'hgss4',
            series: 'HeartGold & SoulSilver',
            printedTotal: 102,
            total: 103,
            ptcgoid: 'TM',
            releaseDate: new Date('2010/11/03'),
            logoUrl: 'https://images.pokemontcg.io/hgss4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/hgss4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Call of Legends',
            id: 'col1',
            series: 'HeartGold & SoulSilver',
            printedTotal: 95,
            total: 106,
            ptcgoid: 'CL',
            releaseDate: new Date('2011/02/09'),
            logoUrl: 'https://images.pokemontcg.io/col1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/col1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'BW Black Star Promos',
            id: 'bwp',
            series: 'Black & White',
            printedTotal: 101,
            total: 101,
            ptcgoid: 'PR-BLW',
            releaseDate: new Date('2011/03/01'),
            logoUrl: 'https://images.pokemontcg.io/bwp/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bwp/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Black & White',
            id: 'bw1',
            series: 'Black & White',
            printedTotal: 114,
            total: 115,
            ptcgoid: 'BLW',
            releaseDate: new Date('2011/04/25'),
            logoUrl: 'https://images.pokemontcg.io/bw1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw1/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2011",
            id: 'mcd11',
            series: 'Other',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2011/06/17'),
            logoUrl: 'https://images.pokemontcg.io/mcd11/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd11/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Emerging Powers',
            id: 'bw2',
            series: 'Black & White',
            printedTotal: 98,
            total: 98,
            ptcgoid: 'EPO',
            releaseDate: new Date('2011/08/31'),
            logoUrl: 'https://images.pokemontcg.io/bw2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Noble Victories',
            id: 'bw3',
            series: 'Black & White',
            printedTotal: 101,
            total: 102,
            ptcgoid: 'NVI',
            releaseDate: new Date('2011/11/16'),
            logoUrl: 'https://images.pokemontcg.io/bw3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Next Destinies',
            id: 'bw4',
            series: 'Black & White',
            printedTotal: 99,
            total: 103,
            ptcgoid: 'NXD',
            releaseDate: new Date('2012/02/08'),
            logoUrl: 'https://images.pokemontcg.io/bw4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Dark Explorers',
            id: 'bw5',
            series: 'Black & White',
            printedTotal: 108,
            total: 111,
            ptcgoid: 'DEX',
            releaseDate: new Date('2012/05/09'),
            logoUrl: 'https://images.pokemontcg.io/bw5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw5/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2012",
            id: 'mcd12',
            series: 'Other',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2012/06/15'),
            logoUrl: 'https://images.pokemontcg.io/mcd12/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd12/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Dragons Exalted',
            id: 'bw6',
            series: 'Black & White',
            printedTotal: 124,
            total: 128,
            ptcgoid: 'DRX',
            releaseDate: new Date('2012/08/15'),
            logoUrl: 'https://images.pokemontcg.io/bw6/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw6/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Dragon Vault',
            id: 'dv1',
            series: 'Black & White',
            printedTotal: 20,
            total: 21,
            ptcgoid: 'DRV',
            releaseDate: new Date('2012/10/05'),
            logoUrl: 'https://images.pokemontcg.io/dv1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dv1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Boundaries Crossed',
            id: 'bw7',
            series: 'Black & White',
            printedTotal: 149,
            total: 153,
            ptcgoid: 'BCR',
            releaseDate: new Date('2012/11/07'),
            logoUrl: 'https://images.pokemontcg.io/bw7/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw7/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Plasma Storm',
            id: 'bw8',
            series: 'Black & White',
            printedTotal: 135,
            total: 138,
            ptcgoid: 'PLS',
            releaseDate: new Date('2013/02/06'),
            logoUrl: 'https://images.pokemontcg.io/bw8/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw8/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Plasma Freeze',
            id: 'bw9',
            series: 'Black & White',
            printedTotal: 116,
            total: 122,
            ptcgoid: 'PLF',
            releaseDate: new Date('2013/05/08'),
            logoUrl: 'https://images.pokemontcg.io/bw9/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw9/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Plasma Blast',
            id: 'bw10',
            series: 'Black & White',
            printedTotal: 101,
            total: 105,
            ptcgoid: 'PLB',
            releaseDate: new Date('2013/08/14'),
            logoUrl: 'https://images.pokemontcg.io/bw10/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw10/symbol.png'
        },
        {
            tcgId: 1,
            name: 'XY Black Star Promos',
            id: 'xyp',
            series: 'XY',
            printedTotal: 211,
            total: 216,
            ptcgoid: 'PR-XY',
            releaseDate: new Date('2013/10/12'),
            logoUrl: 'https://images.pokemontcg.io/xyp/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xyp/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Legendary Treasures',
            id: 'bw11',
            series: 'Black & White',
            printedTotal: 113,
            total: 140,
            ptcgoid: 'LTR',
            releaseDate: new Date('2013/11/06'),
            logoUrl: 'https://images.pokemontcg.io/bw11/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/bw11/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Kalos Starter Set',
            id: 'xy0',
            series: 'XY',
            printedTotal: 39,
            total: 39,
            ptcgoid: 'KSS',
            releaseDate: new Date('2013/11/08'),
            logoUrl: 'https://images.pokemontcg.io/xy0/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy0/symbol.png'
        },
        {
            tcgId: 1,
            name: 'XY',
            id: 'xy1',
            series: 'XY',
            printedTotal: 146,
            total: 146,
            ptcgoid: 'XY',
            releaseDate: new Date('2014/02/05'),
            logoUrl: 'https://images.pokemontcg.io/xy1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Flashfire',
            id: 'xy2',
            series: 'XY',
            printedTotal: 106,
            total: 110,
            ptcgoid: 'FLF',
            releaseDate: new Date('2014/05/07'),
            logoUrl: 'https://images.pokemontcg.io/xy2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy2/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2014",
            id: 'mcd14',
            series: 'Other',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2014/05/23'),
            logoUrl: 'https://images.pokemontcg.io/mcd14/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd14/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Furious Fists',
            id: 'xy3',
            series: 'XY',
            printedTotal: 111,
            total: 114,
            ptcgoid: 'FFI',
            releaseDate: new Date('2014/08/13'),
            logoUrl: 'https://images.pokemontcg.io/xy3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Phantom Forces',
            id: 'xy4',
            series: 'XY',
            printedTotal: 119,
            total: 124,
            ptcgoid: 'PHF',
            releaseDate: new Date('2014/11/05'),
            logoUrl: 'https://images.pokemontcg.io/xy4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Primal Clash',
            id: 'xy5',
            series: 'XY',
            printedTotal: 160,
            total: 164,
            ptcgoid: 'PRC',
            releaseDate: new Date('2015/02/04'),
            logoUrl: 'https://images.pokemontcg.io/xy5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Double Crisis',
            id: 'dc1',
            series: 'XY',
            printedTotal: 34,
            total: 34,
            ptcgoid: 'DCR',
            releaseDate: new Date('2015/03/25'),
            logoUrl: 'https://images.pokemontcg.io/dc1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/dc1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Roaring Skies',
            id: 'xy6',
            series: 'XY',
            printedTotal: 108,
            total: 112,
            ptcgoid: 'ROS',
            releaseDate: new Date('2015/05/06'),
            logoUrl: 'https://images.pokemontcg.io/xy6/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy6/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Ancient Origins',
            id: 'xy7',
            series: 'XY',
            printedTotal: 98,
            total: 100,
            ptcgoid: 'AOR',
            releaseDate: new Date('2015/08/12'),
            logoUrl: 'https://images.pokemontcg.io/xy7/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy7/symbol.png'
        },
        {
            tcgId: 1,
            name: 'BREAKthrough',
            id: 'xy8',
            series: 'XY',
            printedTotal: 162,
            total: 165,
            ptcgoid: 'BKT',
            releaseDate: new Date('2015/11/04'),
            logoUrl: 'https://images.pokemontcg.io/xy8/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy8/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2015",
            id: 'mcd15',
            series: 'Other',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2015/11/27'),
            logoUrl: 'https://images.pokemontcg.io/mcd15/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd15/symbol.png'
        },
        {
            tcgId: 1,
            name: 'BREAKpoint',
            id: 'xy9',
            series: 'XY',
            printedTotal: 122,
            total: 126,
            ptcgoid: 'BKP',
            releaseDate: new Date('2016/02/03'),
            logoUrl: 'https://images.pokemontcg.io/xy9/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy9/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Generations',
            id: 'g1',
            series: 'XY',
            printedTotal: 83,
            total: 117,
            ptcgoid: 'GEN',
            releaseDate: new Date('2016/02/22'),
            logoUrl: 'https://images.pokemontcg.io/g1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/g1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Fates Collide',
            id: 'xy10',
            series: 'XY',
            printedTotal: 124,
            total: 129,
            ptcgoid: 'FCO',
            releaseDate: new Date('2016/05/02'),
            logoUrl: 'https://images.pokemontcg.io/xy10/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy10/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Steam Siege',
            id: 'xy11',
            series: 'XY',
            printedTotal: 114,
            total: 116,
            ptcgoid: 'STS',
            releaseDate: new Date('2016/08/03'),
            logoUrl: 'https://images.pokemontcg.io/xy11/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy11/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2016",
            id: 'mcd16',
            series: 'Other',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2016/08/19'),
            logoUrl: 'https://images.pokemontcg.io/mcd16/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd16/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Evolutions',
            id: 'xy12',
            series: 'XY',
            printedTotal: 108,
            total: 113,
            ptcgoid: 'EVO',
            releaseDate: new Date('2016/11/02'),
            logoUrl: 'https://images.pokemontcg.io/xy12/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/xy12/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Sun & Moon',
            id: 'sm1',
            series: 'Sun & Moon',
            printedTotal: 149,
            total: 173,
            ptcgoid: 'SUM',
            releaseDate: new Date('2017/02/03'),
            logoUrl: 'https://images.pokemontcg.io/sm1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'SM Black Star Promos',
            id: 'smp',
            series: 'Sun & Moon',
            printedTotal: 248,
            total: 250,
            ptcgoid: 'PR-SM',
            releaseDate: new Date('2017/02/03'),
            logoUrl: 'https://images.pokemontcg.io/smp/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/smp/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Guardians Rising',
            id: 'sm2',
            series: 'Sun & Moon',
            printedTotal: 145,
            total: 180,
            ptcgoid: 'GRI',
            releaseDate: new Date('2017/05/05'),
            logoUrl: 'https://images.pokemontcg.io/sm2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Burning Shadows',
            id: 'sm3',
            series: 'Sun & Moon',
            printedTotal: 147,
            total: 177,
            ptcgoid: 'BUS',
            releaseDate: new Date('2017/08/05'),
            logoUrl: 'https://images.pokemontcg.io/sm3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Shining Legends',
            id: 'sm35',
            series: 'Sun & Moon',
            printedTotal: 73,
            total: 81,
            ptcgoid: 'SLG',
            releaseDate: new Date('2017/10/06'),
            logoUrl: 'https://images.pokemontcg.io/sm35/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm35/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Crimson Invasion',
            id: 'sm4',
            series: 'Sun & Moon',
            printedTotal: 111,
            total: 126,
            ptcgoid: 'CIN',
            releaseDate: new Date('2017/11/03'),
            logoUrl: 'https://images.pokemontcg.io/sm4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm4/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2017",
            id: 'mcd17',
            series: 'Other',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2017/11/07'),
            logoUrl: 'https://images.pokemontcg.io/mcd17/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd17/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Ultra Prism',
            id: 'sm5',
            series: 'Sun & Moon',
            printedTotal: 156,
            total: 178,
            ptcgoid: 'UPR',
            releaseDate: new Date('2018/02/02'),
            logoUrl: 'https://images.pokemontcg.io/sm5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Forbidden Light',
            id: 'sm6',
            series: 'Sun & Moon',
            printedTotal: 131,
            total: 150,
            ptcgoid: 'FLI',
            releaseDate: new Date('2018/05/04'),
            logoUrl: 'https://images.pokemontcg.io/sm6/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm6/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Celestial Storm',
            id: 'sm7',
            series: 'Sun & Moon',
            printedTotal: 168,
            total: 187,
            ptcgoid: 'CES',
            releaseDate: new Date('2018/08/03'),
            logoUrl: 'https://images.pokemontcg.io/sm7/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm7/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Dragon Majesty',
            id: 'sm75',
            series: 'Sun & Moon',
            printedTotal: 70,
            total: 80,
            ptcgoid: 'DRM',
            releaseDate: new Date('2018/09/07'),
            logoUrl: 'https://images.pokemontcg.io/sm75/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm75/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2018",
            id: 'mcd18',
            series: 'Other',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2018/10/16'),
            logoUrl: 'https://images.pokemontcg.io/mcd18/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd18/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Lost Thunder',
            id: 'sm8',
            series: 'Sun & Moon',
            printedTotal: 214,
            total: 240,
            ptcgoid: 'LOT',
            releaseDate: new Date('2018/11/02'),
            logoUrl: 'https://images.pokemontcg.io/sm8/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm8/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Team Up',
            id: 'sm9',
            series: 'Sun & Moon',
            printedTotal: 181,
            total: 198,
            ptcgoid: 'TEU',
            releaseDate: new Date('2019/02/01'),
            logoUrl: 'https://images.pokemontcg.io/sm9/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm9/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Detective Pikachu',
            id: 'det1',
            series: 'Sun & Moon',
            printedTotal: 18,
            total: 18,
            ptcgoid: 'DET',
            releaseDate: new Date('2019/04/05'),
            logoUrl: 'https://images.pokemontcg.io/det1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/det1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Unbroken Bonds',
            id: 'sm10',
            series: 'Sun & Moon',
            printedTotal: 214,
            total: 234,
            ptcgoid: 'UNB',
            releaseDate: new Date('2019/05/03'),
            logoUrl: 'https://images.pokemontcg.io/sm10/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm10/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Unified Minds',
            id: 'sm11',
            series: 'Sun & Moon',
            printedTotal: 236,
            total: 260,
            ptcgoid: 'UNM',
            releaseDate: new Date('2019/08/02'),
            logoUrl: 'https://images.pokemontcg.io/sm11/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm11/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Hidden Fates',
            id: 'sm115',
            series: 'Sun & Moon',
            printedTotal: 68,
            total: 69,
            ptcgoid: 'HIF',
            releaseDate: new Date('2019/08/23'),
            logoUrl: 'https://images.pokemontcg.io/sm115/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm115/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Hidden Fates Shiny Vault',
            id: 'sma',
            series: 'Sun & Moon',
            printedTotal: 94,
            total: 94,
            ptcgoid: 'HIF',
            releaseDate: new Date('2019/08/23'),
            logoUrl: 'https://images.pokemontcg.io/sma/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sma/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2019",
            id: 'mcd19',
            series: 'Other',
            printedTotal: 12,
            total: 12,
            ptcgoid: undefined,
            releaseDate: new Date('2019/10/15'),
            logoUrl: 'https://images.pokemontcg.io/mcd19/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd19/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Cosmic Eclipse',
            id: 'sm12',
            series: 'Sun & Moon',
            printedTotal: 236,
            total: 272,
            ptcgoid: 'CEC',
            releaseDate: new Date('2019/11/01'),
            logoUrl: 'https://images.pokemontcg.io/sm12/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sm12/symbol.png'
        },
        {
            tcgId: 1,
            name: 'SWSH Black Star Promos',
            id: 'swshp',
            series: 'Sword & Shield',
            printedTotal: 307,
            total: 304,
            ptcgoid: 'PR-SW',
            releaseDate: new Date('2019/11/15'),
            logoUrl: 'https://images.pokemontcg.io/swshp/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swshp/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Sword & Shield',
            id: 'swsh1',
            series: 'Sword & Shield',
            printedTotal: 202,
            total: 216,
            ptcgoid: 'SSH',
            releaseDate: new Date('2020/02/07'),
            logoUrl: 'https://images.pokemontcg.io/swsh1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Rebel Clash',
            id: 'swsh2',
            series: 'Sword & Shield',
            printedTotal: 192,
            total: 209,
            ptcgoid: 'RCL',
            releaseDate: new Date('2020/05/01'),
            logoUrl: 'https://images.pokemontcg.io/swsh2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Darkness Ablaze',
            id: 'swsh3',
            series: 'Sword & Shield',
            printedTotal: 189,
            total: 201,
            ptcgoid: 'DAA',
            releaseDate: new Date('2020/08/14'),
            logoUrl: 'https://images.pokemontcg.io/swsh3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh3/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Pokémon Futsal Collection',
            id: 'fut20',
            series: 'Other',
            printedTotal: 5,
            total: 5,
            ptcgoid: 'FUT20',
            releaseDate: new Date('2020/09/11'),
            logoUrl: 'https://images.pokemontcg.io/fut20/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/fut20/symbol.png'
        },
        {
            tcgId: 1,
            name: "Champion's Path",
            id: 'swsh35',
            series: 'Sword & Shield',
            printedTotal: 73,
            total: 80,
            ptcgoid: 'CPA',
            releaseDate: new Date('2020/09/25'),
            logoUrl: 'https://images.pokemontcg.io/swsh35/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh35/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Vivid Voltage',
            id: 'swsh4',
            series: 'Sword & Shield',
            printedTotal: 185,
            total: 203,
            ptcgoid: 'VIV',
            releaseDate: new Date('2020/11/13'),
            logoUrl: 'https://images.pokemontcg.io/swsh4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Shining Fates',
            id: 'swsh45',
            series: 'Sword & Shield',
            printedTotal: 72,
            total: 73,
            ptcgoid: 'SHF',
            releaseDate: new Date('2021/02/19'),
            logoUrl: 'https://images.pokemontcg.io/swsh45/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh45/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Shining Fates Shiny Vault',
            id: 'swsh45sv',
            series: 'Sword & Shield',
            printedTotal: 122,
            total: 122,
            ptcgoid: 'SHF',
            releaseDate: new Date('2021/02/19'),
            logoUrl: 'https://images.pokemontcg.io/swsh45sv/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh45sv/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Battle Styles',
            id: 'swsh5',
            series: 'Sword & Shield',
            printedTotal: 163,
            total: 183,
            ptcgoid: 'BST',
            releaseDate: new Date('2021/03/19'),
            logoUrl: 'https://images.pokemontcg.io/swsh5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Chilling Reign',
            id: 'swsh6',
            series: 'Sword & Shield',
            printedTotal: 198,
            total: 233,
            ptcgoid: 'CRE',
            releaseDate: new Date('2021/06/18'),
            logoUrl: 'https://images.pokemontcg.io/swsh6/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh6/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Evolving Skies',
            id: 'swsh7',
            series: 'Sword & Shield',
            printedTotal: 203,
            total: 237,
            ptcgoid: 'EVS',
            releaseDate: new Date('2021/08/27'),
            logoUrl: 'https://images.pokemontcg.io/swsh7/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh7/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2021",
            id: 'mcd21',
            series: 'Other',
            printedTotal: 25,
            total: 25,
            ptcgoid: undefined,
            releaseDate: new Date('2021/02/09'),
            logoUrl: 'https://images.pokemontcg.io/mcd21/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd21/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Celebrations',
            id: 'cel25',
            series: 'Sword & Shield',
            printedTotal: 25,
            total: 25,
            ptcgoid: 'CEL',
            releaseDate: new Date('2021/10/08'),
            logoUrl: 'https://images.pokemontcg.io/cel25/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/cel25/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Celebrations: Classic Collection',
            id: 'cel25c',
            series: 'Sword & Shield',
            printedTotal: 25,
            total: 25,
            ptcgoid: 'CEL',
            releaseDate: new Date('2021/10/08'),
            logoUrl: 'https://images.pokemontcg.io/cel25c/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/cel25c/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Fusion Strike',
            id: 'swsh8',
            series: 'Sword & Shield',
            printedTotal: 264,
            total: 284,
            ptcgoid: 'FST',
            releaseDate: new Date('2021/11/12'),
            logoUrl: 'https://images.pokemontcg.io/swsh8/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh8/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Brilliant Stars',
            id: 'swsh9',
            series: 'Sword & Shield',
            printedTotal: 172,
            total: 186,
            ptcgoid: 'BRS',
            releaseDate: new Date('2022/02/25'),
            logoUrl: 'https://images.pokemontcg.io/swsh9/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh9/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Brilliant Stars Trainer Gallery',
            id: 'swsh9tg',
            series: 'Sword & Shield',
            printedTotal: 30,
            total: 30,
            ptcgoid: 'BRS',
            releaseDate: new Date('2022/02/25'),
            logoUrl: 'https://images.pokemontcg.io/swsh9tg/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh9tg/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Astral Radiance',
            id: 'swsh10',
            series: 'Sword & Shield',
            printedTotal: 189,
            total: 216,
            ptcgoid: 'ASR',
            releaseDate: new Date('2022/05/27'),
            logoUrl: 'https://images.pokemontcg.io/swsh10/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh10/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Astral Radiance Trainer Gallery',
            id: 'swsh10tg',
            series: 'Sword & Shield',
            printedTotal: 30,
            total: 30,
            ptcgoid: 'ASR',
            releaseDate: new Date('2022/05/27'),
            logoUrl: 'https://images.pokemontcg.io/swsh10tg/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh10tg/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Pokémon GO',
            id: 'pgo',
            series: 'Sword & Shield',
            printedTotal: 78,
            total: 88,
            ptcgoid: 'PGO',
            releaseDate: new Date('2022/07/01'),
            logoUrl: 'https://images.pokemontcg.io/pgo/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/pgo/symbol.png'
        },
        {
            tcgId: 1,
            name: "McDonald's Collection 2022",
            id: 'mcd22',
            series: 'Other',
            printedTotal: 15,
            total: 15,
            ptcgoid: undefined,
            releaseDate: new Date('2022/08/03'),
            logoUrl: 'https://images.pokemontcg.io/mcd22/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/mcd22/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Lost Origin',
            id: 'swsh11',
            series: 'Sword & Shield',
            printedTotal: 196,
            total: 217,
            ptcgoid: 'LOR',
            releaseDate: new Date('2022/09/09'),
            logoUrl: 'https://images.pokemontcg.io/swsh11/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh11/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Lost Origin Trainer Gallery',
            id: 'swsh11tg',
            series: 'Sword & Shield',
            printedTotal: 30,
            total: 30,
            ptcgoid: 'LOR',
            releaseDate: new Date('2022/09/09'),
            logoUrl: 'https://images.pokemontcg.io/swsh11tg/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh11tg/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Silver Tempest',
            id: 'swsh12',
            series: 'Sword & Shield',
            printedTotal: 195,
            total: 215,
            ptcgoid: 'SIT',
            releaseDate: new Date('2022/11/11'),
            logoUrl: 'https://images.pokemontcg.io/swsh12/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh12/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Silver Tempest Trainer Gallery',
            id: 'swsh12tg',
            series: 'Sword & Shield',
            printedTotal: 30,
            total: 30,
            ptcgoid: 'SIT',
            releaseDate: new Date('2022/11/11'),
            logoUrl: 'https://images.pokemontcg.io/swsh12tg/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh12tg/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Crown Zenith',
            id: 'swsh12pt5',
            series: 'Sword & Shield',
            printedTotal: 159,
            total: 160,
            ptcgoid: 'CRZ',
            releaseDate: new Date('2023/01/20'),
            logoUrl: 'https://images.pokemontcg.io/swsh12pt5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh12pt5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Crown Zenith Galarian Gallery',
            id: 'swsh12pt5gg',
            series: 'Sword & Shield',
            printedTotal: 70,
            total: 70,
            ptcgoid: 'CRZ',
            releaseDate: new Date('2023/01/20'),
            logoUrl: 'https://images.pokemontcg.io/swsh12pt5gg/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/swsh12pt5gg/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Scarlet & Violet Black Star Promos',
            id: 'svp',
            series: 'Scarlet & Violet',
            printedTotal: 102,
            total: 75,
            ptcgoid: 'PR-SV',
            releaseDate: new Date('2023/01/01'),
            logoUrl: 'https://images.pokemontcg.io/svp/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/svp/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Scarlet & Violet Energies',
            id: 'sve',
            series: 'Scarlet & Violet',
            printedTotal: 8,
            total: 8,
            ptcgoid: 'SVE',
            releaseDate: new Date('2023/03/31'),
            logoUrl: 'https://images.pokemontcg.io/sve/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sve/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Scarlet & Violet',
            id: 'sv1',
            series: 'Scarlet & Violet',
            printedTotal: 198,
            total: 258,
            ptcgoid: 'SVI',
            releaseDate: new Date('2023/03/31'),
            logoUrl: 'https://images.pokemontcg.io/sv1/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv1/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Paldea Evolved',
            id: 'sv2',
            series: 'Scarlet & Violet',
            printedTotal: 193,
            total: 279,
            ptcgoid: 'PAL',
            releaseDate: new Date('2023/06/09'),
            logoUrl: 'https://images.pokemontcg.io/sv2/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv2/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Obsidian Flames',
            id: 'sv3',
            series: 'Scarlet & Violet',
            printedTotal: 197,
            total: 230,
            ptcgoid: 'OBF',
            releaseDate: new Date('2023/08/11'),
            logoUrl: 'https://images.pokemontcg.io/sv3/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv3/symbol.png'
        },
        {
            tcgId: 1,
            name: '151',
            id: 'sv3pt5',
            series: 'Scarlet & Violet',
            printedTotal: 165,
            total: 207,
            ptcgoid: 'MEW',
            releaseDate: new Date('2023/09/22'),
            logoUrl: 'https://images.pokemontcg.io/sv3pt5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv3pt5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Paradox Rift',
            id: 'sv4',
            series: 'Scarlet & Violet',
            printedTotal: 182,
            total: 266,
            ptcgoid: 'PAR',
            releaseDate: new Date('2023/11/03'),
            logoUrl: 'https://images.pokemontcg.io/sv4/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv4/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Paldean Fates',
            id: 'sv4pt5',
            series: 'Scarlet & Violet',
            printedTotal: 91,
            total: 245,
            ptcgoid: 'PAF',
            releaseDate: new Date('2024/01/26'),
            logoUrl: 'https://images.pokemontcg.io/sv4pt5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv4pt5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Temporal Forces',
            id: 'sv5',
            series: 'Scarlet & Violet',
            printedTotal: 162,
            total: 218,
            ptcgoid: 'TEF',
            releaseDate: new Date('2024/03/22'),
            logoUrl: 'https://images.pokemontcg.io/sv5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Twilight Masquerade',
            id: 'sv6',
            series: 'Scarlet & Violet',
            printedTotal: 167,
            total: 226,
            ptcgoid: 'TWM',
            releaseDate: new Date('2024/05/24'),
            logoUrl: 'https://images.pokemontcg.io/sv6/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv6/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Shrouded Fable',
            id: 'sv6pt5',
            series: 'Scarlet & Violet',
            printedTotal: 64,
            total: 99,
            ptcgoid: 'SFA',
            releaseDate: new Date('2024/08/02'),
            logoUrl: 'https://images.pokemontcg.io/sv6pt5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv6pt5/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Stellar Crown',
            id: 'sv7',
            series: 'Scarlet & Violet',
            printedTotal: 142,
            total: 175,
            ptcgoid: 'SCR',
            releaseDate: new Date('2024/09/13'),
            logoUrl: 'https://images.pokemontcg.io/sv7/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv7/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Surging Sparks',
            id: 'sv8',
            series: 'Scarlet & Violet',
            printedTotal: 191,
            total: 252,
            ptcgoid: 'SSP',
            releaseDate: new Date('2024/11/08'),
            logoUrl: 'https://images.pokemontcg.io/sv8/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv8/symbol.png'
        },
        {
            tcgId: 1,
            name: 'Prismatic Evolutions',
            id: 'sv8pt5',
            series: 'Scarlet & Violet',
            printedTotal: 131,
            total: 180,
            ptcgoid: 'PRE',
            releaseDate: new Date('2025/01/17'),
            logoUrl: 'https://images.pokemontcg.io/sv8pt5/logo.png',
            symbolUrl: 'https://images.pokemontcg.io/sv8pt5/symbol.png'
        }
    ]
