export const cardSeedBase5 = [
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Alakazam',
    tcgApiId: 'base5-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/1.png","large":"https://images.pokemontcg.io/base5/1_hires.png"}',
    searchName: 'Dark Alakazam (TR 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Arbok',
    tcgApiId: 'base5-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/2.png","large":"https://images.pokemontcg.io/base5/2_hires.png"}',
    searchName: 'Dark Arbok (TR 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Blastoise',
    tcgApiId: 'base5-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/3.png","large":"https://images.pokemontcg.io/base5/3_hires.png"}',
    searchName: 'Dark Blastoise (TR 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Charizard',
    tcgApiId: 'base5-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/4.png","large":"https://images.pokemontcg.io/base5/4_hires.png"}',
    searchName: 'Dark Charizard (TR 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Dragonite',
    tcgApiId: 'base5-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/5.png","large":"https://images.pokemontcg.io/base5/5_hires.png"}',
    searchName: 'Dark Dragonite (TR 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Dugtrio',
    tcgApiId: 'base5-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/6.png","large":"https://images.pokemontcg.io/base5/6_hires.png"}',
    searchName: 'Dark Dugtrio (TR 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Golbat',
    tcgApiId: 'base5-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/7.png","large":"https://images.pokemontcg.io/base5/7_hires.png"}',
    searchName: 'Dark Golbat (TR 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Gyarados',
    tcgApiId: 'base5-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/8.png","large":"https://images.pokemontcg.io/base5/8_hires.png"}',
    searchName: 'Dark Gyarados (TR 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Hypno',
    tcgApiId: 'base5-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/9.png","large":"https://images.pokemontcg.io/base5/9_hires.png"}',
    searchName: 'Dark Hypno (TR 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Machamp',
    tcgApiId: 'base5-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/10.png","large":"https://images.pokemontcg.io/base5/10_hires.png"}',
    searchName: 'Dark Machamp (TR 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Magneton',
    tcgApiId: 'base5-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/11.png","large":"https://images.pokemontcg.io/base5/11_hires.png"}',
    searchName: 'Dark Magneton (TR 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Slowbro',
    tcgApiId: 'base5-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/12.png","large":"https://images.pokemontcg.io/base5/12_hires.png"}',
    searchName: 'Dark Slowbro (TR 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Vileplume',
    tcgApiId: 'base5-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/13.png","large":"https://images.pokemontcg.io/base5/13_hires.png"}',
    searchName: 'Dark Vileplume (TR 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Weezing',
    tcgApiId: 'base5-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/14.png","large":"https://images.pokemontcg.io/base5/14_hires.png"}',
    searchName: 'Dark Weezing (TR 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Here Comes Team Rocket!',
    tcgApiId: 'base5-15',
    number: '15',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/15.png","large":"https://images.pokemontcg.io/base5/15_hires.png"}',
    searchName: 'Here Comes Team Rocket! (TR 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: "Rocket's Sneak Attack",
    tcgApiId: 'base5-16',
    number: '16',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/16.png","large":"https://images.pokemontcg.io/base5/16_hires.png"}',
    searchName: "Rocket's Sneak Attack (TR 16)",
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Rainbow Energy',
    tcgApiId: 'base5-17',
    number: '17',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/base5/17.png","large":"https://images.pokemontcg.io/base5/17_hires.png"}',
    searchName: 'Rainbow Energy (TR 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Alakazam',
    tcgApiId: 'base5-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/18.png","large":"https://images.pokemontcg.io/base5/18_hires.png"}',
    searchName: 'Dark Alakazam (TR 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Arbok',
    tcgApiId: 'base5-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/19.png","large":"https://images.pokemontcg.io/base5/19_hires.png"}',
    searchName: 'Dark Arbok (TR 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Blastoise',
    tcgApiId: 'base5-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/20.png","large":"https://images.pokemontcg.io/base5/20_hires.png"}',
    searchName: 'Dark Blastoise (TR 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Charizard',
    tcgApiId: 'base5-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/21.png","large":"https://images.pokemontcg.io/base5/21_hires.png"}',
    searchName: 'Dark Charizard (TR 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Dragonite',
    tcgApiId: 'base5-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/22.png","large":"https://images.pokemontcg.io/base5/22_hires.png"}',
    searchName: 'Dark Dragonite (TR 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Dugtrio',
    tcgApiId: 'base5-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/23.png","large":"https://images.pokemontcg.io/base5/23_hires.png"}',
    searchName: 'Dark Dugtrio (TR 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Golbat',
    tcgApiId: 'base5-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/24.png","large":"https://images.pokemontcg.io/base5/24_hires.png"}',
    searchName: 'Dark Golbat (TR 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Gyarados',
    tcgApiId: 'base5-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/25.png","large":"https://images.pokemontcg.io/base5/25_hires.png"}',
    searchName: 'Dark Gyarados (TR 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Hypno',
    tcgApiId: 'base5-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/26.png","large":"https://images.pokemontcg.io/base5/26_hires.png"}',
    searchName: 'Dark Hypno (TR 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Machamp',
    tcgApiId: 'base5-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/27.png","large":"https://images.pokemontcg.io/base5/27_hires.png"}',
    searchName: 'Dark Machamp (TR 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Magneton',
    tcgApiId: 'base5-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/28.png","large":"https://images.pokemontcg.io/base5/28_hires.png"}',
    searchName: 'Dark Magneton (TR 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Slowbro',
    tcgApiId: 'base5-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/29.png","large":"https://images.pokemontcg.io/base5/29_hires.png"}',
    searchName: 'Dark Slowbro (TR 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Vileplume',
    tcgApiId: 'base5-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/30.png","large":"https://images.pokemontcg.io/base5/30_hires.png"}',
    searchName: 'Dark Vileplume (TR 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Weezing',
    tcgApiId: 'base5-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/31.png","large":"https://images.pokemontcg.io/base5/31_hires.png"}',
    searchName: 'Dark Weezing (TR 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Charmeleon',
    tcgApiId: 'base5-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/32.png","large":"https://images.pokemontcg.io/base5/32_hires.png"}',
    searchName: 'Dark Charmeleon (TR 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Dragonair',
    tcgApiId: 'base5-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/33.png","large":"https://images.pokemontcg.io/base5/33_hires.png"}',
    searchName: 'Dark Dragonair (TR 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Electrode',
    tcgApiId: 'base5-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/34.png","large":"https://images.pokemontcg.io/base5/34_hires.png"}',
    searchName: 'Dark Electrode (TR 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Flareon',
    tcgApiId: 'base5-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/35.png","large":"https://images.pokemontcg.io/base5/35_hires.png"}',
    searchName: 'Dark Flareon (TR 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Gloom',
    tcgApiId: 'base5-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/36.png","large":"https://images.pokemontcg.io/base5/36_hires.png"}',
    searchName: 'Dark Gloom (TR 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Golduck',
    tcgApiId: 'base5-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/37.png","large":"https://images.pokemontcg.io/base5/37_hires.png"}',
    searchName: 'Dark Golduck (TR 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Jolteon',
    tcgApiId: 'base5-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/38.png","large":"https://images.pokemontcg.io/base5/38_hires.png"}',
    searchName: 'Dark Jolteon (TR 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Kadabra',
    tcgApiId: 'base5-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/39.png","large":"https://images.pokemontcg.io/base5/39_hires.png"}',
    searchName: 'Dark Kadabra (TR 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Machoke',
    tcgApiId: 'base5-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/40.png","large":"https://images.pokemontcg.io/base5/40_hires.png"}',
    searchName: 'Dark Machoke (TR 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Muk',
    tcgApiId: 'base5-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/41.png","large":"https://images.pokemontcg.io/base5/41_hires.png"}',
    searchName: 'Dark Muk (TR 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Persian',
    tcgApiId: 'base5-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/42.png","large":"https://images.pokemontcg.io/base5/42_hires.png"}',
    searchName: 'Dark Persian (TR 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Primeape',
    tcgApiId: 'base5-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/43.png","large":"https://images.pokemontcg.io/base5/43_hires.png"}',
    searchName: 'Dark Primeape (TR 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Rapidash',
    tcgApiId: 'base5-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/44.png","large":"https://images.pokemontcg.io/base5/44_hires.png"}',
    searchName: 'Dark Rapidash (TR 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Vaporeon',
    tcgApiId: 'base5-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/45.png","large":"https://images.pokemontcg.io/base5/45_hires.png"}',
    searchName: 'Dark Vaporeon (TR 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Wartortle',
    tcgApiId: 'base5-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/46.png","large":"https://images.pokemontcg.io/base5/46_hires.png"}',
    searchName: 'Dark Wartortle (TR 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Magikarp',
    tcgApiId: 'base5-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/47.png","large":"https://images.pokemontcg.io/base5/47_hires.png"}',
    searchName: 'Magikarp (TR 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Porygon',
    tcgApiId: 'base5-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/48.png","large":"https://images.pokemontcg.io/base5/48_hires.png"}',
    searchName: 'Porygon (TR 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Abra',
    tcgApiId: 'base5-49',
    number: '49',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/49.png","large":"https://images.pokemontcg.io/base5/49_hires.png"}',
    searchName: 'Abra (TR 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Charmander',
    tcgApiId: 'base5-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/50.png","large":"https://images.pokemontcg.io/base5/50_hires.png"}',
    searchName: 'Charmander (TR 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Raticate',
    tcgApiId: 'base5-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/51.png","large":"https://images.pokemontcg.io/base5/51_hires.png"}',
    searchName: 'Dark Raticate (TR 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Diglett',
    tcgApiId: 'base5-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/52.png","large":"https://images.pokemontcg.io/base5/52_hires.png"}',
    searchName: 'Diglett (TR 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dratini',
    tcgApiId: 'base5-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/53.png","large":"https://images.pokemontcg.io/base5/53_hires.png"}',
    searchName: 'Dratini (TR 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Drowzee',
    tcgApiId: 'base5-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/54.png","large":"https://images.pokemontcg.io/base5/54_hires.png"}',
    searchName: 'Drowzee (TR 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Eevee',
    tcgApiId: 'base5-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/55.png","large":"https://images.pokemontcg.io/base5/55_hires.png"}',
    searchName: 'Eevee (TR 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Ekans',
    tcgApiId: 'base5-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/56.png","large":"https://images.pokemontcg.io/base5/56_hires.png"}',
    searchName: 'Ekans (TR 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Grimer',
    tcgApiId: 'base5-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/57.png","large":"https://images.pokemontcg.io/base5/57_hires.png"}',
    searchName: 'Grimer (TR 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Koffing',
    tcgApiId: 'base5-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/58.png","large":"https://images.pokemontcg.io/base5/58_hires.png"}',
    searchName: 'Koffing (TR 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Machop',
    tcgApiId: 'base5-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/59.png","large":"https://images.pokemontcg.io/base5/59_hires.png"}',
    searchName: 'Machop (TR 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Magnemite',
    tcgApiId: 'base5-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/60.png","large":"https://images.pokemontcg.io/base5/60_hires.png"}',
    searchName: 'Magnemite (TR 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Mankey',
    tcgApiId: 'base5-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/61.png","large":"https://images.pokemontcg.io/base5/61_hires.png"}',
    searchName: 'Mankey (TR 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Meowth',
    tcgApiId: 'base5-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/62.png","large":"https://images.pokemontcg.io/base5/62_hires.png"}',
    searchName: 'Meowth (TR 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Oddish',
    tcgApiId: 'base5-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/63.png","large":"https://images.pokemontcg.io/base5/63_hires.png"}',
    searchName: 'Oddish (TR 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Ponyta',
    tcgApiId: 'base5-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/64.png","large":"https://images.pokemontcg.io/base5/64_hires.png"}',
    searchName: 'Ponyta (TR 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Psyduck',
    tcgApiId: 'base5-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/65.png","large":"https://images.pokemontcg.io/base5/65_hires.png"}',
    searchName: 'Psyduck (TR 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Rattata',
    tcgApiId: 'base5-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/66.png","large":"https://images.pokemontcg.io/base5/66_hires.png"}',
    searchName: 'Rattata (TR 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Slowpoke',
    tcgApiId: 'base5-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/67.png","large":"https://images.pokemontcg.io/base5/67_hires.png"}',
    searchName: 'Slowpoke (TR 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Squirtle',
    tcgApiId: 'base5-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/68.png","large":"https://images.pokemontcg.io/base5/68_hires.png"}',
    searchName: 'Squirtle (TR 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Voltorb',
    tcgApiId: 'base5-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/69.png","large":"https://images.pokemontcg.io/base5/69_hires.png"}',
    searchName: 'Voltorb (TR 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Zubat',
    tcgApiId: 'base5-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/70.png","large":"https://images.pokemontcg.io/base5/70_hires.png"}',
    searchName: 'Zubat (TR 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Here Comes Team Rocket!',
    tcgApiId: 'base5-71',
    number: '71',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/71.png","large":"https://images.pokemontcg.io/base5/71_hires.png"}',
    searchName: 'Here Comes Team Rocket! (TR 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: "Rocket's Sneak Attack",
    tcgApiId: 'base5-72',
    number: '72',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/72.png","large":"https://images.pokemontcg.io/base5/72_hires.png"}',
    searchName: "Rocket's Sneak Attack (TR 72)",
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: "The Boss's Way",
    tcgApiId: 'base5-73',
    number: '73',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/73.png","large":"https://images.pokemontcg.io/base5/73_hires.png"}',
    searchName: "The Boss's Way (TR 73)",
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Challenge!',
    tcgApiId: 'base5-74',
    number: '74',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/74.png","large":"https://images.pokemontcg.io/base5/74_hires.png"}',
    searchName: 'Challenge! (TR 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Digger',
    tcgApiId: 'base5-75',
    number: '75',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/75.png","large":"https://images.pokemontcg.io/base5/75_hires.png"}',
    searchName: 'Digger (TR 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: "Imposter Oak's Revenge",
    tcgApiId: 'base5-76',
    number: '76',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/76.png","large":"https://images.pokemontcg.io/base5/76_hires.png"}',
    searchName: "Imposter Oak's Revenge (TR 76)",
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Nightly Garbage Run',
    tcgApiId: 'base5-77',
    number: '77',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/77.png","large":"https://images.pokemontcg.io/base5/77_hires.png"}',
    searchName: 'Nightly Garbage Run (TR 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Goop Gas Attack',
    tcgApiId: 'base5-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/78.png","large":"https://images.pokemontcg.io/base5/78_hires.png"}',
    searchName: 'Goop Gas Attack (TR 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Sleep!',
    tcgApiId: 'base5-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/base5/79.png","large":"https://images.pokemontcg.io/base5/79_hires.png"}',
    searchName: 'Sleep! (TR 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Rainbow Energy',
    tcgApiId: 'base5-80',
    number: '80',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/base5/80.png","large":"https://images.pokemontcg.io/base5/80_hires.png"}',
    searchName: 'Rainbow Energy (TR 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Full Heal Energy',
    tcgApiId: 'base5-81',
    number: '81',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/81.png","large":"https://images.pokemontcg.io/base5/81_hires.png"}',
    searchName: 'Full Heal Energy (TR 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Potion Energy',
    tcgApiId: 'base5-82',
    number: '82',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/base5/82.png","large":"https://images.pokemontcg.io/base5/82_hires.png"}',
    searchName: 'Potion Energy (TR 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'base5',
    name: 'Dark Raichu',
    tcgApiId: 'base5-83',
    number: '83',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/base5/83.png","large":"https://images.pokemontcg.io/base5/83_hires.png"}',
    searchName: 'Dark Raichu (TR 83)',
  },
];
