export const cardSeedBw1 = [
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Snivy',
    tcgApiId: 'bw1-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/1.png","large":"https://images.pokemontcg.io/bw1/1_hires.png"}',
    searchName: 'Snivy (BLW 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Snivy',
    tcgApiId: 'bw1-2',
    number: '2',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/2.png","large":"https://images.pokemontcg.io/bw1/2_hires.png"}',
    searchName: 'Snivy (BLW 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Servine',
    tcgApiId: 'bw1-3',
    number: '3',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/3.png","large":"https://images.pokemontcg.io/bw1/3_hires.png"}',
    searchName: 'Servine (BLW 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Servine',
    tcgApiId: 'bw1-4',
    number: '4',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/4.png","large":"https://images.pokemontcg.io/bw1/4_hires.png"}',
    searchName: 'Servine (BLW 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Serperior',
    tcgApiId: 'bw1-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/5.png","large":"https://images.pokemontcg.io/bw1/5_hires.png"}',
    searchName: 'Serperior (BLW 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Serperior',
    tcgApiId: 'bw1-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/6.png","large":"https://images.pokemontcg.io/bw1/6_hires.png"}',
    searchName: 'Serperior (BLW 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Pansage',
    tcgApiId: 'bw1-7',
    number: '7',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/7.png","large":"https://images.pokemontcg.io/bw1/7_hires.png"}',
    searchName: 'Pansage (BLW 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Simisage',
    tcgApiId: 'bw1-8',
    number: '8',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/8.png","large":"https://images.pokemontcg.io/bw1/8_hires.png"}',
    searchName: 'Simisage (BLW 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Petilil',
    tcgApiId: 'bw1-9',
    number: '9',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/9.png","large":"https://images.pokemontcg.io/bw1/9_hires.png"}',
    searchName: 'Petilil (BLW 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Lilligant',
    tcgApiId: 'bw1-10',
    number: '10',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/10.png","large":"https://images.pokemontcg.io/bw1/10_hires.png"}',
    searchName: 'Lilligant (BLW 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Maractus',
    tcgApiId: 'bw1-11',
    number: '11',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/11.png","large":"https://images.pokemontcg.io/bw1/11_hires.png"}',
    searchName: 'Maractus (BLW 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Maractus',
    tcgApiId: 'bw1-12',
    number: '12',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/12.png","large":"https://images.pokemontcg.io/bw1/12_hires.png"}',
    searchName: 'Maractus (BLW 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Deerling',
    tcgApiId: 'bw1-13',
    number: '13',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/13.png","large":"https://images.pokemontcg.io/bw1/13_hires.png"}',
    searchName: 'Deerling (BLW 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Sawsbuck',
    tcgApiId: 'bw1-14',
    number: '14',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/14.png","large":"https://images.pokemontcg.io/bw1/14_hires.png"}',
    searchName: 'Sawsbuck (BLW 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Tepig',
    tcgApiId: 'bw1-15',
    number: '15',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/15.png","large":"https://images.pokemontcg.io/bw1/15_hires.png"}',
    searchName: 'Tepig (BLW 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Tepig',
    tcgApiId: 'bw1-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/16.png","large":"https://images.pokemontcg.io/bw1/16_hires.png"}',
    searchName: 'Tepig (BLW 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Pignite',
    tcgApiId: 'bw1-17',
    number: '17',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/17.png","large":"https://images.pokemontcg.io/bw1/17_hires.png"}',
    searchName: 'Pignite (BLW 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Pignite',
    tcgApiId: 'bw1-18',
    number: '18',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/18.png","large":"https://images.pokemontcg.io/bw1/18_hires.png"}',
    searchName: 'Pignite (BLW 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Emboar',
    tcgApiId: 'bw1-19',
    number: '19',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/19.png","large":"https://images.pokemontcg.io/bw1/19_hires.png"}',
    searchName: 'Emboar (BLW 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Emboar',
    tcgApiId: 'bw1-20',
    number: '20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/20.png","large":"https://images.pokemontcg.io/bw1/20_hires.png"}',
    searchName: 'Emboar (BLW 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Pansear',
    tcgApiId: 'bw1-21',
    number: '21',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/21.png","large":"https://images.pokemontcg.io/bw1/21_hires.png"}',
    searchName: 'Pansear (BLW 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Simisear',
    tcgApiId: 'bw1-22',
    number: '22',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/22.png","large":"https://images.pokemontcg.io/bw1/22_hires.png"}',
    searchName: 'Simisear (BLW 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Darumaka',
    tcgApiId: 'bw1-23',
    number: '23',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/23.png","large":"https://images.pokemontcg.io/bw1/23_hires.png"}',
    searchName: 'Darumaka (BLW 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Darumaka',
    tcgApiId: 'bw1-24',
    number: '24',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/24.png","large":"https://images.pokemontcg.io/bw1/24_hires.png"}',
    searchName: 'Darumaka (BLW 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Darmanitan',
    tcgApiId: 'bw1-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/25.png","large":"https://images.pokemontcg.io/bw1/25_hires.png"}',
    searchName: 'Darmanitan (BLW 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Reshiram',
    tcgApiId: 'bw1-26',
    number: '26',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/26.png","large":"https://images.pokemontcg.io/bw1/26_hires.png"}',
    searchName: 'Reshiram (BLW 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Oshawott',
    tcgApiId: 'bw1-27',
    number: '27',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/27.png","large":"https://images.pokemontcg.io/bw1/27_hires.png"}',
    searchName: 'Oshawott (BLW 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Oshawott',
    tcgApiId: 'bw1-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/28.png","large":"https://images.pokemontcg.io/bw1/28_hires.png"}',
    searchName: 'Oshawott (BLW 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Dewott',
    tcgApiId: 'bw1-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/29.png","large":"https://images.pokemontcg.io/bw1/29_hires.png"}',
    searchName: 'Dewott (BLW 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Dewott',
    tcgApiId: 'bw1-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/30.png","large":"https://images.pokemontcg.io/bw1/30_hires.png"}',
    searchName: 'Dewott (BLW 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Samurott',
    tcgApiId: 'bw1-31',
    number: '31',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/31.png","large":"https://images.pokemontcg.io/bw1/31_hires.png"}',
    searchName: 'Samurott (BLW 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Samurott',
    tcgApiId: 'bw1-32',
    number: '32',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/32.png","large":"https://images.pokemontcg.io/bw1/32_hires.png"}',
    searchName: 'Samurott (BLW 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Panpour',
    tcgApiId: 'bw1-33',
    number: '33',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/33.png","large":"https://images.pokemontcg.io/bw1/33_hires.png"}',
    searchName: 'Panpour (BLW 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Simipour',
    tcgApiId: 'bw1-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/34.png","large":"https://images.pokemontcg.io/bw1/34_hires.png"}',
    searchName: 'Simipour (BLW 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Basculin',
    tcgApiId: 'bw1-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/35.png","large":"https://images.pokemontcg.io/bw1/35_hires.png"}',
    searchName: 'Basculin (BLW 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Ducklett',
    tcgApiId: 'bw1-36',
    number: '36',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/36.png","large":"https://images.pokemontcg.io/bw1/36_hires.png"}',
    searchName: 'Ducklett (BLW 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Swanna',
    tcgApiId: 'bw1-37',
    number: '37',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/37.png","large":"https://images.pokemontcg.io/bw1/37_hires.png"}',
    searchName: 'Swanna (BLW 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Alomomola',
    tcgApiId: 'bw1-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/38.png","large":"https://images.pokemontcg.io/bw1/38_hires.png"}',
    searchName: 'Alomomola (BLW 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Alomomola',
    tcgApiId: 'bw1-39',
    number: '39',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/39.png","large":"https://images.pokemontcg.io/bw1/39_hires.png"}',
    searchName: 'Alomomola (BLW 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Blitzle',
    tcgApiId: 'bw1-40',
    number: '40',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/40.png","large":"https://images.pokemontcg.io/bw1/40_hires.png"}',
    searchName: 'Blitzle (BLW 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Blitzle',
    tcgApiId: 'bw1-41',
    number: '41',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/41.png","large":"https://images.pokemontcg.io/bw1/41_hires.png"}',
    searchName: 'Blitzle (BLW 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Zebstrika',
    tcgApiId: 'bw1-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/42.png","large":"https://images.pokemontcg.io/bw1/42_hires.png"}',
    searchName: 'Zebstrika (BLW 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Zebstrika',
    tcgApiId: 'bw1-43',
    number: '43',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/43.png","large":"https://images.pokemontcg.io/bw1/43_hires.png"}',
    searchName: 'Zebstrika (BLW 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Joltik',
    tcgApiId: 'bw1-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/44.png","large":"https://images.pokemontcg.io/bw1/44_hires.png"}',
    searchName: 'Joltik (BLW 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Joltik',
    tcgApiId: 'bw1-45',
    number: '45',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/45.png","large":"https://images.pokemontcg.io/bw1/45_hires.png"}',
    searchName: 'Joltik (BLW 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Galvantula',
    tcgApiId: 'bw1-46',
    number: '46',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/46.png","large":"https://images.pokemontcg.io/bw1/46_hires.png"}',
    searchName: 'Galvantula (BLW 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Zekrom',
    tcgApiId: 'bw1-47',
    number: '47',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/47.png","large":"https://images.pokemontcg.io/bw1/47_hires.png"}',
    searchName: 'Zekrom (BLW 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Munna',
    tcgApiId: 'bw1-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/48.png","large":"https://images.pokemontcg.io/bw1/48_hires.png"}',
    searchName: 'Munna (BLW 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Musharna',
    tcgApiId: 'bw1-49',
    number: '49',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/49.png","large":"https://images.pokemontcg.io/bw1/49_hires.png"}',
    searchName: 'Musharna (BLW 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Woobat',
    tcgApiId: 'bw1-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/50.png","large":"https://images.pokemontcg.io/bw1/50_hires.png"}',
    searchName: 'Woobat (BLW 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Swoobat',
    tcgApiId: 'bw1-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/51.png","large":"https://images.pokemontcg.io/bw1/51_hires.png"}',
    searchName: 'Swoobat (BLW 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Venipede',
    tcgApiId: 'bw1-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/52.png","large":"https://images.pokemontcg.io/bw1/52_hires.png"}',
    searchName: 'Venipede (BLW 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Whirlipede',
    tcgApiId: 'bw1-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/53.png","large":"https://images.pokemontcg.io/bw1/53_hires.png"}',
    searchName: 'Whirlipede (BLW 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Scolipede',
    tcgApiId: 'bw1-54',
    number: '54',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/54.png","large":"https://images.pokemontcg.io/bw1/54_hires.png"}',
    searchName: 'Scolipede (BLW 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Solosis',
    tcgApiId: 'bw1-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/55.png","large":"https://images.pokemontcg.io/bw1/55_hires.png"}',
    searchName: 'Solosis (BLW 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Duosion',
    tcgApiId: 'bw1-56',
    number: '56',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/56.png","large":"https://images.pokemontcg.io/bw1/56_hires.png"}',
    searchName: 'Duosion (BLW 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Reuniclus',
    tcgApiId: 'bw1-57',
    number: '57',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/57.png","large":"https://images.pokemontcg.io/bw1/57_hires.png"}',
    searchName: 'Reuniclus (BLW 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Timburr',
    tcgApiId: 'bw1-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/58.png","large":"https://images.pokemontcg.io/bw1/58_hires.png"}',
    searchName: 'Timburr (BLW 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Timburr',
    tcgApiId: 'bw1-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/59.png","large":"https://images.pokemontcg.io/bw1/59_hires.png"}',
    searchName: 'Timburr (BLW 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Gurdurr',
    tcgApiId: 'bw1-60',
    number: '60',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/60.png","large":"https://images.pokemontcg.io/bw1/60_hires.png"}',
    searchName: 'Gurdurr (BLW 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Throh',
    tcgApiId: 'bw1-61',
    number: '61',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/61.png","large":"https://images.pokemontcg.io/bw1/61_hires.png"}',
    searchName: 'Throh (BLW 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Sawk',
    tcgApiId: 'bw1-62',
    number: '62',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/62.png","large":"https://images.pokemontcg.io/bw1/62_hires.png"}',
    searchName: 'Sawk (BLW 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Sandile',
    tcgApiId: 'bw1-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/63.png","large":"https://images.pokemontcg.io/bw1/63_hires.png"}',
    searchName: 'Sandile (BLW 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Krokorok',
    tcgApiId: 'bw1-64',
    number: '64',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/64.png","large":"https://images.pokemontcg.io/bw1/64_hires.png"}',
    searchName: 'Krokorok (BLW 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Krookodile',
    tcgApiId: 'bw1-65',
    number: '65',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/65.png","large":"https://images.pokemontcg.io/bw1/65_hires.png"}',
    searchName: 'Krookodile (BLW 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Purrloin',
    tcgApiId: 'bw1-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/66.png","large":"https://images.pokemontcg.io/bw1/66_hires.png"}',
    searchName: 'Purrloin (BLW 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Liepard',
    tcgApiId: 'bw1-67',
    number: '67',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/67.png","large":"https://images.pokemontcg.io/bw1/67_hires.png"}',
    searchName: 'Liepard (BLW 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Scraggy',
    tcgApiId: 'bw1-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/68.png","large":"https://images.pokemontcg.io/bw1/68_hires.png"}',
    searchName: 'Scraggy (BLW 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Scrafty',
    tcgApiId: 'bw1-69',
    number: '69',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/69.png","large":"https://images.pokemontcg.io/bw1/69_hires.png"}',
    searchName: 'Scrafty (BLW 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Zorua',
    tcgApiId: 'bw1-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/70.png","large":"https://images.pokemontcg.io/bw1/70_hires.png"}',
    searchName: 'Zorua (BLW 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Zoroark',
    tcgApiId: 'bw1-71',
    number: '71',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/71.png","large":"https://images.pokemontcg.io/bw1/71_hires.png"}',
    searchName: 'Zoroark (BLW 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Vullaby',
    tcgApiId: 'bw1-72',
    number: '72',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/72.png","large":"https://images.pokemontcg.io/bw1/72_hires.png"}',
    searchName: 'Vullaby (BLW 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Mandibuzz',
    tcgApiId: 'bw1-73',
    number: '73',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/73.png","large":"https://images.pokemontcg.io/bw1/73_hires.png"}',
    searchName: 'Mandibuzz (BLW 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Klink',
    tcgApiId: 'bw1-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/74.png","large":"https://images.pokemontcg.io/bw1/74_hires.png"}',
    searchName: 'Klink (BLW 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Klang',
    tcgApiId: 'bw1-75',
    number: '75',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/75.png","large":"https://images.pokemontcg.io/bw1/75_hires.png"}',
    searchName: 'Klang (BLW 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Klinklang',
    tcgApiId: 'bw1-76',
    number: '76',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/76.png","large":"https://images.pokemontcg.io/bw1/76_hires.png"}',
    searchName: 'Klinklang (BLW 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Patrat',
    tcgApiId: 'bw1-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/77.png","large":"https://images.pokemontcg.io/bw1/77_hires.png"}',
    searchName: 'Patrat (BLW 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Patrat',
    tcgApiId: 'bw1-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/78.png","large":"https://images.pokemontcg.io/bw1/78_hires.png"}',
    searchName: 'Patrat (BLW 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Watchog',
    tcgApiId: 'bw1-79',
    number: '79',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/79.png","large":"https://images.pokemontcg.io/bw1/79_hires.png"}',
    searchName: 'Watchog (BLW 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Lillipup',
    tcgApiId: 'bw1-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/80.png","large":"https://images.pokemontcg.io/bw1/80_hires.png"}',
    searchName: 'Lillipup (BLW 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Lillipup',
    tcgApiId: 'bw1-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/81.png","large":"https://images.pokemontcg.io/bw1/81_hires.png"}',
    searchName: 'Lillipup (BLW 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Herdier',
    tcgApiId: 'bw1-82',
    number: '82',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/82.png","large":"https://images.pokemontcg.io/bw1/82_hires.png"}',
    searchName: 'Herdier (BLW 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Stoutland',
    tcgApiId: 'bw1-83',
    number: '83',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/83.png","large":"https://images.pokemontcg.io/bw1/83_hires.png"}',
    searchName: 'Stoutland (BLW 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Pidove',
    tcgApiId: 'bw1-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/84.png","large":"https://images.pokemontcg.io/bw1/84_hires.png"}',
    searchName: 'Pidove (BLW 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Tranquill',
    tcgApiId: 'bw1-85',
    number: '85',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/85.png","large":"https://images.pokemontcg.io/bw1/85_hires.png"}',
    searchName: 'Tranquill (BLW 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Unfezant',
    tcgApiId: 'bw1-86',
    number: '86',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/86.png","large":"https://images.pokemontcg.io/bw1/86_hires.png"}',
    searchName: 'Unfezant (BLW 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Audino',
    tcgApiId: 'bw1-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/87.png","large":"https://images.pokemontcg.io/bw1/87_hires.png"}',
    searchName: 'Audino (BLW 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Minccino',
    tcgApiId: 'bw1-88',
    number: '88',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/88.png","large":"https://images.pokemontcg.io/bw1/88_hires.png"}',
    searchName: 'Minccino (BLW 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Cinccino',
    tcgApiId: 'bw1-89',
    number: '89',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/89.png","large":"https://images.pokemontcg.io/bw1/89_hires.png"}',
    searchName: 'Cinccino (BLW 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Bouffalant',
    tcgApiId: 'bw1-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/90.png","large":"https://images.pokemontcg.io/bw1/90_hires.png"}',
    searchName: 'Bouffalant (BLW 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Bouffalant',
    tcgApiId: 'bw1-91',
    number: '91',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/91.png","large":"https://images.pokemontcg.io/bw1/91_hires.png"}',
    searchName: 'Bouffalant (BLW 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Energy Retrieval',
    tcgApiId: 'bw1-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/92.png","large":"https://images.pokemontcg.io/bw1/92_hires.png"}',
    searchName: 'Energy Retrieval (BLW 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Energy Search',
    tcgApiId: 'bw1-93',
    number: '93',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/93.png","large":"https://images.pokemontcg.io/bw1/93_hires.png"}',
    searchName: 'Energy Search (BLW 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Energy Switch',
    tcgApiId: 'bw1-94',
    number: '94',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/94.png","large":"https://images.pokemontcg.io/bw1/94_hires.png"}',
    searchName: 'Energy Switch (BLW 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Full Heal',
    tcgApiId: 'bw1-95',
    number: '95',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/95.png","large":"https://images.pokemontcg.io/bw1/95_hires.png"}',
    searchName: 'Full Heal (BLW 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'PlusPower',
    tcgApiId: 'bw1-96',
    number: '96',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/96.png","large":"https://images.pokemontcg.io/bw1/96_hires.png"}',
    searchName: 'PlusPower (BLW 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Poké Ball',
    tcgApiId: 'bw1-97',
    number: '97',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/97.png","large":"https://images.pokemontcg.io/bw1/97_hires.png"}',
    searchName: 'Poké Ball (BLW 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Pokédex',
    tcgApiId: 'bw1-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/98.png","large":"https://images.pokemontcg.io/bw1/98_hires.png"}',
    searchName: 'Pokédex (BLW 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Pokémon Communication',
    tcgApiId: 'bw1-99',
    number: '99',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/99.png","large":"https://images.pokemontcg.io/bw1/99_hires.png"}',
    searchName: 'Pokémon Communication (BLW 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Potion',
    tcgApiId: 'bw1-100',
    number: '100',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/100.png","large":"https://images.pokemontcg.io/bw1/100_hires.png"}',
    searchName: 'Potion (BLW 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Professor Juniper',
    tcgApiId: 'bw1-101',
    number: '101',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/101.png","large":"https://images.pokemontcg.io/bw1/101_hires.png"}',
    searchName: 'Professor Juniper (BLW 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Revive',
    tcgApiId: 'bw1-102',
    number: '102',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/102.png","large":"https://images.pokemontcg.io/bw1/102_hires.png"}',
    searchName: 'Revive (BLW 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Super Scoop Up',
    tcgApiId: 'bw1-103',
    number: '103',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/103.png","large":"https://images.pokemontcg.io/bw1/103_hires.png"}',
    searchName: 'Super Scoop Up (BLW 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Switch',
    tcgApiId: 'bw1-104',
    number: '104',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/104.png","large":"https://images.pokemontcg.io/bw1/104_hires.png"}',
    searchName: 'Switch (BLW 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Grass Energy',
    tcgApiId: 'bw1-105',
    number: '105',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/105.png","large":"https://images.pokemontcg.io/bw1/105_hires.png"}',
    searchName: 'Grass Energy (BLW 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Fire Energy',
    tcgApiId: 'bw1-106',
    number: '106',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/106.png","large":"https://images.pokemontcg.io/bw1/106_hires.png"}',
    searchName: 'Fire Energy (BLW 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Water Energy',
    tcgApiId: 'bw1-107',
    number: '107',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/107.png","large":"https://images.pokemontcg.io/bw1/107_hires.png"}',
    searchName: 'Water Energy (BLW 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Lightning Energy',
    tcgApiId: 'bw1-108',
    number: '108',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/108.png","large":"https://images.pokemontcg.io/bw1/108_hires.png"}',
    searchName: 'Lightning Energy (BLW 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Psychic Energy',
    tcgApiId: 'bw1-109',
    number: '109',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/109.png","large":"https://images.pokemontcg.io/bw1/109_hires.png"}',
    searchName: 'Psychic Energy (BLW 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Fighting Energy',
    tcgApiId: 'bw1-110',
    number: '110',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/110.png","large":"https://images.pokemontcg.io/bw1/110_hires.png"}',
    searchName: 'Fighting Energy (BLW 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Darkness Energy',
    tcgApiId: 'bw1-111',
    number: '111',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/111.png","large":"https://images.pokemontcg.io/bw1/111_hires.png"}',
    searchName: 'Darkness Energy (BLW 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Metal Energy',
    tcgApiId: 'bw1-112',
    number: '112',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/112.png","large":"https://images.pokemontcg.io/bw1/112_hires.png"}',
    searchName: 'Metal Energy (BLW 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Reshiram',
    tcgApiId: 'bw1-113',
    number: '113',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/113.png","large":"https://images.pokemontcg.io/bw1/113_hires.png"}',
    searchName: 'Reshiram (BLW 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Zekrom',
    tcgApiId: 'bw1-114',
    number: '114',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/114.png","large":"https://images.pokemontcg.io/bw1/114_hires.png"}',
    searchName: 'Zekrom (BLW 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw1',
    name: 'Pikachu',
    tcgApiId: 'bw1-115',
    number: '115',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw1/115.png","large":"https://images.pokemontcg.io/bw1/115_hires.png"}',
    searchName: 'Pikachu (BLW 115)',
  },
];
