export const cardSeedBw10 = [
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Surskit',
    tcgApiId: 'bw10-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/1.png","large":"https://images.pokemontcg.io/bw10/1_hires.png"}',
    searchName: 'Surskit (PLB 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Masquerain',
    tcgApiId: 'bw10-2',
    number: '2',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/2.png","large":"https://images.pokemontcg.io/bw10/2_hires.png"}',
    searchName: 'Masquerain (PLB 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Lileep',
    tcgApiId: 'bw10-3',
    number: '3',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/3.png","large":"https://images.pokemontcg.io/bw10/3_hires.png"}',
    searchName: 'Lileep (PLB 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Cradily',
    tcgApiId: 'bw10-4',
    number: '4',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/4.png","large":"https://images.pokemontcg.io/bw10/4_hires.png"}',
    searchName: 'Cradily (PLB 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Tropius',
    tcgApiId: 'bw10-5',
    number: '5',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/5.png","large":"https://images.pokemontcg.io/bw10/5_hires.png"}',
    searchName: 'Tropius (PLB 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Karrablast',
    tcgApiId: 'bw10-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/6.png","large":"https://images.pokemontcg.io/bw10/6_hires.png"}',
    searchName: 'Karrablast (PLB 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Shelmet',
    tcgApiId: 'bw10-7',
    number: '7',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/7.png","large":"https://images.pokemontcg.io/bw10/7_hires.png"}',
    searchName: 'Shelmet (PLB 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Accelgor',
    tcgApiId: 'bw10-8',
    number: '8',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/8.png","large":"https://images.pokemontcg.io/bw10/8_hires.png"}',
    searchName: 'Accelgor (PLB 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Virizion-EX',
    tcgApiId: 'bw10-9',
    number: '9',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/9.png","large":"https://images.pokemontcg.io/bw10/9_hires.png"}',
    searchName: 'Virizion-EX (PLB 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Genesect',
    tcgApiId: 'bw10-10',
    number: '10',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/10.png","large":"https://images.pokemontcg.io/bw10/10_hires.png"}',
    searchName: 'Genesect (PLB 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Genesect-EX',
    tcgApiId: 'bw10-11',
    number: '11',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/11.png","large":"https://images.pokemontcg.io/bw10/11_hires.png"}',
    searchName: 'Genesect-EX (PLB 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Larvesta',
    tcgApiId: 'bw10-12',
    number: '12',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/12.png","large":"https://images.pokemontcg.io/bw10/12_hires.png"}',
    searchName: 'Larvesta (PLB 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Volcarona',
    tcgApiId: 'bw10-13',
    number: '13',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/13.png","large":"https://images.pokemontcg.io/bw10/13_hires.png"}',
    searchName: 'Volcarona (PLB 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Squirtle',
    tcgApiId: 'bw10-14',
    number: '14',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/14.png","large":"https://images.pokemontcg.io/bw10/14_hires.png"}',
    searchName: 'Squirtle (PLB 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Wartortle',
    tcgApiId: 'bw10-15',
    number: '15',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/15.png","large":"https://images.pokemontcg.io/bw10/15_hires.png"}',
    searchName: 'Wartortle (PLB 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Blastoise',
    tcgApiId: 'bw10-16',
    number: '16',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/16.png","large":"https://images.pokemontcg.io/bw10/16_hires.png"}',
    searchName: 'Blastoise (PLB 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Lapras',
    tcgApiId: 'bw10-17',
    number: '17',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/17.png","large":"https://images.pokemontcg.io/bw10/17_hires.png"}',
    searchName: 'Lapras (PLB 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Remoraid',
    tcgApiId: 'bw10-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/18.png","large":"https://images.pokemontcg.io/bw10/18_hires.png"}',
    searchName: 'Remoraid (PLB 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Octillery',
    tcgApiId: 'bw10-19',
    number: '19',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/19.png","large":"https://images.pokemontcg.io/bw10/19_hires.png"}',
    searchName: 'Octillery (PLB 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Suicune',
    tcgApiId: 'bw10-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/20.png","large":"https://images.pokemontcg.io/bw10/20_hires.png"}',
    searchName: 'Suicune (PLB 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Snorunt',
    tcgApiId: 'bw10-21',
    number: '21',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/21.png","large":"https://images.pokemontcg.io/bw10/21_hires.png"}',
    searchName: 'Snorunt (PLB 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Glalie',
    tcgApiId: 'bw10-22',
    number: '22',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/22.png","large":"https://images.pokemontcg.io/bw10/22_hires.png"}',
    searchName: 'Glalie (PLB 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Froslass',
    tcgApiId: 'bw10-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/23.png","large":"https://images.pokemontcg.io/bw10/23_hires.png"}',
    searchName: 'Froslass (PLB 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Relicanth',
    tcgApiId: 'bw10-24',
    number: '24',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/24.png","large":"https://images.pokemontcg.io/bw10/24_hires.png"}',
    searchName: 'Relicanth (PLB 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Snover',
    tcgApiId: 'bw10-25',
    number: '25',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/25.png","large":"https://images.pokemontcg.io/bw10/25_hires.png"}',
    searchName: 'Snover (PLB 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Abomasnow',
    tcgApiId: 'bw10-26',
    number: '26',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/26.png","large":"https://images.pokemontcg.io/bw10/26_hires.png"}',
    searchName: 'Abomasnow (PLB 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Tirtouga',
    tcgApiId: 'bw10-27',
    number: '27',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/27.png","large":"https://images.pokemontcg.io/bw10/27_hires.png"}',
    searchName: 'Tirtouga (PLB 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Carracosta',
    tcgApiId: 'bw10-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/28.png","large":"https://images.pokemontcg.io/bw10/28_hires.png"}',
    searchName: 'Carracosta (PLB 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Ducklett',
    tcgApiId: 'bw10-29',
    number: '29',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/29.png","large":"https://images.pokemontcg.io/bw10/29_hires.png"}',
    searchName: 'Ducklett (PLB 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Kyurem-EX',
    tcgApiId: 'bw10-30',
    number: '30',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/30.png","large":"https://images.pokemontcg.io/bw10/30_hires.png"}',
    searchName: 'Kyurem-EX (PLB 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Tynamo',
    tcgApiId: 'bw10-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/31.png","large":"https://images.pokemontcg.io/bw10/31_hires.png"}',
    searchName: 'Tynamo (PLB 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Eelektrik',
    tcgApiId: 'bw10-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/32.png","large":"https://images.pokemontcg.io/bw10/32_hires.png"}',
    searchName: 'Eelektrik (PLB 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Eelektross',
    tcgApiId: 'bw10-33',
    number: '33',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/33.png","large":"https://images.pokemontcg.io/bw10/33_hires.png"}',
    searchName: 'Eelektross (PLB 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Drifloon',
    tcgApiId: 'bw10-34',
    number: '34',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/34.png","large":"https://images.pokemontcg.io/bw10/34_hires.png"}',
    searchName: 'Drifloon (PLB 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Drifblim',
    tcgApiId: 'bw10-35',
    number: '35',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/35.png","large":"https://images.pokemontcg.io/bw10/35_hires.png"}',
    searchName: 'Drifblim (PLB 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Uxie',
    tcgApiId: 'bw10-36',
    number: '36',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/36.png","large":"https://images.pokemontcg.io/bw10/36_hires.png"}',
    searchName: 'Uxie (PLB 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Mesprit',
    tcgApiId: 'bw10-37',
    number: '37',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/37.png","large":"https://images.pokemontcg.io/bw10/37_hires.png"}',
    searchName: 'Mesprit (PLB 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Azelf',
    tcgApiId: 'bw10-38',
    number: '38',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/38.png","large":"https://images.pokemontcg.io/bw10/38_hires.png"}',
    searchName: 'Azelf (PLB 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Munna',
    tcgApiId: 'bw10-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/39.png","large":"https://images.pokemontcg.io/bw10/39_hires.png"}',
    searchName: 'Munna (PLB 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Musharna',
    tcgApiId: 'bw10-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/40.png","large":"https://images.pokemontcg.io/bw10/40_hires.png"}',
    searchName: 'Musharna (PLB 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Sigilyph',
    tcgApiId: 'bw10-41',
    number: '41',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/41.png","large":"https://images.pokemontcg.io/bw10/41_hires.png"}',
    searchName: 'Sigilyph (PLB 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Solosis',
    tcgApiId: 'bw10-42',
    number: '42',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/42.png","large":"https://images.pokemontcg.io/bw10/42_hires.png"}',
    searchName: 'Solosis (PLB 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Duosion',
    tcgApiId: 'bw10-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/43.png","large":"https://images.pokemontcg.io/bw10/43_hires.png"}',
    searchName: 'Duosion (PLB 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Reuniclus',
    tcgApiId: 'bw10-44',
    number: '44',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/44.png","large":"https://images.pokemontcg.io/bw10/44_hires.png"}',
    searchName: 'Reuniclus (PLB 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Golett',
    tcgApiId: 'bw10-45',
    number: '45',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/45.png","large":"https://images.pokemontcg.io/bw10/45_hires.png"}',
    searchName: 'Golett (PLB 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Golurk',
    tcgApiId: 'bw10-46',
    number: '46',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/46.png","large":"https://images.pokemontcg.io/bw10/46_hires.png"}',
    searchName: 'Golurk (PLB 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Machop',
    tcgApiId: 'bw10-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/47.png","large":"https://images.pokemontcg.io/bw10/47_hires.png"}',
    searchName: 'Machop (PLB 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Machoke',
    tcgApiId: 'bw10-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/48.png","large":"https://images.pokemontcg.io/bw10/48_hires.png"}',
    searchName: 'Machoke (PLB 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Machamp',
    tcgApiId: 'bw10-49',
    number: '49',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/49.png","large":"https://images.pokemontcg.io/bw10/49_hires.png"}',
    searchName: 'Machamp (PLB 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Machamp',
    tcgApiId: 'bw10-50',
    number: '50',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/50.png","large":"https://images.pokemontcg.io/bw10/50_hires.png"}',
    searchName: 'Machamp (PLB 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Throh',
    tcgApiId: 'bw10-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/51.png","large":"https://images.pokemontcg.io/bw10/51_hires.png"}',
    searchName: 'Throh (PLB 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Sawk',
    tcgApiId: 'bw10-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/52.png","large":"https://images.pokemontcg.io/bw10/52_hires.png"}',
    searchName: 'Sawk (PLB 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Archen',
    tcgApiId: 'bw10-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/53.png","large":"https://images.pokemontcg.io/bw10/53_hires.png"}',
    searchName: 'Archen (PLB 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Archeops',
    tcgApiId: 'bw10-54',
    number: '54',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/54.png","large":"https://images.pokemontcg.io/bw10/54_hires.png"}',
    searchName: 'Archeops (PLB 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Houndour',
    tcgApiId: 'bw10-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/55.png","large":"https://images.pokemontcg.io/bw10/55_hires.png"}',
    searchName: 'Houndour (PLB 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Houndoom',
    tcgApiId: 'bw10-56',
    number: '56',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/56.png","large":"https://images.pokemontcg.io/bw10/56_hires.png"}',
    searchName: 'Houndoom (PLB 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Aron',
    tcgApiId: 'bw10-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/57.png","large":"https://images.pokemontcg.io/bw10/57_hires.png"}',
    searchName: 'Aron (PLB 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Lairon',
    tcgApiId: 'bw10-58',
    number: '58',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/58.png","large":"https://images.pokemontcg.io/bw10/58_hires.png"}',
    searchName: 'Lairon (PLB 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Aggron',
    tcgApiId: 'bw10-59',
    number: '59',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/59.png","large":"https://images.pokemontcg.io/bw10/59_hires.png"}',
    searchName: 'Aggron (PLB 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Jirachi-EX',
    tcgApiId: 'bw10-60',
    number: '60',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/60.png","large":"https://images.pokemontcg.io/bw10/60_hires.png"}',
    searchName: 'Jirachi-EX (PLB 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Escavalier',
    tcgApiId: 'bw10-61',
    number: '61',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/61.png","large":"https://images.pokemontcg.io/bw10/61_hires.png"}',
    searchName: 'Escavalier (PLB 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Bagon',
    tcgApiId: 'bw10-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/62.png","large":"https://images.pokemontcg.io/bw10/62_hires.png"}',
    searchName: 'Bagon (PLB 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Shelgon',
    tcgApiId: 'bw10-63',
    number: '63',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/63.png","large":"https://images.pokemontcg.io/bw10/63_hires.png"}',
    searchName: 'Shelgon (PLB 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Salamence',
    tcgApiId: 'bw10-64',
    number: '64',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/64.png","large":"https://images.pokemontcg.io/bw10/64_hires.png"}',
    searchName: 'Salamence (PLB 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Dialga-EX',
    tcgApiId: 'bw10-65',
    number: '65',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/65.png","large":"https://images.pokemontcg.io/bw10/65_hires.png"}',
    searchName: 'Dialga-EX (PLB 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Palkia-EX',
    tcgApiId: 'bw10-66',
    number: '66',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/66.png","large":"https://images.pokemontcg.io/bw10/66_hires.png"}',
    searchName: 'Palkia-EX (PLB 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Axew',
    tcgApiId: 'bw10-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/67.png","large":"https://images.pokemontcg.io/bw10/67_hires.png"}',
    searchName: 'Axew (PLB 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Fraxure',
    tcgApiId: 'bw10-68',
    number: '68',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/68.png","large":"https://images.pokemontcg.io/bw10/68_hires.png"}',
    searchName: 'Fraxure (PLB 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Haxorus',
    tcgApiId: 'bw10-69',
    number: '69',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/69.png","large":"https://images.pokemontcg.io/bw10/69_hires.png"}',
    searchName: 'Haxorus (PLB 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Druddigon',
    tcgApiId: 'bw10-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/70.png","large":"https://images.pokemontcg.io/bw10/70_hires.png"}',
    searchName: 'Druddigon (PLB 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Kangaskhan',
    tcgApiId: 'bw10-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/71.png","large":"https://images.pokemontcg.io/bw10/71_hires.png"}',
    searchName: 'Kangaskhan (PLB 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Porygon',
    tcgApiId: 'bw10-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/72.png","large":"https://images.pokemontcg.io/bw10/72_hires.png"}',
    searchName: 'Porygon (PLB 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Porygon2',
    tcgApiId: 'bw10-73',
    number: '73',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/73.png","large":"https://images.pokemontcg.io/bw10/73_hires.png"}',
    searchName: 'Porygon2 (PLB 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Porygon-Z',
    tcgApiId: 'bw10-74',
    number: '74',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/74.png","large":"https://images.pokemontcg.io/bw10/74_hires.png"}',
    searchName: 'Porygon-Z (PLB 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Teddiursa',
    tcgApiId: 'bw10-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/75.png","large":"https://images.pokemontcg.io/bw10/75_hires.png"}',
    searchName: 'Teddiursa (PLB 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Ursaring',
    tcgApiId: 'bw10-76',
    number: '76',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/76.png","large":"https://images.pokemontcg.io/bw10/76_hires.png"}',
    searchName: 'Ursaring (PLB 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Chatot',
    tcgApiId: 'bw10-77',
    number: '77',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/77.png","large":"https://images.pokemontcg.io/bw10/77_hires.png"}',
    searchName: 'Chatot (PLB 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Caitlin',
    tcgApiId: 'bw10-78',
    number: '78',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/78.png","large":"https://images.pokemontcg.io/bw10/78_hires.png"}',
    searchName: 'Caitlin (PLB 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Cover Fossil',
    tcgApiId: 'bw10-79',
    number: '79',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/79.png","large":"https://images.pokemontcg.io/bw10/79_hires.png"}',
    searchName: 'Cover Fossil (PLB 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Energy Retrieval',
    tcgApiId: 'bw10-80',
    number: '80',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/80.png","large":"https://images.pokemontcg.io/bw10/80_hires.png"}',
    searchName: 'Energy Retrieval (PLB 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Iris',
    tcgApiId: 'bw10-81',
    number: '81',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/81.png","large":"https://images.pokemontcg.io/bw10/81_hires.png"}',
    searchName: 'Iris (PLB 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Plume Fossil',
    tcgApiId: 'bw10-82',
    number: '82',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/82.png","large":"https://images.pokemontcg.io/bw10/82_hires.png"}',
    searchName: 'Plume Fossil (PLB 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Pokémon Catcher',
    tcgApiId: 'bw10-83',
    number: '83',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/83.png","large":"https://images.pokemontcg.io/bw10/83_hires.png"}',
    searchName: 'Pokémon Catcher (PLB 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Professor Juniper',
    tcgApiId: 'bw10-84',
    number: '84',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/84.png","large":"https://images.pokemontcg.io/bw10/84_hires.png"}',
    searchName: 'Professor Juniper (PLB 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Rare Candy',
    tcgApiId: 'bw10-85',
    number: '85',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/85.png","large":"https://images.pokemontcg.io/bw10/85_hires.png"}',
    searchName: 'Rare Candy (PLB 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Reversal Trigger',
    tcgApiId: 'bw10-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/86.png","large":"https://images.pokemontcg.io/bw10/86_hires.png"}',
    searchName: 'Reversal Trigger (PLB 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Root Fossil Lileep',
    tcgApiId: 'bw10-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/87.png","large":"https://images.pokemontcg.io/bw10/87_hires.png"}',
    searchName: 'Root Fossil Lileep (PLB 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Silver Bangle',
    tcgApiId: 'bw10-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/88.png","large":"https://images.pokemontcg.io/bw10/88_hires.png"}',
    searchName: 'Silver Bangle (PLB 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Silver Mirror',
    tcgApiId: 'bw10-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/89.png","large":"https://images.pokemontcg.io/bw10/89_hires.png"}',
    searchName: 'Silver Mirror (PLB 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Ultra Ball',
    tcgApiId: 'bw10-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/90.png","large":"https://images.pokemontcg.io/bw10/90_hires.png"}',
    searchName: 'Ultra Ball (PLB 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Plasma Energy',
    tcgApiId: 'bw10-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/91.png","large":"https://images.pokemontcg.io/bw10/91_hires.png"}',
    searchName: 'Plasma Energy (PLB 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'G Booster',
    tcgApiId: 'bw10-92',
    number: '92',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/92.png","large":"https://images.pokemontcg.io/bw10/92_hires.png"}',
    searchName: 'G Booster (PLB 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'G Scope',
    tcgApiId: 'bw10-93',
    number: '93',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/93.png","large":"https://images.pokemontcg.io/bw10/93_hires.png"}',
    searchName: 'G Scope (PLB 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Master Ball',
    tcgApiId: 'bw10-94',
    number: '94',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/94.png","large":"https://images.pokemontcg.io/bw10/94_hires.png"}',
    searchName: 'Master Ball (PLB 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Scoop Up Cyclone',
    tcgApiId: 'bw10-95',
    number: '95',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/95.png","large":"https://images.pokemontcg.io/bw10/95_hires.png"}',
    searchName: 'Scoop Up Cyclone (PLB 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Virizion-EX',
    tcgApiId: 'bw10-96',
    number: '96',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/96.png","large":"https://images.pokemontcg.io/bw10/96_hires.png"}',
    searchName: 'Virizion-EX (PLB 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Genesect-EX',
    tcgApiId: 'bw10-97',
    number: '97',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/97.png","large":"https://images.pokemontcg.io/bw10/97_hires.png"}',
    searchName: 'Genesect-EX (PLB 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Jirachi-EX',
    tcgApiId: 'bw10-98',
    number: '98',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/98.png","large":"https://images.pokemontcg.io/bw10/98_hires.png"}',
    searchName: 'Jirachi-EX (PLB 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Dialga-EX',
    tcgApiId: 'bw10-99',
    number: '99',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/99.png","large":"https://images.pokemontcg.io/bw10/99_hires.png"}',
    searchName: 'Dialga-EX (PLB 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Palkia-EX',
    tcgApiId: 'bw10-100',
    number: '100',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/100.png","large":"https://images.pokemontcg.io/bw10/100_hires.png"}',
    searchName: 'Palkia-EX (PLB 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Iris',
    tcgApiId: 'bw10-101',
    number: '101',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/101.png","large":"https://images.pokemontcg.io/bw10/101_hires.png"}',
    searchName: 'Iris (PLB 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Exeggcute',
    tcgApiId: 'bw10-102',
    number: '102',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/102.png","large":"https://images.pokemontcg.io/bw10/102_hires.png"}',
    searchName: 'Exeggcute (PLB 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Virizion',
    tcgApiId: 'bw10-103',
    number: '103',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/103.png","large":"https://images.pokemontcg.io/bw10/103_hires.png"}',
    searchName: 'Virizion (PLB 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Dusknoir',
    tcgApiId: 'bw10-104',
    number: '104',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/104.png","large":"https://images.pokemontcg.io/bw10/104_hires.png"}',
    searchName: 'Dusknoir (PLB 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw10',
    name: 'Rare Candy',
    tcgApiId: 'bw10-105',
    number: '105',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw10/105.png","large":"https://images.pokemontcg.io/bw10/105_hires.png"}',
    searchName: 'Rare Candy (PLB 105)',
  },
];
