export const cardSeedBw4 = [
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Pinsir',
    tcgApiId: 'bw4-1',
    number: '1',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/1.png","large":"https://images.pokemontcg.io/bw4/1_hires.png"}',
    searchName: 'Pinsir (NXD 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Seedot',
    tcgApiId: 'bw4-2',
    number: '2',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/2.png","large":"https://images.pokemontcg.io/bw4/2_hires.png"}',
    searchName: 'Seedot (NXD 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Kricketot',
    tcgApiId: 'bw4-3',
    number: '3',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/3.png","large":"https://images.pokemontcg.io/bw4/3_hires.png"}',
    searchName: 'Kricketot (NXD 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Kricketune',
    tcgApiId: 'bw4-4',
    number: '4',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/4.png","large":"https://images.pokemontcg.io/bw4/4_hires.png"}',
    searchName: 'Kricketune (NXD 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Shaymin-EX',
    tcgApiId: 'bw4-5',
    number: '5',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/5.png","large":"https://images.pokemontcg.io/bw4/5_hires.png"}',
    searchName: 'Shaymin-EX (NXD 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Pansage',
    tcgApiId: 'bw4-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/6.png","large":"https://images.pokemontcg.io/bw4/6_hires.png"}',
    searchName: 'Pansage (NXD 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Simisage',
    tcgApiId: 'bw4-7',
    number: '7',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/7.png","large":"https://images.pokemontcg.io/bw4/7_hires.png"}',
    searchName: 'Simisage (NXD 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Foongus',
    tcgApiId: 'bw4-8',
    number: '8',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/8.png","large":"https://images.pokemontcg.io/bw4/8_hires.png"}',
    searchName: 'Foongus (NXD 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Amoonguss',
    tcgApiId: 'bw4-9',
    number: '9',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/9.png","large":"https://images.pokemontcg.io/bw4/9_hires.png"}',
    searchName: 'Amoonguss (NXD 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Growlithe',
    tcgApiId: 'bw4-10',
    number: '10',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/10.png","large":"https://images.pokemontcg.io/bw4/10_hires.png"}',
    searchName: 'Growlithe (NXD 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Growlithe',
    tcgApiId: 'bw4-11',
    number: '11',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/11.png","large":"https://images.pokemontcg.io/bw4/11_hires.png"}',
    searchName: 'Growlithe (NXD 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Arcanine',
    tcgApiId: 'bw4-12',
    number: '12',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/12.png","large":"https://images.pokemontcg.io/bw4/12_hires.png"}',
    searchName: 'Arcanine (NXD 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Arcanine',
    tcgApiId: 'bw4-13',
    number: '13',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/13.png","large":"https://images.pokemontcg.io/bw4/13_hires.png"}',
    searchName: 'Arcanine (NXD 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Moltres',
    tcgApiId: 'bw4-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/14.png","large":"https://images.pokemontcg.io/bw4/14_hires.png"}',
    searchName: 'Moltres (NXD 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Pansear',
    tcgApiId: 'bw4-15',
    number: '15',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/15.png","large":"https://images.pokemontcg.io/bw4/15_hires.png"}',
    searchName: 'Pansear (NXD 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Simisear',
    tcgApiId: 'bw4-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/16.png","large":"https://images.pokemontcg.io/bw4/16_hires.png"}',
    searchName: 'Simisear (NXD 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Darumaka',
    tcgApiId: 'bw4-17',
    number: '17',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/17.png","large":"https://images.pokemontcg.io/bw4/17_hires.png"}',
    searchName: 'Darumaka (NXD 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Litwick',
    tcgApiId: 'bw4-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/18.png","large":"https://images.pokemontcg.io/bw4/18_hires.png"}',
    searchName: 'Litwick (NXD 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Lampent',
    tcgApiId: 'bw4-19',
    number: '19',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/19.png","large":"https://images.pokemontcg.io/bw4/19_hires.png"}',
    searchName: 'Lampent (NXD 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Chandelure',
    tcgApiId: 'bw4-20',
    number: '20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/20.png","large":"https://images.pokemontcg.io/bw4/20_hires.png"}',
    searchName: 'Chandelure (NXD 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Reshiram',
    tcgApiId: 'bw4-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/21.png","large":"https://images.pokemontcg.io/bw4/21_hires.png"}',
    searchName: 'Reshiram (NXD 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Reshiram-EX',
    tcgApiId: 'bw4-22',
    number: '22',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/22.png","large":"https://images.pokemontcg.io/bw4/22_hires.png"}',
    searchName: 'Reshiram-EX (NXD 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Staryu',
    tcgApiId: 'bw4-23',
    number: '23',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/23.png","large":"https://images.pokemontcg.io/bw4/23_hires.png"}',
    searchName: 'Staryu (NXD 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Starmie',
    tcgApiId: 'bw4-24',
    number: '24',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/24.png","large":"https://images.pokemontcg.io/bw4/24_hires.png"}',
    searchName: 'Starmie (NXD 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Lapras',
    tcgApiId: 'bw4-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/25.png","large":"https://images.pokemontcg.io/bw4/25_hires.png"}',
    searchName: 'Lapras (NXD 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Lapras',
    tcgApiId: 'bw4-26',
    number: '26',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/26.png","large":"https://images.pokemontcg.io/bw4/26_hires.png"}',
    searchName: 'Lapras (NXD 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Articuno',
    tcgApiId: 'bw4-27',
    number: '27',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/27.png","large":"https://images.pokemontcg.io/bw4/27_hires.png"}',
    searchName: 'Articuno (NXD 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Panpour',
    tcgApiId: 'bw4-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/28.png","large":"https://images.pokemontcg.io/bw4/28_hires.png"}',
    searchName: 'Panpour (NXD 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Simipour',
    tcgApiId: 'bw4-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/29.png","large":"https://images.pokemontcg.io/bw4/29_hires.png"}',
    searchName: 'Simipour (NXD 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Basculin',
    tcgApiId: 'bw4-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/30.png","large":"https://images.pokemontcg.io/bw4/30_hires.png"}',
    searchName: 'Basculin (NXD 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Vanillite',
    tcgApiId: 'bw4-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/31.png","large":"https://images.pokemontcg.io/bw4/31_hires.png"}',
    searchName: 'Vanillite (NXD 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Vanillish',
    tcgApiId: 'bw4-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/32.png","large":"https://images.pokemontcg.io/bw4/32_hires.png"}',
    searchName: 'Vanillish (NXD 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Vanilluxe',
    tcgApiId: 'bw4-33',
    number: '33',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/33.png","large":"https://images.pokemontcg.io/bw4/33_hires.png"}',
    searchName: 'Vanilluxe (NXD 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Frillish',
    tcgApiId: 'bw4-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/34.png","large":"https://images.pokemontcg.io/bw4/34_hires.png"}',
    searchName: 'Frillish (NXD 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Jellicent',
    tcgApiId: 'bw4-35',
    number: '35',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/35.png","large":"https://images.pokemontcg.io/bw4/35_hires.png"}',
    searchName: 'Jellicent (NXD 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Cubchoo',
    tcgApiId: 'bw4-36',
    number: '36',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/36.png","large":"https://images.pokemontcg.io/bw4/36_hires.png"}',
    searchName: 'Cubchoo (NXD 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Beartic',
    tcgApiId: 'bw4-37',
    number: '37',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/37.png","large":"https://images.pokemontcg.io/bw4/37_hires.png"}',
    searchName: 'Beartic (NXD 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Kyurem-EX',
    tcgApiId: 'bw4-38',
    number: '38',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/38.png","large":"https://images.pokemontcg.io/bw4/38_hires.png"}',
    searchName: 'Kyurem-EX (NXD 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Pikachu',
    tcgApiId: 'bw4-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/39.png","large":"https://images.pokemontcg.io/bw4/39_hires.png"}',
    searchName: 'Pikachu (NXD 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Raichu',
    tcgApiId: 'bw4-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/40.png","large":"https://images.pokemontcg.io/bw4/40_hires.png"}',
    searchName: 'Raichu (NXD 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Zapdos',
    tcgApiId: 'bw4-41',
    number: '41',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/41.png","large":"https://images.pokemontcg.io/bw4/41_hires.png"}',
    searchName: 'Zapdos (NXD 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Shinx',
    tcgApiId: 'bw4-42',
    number: '42',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/42.png","large":"https://images.pokemontcg.io/bw4/42_hires.png"}',
    searchName: 'Shinx (NXD 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Shinx',
    tcgApiId: 'bw4-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/43.png","large":"https://images.pokemontcg.io/bw4/43_hires.png"}',
    searchName: 'Shinx (NXD 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Luxio',
    tcgApiId: 'bw4-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/44.png","large":"https://images.pokemontcg.io/bw4/44_hires.png"}',
    searchName: 'Luxio (NXD 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Luxio',
    tcgApiId: 'bw4-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/45.png","large":"https://images.pokemontcg.io/bw4/45_hires.png"}',
    searchName: 'Luxio (NXD 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Luxray',
    tcgApiId: 'bw4-46',
    number: '46',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/46.png","large":"https://images.pokemontcg.io/bw4/46_hires.png"}',
    searchName: 'Luxray (NXD 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Blitzle',
    tcgApiId: 'bw4-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/47.png","large":"https://images.pokemontcg.io/bw4/47_hires.png"}',
    searchName: 'Blitzle (NXD 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Zebstrika',
    tcgApiId: 'bw4-48',
    number: '48',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/48.png","large":"https://images.pokemontcg.io/bw4/48_hires.png"}',
    searchName: 'Zebstrika (NXD 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Emolga',
    tcgApiId: 'bw4-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/49.png","large":"https://images.pokemontcg.io/bw4/49_hires.png"}',
    searchName: 'Emolga (NXD 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Zekrom',
    tcgApiId: 'bw4-50',
    number: '50',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/50.png","large":"https://images.pokemontcg.io/bw4/50_hires.png"}',
    searchName: 'Zekrom (NXD 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Zekrom-EX',
    tcgApiId: 'bw4-51',
    number: '51',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/51.png","large":"https://images.pokemontcg.io/bw4/51_hires.png"}',
    searchName: 'Zekrom-EX (NXD 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Grimer',
    tcgApiId: 'bw4-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/52.png","large":"https://images.pokemontcg.io/bw4/52_hires.png"}',
    searchName: 'Grimer (NXD 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Muk',
    tcgApiId: 'bw4-53',
    number: '53',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/53.png","large":"https://images.pokemontcg.io/bw4/53_hires.png"}',
    searchName: 'Muk (NXD 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Mewtwo-EX',
    tcgApiId: 'bw4-54',
    number: '54',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/54.png","large":"https://images.pokemontcg.io/bw4/54_hires.png"}',
    searchName: 'Mewtwo-EX (NXD 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Ralts',
    tcgApiId: 'bw4-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/55.png","large":"https://images.pokemontcg.io/bw4/55_hires.png"}',
    searchName: 'Ralts (NXD 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Kirlia',
    tcgApiId: 'bw4-56',
    number: '56',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/56.png","large":"https://images.pokemontcg.io/bw4/56_hires.png"}',
    searchName: 'Kirlia (NXD 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Gardevoir',
    tcgApiId: 'bw4-57',
    number: '57',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/57.png","large":"https://images.pokemontcg.io/bw4/57_hires.png"}',
    searchName: 'Gardevoir (NXD 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Munna',
    tcgApiId: 'bw4-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/58.png","large":"https://images.pokemontcg.io/bw4/58_hires.png"}',
    searchName: 'Munna (NXD 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Musharna',
    tcgApiId: 'bw4-59',
    number: '59',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/59.png","large":"https://images.pokemontcg.io/bw4/59_hires.png"}',
    searchName: 'Musharna (NXD 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Darmanitan',
    tcgApiId: 'bw4-60',
    number: '60',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/60.png","large":"https://images.pokemontcg.io/bw4/60_hires.png"}',
    searchName: 'Darmanitan (NXD 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Elgyem',
    tcgApiId: 'bw4-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/61.png","large":"https://images.pokemontcg.io/bw4/61_hires.png"}',
    searchName: 'Elgyem (NXD 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Beheeyem',
    tcgApiId: 'bw4-62',
    number: '62',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/62.png","large":"https://images.pokemontcg.io/bw4/62_hires.png"}',
    searchName: 'Beheeyem (NXD 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Riolu',
    tcgApiId: 'bw4-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/63.png","large":"https://images.pokemontcg.io/bw4/63_hires.png"}',
    searchName: 'Riolu (NXD 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Lucario',
    tcgApiId: 'bw4-64',
    number: '64',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/64.png","large":"https://images.pokemontcg.io/bw4/64_hires.png"}',
    searchName: 'Lucario (NXD 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Hippopotas',
    tcgApiId: 'bw4-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/65.png","large":"https://images.pokemontcg.io/bw4/65_hires.png"}',
    searchName: 'Hippopotas (NXD 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Hippowdon',
    tcgApiId: 'bw4-66',
    number: '66',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/66.png","large":"https://images.pokemontcg.io/bw4/66_hires.png"}',
    searchName: 'Hippowdon (NXD 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Mienfoo',
    tcgApiId: 'bw4-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/67.png","large":"https://images.pokemontcg.io/bw4/67_hires.png"}',
    searchName: 'Mienfoo (NXD 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Mienshao',
    tcgApiId: 'bw4-68',
    number: '68',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/68.png","large":"https://images.pokemontcg.io/bw4/68_hires.png"}',
    searchName: 'Mienshao (NXD 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Sneasel',
    tcgApiId: 'bw4-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/69.png","large":"https://images.pokemontcg.io/bw4/69_hires.png"}',
    searchName: 'Sneasel (NXD 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Weavile',
    tcgApiId: 'bw4-70',
    number: '70',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/70.png","large":"https://images.pokemontcg.io/bw4/70_hires.png"}',
    searchName: 'Weavile (NXD 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Nuzleaf',
    tcgApiId: 'bw4-71',
    number: '71',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/71.png","large":"https://images.pokemontcg.io/bw4/71_hires.png"}',
    searchName: 'Nuzleaf (NXD 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Shiftry',
    tcgApiId: 'bw4-72',
    number: '72',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/72.png","large":"https://images.pokemontcg.io/bw4/72_hires.png"}',
    searchName: 'Shiftry (NXD 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Scraggy',
    tcgApiId: 'bw4-73',
    number: '73',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/73.png","large":"https://images.pokemontcg.io/bw4/73_hires.png"}',
    searchName: 'Scraggy (NXD 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Scrafty',
    tcgApiId: 'bw4-74',
    number: '74',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/74.png","large":"https://images.pokemontcg.io/bw4/74_hires.png"}',
    searchName: 'Scrafty (NXD 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Bronzor',
    tcgApiId: 'bw4-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/75.png","large":"https://images.pokemontcg.io/bw4/75_hires.png"}',
    searchName: 'Bronzor (NXD 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Bronzong',
    tcgApiId: 'bw4-76',
    number: '76',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/76.png","large":"https://images.pokemontcg.io/bw4/76_hires.png"}',
    searchName: 'Bronzong (NXD 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Ferroseed',
    tcgApiId: 'bw4-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/77.png","large":"https://images.pokemontcg.io/bw4/77_hires.png"}',
    searchName: 'Ferroseed (NXD 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Jigglypuff',
    tcgApiId: 'bw4-78',
    number: '78',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/78.png","large":"https://images.pokemontcg.io/bw4/78_hires.png"}',
    searchName: 'Jigglypuff (NXD 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Wigglytuff',
    tcgApiId: 'bw4-79',
    number: '79',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/79.png","large":"https://images.pokemontcg.io/bw4/79_hires.png"}',
    searchName: 'Wigglytuff (NXD 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Meowth',
    tcgApiId: 'bw4-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/80.png","large":"https://images.pokemontcg.io/bw4/80_hires.png"}',
    searchName: 'Meowth (NXD 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Persian',
    tcgApiId: 'bw4-81',
    number: '81',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/81.png","large":"https://images.pokemontcg.io/bw4/81_hires.png"}',
    searchName: 'Persian (NXD 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Regigigas-EX',
    tcgApiId: 'bw4-82',
    number: '82',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/82.png","large":"https://images.pokemontcg.io/bw4/82_hires.png"}',
    searchName: 'Regigigas-EX (NXD 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Pidove',
    tcgApiId: 'bw4-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/83.png","large":"https://images.pokemontcg.io/bw4/83_hires.png"}',
    searchName: 'Pidove (NXD 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Minccino',
    tcgApiId: 'bw4-84',
    number: '84',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/84.png","large":"https://images.pokemontcg.io/bw4/84_hires.png"}',
    searchName: 'Minccino (NXD 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Cinccino',
    tcgApiId: 'bw4-85',
    number: '85',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/85.png","large":"https://images.pokemontcg.io/bw4/85_hires.png"}',
    searchName: 'Cinccino (NXD 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Cilan',
    tcgApiId: 'bw4-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/86.png","large":"https://images.pokemontcg.io/bw4/86_hires.png"}',
    searchName: 'Cilan (NXD 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Exp. Share',
    tcgApiId: 'bw4-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/87.png","large":"https://images.pokemontcg.io/bw4/87_hires.png"}',
    searchName: 'Exp. Share (NXD 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Heavy Ball',
    tcgApiId: 'bw4-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/88.png","large":"https://images.pokemontcg.io/bw4/88_hires.png"}',
    searchName: 'Heavy Ball (NXD 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Level Ball',
    tcgApiId: 'bw4-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/89.png","large":"https://images.pokemontcg.io/bw4/89_hires.png"}',
    searchName: 'Level Ball (NXD 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Pokémon Center',
    tcgApiId: 'bw4-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/90.png","large":"https://images.pokemontcg.io/bw4/90_hires.png"}',
    searchName: 'Pokémon Center (NXD 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Skyarrow Bridge',
    tcgApiId: 'bw4-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/91.png","large":"https://images.pokemontcg.io/bw4/91_hires.png"}',
    searchName: 'Skyarrow Bridge (NXD 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Double Colorless Energy',
    tcgApiId: 'bw4-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/92.png","large":"https://images.pokemontcg.io/bw4/92_hires.png"}',
    searchName: 'Double Colorless Energy (NXD 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Prism Energy',
    tcgApiId: 'bw4-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/93.png","large":"https://images.pokemontcg.io/bw4/93_hires.png"}',
    searchName: 'Prism Energy (NXD 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Shaymin-EX',
    tcgApiId: 'bw4-94',
    number: '94',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/94.png","large":"https://images.pokemontcg.io/bw4/94_hires.png"}',
    searchName: 'Shaymin-EX (NXD 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Reshiram-EX',
    tcgApiId: 'bw4-95',
    number: '95',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/95.png","large":"https://images.pokemontcg.io/bw4/95_hires.png"}',
    searchName: 'Reshiram-EX (NXD 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Kyurem-EX',
    tcgApiId: 'bw4-96',
    number: '96',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/96.png","large":"https://images.pokemontcg.io/bw4/96_hires.png"}',
    searchName: 'Kyurem-EX (NXD 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Zekrom-EX',
    tcgApiId: 'bw4-97',
    number: '97',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/97.png","large":"https://images.pokemontcg.io/bw4/97_hires.png"}',
    searchName: 'Zekrom-EX (NXD 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Mewtwo-EX',
    tcgApiId: 'bw4-98',
    number: '98',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/98.png","large":"https://images.pokemontcg.io/bw4/98_hires.png"}',
    searchName: 'Mewtwo-EX (NXD 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Regigigas-EX',
    tcgApiId: 'bw4-99',
    number: '99',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/99.png","large":"https://images.pokemontcg.io/bw4/99_hires.png"}',
    searchName: 'Regigigas-EX (NXD 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Emboar',
    tcgApiId: 'bw4-100',
    number: '100',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/100.png","large":"https://images.pokemontcg.io/bw4/100_hires.png"}',
    searchName: 'Emboar (NXD 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Chandelure',
    tcgApiId: 'bw4-101',
    number: '101',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/101.png","large":"https://images.pokemontcg.io/bw4/101_hires.png"}',
    searchName: 'Chandelure (NXD 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Zoroark',
    tcgApiId: 'bw4-102',
    number: '102',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/102.png","large":"https://images.pokemontcg.io/bw4/102_hires.png"}',
    searchName: 'Zoroark (NXD 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw4',
    name: 'Hydreigon',
    tcgApiId: 'bw4-103',
    number: '103',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw4/103.png","large":"https://images.pokemontcg.io/bw4/103_hires.png"}',
    searchName: 'Hydreigon (NXD 103)',
  },
];
