export const cardSeedBw7 = [
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Oddish',
    tcgApiId: 'bw7-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/1.png","large":"https://images.pokemontcg.io/bw7/1_hires.png"}',
    searchName: 'Oddish (BCR 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Gloom',
    tcgApiId: 'bw7-2',
    number: '2',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/2.png","large":"https://images.pokemontcg.io/bw7/2_hires.png"}',
    searchName: 'Gloom (BCR 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Vileplume',
    tcgApiId: 'bw7-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/3.png","large":"https://images.pokemontcg.io/bw7/3_hires.png"}',
    searchName: 'Vileplume (BCR 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Bellossom',
    tcgApiId: 'bw7-4',
    number: '4',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/4.png","large":"https://images.pokemontcg.io/bw7/4_hires.png"}',
    searchName: 'Bellossom (BCR 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Tangela',
    tcgApiId: 'bw7-5',
    number: '5',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/5.png","large":"https://images.pokemontcg.io/bw7/5_hires.png"}',
    searchName: 'Tangela (BCR 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Tangrowth',
    tcgApiId: 'bw7-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/6.png","large":"https://images.pokemontcg.io/bw7/6_hires.png"}',
    searchName: 'Tangrowth (BCR 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Scyther',
    tcgApiId: 'bw7-7',
    number: '7',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/7.png","large":"https://images.pokemontcg.io/bw7/7_hires.png"}',
    searchName: 'Scyther (BCR 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Heracross',
    tcgApiId: 'bw7-8',
    number: '8',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/8.png","large":"https://images.pokemontcg.io/bw7/8_hires.png"}',
    searchName: 'Heracross (BCR 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Celebi-EX',
    tcgApiId: 'bw7-9',
    number: '9',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/9.png","large":"https://images.pokemontcg.io/bw7/9_hires.png"}',
    searchName: 'Celebi-EX (BCR 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Shaymin',
    tcgApiId: 'bw7-10',
    number: '10',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/10.png","large":"https://images.pokemontcg.io/bw7/10_hires.png"}',
    searchName: 'Shaymin (BCR 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Snivy',
    tcgApiId: 'bw7-11',
    number: '11',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/11.png","large":"https://images.pokemontcg.io/bw7/11_hires.png"}',
    searchName: 'Snivy (BCR 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Servine',
    tcgApiId: 'bw7-12',
    number: '12',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/12.png","large":"https://images.pokemontcg.io/bw7/12_hires.png"}',
    searchName: 'Servine (BCR 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Serperior',
    tcgApiId: 'bw7-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/13.png","large":"https://images.pokemontcg.io/bw7/13_hires.png"}',
    searchName: 'Serperior (BCR 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Cottonee',
    tcgApiId: 'bw7-14',
    number: '14',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/14.png","large":"https://images.pokemontcg.io/bw7/14_hires.png"}',
    searchName: 'Cottonee (BCR 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Whimsicott',
    tcgApiId: 'bw7-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/15.png","large":"https://images.pokemontcg.io/bw7/15_hires.png"}',
    searchName: 'Whimsicott (BCR 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Petilil',
    tcgApiId: 'bw7-16',
    number: '16',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/16.png","large":"https://images.pokemontcg.io/bw7/16_hires.png"}',
    searchName: 'Petilil (BCR 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Lilligant',
    tcgApiId: 'bw7-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/17.png","large":"https://images.pokemontcg.io/bw7/17_hires.png"}',
    searchName: 'Lilligant (BCR 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Charmander',
    tcgApiId: 'bw7-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/18.png","large":"https://images.pokemontcg.io/bw7/18_hires.png"}',
    searchName: 'Charmander (BCR 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Charmeleon',
    tcgApiId: 'bw7-19',
    number: '19',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/19.png","large":"https://images.pokemontcg.io/bw7/19_hires.png"}',
    searchName: 'Charmeleon (BCR 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Charizard',
    tcgApiId: 'bw7-20',
    number: '20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/20.png","large":"https://images.pokemontcg.io/bw7/20_hires.png"}',
    searchName: 'Charizard (BCR 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Numel',
    tcgApiId: 'bw7-21',
    number: '21',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/21.png","large":"https://images.pokemontcg.io/bw7/21_hires.png"}',
    searchName: 'Numel (BCR 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Camerupt',
    tcgApiId: 'bw7-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/22.png","large":"https://images.pokemontcg.io/bw7/22_hires.png"}',
    searchName: 'Camerupt (BCR 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Victini',
    tcgApiId: 'bw7-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/23.png","large":"https://images.pokemontcg.io/bw7/23_hires.png"}',
    searchName: 'Victini (BCR 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Tepig',
    tcgApiId: 'bw7-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/24.png","large":"https://images.pokemontcg.io/bw7/24_hires.png"}',
    searchName: 'Tepig (BCR 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Pignite',
    tcgApiId: 'bw7-25',
    number: '25',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/25.png","large":"https://images.pokemontcg.io/bw7/25_hires.png"}',
    searchName: 'Pignite (BCR 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Emboar',
    tcgApiId: 'bw7-26',
    number: '26',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/26.png","large":"https://images.pokemontcg.io/bw7/26_hires.png"}',
    searchName: 'Emboar (BCR 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Darumaka',
    tcgApiId: 'bw7-27',
    number: '27',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/27.png","large":"https://images.pokemontcg.io/bw7/27_hires.png"}',
    searchName: 'Darumaka (BCR 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Darmanitan',
    tcgApiId: 'bw7-28',
    number: '28',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/28.png","large":"https://images.pokemontcg.io/bw7/28_hires.png"}',
    searchName: 'Darmanitan (BCR 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Squirtle',
    tcgApiId: 'bw7-29',
    number: '29',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/29.png","large":"https://images.pokemontcg.io/bw7/29_hires.png"}',
    searchName: 'Squirtle (BCR 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Wartortle',
    tcgApiId: 'bw7-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/30.png","large":"https://images.pokemontcg.io/bw7/30_hires.png"}',
    searchName: 'Wartortle (BCR 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Blastoise',
    tcgApiId: 'bw7-31',
    number: '31',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/31.png","large":"https://images.pokemontcg.io/bw7/31_hires.png"}',
    searchName: 'Blastoise (BCR 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Psyduck',
    tcgApiId: 'bw7-32',
    number: '32',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/32.png","large":"https://images.pokemontcg.io/bw7/32_hires.png"}',
    searchName: 'Psyduck (BCR 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Psyduck',
    tcgApiId: 'bw7-33',
    number: '33',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/33.png","large":"https://images.pokemontcg.io/bw7/33_hires.png"}',
    searchName: 'Psyduck (BCR 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Golduck',
    tcgApiId: 'bw7-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/34.png","large":"https://images.pokemontcg.io/bw7/34_hires.png"}',
    searchName: 'Golduck (BCR 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Golduck',
    tcgApiId: 'bw7-35',
    number: '35',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/35.png","large":"https://images.pokemontcg.io/bw7/35_hires.png"}',
    searchName: 'Golduck (BCR 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Marill',
    tcgApiId: 'bw7-36',
    number: '36',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/36.png","large":"https://images.pokemontcg.io/bw7/36_hires.png"}',
    searchName: 'Marill (BCR 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Azumarill',
    tcgApiId: 'bw7-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/37.png","large":"https://images.pokemontcg.io/bw7/37_hires.png"}',
    searchName: 'Azumarill (BCR 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Delibird',
    tcgApiId: 'bw7-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/38.png","large":"https://images.pokemontcg.io/bw7/38_hires.png"}',
    searchName: 'Delibird (BCR 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Oshawott',
    tcgApiId: 'bw7-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/39.png","large":"https://images.pokemontcg.io/bw7/39_hires.png"}',
    searchName: 'Oshawott (BCR 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Dewott',
    tcgApiId: 'bw7-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/40.png","large":"https://images.pokemontcg.io/bw7/40_hires.png"}',
    searchName: 'Dewott (BCR 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Samurott',
    tcgApiId: 'bw7-41',
    number: '41',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/41.png","large":"https://images.pokemontcg.io/bw7/41_hires.png"}',
    searchName: 'Samurott (BCR 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Ducklett',
    tcgApiId: 'bw7-42',
    number: '42',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/42.png","large":"https://images.pokemontcg.io/bw7/42_hires.png"}',
    searchName: 'Ducklett (BCR 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Swanna',
    tcgApiId: 'bw7-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/43.png","large":"https://images.pokemontcg.io/bw7/43_hires.png"}',
    searchName: 'Swanna (BCR 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Frillish',
    tcgApiId: 'bw7-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/44.png","large":"https://images.pokemontcg.io/bw7/44_hires.png"}',
    searchName: 'Frillish (BCR 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Jellicent',
    tcgApiId: 'bw7-45',
    number: '45',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/45.png","large":"https://images.pokemontcg.io/bw7/45_hires.png"}',
    searchName: 'Jellicent (BCR 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Cryogonal',
    tcgApiId: 'bw7-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/46.png","large":"https://images.pokemontcg.io/bw7/46_hires.png"}',
    searchName: 'Cryogonal (BCR 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Keldeo',
    tcgApiId: 'bw7-47',
    number: '47',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/47.png","large":"https://images.pokemontcg.io/bw7/47_hires.png"}',
    searchName: 'Keldeo (BCR 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Keldeo',
    tcgApiId: 'bw7-48',
    number: '48',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/48.png","large":"https://images.pokemontcg.io/bw7/48_hires.png"}',
    searchName: 'Keldeo (BCR 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Keldeo-EX',
    tcgApiId: 'bw7-49',
    number: '49',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/49.png","large":"https://images.pokemontcg.io/bw7/49_hires.png"}',
    searchName: 'Keldeo-EX (BCR 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Pikachu',
    tcgApiId: 'bw7-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/50.png","large":"https://images.pokemontcg.io/bw7/50_hires.png"}',
    searchName: 'Pikachu (BCR 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Voltorb',
    tcgApiId: 'bw7-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/51.png","large":"https://images.pokemontcg.io/bw7/51_hires.png"}',
    searchName: 'Voltorb (BCR 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Electrode',
    tcgApiId: 'bw7-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/52.png","large":"https://images.pokemontcg.io/bw7/52_hires.png"}',
    searchName: 'Electrode (BCR 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Electabuzz',
    tcgApiId: 'bw7-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/53.png","large":"https://images.pokemontcg.io/bw7/53_hires.png"}',
    searchName: 'Electabuzz (BCR 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Electivire',
    tcgApiId: 'bw7-54',
    number: '54',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/54.png","large":"https://images.pokemontcg.io/bw7/54_hires.png"}',
    searchName: 'Electivire (BCR 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Chinchou',
    tcgApiId: 'bw7-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/55.png","large":"https://images.pokemontcg.io/bw7/55_hires.png"}',
    searchName: 'Chinchou (BCR 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Blitzle',
    tcgApiId: 'bw7-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/56.png","large":"https://images.pokemontcg.io/bw7/56_hires.png"}',
    searchName: 'Blitzle (BCR 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Zebstrika',
    tcgApiId: 'bw7-57',
    number: '57',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/57.png","large":"https://images.pokemontcg.io/bw7/57_hires.png"}',
    searchName: 'Zebstrika (BCR 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Wobbuffet',
    tcgApiId: 'bw7-58',
    number: '58',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/58.png","large":"https://images.pokemontcg.io/bw7/58_hires.png"}',
    searchName: 'Wobbuffet (BCR 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Spoink',
    tcgApiId: 'bw7-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/59.png","large":"https://images.pokemontcg.io/bw7/59_hires.png"}',
    searchName: 'Spoink (BCR 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Grumpig',
    tcgApiId: 'bw7-60',
    number: '60',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/60.png","large":"https://images.pokemontcg.io/bw7/60_hires.png"}',
    searchName: 'Grumpig (BCR 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Duskull',
    tcgApiId: 'bw7-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/61.png","large":"https://images.pokemontcg.io/bw7/61_hires.png"}',
    searchName: 'Duskull (BCR 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Dusclops',
    tcgApiId: 'bw7-62',
    number: '62',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/62.png","large":"https://images.pokemontcg.io/bw7/62_hires.png"}',
    searchName: 'Dusclops (BCR 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Dusknoir',
    tcgApiId: 'bw7-63',
    number: '63',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/63.png","large":"https://images.pokemontcg.io/bw7/63_hires.png"}',
    searchName: 'Dusknoir (BCR 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Croagunk',
    tcgApiId: 'bw7-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/64.png","large":"https://images.pokemontcg.io/bw7/64_hires.png"}',
    searchName: 'Croagunk (BCR 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Croagunk',
    tcgApiId: 'bw7-65',
    number: '65',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/65.png","large":"https://images.pokemontcg.io/bw7/65_hires.png"}',
    searchName: 'Croagunk (BCR 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Toxicroak',
    tcgApiId: 'bw7-66',
    number: '66',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/66.png","large":"https://images.pokemontcg.io/bw7/66_hires.png"}',
    searchName: 'Toxicroak (BCR 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Cresselia-EX',
    tcgApiId: 'bw7-67',
    number: '67',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/67.png","large":"https://images.pokemontcg.io/bw7/67_hires.png"}',
    searchName: 'Cresselia-EX (BCR 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Munna',
    tcgApiId: 'bw7-68',
    number: '68',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/68.png","large":"https://images.pokemontcg.io/bw7/68_hires.png"}',
    searchName: 'Munna (BCR 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Musharna',
    tcgApiId: 'bw7-69',
    number: '69',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/69.png","large":"https://images.pokemontcg.io/bw7/69_hires.png"}',
    searchName: 'Musharna (BCR 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Woobat',
    tcgApiId: 'bw7-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/70.png","large":"https://images.pokemontcg.io/bw7/70_hires.png"}',
    searchName: 'Woobat (BCR 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Swoobat',
    tcgApiId: 'bw7-71',
    number: '71',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/71.png","large":"https://images.pokemontcg.io/bw7/71_hires.png"}',
    searchName: 'Swoobat (BCR 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Venipede',
    tcgApiId: 'bw7-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/72.png","large":"https://images.pokemontcg.io/bw7/72_hires.png"}',
    searchName: 'Venipede (BCR 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Whirlipede',
    tcgApiId: 'bw7-73',
    number: '73',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/73.png","large":"https://images.pokemontcg.io/bw7/73_hires.png"}',
    searchName: 'Whirlipede (BCR 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Scolipede',
    tcgApiId: 'bw7-74',
    number: '74',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/74.png","large":"https://images.pokemontcg.io/bw7/74_hires.png"}',
    searchName: 'Scolipede (BCR 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Gothita',
    tcgApiId: 'bw7-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/75.png","large":"https://images.pokemontcg.io/bw7/75_hires.png"}',
    searchName: 'Gothita (BCR 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Gothorita',
    tcgApiId: 'bw7-76',
    number: '76',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/76.png","large":"https://images.pokemontcg.io/bw7/76_hires.png"}',
    searchName: 'Gothorita (BCR 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Meloetta',
    tcgApiId: 'bw7-77',
    number: '77',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/77.png","large":"https://images.pokemontcg.io/bw7/77_hires.png"}',
    searchName: 'Meloetta (BCR 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Sandshrew',
    tcgApiId: 'bw7-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/78.png","large":"https://images.pokemontcg.io/bw7/78_hires.png"}',
    searchName: 'Sandshrew (BCR 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Sandslash',
    tcgApiId: 'bw7-79',
    number: '79',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/79.png","large":"https://images.pokemontcg.io/bw7/79_hires.png"}',
    searchName: 'Sandslash (BCR 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Gligar',
    tcgApiId: 'bw7-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/80.png","large":"https://images.pokemontcg.io/bw7/80_hires.png"}',
    searchName: 'Gligar (BCR 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Gliscor',
    tcgApiId: 'bw7-81',
    number: '81',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/81.png","large":"https://images.pokemontcg.io/bw7/81_hires.png"}',
    searchName: 'Gliscor (BCR 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Makuhita',
    tcgApiId: 'bw7-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/82.png","large":"https://images.pokemontcg.io/bw7/82_hires.png"}',
    searchName: 'Makuhita (BCR 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Trapinch',
    tcgApiId: 'bw7-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/83.png","large":"https://images.pokemontcg.io/bw7/83_hires.png"}',
    searchName: 'Trapinch (BCR 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Dwebble',
    tcgApiId: 'bw7-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/84.png","large":"https://images.pokemontcg.io/bw7/84_hires.png"}',
    searchName: 'Dwebble (BCR 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Crustle',
    tcgApiId: 'bw7-85',
    number: '85',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/85.png","large":"https://images.pokemontcg.io/bw7/85_hires.png"}',
    searchName: 'Crustle (BCR 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Mienfoo',
    tcgApiId: 'bw7-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/86.png","large":"https://images.pokemontcg.io/bw7/86_hires.png"}',
    searchName: 'Mienfoo (BCR 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Mienfoo',
    tcgApiId: 'bw7-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/87.png","large":"https://images.pokemontcg.io/bw7/87_hires.png"}',
    searchName: 'Mienfoo (BCR 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Mienshao',
    tcgApiId: 'bw7-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/88.png","large":"https://images.pokemontcg.io/bw7/88_hires.png"}',
    searchName: 'Mienshao (BCR 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Landorus-EX',
    tcgApiId: 'bw7-89',
    number: '89',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/89.png","large":"https://images.pokemontcg.io/bw7/89_hires.png"}',
    searchName: 'Landorus-EX (BCR 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Purrloin',
    tcgApiId: 'bw7-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/90.png","large":"https://images.pokemontcg.io/bw7/90_hires.png"}',
    searchName: 'Purrloin (BCR 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Liepard',
    tcgApiId: 'bw7-91',
    number: '91',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/91.png","large":"https://images.pokemontcg.io/bw7/91_hires.png"}',
    searchName: 'Liepard (BCR 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Vullaby',
    tcgApiId: 'bw7-92',
    number: '92',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/92.png","large":"https://images.pokemontcg.io/bw7/92_hires.png"}',
    searchName: 'Vullaby (BCR 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Mandibuzz',
    tcgApiId: 'bw7-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/93.png","large":"https://images.pokemontcg.io/bw7/93_hires.png"}',
    searchName: 'Mandibuzz (BCR 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Scizor',
    tcgApiId: 'bw7-94',
    number: '94',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/94.png","large":"https://images.pokemontcg.io/bw7/94_hires.png"}',
    searchName: 'Scizor (BCR 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Skarmory',
    tcgApiId: 'bw7-95',
    number: '95',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/95.png","large":"https://images.pokemontcg.io/bw7/95_hires.png"}',
    searchName: 'Skarmory (BCR 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Skarmory',
    tcgApiId: 'bw7-96',
    number: '96',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/96.png","large":"https://images.pokemontcg.io/bw7/96_hires.png"}',
    searchName: 'Skarmory (BCR 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Klink',
    tcgApiId: 'bw7-97',
    number: '97',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/97.png","large":"https://images.pokemontcg.io/bw7/97_hires.png"}',
    searchName: 'Klink (BCR 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Vibrava',
    tcgApiId: 'bw7-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/98.png","large":"https://images.pokemontcg.io/bw7/98_hires.png"}',
    searchName: 'Vibrava (BCR 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Flygon',
    tcgApiId: 'bw7-99',
    number: '99',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/99.png","large":"https://images.pokemontcg.io/bw7/99_hires.png"}',
    searchName: 'Flygon (BCR 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Black Kyurem',
    tcgApiId: 'bw7-100',
    number: '100',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/100.png","large":"https://images.pokemontcg.io/bw7/100_hires.png"}',
    searchName: 'Black Kyurem (BCR 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Black Kyurem-EX',
    tcgApiId: 'bw7-101',
    number: '101',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/101.png","large":"https://images.pokemontcg.io/bw7/101_hires.png"}',
    searchName: 'Black Kyurem-EX (BCR 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'White Kyurem',
    tcgApiId: 'bw7-102',
    number: '102',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/102.png","large":"https://images.pokemontcg.io/bw7/102_hires.png"}',
    searchName: 'White Kyurem (BCR 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'White Kyurem-EX',
    tcgApiId: 'bw7-103',
    number: '103',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/103.png","large":"https://images.pokemontcg.io/bw7/103_hires.png"}',
    searchName: 'White Kyurem-EX (BCR 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Rattata',
    tcgApiId: 'bw7-104',
    number: '104',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/104.png","large":"https://images.pokemontcg.io/bw7/104_hires.png"}',
    searchName: 'Rattata (BCR 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Raticate',
    tcgApiId: 'bw7-105',
    number: '105',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/105.png","large":"https://images.pokemontcg.io/bw7/105_hires.png"}',
    searchName: 'Raticate (BCR 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Meowth',
    tcgApiId: 'bw7-106',
    number: '106',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/106.png","large":"https://images.pokemontcg.io/bw7/106_hires.png"}',
    searchName: 'Meowth (BCR 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: "Farfetch'd",
    tcgApiId: 'bw7-107',
    number: '107',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/107.png","large":"https://images.pokemontcg.io/bw7/107_hires.png"}',
    searchName: "Farfetch'd (BCR 107)",
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Ditto',
    tcgApiId: 'bw7-108',
    number: '108',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/108.png","large":"https://images.pokemontcg.io/bw7/108_hires.png"}',
    searchName: 'Ditto (BCR 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Snorlax',
    tcgApiId: 'bw7-109',
    number: '109',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/109.png","large":"https://images.pokemontcg.io/bw7/109_hires.png"}',
    searchName: 'Snorlax (BCR 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Togepi',
    tcgApiId: 'bw7-110',
    number: '110',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/110.png","large":"https://images.pokemontcg.io/bw7/110_hires.png"}',
    searchName: 'Togepi (BCR 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Dunsparce',
    tcgApiId: 'bw7-111',
    number: '111',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/111.png","large":"https://images.pokemontcg.io/bw7/111_hires.png"}',
    searchName: 'Dunsparce (BCR 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Taillow',
    tcgApiId: 'bw7-112',
    number: '112',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/112.png","large":"https://images.pokemontcg.io/bw7/112_hires.png"}',
    searchName: 'Taillow (BCR 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Skitty',
    tcgApiId: 'bw7-113',
    number: '113',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/113.png","large":"https://images.pokemontcg.io/bw7/113_hires.png"}',
    searchName: 'Skitty (BCR 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Delcatty',
    tcgApiId: 'bw7-114',
    number: '114',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/114.png","large":"https://images.pokemontcg.io/bw7/114_hires.png"}',
    searchName: 'Delcatty (BCR 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Spinda',
    tcgApiId: 'bw7-115',
    number: '115',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/115.png","large":"https://images.pokemontcg.io/bw7/115_hires.png"}',
    searchName: 'Spinda (BCR 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Buneary',
    tcgApiId: 'bw7-116',
    number: '116',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/116.png","large":"https://images.pokemontcg.io/bw7/116_hires.png"}',
    searchName: 'Buneary (BCR 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Lopunny',
    tcgApiId: 'bw7-117',
    number: '117',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/117.png","large":"https://images.pokemontcg.io/bw7/117_hires.png"}',
    searchName: 'Lopunny (BCR 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Patrat',
    tcgApiId: 'bw7-118',
    number: '118',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/118.png","large":"https://images.pokemontcg.io/bw7/118_hires.png"}',
    searchName: 'Patrat (BCR 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Watchog',
    tcgApiId: 'bw7-119',
    number: '119',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/119.png","large":"https://images.pokemontcg.io/bw7/119_hires.png"}',
    searchName: 'Watchog (BCR 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Lillipup',
    tcgApiId: 'bw7-120',
    number: '120',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/120.png","large":"https://images.pokemontcg.io/bw7/120_hires.png"}',
    searchName: 'Lillipup (BCR 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Herdier',
    tcgApiId: 'bw7-121',
    number: '121',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/121.png","large":"https://images.pokemontcg.io/bw7/121_hires.png"}',
    searchName: 'Herdier (BCR 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Stoutland',
    tcgApiId: 'bw7-122',
    number: '122',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/122.png","large":"https://images.pokemontcg.io/bw7/122_hires.png"}',
    searchName: 'Stoutland (BCR 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Pidove',
    tcgApiId: 'bw7-123',
    number: '123',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/123.png","large":"https://images.pokemontcg.io/bw7/123_hires.png"}',
    searchName: 'Pidove (BCR 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Tranquill',
    tcgApiId: 'bw7-124',
    number: '124',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/124.png","large":"https://images.pokemontcg.io/bw7/124_hires.png"}',
    searchName: 'Tranquill (BCR 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Unfezant',
    tcgApiId: 'bw7-125',
    number: '125',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/125.png","large":"https://images.pokemontcg.io/bw7/125_hires.png"}',
    searchName: 'Unfezant (BCR 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Audino',
    tcgApiId: 'bw7-126',
    number: '126',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/126.png","large":"https://images.pokemontcg.io/bw7/126_hires.png"}',
    searchName: 'Audino (BCR 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Aspertia City Gym',
    tcgApiId: 'bw7-127',
    number: '127',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/127.png","large":"https://images.pokemontcg.io/bw7/127_hires.png"}',
    searchName: 'Aspertia City Gym (BCR 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Energy Search',
    tcgApiId: 'bw7-128',
    number: '128',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/128.png","large":"https://images.pokemontcg.io/bw7/128_hires.png"}',
    searchName: 'Energy Search (BCR 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Great Ball',
    tcgApiId: 'bw7-129',
    number: '129',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/129.png","large":"https://images.pokemontcg.io/bw7/129_hires.png"}',
    searchName: 'Great Ball (BCR 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Hugh',
    tcgApiId: 'bw7-130',
    number: '130',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/130.png","large":"https://images.pokemontcg.io/bw7/130_hires.png"}',
    searchName: 'Hugh (BCR 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Poké Ball',
    tcgApiId: 'bw7-131',
    number: '131',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/131.png","large":"https://images.pokemontcg.io/bw7/131_hires.png"}',
    searchName: 'Poké Ball (BCR 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Potion',
    tcgApiId: 'bw7-132',
    number: '132',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/132.png","large":"https://images.pokemontcg.io/bw7/132_hires.png"}',
    searchName: 'Potion (BCR 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Rocky Helmet',
    tcgApiId: 'bw7-133',
    number: '133',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/133.png","large":"https://images.pokemontcg.io/bw7/133_hires.png"}',
    searchName: 'Rocky Helmet (BCR 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Skyla',
    tcgApiId: 'bw7-134',
    number: '134',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/134.png","large":"https://images.pokemontcg.io/bw7/134_hires.png"}',
    searchName: 'Skyla (BCR 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Switch',
    tcgApiId: 'bw7-135',
    number: '135',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/135.png","large":"https://images.pokemontcg.io/bw7/135_hires.png"}',
    searchName: 'Switch (BCR 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Town Map',
    tcgApiId: 'bw7-136',
    number: '136',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/136.png","large":"https://images.pokemontcg.io/bw7/136_hires.png"}',
    searchName: 'Town Map (BCR 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Computer Search',
    tcgApiId: 'bw7-137',
    number: '137',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/137.png","large":"https://images.pokemontcg.io/bw7/137_hires.png"}',
    searchName: 'Computer Search (BCR 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Crystal Edge',
    tcgApiId: 'bw7-138',
    number: '138',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/138.png","large":"https://images.pokemontcg.io/bw7/138_hires.png"}',
    searchName: 'Crystal Edge (BCR 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Crystal Wall',
    tcgApiId: 'bw7-139',
    number: '139',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/139.png","large":"https://images.pokemontcg.io/bw7/139_hires.png"}',
    searchName: 'Crystal Wall (BCR 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Gold Potion',
    tcgApiId: 'bw7-140',
    number: '140',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/140.png","large":"https://images.pokemontcg.io/bw7/140_hires.png"}',
    searchName: 'Gold Potion (BCR 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Celebi-EX',
    tcgApiId: 'bw7-141',
    number: '141',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/141.png","large":"https://images.pokemontcg.io/bw7/141_hires.png"}',
    searchName: 'Celebi-EX (BCR 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Keldeo-EX',
    tcgApiId: 'bw7-142',
    number: '142',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/142.png","large":"https://images.pokemontcg.io/bw7/142_hires.png"}',
    searchName: 'Keldeo-EX (BCR 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Cresselia-EX',
    tcgApiId: 'bw7-143',
    number: '143',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/143.png","large":"https://images.pokemontcg.io/bw7/143_hires.png"}',
    searchName: 'Cresselia-EX (BCR 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Landorus-EX',
    tcgApiId: 'bw7-144',
    number: '144',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/144.png","large":"https://images.pokemontcg.io/bw7/144_hires.png"}',
    searchName: 'Landorus-EX (BCR 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Black Kyurem-EX',
    tcgApiId: 'bw7-145',
    number: '145',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/145.png","large":"https://images.pokemontcg.io/bw7/145_hires.png"}',
    searchName: 'Black Kyurem-EX (BCR 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'White Kyurem-EX',
    tcgApiId: 'bw7-146',
    number: '146',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/146.png","large":"https://images.pokemontcg.io/bw7/146_hires.png"}',
    searchName: 'White Kyurem-EX (BCR 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Bianca',
    tcgApiId: 'bw7-147',
    number: '147',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/147.png","large":"https://images.pokemontcg.io/bw7/147_hires.png"}',
    searchName: 'Bianca (BCR 147)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Cheren',
    tcgApiId: 'bw7-148',
    number: '148',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/148.png","large":"https://images.pokemontcg.io/bw7/148_hires.png"}',
    searchName: 'Cheren (BCR 148)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Skyla',
    tcgApiId: 'bw7-149',
    number: '149',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/149.png","large":"https://images.pokemontcg.io/bw7/149_hires.png"}',
    searchName: 'Skyla (BCR 149)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Golurk',
    tcgApiId: 'bw7-150',
    number: '150',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/150.png","large":"https://images.pokemontcg.io/bw7/150_hires.png"}',
    searchName: 'Golurk (BCR 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Terrakion',
    tcgApiId: 'bw7-151',
    number: '151',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/151.png","large":"https://images.pokemontcg.io/bw7/151_hires.png"}',
    searchName: 'Terrakion (BCR 151)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Altaria',
    tcgApiId: 'bw7-152',
    number: '152',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/152.png","large":"https://images.pokemontcg.io/bw7/152_hires.png"}',
    searchName: 'Altaria (BCR 152)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw7',
    name: 'Rocky Helmet',
    tcgApiId: 'bw7-153',
    number: '153',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw7/153.png","large":"https://images.pokemontcg.io/bw7/153_hires.png"}',
    searchName: 'Rocky Helmet (BCR 153)',
  },
];
