export const cardSeedBw8 = [
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Turtwig',
    tcgApiId: 'bw8-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/1.png","large":"https://images.pokemontcg.io/bw8/1_hires.png"}',
    searchName: 'Turtwig (PLS 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Grotle',
    tcgApiId: 'bw8-2',
    number: '2',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/2.png","large":"https://images.pokemontcg.io/bw8/2_hires.png"}',
    searchName: 'Grotle (PLS 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Torterra',
    tcgApiId: 'bw8-3',
    number: '3',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/3.png","large":"https://images.pokemontcg.io/bw8/3_hires.png"}',
    searchName: 'Torterra (PLS 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Combee',
    tcgApiId: 'bw8-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/4.png","large":"https://images.pokemontcg.io/bw8/4_hires.png"}',
    searchName: 'Combee (PLS 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Vespiquen',
    tcgApiId: 'bw8-5',
    number: '5',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/5.png","large":"https://images.pokemontcg.io/bw8/5_hires.png"}',
    searchName: 'Vespiquen (PLS 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Cherubi',
    tcgApiId: 'bw8-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/6.png","large":"https://images.pokemontcg.io/bw8/6_hires.png"}',
    searchName: 'Cherubi (PLS 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Cherrim',
    tcgApiId: 'bw8-7',
    number: '7',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/7.png","large":"https://images.pokemontcg.io/bw8/7_hires.png"}',
    searchName: 'Cherrim (PLS 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Sewaddle',
    tcgApiId: 'bw8-8',
    number: '8',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/8.png","large":"https://images.pokemontcg.io/bw8/8_hires.png"}',
    searchName: 'Sewaddle (PLS 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Swadloon',
    tcgApiId: 'bw8-9',
    number: '9',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/9.png","large":"https://images.pokemontcg.io/bw8/9_hires.png"}',
    searchName: 'Swadloon (PLS 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Leavanny',
    tcgApiId: 'bw8-10',
    number: '10',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/10.png","large":"https://images.pokemontcg.io/bw8/10_hires.png"}',
    searchName: 'Leavanny (PLS 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Maractus',
    tcgApiId: 'bw8-11',
    number: '11',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/11.png","large":"https://images.pokemontcg.io/bw8/11_hires.png"}',
    searchName: 'Maractus (PLS 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Foongus',
    tcgApiId: 'bw8-12',
    number: '12',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/12.png","large":"https://images.pokemontcg.io/bw8/12_hires.png"}',
    searchName: 'Foongus (PLS 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Amoonguss',
    tcgApiId: 'bw8-13',
    number: '13',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/13.png","large":"https://images.pokemontcg.io/bw8/13_hires.png"}',
    searchName: 'Amoonguss (PLS 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Moltres-EX',
    tcgApiId: 'bw8-14',
    number: '14',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/14.png","large":"https://images.pokemontcg.io/bw8/14_hires.png"}',
    searchName: 'Moltres-EX (PLS 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Chimchar',
    tcgApiId: 'bw8-15',
    number: '15',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/15.png","large":"https://images.pokemontcg.io/bw8/15_hires.png"}',
    searchName: 'Chimchar (PLS 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Monferno',
    tcgApiId: 'bw8-16',
    number: '16',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/16.png","large":"https://images.pokemontcg.io/bw8/16_hires.png"}',
    searchName: 'Monferno (PLS 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Infernape',
    tcgApiId: 'bw8-17',
    number: '17',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/17.png","large":"https://images.pokemontcg.io/bw8/17_hires.png"}',
    searchName: 'Infernape (PLS 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Victini-EX',
    tcgApiId: 'bw8-18',
    number: '18',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/18.png","large":"https://images.pokemontcg.io/bw8/18_hires.png"}',
    searchName: 'Victini-EX (PLS 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Pansear',
    tcgApiId: 'bw8-19',
    number: '19',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/19.png","large":"https://images.pokemontcg.io/bw8/19_hires.png"}',
    searchName: 'Pansear (PLS 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Simisear',
    tcgApiId: 'bw8-20',
    number: '20',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/20.png","large":"https://images.pokemontcg.io/bw8/20_hires.png"}',
    searchName: 'Simisear (PLS 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Litwick',
    tcgApiId: 'bw8-21',
    number: '21',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/21.png","large":"https://images.pokemontcg.io/bw8/21_hires.png"}',
    searchName: 'Litwick (PLS 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Lampent',
    tcgApiId: 'bw8-22',
    number: '22',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/22.png","large":"https://images.pokemontcg.io/bw8/22_hires.png"}',
    searchName: 'Lampent (PLS 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Heatmor',
    tcgApiId: 'bw8-23',
    number: '23',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/23.png","large":"https://images.pokemontcg.io/bw8/23_hires.png"}',
    searchName: 'Heatmor (PLS 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Squirtle',
    tcgApiId: 'bw8-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/24.png","large":"https://images.pokemontcg.io/bw8/24_hires.png"}',
    searchName: 'Squirtle (PLS 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Articuno-EX',
    tcgApiId: 'bw8-25',
    number: '25',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/25.png","large":"https://images.pokemontcg.io/bw8/25_hires.png"}',
    searchName: 'Articuno-EX (PLS 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Swinub',
    tcgApiId: 'bw8-26',
    number: '26',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/26.png","large":"https://images.pokemontcg.io/bw8/26_hires.png"}',
    searchName: 'Swinub (PLS 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Piloswine',
    tcgApiId: 'bw8-27',
    number: '27',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/27.png","large":"https://images.pokemontcg.io/bw8/27_hires.png"}',
    searchName: 'Piloswine (PLS 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Mamoswine',
    tcgApiId: 'bw8-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/28.png","large":"https://images.pokemontcg.io/bw8/28_hires.png"}',
    searchName: 'Mamoswine (PLS 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Lotad',
    tcgApiId: 'bw8-29',
    number: '29',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/29.png","large":"https://images.pokemontcg.io/bw8/29_hires.png"}',
    searchName: 'Lotad (PLS 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Lombre',
    tcgApiId: 'bw8-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/30.png","large":"https://images.pokemontcg.io/bw8/30_hires.png"}',
    searchName: 'Lombre (PLS 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Ludicolo',
    tcgApiId: 'bw8-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/31.png","large":"https://images.pokemontcg.io/bw8/31_hires.png"}',
    searchName: 'Ludicolo (PLS 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Carvanha',
    tcgApiId: 'bw8-32',
    number: '32',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/32.png","large":"https://images.pokemontcg.io/bw8/32_hires.png"}',
    searchName: 'Carvanha (PLS 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Sharpedo',
    tcgApiId: 'bw8-33',
    number: '33',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/33.png","large":"https://images.pokemontcg.io/bw8/33_hires.png"}',
    searchName: 'Sharpedo (PLS 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Manaphy',
    tcgApiId: 'bw8-34',
    number: '34',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/34.png","large":"https://images.pokemontcg.io/bw8/34_hires.png"}',
    searchName: 'Manaphy (PLS 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Vanillite',
    tcgApiId: 'bw8-35',
    number: '35',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/35.png","large":"https://images.pokemontcg.io/bw8/35_hires.png"}',
    searchName: 'Vanillite (PLS 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Vanillish',
    tcgApiId: 'bw8-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/36.png","large":"https://images.pokemontcg.io/bw8/36_hires.png"}',
    searchName: 'Vanillish (PLS 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Vanilluxe',
    tcgApiId: 'bw8-37',
    number: '37',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/37.png","large":"https://images.pokemontcg.io/bw8/37_hires.png"}',
    searchName: 'Vanilluxe (PLS 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Frillish',
    tcgApiId: 'bw8-38',
    number: '38',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/38.png","large":"https://images.pokemontcg.io/bw8/38_hires.png"}',
    searchName: 'Frillish (PLS 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Jellicent',
    tcgApiId: 'bw8-39',
    number: '39',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/39.png","large":"https://images.pokemontcg.io/bw8/39_hires.png"}',
    searchName: 'Jellicent (PLS 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Cubchoo',
    tcgApiId: 'bw8-40',
    number: '40',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/40.png","large":"https://images.pokemontcg.io/bw8/40_hires.png"}',
    searchName: 'Cubchoo (PLS 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Beartic',
    tcgApiId: 'bw8-41',
    number: '41',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/41.png","large":"https://images.pokemontcg.io/bw8/41_hires.png"}',
    searchName: 'Beartic (PLS 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Magnemite',
    tcgApiId: 'bw8-42',
    number: '42',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/42.png","large":"https://images.pokemontcg.io/bw8/42_hires.png"}',
    searchName: 'Magnemite (PLS 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Magnemite',
    tcgApiId: 'bw8-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/43.png","large":"https://images.pokemontcg.io/bw8/43_hires.png"}',
    searchName: 'Magnemite (PLS 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Magneton',
    tcgApiId: 'bw8-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/44.png","large":"https://images.pokemontcg.io/bw8/44_hires.png"}',
    searchName: 'Magneton (PLS 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Magneton',
    tcgApiId: 'bw8-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/45.png","large":"https://images.pokemontcg.io/bw8/45_hires.png"}',
    searchName: 'Magneton (PLS 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Magnezone',
    tcgApiId: 'bw8-46',
    number: '46',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/46.png","large":"https://images.pokemontcg.io/bw8/46_hires.png"}',
    searchName: 'Magnezone (PLS 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Magnezone',
    tcgApiId: 'bw8-47',
    number: '47',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/47.png","large":"https://images.pokemontcg.io/bw8/47_hires.png"}',
    searchName: 'Magnezone (PLS 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Zapdos-EX',
    tcgApiId: 'bw8-48',
    number: '48',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/48.png","large":"https://images.pokemontcg.io/bw8/48_hires.png"}',
    searchName: 'Zapdos-EX (PLS 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Rotom',
    tcgApiId: 'bw8-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/49.png","large":"https://images.pokemontcg.io/bw8/49_hires.png"}',
    searchName: 'Rotom (PLS 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Joltik',
    tcgApiId: 'bw8-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/50.png","large":"https://images.pokemontcg.io/bw8/50_hires.png"}',
    searchName: 'Joltik (PLS 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Galvantula',
    tcgApiId: 'bw8-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/51.png","large":"https://images.pokemontcg.io/bw8/51_hires.png"}',
    searchName: 'Galvantula (PLS 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Zubat',
    tcgApiId: 'bw8-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/52.png","large":"https://images.pokemontcg.io/bw8/52_hires.png"}',
    searchName: 'Zubat (PLS 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Zubat',
    tcgApiId: 'bw8-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/53.png","large":"https://images.pokemontcg.io/bw8/53_hires.png"}',
    searchName: 'Zubat (PLS 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Golbat',
    tcgApiId: 'bw8-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/54.png","large":"https://images.pokemontcg.io/bw8/54_hires.png"}',
    searchName: 'Golbat (PLS 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Crobat',
    tcgApiId: 'bw8-55',
    number: '55',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/55.png","large":"https://images.pokemontcg.io/bw8/55_hires.png"}',
    searchName: 'Crobat (PLS 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Koffing',
    tcgApiId: 'bw8-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/56.png","large":"https://images.pokemontcg.io/bw8/56_hires.png"}',
    searchName: 'Koffing (PLS 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Koffing',
    tcgApiId: 'bw8-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/57.png","large":"https://images.pokemontcg.io/bw8/57_hires.png"}',
    searchName: 'Koffing (PLS 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Weezing',
    tcgApiId: 'bw8-58',
    number: '58',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/58.png","large":"https://images.pokemontcg.io/bw8/58_hires.png"}',
    searchName: 'Weezing (PLS 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Ralts',
    tcgApiId: 'bw8-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/59.png","large":"https://images.pokemontcg.io/bw8/59_hires.png"}',
    searchName: 'Ralts (PLS 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Kirlia',
    tcgApiId: 'bw8-60',
    number: '60',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/60.png","large":"https://images.pokemontcg.io/bw8/60_hires.png"}',
    searchName: 'Kirlia (PLS 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Gallade',
    tcgApiId: 'bw8-61',
    number: '61',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/61.png","large":"https://images.pokemontcg.io/bw8/61_hires.png"}',
    searchName: 'Gallade (PLS 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Giratina',
    tcgApiId: 'bw8-62',
    number: '62',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/62.png","large":"https://images.pokemontcg.io/bw8/62_hires.png"}',
    searchName: 'Giratina (PLS 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Trubbish',
    tcgApiId: 'bw8-63',
    number: '63',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/63.png","large":"https://images.pokemontcg.io/bw8/63_hires.png"}',
    searchName: 'Trubbish (PLS 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Trubbish',
    tcgApiId: 'bw8-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/64.png","large":"https://images.pokemontcg.io/bw8/64_hires.png"}',
    searchName: 'Trubbish (PLS 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Trubbish',
    tcgApiId: 'bw8-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/65.png","large":"https://images.pokemontcg.io/bw8/65_hires.png"}',
    searchName: 'Trubbish (PLS 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Garbodor',
    tcgApiId: 'bw8-66',
    number: '66',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/66.png","large":"https://images.pokemontcg.io/bw8/66_hires.png"}',
    searchName: 'Garbodor (PLS 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Garbodor',
    tcgApiId: 'bw8-67',
    number: '67',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/67.png","large":"https://images.pokemontcg.io/bw8/67_hires.png"}',
    searchName: 'Garbodor (PLS 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Elgyem',
    tcgApiId: 'bw8-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/68.png","large":"https://images.pokemontcg.io/bw8/68_hires.png"}',
    searchName: 'Elgyem (PLS 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Elgyem',
    tcgApiId: 'bw8-69',
    number: '69',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/69.png","large":"https://images.pokemontcg.io/bw8/69_hires.png"}',
    searchName: 'Elgyem (PLS 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Beheeyem',
    tcgApiId: 'bw8-70',
    number: '70',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/70.png","large":"https://images.pokemontcg.io/bw8/70_hires.png"}',
    searchName: 'Beheeyem (PLS 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Phanpy',
    tcgApiId: 'bw8-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/71.png","large":"https://images.pokemontcg.io/bw8/71_hires.png"}',
    searchName: 'Phanpy (PLS 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Donphan',
    tcgApiId: 'bw8-72',
    number: '72',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/72.png","large":"https://images.pokemontcg.io/bw8/72_hires.png"}',
    searchName: 'Donphan (PLS 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Lunatone',
    tcgApiId: 'bw8-73',
    number: '73',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/73.png","large":"https://images.pokemontcg.io/bw8/73_hires.png"}',
    searchName: 'Lunatone (PLS 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Solrock',
    tcgApiId: 'bw8-74',
    number: '74',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/74.png","large":"https://images.pokemontcg.io/bw8/74_hires.png"}',
    searchName: 'Solrock (PLS 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Riolu',
    tcgApiId: 'bw8-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/75.png","large":"https://images.pokemontcg.io/bw8/75_hires.png"}',
    searchName: 'Riolu (PLS 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Riolu',
    tcgApiId: 'bw8-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/76.png","large":"https://images.pokemontcg.io/bw8/76_hires.png"}',
    searchName: 'Riolu (PLS 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Lucario',
    tcgApiId: 'bw8-77',
    number: '77',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/77.png","large":"https://images.pokemontcg.io/bw8/77_hires.png"}',
    searchName: 'Lucario (PLS 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Lucario',
    tcgApiId: 'bw8-78',
    number: '78',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/78.png","large":"https://images.pokemontcg.io/bw8/78_hires.png"}',
    searchName: 'Lucario (PLS 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Timburr',
    tcgApiId: 'bw8-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/79.png","large":"https://images.pokemontcg.io/bw8/79_hires.png"}',
    searchName: 'Timburr (PLS 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Gurdurr',
    tcgApiId: 'bw8-80',
    number: '80',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/80.png","large":"https://images.pokemontcg.io/bw8/80_hires.png"}',
    searchName: 'Gurdurr (PLS 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Conkeldurr',
    tcgApiId: 'bw8-81',
    number: '81',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/81.png","large":"https://images.pokemontcg.io/bw8/81_hires.png"}',
    searchName: 'Conkeldurr (PLS 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Purrloin',
    tcgApiId: 'bw8-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/82.png","large":"https://images.pokemontcg.io/bw8/82_hires.png"}',
    searchName: 'Purrloin (PLS 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Purrloin',
    tcgApiId: 'bw8-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/83.png","large":"https://images.pokemontcg.io/bw8/83_hires.png"}',
    searchName: 'Purrloin (PLS 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Liepard',
    tcgApiId: 'bw8-84',
    number: '84',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/84.png","large":"https://images.pokemontcg.io/bw8/84_hires.png"}',
    searchName: 'Liepard (PLS 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Scraggy',
    tcgApiId: 'bw8-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/85.png","large":"https://images.pokemontcg.io/bw8/85_hires.png"}',
    searchName: 'Scraggy (PLS 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Scrafty',
    tcgApiId: 'bw8-86',
    number: '86',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/86.png","large":"https://images.pokemontcg.io/bw8/86_hires.png"}',
    searchName: 'Scrafty (PLS 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Skarmory',
    tcgApiId: 'bw8-87',
    number: '87',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/87.png","large":"https://images.pokemontcg.io/bw8/87_hires.png"}',
    searchName: 'Skarmory (PLS 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Klink',
    tcgApiId: 'bw8-88',
    number: '88',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/88.png","large":"https://images.pokemontcg.io/bw8/88_hires.png"}',
    searchName: 'Klink (PLS 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Klang',
    tcgApiId: 'bw8-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/89.png","large":"https://images.pokemontcg.io/bw8/89_hires.png"}',
    searchName: 'Klang (PLS 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Klinklang',
    tcgApiId: 'bw8-90',
    number: '90',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/90.png","large":"https://images.pokemontcg.io/bw8/90_hires.png"}',
    searchName: 'Klinklang (PLS 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Durant',
    tcgApiId: 'bw8-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/91.png","large":"https://images.pokemontcg.io/bw8/91_hires.png"}',
    searchName: 'Durant (PLS 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Durant',
    tcgApiId: 'bw8-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/92.png","large":"https://images.pokemontcg.io/bw8/92_hires.png"}',
    searchName: 'Durant (PLS 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Cobalion-EX',
    tcgApiId: 'bw8-93',
    number: '93',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/93.png","large":"https://images.pokemontcg.io/bw8/93_hires.png"}',
    searchName: 'Cobalion-EX (PLS 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Druddigon',
    tcgApiId: 'bw8-94',
    number: '94',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/94.png","large":"https://images.pokemontcg.io/bw8/94_hires.png"}',
    searchName: 'Druddigon (PLS 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Black Kyurem-EX',
    tcgApiId: 'bw8-95',
    number: '95',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/95.png","large":"https://images.pokemontcg.io/bw8/95_hires.png"}',
    searchName: 'Black Kyurem-EX (PLS 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'White Kyurem-EX',
    tcgApiId: 'bw8-96',
    number: '96',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/96.png","large":"https://images.pokemontcg.io/bw8/96_hires.png"}',
    searchName: 'White Kyurem-EX (PLS 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Clefairy',
    tcgApiId: 'bw8-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/97.png","large":"https://images.pokemontcg.io/bw8/97_hires.png"}',
    searchName: 'Clefairy (PLS 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Clefable',
    tcgApiId: 'bw8-98',
    number: '98',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/98.png","large":"https://images.pokemontcg.io/bw8/98_hires.png"}',
    searchName: 'Clefable (PLS 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Doduo',
    tcgApiId: 'bw8-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/99.png","large":"https://images.pokemontcg.io/bw8/99_hires.png"}',
    searchName: 'Doduo (PLS 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Dodrio',
    tcgApiId: 'bw8-100',
    number: '100',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/100.png","large":"https://images.pokemontcg.io/bw8/100_hires.png"}',
    searchName: 'Dodrio (PLS 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Snorlax',
    tcgApiId: 'bw8-101',
    number: '101',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/101.png","large":"https://images.pokemontcg.io/bw8/101_hires.png"}',
    searchName: 'Snorlax (PLS 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Togepi',
    tcgApiId: 'bw8-102',
    number: '102',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/102.png","large":"https://images.pokemontcg.io/bw8/102_hires.png"}',
    searchName: 'Togepi (PLS 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Togetic',
    tcgApiId: 'bw8-103',
    number: '103',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/103.png","large":"https://images.pokemontcg.io/bw8/103_hires.png"}',
    searchName: 'Togetic (PLS 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Togekiss',
    tcgApiId: 'bw8-104',
    number: '104',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/104.png","large":"https://images.pokemontcg.io/bw8/104_hires.png"}',
    searchName: 'Togekiss (PLS 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Whismur',
    tcgApiId: 'bw8-105',
    number: '105',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/105.png","large":"https://images.pokemontcg.io/bw8/105_hires.png"}',
    searchName: 'Whismur (PLS 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Loudred',
    tcgApiId: 'bw8-106',
    number: '106',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/106.png","large":"https://images.pokemontcg.io/bw8/106_hires.png"}',
    searchName: 'Loudred (PLS 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Exploud',
    tcgApiId: 'bw8-107',
    number: '107',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/107.png","large":"https://images.pokemontcg.io/bw8/107_hires.png"}',
    searchName: 'Exploud (PLS 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Lugia-EX',
    tcgApiId: 'bw8-108',
    number: '108',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/108.png","large":"https://images.pokemontcg.io/bw8/108_hires.png"}',
    searchName: 'Lugia-EX (PLS 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Skitty',
    tcgApiId: 'bw8-109',
    number: '109',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/109.png","large":"https://images.pokemontcg.io/bw8/109_hires.png"}',
    searchName: 'Skitty (PLS 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Patrat',
    tcgApiId: 'bw8-110',
    number: '110',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/110.png","large":"https://images.pokemontcg.io/bw8/110_hires.png"}',
    searchName: 'Patrat (PLS 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Patrat',
    tcgApiId: 'bw8-111',
    number: '111',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/111.png","large":"https://images.pokemontcg.io/bw8/111_hires.png"}',
    searchName: 'Patrat (PLS 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Watchog',
    tcgApiId: 'bw8-112',
    number: '112',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/112.png","large":"https://images.pokemontcg.io/bw8/112_hires.png"}',
    searchName: 'Watchog (PLS 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Watchog',
    tcgApiId: 'bw8-113',
    number: '113',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/113.png","large":"https://images.pokemontcg.io/bw8/113_hires.png"}',
    searchName: 'Watchog (PLS 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Bouffalant',
    tcgApiId: 'bw8-114',
    number: '114',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/114.png","large":"https://images.pokemontcg.io/bw8/114_hires.png"}',
    searchName: 'Bouffalant (PLS 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Rufflet',
    tcgApiId: 'bw8-115',
    number: '115',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/115.png","large":"https://images.pokemontcg.io/bw8/115_hires.png"}',
    searchName: 'Rufflet (PLS 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Braviary',
    tcgApiId: 'bw8-116',
    number: '116',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/116.png","large":"https://images.pokemontcg.io/bw8/116_hires.png"}',
    searchName: 'Braviary (PLS 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Bicycle',
    tcgApiId: 'bw8-117',
    number: '117',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/117.png","large":"https://images.pokemontcg.io/bw8/117_hires.png"}',
    searchName: 'Bicycle (PLS 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Colress',
    tcgApiId: 'bw8-118',
    number: '118',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/118.png","large":"https://images.pokemontcg.io/bw8/118_hires.png"}',
    searchName: 'Colress (PLS 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Colress Machine',
    tcgApiId: 'bw8-119',
    number: '119',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/119.png","large":"https://images.pokemontcg.io/bw8/119_hires.png"}',
    searchName: 'Colress Machine (PLS 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Escape Rope',
    tcgApiId: 'bw8-120',
    number: '120',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/120.png","large":"https://images.pokemontcg.io/bw8/120_hires.png"}',
    searchName: 'Escape Rope (PLS 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Ether',
    tcgApiId: 'bw8-121',
    number: '121',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/121.png","large":"https://images.pokemontcg.io/bw8/121_hires.png"}',
    searchName: 'Ether (PLS 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Eviolite',
    tcgApiId: 'bw8-122',
    number: '122',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/122.png","large":"https://images.pokemontcg.io/bw8/122_hires.png"}',
    searchName: 'Eviolite (PLS 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Hypnotoxic Laser',
    tcgApiId: 'bw8-123',
    number: '123',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/123.png","large":"https://images.pokemontcg.io/bw8/123_hires.png"}',
    searchName: 'Hypnotoxic Laser (PLS 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Plasma Frigate',
    tcgApiId: 'bw8-124',
    number: '124',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/124.png","large":"https://images.pokemontcg.io/bw8/124_hires.png"}',
    searchName: 'Plasma Frigate (PLS 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Team Plasma Grunt',
    tcgApiId: 'bw8-125',
    number: '125',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/125.png","large":"https://images.pokemontcg.io/bw8/125_hires.png"}',
    searchName: 'Team Plasma Grunt (PLS 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Virbank City Gym',
    tcgApiId: 'bw8-126',
    number: '126',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/126.png","large":"https://images.pokemontcg.io/bw8/126_hires.png"}',
    searchName: 'Virbank City Gym (PLS 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Plasma Energy',
    tcgApiId: 'bw8-127',
    number: '127',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/127.png","large":"https://images.pokemontcg.io/bw8/127_hires.png"}',
    searchName: 'Plasma Energy (PLS 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Dowsing Machine',
    tcgApiId: 'bw8-128',
    number: '128',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/128.png","large":"https://images.pokemontcg.io/bw8/128_hires.png"}',
    searchName: 'Dowsing Machine (PLS 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Scramble Switch',
    tcgApiId: 'bw8-129',
    number: '129',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/129.png","large":"https://images.pokemontcg.io/bw8/129_hires.png"}',
    searchName: 'Scramble Switch (PLS 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Victory Piece',
    tcgApiId: 'bw8-130',
    number: '130',
    rarity: 'Rare ACE',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/130.png","large":"https://images.pokemontcg.io/bw8/130_hires.png"}',
    searchName: 'Victory Piece (PLS 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Victini-EX',
    tcgApiId: 'bw8-131',
    number: '131',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/131.png","large":"https://images.pokemontcg.io/bw8/131_hires.png"}',
    searchName: 'Victini-EX (PLS 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Articuno-EX',
    tcgApiId: 'bw8-132',
    number: '132',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/132.png","large":"https://images.pokemontcg.io/bw8/132_hires.png"}',
    searchName: 'Articuno-EX (PLS 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Cobalion-EX',
    tcgApiId: 'bw8-133',
    number: '133',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/133.png","large":"https://images.pokemontcg.io/bw8/133_hires.png"}',
    searchName: 'Cobalion-EX (PLS 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Lugia-EX',
    tcgApiId: 'bw8-134',
    number: '134',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/134.png","large":"https://images.pokemontcg.io/bw8/134_hires.png"}',
    searchName: 'Lugia-EX (PLS 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Colress',
    tcgApiId: 'bw8-135',
    number: '135',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/135.png","large":"https://images.pokemontcg.io/bw8/135_hires.png"}',
    searchName: 'Colress (PLS 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Charizard',
    tcgApiId: 'bw8-136',
    number: '136',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/136.png","large":"https://images.pokemontcg.io/bw8/136_hires.png"}',
    searchName: 'Charizard (PLS 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Blastoise',
    tcgApiId: 'bw8-137',
    number: '137',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/137.png","large":"https://images.pokemontcg.io/bw8/137_hires.png"}',
    searchName: 'Blastoise (PLS 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bw8',
    name: 'Random Receiver',
    tcgApiId: 'bw8-138',
    number: '138',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/bw8/138.png","large":"https://images.pokemontcg.io/bw8/138_hires.png"}',
    searchName: 'Random Receiver (PLS 138)',
  },
];
