export const cardSeedBwp = [
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Snivy',
    tcgApiId: 'bwp-BW01',
    number: 'BW01',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW01.png","large":"https://images.pokemontcg.io/bwp/BW01_hires.png"}',
    searchName: 'Snivy (PR-BLW BW01)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Tepig',
    tcgApiId: 'bwp-BW02',
    number: 'BW02',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW02.png","large":"https://images.pokemontcg.io/bwp/BW02_hires.png"}',
    searchName: 'Tepig (PR-BLW BW02)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Oshawott',
    tcgApiId: 'bwp-BW03',
    number: 'BW03',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW03.png","large":"https://images.pokemontcg.io/bwp/BW03_hires.png"}',
    searchName: 'Oshawott (PR-BLW BW03)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Reshiram',
    tcgApiId: 'bwp-BW004',
    number: 'BW004',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW004.png","large":"https://images.pokemontcg.io/bwp/BW004_hires.png"}',
    searchName: 'Reshiram (PR-BLW BW004)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Zekrom',
    tcgApiId: 'bwp-BW005',
    number: 'BW005',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW005.png","large":"https://images.pokemontcg.io/bwp/BW005_hires.png"}',
    searchName: 'Zekrom (PR-BLW BW005)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Snivy',
    tcgApiId: 'bwp-BW06',
    number: 'BW06',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW06.png","large":"https://images.pokemontcg.io/bwp/BW06_hires.png"}',
    searchName: 'Snivy (PR-BLW BW06)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Tepig',
    tcgApiId: 'bwp-BW07',
    number: 'BW07',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW07.png","large":"https://images.pokemontcg.io/bwp/BW07_hires.png"}',
    searchName: 'Tepig (PR-BLW BW07)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Oshawott',
    tcgApiId: 'bwp-BW08',
    number: 'BW08',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW08.png","large":"https://images.pokemontcg.io/bwp/BW08_hires.png"}',
    searchName: 'Oshawott (PR-BLW BW08)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Zoroark',
    tcgApiId: 'bwp-BW09',
    number: 'BW09',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW09.png","large":"https://images.pokemontcg.io/bwp/BW09_hires.png"}',
    searchName: 'Zoroark (PR-BLW BW09)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Axew',
    tcgApiId: 'bwp-BW10',
    number: 'BW10',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW10.png","large":"https://images.pokemontcg.io/bwp/BW10_hires.png"}',
    searchName: 'Axew (PR-BLW BW10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Pansage',
    tcgApiId: 'bwp-BW11',
    number: 'BW11',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW11.png","large":"https://images.pokemontcg.io/bwp/BW11_hires.png"}',
    searchName: 'Pansage (PR-BLW BW11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Zorua',
    tcgApiId: 'bwp-BW12',
    number: 'BW12',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW12.png","large":"https://images.pokemontcg.io/bwp/BW12_hires.png"}',
    searchName: 'Zorua (PR-BLW BW12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Minccino',
    tcgApiId: 'bwp-BW13',
    number: 'BW13',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW13.png","large":"https://images.pokemontcg.io/bwp/BW13_hires.png"}',
    searchName: 'Minccino (PR-BLW BW13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Pansage',
    tcgApiId: 'bwp-BW14',
    number: 'BW14',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW14.png","large":"https://images.pokemontcg.io/bwp/BW14_hires.png"}',
    searchName: 'Pansage (PR-BLW BW14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Pidove',
    tcgApiId: 'bwp-BW15',
    number: 'BW15',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW15.png","large":"https://images.pokemontcg.io/bwp/BW15_hires.png"}',
    searchName: 'Pidove (PR-BLW BW15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Axew',
    tcgApiId: 'bwp-BW16',
    number: 'BW16',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW16.png","large":"https://images.pokemontcg.io/bwp/BW16_hires.png"}',
    searchName: 'Axew (PR-BLW BW16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Ducklett',
    tcgApiId: 'bwp-BW17',
    number: 'BW17',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW17.png","large":"https://images.pokemontcg.io/bwp/BW17_hires.png"}',
    searchName: 'Ducklett (PR-BLW BW17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Darumaka',
    tcgApiId: 'bwp-BW18',
    number: 'BW18',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW18.png","large":"https://images.pokemontcg.io/bwp/BW18_hires.png"}',
    searchName: 'Darumaka (PR-BLW BW18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Zoroark',
    tcgApiId: 'bwp-BW19',
    number: 'BW19',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW19.png","large":"https://images.pokemontcg.io/bwp/BW19_hires.png"}',
    searchName: 'Zoroark (PR-BLW BW19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Serperior',
    tcgApiId: 'bwp-BW20',
    number: 'BW20',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW20.png","large":"https://images.pokemontcg.io/bwp/BW20_hires.png"}',
    searchName: 'Serperior (PR-BLW BW20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Emboar',
    tcgApiId: 'bwp-BW21',
    number: 'BW21',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW21.png","large":"https://images.pokemontcg.io/bwp/BW21_hires.png"}',
    searchName: 'Emboar (PR-BLW BW21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Samurott',
    tcgApiId: 'bwp-BW22',
    number: 'BW22',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW22.png","large":"https://images.pokemontcg.io/bwp/BW22_hires.png"}',
    searchName: 'Samurott (PR-BLW BW22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Reshiram',
    tcgApiId: 'bwp-BW23',
    number: 'BW23',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW23.png","large":"https://images.pokemontcg.io/bwp/BW23_hires.png"}',
    searchName: 'Reshiram (PR-BLW BW23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Zekrom',
    tcgApiId: 'bwp-BW24',
    number: 'BW24',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW24.png","large":"https://images.pokemontcg.io/bwp/BW24_hires.png"}',
    searchName: 'Zekrom (PR-BLW BW24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Scraggy',
    tcgApiId: 'bwp-BW25',
    number: 'BW25',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW25.png","large":"https://images.pokemontcg.io/bwp/BW25_hires.png"}',
    searchName: 'Scraggy (PR-BLW BW25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Axew',
    tcgApiId: 'bwp-BW26',
    number: 'BW26',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW26.png","large":"https://images.pokemontcg.io/bwp/BW26_hires.png"}',
    searchName: 'Axew (PR-BLW BW26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Litwick',
    tcgApiId: 'bwp-BW27',
    number: 'BW27',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW27.png","large":"https://images.pokemontcg.io/bwp/BW27_hires.png"}',
    searchName: 'Litwick (PR-BLW BW27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Tropical Beach',
    tcgApiId: 'bwp-BW28',
    number: 'BW28',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW28.png","large":"https://images.pokemontcg.io/bwp/BW28_hires.png"}',
    searchName: 'Tropical Beach (PR-BLW BW28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Victory Cup',
    tcgApiId: 'bwp-BW29',
    number: 'BW29',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW29.png","large":"https://images.pokemontcg.io/bwp/BW29_hires.png"}',
    searchName: 'Victory Cup (PR-BLW BW29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Victory Cup',
    tcgApiId: 'bwp-BW30',
    number: 'BW30',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW30.png","large":"https://images.pokemontcg.io/bwp/BW30_hires.png"}',
    searchName: 'Victory Cup (PR-BLW BW30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Victory Cup',
    tcgApiId: 'bwp-BW31',
    number: 'BW31',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW31.png","large":"https://images.pokemontcg.io/bwp/BW31_hires.png"}',
    searchName: 'Victory Cup (PR-BLW BW31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Victini',
    tcgApiId: 'bwp-BW32',
    number: 'BW32',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW32.png","large":"https://images.pokemontcg.io/bwp/BW32_hires.png"}',
    searchName: 'Victini (PR-BLW BW32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Riolu',
    tcgApiId: 'bwp-BW33',
    number: 'BW33',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW33.png","large":"https://images.pokemontcg.io/bwp/BW33_hires.png"}',
    searchName: 'Riolu (PR-BLW BW33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Luxio',
    tcgApiId: 'bwp-BW34',
    number: 'BW34',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW34.png","large":"https://images.pokemontcg.io/bwp/BW34_hires.png"}',
    searchName: 'Luxio (PR-BLW BW34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Meowth',
    tcgApiId: 'bwp-BW35',
    number: 'BW35',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW35.png","large":"https://images.pokemontcg.io/bwp/BW35_hires.png"}',
    searchName: 'Meowth (PR-BLW BW35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Reshiram-EX',
    tcgApiId: 'bwp-BW36',
    number: 'BW36',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW36.png","large":"https://images.pokemontcg.io/bwp/BW36_hires.png"}',
    searchName: 'Reshiram-EX (PR-BLW BW36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Kyurem-EX',
    tcgApiId: 'bwp-BW37',
    number: 'BW37',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW37.png","large":"https://images.pokemontcg.io/bwp/BW37_hires.png"}',
    searchName: 'Kyurem-EX (PR-BLW BW37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Zekrom-EX',
    tcgApiId: 'bwp-BW38',
    number: 'BW38',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW38.png","large":"https://images.pokemontcg.io/bwp/BW38_hires.png"}',
    searchName: 'Zekrom-EX (PR-BLW BW38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Battle City',
    tcgApiId: 'bwp-BW39',
    number: 'BW39',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW39.png","large":"https://images.pokemontcg.io/bwp/BW39_hires.png"}',
    searchName: 'Battle City (PR-BLW BW39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Volcarona',
    tcgApiId: 'bwp-BW40',
    number: 'BW40',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW40.png","large":"https://images.pokemontcg.io/bwp/BW40_hires.png"}',
    searchName: 'Volcarona (PR-BLW BW40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Thundurus',
    tcgApiId: 'bwp-BW41',
    number: 'BW41',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW41.png","large":"https://images.pokemontcg.io/bwp/BW41_hires.png"}',
    searchName: 'Thundurus (PR-BLW BW41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Tornadus',
    tcgApiId: 'bwp-BW42',
    number: 'BW42',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW42.png","large":"https://images.pokemontcg.io/bwp/BW42_hires.png"}',
    searchName: 'Tornadus (PR-BLW BW42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Landorus',
    tcgApiId: 'bwp-BW43',
    number: 'BW43',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW43.png","large":"https://images.pokemontcg.io/bwp/BW43_hires.png"}',
    searchName: 'Landorus (PR-BLW BW43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Kyurem',
    tcgApiId: 'bwp-BW44',
    number: 'BW44',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW44.png","large":"https://images.pokemontcg.io/bwp/BW44_hires.png"}',
    searchName: 'Kyurem (PR-BLW BW44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Mewtwo-EX',
    tcgApiId: 'bwp-BW45',
    number: 'BW45',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW45.png","large":"https://images.pokemontcg.io/bwp/BW45_hires.png"}',
    searchName: 'Mewtwo-EX (PR-BLW BW45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Darkrai-EX',
    tcgApiId: 'bwp-BW46',
    number: 'BW46',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW46.png","large":"https://images.pokemontcg.io/bwp/BW46_hires.png"}',
    searchName: 'Darkrai-EX (PR-BLW BW46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Rayquaza-EX',
    tcgApiId: 'bwp-BW47',
    number: 'BW47',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW47.png","large":"https://images.pokemontcg.io/bwp/BW47_hires.png"}',
    searchName: 'Rayquaza-EX (PR-BLW BW47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Altaria',
    tcgApiId: 'bwp-BW48',
    number: 'BW48',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW48.png","large":"https://images.pokemontcg.io/bwp/BW48_hires.png"}',
    searchName: 'Altaria (PR-BLW BW48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Lilligant',
    tcgApiId: 'bwp-BW49',
    number: 'BW49',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW49.png","large":"https://images.pokemontcg.io/bwp/BW49_hires.png"}',
    searchName: 'Lilligant (PR-BLW BW49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Tropical Beach',
    tcgApiId: 'bwp-BW50',
    number: 'BW50',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW50.png","large":"https://images.pokemontcg.io/bwp/BW50_hires.png"}',
    searchName: 'Tropical Beach (PR-BLW BW50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Crobat',
    tcgApiId: 'bwp-BW51',
    number: 'BW51',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW51.png","large":"https://images.pokemontcg.io/bwp/BW51_hires.png"}',
    searchName: 'Crobat (PR-BLW BW51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Lillipup',
    tcgApiId: 'bwp-BW52',
    number: 'BW52',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW52.png","large":"https://images.pokemontcg.io/bwp/BW52_hires.png"}',
    searchName: 'Lillipup (PR-BLW BW52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Flygon',
    tcgApiId: 'bwp-BW53',
    number: 'BW53',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW53.png","large":"https://images.pokemontcg.io/bwp/BW53_hires.png"}',
    searchName: 'Flygon (PR-BLW BW53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Pikachu',
    tcgApiId: 'bwp-BW54',
    number: 'BW54',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW54.png","large":"https://images.pokemontcg.io/bwp/BW54_hires.png"}',
    searchName: 'Pikachu (PR-BLW BW54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Elgyem',
    tcgApiId: 'bwp-BW55',
    number: 'BW55',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW55.png","large":"https://images.pokemontcg.io/bwp/BW55_hires.png"}',
    searchName: 'Elgyem (PR-BLW BW55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Empoleon',
    tcgApiId: 'bwp-BW56',
    number: 'BW56',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW56.png","large":"https://images.pokemontcg.io/bwp/BW56_hires.png"}',
    searchName: 'Empoleon (PR-BLW BW56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Haxorus',
    tcgApiId: 'bwp-BW57',
    number: 'BW57',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW57.png","large":"https://images.pokemontcg.io/bwp/BW57_hires.png"}',
    searchName: 'Haxorus (PR-BLW BW57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Black Kyurem',
    tcgApiId: 'bwp-BW58',
    number: 'BW58',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW58.png","large":"https://images.pokemontcg.io/bwp/BW58_hires.png"}',
    searchName: 'Black Kyurem (PR-BLW BW58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'White Kyurem',
    tcgApiId: 'bwp-BW59',
    number: 'BW59',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW59.png","large":"https://images.pokemontcg.io/bwp/BW59_hires.png"}',
    searchName: 'White Kyurem (PR-BLW BW59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Keldeo',
    tcgApiId: 'bwp-BW60',
    number: 'BW60',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW60.png","large":"https://images.pokemontcg.io/bwp/BW60_hires.png"}',
    searchName: 'Keldeo (PR-BLW BW60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Keldeo-EX',
    tcgApiId: 'bwp-BW61',
    number: 'BW61',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW61.png","large":"https://images.pokemontcg.io/bwp/BW61_hires.png"}',
    searchName: 'Keldeo-EX (PR-BLW BW61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Black Kyurem-EX',
    tcgApiId: 'bwp-BW62',
    number: 'BW62',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW62.png","large":"https://images.pokemontcg.io/bwp/BW62_hires.png"}',
    searchName: 'Black Kyurem-EX (PR-BLW BW62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'White Kyurem-EX',
    tcgApiId: 'bwp-BW63',
    number: 'BW63',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW63.png","large":"https://images.pokemontcg.io/bwp/BW63_hires.png"}',
    searchName: 'White Kyurem-EX (PR-BLW BW63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Drifblim',
    tcgApiId: 'bwp-BW64',
    number: 'BW64',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW64.png","large":"https://images.pokemontcg.io/bwp/BW64_hires.png"}',
    searchName: 'Drifblim (PR-BLW BW64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Jigglypuff',
    tcgApiId: 'bwp-BW65',
    number: 'BW65',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW65.png","large":"https://images.pokemontcg.io/bwp/BW65_hires.png"}',
    searchName: 'Jigglypuff (PR-BLW BW65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Ninetales',
    tcgApiId: 'bwp-BW66',
    number: 'BW66',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW66.png","large":"https://images.pokemontcg.io/bwp/BW66_hires.png"}',
    searchName: 'Ninetales (PR-BLW BW66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Ampharos',
    tcgApiId: 'bwp-BW67',
    number: 'BW67',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW67.png","large":"https://images.pokemontcg.io/bwp/BW67_hires.png"}',
    searchName: 'Ampharos (PR-BLW BW67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Meloetta',
    tcgApiId: 'bwp-BW68',
    number: 'BW68',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW68.png","large":"https://images.pokemontcg.io/bwp/BW68_hires.png"}',
    searchName: 'Meloetta (PR-BLW BW68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Meloetta',
    tcgApiId: 'bwp-BW69',
    number: 'BW69',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW69.png","large":"https://images.pokemontcg.io/bwp/BW69_hires.png"}',
    searchName: 'Meloetta (PR-BLW BW69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Virizion',
    tcgApiId: 'bwp-BW70',
    number: 'BW70',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW70.png","large":"https://images.pokemontcg.io/bwp/BW70_hires.png"}',
    searchName: 'Virizion (PR-BLW BW70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Terrakion',
    tcgApiId: 'bwp-BW71',
    number: 'BW71',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW71.png","large":"https://images.pokemontcg.io/bwp/BW71_hires.png"}',
    searchName: 'Terrakion (PR-BLW BW71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Cobalion',
    tcgApiId: 'bwp-BW72',
    number: 'BW72',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW72.png","large":"https://images.pokemontcg.io/bwp/BW72_hires.png"}',
    searchName: 'Cobalion (PR-BLW BW72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Darkrai',
    tcgApiId: 'bwp-BW73',
    number: 'BW73',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW73.png","large":"https://images.pokemontcg.io/bwp/BW73_hires.png"}',
    searchName: 'Darkrai (PR-BLW BW73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Giratina',
    tcgApiId: 'bwp-BW74',
    number: 'BW74',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW74.png","large":"https://images.pokemontcg.io/bwp/BW74_hires.png"}',
    searchName: 'Giratina (PR-BLW BW74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Metagross',
    tcgApiId: 'bwp-BW75',
    number: 'BW75',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW75.png","large":"https://images.pokemontcg.io/bwp/BW75_hires.png"}',
    searchName: 'Metagross (PR-BLW BW75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Electrode',
    tcgApiId: 'bwp-BW76',
    number: 'BW76',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW76.png","large":"https://images.pokemontcg.io/bwp/BW76_hires.png"}',
    searchName: 'Electrode (PR-BLW BW76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Pikachu',
    tcgApiId: 'bwp-BW77',
    number: 'BW77',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW77.png","large":"https://images.pokemontcg.io/bwp/BW77_hires.png"}',
    searchName: 'Pikachu (PR-BLW BW77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Raichu',
    tcgApiId: 'bwp-BW78',
    number: 'BW78',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW78.png","large":"https://images.pokemontcg.io/bwp/BW78_hires.png"}',
    searchName: 'Raichu (PR-BLW BW78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Landorus',
    tcgApiId: 'bwp-BW79',
    number: 'BW79',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW79.png","large":"https://images.pokemontcg.io/bwp/BW79_hires.png"}',
    searchName: 'Landorus (PR-BLW BW79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Druddigon',
    tcgApiId: 'bwp-BW80',
    number: 'BW80',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW80.png","large":"https://images.pokemontcg.io/bwp/BW80_hires.png"}',
    searchName: 'Druddigon (PR-BLW BW80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Thundurus-EX',
    tcgApiId: 'bwp-BW81',
    number: 'BW81',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW81.png","large":"https://images.pokemontcg.io/bwp/BW81_hires.png"}',
    searchName: 'Thundurus-EX (PR-BLW BW81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Deoxys-EX',
    tcgApiId: 'bwp-BW82',
    number: 'BW82',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW82.png","large":"https://images.pokemontcg.io/bwp/BW82_hires.png"}',
    searchName: 'Deoxys-EX (PR-BLW BW82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Lugia-EX',
    tcgApiId: 'bwp-BW83',
    number: 'BW83',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW83.png","large":"https://images.pokemontcg.io/bwp/BW83_hires.png"}',
    searchName: 'Lugia-EX (PR-BLW BW83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Porygon-Z',
    tcgApiId: 'bwp-BW84',
    number: 'BW84',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW84.png","large":"https://images.pokemontcg.io/bwp/BW84_hires.png"}',
    searchName: 'Porygon-Z (PR-BLW BW84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Lucario',
    tcgApiId: 'bwp-BW85',
    number: 'BW85',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW85.png","large":"https://images.pokemontcg.io/bwp/BW85_hires.png"}',
    searchName: 'Lucario (PR-BLW BW85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Genesect',
    tcgApiId: 'bwp-BW86',
    number: 'BW86',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW86.png","large":"https://images.pokemontcg.io/bwp/BW86_hires.png"}',
    searchName: 'Genesect (PR-BLW BW86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Leafeon',
    tcgApiId: 'bwp-BW87',
    number: 'BW87',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW87.png","large":"https://images.pokemontcg.io/bwp/BW87_hires.png"}',
    searchName: 'Leafeon (PR-BLW BW87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Flareon',
    tcgApiId: 'bwp-BW88',
    number: 'BW88',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW88.png","large":"https://images.pokemontcg.io/bwp/BW88_hires.png"}',
    searchName: 'Flareon (PR-BLW BW88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Vaporeon',
    tcgApiId: 'bwp-BW89',
    number: 'BW89',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW89.png","large":"https://images.pokemontcg.io/bwp/BW89_hires.png"}',
    searchName: 'Vaporeon (PR-BLW BW89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Glaceon',
    tcgApiId: 'bwp-BW90',
    number: 'BW90',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW90.png","large":"https://images.pokemontcg.io/bwp/BW90_hires.png"}',
    searchName: 'Glaceon (PR-BLW BW90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Jolteon',
    tcgApiId: 'bwp-BW91',
    number: 'BW91',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW91.png","large":"https://images.pokemontcg.io/bwp/BW91_hires.png"}',
    searchName: 'Jolteon (PR-BLW BW91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Espeon',
    tcgApiId: 'bwp-BW92',
    number: 'BW92',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW92.png","large":"https://images.pokemontcg.io/bwp/BW92_hires.png"}',
    searchName: 'Espeon (PR-BLW BW92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Umbreon',
    tcgApiId: 'bwp-BW93',
    number: 'BW93',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW93.png","large":"https://images.pokemontcg.io/bwp/BW93_hires.png"}',
    searchName: 'Umbreon (PR-BLW BW93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Eevee',
    tcgApiId: 'bwp-BW94',
    number: 'BW94',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW94.png","large":"https://images.pokemontcg.io/bwp/BW94_hires.png"}',
    searchName: 'Eevee (PR-BLW BW94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Champions Festival',
    tcgApiId: 'bwp-BW95',
    number: 'BW95',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW95.png","large":"https://images.pokemontcg.io/bwp/BW95_hires.png"}',
    searchName: 'Champions Festival (PR-BLW BW95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Tornadus-EX',
    tcgApiId: 'bwp-BW96',
    number: 'BW96',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW96.png","large":"https://images.pokemontcg.io/bwp/BW96_hires.png"}',
    searchName: 'Tornadus-EX (PR-BLW BW96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Eevee',
    tcgApiId: 'bwp-BW97',
    number: 'BW97',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW97.png","large":"https://images.pokemontcg.io/bwp/BW97_hires.png"}',
    searchName: 'Eevee (PR-BLW BW97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Mew',
    tcgApiId: 'bwp-BW98',
    number: 'BW98',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW98.png","large":"https://images.pokemontcg.io/bwp/BW98_hires.png"}',
    searchName: 'Mew (PR-BLW BW98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Genesect',
    tcgApiId: 'bwp-BW99',
    number: 'BW99',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW99.png","large":"https://images.pokemontcg.io/bwp/BW99_hires.png"}',
    searchName: 'Genesect (PR-BLW BW99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'N',
    tcgApiId: 'bwp-BW100',
    number: 'BW100',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW100.png","large":"https://images.pokemontcg.io/bwp/BW100_hires.png"}',
    searchName: 'N (PR-BLW BW100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'bwp',
    name: 'Genesect',
    tcgApiId: 'bwp-BW101',
    number: 'BW101',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/bwp/BW101.png","large":"https://images.pokemontcg.io/bwp/BW101_hires.png"}',
    searchName: 'Genesect (PR-BLW BW101)',
  },
];
