export const cardSeedCel25c = [
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Blastoise',
    tcgApiId: 'cel25c-2_A',
    number: '2',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/2_A.png","large":"https://images.pokemontcg.io/cel25c/2_A_hires.png"}',
    searchName: 'Blastoise (CEL 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Charizard',
    tcgApiId: 'cel25c-4_A',
    number: '4',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/4_A.png","large":"https://images.pokemontcg.io/cel25c/4_A_hires.png"}',
    searchName: 'Charizard (CEL 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Venusaur',
    tcgApiId: 'cel25c-15_A1',
    number: '15',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/15_A.png","large":"https://images.pokemontcg.io/cel25c/15_A_hires.png"}',
    searchName: 'Venusaur (CEL 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Here Comes Team Rocket!',
    tcgApiId: 'cel25c-15_A2',
    number: '15',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/15_B.png","large":"https://images.pokemontcg.io/cel25c/15_B_hires.png"}',
    searchName: 'Here Comes Team Rocket! (CEL 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: "Rocket's Zapdos",
    tcgApiId: 'cel25c-15_A3',
    number: '15',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/15_C.png","large":"https://images.pokemontcg.io/cel25c/15_C_hires.png"}',
    searchName: "Rocket's Zapdos (CEL 15)",
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Claydol',
    tcgApiId: 'cel25c-15_A4',
    number: '15',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/15_D.png","large":"https://images.pokemontcg.io/cel25c/15_D_hires.png"}',
    searchName: 'Claydol (CEL 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Imposter Professor Oak',
    tcgApiId: 'cel25c-73_A',
    number: '73',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/73_A.png","large":"https://images.pokemontcg.io/cel25c/73_A_hires.png"}',
    searchName: 'Imposter Professor Oak (CEL 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Dark Gyarados',
    tcgApiId: 'cel25c-8_A',
    number: '8',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/8_A.png","large":"https://images.pokemontcg.io/cel25c/8_A_hires.png"}',
    searchName: 'Dark Gyarados (CEL 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: "_____'s Pikachu",
    tcgApiId: 'cel25c-24_A',
    number: '24',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/24_A.png","large":"https://images.pokemontcg.io/cel25c/24_A_hires.png"}',
    searchName: "_____'s Pikachu (CEL 24)",
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Cleffa',
    tcgApiId: 'cel25c-20_A',
    number: '20',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/20_A.png","large":"https://images.pokemontcg.io/cel25c/20_A_hires.png"}',
    searchName: 'Cleffa (CEL 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Shining Magikarp',
    tcgApiId: 'cel25c-66_A',
    number: '66',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/66_A.png","large":"https://images.pokemontcg.io/cel25c/66_A_hires.png"}',
    searchName: 'Shining Magikarp (CEL 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: "Team Magma's Groudon",
    tcgApiId: 'cel25c-9_A',
    number: '9',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/9_A.png","large":"https://images.pokemontcg.io/cel25c/9_A_hires.png"}',
    searchName: "Team Magma's Groudon (CEL 9)",
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: "Rocket's Admin.",
    tcgApiId: 'cel25c-86_A',
    number: '86',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/86_A.png","large":"https://images.pokemontcg.io/cel25c/86_A_hires.png"}',
    searchName: "Rocket's Admin. (CEL 86)",
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Mew ex',
    tcgApiId: 'cel25c-88_A',
    number: '88',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/88_A.png","large":"https://images.pokemontcg.io/cel25c/88_A_hires.png"}',
    searchName: 'Mew ex (CEL 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Gardevoir ex δ',
    tcgApiId: 'cel25c-93_A',
    number: '93',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/93_A.png","large":"https://images.pokemontcg.io/cel25c/93_A_hires.png"}',
    searchName: 'Gardevoir ex δ (CEL 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Umbreon ★',
    tcgApiId: 'cel25c-17_A',
    number: '17',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/17_A.png","large":"https://images.pokemontcg.io/cel25c/17_A_hires.png"}',
    searchName: 'Umbreon ★ (CEL 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Luxray GL LV.X',
    tcgApiId: 'cel25c-109_A',
    number: '109',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/109_A.png","large":"https://images.pokemontcg.io/cel25c/109_A_hires.png"}',
    searchName: 'Luxray GL LV.X (CEL 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Garchomp C LV.X',
    tcgApiId: 'cel25c-145_A',
    number: '145',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/145_A.png","large":"https://images.pokemontcg.io/cel25c/145_A_hires.png"}',
    searchName: 'Garchomp C LV.X (CEL 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Donphan',
    tcgApiId: 'cel25c-107_A',
    number: '107',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/107_A.png","large":"https://images.pokemontcg.io/cel25c/107_A_hires.png"}',
    searchName: 'Donphan (CEL 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Reshiram',
    tcgApiId: 'cel25c-113_A',
    number: '113',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/113_A.png","large":"https://images.pokemontcg.io/cel25c/113_A_hires.png"}',
    searchName: 'Reshiram (CEL 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Zekrom',
    tcgApiId: 'cel25c-114_A',
    number: '114',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/114_A.png","large":"https://images.pokemontcg.io/cel25c/114_A_hires.png"}',
    searchName: 'Zekrom (CEL 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Mewtwo-EX',
    tcgApiId: 'cel25c-54_A',
    number: '54',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/54_A.png","large":"https://images.pokemontcg.io/cel25c/54_A_hires.png"}',
    searchName: 'Mewtwo-EX (CEL 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Xerneas-EX',
    tcgApiId: 'cel25c-97_A',
    number: '97',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/97_A.png","large":"https://images.pokemontcg.io/cel25c/97_A_hires.png"}',
    searchName: 'Xerneas-EX (CEL 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'M Rayquaza-EX',
    tcgApiId: 'cel25c-76_A',
    number: '76',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/76_A.png","large":"https://images.pokemontcg.io/cel25c/76_A_hires.png"}',
    searchName: 'M Rayquaza-EX (CEL 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'cel25c',
    name: 'Tapu Lele-GX',
    tcgApiId: 'cel25c-60_A',
    number: '60',
    rarity: 'Classic Collection',
    images:
      '{"small":"https://images.pokemontcg.io/cel25c/60_A.png","large":"https://images.pokemontcg.io/cel25c/60_A_hires.png"}',
    searchName: 'Tapu Lele-GX (CEL 60)',
  },
];
