export const cardSeedDc1 = [
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Numel",
    tcgApiId: 'dc1-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/1.png","large":"https://images.pokemontcg.io/dc1/1_hires.png"}',
    searchName: "Team Magma's Numel (DCR 1)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Camerupt",
    tcgApiId: 'dc1-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/2.png","large":"https://images.pokemontcg.io/dc1/2_hires.png"}',
    searchName: "Team Magma's Camerupt (DCR 2)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Spheal",
    tcgApiId: 'dc1-3',
    number: '3',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/3.png","large":"https://images.pokemontcg.io/dc1/3_hires.png"}',
    searchName: "Team Aqua's Spheal (DCR 3)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Sealeo",
    tcgApiId: 'dc1-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/4.png","large":"https://images.pokemontcg.io/dc1/4_hires.png"}',
    searchName: "Team Aqua's Sealeo (DCR 4)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Walrein",
    tcgApiId: 'dc1-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/5.png","large":"https://images.pokemontcg.io/dc1/5_hires.png"}',
    searchName: "Team Aqua's Walrein (DCR 5)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Kyogre-EX",
    tcgApiId: 'dc1-6',
    number: '6',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/6.png","large":"https://images.pokemontcg.io/dc1/6_hires.png"}',
    searchName: "Team Aqua's Kyogre-EX (DCR 6)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Grimer",
    tcgApiId: 'dc1-7',
    number: '7',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/7.png","large":"https://images.pokemontcg.io/dc1/7_hires.png"}',
    searchName: "Team Aqua's Grimer (DCR 7)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Muk",
    tcgApiId: 'dc1-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/8.png","large":"https://images.pokemontcg.io/dc1/8_hires.png"}',
    searchName: "Team Aqua's Muk (DCR 8)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Seviper",
    tcgApiId: 'dc1-9',
    number: '9',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/9.png","large":"https://images.pokemontcg.io/dc1/9_hires.png"}',
    searchName: "Team Aqua's Seviper (DCR 9)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Baltoy",
    tcgApiId: 'dc1-10',
    number: '10',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/10.png","large":"https://images.pokemontcg.io/dc1/10_hires.png"}',
    searchName: "Team Magma's Baltoy (DCR 10)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Claydol",
    tcgApiId: 'dc1-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/11.png","large":"https://images.pokemontcg.io/dc1/11_hires.png"}',
    searchName: "Team Magma's Claydol (DCR 11)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Aron",
    tcgApiId: 'dc1-12',
    number: '12',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/12.png","large":"https://images.pokemontcg.io/dc1/12_hires.png"}',
    searchName: "Team Magma's Aron (DCR 12)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Lairon",
    tcgApiId: 'dc1-13',
    number: '13',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/13.png","large":"https://images.pokemontcg.io/dc1/13_hires.png"}',
    searchName: "Team Magma's Lairon (DCR 13)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Aggron",
    tcgApiId: 'dc1-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/14.png","large":"https://images.pokemontcg.io/dc1/14_hires.png"}',
    searchName: "Team Magma's Aggron (DCR 14)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Groudon-EX",
    tcgApiId: 'dc1-15',
    number: '15',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/15.png","large":"https://images.pokemontcg.io/dc1/15_hires.png"}',
    searchName: "Team Magma's Groudon-EX (DCR 15)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Poochyena",
    tcgApiId: 'dc1-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/16.png","large":"https://images.pokemontcg.io/dc1/16_hires.png"}',
    searchName: "Team Aqua's Poochyena (DCR 16)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Poochyena",
    tcgApiId: 'dc1-17',
    number: '17',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/17.png","large":"https://images.pokemontcg.io/dc1/17_hires.png"}',
    searchName: "Team Magma's Poochyena (DCR 17)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Mightyena",
    tcgApiId: 'dc1-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/18.png","large":"https://images.pokemontcg.io/dc1/18_hires.png"}',
    searchName: "Team Aqua's Mightyena (DCR 18)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Mightyena",
    tcgApiId: 'dc1-19',
    number: '19',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/19.png","large":"https://images.pokemontcg.io/dc1/19_hires.png"}',
    searchName: "Team Magma's Mightyena (DCR 19)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Carvanha",
    tcgApiId: 'dc1-20',
    number: '20',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/20.png","large":"https://images.pokemontcg.io/dc1/20_hires.png"}',
    searchName: "Team Aqua's Carvanha (DCR 20)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Sharpedo",
    tcgApiId: 'dc1-21',
    number: '21',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/21.png","large":"https://images.pokemontcg.io/dc1/21_hires.png"}',
    searchName: "Team Aqua's Sharpedo (DCR 21)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Zangoose",
    tcgApiId: 'dc1-22',
    number: '22',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/22.png","large":"https://images.pokemontcg.io/dc1/22_hires.png"}',
    searchName: "Team Magma's Zangoose (DCR 22)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: 'Aqua Diffuser',
    tcgApiId: 'dc1-23',
    number: '23',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/23.png","large":"https://images.pokemontcg.io/dc1/23_hires.png"}',
    searchName: 'Aqua Diffuser (DCR 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: 'Magma Pointer',
    tcgApiId: 'dc1-24',
    number: '24',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/24.png","large":"https://images.pokemontcg.io/dc1/24_hires.png"}',
    searchName: 'Magma Pointer (DCR 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: 'Team Aqua Admin',
    tcgApiId: 'dc1-25',
    number: '25',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/25.png","large":"https://images.pokemontcg.io/dc1/25_hires.png"}',
    searchName: 'Team Aqua Admin (DCR 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: 'Team Aqua Grunt',
    tcgApiId: 'dc1-26',
    number: '26',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/26.png","large":"https://images.pokemontcg.io/dc1/26_hires.png"}',
    searchName: 'Team Aqua Grunt (DCR 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Great Ball",
    tcgApiId: 'dc1-27',
    number: '27',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/27.png","large":"https://images.pokemontcg.io/dc1/27_hires.png"}',
    searchName: "Team Aqua's Great Ball (DCR 27)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Aqua's Secret Base",
    tcgApiId: 'dc1-28',
    number: '28',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/28.png","large":"https://images.pokemontcg.io/dc1/28_hires.png"}',
    searchName: "Team Aqua's Secret Base (DCR 28)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: 'Team Magma Admin',
    tcgApiId: 'dc1-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/29.png","large":"https://images.pokemontcg.io/dc1/29_hires.png"}',
    searchName: 'Team Magma Admin (DCR 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: 'Team Magma Grunt',
    tcgApiId: 'dc1-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/30.png","large":"https://images.pokemontcg.io/dc1/30_hires.png"}',
    searchName: 'Team Magma Grunt (DCR 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Great Ball",
    tcgApiId: 'dc1-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/31.png","large":"https://images.pokemontcg.io/dc1/31_hires.png"}',
    searchName: "Team Magma's Great Ball (DCR 31)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: "Team Magma's Secret Base",
    tcgApiId: 'dc1-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/32.png","large":"https://images.pokemontcg.io/dc1/32_hires.png"}',
    searchName: "Team Magma's Secret Base (DCR 32)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: 'Double Aqua Energy',
    tcgApiId: 'dc1-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/33.png","large":"https://images.pokemontcg.io/dc1/33_hires.png"}',
    searchName: 'Double Aqua Energy (DCR 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dc1',
    name: 'Double Magma Energy',
    tcgApiId: 'dc1-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dc1/34.png","large":"https://images.pokemontcg.io/dc1/34_hires.png"}',
    searchName: 'Double Magma Energy (DCR 34)',
  },
];
