export const cardSeedDet1 = [
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Bulbasaur',
    tcgApiId: 'det1-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/det1/1.png","large":"https://images.pokemontcg.io/det1/1_hires.png"}',
    searchName: 'Bulbasaur (DET 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Ludicolo',
    tcgApiId: 'det1-2',
    number: '2',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/det1/2.png","large":"https://images.pokemontcg.io/det1/2_hires.png"}',
    searchName: 'Ludicolo (DET 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Morelull',
    tcgApiId: 'det1-3',
    number: '3',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/det1/3.png","large":"https://images.pokemontcg.io/det1/3_hires.png"}',
    searchName: 'Morelull (DET 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Charmander',
    tcgApiId: 'det1-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/det1/4.png","large":"https://images.pokemontcg.io/det1/4_hires.png"}',
    searchName: 'Charmander (DET 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Charizard',
    tcgApiId: 'det1-5',
    number: '5',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/det1/5.png","large":"https://images.pokemontcg.io/det1/5_hires.png"}',
    searchName: 'Charizard (DET 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Arcanine',
    tcgApiId: 'det1-6',
    number: '6',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/det1/6.png","large":"https://images.pokemontcg.io/det1/6_hires.png"}',
    searchName: 'Arcanine (DET 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Psyduck',
    tcgApiId: 'det1-7',
    number: '7',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/det1/7.png","large":"https://images.pokemontcg.io/det1/7_hires.png"}',
    searchName: 'Psyduck (DET 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Magikarp',
    tcgApiId: 'det1-8',
    number: '8',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/det1/8.png","large":"https://images.pokemontcg.io/det1/8_hires.png"}',
    searchName: 'Magikarp (DET 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Greninja',
    tcgApiId: 'det1-9',
    number: '9',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/det1/9.png","large":"https://images.pokemontcg.io/det1/9_hires.png"}',
    searchName: 'Greninja (DET 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Detective Pikachu',
    tcgApiId: 'det1-10',
    number: '10',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/det1/10.png","large":"https://images.pokemontcg.io/det1/10_hires.png"}',
    searchName: 'Detective Pikachu (DET 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Mr. Mime',
    tcgApiId: 'det1-11',
    number: '11',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/det1/11.png","large":"https://images.pokemontcg.io/det1/11_hires.png"}',
    searchName: 'Mr. Mime (DET 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Mewtwo',
    tcgApiId: 'det1-12',
    number: '12',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/det1/12.png","large":"https://images.pokemontcg.io/det1/12_hires.png"}',
    searchName: 'Mewtwo (DET 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Machamp',
    tcgApiId: 'det1-13',
    number: '13',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/det1/13.png","large":"https://images.pokemontcg.io/det1/13_hires.png"}',
    searchName: 'Machamp (DET 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Jigglypuff',
    tcgApiId: 'det1-14',
    number: '14',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/det1/14.png","large":"https://images.pokemontcg.io/det1/14_hires.png"}',
    searchName: 'Jigglypuff (DET 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Snubbull',
    tcgApiId: 'det1-15',
    number: '15',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/det1/15.png","large":"https://images.pokemontcg.io/det1/15_hires.png"}',
    searchName: 'Snubbull (DET 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Lickitung',
    tcgApiId: 'det1-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/det1/16.png","large":"https://images.pokemontcg.io/det1/16_hires.png"}',
    searchName: 'Lickitung (DET 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Ditto',
    tcgApiId: 'det1-17',
    number: '17',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/det1/17.png","large":"https://images.pokemontcg.io/det1/17_hires.png"}',
    searchName: 'Ditto (DET 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'det1',
    name: 'Slaking',
    tcgApiId: 'det1-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/det1/18.png","large":"https://images.pokemontcg.io/det1/18_hires.png"}',
    searchName: 'Slaking (DET 18)',
  },
];
