export const cardSeedDp4 = [
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Blaziken',
    tcgApiId: 'dp4-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/1.png","large":"https://images.pokemontcg.io/dp4/1_hires.png"}',
    searchName: 'Blaziken (GE 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Cresselia',
    tcgApiId: 'dp4-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/2.png","large":"https://images.pokemontcg.io/dp4/2_hires.png"}',
    searchName: 'Cresselia (GE 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Darkrai',
    tcgApiId: 'dp4-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/3.png","large":"https://images.pokemontcg.io/dp4/3_hires.png"}',
    searchName: 'Darkrai (GE 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Darkrai',
    tcgApiId: 'dp4-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/4.png","large":"https://images.pokemontcg.io/dp4/4_hires.png"}',
    searchName: 'Darkrai (GE 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Pachirisu',
    tcgApiId: 'dp4-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/5.png","large":"https://images.pokemontcg.io/dp4/5_hires.png"}',
    searchName: 'Pachirisu (GE 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Porygon-Z',
    tcgApiId: 'dp4-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/6.png","large":"https://images.pokemontcg.io/dp4/6_hires.png"}',
    searchName: 'Porygon-Z (GE 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Rotom',
    tcgApiId: 'dp4-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/7.png","large":"https://images.pokemontcg.io/dp4/7_hires.png"}',
    searchName: 'Rotom (GE 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Sceptile',
    tcgApiId: 'dp4-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/8.png","large":"https://images.pokemontcg.io/dp4/8_hires.png"}',
    searchName: 'Sceptile (GE 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Swampert',
    tcgApiId: 'dp4-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/9.png","large":"https://images.pokemontcg.io/dp4/9_hires.png"}',
    searchName: 'Swampert (GE 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Tangrowth',
    tcgApiId: 'dp4-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/10.png","large":"https://images.pokemontcg.io/dp4/10_hires.png"}',
    searchName: 'Tangrowth (GE 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Togekiss',
    tcgApiId: 'dp4-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/11.png","large":"https://images.pokemontcg.io/dp4/11_hires.png"}',
    searchName: 'Togekiss (GE 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Altaria',
    tcgApiId: 'dp4-12',
    number: '12',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/12.png","large":"https://images.pokemontcg.io/dp4/12_hires.png"}',
    searchName: 'Altaria (GE 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Beedrill',
    tcgApiId: 'dp4-13',
    number: '13',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/13.png","large":"https://images.pokemontcg.io/dp4/13_hires.png"}',
    searchName: 'Beedrill (GE 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Butterfree',
    tcgApiId: 'dp4-14',
    number: '14',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/14.png","large":"https://images.pokemontcg.io/dp4/14_hires.png"}',
    searchName: 'Butterfree (GE 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Claydol',
    tcgApiId: 'dp4-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/15.png","large":"https://images.pokemontcg.io/dp4/15_hires.png"}',
    searchName: 'Claydol (GE 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Dialga',
    tcgApiId: 'dp4-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/16.png","large":"https://images.pokemontcg.io/dp4/16_hires.png"}',
    searchName: 'Dialga (GE 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Exploud',
    tcgApiId: 'dp4-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/17.png","large":"https://images.pokemontcg.io/dp4/17_hires.png"}',
    searchName: 'Exploud (GE 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Houndoom',
    tcgApiId: 'dp4-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/18.png","large":"https://images.pokemontcg.io/dp4/18_hires.png"}',
    searchName: 'Houndoom (GE 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Hypno',
    tcgApiId: 'dp4-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/19.png","large":"https://images.pokemontcg.io/dp4/19_hires.png"}',
    searchName: 'Hypno (GE 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Kingler',
    tcgApiId: 'dp4-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/20.png","large":"https://images.pokemontcg.io/dp4/20_hires.png"}',
    searchName: 'Kingler (GE 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Lapras',
    tcgApiId: 'dp4-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/21.png","large":"https://images.pokemontcg.io/dp4/21_hires.png"}',
    searchName: 'Lapras (GE 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Latias',
    tcgApiId: 'dp4-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/22.png","large":"https://images.pokemontcg.io/dp4/22_hires.png"}',
    searchName: 'Latias (GE 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Latios',
    tcgApiId: 'dp4-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/23.png","large":"https://images.pokemontcg.io/dp4/23_hires.png"}',
    searchName: 'Latios (GE 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Mawile',
    tcgApiId: 'dp4-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/24.png","large":"https://images.pokemontcg.io/dp4/24_hires.png"}',
    searchName: 'Mawile (GE 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Milotic',
    tcgApiId: 'dp4-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/25.png","large":"https://images.pokemontcg.io/dp4/25_hires.png"}',
    searchName: 'Milotic (GE 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Palkia',
    tcgApiId: 'dp4-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/26.png","large":"https://images.pokemontcg.io/dp4/26_hires.png"}',
    searchName: 'Palkia (GE 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Primeape',
    tcgApiId: 'dp4-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/27.png","large":"https://images.pokemontcg.io/dp4/27_hires.png"}',
    searchName: 'Primeape (GE 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Slowking',
    tcgApiId: 'dp4-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/28.png","large":"https://images.pokemontcg.io/dp4/28_hires.png"}',
    searchName: 'Slowking (GE 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Unown [H]',
    tcgApiId: 'dp4-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/29.png","large":"https://images.pokemontcg.io/dp4/29_hires.png"}',
    searchName: 'Unown [H] (GE 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Wailord',
    tcgApiId: 'dp4-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/30.png","large":"https://images.pokemontcg.io/dp4/30_hires.png"}',
    searchName: 'Wailord (GE 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Weezing',
    tcgApiId: 'dp4-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/31.png","large":"https://images.pokemontcg.io/dp4/31_hires.png"}',
    searchName: 'Weezing (GE 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Wigglytuff',
    tcgApiId: 'dp4-32',
    number: '32',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/32.png","large":"https://images.pokemontcg.io/dp4/32_hires.png"}',
    searchName: 'Wigglytuff (GE 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Arbok',
    tcgApiId: 'dp4-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/33.png","large":"https://images.pokemontcg.io/dp4/33_hires.png"}',
    searchName: 'Arbok (GE 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Cacturne',
    tcgApiId: 'dp4-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/34.png","large":"https://images.pokemontcg.io/dp4/34_hires.png"}',
    searchName: 'Cacturne (GE 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Combusken',
    tcgApiId: 'dp4-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/35.png","large":"https://images.pokemontcg.io/dp4/35_hires.png"}',
    searchName: 'Combusken (GE 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Delibird',
    tcgApiId: 'dp4-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/36.png","large":"https://images.pokemontcg.io/dp4/36_hires.png"}',
    searchName: 'Delibird (GE 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Floatzel',
    tcgApiId: 'dp4-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/37.png","large":"https://images.pokemontcg.io/dp4/37_hires.png"}',
    searchName: 'Floatzel (GE 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Gorebyss',
    tcgApiId: 'dp4-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/38.png","large":"https://images.pokemontcg.io/dp4/38_hires.png"}',
    searchName: 'Gorebyss (GE 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Granbull',
    tcgApiId: 'dp4-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/39.png","large":"https://images.pokemontcg.io/dp4/39_hires.png"}',
    searchName: 'Granbull (GE 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Grovyle',
    tcgApiId: 'dp4-40',
    number: '40',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/40.png","large":"https://images.pokemontcg.io/dp4/40_hires.png"}',
    searchName: 'Grovyle (GE 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Hariyama',
    tcgApiId: 'dp4-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/41.png","large":"https://images.pokemontcg.io/dp4/41_hires.png"}',
    searchName: 'Hariyama (GE 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Huntail',
    tcgApiId: 'dp4-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/42.png","large":"https://images.pokemontcg.io/dp4/42_hires.png"}',
    searchName: 'Huntail (GE 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Linoone',
    tcgApiId: 'dp4-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/43.png","large":"https://images.pokemontcg.io/dp4/43_hires.png"}',
    searchName: 'Linoone (GE 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Loudred',
    tcgApiId: 'dp4-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/44.png","large":"https://images.pokemontcg.io/dp4/44_hires.png"}',
    searchName: 'Loudred (GE 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Magcargo',
    tcgApiId: 'dp4-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/45.png","large":"https://images.pokemontcg.io/dp4/45_hires.png"}',
    searchName: 'Magcargo (GE 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Marshtomp',
    tcgApiId: 'dp4-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/46.png","large":"https://images.pokemontcg.io/dp4/46_hires.png"}',
    searchName: 'Marshtomp (GE 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Metapod',
    tcgApiId: 'dp4-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/47.png","large":"https://images.pokemontcg.io/dp4/47_hires.png"}',
    searchName: 'Metapod (GE 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Pelipper',
    tcgApiId: 'dp4-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/48.png","large":"https://images.pokemontcg.io/dp4/48_hires.png"}',
    searchName: 'Pelipper (GE 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Porygon2',
    tcgApiId: 'dp4-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/49.png","large":"https://images.pokemontcg.io/dp4/49_hires.png"}',
    searchName: 'Porygon2 (GE 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Purugly',
    tcgApiId: 'dp4-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/50.png","large":"https://images.pokemontcg.io/dp4/50_hires.png"}',
    searchName: 'Purugly (GE 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Relicanth',
    tcgApiId: 'dp4-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/51.png","large":"https://images.pokemontcg.io/dp4/51_hires.png"}',
    searchName: 'Relicanth (GE 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Seviper',
    tcgApiId: 'dp4-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/52.png","large":"https://images.pokemontcg.io/dp4/52_hires.png"}',
    searchName: 'Seviper (GE 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Skarmory',
    tcgApiId: 'dp4-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/53.png","large":"https://images.pokemontcg.io/dp4/53_hires.png"}',
    searchName: 'Skarmory (GE 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Slowbro',
    tcgApiId: 'dp4-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/54.png","large":"https://images.pokemontcg.io/dp4/54_hires.png"}',
    searchName: 'Slowbro (GE 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Togetic',
    tcgApiId: 'dp4-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/55.png","large":"https://images.pokemontcg.io/dp4/55_hires.png"}',
    searchName: 'Togetic (GE 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Unown [F]',
    tcgApiId: 'dp4-56',
    number: '56',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/56.png","large":"https://images.pokemontcg.io/dp4/56_hires.png"}',
    searchName: 'Unown [F] (GE 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Unown [G]',
    tcgApiId: 'dp4-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/57.png","large":"https://images.pokemontcg.io/dp4/57_hires.png"}',
    searchName: 'Unown [G] (GE 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Wailmer',
    tcgApiId: 'dp4-58',
    number: '58',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/58.png","large":"https://images.pokemontcg.io/dp4/58_hires.png"}',
    searchName: 'Wailmer (GE 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Zangoose',
    tcgApiId: 'dp4-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/59.png","large":"https://images.pokemontcg.io/dp4/59_hires.png"}',
    searchName: 'Zangoose (GE 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Baltoy',
    tcgApiId: 'dp4-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/60.png","large":"https://images.pokemontcg.io/dp4/60_hires.png"}',
    searchName: 'Baltoy (GE 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Buizel',
    tcgApiId: 'dp4-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/61.png","large":"https://images.pokemontcg.io/dp4/61_hires.png"}',
    searchName: 'Buizel (GE 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Cacnea',
    tcgApiId: 'dp4-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/62.png","large":"https://images.pokemontcg.io/dp4/62_hires.png"}',
    searchName: 'Cacnea (GE 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Caterpie',
    tcgApiId: 'dp4-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/63.png","large":"https://images.pokemontcg.io/dp4/63_hires.png"}',
    searchName: 'Caterpie (GE 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Clamperl',
    tcgApiId: 'dp4-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/64.png","large":"https://images.pokemontcg.io/dp4/64_hires.png"}',
    searchName: 'Clamperl (GE 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Drowzee',
    tcgApiId: 'dp4-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/65.png","large":"https://images.pokemontcg.io/dp4/65_hires.png"}',
    searchName: 'Drowzee (GE 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Ekans',
    tcgApiId: 'dp4-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/66.png","large":"https://images.pokemontcg.io/dp4/66_hires.png"}',
    searchName: 'Ekans (GE 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Feebas',
    tcgApiId: 'dp4-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/67.png","large":"https://images.pokemontcg.io/dp4/67_hires.png"}',
    searchName: 'Feebas (GE 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Glameow',
    tcgApiId: 'dp4-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/68.png","large":"https://images.pokemontcg.io/dp4/68_hires.png"}',
    searchName: 'Glameow (GE 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Houndour',
    tcgApiId: 'dp4-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/69.png","large":"https://images.pokemontcg.io/dp4/69_hires.png"}',
    searchName: 'Houndour (GE 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Igglybuff',
    tcgApiId: 'dp4-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/70.png","large":"https://images.pokemontcg.io/dp4/70_hires.png"}',
    searchName: 'Igglybuff (GE 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Illumise',
    tcgApiId: 'dp4-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/71.png","large":"https://images.pokemontcg.io/dp4/71_hires.png"}',
    searchName: 'Illumise (GE 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Jigglypuff',
    tcgApiId: 'dp4-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/72.png","large":"https://images.pokemontcg.io/dp4/72_hires.png"}',
    searchName: 'Jigglypuff (GE 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Kakuna',
    tcgApiId: 'dp4-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/73.png","large":"https://images.pokemontcg.io/dp4/73_hires.png"}',
    searchName: 'Kakuna (GE 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Koffing',
    tcgApiId: 'dp4-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/74.png","large":"https://images.pokemontcg.io/dp4/74_hires.png"}',
    searchName: 'Koffing (GE 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Krabby',
    tcgApiId: 'dp4-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/75.png","large":"https://images.pokemontcg.io/dp4/75_hires.png"}',
    searchName: 'Krabby (GE 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Lunatone',
    tcgApiId: 'dp4-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/76.png","large":"https://images.pokemontcg.io/dp4/76_hires.png"}',
    searchName: 'Lunatone (GE 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Luvdisc',
    tcgApiId: 'dp4-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/77.png","large":"https://images.pokemontcg.io/dp4/77_hires.png"}',
    searchName: 'Luvdisc (GE 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Makuhita',
    tcgApiId: 'dp4-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/78.png","large":"https://images.pokemontcg.io/dp4/78_hires.png"}',
    searchName: 'Makuhita (GE 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Mankey',
    tcgApiId: 'dp4-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/79.png","large":"https://images.pokemontcg.io/dp4/79_hires.png"}',
    searchName: 'Mankey (GE 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Mudkip',
    tcgApiId: 'dp4-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/80.png","large":"https://images.pokemontcg.io/dp4/80_hires.png"}',
    searchName: 'Mudkip (GE 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Porygon',
    tcgApiId: 'dp4-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/81.png","large":"https://images.pokemontcg.io/dp4/81_hires.png"}',
    searchName: 'Porygon (GE 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Slowpoke',
    tcgApiId: 'dp4-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/82.png","large":"https://images.pokemontcg.io/dp4/82_hires.png"}',
    searchName: 'Slowpoke (GE 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Slugma',
    tcgApiId: 'dp4-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/83.png","large":"https://images.pokemontcg.io/dp4/83_hires.png"}',
    searchName: 'Slugma (GE 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Snubbull',
    tcgApiId: 'dp4-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/84.png","large":"https://images.pokemontcg.io/dp4/84_hires.png"}',
    searchName: 'Snubbull (GE 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Solrock',
    tcgApiId: 'dp4-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/85.png","large":"https://images.pokemontcg.io/dp4/85_hires.png"}',
    searchName: 'Solrock (GE 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Swablu',
    tcgApiId: 'dp4-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/86.png","large":"https://images.pokemontcg.io/dp4/86_hires.png"}',
    searchName: 'Swablu (GE 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Tangela',
    tcgApiId: 'dp4-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/87.png","large":"https://images.pokemontcg.io/dp4/87_hires.png"}',
    searchName: 'Tangela (GE 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Togepi',
    tcgApiId: 'dp4-88',
    number: '88',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/88.png","large":"https://images.pokemontcg.io/dp4/88_hires.png"}',
    searchName: 'Togepi (GE 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Torchic',
    tcgApiId: 'dp4-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/89.png","large":"https://images.pokemontcg.io/dp4/89_hires.png"}',
    searchName: 'Torchic (GE 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Treecko',
    tcgApiId: 'dp4-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/90.png","large":"https://images.pokemontcg.io/dp4/90_hires.png"}',
    searchName: 'Treecko (GE 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Unown [L]',
    tcgApiId: 'dp4-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/91.png","large":"https://images.pokemontcg.io/dp4/91_hires.png"}',
    searchName: 'Unown [L] (GE 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Volbeat',
    tcgApiId: 'dp4-92',
    number: '92',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/92.png","large":"https://images.pokemontcg.io/dp4/92_hires.png"}',
    searchName: 'Volbeat (GE 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Weedle',
    tcgApiId: 'dp4-93',
    number: '93',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/93.png","large":"https://images.pokemontcg.io/dp4/93_hires.png"}',
    searchName: 'Weedle (GE 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Whismur',
    tcgApiId: 'dp4-94',
    number: '94',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/94.png","large":"https://images.pokemontcg.io/dp4/94_hires.png"}',
    searchName: 'Whismur (GE 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Wingull',
    tcgApiId: 'dp4-95',
    number: '95',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/95.png","large":"https://images.pokemontcg.io/dp4/95_hires.png"}',
    searchName: 'Wingull (GE 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Zigzagoon',
    tcgApiId: 'dp4-96',
    number: '96',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/96.png","large":"https://images.pokemontcg.io/dp4/96_hires.png"}',
    searchName: 'Zigzagoon (GE 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Amulet Coin',
    tcgApiId: 'dp4-97',
    number: '97',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/97.png","large":"https://images.pokemontcg.io/dp4/97_hires.png"}',
    searchName: 'Amulet Coin (GE 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: "Felicity's Drawing",
    tcgApiId: 'dp4-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/98.png","large":"https://images.pokemontcg.io/dp4/98_hires.png"}',
    searchName: "Felicity's Drawing (GE 98)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Leftovers',
    tcgApiId: 'dp4-99',
    number: '99',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/99.png","large":"https://images.pokemontcg.io/dp4/99_hires.png"}',
    searchName: 'Leftovers (GE 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Moonlight Stadium',
    tcgApiId: 'dp4-100',
    number: '100',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/100.png","large":"https://images.pokemontcg.io/dp4/100_hires.png"}',
    searchName: 'Moonlight Stadium (GE 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Premier Ball',
    tcgApiId: 'dp4-101',
    number: '101',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/101.png","large":"https://images.pokemontcg.io/dp4/101_hires.png"}',
    searchName: 'Premier Ball (GE 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Rare Candy',
    tcgApiId: 'dp4-102',
    number: '102',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/102.png","large":"https://images.pokemontcg.io/dp4/102_hires.png"}',
    searchName: 'Rare Candy (GE 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Cresselia LV.X',
    tcgApiId: 'dp4-103',
    number: '103',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/103.png","large":"https://images.pokemontcg.io/dp4/103_hires.png"}',
    searchName: 'Cresselia LV.X (GE 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Darkrai LV.X',
    tcgApiId: 'dp4-104',
    number: '104',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/104.png","large":"https://images.pokemontcg.io/dp4/104_hires.png"}',
    searchName: 'Darkrai LV.X (GE 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Dialga LV.X',
    tcgApiId: 'dp4-105',
    number: '105',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/105.png","large":"https://images.pokemontcg.io/dp4/105_hires.png"}',
    searchName: 'Dialga LV.X (GE 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp4',
    name: 'Palkia LV.X',
    tcgApiId: 'dp4-106',
    number: '106',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/dp4/106.png","large":"https://images.pokemontcg.io/dp4/106_hires.png"}',
    searchName: 'Palkia LV.X (GE 106)',
  },
];
