export const cardSeedDp5 = [
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Articuno',
    tcgApiId: 'dp5-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/1.png","large":"https://images.pokemontcg.io/dp5/1_hires.png"}',
    searchName: 'Articuno (MD 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Cresselia',
    tcgApiId: 'dp5-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/2.png","large":"https://images.pokemontcg.io/dp5/2_hires.png"}',
    searchName: 'Cresselia (MD 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Darkrai',
    tcgApiId: 'dp5-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/3.png","large":"https://images.pokemontcg.io/dp5/3_hires.png"}',
    searchName: 'Darkrai (MD 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Dialga',
    tcgApiId: 'dp5-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/4.png","large":"https://images.pokemontcg.io/dp5/4_hires.png"}',
    searchName: 'Dialga (MD 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Glaceon',
    tcgApiId: 'dp5-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/5.png","large":"https://images.pokemontcg.io/dp5/5_hires.png"}',
    searchName: 'Glaceon (MD 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Kabutops',
    tcgApiId: 'dp5-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/6.png","large":"https://images.pokemontcg.io/dp5/6_hires.png"}',
    searchName: 'Kabutops (MD 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Leafeon',
    tcgApiId: 'dp5-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/7.png","large":"https://images.pokemontcg.io/dp5/7_hires.png"}',
    searchName: 'Leafeon (MD 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Manaphy',
    tcgApiId: 'dp5-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/8.png","large":"https://images.pokemontcg.io/dp5/8_hires.png"}',
    searchName: 'Manaphy (MD 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Mewtwo',
    tcgApiId: 'dp5-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/9.png","large":"https://images.pokemontcg.io/dp5/9_hires.png"}',
    searchName: 'Mewtwo (MD 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Moltres',
    tcgApiId: 'dp5-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/10.png","large":"https://images.pokemontcg.io/dp5/10_hires.png"}',
    searchName: 'Moltres (MD 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Palkia',
    tcgApiId: 'dp5-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/11.png","large":"https://images.pokemontcg.io/dp5/11_hires.png"}',
    searchName: 'Palkia (MD 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Phione',
    tcgApiId: 'dp5-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/12.png","large":"https://images.pokemontcg.io/dp5/12_hires.png"}',
    searchName: 'Phione (MD 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Rotom',
    tcgApiId: 'dp5-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/13.png","large":"https://images.pokemontcg.io/dp5/13_hires.png"}',
    searchName: 'Rotom (MD 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Zapdos',
    tcgApiId: 'dp5-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/14.png","large":"https://images.pokemontcg.io/dp5/14_hires.png"}',
    searchName: 'Zapdos (MD 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Aerodactyl',
    tcgApiId: 'dp5-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/15.png","large":"https://images.pokemontcg.io/dp5/15_hires.png"}',
    searchName: 'Aerodactyl (MD 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Bronzong',
    tcgApiId: 'dp5-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/16.png","large":"https://images.pokemontcg.io/dp5/16_hires.png"}',
    searchName: 'Bronzong (MD 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Empoleon',
    tcgApiId: 'dp5-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/17.png","large":"https://images.pokemontcg.io/dp5/17_hires.png"}',
    searchName: 'Empoleon (MD 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Espeon',
    tcgApiId: 'dp5-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/18.png","large":"https://images.pokemontcg.io/dp5/18_hires.png"}',
    searchName: 'Espeon (MD 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Flareon',
    tcgApiId: 'dp5-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/19.png","large":"https://images.pokemontcg.io/dp5/19_hires.png"}',
    searchName: 'Flareon (MD 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Glaceon',
    tcgApiId: 'dp5-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/20.png","large":"https://images.pokemontcg.io/dp5/20_hires.png"}',
    searchName: 'Glaceon (MD 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Hippowdon',
    tcgApiId: 'dp5-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/21.png","large":"https://images.pokemontcg.io/dp5/21_hires.png"}',
    searchName: 'Hippowdon (MD 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Infernape',
    tcgApiId: 'dp5-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/22.png","large":"https://images.pokemontcg.io/dp5/22_hires.png"}',
    searchName: 'Infernape (MD 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Jolteon',
    tcgApiId: 'dp5-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/23.png","large":"https://images.pokemontcg.io/dp5/23_hires.png"}',
    searchName: 'Jolteon (MD 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Leafeon',
    tcgApiId: 'dp5-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/24.png","large":"https://images.pokemontcg.io/dp5/24_hires.png"}',
    searchName: 'Leafeon (MD 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Minun',
    tcgApiId: 'dp5-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/25.png","large":"https://images.pokemontcg.io/dp5/25_hires.png"}',
    searchName: 'Minun (MD 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Omastar',
    tcgApiId: 'dp5-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/26.png","large":"https://images.pokemontcg.io/dp5/26_hires.png"}',
    searchName: 'Omastar (MD 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Phione',
    tcgApiId: 'dp5-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/27.png","large":"https://images.pokemontcg.io/dp5/27_hires.png"}',
    searchName: 'Phione (MD 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Plusle',
    tcgApiId: 'dp5-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/28.png","large":"https://images.pokemontcg.io/dp5/28_hires.png"}',
    searchName: 'Plusle (MD 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Scizor',
    tcgApiId: 'dp5-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/29.png","large":"https://images.pokemontcg.io/dp5/29_hires.png"}',
    searchName: 'Scizor (MD 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Torterra',
    tcgApiId: 'dp5-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/30.png","large":"https://images.pokemontcg.io/dp5/30_hires.png"}',
    searchName: 'Torterra (MD 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Toxicroak',
    tcgApiId: 'dp5-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/31.png","large":"https://images.pokemontcg.io/dp5/31_hires.png"}',
    searchName: 'Toxicroak (MD 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Umbreon',
    tcgApiId: 'dp5-32',
    number: '32',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/32.png","large":"https://images.pokemontcg.io/dp5/32_hires.png"}',
    searchName: 'Umbreon (MD 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Unown [P]',
    tcgApiId: 'dp5-33',
    number: '33',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/33.png","large":"https://images.pokemontcg.io/dp5/33_hires.png"}',
    searchName: 'Unown [P] (MD 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Vaporeon',
    tcgApiId: 'dp5-34',
    number: '34',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/34.png","large":"https://images.pokemontcg.io/dp5/34_hires.png"}',
    searchName: 'Vaporeon (MD 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Ambipom',
    tcgApiId: 'dp5-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/35.png","large":"https://images.pokemontcg.io/dp5/35_hires.png"}',
    searchName: 'Ambipom (MD 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Fearow',
    tcgApiId: 'dp5-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/36.png","large":"https://images.pokemontcg.io/dp5/36_hires.png"}',
    searchName: 'Fearow (MD 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Grotle',
    tcgApiId: 'dp5-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/37.png","large":"https://images.pokemontcg.io/dp5/37_hires.png"}',
    searchName: 'Grotle (MD 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Kangaskhan',
    tcgApiId: 'dp5-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/38.png","large":"https://images.pokemontcg.io/dp5/38_hires.png"}',
    searchName: 'Kangaskhan (MD 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Lickitung',
    tcgApiId: 'dp5-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/39.png","large":"https://images.pokemontcg.io/dp5/39_hires.png"}',
    searchName: 'Lickitung (MD 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Manectric',
    tcgApiId: 'dp5-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/40.png","large":"https://images.pokemontcg.io/dp5/40_hires.png"}',
    searchName: 'Manectric (MD 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Monferno',
    tcgApiId: 'dp5-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/41.png","large":"https://images.pokemontcg.io/dp5/41_hires.png"}',
    searchName: 'Monferno (MD 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Mothim',
    tcgApiId: 'dp5-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/42.png","large":"https://images.pokemontcg.io/dp5/42_hires.png"}',
    searchName: 'Mothim (MD 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Pachirisu',
    tcgApiId: 'dp5-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/43.png","large":"https://images.pokemontcg.io/dp5/43_hires.png"}',
    searchName: 'Pachirisu (MD 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Prinplup',
    tcgApiId: 'dp5-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/44.png","large":"https://images.pokemontcg.io/dp5/44_hires.png"}',
    searchName: 'Prinplup (MD 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Raichu',
    tcgApiId: 'dp5-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/45.png","large":"https://images.pokemontcg.io/dp5/45_hires.png"}',
    searchName: 'Raichu (MD 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Scyther',
    tcgApiId: 'dp5-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/46.png","large":"https://images.pokemontcg.io/dp5/46_hires.png"}',
    searchName: 'Scyther (MD 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Staravia',
    tcgApiId: 'dp5-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/47.png","large":"https://images.pokemontcg.io/dp5/47_hires.png"}',
    searchName: 'Staravia (MD 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Sudowoodo',
    tcgApiId: 'dp5-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/48.png","large":"https://images.pokemontcg.io/dp5/48_hires.png"}',
    searchName: 'Sudowoodo (MD 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Unown [Q]',
    tcgApiId: 'dp5-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/49.png","large":"https://images.pokemontcg.io/dp5/49_hires.png"}',
    searchName: 'Unown [Q] (MD 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Aipom',
    tcgApiId: 'dp5-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/50.png","large":"https://images.pokemontcg.io/dp5/50_hires.png"}',
    searchName: 'Aipom (MD 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Aipom',
    tcgApiId: 'dp5-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/51.png","large":"https://images.pokemontcg.io/dp5/51_hires.png"}',
    searchName: 'Aipom (MD 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Bronzor',
    tcgApiId: 'dp5-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/52.png","large":"https://images.pokemontcg.io/dp5/52_hires.png"}',
    searchName: 'Bronzor (MD 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Buneary',
    tcgApiId: 'dp5-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/53.png","large":"https://images.pokemontcg.io/dp5/53_hires.png"}',
    searchName: 'Buneary (MD 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Burmy Sandy Cloak',
    tcgApiId: 'dp5-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/54.png","large":"https://images.pokemontcg.io/dp5/54_hires.png"}',
    searchName: 'Burmy Sandy Cloak (MD 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Chatot',
    tcgApiId: 'dp5-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/55.png","large":"https://images.pokemontcg.io/dp5/55_hires.png"}',
    searchName: 'Chatot (MD 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Chimchar',
    tcgApiId: 'dp5-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/56.png","large":"https://images.pokemontcg.io/dp5/56_hires.png"}',
    searchName: 'Chimchar (MD 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Chimchar',
    tcgApiId: 'dp5-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/57.png","large":"https://images.pokemontcg.io/dp5/57_hires.png"}',
    searchName: 'Chimchar (MD 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Chingling',
    tcgApiId: 'dp5-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/58.png","large":"https://images.pokemontcg.io/dp5/58_hires.png"}',
    searchName: 'Chingling (MD 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Combee',
    tcgApiId: 'dp5-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/59.png","large":"https://images.pokemontcg.io/dp5/59_hires.png"}',
    searchName: 'Combee (MD 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Croagunk',
    tcgApiId: 'dp5-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/60.png","large":"https://images.pokemontcg.io/dp5/60_hires.png"}',
    searchName: 'Croagunk (MD 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Drifloon',
    tcgApiId: 'dp5-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/61.png","large":"https://images.pokemontcg.io/dp5/61_hires.png"}',
    searchName: 'Drifloon (MD 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Eevee',
    tcgApiId: 'dp5-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/62.png","large":"https://images.pokemontcg.io/dp5/62_hires.png"}',
    searchName: 'Eevee (MD 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Eevee',
    tcgApiId: 'dp5-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/63.png","large":"https://images.pokemontcg.io/dp5/63_hires.png"}',
    searchName: 'Eevee (MD 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Electrike',
    tcgApiId: 'dp5-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/64.png","large":"https://images.pokemontcg.io/dp5/64_hires.png"}',
    searchName: 'Electrike (MD 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Glameow',
    tcgApiId: 'dp5-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/65.png","large":"https://images.pokemontcg.io/dp5/65_hires.png"}',
    searchName: 'Glameow (MD 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Hippopotas',
    tcgApiId: 'dp5-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/66.png","large":"https://images.pokemontcg.io/dp5/66_hires.png"}',
    searchName: 'Hippopotas (MD 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Kabuto',
    tcgApiId: 'dp5-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/67.png","large":"https://images.pokemontcg.io/dp5/67_hires.png"}',
    searchName: 'Kabuto (MD 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Munchlax',
    tcgApiId: 'dp5-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/68.png","large":"https://images.pokemontcg.io/dp5/68_hires.png"}',
    searchName: 'Munchlax (MD 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Omanyte',
    tcgApiId: 'dp5-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/69.png","large":"https://images.pokemontcg.io/dp5/69_hires.png"}',
    searchName: 'Omanyte (MD 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Pikachu',
    tcgApiId: 'dp5-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/70.png","large":"https://images.pokemontcg.io/dp5/70_hires.png"}',
    searchName: 'Pikachu (MD 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Piplup',
    tcgApiId: 'dp5-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/71.png","large":"https://images.pokemontcg.io/dp5/71_hires.png"}',
    searchName: 'Piplup (MD 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Piplup',
    tcgApiId: 'dp5-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/72.png","large":"https://images.pokemontcg.io/dp5/72_hires.png"}',
    searchName: 'Piplup (MD 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Shellos East Sea',
    tcgApiId: 'dp5-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/73.png","large":"https://images.pokemontcg.io/dp5/73_hires.png"}',
    searchName: 'Shellos East Sea (MD 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Spearow',
    tcgApiId: 'dp5-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/74.png","large":"https://images.pokemontcg.io/dp5/74_hires.png"}',
    searchName: 'Spearow (MD 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Starly',
    tcgApiId: 'dp5-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/75.png","large":"https://images.pokemontcg.io/dp5/75_hires.png"}',
    searchName: 'Starly (MD 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Stunky',
    tcgApiId: 'dp5-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/76.png","large":"https://images.pokemontcg.io/dp5/76_hires.png"}',
    searchName: 'Stunky (MD 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Turtwig',
    tcgApiId: 'dp5-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/77.png","large":"https://images.pokemontcg.io/dp5/77_hires.png"}',
    searchName: 'Turtwig (MD 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Turtwig',
    tcgApiId: 'dp5-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/78.png","large":"https://images.pokemontcg.io/dp5/78_hires.png"}',
    searchName: 'Turtwig (MD 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Dawn Stadium',
    tcgApiId: 'dp5-79',
    number: '79',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/79.png","large":"https://images.pokemontcg.io/dp5/79_hires.png"}',
    searchName: 'Dawn Stadium (MD 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Dusk Ball',
    tcgApiId: 'dp5-80',
    number: '80',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/80.png","large":"https://images.pokemontcg.io/dp5/80_hires.png"}',
    searchName: 'Dusk Ball (MD 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Energy Restore',
    tcgApiId: 'dp5-81',
    number: '81',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/81.png","large":"https://images.pokemontcg.io/dp5/81_hires.png"}',
    searchName: 'Energy Restore (MD 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Fossil Excavator',
    tcgApiId: 'dp5-82',
    number: '82',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/82.png","large":"https://images.pokemontcg.io/dp5/82_hires.png"}',
    searchName: 'Fossil Excavator (MD 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: "Mom's Kindness",
    tcgApiId: 'dp5-83',
    number: '83',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/83.png","large":"https://images.pokemontcg.io/dp5/83_hires.png"}',
    searchName: "Mom's Kindness (MD 83)",
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Old Amber',
    tcgApiId: 'dp5-84',
    number: '84',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/84.png","large":"https://images.pokemontcg.io/dp5/84_hires.png"}',
    searchName: 'Old Amber (MD 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Poké Ball',
    tcgApiId: 'dp5-85',
    number: '85',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/85.png","large":"https://images.pokemontcg.io/dp5/85_hires.png"}',
    searchName: 'Poké Ball (MD 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Quick Ball',
    tcgApiId: 'dp5-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/86.png","large":"https://images.pokemontcg.io/dp5/86_hires.png"}',
    searchName: 'Quick Ball (MD 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Super Scoop Up',
    tcgApiId: 'dp5-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/87.png","large":"https://images.pokemontcg.io/dp5/87_hires.png"}',
    searchName: 'Super Scoop Up (MD 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Warp Point',
    tcgApiId: 'dp5-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/88.png","large":"https://images.pokemontcg.io/dp5/88_hires.png"}',
    searchName: 'Warp Point (MD 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Dome Fossil',
    tcgApiId: 'dp5-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/89.png","large":"https://images.pokemontcg.io/dp5/89_hires.png"}',
    searchName: 'Dome Fossil (MD 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Energy Search',
    tcgApiId: 'dp5-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/90.png","large":"https://images.pokemontcg.io/dp5/90_hires.png"}',
    searchName: 'Energy Search (MD 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Helix Fossil',
    tcgApiId: 'dp5-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/91.png","large":"https://images.pokemontcg.io/dp5/91_hires.png"}',
    searchName: 'Helix Fossil (MD 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Call Energy',
    tcgApiId: 'dp5-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/92.png","large":"https://images.pokemontcg.io/dp5/92_hires.png"}',
    searchName: 'Call Energy (MD 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Darkness Energy',
    tcgApiId: 'dp5-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/93.png","large":"https://images.pokemontcg.io/dp5/93_hires.png"}',
    searchName: 'Darkness Energy (MD 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Health Energy',
    tcgApiId: 'dp5-94',
    number: '94',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/94.png","large":"https://images.pokemontcg.io/dp5/94_hires.png"}',
    searchName: 'Health Energy (MD 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Metal Energy',
    tcgApiId: 'dp5-95',
    number: '95',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/95.png","large":"https://images.pokemontcg.io/dp5/95_hires.png"}',
    searchName: 'Metal Energy (MD 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Recover Energy',
    tcgApiId: 'dp5-96',
    number: '96',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/96.png","large":"https://images.pokemontcg.io/dp5/96_hires.png"}',
    searchName: 'Recover Energy (MD 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Garchomp LV.X',
    tcgApiId: 'dp5-97',
    number: '97',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/97.png","large":"https://images.pokemontcg.io/dp5/97_hires.png"}',
    searchName: 'Garchomp LV.X (MD 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Glaceon LV.X',
    tcgApiId: 'dp5-98',
    number: '98',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/98.png","large":"https://images.pokemontcg.io/dp5/98_hires.png"}',
    searchName: 'Glaceon LV.X (MD 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Leafeon LV.X',
    tcgApiId: 'dp5-99',
    number: '99',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/99.png","large":"https://images.pokemontcg.io/dp5/99_hires.png"}',
    searchName: 'Leafeon LV.X (MD 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dp5',
    name: 'Porygon-Z LV.X',
    tcgApiId: 'dp5-100',
    number: '100',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/dp5/100.png","large":"https://images.pokemontcg.io/dp5/100_hires.png"}',
    searchName: 'Porygon-Z LV.X (MD 100)',
  },
];
