export const cardSeedDpp = [
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Turtwig',
    tcgApiId: 'dpp-DP01',
    number: 'DP01',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP01.png","large":"https://images.pokemontcg.io/dpp/DP01_hires.png"}',
    searchName: 'Turtwig (PR-DPP DP01)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Chimchar',
    tcgApiId: 'dpp-DP02',
    number: 'DP02',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP02.png","large":"https://images.pokemontcg.io/dpp/DP02_hires.png"}',
    searchName: 'Chimchar (PR-DPP DP02)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Piplup',
    tcgApiId: 'dpp-DP03',
    number: 'DP03',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP03.png","large":"https://images.pokemontcg.io/dpp/DP03_hires.png"}',
    searchName: 'Piplup (PR-DPP DP03)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Pachirisu',
    tcgApiId: 'dpp-DP04',
    number: 'DP04',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP04.png","large":"https://images.pokemontcg.io/dpp/DP04_hires.png"}',
    searchName: 'Pachirisu (PR-DPP DP04)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Tropical Wind',
    tcgApiId: 'dpp-DP05',
    number: 'DP05',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP05.png","large":"https://images.pokemontcg.io/dpp/DP05_hires.png"}',
    searchName: 'Tropical Wind (PR-DPP DP05)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Buneary',
    tcgApiId: 'dpp-DP06',
    number: 'DP06',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP06.png","large":"https://images.pokemontcg.io/dpp/DP06_hires.png"}',
    searchName: 'Buneary (PR-DPP DP06)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Cranidos',
    tcgApiId: 'dpp-DP07',
    number: 'DP07',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP07.png","large":"https://images.pokemontcg.io/dpp/DP07_hires.png"}',
    searchName: 'Cranidos (PR-DPP DP07)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Shieldon',
    tcgApiId: 'dpp-DP08',
    number: 'DP08',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP08.png","large":"https://images.pokemontcg.io/dpp/DP08_hires.png"}',
    searchName: 'Shieldon (PR-DPP DP08)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Torterra LV.X',
    tcgApiId: 'dpp-DP09',
    number: 'DP09',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP09.png","large":"https://images.pokemontcg.io/dpp/DP09_hires.png"}',
    searchName: 'Torterra LV.X (PR-DPP DP09)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Infernape LV.X',
    tcgApiId: 'dpp-DP10',
    number: 'DP10',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP10.png","large":"https://images.pokemontcg.io/dpp/DP10_hires.png"}',
    searchName: 'Infernape LV.X (PR-DPP DP10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Empoleon LV.X',
    tcgApiId: 'dpp-DP11',
    number: 'DP11',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP11.png","large":"https://images.pokemontcg.io/dpp/DP11_hires.png"}',
    searchName: 'Empoleon LV.X (PR-DPP DP11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Lucario LV.X',
    tcgApiId: 'dpp-DP12',
    number: 'DP12',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP12.png","large":"https://images.pokemontcg.io/dpp/DP12_hires.png"}',
    searchName: 'Lucario LV.X (PR-DPP DP12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Buizel',
    tcgApiId: 'dpp-DP13',
    number: 'DP13',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP13.png","large":"https://images.pokemontcg.io/dpp/DP13_hires.png"}',
    searchName: 'Buizel (PR-DPP DP13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Chatot',
    tcgApiId: 'dpp-DP14',
    number: 'DP14',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP14.png","large":"https://images.pokemontcg.io/dpp/DP14_hires.png"}',
    searchName: 'Chatot (PR-DPP DP14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Shinx',
    tcgApiId: 'dpp-DP15',
    number: 'DP15',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP15.png","large":"https://images.pokemontcg.io/dpp/DP15_hires.png"}',
    searchName: 'Shinx (PR-DPP DP15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Pikachu',
    tcgApiId: 'dpp-DP16',
    number: 'DP16',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP16.png","large":"https://images.pokemontcg.io/dpp/DP16_hires.png"}',
    searchName: 'Pikachu (PR-DPP DP16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Dialga LV.X',
    tcgApiId: 'dpp-DP17',
    number: 'DP17',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP17.png","large":"https://images.pokemontcg.io/dpp/DP17_hires.png"}',
    searchName: 'Dialga LV.X (PR-DPP DP17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Palkia LV.X',
    tcgApiId: 'dpp-DP18',
    number: 'DP18',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP18.png","large":"https://images.pokemontcg.io/dpp/DP18_hires.png"}',
    searchName: 'Palkia LV.X (PR-DPP DP18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Darkrai LV.X',
    tcgApiId: 'dpp-DP19',
    number: 'DP19',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP19.png","large":"https://images.pokemontcg.io/dpp/DP19_hires.png"}',
    searchName: 'Darkrai LV.X (PR-DPP DP19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Magmortar',
    tcgApiId: 'dpp-DP20',
    number: 'DP20',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP20.png","large":"https://images.pokemontcg.io/dpp/DP20_hires.png"}',
    searchName: 'Magmortar (PR-DPP DP20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Raichu',
    tcgApiId: 'dpp-DP21',
    number: 'DP21',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP21.png","large":"https://images.pokemontcg.io/dpp/DP21_hires.png"}',
    searchName: 'Raichu (PR-DPP DP21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Mime Jr.',
    tcgApiId: 'dpp-DP22',
    number: 'DP22',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP22.png","large":"https://images.pokemontcg.io/dpp/DP22_hires.png"}',
    searchName: 'Mime Jr. (PR-DPP DP22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Glameow',
    tcgApiId: 'dpp-DP23',
    number: 'DP23',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP23.png","large":"https://images.pokemontcg.io/dpp/DP23_hires.png"}',
    searchName: 'Glameow (PR-DPP DP23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Darkrai',
    tcgApiId: 'dpp-DP24',
    number: 'DP24',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP24.png","large":"https://images.pokemontcg.io/dpp/DP24_hires.png"}',
    searchName: 'Darkrai (PR-DPP DP24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Tropical Wind',
    tcgApiId: 'dpp-DP25',
    number: 'DP25',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP25.png","large":"https://images.pokemontcg.io/dpp/DP25_hires.png"}',
    searchName: 'Tropical Wind (PR-DPP DP25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Dialga',
    tcgApiId: 'dpp-DP26',
    number: 'DP26',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP26.png","large":"https://images.pokemontcg.io/dpp/DP26_hires.png"}',
    searchName: 'Dialga (PR-DPP DP26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Palkia',
    tcgApiId: 'dpp-DP27',
    number: 'DP27',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP27.png","large":"https://images.pokemontcg.io/dpp/DP27_hires.png"}',
    searchName: 'Palkia (PR-DPP DP27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Mewtwo LV.X',
    tcgApiId: 'dpp-DP28',
    number: 'DP28',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP28.png","large":"https://images.pokemontcg.io/dpp/DP28_hires.png"}',
    searchName: 'Mewtwo LV.X (PR-DPP DP28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Rhyperior LV.X',
    tcgApiId: 'dpp-DP29',
    number: 'DP29',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP29.png","large":"https://images.pokemontcg.io/dpp/DP29_hires.png"}',
    searchName: 'Rhyperior LV.X (PR-DPP DP29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Regigigas LV.X',
    tcgApiId: 'dpp-DP30',
    number: 'DP30',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP30.png","large":"https://images.pokemontcg.io/dpp/DP30_hires.png"}',
    searchName: 'Regigigas LV.X (PR-DPP DP30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Heatran LV.X',
    tcgApiId: 'dpp-DP31',
    number: 'DP31',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP31.png","large":"https://images.pokemontcg.io/dpp/DP31_hires.png"}',
    searchName: 'Heatran LV.X (PR-DPP DP31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Magnezone',
    tcgApiId: 'dpp-DP32',
    number: 'DP32',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP32.png","large":"https://images.pokemontcg.io/dpp/DP32_hires.png"}',
    searchName: 'Magnezone (PR-DPP DP32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Dusknoir',
    tcgApiId: 'dpp-DP33',
    number: 'DP33',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP33.png","large":"https://images.pokemontcg.io/dpp/DP33_hires.png"}',
    searchName: 'Dusknoir (PR-DPP DP33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Drifblim',
    tcgApiId: 'dpp-DP34',
    number: 'DP34',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP34.png","large":"https://images.pokemontcg.io/dpp/DP34_hires.png"}',
    searchName: 'Drifblim (PR-DPP DP34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Porygon-Z',
    tcgApiId: 'dpp-DP35',
    number: 'DP35',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP35.png","large":"https://images.pokemontcg.io/dpp/DP35_hires.png"}',
    searchName: 'Porygon-Z (PR-DPP DP35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Gliscor',
    tcgApiId: 'dpp-DP36',
    number: 'DP36',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP36.png","large":"https://images.pokemontcg.io/dpp/DP36_hires.png"}',
    searchName: 'Gliscor (PR-DPP DP36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Dialga LV.X',
    tcgApiId: 'dpp-DP37',
    number: 'DP37',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP37.png","large":"https://images.pokemontcg.io/dpp/DP37_hires.png"}',
    searchName: 'Dialga LV.X (PR-DPP DP37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Giratina LV.X',
    tcgApiId: 'dpp-DP38',
    number: 'DP38',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP38.png","large":"https://images.pokemontcg.io/dpp/DP38_hires.png"}',
    searchName: 'Giratina LV.X (PR-DPP DP38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Shaymin LV.X',
    tcgApiId: 'dpp-DP39',
    number: 'DP39',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP39.png","large":"https://images.pokemontcg.io/dpp/DP39_hires.png"}',
    searchName: 'Shaymin LV.X (PR-DPP DP39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Regigigas',
    tcgApiId: 'dpp-DP40',
    number: 'DP40',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP40.png","large":"https://images.pokemontcg.io/dpp/DP40_hires.png"}',
    searchName: 'Regigigas (PR-DPP DP40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Toxicroak G',
    tcgApiId: 'dpp-DP41',
    number: 'DP41',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP41.png","large":"https://images.pokemontcg.io/dpp/DP41_hires.png"}',
    searchName: 'Toxicroak G (PR-DPP DP41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Carnivine G',
    tcgApiId: 'dpp-DP42',
    number: 'DP42',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP42.png","large":"https://images.pokemontcg.io/dpp/DP42_hires.png"}',
    searchName: 'Carnivine G (PR-DPP DP42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Probopass G',
    tcgApiId: 'dpp-DP43',
    number: 'DP43',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP43.png","large":"https://images.pokemontcg.io/dpp/DP43_hires.png"}',
    searchName: 'Probopass G (PR-DPP DP43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Magnezone',
    tcgApiId: 'dpp-DP44',
    number: 'DP44',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP44.png","large":"https://images.pokemontcg.io/dpp/DP44_hires.png"}',
    searchName: 'Magnezone (PR-DPP DP44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Charizard G LV.X',
    tcgApiId: 'dpp-DP45',
    number: 'DP45',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP45.png","large":"https://images.pokemontcg.io/dpp/DP45_hires.png"}',
    searchName: 'Charizard G LV.X (PR-DPP DP45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Garchomp C LV.X',
    tcgApiId: 'dpp-DP46',
    number: 'DP46',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP46.png","large":"https://images.pokemontcg.io/dpp/DP46_hires.png"}',
    searchName: 'Garchomp C LV.X (PR-DPP DP46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Rayquaza C LV.X',
    tcgApiId: 'dpp-DP47',
    number: 'DP47',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP47.png","large":"https://images.pokemontcg.io/dpp/DP47_hires.png"}',
    searchName: 'Rayquaza C LV.X (PR-DPP DP47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Tropical Wind',
    tcgApiId: 'dpp-DP48',
    number: 'DP48',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP48.png","large":"https://images.pokemontcg.io/dpp/DP48_hires.png"}',
    searchName: 'Tropical Wind (PR-DPP DP48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Dialga',
    tcgApiId: 'dpp-DP49',
    number: 'DP49',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP49.png","large":"https://images.pokemontcg.io/dpp/DP49_hires.png"}',
    searchName: 'Dialga (PR-DPP DP49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Arceus',
    tcgApiId: 'dpp-DP50',
    number: 'DP50',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP50.png","large":"https://images.pokemontcg.io/dpp/DP50_hires.png"}',
    searchName: 'Arceus (PR-DPP DP50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Cresselia',
    tcgApiId: 'dpp-DP51',
    number: 'DP51',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP51.png","large":"https://images.pokemontcg.io/dpp/DP51_hires.png"}',
    searchName: 'Cresselia (PR-DPP DP51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Darkrai',
    tcgApiId: 'dpp-DP52',
    number: 'DP52',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP52.png","large":"https://images.pokemontcg.io/dpp/DP52_hires.png"}',
    searchName: 'Darkrai (PR-DPP DP52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Arceus LV.X',
    tcgApiId: 'dpp-DP53',
    number: 'DP53',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP53.png","large":"https://images.pokemontcg.io/dpp/DP53_hires.png"}',
    searchName: 'Arceus LV.X (PR-DPP DP53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Beginning Door',
    tcgApiId: 'dpp-DP54',
    number: 'DP54',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP54.png","large":"https://images.pokemontcg.io/dpp/DP54_hires.png"}',
    searchName: 'Beginning Door (PR-DPP DP54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Ultimate Zone',
    tcgApiId: 'dpp-DP55',
    number: 'DP55',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP55.png","large":"https://images.pokemontcg.io/dpp/DP55_hires.png"}',
    searchName: 'Ultimate Zone (PR-DPP DP55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dpp',
    name: 'Arceus LV.X',
    tcgApiId: 'dpp-DP56',
    number: 'DP56',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/dpp/DP56.png","large":"https://images.pokemontcg.io/dpp/DP56_hires.png"}',
    searchName: 'Arceus LV.X (PR-DPP DP56)',
  },
];
