export const cardSeedDv1 = [
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Dratini',
    tcgApiId: 'dv1-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/1.png","large":"https://images.pokemontcg.io/dv1/1_hires.png"}',
    searchName: 'Dratini (DRV 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Dratini',
    tcgApiId: 'dv1-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/2.png","large":"https://images.pokemontcg.io/dv1/2_hires.png"}',
    searchName: 'Dratini (DRV 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Dragonair',
    tcgApiId: 'dv1-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/3.png","large":"https://images.pokemontcg.io/dv1/3_hires.png"}',
    searchName: 'Dragonair (DRV 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Dragonair',
    tcgApiId: 'dv1-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/4.png","large":"https://images.pokemontcg.io/dv1/4_hires.png"}',
    searchName: 'Dragonair (DRV 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Dragonite',
    tcgApiId: 'dv1-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/5.png","large":"https://images.pokemontcg.io/dv1/5_hires.png"}',
    searchName: 'Dragonite (DRV 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Bagon',
    tcgApiId: 'dv1-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/6.png","large":"https://images.pokemontcg.io/dv1/6_hires.png"}',
    searchName: 'Bagon (DRV 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Shelgon',
    tcgApiId: 'dv1-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/7.png","large":"https://images.pokemontcg.io/dv1/7_hires.png"}',
    searchName: 'Shelgon (DRV 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Salamence',
    tcgApiId: 'dv1-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/8.png","large":"https://images.pokemontcg.io/dv1/8_hires.png"}',
    searchName: 'Salamence (DRV 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Latias',
    tcgApiId: 'dv1-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/9.png","large":"https://images.pokemontcg.io/dv1/9_hires.png"}',
    searchName: 'Latias (DRV 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Latios',
    tcgApiId: 'dv1-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/10.png","large":"https://images.pokemontcg.io/dv1/10_hires.png"}',
    searchName: 'Latios (DRV 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Rayquaza',
    tcgApiId: 'dv1-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/11.png","large":"https://images.pokemontcg.io/dv1/11_hires.png"}',
    searchName: 'Rayquaza (DRV 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Axew',
    tcgApiId: 'dv1-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/12.png","large":"https://images.pokemontcg.io/dv1/12_hires.png"}',
    searchName: 'Axew (DRV 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Axew',
    tcgApiId: 'dv1-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/13.png","large":"https://images.pokemontcg.io/dv1/13_hires.png"}',
    searchName: 'Axew (DRV 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Fraxure',
    tcgApiId: 'dv1-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/14.png","large":"https://images.pokemontcg.io/dv1/14_hires.png"}',
    searchName: 'Fraxure (DRV 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Fraxure',
    tcgApiId: 'dv1-15',
    number: '15',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/15.png","large":"https://images.pokemontcg.io/dv1/15_hires.png"}',
    searchName: 'Fraxure (DRV 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Haxorus',
    tcgApiId: 'dv1-16',
    number: '16',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/16.png","large":"https://images.pokemontcg.io/dv1/16_hires.png"}',
    searchName: 'Haxorus (DRV 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Druddigon',
    tcgApiId: 'dv1-17',
    number: '17',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/17.png","large":"https://images.pokemontcg.io/dv1/17_hires.png"}',
    searchName: 'Druddigon (DRV 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Exp. Share',
    tcgApiId: 'dv1-18',
    number: '18',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/18.png","large":"https://images.pokemontcg.io/dv1/18_hires.png"}',
    searchName: 'Exp. Share (DRV 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'First Ticket',
    tcgApiId: 'dv1-19',
    number: '19',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/19.png","large":"https://images.pokemontcg.io/dv1/19_hires.png"}',
    searchName: 'First Ticket (DRV 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Super Rod',
    tcgApiId: 'dv1-20',
    number: '20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/20.png","large":"https://images.pokemontcg.io/dv1/20_hires.png"}',
    searchName: 'Super Rod (DRV 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'dv1',
    name: 'Kyurem',
    tcgApiId: 'dv1-21',
    number: '21',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/dv1/21.png","large":"https://images.pokemontcg.io/dv1/21_hires.png"}',
    searchName: 'Kyurem (DRV 21)',
  },
];
