export const cardSeedEcard3 = [
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Aerodactyl',
    tcgApiId: 'ecard3-1',
    number: '1',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/1.png","large":"https://images.pokemontcg.io/ecard3/1_hires.png"}',
    searchName: 'Aerodactyl (SK 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Alakazam',
    tcgApiId: 'ecard3-2',
    number: '2',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/2.png","large":"https://images.pokemontcg.io/ecard3/2_hires.png"}',
    searchName: 'Alakazam (SK 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Arcanine',
    tcgApiId: 'ecard3-3',
    number: '3',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/3.png","large":"https://images.pokemontcg.io/ecard3/3_hires.png"}',
    searchName: 'Arcanine (SK 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Articuno',
    tcgApiId: 'ecard3-4',
    number: '4',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/4.png","large":"https://images.pokemontcg.io/ecard3/4_hires.png"}',
    searchName: 'Articuno (SK 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Beedrill',
    tcgApiId: 'ecard3-5',
    number: '5',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/5.png","large":"https://images.pokemontcg.io/ecard3/5_hires.png"}',
    searchName: 'Beedrill (SK 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Crobat',
    tcgApiId: 'ecard3-6',
    number: '6',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/6.png","large":"https://images.pokemontcg.io/ecard3/6_hires.png"}',
    searchName: 'Crobat (SK 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Dewgong',
    tcgApiId: 'ecard3-7',
    number: '7',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/7.png","large":"https://images.pokemontcg.io/ecard3/7_hires.png"}',
    searchName: 'Dewgong (SK 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Flareon',
    tcgApiId: 'ecard3-8',
    number: '8',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/8.png","large":"https://images.pokemontcg.io/ecard3/8_hires.png"}',
    searchName: 'Flareon (SK 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Forretress',
    tcgApiId: 'ecard3-9',
    number: '9',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/9.png","large":"https://images.pokemontcg.io/ecard3/9_hires.png"}',
    searchName: 'Forretress (SK 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Gengar',
    tcgApiId: 'ecard3-10',
    number: '10',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/10.png","large":"https://images.pokemontcg.io/ecard3/10_hires.png"}',
    searchName: 'Gengar (SK 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Gyarados',
    tcgApiId: 'ecard3-11',
    number: '11',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/11.png","large":"https://images.pokemontcg.io/ecard3/11_hires.png"}',
    searchName: 'Gyarados (SK 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Houndoom',
    tcgApiId: 'ecard3-12',
    number: '12',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/12.png","large":"https://images.pokemontcg.io/ecard3/12_hires.png"}',
    searchName: 'Houndoom (SK 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Jolteon',
    tcgApiId: 'ecard3-13',
    number: '13',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/13.png","large":"https://images.pokemontcg.io/ecard3/13_hires.png"}',
    searchName: 'Jolteon (SK 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Kabutops',
    tcgApiId: 'ecard3-14',
    number: '14',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/14.png","large":"https://images.pokemontcg.io/ecard3/14_hires.png"}',
    searchName: 'Kabutops (SK 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Ledian',
    tcgApiId: 'ecard3-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/15.png","large":"https://images.pokemontcg.io/ecard3/15_hires.png"}',
    searchName: 'Ledian (SK 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Machamp',
    tcgApiId: 'ecard3-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/16.png","large":"https://images.pokemontcg.io/ecard3/16_hires.png"}',
    searchName: 'Machamp (SK 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magcargo',
    tcgApiId: 'ecard3-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/17.png","large":"https://images.pokemontcg.io/ecard3/17_hires.png"}',
    searchName: 'Magcargo (SK 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magcargo',
    tcgApiId: 'ecard3-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/18.png","large":"https://images.pokemontcg.io/ecard3/18_hires.png"}',
    searchName: 'Magcargo (SK 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magneton',
    tcgApiId: 'ecard3-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/19.png","large":"https://images.pokemontcg.io/ecard3/19_hires.png"}',
    searchName: 'Magneton (SK 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magneton',
    tcgApiId: 'ecard3-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/20.png","large":"https://images.pokemontcg.io/ecard3/20_hires.png"}',
    searchName: 'Magneton (SK 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Moltres',
    tcgApiId: 'ecard3-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/21.png","large":"https://images.pokemontcg.io/ecard3/21_hires.png"}',
    searchName: 'Moltres (SK 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Nidoqueen',
    tcgApiId: 'ecard3-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/22.png","large":"https://images.pokemontcg.io/ecard3/22_hires.png"}',
    searchName: 'Nidoqueen (SK 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Omastar',
    tcgApiId: 'ecard3-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/23.png","large":"https://images.pokemontcg.io/ecard3/23_hires.png"}',
    searchName: 'Omastar (SK 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Piloswine',
    tcgApiId: 'ecard3-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/24.png","large":"https://images.pokemontcg.io/ecard3/24_hires.png"}',
    searchName: 'Piloswine (SK 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Politoed',
    tcgApiId: 'ecard3-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/25.png","large":"https://images.pokemontcg.io/ecard3/25_hires.png"}',
    searchName: 'Politoed (SK 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Poliwrath',
    tcgApiId: 'ecard3-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/26.png","large":"https://images.pokemontcg.io/ecard3/26_hires.png"}',
    searchName: 'Poliwrath (SK 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Raichu',
    tcgApiId: 'ecard3-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/27.png","large":"https://images.pokemontcg.io/ecard3/27_hires.png"}',
    searchName: 'Raichu (SK 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Raikou',
    tcgApiId: 'ecard3-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/28.png","large":"https://images.pokemontcg.io/ecard3/28_hires.png"}',
    searchName: 'Raikou (SK 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Rhydon',
    tcgApiId: 'ecard3-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/29.png","large":"https://images.pokemontcg.io/ecard3/29_hires.png"}',
    searchName: 'Rhydon (SK 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Starmie',
    tcgApiId: 'ecard3-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/30.png","large":"https://images.pokemontcg.io/ecard3/30_hires.png"}',
    searchName: 'Starmie (SK 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Steelix',
    tcgApiId: 'ecard3-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/31.png","large":"https://images.pokemontcg.io/ecard3/31_hires.png"}',
    searchName: 'Steelix (SK 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Umbreon',
    tcgApiId: 'ecard3-32',
    number: '32',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/32.png","large":"https://images.pokemontcg.io/ecard3/32_hires.png"}',
    searchName: 'Umbreon (SK 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Vaporeon',
    tcgApiId: 'ecard3-33',
    number: '33',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/33.png","large":"https://images.pokemontcg.io/ecard3/33_hires.png"}',
    searchName: 'Vaporeon (SK 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Wigglytuff',
    tcgApiId: 'ecard3-34',
    number: '34',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/34.png","large":"https://images.pokemontcg.io/ecard3/34_hires.png"}',
    searchName: 'Wigglytuff (SK 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Xatu',
    tcgApiId: 'ecard3-35',
    number: '35',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/35.png","large":"https://images.pokemontcg.io/ecard3/35_hires.png"}',
    searchName: 'Xatu (SK 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Electrode',
    tcgApiId: 'ecard3-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/36.png","large":"https://images.pokemontcg.io/ecard3/36_hires.png"}',
    searchName: 'Electrode (SK 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Kabuto',
    tcgApiId: 'ecard3-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/37.png","large":"https://images.pokemontcg.io/ecard3/37_hires.png"}',
    searchName: 'Kabuto (SK 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Machoke',
    tcgApiId: 'ecard3-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/38.png","large":"https://images.pokemontcg.io/ecard3/38_hires.png"}',
    searchName: 'Machoke (SK 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Misdreavus',
    tcgApiId: 'ecard3-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/39.png","large":"https://images.pokemontcg.io/ecard3/39_hires.png"}',
    searchName: 'Misdreavus (SK 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Noctowl',
    tcgApiId: 'ecard3-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/40.png","large":"https://images.pokemontcg.io/ecard3/40_hires.png"}',
    searchName: 'Noctowl (SK 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Omanyte',
    tcgApiId: 'ecard3-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/41.png","large":"https://images.pokemontcg.io/ecard3/41_hires.png"}',
    searchName: 'Omanyte (SK 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Persian',
    tcgApiId: 'ecard3-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/42.png","large":"https://images.pokemontcg.io/ecard3/42_hires.png"}',
    searchName: 'Persian (SK 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Piloswine',
    tcgApiId: 'ecard3-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/43.png","large":"https://images.pokemontcg.io/ecard3/43_hires.png"}',
    searchName: 'Piloswine (SK 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Starmie',
    tcgApiId: 'ecard3-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/44.png","large":"https://images.pokemontcg.io/ecard3/44_hires.png"}',
    searchName: 'Starmie (SK 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Wobbuffet',
    tcgApiId: 'ecard3-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/45.png","large":"https://images.pokemontcg.io/ecard3/45_hires.png"}',
    searchName: 'Wobbuffet (SK 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Abra',
    tcgApiId: 'ecard3-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/46.png","large":"https://images.pokemontcg.io/ecard3/46_hires.png"}',
    searchName: 'Abra (SK 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Buried Fossil',
    tcgApiId: 'ecard3-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/47.png","large":"https://images.pokemontcg.io/ecard3/47_hires.png"}',
    searchName: 'Buried Fossil (SK 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Cleffa',
    tcgApiId: 'ecard3-48',
    number: '48',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/48.png","large":"https://images.pokemontcg.io/ecard3/48_hires.png"}',
    searchName: 'Cleffa (SK 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Delibird',
    tcgApiId: 'ecard3-49',
    number: '49',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/49.png","large":"https://images.pokemontcg.io/ecard3/49_hires.png"}',
    searchName: 'Delibird (SK 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Diglett',
    tcgApiId: 'ecard3-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/50.png","large":"https://images.pokemontcg.io/ecard3/50_hires.png"}',
    searchName: 'Diglett (SK 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Ditto',
    tcgApiId: 'ecard3-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/51.png","large":"https://images.pokemontcg.io/ecard3/51_hires.png"}',
    searchName: 'Ditto (SK 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Dugtrio',
    tcgApiId: 'ecard3-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/52.png","large":"https://images.pokemontcg.io/ecard3/52_hires.png"}',
    searchName: 'Dugtrio (SK 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Dunsparce',
    tcgApiId: 'ecard3-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/53.png","large":"https://images.pokemontcg.io/ecard3/53_hires.png"}',
    searchName: 'Dunsparce (SK 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Eevee',
    tcgApiId: 'ecard3-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/54.png","large":"https://images.pokemontcg.io/ecard3/54_hires.png"}',
    searchName: 'Eevee (SK 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: "Farfetch'd",
    tcgApiId: 'ecard3-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/55.png","large":"https://images.pokemontcg.io/ecard3/55_hires.png"}',
    searchName: "Farfetch'd (SK 55)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Forretress',
    tcgApiId: 'ecard3-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/56.png","large":"https://images.pokemontcg.io/ecard3/56_hires.png"}',
    searchName: 'Forretress (SK 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Gastly',
    tcgApiId: 'ecard3-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/57.png","large":"https://images.pokemontcg.io/ecard3/57_hires.png"}',
    searchName: 'Gastly (SK 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Girafarig',
    tcgApiId: 'ecard3-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/58.png","large":"https://images.pokemontcg.io/ecard3/58_hires.png"}',
    searchName: 'Girafarig (SK 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Gligar',
    tcgApiId: 'ecard3-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/59.png","large":"https://images.pokemontcg.io/ecard3/59_hires.png"}',
    searchName: 'Gligar (SK 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Golbat',
    tcgApiId: 'ecard3-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/60.png","large":"https://images.pokemontcg.io/ecard3/60_hires.png"}',
    searchName: 'Golbat (SK 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Granbull',
    tcgApiId: 'ecard3-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/61.png","large":"https://images.pokemontcg.io/ecard3/61_hires.png"}',
    searchName: 'Granbull (SK 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Growlithe',
    tcgApiId: 'ecard3-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/62.png","large":"https://images.pokemontcg.io/ecard3/62_hires.png"}',
    searchName: 'Growlithe (SK 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Haunter',
    tcgApiId: 'ecard3-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/63.png","large":"https://images.pokemontcg.io/ecard3/63_hires.png"}',
    searchName: 'Haunter (SK 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Heracross',
    tcgApiId: 'ecard3-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/64.png","large":"https://images.pokemontcg.io/ecard3/64_hires.png"}',
    searchName: 'Heracross (SK 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Hoothoot',
    tcgApiId: 'ecard3-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/65.png","large":"https://images.pokemontcg.io/ecard3/65_hires.png"}',
    searchName: 'Hoothoot (SK 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Houndour',
    tcgApiId: 'ecard3-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/66.png","large":"https://images.pokemontcg.io/ecard3/66_hires.png"}',
    searchName: 'Houndour (SK 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Igglybuff',
    tcgApiId: 'ecard3-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/67.png","large":"https://images.pokemontcg.io/ecard3/67_hires.png"}',
    searchName: 'Igglybuff (SK 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Jigglypuff',
    tcgApiId: 'ecard3-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/68.png","large":"https://images.pokemontcg.io/ecard3/68_hires.png"}',
    searchName: 'Jigglypuff (SK 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Kadabra',
    tcgApiId: 'ecard3-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/69.png","large":"https://images.pokemontcg.io/ecard3/69_hires.png"}',
    searchName: 'Kadabra (SK 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Kakuna',
    tcgApiId: 'ecard3-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/70.png","large":"https://images.pokemontcg.io/ecard3/70_hires.png"}',
    searchName: 'Kakuna (SK 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Lapras',
    tcgApiId: 'ecard3-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/71.png","large":"https://images.pokemontcg.io/ecard3/71_hires.png"}',
    searchName: 'Lapras (SK 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Ledyba',
    tcgApiId: 'ecard3-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/72.png","large":"https://images.pokemontcg.io/ecard3/72_hires.png"}',
    searchName: 'Ledyba (SK 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Ledyba',
    tcgApiId: 'ecard3-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/73.png","large":"https://images.pokemontcg.io/ecard3/73_hires.png"}',
    searchName: 'Ledyba (SK 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Machop',
    tcgApiId: 'ecard3-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/74.png","large":"https://images.pokemontcg.io/ecard3/74_hires.png"}',
    searchName: 'Machop (SK 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magikarp',
    tcgApiId: 'ecard3-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/75.png","large":"https://images.pokemontcg.io/ecard3/75_hires.png"}',
    searchName: 'Magikarp (SK 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magnemite',
    tcgApiId: 'ecard3-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/76.png","large":"https://images.pokemontcg.io/ecard3/76_hires.png"}',
    searchName: 'Magnemite (SK 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Mantine',
    tcgApiId: 'ecard3-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/77.png","large":"https://images.pokemontcg.io/ecard3/77_hires.png"}',
    searchName: 'Mantine (SK 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Meowth',
    tcgApiId: 'ecard3-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/78.png","large":"https://images.pokemontcg.io/ecard3/78_hires.png"}',
    searchName: 'Meowth (SK 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Murkrow',
    tcgApiId: 'ecard3-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/79.png","large":"https://images.pokemontcg.io/ecard3/79_hires.png"}',
    searchName: 'Murkrow (SK 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Natu',
    tcgApiId: 'ecard3-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/80.png","large":"https://images.pokemontcg.io/ecard3/80_hires.png"}',
    searchName: 'Natu (SK 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Nidoran ♀',
    tcgApiId: 'ecard3-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/81.png","large":"https://images.pokemontcg.io/ecard3/81_hires.png"}',
    searchName: 'Nidoran ♀ (SK 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Nidoran ♀',
    tcgApiId: 'ecard3-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/82.png","large":"https://images.pokemontcg.io/ecard3/82_hires.png"}',
    searchName: 'Nidoran ♀ (SK 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Nidorina',
    tcgApiId: 'ecard3-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/83.png","large":"https://images.pokemontcg.io/ecard3/83_hires.png"}',
    searchName: 'Nidorina (SK 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Pikachu',
    tcgApiId: 'ecard3-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/84.png","large":"https://images.pokemontcg.io/ecard3/84_hires.png"}',
    searchName: 'Pikachu (SK 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Pineco',
    tcgApiId: 'ecard3-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/85.png","large":"https://images.pokemontcg.io/ecard3/85_hires.png"}',
    searchName: 'Pineco (SK 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Pineco',
    tcgApiId: 'ecard3-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/86.png","large":"https://images.pokemontcg.io/ecard3/86_hires.png"}',
    searchName: 'Pineco (SK 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Poliwag',
    tcgApiId: 'ecard3-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/87.png","large":"https://images.pokemontcg.io/ecard3/87_hires.png"}',
    searchName: 'Poliwag (SK 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Poliwhirl',
    tcgApiId: 'ecard3-88',
    number: '88',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/88.png","large":"https://images.pokemontcg.io/ecard3/88_hires.png"}',
    searchName: 'Poliwhirl (SK 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Raticate',
    tcgApiId: 'ecard3-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/89.png","large":"https://images.pokemontcg.io/ecard3/89_hires.png"}',
    searchName: 'Raticate (SK 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Rattata',
    tcgApiId: 'ecard3-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/90.png","large":"https://images.pokemontcg.io/ecard3/90_hires.png"}',
    searchName: 'Rattata (SK 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Rhyhorn',
    tcgApiId: 'ecard3-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/91.png","large":"https://images.pokemontcg.io/ecard3/91_hires.png"}',
    searchName: 'Rhyhorn (SK 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Sandshrew',
    tcgApiId: 'ecard3-92',
    number: '92',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/92.png","large":"https://images.pokemontcg.io/ecard3/92_hires.png"}',
    searchName: 'Sandshrew (SK 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Sandslash',
    tcgApiId: 'ecard3-93',
    number: '93',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/93.png","large":"https://images.pokemontcg.io/ecard3/93_hires.png"}',
    searchName: 'Sandslash (SK 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Seel',
    tcgApiId: 'ecard3-94',
    number: '94',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/94.png","large":"https://images.pokemontcg.io/ecard3/94_hires.png"}',
    searchName: 'Seel (SK 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Seel',
    tcgApiId: 'ecard3-95',
    number: '95',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/95.png","large":"https://images.pokemontcg.io/ecard3/95_hires.png"}',
    searchName: 'Seel (SK 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Shuckle',
    tcgApiId: 'ecard3-96',
    number: '96',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/96.png","large":"https://images.pokemontcg.io/ecard3/96_hires.png"}',
    searchName: 'Shuckle (SK 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Skarmory',
    tcgApiId: 'ecard3-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/97.png","large":"https://images.pokemontcg.io/ecard3/97_hires.png"}',
    searchName: 'Skarmory (SK 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Slugma',
    tcgApiId: 'ecard3-98',
    number: '98',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/98.png","large":"https://images.pokemontcg.io/ecard3/98_hires.png"}',
    searchName: 'Slugma (SK 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Slugma',
    tcgApiId: 'ecard3-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/99.png","large":"https://images.pokemontcg.io/ecard3/99_hires.png"}',
    searchName: 'Slugma (SK 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Snorlax',
    tcgApiId: 'ecard3-100',
    number: '100',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/100.png","large":"https://images.pokemontcg.io/ecard3/100_hires.png"}',
    searchName: 'Snorlax (SK 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Snubbull',
    tcgApiId: 'ecard3-101',
    number: '101',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/101.png","large":"https://images.pokemontcg.io/ecard3/101_hires.png"}',
    searchName: 'Snubbull (SK 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Stantler',
    tcgApiId: 'ecard3-102',
    number: '102',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/102.png","large":"https://images.pokemontcg.io/ecard3/102_hires.png"}',
    searchName: 'Stantler (SK 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Staryu',
    tcgApiId: 'ecard3-103',
    number: '103',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/103.png","large":"https://images.pokemontcg.io/ecard3/103_hires.png"}',
    searchName: 'Staryu (SK 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Staryu',
    tcgApiId: 'ecard3-104',
    number: '104',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/104.png","large":"https://images.pokemontcg.io/ecard3/104_hires.png"}',
    searchName: 'Staryu (SK 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Sunflora',
    tcgApiId: 'ecard3-105',
    number: '105',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/105.png","large":"https://images.pokemontcg.io/ecard3/105_hires.png"}',
    searchName: 'Sunflora (SK 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Sunkern',
    tcgApiId: 'ecard3-106',
    number: '106',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/106.png","large":"https://images.pokemontcg.io/ecard3/106_hires.png"}',
    searchName: 'Sunkern (SK 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Swinub',
    tcgApiId: 'ecard3-107',
    number: '107',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/107.png","large":"https://images.pokemontcg.io/ecard3/107_hires.png"}',
    searchName: 'Swinub (SK 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Swinub',
    tcgApiId: 'ecard3-108',
    number: '108',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/108.png","large":"https://images.pokemontcg.io/ecard3/108_hires.png"}',
    searchName: 'Swinub (SK 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Teddiursa',
    tcgApiId: 'ecard3-109',
    number: '109',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/109.png","large":"https://images.pokemontcg.io/ecard3/109_hires.png"}',
    searchName: 'Teddiursa (SK 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Ursaring',
    tcgApiId: 'ecard3-110',
    number: '110',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/110.png","large":"https://images.pokemontcg.io/ecard3/110_hires.png"}',
    searchName: 'Ursaring (SK 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Venomoth',
    tcgApiId: 'ecard3-111',
    number: '111',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/111.png","large":"https://images.pokemontcg.io/ecard3/111_hires.png"}',
    searchName: 'Venomoth (SK 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Venonat',
    tcgApiId: 'ecard3-112',
    number: '112',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/112.png","large":"https://images.pokemontcg.io/ecard3/112_hires.png"}',
    searchName: 'Venonat (SK 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Voltorb',
    tcgApiId: 'ecard3-113',
    number: '113',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/113.png","large":"https://images.pokemontcg.io/ecard3/113_hires.png"}',
    searchName: 'Voltorb (SK 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Weedle',
    tcgApiId: 'ecard3-114',
    number: '114',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/114.png","large":"https://images.pokemontcg.io/ecard3/114_hires.png"}',
    searchName: 'Weedle (SK 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Weedle',
    tcgApiId: 'ecard3-115',
    number: '115',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/115.png","large":"https://images.pokemontcg.io/ecard3/115_hires.png"}',
    searchName: 'Weedle (SK 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Yanma',
    tcgApiId: 'ecard3-116',
    number: '116',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/116.png","large":"https://images.pokemontcg.io/ecard3/116_hires.png"}',
    searchName: 'Yanma (SK 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Zubat',
    tcgApiId: 'ecard3-117',
    number: '117',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/117.png","large":"https://images.pokemontcg.io/ecard3/117_hires.png"}',
    searchName: 'Zubat (SK 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Zubat',
    tcgApiId: 'ecard3-118',
    number: '118',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/118.png","large":"https://images.pokemontcg.io/ecard3/118_hires.png"}',
    searchName: 'Zubat (SK 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Ancient Ruins',
    tcgApiId: 'ecard3-119',
    number: '119',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/119.png","large":"https://images.pokemontcg.io/ecard3/119_hires.png"}',
    searchName: 'Ancient Ruins (SK 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Relic Hunter',
    tcgApiId: 'ecard3-120',
    number: '120',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/120.png","large":"https://images.pokemontcg.io/ecard3/120_hires.png"}',
    searchName: 'Relic Hunter (SK 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Apricorn Maker',
    tcgApiId: 'ecard3-121',
    number: '121',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/121.png","large":"https://images.pokemontcg.io/ecard3/121_hires.png"}',
    searchName: 'Apricorn Maker (SK 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Crystal Shard',
    tcgApiId: 'ecard3-122',
    number: '122',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/122.png","large":"https://images.pokemontcg.io/ecard3/122_hires.png"}',
    searchName: 'Crystal Shard (SK 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Desert Shaman',
    tcgApiId: 'ecard3-123',
    number: '123',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/123.png","large":"https://images.pokemontcg.io/ecard3/123_hires.png"}',
    searchName: 'Desert Shaman (SK 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Fast Ball',
    tcgApiId: 'ecard3-124',
    number: '124',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/124.png","large":"https://images.pokemontcg.io/ecard3/124_hires.png"}',
    searchName: 'Fast Ball (SK 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Fisherman',
    tcgApiId: 'ecard3-125',
    number: '125',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/125.png","large":"https://images.pokemontcg.io/ecard3/125_hires.png"}',
    searchName: 'Fisherman (SK 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Friend Ball',
    tcgApiId: 'ecard3-126',
    number: '126',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/126.png","large":"https://images.pokemontcg.io/ecard3/126_hires.png"}',
    searchName: 'Friend Ball (SK 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Hyper Potion',
    tcgApiId: 'ecard3-127',
    number: '127',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/127.png","large":"https://images.pokemontcg.io/ecard3/127_hires.png"}',
    searchName: 'Hyper Potion (SK 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Lure Ball',
    tcgApiId: 'ecard3-128',
    number: '128',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/128.png","large":"https://images.pokemontcg.io/ecard3/128_hires.png"}',
    searchName: 'Lure Ball (SK 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Miracle Sphere α',
    tcgApiId: 'ecard3-129',
    number: '129',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/129.png","large":"https://images.pokemontcg.io/ecard3/129_hires.png"}',
    searchName: 'Miracle Sphere α (SK 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Miracle Sphere β',
    tcgApiId: 'ecard3-130',
    number: '130',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/130.png","large":"https://images.pokemontcg.io/ecard3/130_hires.png"}',
    searchName: 'Miracle Sphere β (SK 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Miracle Sphere γ',
    tcgApiId: 'ecard3-131',
    number: '131',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/131.png","large":"https://images.pokemontcg.io/ecard3/131_hires.png"}',
    searchName: 'Miracle Sphere γ (SK 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Mirage Stadium',
    tcgApiId: 'ecard3-132',
    number: '132',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/132.png","large":"https://images.pokemontcg.io/ecard3/132_hires.png"}',
    searchName: 'Mirage Stadium (SK 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Mystery Plate α',
    tcgApiId: 'ecard3-133',
    number: '133',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/133.png","large":"https://images.pokemontcg.io/ecard3/133_hires.png"}',
    searchName: 'Mystery Plate α (SK 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Mystery Plate β',
    tcgApiId: 'ecard3-134',
    number: '134',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/134.png","large":"https://images.pokemontcg.io/ecard3/134_hires.png"}',
    searchName: 'Mystery Plate β (SK 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Mystery Plate γ',
    tcgApiId: 'ecard3-135',
    number: '135',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/135.png","large":"https://images.pokemontcg.io/ecard3/135_hires.png"}',
    searchName: 'Mystery Plate γ (SK 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Mystery Plate δ',
    tcgApiId: 'ecard3-136',
    number: '136',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/136.png","large":"https://images.pokemontcg.io/ecard3/136_hires.png"}',
    searchName: 'Mystery Plate δ (SK 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Mystery Zone',
    tcgApiId: 'ecard3-137',
    number: '137',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/137.png","large":"https://images.pokemontcg.io/ecard3/137_hires.png"}',
    searchName: 'Mystery Zone (SK 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Oracle',
    tcgApiId: 'ecard3-138',
    number: '138',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/138.png","large":"https://images.pokemontcg.io/ecard3/138_hires.png"}',
    searchName: 'Oracle (SK 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Star Piece',
    tcgApiId: 'ecard3-139',
    number: '139',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/139.png","large":"https://images.pokemontcg.io/ecard3/139_hires.png"}',
    searchName: 'Star Piece (SK 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Underground Expedition',
    tcgApiId: 'ecard3-140',
    number: '140',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/140.png","large":"https://images.pokemontcg.io/ecard3/140_hires.png"}',
    searchName: 'Underground Expedition (SK 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Underground Lake',
    tcgApiId: 'ecard3-141',
    number: '141',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/141.png","large":"https://images.pokemontcg.io/ecard3/141_hires.png"}',
    searchName: 'Underground Lake (SK 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Bounce Energy',
    tcgApiId: 'ecard3-142',
    number: '142',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/142.png","large":"https://images.pokemontcg.io/ecard3/142_hires.png"}',
    searchName: 'Bounce Energy (SK 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Cyclone Energy',
    tcgApiId: 'ecard3-143',
    number: '143',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/143.png","large":"https://images.pokemontcg.io/ecard3/143_hires.png"}',
    searchName: 'Cyclone Energy (SK 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Retro Energy',
    tcgApiId: 'ecard3-144',
    number: '144',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/144.png","large":"https://images.pokemontcg.io/ecard3/144_hires.png"}',
    searchName: 'Retro Energy (SK 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Celebi',
    tcgApiId: 'ecard3-145',
    number: '145',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/145.png","large":"https://images.pokemontcg.io/ecard3/145_hires.png"}',
    searchName: 'Celebi (SK 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Charizard',
    tcgApiId: 'ecard3-146',
    number: '146',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/146.png","large":"https://images.pokemontcg.io/ecard3/146_hires.png"}',
    searchName: 'Charizard (SK 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Crobat',
    tcgApiId: 'ecard3-147',
    number: '147',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/147.png","large":"https://images.pokemontcg.io/ecard3/147_hires.png"}',
    searchName: 'Crobat (SK 147)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Golem',
    tcgApiId: 'ecard3-148',
    number: '148',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/148.png","large":"https://images.pokemontcg.io/ecard3/148_hires.png"}',
    searchName: 'Golem (SK 148)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Ho-oh',
    tcgApiId: 'ecard3-149',
    number: '149',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/149.png","large":"https://images.pokemontcg.io/ecard3/149_hires.png"}',
    searchName: 'Ho-oh (SK 149)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Kabutops',
    tcgApiId: 'ecard3-150',
    number: '150',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/150.png","large":"https://images.pokemontcg.io/ecard3/150_hires.png"}',
    searchName: 'Kabutops (SK 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Alakazam',
    tcgApiId: 'ecard3-H1',
    number: 'H1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H1.png","large":"https://images.pokemontcg.io/ecard3/H1_hires.png"}',
    searchName: 'Alakazam (SK H1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Arcanine',
    tcgApiId: 'ecard3-H2',
    number: 'H2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H2.png","large":"https://images.pokemontcg.io/ecard3/H2_hires.png"}',
    searchName: 'Arcanine (SK H2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Articuno',
    tcgApiId: 'ecard3-H3',
    number: 'H3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H3.png","large":"https://images.pokemontcg.io/ecard3/H3_hires.png"}',
    searchName: 'Articuno (SK H3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Beedrill',
    tcgApiId: 'ecard3-H4',
    number: 'H4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H4.png","large":"https://images.pokemontcg.io/ecard3/H4_hires.png"}',
    searchName: 'Beedrill (SK H4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Crobat',
    tcgApiId: 'ecard3-H5',
    number: 'H5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H5.png","large":"https://images.pokemontcg.io/ecard3/H5_hires.png"}',
    searchName: 'Crobat (SK H5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Dewgong',
    tcgApiId: 'ecard3-H6',
    number: 'H6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H6.png","large":"https://images.pokemontcg.io/ecard3/H6_hires.png"}',
    searchName: 'Dewgong (SK H6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Flareon',
    tcgApiId: 'ecard3-H7',
    number: 'H7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H7.png","large":"https://images.pokemontcg.io/ecard3/H7_hires.png"}',
    searchName: 'Flareon (SK H7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Forretress',
    tcgApiId: 'ecard3-H8',
    number: 'H8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H8.png","large":"https://images.pokemontcg.io/ecard3/H8_hires.png"}',
    searchName: 'Forretress (SK H8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Gengar',
    tcgApiId: 'ecard3-H9',
    number: 'H9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H9.png","large":"https://images.pokemontcg.io/ecard3/H9_hires.png"}',
    searchName: 'Gengar (SK H9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Gyarados',
    tcgApiId: 'ecard3-H10',
    number: 'H10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H10.png","large":"https://images.pokemontcg.io/ecard3/H10_hires.png"}',
    searchName: 'Gyarados (SK H10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Houndoom',
    tcgApiId: 'ecard3-H11',
    number: 'H11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H11.png","large":"https://images.pokemontcg.io/ecard3/H11_hires.png"}',
    searchName: 'Houndoom (SK H11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Jolteon',
    tcgApiId: 'ecard3-H12',
    number: 'H12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H12.png","large":"https://images.pokemontcg.io/ecard3/H12_hires.png"}',
    searchName: 'Jolteon (SK H12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Kabutops',
    tcgApiId: 'ecard3-H13',
    number: 'H13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H13.png","large":"https://images.pokemontcg.io/ecard3/H13_hires.png"}',
    searchName: 'Kabutops (SK H13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Ledian',
    tcgApiId: 'ecard3-H14',
    number: 'H14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H14.png","large":"https://images.pokemontcg.io/ecard3/H14_hires.png"}',
    searchName: 'Ledian (SK H14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Machamp',
    tcgApiId: 'ecard3-H15',
    number: 'H15',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H15.png","large":"https://images.pokemontcg.io/ecard3/H15_hires.png"}',
    searchName: 'Machamp (SK H15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magcargo',
    tcgApiId: 'ecard3-H16',
    number: 'H16',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H16.png","large":"https://images.pokemontcg.io/ecard3/H16_hires.png"}',
    searchName: 'Magcargo (SK H16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magcargo',
    tcgApiId: 'ecard3-H17',
    number: 'H17',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H17.png","large":"https://images.pokemontcg.io/ecard3/H17_hires.png"}',
    searchName: 'Magcargo (SK H17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magneton',
    tcgApiId: 'ecard3-H18',
    number: 'H18',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H18.png","large":"https://images.pokemontcg.io/ecard3/H18_hires.png"}',
    searchName: 'Magneton (SK H18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Magneton',
    tcgApiId: 'ecard3-H19',
    number: 'H19',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H19.png","large":"https://images.pokemontcg.io/ecard3/H19_hires.png"}',
    searchName: 'Magneton (SK H19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Moltres',
    tcgApiId: 'ecard3-H20',
    number: 'H20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H20.png","large":"https://images.pokemontcg.io/ecard3/H20_hires.png"}',
    searchName: 'Moltres (SK H20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Nidoqueen',
    tcgApiId: 'ecard3-H21',
    number: 'H21',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H21.png","large":"https://images.pokemontcg.io/ecard3/H21_hires.png"}',
    searchName: 'Nidoqueen (SK H21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Piloswine',
    tcgApiId: 'ecard3-H22',
    number: 'H22',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H22.png","large":"https://images.pokemontcg.io/ecard3/H22_hires.png"}',
    searchName: 'Piloswine (SK H22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Politoed',
    tcgApiId: 'ecard3-H23',
    number: 'H23',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H23.png","large":"https://images.pokemontcg.io/ecard3/H23_hires.png"}',
    searchName: 'Politoed (SK H23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Poliwrath',
    tcgApiId: 'ecard3-H24',
    number: 'H24',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H24.png","large":"https://images.pokemontcg.io/ecard3/H24_hires.png"}',
    searchName: 'Poliwrath (SK H24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Raichu',
    tcgApiId: 'ecard3-H25',
    number: 'H25',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H25.png","large":"https://images.pokemontcg.io/ecard3/H25_hires.png"}',
    searchName: 'Raichu (SK H25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Raikou',
    tcgApiId: 'ecard3-H26',
    number: 'H26',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H26.png","large":"https://images.pokemontcg.io/ecard3/H26_hires.png"}',
    searchName: 'Raikou (SK H26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Rhydon',
    tcgApiId: 'ecard3-H27',
    number: 'H27',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H27.png","large":"https://images.pokemontcg.io/ecard3/H27_hires.png"}',
    searchName: 'Rhydon (SK H27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Starmie',
    tcgApiId: 'ecard3-H28',
    number: 'H28',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H28.png","large":"https://images.pokemontcg.io/ecard3/H28_hires.png"}',
    searchName: 'Starmie (SK H28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Steelix',
    tcgApiId: 'ecard3-H29',
    number: 'H29',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H29.png","large":"https://images.pokemontcg.io/ecard3/H29_hires.png"}',
    searchName: 'Steelix (SK H29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Umbreon',
    tcgApiId: 'ecard3-H30',
    number: 'H30',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H30.png","large":"https://images.pokemontcg.io/ecard3/H30_hires.png"}',
    searchName: 'Umbreon (SK H30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Vaporeon',
    tcgApiId: 'ecard3-H31',
    number: 'H31',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H31.png","large":"https://images.pokemontcg.io/ecard3/H31_hires.png"}',
    searchName: 'Vaporeon (SK H31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ecard3',
    name: 'Xatu',
    tcgApiId: 'ecard3-H32',
    number: 'H32',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ecard3/H32.png","large":"https://images.pokemontcg.io/ecard3/H32_hires.png"}',
    searchName: 'Xatu (SK H32)',
  },
];
