export const cardSeedEx11 = [
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Beedrill δ',
    tcgApiId: 'ex11-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/1.png","large":"https://images.pokemontcg.io/ex11/1_hires.png"}',
    searchName: 'Beedrill δ (DS 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Crobat δ',
    tcgApiId: 'ex11-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/2.png","large":"https://images.pokemontcg.io/ex11/2_hires.png"}',
    searchName: 'Crobat δ (DS 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Dragonite δ',
    tcgApiId: 'ex11-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/3.png","large":"https://images.pokemontcg.io/ex11/3_hires.png"}',
    searchName: 'Dragonite δ (DS 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Espeon δ',
    tcgApiId: 'ex11-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/4.png","large":"https://images.pokemontcg.io/ex11/4_hires.png"}',
    searchName: 'Espeon δ (DS 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Flareon δ',
    tcgApiId: 'ex11-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/5.png","large":"https://images.pokemontcg.io/ex11/5_hires.png"}',
    searchName: 'Flareon δ (DS 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Gardevoir δ',
    tcgApiId: 'ex11-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/6.png","large":"https://images.pokemontcg.io/ex11/6_hires.png"}',
    searchName: 'Gardevoir δ (DS 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Jolteon δ',
    tcgApiId: 'ex11-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/7.png","large":"https://images.pokemontcg.io/ex11/7_hires.png"}',
    searchName: 'Jolteon δ (DS 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Latias δ',
    tcgApiId: 'ex11-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/8.png","large":"https://images.pokemontcg.io/ex11/8_hires.png"}',
    searchName: 'Latias δ (DS 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Latios δ',
    tcgApiId: 'ex11-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/9.png","large":"https://images.pokemontcg.io/ex11/9_hires.png"}',
    searchName: 'Latios δ (DS 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Marowak δ',
    tcgApiId: 'ex11-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/10.png","large":"https://images.pokemontcg.io/ex11/10_hires.png"}',
    searchName: 'Marowak δ (DS 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Metagross δ',
    tcgApiId: 'ex11-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/11.png","large":"https://images.pokemontcg.io/ex11/11_hires.png"}',
    searchName: 'Metagross δ (DS 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Mewtwo δ',
    tcgApiId: 'ex11-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/12.png","large":"https://images.pokemontcg.io/ex11/12_hires.png"}',
    searchName: 'Mewtwo δ (DS 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Rayquaza δ',
    tcgApiId: 'ex11-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/13.png","large":"https://images.pokemontcg.io/ex11/13_hires.png"}',
    searchName: 'Rayquaza δ (DS 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Salamence δ',
    tcgApiId: 'ex11-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/14.png","large":"https://images.pokemontcg.io/ex11/14_hires.png"}',
    searchName: 'Salamence δ (DS 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Starmie δ',
    tcgApiId: 'ex11-15',
    number: '15',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/15.png","large":"https://images.pokemontcg.io/ex11/15_hires.png"}',
    searchName: 'Starmie δ (DS 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Tyranitar δ',
    tcgApiId: 'ex11-16',
    number: '16',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/16.png","large":"https://images.pokemontcg.io/ex11/16_hires.png"}',
    searchName: 'Tyranitar δ (DS 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Umbreon δ',
    tcgApiId: 'ex11-17',
    number: '17',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/17.png","large":"https://images.pokemontcg.io/ex11/17_hires.png"}',
    searchName: 'Umbreon δ (DS 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Vaporeon δ',
    tcgApiId: 'ex11-18',
    number: '18',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/18.png","large":"https://images.pokemontcg.io/ex11/18_hires.png"}',
    searchName: 'Vaporeon δ (DS 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Azumarill δ',
    tcgApiId: 'ex11-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/19.png","large":"https://images.pokemontcg.io/ex11/19_hires.png"}',
    searchName: 'Azumarill δ (DS 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Azurill',
    tcgApiId: 'ex11-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/20.png","large":"https://images.pokemontcg.io/ex11/20_hires.png"}',
    searchName: 'Azurill (DS 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: "Holon's Electrode",
    tcgApiId: 'ex11-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/21.png","large":"https://images.pokemontcg.io/ex11/21_hires.png"}',
    searchName: "Holon's Electrode (DS 21)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: "Holon's Magneton",
    tcgApiId: 'ex11-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/22.png","large":"https://images.pokemontcg.io/ex11/22_hires.png"}',
    searchName: "Holon's Magneton (DS 22)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Hypno',
    tcgApiId: 'ex11-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/23.png","large":"https://images.pokemontcg.io/ex11/23_hires.png"}',
    searchName: 'Hypno (DS 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Mightyena δ',
    tcgApiId: 'ex11-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/24.png","large":"https://images.pokemontcg.io/ex11/24_hires.png"}',
    searchName: 'Mightyena δ (DS 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Porygon2',
    tcgApiId: 'ex11-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/25.png","large":"https://images.pokemontcg.io/ex11/25_hires.png"}',
    searchName: 'Porygon2 (DS 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Rain Castform',
    tcgApiId: 'ex11-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/26.png","large":"https://images.pokemontcg.io/ex11/26_hires.png"}',
    searchName: 'Rain Castform (DS 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Sandslash δ',
    tcgApiId: 'ex11-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/27.png","large":"https://images.pokemontcg.io/ex11/27_hires.png"}',
    searchName: 'Sandslash δ (DS 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Slowking',
    tcgApiId: 'ex11-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/28.png","large":"https://images.pokemontcg.io/ex11/28_hires.png"}',
    searchName: 'Slowking (DS 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Snow-cloud Castform',
    tcgApiId: 'ex11-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/29.png","large":"https://images.pokemontcg.io/ex11/29_hires.png"}',
    searchName: 'Snow-cloud Castform (DS 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Starmie δ',
    tcgApiId: 'ex11-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/30.png","large":"https://images.pokemontcg.io/ex11/30_hires.png"}',
    searchName: 'Starmie δ (DS 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Sunny Castform',
    tcgApiId: 'ex11-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/31.png","large":"https://images.pokemontcg.io/ex11/31_hires.png"}',
    searchName: 'Sunny Castform (DS 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Swellow',
    tcgApiId: 'ex11-32',
    number: '32',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/32.png","large":"https://images.pokemontcg.io/ex11/32_hires.png"}',
    searchName: 'Swellow (DS 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Weezing',
    tcgApiId: 'ex11-33',
    number: '33',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/33.png","large":"https://images.pokemontcg.io/ex11/33_hires.png"}',
    searchName: 'Weezing (DS 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Castform',
    tcgApiId: 'ex11-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/34.png","large":"https://images.pokemontcg.io/ex11/34_hires.png"}',
    searchName: 'Castform (DS 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/35.png","large":"https://images.pokemontcg.io/ex11/35_hires.png"}',
    searchName: 'Ditto (DS 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/36.png","large":"https://images.pokemontcg.io/ex11/36_hires.png"}',
    searchName: 'Ditto (DS 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/37.png","large":"https://images.pokemontcg.io/ex11/37_hires.png"}',
    searchName: 'Ditto (DS 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/38.png","large":"https://images.pokemontcg.io/ex11/38_hires.png"}',
    searchName: 'Ditto (DS 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/39.png","large":"https://images.pokemontcg.io/ex11/39_hires.png"}',
    searchName: 'Ditto (DS 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/40.png","large":"https://images.pokemontcg.io/ex11/40_hires.png"}',
    searchName: 'Ditto (DS 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Dragonair δ',
    tcgApiId: 'ex11-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/41.png","large":"https://images.pokemontcg.io/ex11/41_hires.png"}',
    searchName: 'Dragonair δ (DS 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Dragonair δ',
    tcgApiId: 'ex11-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/42.png","large":"https://images.pokemontcg.io/ex11/42_hires.png"}',
    searchName: 'Dragonair δ (DS 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Golbat',
    tcgApiId: 'ex11-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/43.png","large":"https://images.pokemontcg.io/ex11/43_hires.png"}',
    searchName: 'Golbat (DS 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Hariyama',
    tcgApiId: 'ex11-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/44.png","large":"https://images.pokemontcg.io/ex11/44_hires.png"}',
    searchName: 'Hariyama (DS 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Illumise',
    tcgApiId: 'ex11-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/45.png","large":"https://images.pokemontcg.io/ex11/45_hires.png"}',
    searchName: 'Illumise (DS 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Kakuna',
    tcgApiId: 'ex11-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/46.png","large":"https://images.pokemontcg.io/ex11/46_hires.png"}',
    searchName: 'Kakuna (DS 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Kirlia',
    tcgApiId: 'ex11-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/47.png","large":"https://images.pokemontcg.io/ex11/47_hires.png"}',
    searchName: 'Kirlia (DS 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Magneton',
    tcgApiId: 'ex11-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/48.png","large":"https://images.pokemontcg.io/ex11/48_hires.png"}',
    searchName: 'Magneton (DS 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Metang δ',
    tcgApiId: 'ex11-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/49.png","large":"https://images.pokemontcg.io/ex11/49_hires.png"}',
    searchName: 'Metang δ (DS 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Persian',
    tcgApiId: 'ex11-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/50.png","large":"https://images.pokemontcg.io/ex11/50_hires.png"}',
    searchName: 'Persian (DS 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Pupitar δ',
    tcgApiId: 'ex11-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/51.png","large":"https://images.pokemontcg.io/ex11/51_hires.png"}',
    searchName: 'Pupitar δ (DS 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Rapidash',
    tcgApiId: 'ex11-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/52.png","large":"https://images.pokemontcg.io/ex11/52_hires.png"}',
    searchName: 'Rapidash (DS 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Shelgon δ',
    tcgApiId: 'ex11-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/53.png","large":"https://images.pokemontcg.io/ex11/53_hires.png"}',
    searchName: 'Shelgon δ (DS 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Shelgon δ',
    tcgApiId: 'ex11-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/54.png","large":"https://images.pokemontcg.io/ex11/54_hires.png"}',
    searchName: 'Shelgon δ (DS 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Skarmory',
    tcgApiId: 'ex11-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/55.png","large":"https://images.pokemontcg.io/ex11/55_hires.png"}',
    searchName: 'Skarmory (DS 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Volbeat',
    tcgApiId: 'ex11-56',
    number: '56',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/56.png","large":"https://images.pokemontcg.io/ex11/56_hires.png"}',
    searchName: 'Volbeat (DS 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Bagon δ',
    tcgApiId: 'ex11-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/57.png","large":"https://images.pokemontcg.io/ex11/57_hires.png"}',
    searchName: 'Bagon δ (DS 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Bagon δ',
    tcgApiId: 'ex11-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/58.png","large":"https://images.pokemontcg.io/ex11/58_hires.png"}',
    searchName: 'Bagon δ (DS 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Beldum δ',
    tcgApiId: 'ex11-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/59.png","large":"https://images.pokemontcg.io/ex11/59_hires.png"}',
    searchName: 'Beldum δ (DS 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Cubone',
    tcgApiId: 'ex11-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/60.png","large":"https://images.pokemontcg.io/ex11/60_hires.png"}',
    searchName: 'Cubone (DS 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/61.png","large":"https://images.pokemontcg.io/ex11/61_hires.png"}',
    searchName: 'Ditto (DS 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/62.png","large":"https://images.pokemontcg.io/ex11/62_hires.png"}',
    searchName: 'Ditto (DS 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/63.png","large":"https://images.pokemontcg.io/ex11/63_hires.png"}',
    searchName: 'Ditto (DS 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ditto',
    tcgApiId: 'ex11-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/64.png","large":"https://images.pokemontcg.io/ex11/64_hires.png"}',
    searchName: 'Ditto (DS 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Dratini δ',
    tcgApiId: 'ex11-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/65.png","large":"https://images.pokemontcg.io/ex11/65_hires.png"}',
    searchName: 'Dratini δ (DS 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Dratini δ',
    tcgApiId: 'ex11-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/66.png","large":"https://images.pokemontcg.io/ex11/66_hires.png"}',
    searchName: 'Dratini δ (DS 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Drowzee',
    tcgApiId: 'ex11-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/67.png","large":"https://images.pokemontcg.io/ex11/67_hires.png"}',
    searchName: 'Drowzee (DS 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Eevee δ',
    tcgApiId: 'ex11-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/68.png","large":"https://images.pokemontcg.io/ex11/68_hires.png"}',
    searchName: 'Eevee δ (DS 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Eevee',
    tcgApiId: 'ex11-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/69.png","large":"https://images.pokemontcg.io/ex11/69_hires.png"}',
    searchName: 'Eevee (DS 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: "Holon's Magnemite",
    tcgApiId: 'ex11-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/70.png","large":"https://images.pokemontcg.io/ex11/70_hires.png"}',
    searchName: "Holon's Magnemite (DS 70)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: "Holon's Voltorb",
    tcgApiId: 'ex11-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/71.png","large":"https://images.pokemontcg.io/ex11/71_hires.png"}',
    searchName: "Holon's Voltorb (DS 71)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Koffing',
    tcgApiId: 'ex11-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/72.png","large":"https://images.pokemontcg.io/ex11/72_hires.png"}',
    searchName: 'Koffing (DS 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Larvitar δ',
    tcgApiId: 'ex11-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/73.png","large":"https://images.pokemontcg.io/ex11/73_hires.png"}',
    searchName: 'Larvitar δ (DS 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Magnemite',
    tcgApiId: 'ex11-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/74.png","large":"https://images.pokemontcg.io/ex11/74_hires.png"}',
    searchName: 'Magnemite (DS 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Makuhita',
    tcgApiId: 'ex11-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/75.png","large":"https://images.pokemontcg.io/ex11/75_hires.png"}',
    searchName: 'Makuhita (DS 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Marill',
    tcgApiId: 'ex11-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/76.png","large":"https://images.pokemontcg.io/ex11/76_hires.png"}',
    searchName: 'Marill (DS 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Meowth',
    tcgApiId: 'ex11-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/77.png","large":"https://images.pokemontcg.io/ex11/77_hires.png"}',
    searchName: 'Meowth (DS 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ponyta',
    tcgApiId: 'ex11-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/78.png","large":"https://images.pokemontcg.io/ex11/78_hires.png"}',
    searchName: 'Ponyta (DS 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Poochyena',
    tcgApiId: 'ex11-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/79.png","large":"https://images.pokemontcg.io/ex11/79_hires.png"}',
    searchName: 'Poochyena (DS 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Porygon',
    tcgApiId: 'ex11-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/80.png","large":"https://images.pokemontcg.io/ex11/80_hires.png"}',
    searchName: 'Porygon (DS 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Ralts',
    tcgApiId: 'ex11-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/81.png","large":"https://images.pokemontcg.io/ex11/81_hires.png"}',
    searchName: 'Ralts (DS 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Sandshrew',
    tcgApiId: 'ex11-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/82.png","large":"https://images.pokemontcg.io/ex11/82_hires.png"}',
    searchName: 'Sandshrew (DS 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Slowpoke',
    tcgApiId: 'ex11-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/83.png","large":"https://images.pokemontcg.io/ex11/83_hires.png"}',
    searchName: 'Slowpoke (DS 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Staryu',
    tcgApiId: 'ex11-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/84.png","large":"https://images.pokemontcg.io/ex11/84_hires.png"}',
    searchName: 'Staryu (DS 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Staryu',
    tcgApiId: 'ex11-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/85.png","large":"https://images.pokemontcg.io/ex11/85_hires.png"}',
    searchName: 'Staryu (DS 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Taillow',
    tcgApiId: 'ex11-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/86.png","large":"https://images.pokemontcg.io/ex11/86_hires.png"}',
    searchName: 'Taillow (DS 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Weedle',
    tcgApiId: 'ex11-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/87.png","large":"https://images.pokemontcg.io/ex11/87_hires.png"}',
    searchName: 'Weedle (DS 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Zubat',
    tcgApiId: 'ex11-88',
    number: '88',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/88.png","large":"https://images.pokemontcg.io/ex11/88_hires.png"}',
    searchName: 'Zubat (DS 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Dual Ball',
    tcgApiId: 'ex11-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/89.png","large":"https://images.pokemontcg.io/ex11/89_hires.png"}',
    searchName: 'Dual Ball (DS 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Great Ball',
    tcgApiId: 'ex11-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/90.png","large":"https://images.pokemontcg.io/ex11/90_hires.png"}',
    searchName: 'Great Ball (DS 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Farmer',
    tcgApiId: 'ex11-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/91.png","large":"https://images.pokemontcg.io/ex11/91_hires.png"}',
    searchName: 'Holon Farmer (DS 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Lass',
    tcgApiId: 'ex11-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/92.png","large":"https://images.pokemontcg.io/ex11/92_hires.png"}',
    searchName: 'Holon Lass (DS 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Mentor',
    tcgApiId: 'ex11-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/93.png","large":"https://images.pokemontcg.io/ex11/93_hires.png"}',
    searchName: 'Holon Mentor (DS 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Research Tower',
    tcgApiId: 'ex11-94',
    number: '94',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/94.png","large":"https://images.pokemontcg.io/ex11/94_hires.png"}',
    searchName: 'Holon Research Tower (DS 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Researcher',
    tcgApiId: 'ex11-95',
    number: '95',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/95.png","large":"https://images.pokemontcg.io/ex11/95_hires.png"}',
    searchName: 'Holon Researcher (DS 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Ruins',
    tcgApiId: 'ex11-96',
    number: '96',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/96.png","large":"https://images.pokemontcg.io/ex11/96_hires.png"}',
    searchName: 'Holon Ruins (DS 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Scientist',
    tcgApiId: 'ex11-97',
    number: '97',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/97.png","large":"https://images.pokemontcg.io/ex11/97_hires.png"}',
    searchName: 'Holon Scientist (DS 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Transceiver',
    tcgApiId: 'ex11-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/98.png","large":"https://images.pokemontcg.io/ex11/98_hires.png"}',
    searchName: 'Holon Transceiver (DS 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Master Ball',
    tcgApiId: 'ex11-99',
    number: '99',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/99.png","large":"https://images.pokemontcg.io/ex11/99_hires.png"}',
    searchName: 'Master Ball (DS 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Super Scoop Up',
    tcgApiId: 'ex11-100',
    number: '100',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/100.png","large":"https://images.pokemontcg.io/ex11/100_hires.png"}',
    searchName: 'Super Scoop Up (DS 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Potion',
    tcgApiId: 'ex11-101',
    number: '101',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/101.png","large":"https://images.pokemontcg.io/ex11/101_hires.png"}',
    searchName: 'Potion (DS 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Switch',
    tcgApiId: 'ex11-102',
    number: '102',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/102.png","large":"https://images.pokemontcg.io/ex11/102_hires.png"}',
    searchName: 'Switch (DS 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Darkness Energy',
    tcgApiId: 'ex11-103',
    number: '103',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/103.png","large":"https://images.pokemontcg.io/ex11/103_hires.png"}',
    searchName: 'Darkness Energy (DS 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Energy FF',
    tcgApiId: 'ex11-104',
    number: '104',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/104.png","large":"https://images.pokemontcg.io/ex11/104_hires.png"}',
    searchName: 'Holon Energy FF (DS 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Energy GL',
    tcgApiId: 'ex11-105',
    number: '105',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/105.png","large":"https://images.pokemontcg.io/ex11/105_hires.png"}',
    searchName: 'Holon Energy GL (DS 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Holon Energy WP',
    tcgApiId: 'ex11-106',
    number: '106',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/106.png","large":"https://images.pokemontcg.io/ex11/106_hires.png"}',
    searchName: 'Holon Energy WP (DS 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Metal Energy',
    tcgApiId: 'ex11-107',
    number: '107',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/107.png","large":"https://images.pokemontcg.io/ex11/107_hires.png"}',
    searchName: 'Metal Energy (DS 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Flareon ex',
    tcgApiId: 'ex11-108',
    number: '108',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/108.png","large":"https://images.pokemontcg.io/ex11/108_hires.png"}',
    searchName: 'Flareon ex (DS 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Jolteon ex',
    tcgApiId: 'ex11-109',
    number: '109',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/109.png","large":"https://images.pokemontcg.io/ex11/109_hires.png"}',
    searchName: 'Jolteon ex (DS 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Vaporeon ex',
    tcgApiId: 'ex11-110',
    number: '110',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/110.png","large":"https://images.pokemontcg.io/ex11/110_hires.png"}',
    searchName: 'Vaporeon ex (DS 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Groudon ★',
    tcgApiId: 'ex11-111',
    number: '111',
    rarity: 'Rare Holo Star',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/111.png","large":"https://images.pokemontcg.io/ex11/111_hires.png"}',
    searchName: 'Groudon ★ (DS 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Kyogre ★',
    tcgApiId: 'ex11-112',
    number: '112',
    rarity: 'Rare Holo Star',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/112.png","large":"https://images.pokemontcg.io/ex11/112_hires.png"}',
    searchName: 'Kyogre ★ (DS 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Metagross ★',
    tcgApiId: 'ex11-113',
    number: '113',
    rarity: 'Rare Holo Star',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/113.png","large":"https://images.pokemontcg.io/ex11/113_hires.png"}',
    searchName: 'Metagross ★ (DS 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex11',
    name: 'Azumarill',
    tcgApiId: 'ex11-114',
    number: '114',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ex11/114.png","large":"https://images.pokemontcg.io/ex11/114_hires.png"}',
    searchName: 'Azumarill (DS 114)',
  },
];
