export const cardSeedEx16 = [
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Aggron',
    tcgApiId: 'ex16-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/1.png","large":"https://images.pokemontcg.io/ex16/1_hires.png"}',
    searchName: 'Aggron (PK 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Altaria',
    tcgApiId: 'ex16-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/2.png","large":"https://images.pokemontcg.io/ex16/2_hires.png"}',
    searchName: 'Altaria (PK 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Armaldo',
    tcgApiId: 'ex16-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/3.png","large":"https://images.pokemontcg.io/ex16/3_hires.png"}',
    searchName: 'Armaldo (PK 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Banette',
    tcgApiId: 'ex16-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/4.png","large":"https://images.pokemontcg.io/ex16/4_hires.png"}',
    searchName: 'Banette (PK 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Blaziken',
    tcgApiId: 'ex16-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/5.png","large":"https://images.pokemontcg.io/ex16/5_hires.png"}',
    searchName: 'Blaziken (PK 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Charizard',
    tcgApiId: 'ex16-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/6.png","large":"https://images.pokemontcg.io/ex16/6_hires.png"}',
    searchName: 'Charizard (PK 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Cradily',
    tcgApiId: 'ex16-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/7.png","large":"https://images.pokemontcg.io/ex16/7_hires.png"}',
    searchName: 'Cradily (PK 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Delcatty',
    tcgApiId: 'ex16-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/8.png","large":"https://images.pokemontcg.io/ex16/8_hires.png"}',
    searchName: 'Delcatty (PK 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Gardevoir',
    tcgApiId: 'ex16-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/9.png","large":"https://images.pokemontcg.io/ex16/9_hires.png"}',
    searchName: 'Gardevoir (PK 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Kabutops',
    tcgApiId: 'ex16-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/10.png","large":"https://images.pokemontcg.io/ex16/10_hires.png"}',
    searchName: 'Kabutops (PK 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Machamp',
    tcgApiId: 'ex16-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/11.png","large":"https://images.pokemontcg.io/ex16/11_hires.png"}',
    searchName: 'Machamp (PK 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Raichu',
    tcgApiId: 'ex16-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/12.png","large":"https://images.pokemontcg.io/ex16/12_hires.png"}',
    searchName: 'Raichu (PK 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Slaking',
    tcgApiId: 'ex16-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/13.png","large":"https://images.pokemontcg.io/ex16/13_hires.png"}',
    searchName: 'Slaking (PK 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Dusclops',
    tcgApiId: 'ex16-14',
    number: '14',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/14.png","large":"https://images.pokemontcg.io/ex16/14_hires.png"}',
    searchName: 'Dusclops (PK 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Lanturn',
    tcgApiId: 'ex16-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/15.png","large":"https://images.pokemontcg.io/ex16/15_hires.png"}',
    searchName: 'Lanturn (PK 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Magneton',
    tcgApiId: 'ex16-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/16.png","large":"https://images.pokemontcg.io/ex16/16_hires.png"}',
    searchName: 'Magneton (PK 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Mawile',
    tcgApiId: 'ex16-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/17.png","large":"https://images.pokemontcg.io/ex16/17_hires.png"}',
    searchName: 'Mawile (PK 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Mightyena',
    tcgApiId: 'ex16-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/18.png","large":"https://images.pokemontcg.io/ex16/18_hires.png"}',
    searchName: 'Mightyena (PK 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Ninetales',
    tcgApiId: 'ex16-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/19.png","large":"https://images.pokemontcg.io/ex16/19_hires.png"}',
    searchName: 'Ninetales (PK 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Omastar',
    tcgApiId: 'ex16-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/20.png","large":"https://images.pokemontcg.io/ex16/20_hires.png"}',
    searchName: 'Omastar (PK 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Pichu',
    tcgApiId: 'ex16-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/21.png","large":"https://images.pokemontcg.io/ex16/21_hires.png"}',
    searchName: 'Pichu (PK 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Sableye',
    tcgApiId: 'ex16-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/22.png","large":"https://images.pokemontcg.io/ex16/22_hires.png"}',
    searchName: 'Sableye (PK 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Seviper',
    tcgApiId: 'ex16-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/23.png","large":"https://images.pokemontcg.io/ex16/23_hires.png"}',
    searchName: 'Seviper (PK 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Wobbuffet',
    tcgApiId: 'ex16-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/24.png","large":"https://images.pokemontcg.io/ex16/24_hires.png"}',
    searchName: 'Wobbuffet (PK 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Zangoose',
    tcgApiId: 'ex16-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/25.png","large":"https://images.pokemontcg.io/ex16/25_hires.png"}',
    searchName: 'Zangoose (PK 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Anorith',
    tcgApiId: 'ex16-26',
    number: '26',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/26.png","large":"https://images.pokemontcg.io/ex16/26_hires.png"}',
    searchName: 'Anorith (PK 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Cacturne',
    tcgApiId: 'ex16-27',
    number: '27',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/27.png","large":"https://images.pokemontcg.io/ex16/27_hires.png"}',
    searchName: 'Cacturne (PK 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Charmeleon',
    tcgApiId: 'ex16-28',
    number: '28',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/28.png","large":"https://images.pokemontcg.io/ex16/28_hires.png"}',
    searchName: 'Charmeleon (PK 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Combusken',
    tcgApiId: 'ex16-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/29.png","large":"https://images.pokemontcg.io/ex16/29_hires.png"}',
    searchName: 'Combusken (PK 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Glalie',
    tcgApiId: 'ex16-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/30.png","large":"https://images.pokemontcg.io/ex16/30_hires.png"}',
    searchName: 'Glalie (PK 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Kirlia',
    tcgApiId: 'ex16-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/31.png","large":"https://images.pokemontcg.io/ex16/31_hires.png"}',
    searchName: 'Kirlia (PK 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Lairon',
    tcgApiId: 'ex16-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/32.png","large":"https://images.pokemontcg.io/ex16/32_hires.png"}',
    searchName: 'Lairon (PK 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Machoke',
    tcgApiId: 'ex16-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/33.png","large":"https://images.pokemontcg.io/ex16/33_hires.png"}',
    searchName: 'Machoke (PK 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Medicham',
    tcgApiId: 'ex16-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/34.png","large":"https://images.pokemontcg.io/ex16/34_hires.png"}',
    searchName: 'Medicham (PK 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Metang',
    tcgApiId: 'ex16-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/35.png","large":"https://images.pokemontcg.io/ex16/35_hires.png"}',
    searchName: 'Metang (PK 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Nuzleaf',
    tcgApiId: 'ex16-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/36.png","large":"https://images.pokemontcg.io/ex16/36_hires.png"}',
    searchName: 'Nuzleaf (PK 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Sealeo',
    tcgApiId: 'ex16-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/37.png","large":"https://images.pokemontcg.io/ex16/37_hires.png"}',
    searchName: 'Sealeo (PK 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Sharpedo',
    tcgApiId: 'ex16-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/38.png","large":"https://images.pokemontcg.io/ex16/38_hires.png"}',
    searchName: 'Sharpedo (PK 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Shelgon',
    tcgApiId: 'ex16-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/39.png","large":"https://images.pokemontcg.io/ex16/39_hires.png"}',
    searchName: 'Shelgon (PK 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Vibrava',
    tcgApiId: 'ex16-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/40.png","large":"https://images.pokemontcg.io/ex16/40_hires.png"}',
    searchName: 'Vibrava (PK 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Vigoroth',
    tcgApiId: 'ex16-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/41.png","large":"https://images.pokemontcg.io/ex16/41_hires.png"}',
    searchName: 'Vigoroth (PK 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Aron',
    tcgApiId: 'ex16-42',
    number: '42',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/42.png","large":"https://images.pokemontcg.io/ex16/42_hires.png"}',
    searchName: 'Aron (PK 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Bagon',
    tcgApiId: 'ex16-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/43.png","large":"https://images.pokemontcg.io/ex16/43_hires.png"}',
    searchName: 'Bagon (PK 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Baltoy',
    tcgApiId: 'ex16-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/44.png","large":"https://images.pokemontcg.io/ex16/44_hires.png"}',
    searchName: 'Baltoy (PK 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Beldum',
    tcgApiId: 'ex16-45',
    number: '45',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/45.png","large":"https://images.pokemontcg.io/ex16/45_hires.png"}',
    searchName: 'Beldum (PK 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Cacnea',
    tcgApiId: 'ex16-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/46.png","large":"https://images.pokemontcg.io/ex16/46_hires.png"}',
    searchName: 'Cacnea (PK 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Carvanha',
    tcgApiId: 'ex16-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/47.png","large":"https://images.pokemontcg.io/ex16/47_hires.png"}',
    searchName: 'Carvanha (PK 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Charmander',
    tcgApiId: 'ex16-48',
    number: '48',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/48.png","large":"https://images.pokemontcg.io/ex16/48_hires.png"}',
    searchName: 'Charmander (PK 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Chinchou',
    tcgApiId: 'ex16-49',
    number: '49',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/49.png","large":"https://images.pokemontcg.io/ex16/49_hires.png"}',
    searchName: 'Chinchou (PK 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Duskull',
    tcgApiId: 'ex16-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/50.png","large":"https://images.pokemontcg.io/ex16/50_hires.png"}',
    searchName: 'Duskull (PK 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Kabuto',
    tcgApiId: 'ex16-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/51.png","large":"https://images.pokemontcg.io/ex16/51_hires.png"}',
    searchName: 'Kabuto (PK 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Lileep',
    tcgApiId: 'ex16-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/52.png","large":"https://images.pokemontcg.io/ex16/52_hires.png"}',
    searchName: 'Lileep (PK 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Machop',
    tcgApiId: 'ex16-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/53.png","large":"https://images.pokemontcg.io/ex16/53_hires.png"}',
    searchName: 'Machop (PK 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Magnemite',
    tcgApiId: 'ex16-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/54.png","large":"https://images.pokemontcg.io/ex16/54_hires.png"}',
    searchName: 'Magnemite (PK 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Meditite',
    tcgApiId: 'ex16-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/55.png","large":"https://images.pokemontcg.io/ex16/55_hires.png"}',
    searchName: 'Meditite (PK 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Omanyte',
    tcgApiId: 'ex16-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/56.png","large":"https://images.pokemontcg.io/ex16/56_hires.png"}',
    searchName: 'Omanyte (PK 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Pikachu',
    tcgApiId: 'ex16-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/57.png","large":"https://images.pokemontcg.io/ex16/57_hires.png"}',
    searchName: 'Pikachu (PK 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Poochyena',
    tcgApiId: 'ex16-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/58.png","large":"https://images.pokemontcg.io/ex16/58_hires.png"}',
    searchName: 'Poochyena (PK 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Ralts',
    tcgApiId: 'ex16-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/59.png","large":"https://images.pokemontcg.io/ex16/59_hires.png"}',
    searchName: 'Ralts (PK 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Seedot',
    tcgApiId: 'ex16-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/60.png","large":"https://images.pokemontcg.io/ex16/60_hires.png"}',
    searchName: 'Seedot (PK 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Shuppet',
    tcgApiId: 'ex16-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/61.png","large":"https://images.pokemontcg.io/ex16/61_hires.png"}',
    searchName: 'Shuppet (PK 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Skitty',
    tcgApiId: 'ex16-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/62.png","large":"https://images.pokemontcg.io/ex16/62_hires.png"}',
    searchName: 'Skitty (PK 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Slakoth',
    tcgApiId: 'ex16-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/63.png","large":"https://images.pokemontcg.io/ex16/63_hires.png"}',
    searchName: 'Slakoth (PK 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Snorunt',
    tcgApiId: 'ex16-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/64.png","large":"https://images.pokemontcg.io/ex16/64_hires.png"}',
    searchName: 'Snorunt (PK 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Spheal',
    tcgApiId: 'ex16-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/65.png","large":"https://images.pokemontcg.io/ex16/65_hires.png"}',
    searchName: 'Spheal (PK 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Swablu',
    tcgApiId: 'ex16-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/66.png","large":"https://images.pokemontcg.io/ex16/66_hires.png"}',
    searchName: 'Swablu (PK 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Torchic',
    tcgApiId: 'ex16-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/67.png","large":"https://images.pokemontcg.io/ex16/67_hires.png"}',
    searchName: 'Torchic (PK 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Trapinch',
    tcgApiId: 'ex16-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/68.png","large":"https://images.pokemontcg.io/ex16/68_hires.png"}',
    searchName: 'Trapinch (PK 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Vulpix',
    tcgApiId: 'ex16-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/69.png","large":"https://images.pokemontcg.io/ex16/69_hires.png"}',
    searchName: 'Vulpix (PK 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Wynaut',
    tcgApiId: 'ex16-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/70.png","large":"https://images.pokemontcg.io/ex16/70_hires.png"}',
    searchName: 'Wynaut (PK 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Battle Frontier',
    tcgApiId: 'ex16-71',
    number: '71',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/71.png","large":"https://images.pokemontcg.io/ex16/71_hires.png"}',
    searchName: 'Battle Frontier (PK 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: "Drake's Stadium",
    tcgApiId: 'ex16-72',
    number: '72',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/72.png","large":"https://images.pokemontcg.io/ex16/72_hires.png"}',
    searchName: "Drake's Stadium (PK 72)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Energy Recycle System',
    tcgApiId: 'ex16-73',
    number: '73',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/73.png","large":"https://images.pokemontcg.io/ex16/73_hires.png"}',
    searchName: 'Energy Recycle System (PK 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Energy Removal 2',
    tcgApiId: 'ex16-74',
    number: '74',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/74.png","large":"https://images.pokemontcg.io/ex16/74_hires.png"}',
    searchName: 'Energy Removal 2 (PK 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Energy Switch',
    tcgApiId: 'ex16-75',
    number: '75',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/75.png","large":"https://images.pokemontcg.io/ex16/75_hires.png"}',
    searchName: 'Energy Switch (PK 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: "Glacia's Stadium",
    tcgApiId: 'ex16-76',
    number: '76',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/76.png","large":"https://images.pokemontcg.io/ex16/76_hires.png"}',
    searchName: "Glacia's Stadium (PK 76)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Great Ball',
    tcgApiId: 'ex16-77',
    number: '77',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/77.png","large":"https://images.pokemontcg.io/ex16/77_hires.png"}',
    searchName: 'Great Ball (PK 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Master Ball',
    tcgApiId: 'ex16-78',
    number: '78',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/78.png","large":"https://images.pokemontcg.io/ex16/78_hires.png"}',
    searchName: 'Master Ball (PK 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: "Phoebe's Stadium",
    tcgApiId: 'ex16-79',
    number: '79',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/79.png","large":"https://images.pokemontcg.io/ex16/79_hires.png"}',
    searchName: "Phoebe's Stadium (PK 79)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Professor Birch',
    tcgApiId: 'ex16-80',
    number: '80',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/80.png","large":"https://images.pokemontcg.io/ex16/80_hires.png"}',
    searchName: 'Professor Birch (PK 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Scott',
    tcgApiId: 'ex16-81',
    number: '81',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/81.png","large":"https://images.pokemontcg.io/ex16/81_hires.png"}',
    searchName: 'Scott (PK 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: "Sidney's Stadium",
    tcgApiId: 'ex16-82',
    number: '82',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/82.png","large":"https://images.pokemontcg.io/ex16/82_hires.png"}',
    searchName: "Sidney's Stadium (PK 82)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: "Steven's Advice",
    tcgApiId: 'ex16-83',
    number: '83',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/83.png","large":"https://images.pokemontcg.io/ex16/83_hires.png"}',
    searchName: "Steven's Advice (PK 83)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Claw Fossil',
    tcgApiId: 'ex16-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/84.png","large":"https://images.pokemontcg.io/ex16/84_hires.png"}',
    searchName: 'Claw Fossil (PK 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Mysterious Fossil',
    tcgApiId: 'ex16-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/85.png","large":"https://images.pokemontcg.io/ex16/85_hires.png"}',
    searchName: 'Mysterious Fossil (PK 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Root Fossil',
    tcgApiId: 'ex16-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/86.png","large":"https://images.pokemontcg.io/ex16/86_hires.png"}',
    searchName: 'Root Fossil (PK 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Darkness Energy',
    tcgApiId: 'ex16-87',
    number: '87',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/87.png","large":"https://images.pokemontcg.io/ex16/87_hires.png"}',
    searchName: 'Darkness Energy (PK 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Metal Energy',
    tcgApiId: 'ex16-88',
    number: '88',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/88.png","large":"https://images.pokemontcg.io/ex16/88_hires.png"}',
    searchName: 'Metal Energy (PK 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Multi Energy',
    tcgApiId: 'ex16-89',
    number: '89',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/89.png","large":"https://images.pokemontcg.io/ex16/89_hires.png"}',
    searchName: 'Multi Energy (PK 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Cyclone Energy',
    tcgApiId: 'ex16-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/90.png","large":"https://images.pokemontcg.io/ex16/90_hires.png"}',
    searchName: 'Cyclone Energy (PK 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Warp Energy',
    tcgApiId: 'ex16-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/91.png","large":"https://images.pokemontcg.io/ex16/91_hires.png"}',
    searchName: 'Warp Energy (PK 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Absol ex',
    tcgApiId: 'ex16-92',
    number: '92',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/92.png","large":"https://images.pokemontcg.io/ex16/92_hires.png"}',
    searchName: 'Absol ex (PK 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Claydol ex',
    tcgApiId: 'ex16-93',
    number: '93',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/93.png","large":"https://images.pokemontcg.io/ex16/93_hires.png"}',
    searchName: 'Claydol ex (PK 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Flygon ex',
    tcgApiId: 'ex16-94',
    number: '94',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/94.png","large":"https://images.pokemontcg.io/ex16/94_hires.png"}',
    searchName: 'Flygon ex (PK 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Metagross ex',
    tcgApiId: 'ex16-95',
    number: '95',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/95.png","large":"https://images.pokemontcg.io/ex16/95_hires.png"}',
    searchName: 'Metagross ex (PK 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Salamence ex',
    tcgApiId: 'ex16-96',
    number: '96',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/96.png","large":"https://images.pokemontcg.io/ex16/96_hires.png"}',
    searchName: 'Salamence ex (PK 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Shiftry ex',
    tcgApiId: 'ex16-97',
    number: '97',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/97.png","large":"https://images.pokemontcg.io/ex16/97_hires.png"}',
    searchName: 'Shiftry ex (PK 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Skarmory ex',
    tcgApiId: 'ex16-98',
    number: '98',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/98.png","large":"https://images.pokemontcg.io/ex16/98_hires.png"}',
    searchName: 'Skarmory ex (PK 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Walrein ex',
    tcgApiId: 'ex16-99',
    number: '99',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/99.png","large":"https://images.pokemontcg.io/ex16/99_hires.png"}',
    searchName: 'Walrein ex (PK 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Flareon ★',
    tcgApiId: 'ex16-100',
    number: '100',
    rarity: 'Rare Holo Star',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/100.png","large":"https://images.pokemontcg.io/ex16/100_hires.png"}',
    searchName: 'Flareon ★ (PK 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Jolteon ★',
    tcgApiId: 'ex16-101',
    number: '101',
    rarity: 'Rare Holo Star',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/101.png","large":"https://images.pokemontcg.io/ex16/101_hires.png"}',
    searchName: 'Jolteon ★ (PK 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Vaporeon ★',
    tcgApiId: 'ex16-102',
    number: '102',
    rarity: 'Rare Holo Star',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/102.png","large":"https://images.pokemontcg.io/ex16/102_hires.png"}',
    searchName: 'Vaporeon ★ (PK 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Grass Energy',
    tcgApiId: 'ex16-103',
    number: '103',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/103.png","large":"https://images.pokemontcg.io/ex16/103_hires.png"}',
    searchName: 'Grass Energy (PK 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Fire Energy',
    tcgApiId: 'ex16-104',
    number: '104',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/104.png","large":"https://images.pokemontcg.io/ex16/104_hires.png"}',
    searchName: 'Fire Energy (PK 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Water Energy',
    tcgApiId: 'ex16-105',
    number: '105',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/105.png","large":"https://images.pokemontcg.io/ex16/105_hires.png"}',
    searchName: 'Water Energy (PK 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Lightning Energy',
    tcgApiId: 'ex16-106',
    number: '106',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/106.png","large":"https://images.pokemontcg.io/ex16/106_hires.png"}',
    searchName: 'Lightning Energy (PK 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Psychic Energy',
    tcgApiId: 'ex16-107',
    number: '107',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/107.png","large":"https://images.pokemontcg.io/ex16/107_hires.png"}',
    searchName: 'Psychic Energy (PK 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex16',
    name: 'Fighting Energy',
    tcgApiId: 'ex16-108',
    number: '108',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex16/108.png","large":"https://images.pokemontcg.io/ex16/108_hires.png"}',
    searchName: 'Fighting Energy (PK 108)',
  },
];
