export const cardSeedEx2 = [
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Armaldo',
    tcgApiId: 'ex2-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/1.png","large":"https://images.pokemontcg.io/ex2/1_hires.png"}',
    searchName: 'Armaldo (SS 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Cacturne',
    tcgApiId: 'ex2-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/2.png","large":"https://images.pokemontcg.io/ex2/2_hires.png"}',
    searchName: 'Cacturne (SS 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Cradily',
    tcgApiId: 'ex2-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/3.png","large":"https://images.pokemontcg.io/ex2/3_hires.png"}',
    searchName: 'Cradily (SS 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Dusclops',
    tcgApiId: 'ex2-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/4.png","large":"https://images.pokemontcg.io/ex2/4_hires.png"}',
    searchName: 'Dusclops (SS 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Flareon',
    tcgApiId: 'ex2-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/5.png","large":"https://images.pokemontcg.io/ex2/5_hires.png"}',
    searchName: 'Flareon (SS 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Jolteon',
    tcgApiId: 'ex2-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/6.png","large":"https://images.pokemontcg.io/ex2/6_hires.png"}',
    searchName: 'Jolteon (SS 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Ludicolo',
    tcgApiId: 'ex2-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/7.png","large":"https://images.pokemontcg.io/ex2/7_hires.png"}',
    searchName: 'Ludicolo (SS 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Lunatone',
    tcgApiId: 'ex2-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/8.png","large":"https://images.pokemontcg.io/ex2/8_hires.png"}',
    searchName: 'Lunatone (SS 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Mawile',
    tcgApiId: 'ex2-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/9.png","large":"https://images.pokemontcg.io/ex2/9_hires.png"}',
    searchName: 'Mawile (SS 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Sableye',
    tcgApiId: 'ex2-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/10.png","large":"https://images.pokemontcg.io/ex2/10_hires.png"}',
    searchName: 'Sableye (SS 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Seviper',
    tcgApiId: 'ex2-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/11.png","large":"https://images.pokemontcg.io/ex2/11_hires.png"}',
    searchName: 'Seviper (SS 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Shiftry',
    tcgApiId: 'ex2-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/12.png","large":"https://images.pokemontcg.io/ex2/12_hires.png"}',
    searchName: 'Shiftry (SS 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Solrock',
    tcgApiId: 'ex2-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/13.png","large":"https://images.pokemontcg.io/ex2/13_hires.png"}',
    searchName: 'Solrock (SS 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Zangoose',
    tcgApiId: 'ex2-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/14.png","large":"https://images.pokemontcg.io/ex2/14_hires.png"}',
    searchName: 'Zangoose (SS 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Arcanine',
    tcgApiId: 'ex2-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/15.png","large":"https://images.pokemontcg.io/ex2/15_hires.png"}',
    searchName: 'Arcanine (SS 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Espeon',
    tcgApiId: 'ex2-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/16.png","large":"https://images.pokemontcg.io/ex2/16_hires.png"}',
    searchName: 'Espeon (SS 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Golduck',
    tcgApiId: 'ex2-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/17.png","large":"https://images.pokemontcg.io/ex2/17_hires.png"}',
    searchName: 'Golduck (SS 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Kecleon',
    tcgApiId: 'ex2-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/18.png","large":"https://images.pokemontcg.io/ex2/18_hires.png"}',
    searchName: 'Kecleon (SS 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Omastar',
    tcgApiId: 'ex2-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/19.png","large":"https://images.pokemontcg.io/ex2/19_hires.png"}',
    searchName: 'Omastar (SS 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Pichu',
    tcgApiId: 'ex2-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/20.png","large":"https://images.pokemontcg.io/ex2/20_hires.png"}',
    searchName: 'Pichu (SS 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Sandslash',
    tcgApiId: 'ex2-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/21.png","large":"https://images.pokemontcg.io/ex2/21_hires.png"}',
    searchName: 'Sandslash (SS 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Shiftry',
    tcgApiId: 'ex2-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/22.png","large":"https://images.pokemontcg.io/ex2/22_hires.png"}',
    searchName: 'Shiftry (SS 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Steelix',
    tcgApiId: 'ex2-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/23.png","large":"https://images.pokemontcg.io/ex2/23_hires.png"}',
    searchName: 'Steelix (SS 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Umbreon',
    tcgApiId: 'ex2-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/24.png","large":"https://images.pokemontcg.io/ex2/24_hires.png"}',
    searchName: 'Umbreon (SS 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Vaporeon',
    tcgApiId: 'ex2-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/25.png","large":"https://images.pokemontcg.io/ex2/25_hires.png"}',
    searchName: 'Vaporeon (SS 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Wobbuffet',
    tcgApiId: 'ex2-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/26.png","large":"https://images.pokemontcg.io/ex2/26_hires.png"}',
    searchName: 'Wobbuffet (SS 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Anorith',
    tcgApiId: 'ex2-27',
    number: '27',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/27.png","large":"https://images.pokemontcg.io/ex2/27_hires.png"}',
    searchName: 'Anorith (SS 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Anorith',
    tcgApiId: 'ex2-28',
    number: '28',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/28.png","large":"https://images.pokemontcg.io/ex2/28_hires.png"}',
    searchName: 'Anorith (SS 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Arbok',
    tcgApiId: 'ex2-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/29.png","large":"https://images.pokemontcg.io/ex2/29_hires.png"}',
    searchName: 'Arbok (SS 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Azumarill',
    tcgApiId: 'ex2-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/30.png","large":"https://images.pokemontcg.io/ex2/30_hires.png"}',
    searchName: 'Azumarill (SS 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Azurill',
    tcgApiId: 'ex2-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/31.png","large":"https://images.pokemontcg.io/ex2/31_hires.png"}',
    searchName: 'Azurill (SS 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Baltoy',
    tcgApiId: 'ex2-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/32.png","large":"https://images.pokemontcg.io/ex2/32_hires.png"}',
    searchName: 'Baltoy (SS 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Breloom',
    tcgApiId: 'ex2-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/33.png","large":"https://images.pokemontcg.io/ex2/33_hires.png"}',
    searchName: 'Breloom (SS 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Delcatty',
    tcgApiId: 'ex2-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/34.png","large":"https://images.pokemontcg.io/ex2/34_hires.png"}',
    searchName: 'Delcatty (SS 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Electabuzz',
    tcgApiId: 'ex2-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/35.png","large":"https://images.pokemontcg.io/ex2/35_hires.png"}',
    searchName: 'Electabuzz (SS 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Elekid',
    tcgApiId: 'ex2-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/36.png","large":"https://images.pokemontcg.io/ex2/36_hires.png"}',
    searchName: 'Elekid (SS 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Fearow',
    tcgApiId: 'ex2-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/37.png","large":"https://images.pokemontcg.io/ex2/37_hires.png"}',
    searchName: 'Fearow (SS 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Illumise',
    tcgApiId: 'ex2-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/38.png","large":"https://images.pokemontcg.io/ex2/38_hires.png"}',
    searchName: 'Illumise (SS 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Kabuto',
    tcgApiId: 'ex2-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/39.png","large":"https://images.pokemontcg.io/ex2/39_hires.png"}',
    searchName: 'Kabuto (SS 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Kirlia',
    tcgApiId: 'ex2-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/40.png","large":"https://images.pokemontcg.io/ex2/40_hires.png"}',
    searchName: 'Kirlia (SS 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Lairon',
    tcgApiId: 'ex2-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/41.png","large":"https://images.pokemontcg.io/ex2/41_hires.png"}',
    searchName: 'Lairon (SS 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Lileep',
    tcgApiId: 'ex2-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/42.png","large":"https://images.pokemontcg.io/ex2/42_hires.png"}',
    searchName: 'Lileep (SS 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Lileep',
    tcgApiId: 'ex2-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/43.png","large":"https://images.pokemontcg.io/ex2/43_hires.png"}',
    searchName: 'Lileep (SS 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Linoone',
    tcgApiId: 'ex2-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/44.png","large":"https://images.pokemontcg.io/ex2/44_hires.png"}',
    searchName: 'Linoone (SS 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Lombre',
    tcgApiId: 'ex2-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/45.png","large":"https://images.pokemontcg.io/ex2/45_hires.png"}',
    searchName: 'Lombre (SS 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Lombre',
    tcgApiId: 'ex2-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/46.png","large":"https://images.pokemontcg.io/ex2/46_hires.png"}',
    searchName: 'Lombre (SS 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Murkrow',
    tcgApiId: 'ex2-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/47.png","large":"https://images.pokemontcg.io/ex2/47_hires.png"}',
    searchName: 'Murkrow (SS 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Nuzleaf',
    tcgApiId: 'ex2-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/48.png","large":"https://images.pokemontcg.io/ex2/48_hires.png"}',
    searchName: 'Nuzleaf (SS 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Nuzleaf',
    tcgApiId: 'ex2-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/49.png","large":"https://images.pokemontcg.io/ex2/49_hires.png"}',
    searchName: 'Nuzleaf (SS 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Pelipper',
    tcgApiId: 'ex2-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/50.png","large":"https://images.pokemontcg.io/ex2/50_hires.png"}',
    searchName: 'Pelipper (SS 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Quilava',
    tcgApiId: 'ex2-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/51.png","large":"https://images.pokemontcg.io/ex2/51_hires.png"}',
    searchName: 'Quilava (SS 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Vigoroth',
    tcgApiId: 'ex2-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/52.png","large":"https://images.pokemontcg.io/ex2/52_hires.png"}',
    searchName: 'Vigoroth (SS 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Volbeat',
    tcgApiId: 'ex2-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/53.png","large":"https://images.pokemontcg.io/ex2/53_hires.png"}',
    searchName: 'Volbeat (SS 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Wynaut',
    tcgApiId: 'ex2-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/54.png","large":"https://images.pokemontcg.io/ex2/54_hires.png"}',
    searchName: 'Wynaut (SS 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Xatu',
    tcgApiId: 'ex2-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/55.png","large":"https://images.pokemontcg.io/ex2/55_hires.png"}',
    searchName: 'Xatu (SS 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Aron',
    tcgApiId: 'ex2-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/56.png","large":"https://images.pokemontcg.io/ex2/56_hires.png"}',
    searchName: 'Aron (SS 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Cacnea',
    tcgApiId: 'ex2-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/57.png","large":"https://images.pokemontcg.io/ex2/57_hires.png"}',
    searchName: 'Cacnea (SS 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Cacnea',
    tcgApiId: 'ex2-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/58.png","large":"https://images.pokemontcg.io/ex2/58_hires.png"}',
    searchName: 'Cacnea (SS 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Cyndaquil',
    tcgApiId: 'ex2-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/59.png","large":"https://images.pokemontcg.io/ex2/59_hires.png"}',
    searchName: 'Cyndaquil (SS 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Dunsparce',
    tcgApiId: 'ex2-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/60.png","large":"https://images.pokemontcg.io/ex2/60_hires.png"}',
    searchName: 'Dunsparce (SS 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Duskull',
    tcgApiId: 'ex2-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/61.png","large":"https://images.pokemontcg.io/ex2/61_hires.png"}',
    searchName: 'Duskull (SS 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Duskull',
    tcgApiId: 'ex2-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/62.png","large":"https://images.pokemontcg.io/ex2/62_hires.png"}',
    searchName: 'Duskull (SS 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Eevee',
    tcgApiId: 'ex2-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/63.png","large":"https://images.pokemontcg.io/ex2/63_hires.png"}',
    searchName: 'Eevee (SS 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Ekans',
    tcgApiId: 'ex2-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/64.png","large":"https://images.pokemontcg.io/ex2/64_hires.png"}',
    searchName: 'Ekans (SS 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Growlithe',
    tcgApiId: 'ex2-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/65.png","large":"https://images.pokemontcg.io/ex2/65_hires.png"}',
    searchName: 'Growlithe (SS 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Lotad',
    tcgApiId: 'ex2-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/66.png","large":"https://images.pokemontcg.io/ex2/66_hires.png"}',
    searchName: 'Lotad (SS 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Lotad',
    tcgApiId: 'ex2-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/67.png","large":"https://images.pokemontcg.io/ex2/67_hires.png"}',
    searchName: 'Lotad (SS 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Marill',
    tcgApiId: 'ex2-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/68.png","large":"https://images.pokemontcg.io/ex2/68_hires.png"}',
    searchName: 'Marill (SS 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Natu',
    tcgApiId: 'ex2-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/69.png","large":"https://images.pokemontcg.io/ex2/69_hires.png"}',
    searchName: 'Natu (SS 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Omanyte',
    tcgApiId: 'ex2-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/70.png","large":"https://images.pokemontcg.io/ex2/70_hires.png"}',
    searchName: 'Omanyte (SS 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Onix',
    tcgApiId: 'ex2-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/71.png","large":"https://images.pokemontcg.io/ex2/71_hires.png"}',
    searchName: 'Onix (SS 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Pikachu',
    tcgApiId: 'ex2-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/72.png","large":"https://images.pokemontcg.io/ex2/72_hires.png"}',
    searchName: 'Pikachu (SS 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Psyduck',
    tcgApiId: 'ex2-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/73.png","large":"https://images.pokemontcg.io/ex2/73_hires.png"}',
    searchName: 'Psyduck (SS 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Ralts',
    tcgApiId: 'ex2-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/74.png","large":"https://images.pokemontcg.io/ex2/74_hires.png"}',
    searchName: 'Ralts (SS 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Sandshrew',
    tcgApiId: 'ex2-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/75.png","large":"https://images.pokemontcg.io/ex2/75_hires.png"}',
    searchName: 'Sandshrew (SS 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Seedot',
    tcgApiId: 'ex2-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/76.png","large":"https://images.pokemontcg.io/ex2/76_hires.png"}',
    searchName: 'Seedot (SS 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Seedot',
    tcgApiId: 'ex2-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/77.png","large":"https://images.pokemontcg.io/ex2/77_hires.png"}',
    searchName: 'Seedot (SS 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Shroomish',
    tcgApiId: 'ex2-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/78.png","large":"https://images.pokemontcg.io/ex2/78_hires.png"}',
    searchName: 'Shroomish (SS 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Skitty',
    tcgApiId: 'ex2-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/79.png","large":"https://images.pokemontcg.io/ex2/79_hires.png"}',
    searchName: 'Skitty (SS 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Slakoth',
    tcgApiId: 'ex2-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/80.png","large":"https://images.pokemontcg.io/ex2/80_hires.png"}',
    searchName: 'Slakoth (SS 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Spearow',
    tcgApiId: 'ex2-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/81.png","large":"https://images.pokemontcg.io/ex2/81_hires.png"}',
    searchName: 'Spearow (SS 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Trapinch',
    tcgApiId: 'ex2-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/82.png","large":"https://images.pokemontcg.io/ex2/82_hires.png"}',
    searchName: 'Trapinch (SS 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Wailmer',
    tcgApiId: 'ex2-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/83.png","large":"https://images.pokemontcg.io/ex2/83_hires.png"}',
    searchName: 'Wailmer (SS 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Wingull',
    tcgApiId: 'ex2-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/84.png","large":"https://images.pokemontcg.io/ex2/84_hires.png"}',
    searchName: 'Wingull (SS 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Zigzagoon',
    tcgApiId: 'ex2-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/85.png","large":"https://images.pokemontcg.io/ex2/85_hires.png"}',
    searchName: 'Zigzagoon (SS 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Double Full Heal',
    tcgApiId: 'ex2-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/86.png","large":"https://images.pokemontcg.io/ex2/86_hires.png"}',
    searchName: 'Double Full Heal (SS 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: "Lanette's Net Search",
    tcgApiId: 'ex2-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/87.png","large":"https://images.pokemontcg.io/ex2/87_hires.png"}',
    searchName: "Lanette's Net Search (SS 87)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Rare Candy',
    tcgApiId: 'ex2-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/88.png","large":"https://images.pokemontcg.io/ex2/88_hires.png"}',
    searchName: 'Rare Candy (SS 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: "Wally's Training",
    tcgApiId: 'ex2-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/89.png","large":"https://images.pokemontcg.io/ex2/89_hires.png"}',
    searchName: "Wally's Training (SS 89)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Claw Fossil',
    tcgApiId: 'ex2-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/90.png","large":"https://images.pokemontcg.io/ex2/90_hires.png"}',
    searchName: 'Claw Fossil (SS 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Mysterious Fossil',
    tcgApiId: 'ex2-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/91.png","large":"https://images.pokemontcg.io/ex2/91_hires.png"}',
    searchName: 'Mysterious Fossil (SS 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Root Fossil',
    tcgApiId: 'ex2-92',
    number: '92',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/92.png","large":"https://images.pokemontcg.io/ex2/92_hires.png"}',
    searchName: 'Root Fossil (SS 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Multi Energy',
    tcgApiId: 'ex2-93',
    number: '93',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/93.png","large":"https://images.pokemontcg.io/ex2/93_hires.png"}',
    searchName: 'Multi Energy (SS 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Aerodactyl ex',
    tcgApiId: 'ex2-94',
    number: '94',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/94.png","large":"https://images.pokemontcg.io/ex2/94_hires.png"}',
    searchName: 'Aerodactyl ex (SS 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Aggron ex',
    tcgApiId: 'ex2-95',
    number: '95',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/95.png","large":"https://images.pokemontcg.io/ex2/95_hires.png"}',
    searchName: 'Aggron ex (SS 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Gardevoir ex',
    tcgApiId: 'ex2-96',
    number: '96',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/96.png","large":"https://images.pokemontcg.io/ex2/96_hires.png"}',
    searchName: 'Gardevoir ex (SS 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Kabutops ex',
    tcgApiId: 'ex2-97',
    number: '97',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/97.png","large":"https://images.pokemontcg.io/ex2/97_hires.png"}',
    searchName: 'Kabutops ex (SS 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Raichu ex',
    tcgApiId: 'ex2-98',
    number: '98',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/98.png","large":"https://images.pokemontcg.io/ex2/98_hires.png"}',
    searchName: 'Raichu ex (SS 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Typhlosion ex',
    tcgApiId: 'ex2-99',
    number: '99',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/99.png","large":"https://images.pokemontcg.io/ex2/99_hires.png"}',
    searchName: 'Typhlosion ex (SS 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex2',
    name: 'Wailord ex',
    tcgApiId: 'ex2-100',
    number: '100',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex2/100.png","large":"https://images.pokemontcg.io/ex2/100_hires.png"}',
    searchName: 'Wailord ex (SS 100)',
  },
];
