export const cardSeedEx5 = [
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Banette',
    tcgApiId: 'ex5-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/1.png","large":"https://images.pokemontcg.io/ex5/1_hires.png"}',
    searchName: 'Banette (HL 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Claydol',
    tcgApiId: 'ex5-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/2.png","large":"https://images.pokemontcg.io/ex5/2_hires.png"}',
    searchName: 'Claydol (HL 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Crobat',
    tcgApiId: 'ex5-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/3.png","large":"https://images.pokemontcg.io/ex5/3_hires.png"}',
    searchName: 'Crobat (HL 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Dark Celebi',
    tcgApiId: 'ex5-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/4.png","large":"https://images.pokemontcg.io/ex5/4_hires.png"}',
    searchName: 'Dark Celebi (HL 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Electrode',
    tcgApiId: 'ex5-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/5.png","large":"https://images.pokemontcg.io/ex5/5_hires.png"}',
    searchName: 'Electrode (HL 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Exploud',
    tcgApiId: 'ex5-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/6.png","large":"https://images.pokemontcg.io/ex5/6_hires.png"}',
    searchName: 'Exploud (HL 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Heracross',
    tcgApiId: 'ex5-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/7.png","large":"https://images.pokemontcg.io/ex5/7_hires.png"}',
    searchName: 'Heracross (HL 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Jirachi',
    tcgApiId: 'ex5-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/8.png","large":"https://images.pokemontcg.io/ex5/8_hires.png"}',
    searchName: 'Jirachi (HL 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Machamp',
    tcgApiId: 'ex5-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/9.png","large":"https://images.pokemontcg.io/ex5/9_hires.png"}',
    searchName: 'Machamp (HL 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Medicham',
    tcgApiId: 'ex5-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/10.png","large":"https://images.pokemontcg.io/ex5/10_hires.png"}',
    searchName: 'Medicham (HL 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Metagross',
    tcgApiId: 'ex5-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/11.png","large":"https://images.pokemontcg.io/ex5/11_hires.png"}',
    searchName: 'Metagross (HL 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Milotic',
    tcgApiId: 'ex5-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/12.png","large":"https://images.pokemontcg.io/ex5/12_hires.png"}',
    searchName: 'Milotic (HL 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Pinsir',
    tcgApiId: 'ex5-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/13.png","large":"https://images.pokemontcg.io/ex5/13_hires.png"}',
    searchName: 'Pinsir (HL 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Shiftry',
    tcgApiId: 'ex5-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/14.png","large":"https://images.pokemontcg.io/ex5/14_hires.png"}',
    searchName: 'Shiftry (HL 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Walrein',
    tcgApiId: 'ex5-15',
    number: '15',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/15.png","large":"https://images.pokemontcg.io/ex5/15_hires.png"}',
    searchName: 'Walrein (HL 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Bellossom',
    tcgApiId: 'ex5-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/16.png","large":"https://images.pokemontcg.io/ex5/16_hires.png"}',
    searchName: 'Bellossom (HL 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Chimecho',
    tcgApiId: 'ex5-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/17.png","large":"https://images.pokemontcg.io/ex5/17_hires.png"}',
    searchName: 'Chimecho (HL 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Gorebyss',
    tcgApiId: 'ex5-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/18.png","large":"https://images.pokemontcg.io/ex5/18_hires.png"}',
    searchName: 'Gorebyss (HL 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Huntail',
    tcgApiId: 'ex5-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/19.png","large":"https://images.pokemontcg.io/ex5/19_hires.png"}',
    searchName: 'Huntail (HL 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Masquerain',
    tcgApiId: 'ex5-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/20.png","large":"https://images.pokemontcg.io/ex5/20_hires.png"}',
    searchName: 'Masquerain (HL 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Metang',
    tcgApiId: 'ex5-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/21.png","large":"https://images.pokemontcg.io/ex5/21_hires.png"}',
    searchName: 'Metang (HL 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Ninetales',
    tcgApiId: 'ex5-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/22.png","large":"https://images.pokemontcg.io/ex5/22_hires.png"}',
    searchName: 'Ninetales (HL 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Rain Castform',
    tcgApiId: 'ex5-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/23.png","large":"https://images.pokemontcg.io/ex5/23_hires.png"}',
    searchName: 'Rain Castform (HL 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Relicanth',
    tcgApiId: 'ex5-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/24.png","large":"https://images.pokemontcg.io/ex5/24_hires.png"}',
    searchName: 'Relicanth (HL 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Snow-cloud Castform',
    tcgApiId: 'ex5-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/25.png","large":"https://images.pokemontcg.io/ex5/25_hires.png"}',
    searchName: 'Snow-cloud Castform (HL 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Sunny Castform',
    tcgApiId: 'ex5-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/26.png","large":"https://images.pokemontcg.io/ex5/26_hires.png"}',
    searchName: 'Sunny Castform (HL 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Tropius',
    tcgApiId: 'ex5-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/27.png","large":"https://images.pokemontcg.io/ex5/27_hires.png"}',
    searchName: 'Tropius (HL 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Beldum',
    tcgApiId: 'ex5-28',
    number: '28',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/28.png","large":"https://images.pokemontcg.io/ex5/28_hires.png"}',
    searchName: 'Beldum (HL 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Beldum',
    tcgApiId: 'ex5-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/29.png","large":"https://images.pokemontcg.io/ex5/29_hires.png"}',
    searchName: 'Beldum (HL 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Castform',
    tcgApiId: 'ex5-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/30.png","large":"https://images.pokemontcg.io/ex5/30_hires.png"}',
    searchName: 'Castform (HL 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Claydol',
    tcgApiId: 'ex5-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/31.png","large":"https://images.pokemontcg.io/ex5/31_hires.png"}',
    searchName: 'Claydol (HL 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Corsola',
    tcgApiId: 'ex5-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/32.png","large":"https://images.pokemontcg.io/ex5/32_hires.png"}',
    searchName: 'Corsola (HL 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Dodrio',
    tcgApiId: 'ex5-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/33.png","large":"https://images.pokemontcg.io/ex5/33_hires.png"}',
    searchName: 'Dodrio (HL 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Glalie',
    tcgApiId: 'ex5-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/34.png","large":"https://images.pokemontcg.io/ex5/34_hires.png"}',
    searchName: 'Glalie (HL 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Gloom',
    tcgApiId: 'ex5-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/35.png","large":"https://images.pokemontcg.io/ex5/35_hires.png"}',
    searchName: 'Gloom (HL 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Golbat',
    tcgApiId: 'ex5-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/36.png","large":"https://images.pokemontcg.io/ex5/36_hires.png"}',
    searchName: 'Golbat (HL 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Igglybuff',
    tcgApiId: 'ex5-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/37.png","large":"https://images.pokemontcg.io/ex5/37_hires.png"}',
    searchName: 'Igglybuff (HL 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Lanturn',
    tcgApiId: 'ex5-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/38.png","large":"https://images.pokemontcg.io/ex5/38_hires.png"}',
    searchName: 'Lanturn (HL 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Loudred',
    tcgApiId: 'ex5-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/39.png","large":"https://images.pokemontcg.io/ex5/39_hires.png"}',
    searchName: 'Loudred (HL 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Luvdisc',
    tcgApiId: 'ex5-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/40.png","large":"https://images.pokemontcg.io/ex5/40_hires.png"}',
    searchName: 'Luvdisc (HL 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Machoke',
    tcgApiId: 'ex5-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/41.png","large":"https://images.pokemontcg.io/ex5/41_hires.png"}',
    searchName: 'Machoke (HL 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Medicham',
    tcgApiId: 'ex5-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/42.png","large":"https://images.pokemontcg.io/ex5/42_hires.png"}',
    searchName: 'Medicham (HL 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Metang',
    tcgApiId: 'ex5-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/43.png","large":"https://images.pokemontcg.io/ex5/43_hires.png"}',
    searchName: 'Metang (HL 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Metang',
    tcgApiId: 'ex5-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/44.png","large":"https://images.pokemontcg.io/ex5/44_hires.png"}',
    searchName: 'Metang (HL 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Nuzleaf',
    tcgApiId: 'ex5-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/45.png","large":"https://images.pokemontcg.io/ex5/45_hires.png"}',
    searchName: 'Nuzleaf (HL 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Rhydon',
    tcgApiId: 'ex5-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/46.png","large":"https://images.pokemontcg.io/ex5/46_hires.png"}',
    searchName: 'Rhydon (HL 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Sealeo',
    tcgApiId: 'ex5-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/47.png","large":"https://images.pokemontcg.io/ex5/47_hires.png"}',
    searchName: 'Sealeo (HL 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Spinda',
    tcgApiId: 'ex5-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/48.png","large":"https://images.pokemontcg.io/ex5/48_hires.png"}',
    searchName: 'Spinda (HL 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Starmie',
    tcgApiId: 'ex5-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/49.png","large":"https://images.pokemontcg.io/ex5/49_hires.png"}',
    searchName: 'Starmie (HL 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Swalot',
    tcgApiId: 'ex5-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/50.png","large":"https://images.pokemontcg.io/ex5/50_hires.png"}',
    searchName: 'Swalot (HL 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Tentacruel',
    tcgApiId: 'ex5-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/51.png","large":"https://images.pokemontcg.io/ex5/51_hires.png"}',
    searchName: 'Tentacruel (HL 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Baltoy',
    tcgApiId: 'ex5-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/52.png","large":"https://images.pokemontcg.io/ex5/52_hires.png"}',
    searchName: 'Baltoy (HL 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Baltoy',
    tcgApiId: 'ex5-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/53.png","large":"https://images.pokemontcg.io/ex5/53_hires.png"}',
    searchName: 'Baltoy (HL 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Beldum',
    tcgApiId: 'ex5-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/54.png","large":"https://images.pokemontcg.io/ex5/54_hires.png"}',
    searchName: 'Beldum (HL 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Chikorita',
    tcgApiId: 'ex5-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/55.png","large":"https://images.pokemontcg.io/ex5/55_hires.png"}',
    searchName: 'Chikorita (HL 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Chinchou',
    tcgApiId: 'ex5-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/56.png","large":"https://images.pokemontcg.io/ex5/56_hires.png"}',
    searchName: 'Chinchou (HL 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Chinchou',
    tcgApiId: 'ex5-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/57.png","large":"https://images.pokemontcg.io/ex5/57_hires.png"}',
    searchName: 'Chinchou (HL 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Clamperl',
    tcgApiId: 'ex5-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/58.png","large":"https://images.pokemontcg.io/ex5/58_hires.png"}',
    searchName: 'Clamperl (HL 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Cyndaquil',
    tcgApiId: 'ex5-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/59.png","large":"https://images.pokemontcg.io/ex5/59_hires.png"}',
    searchName: 'Cyndaquil (HL 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Doduo',
    tcgApiId: 'ex5-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/60.png","large":"https://images.pokemontcg.io/ex5/60_hires.png"}',
    searchName: 'Doduo (HL 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Feebas',
    tcgApiId: 'ex5-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/61.png","large":"https://images.pokemontcg.io/ex5/61_hires.png"}',
    searchName: 'Feebas (HL 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Gulpin',
    tcgApiId: 'ex5-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/62.png","large":"https://images.pokemontcg.io/ex5/62_hires.png"}',
    searchName: 'Gulpin (HL 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Jigglypuff',
    tcgApiId: 'ex5-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/63.png","large":"https://images.pokemontcg.io/ex5/63_hires.png"}',
    searchName: 'Jigglypuff (HL 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Machop',
    tcgApiId: 'ex5-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/64.png","large":"https://images.pokemontcg.io/ex5/64_hires.png"}',
    searchName: 'Machop (HL 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Meditite',
    tcgApiId: 'ex5-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/65.png","large":"https://images.pokemontcg.io/ex5/65_hires.png"}',
    searchName: 'Meditite (HL 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Meditite',
    tcgApiId: 'ex5-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/66.png","large":"https://images.pokemontcg.io/ex5/66_hires.png"}',
    searchName: 'Meditite (HL 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Minun',
    tcgApiId: 'ex5-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/67.png","large":"https://images.pokemontcg.io/ex5/67_hires.png"}',
    searchName: 'Minun (HL 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Oddish',
    tcgApiId: 'ex5-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/68.png","large":"https://images.pokemontcg.io/ex5/68_hires.png"}',
    searchName: 'Oddish (HL 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Plusle',
    tcgApiId: 'ex5-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/69.png","large":"https://images.pokemontcg.io/ex5/69_hires.png"}',
    searchName: 'Plusle (HL 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Rhyhorn',
    tcgApiId: 'ex5-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/70.png","large":"https://images.pokemontcg.io/ex5/70_hires.png"}',
    searchName: 'Rhyhorn (HL 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Seedot',
    tcgApiId: 'ex5-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/71.png","large":"https://images.pokemontcg.io/ex5/71_hires.png"}',
    searchName: 'Seedot (HL 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Shuppet',
    tcgApiId: 'ex5-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/72.png","large":"https://images.pokemontcg.io/ex5/72_hires.png"}',
    searchName: 'Shuppet (HL 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Snorunt',
    tcgApiId: 'ex5-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/73.png","large":"https://images.pokemontcg.io/ex5/73_hires.png"}',
    searchName: 'Snorunt (HL 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Spheal',
    tcgApiId: 'ex5-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/74.png","large":"https://images.pokemontcg.io/ex5/74_hires.png"}',
    searchName: 'Spheal (HL 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Staryu',
    tcgApiId: 'ex5-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/75.png","large":"https://images.pokemontcg.io/ex5/75_hires.png"}',
    searchName: 'Staryu (HL 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Surskit',
    tcgApiId: 'ex5-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/76.png","large":"https://images.pokemontcg.io/ex5/76_hires.png"}',
    searchName: 'Surskit (HL 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Tentacool',
    tcgApiId: 'ex5-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/77.png","large":"https://images.pokemontcg.io/ex5/77_hires.png"}',
    searchName: 'Tentacool (HL 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Togepi',
    tcgApiId: 'ex5-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/78.png","large":"https://images.pokemontcg.io/ex5/78_hires.png"}',
    searchName: 'Togepi (HL 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Totodile',
    tcgApiId: 'ex5-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/79.png","large":"https://images.pokemontcg.io/ex5/79_hires.png"}',
    searchName: 'Totodile (HL 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Voltorb',
    tcgApiId: 'ex5-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/80.png","large":"https://images.pokemontcg.io/ex5/80_hires.png"}',
    searchName: 'Voltorb (HL 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Vulpix',
    tcgApiId: 'ex5-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/81.png","large":"https://images.pokemontcg.io/ex5/81_hires.png"}',
    searchName: 'Vulpix (HL 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Whismur',
    tcgApiId: 'ex5-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/82.png","large":"https://images.pokemontcg.io/ex5/82_hires.png"}',
    searchName: 'Whismur (HL 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Zubat',
    tcgApiId: 'ex5-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/83.png","large":"https://images.pokemontcg.io/ex5/83_hires.png"}',
    searchName: 'Zubat (HL 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Ancient Technical Machine [Ice]',
    tcgApiId: 'ex5-84',
    number: '84',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/84.png","large":"https://images.pokemontcg.io/ex5/84_hires.png"}',
    searchName: 'Ancient Technical Machine [Ice] (HL 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Ancient Technical Machine [Rock]',
    tcgApiId: 'ex5-85',
    number: '85',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/85.png","large":"https://images.pokemontcg.io/ex5/85_hires.png"}',
    searchName: 'Ancient Technical Machine [Rock] (HL 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Ancient Technical Machine [Steel]',
    tcgApiId: 'ex5-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/86.png","large":"https://images.pokemontcg.io/ex5/86_hires.png"}',
    searchName: 'Ancient Technical Machine [Steel] (HL 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Ancient Tomb',
    tcgApiId: 'ex5-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/87.png","large":"https://images.pokemontcg.io/ex5/87_hires.png"}',
    searchName: 'Ancient Tomb (HL 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Desert Ruins',
    tcgApiId: 'ex5-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/88.png","large":"https://images.pokemontcg.io/ex5/88_hires.png"}',
    searchName: 'Desert Ruins (HL 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Island Cave',
    tcgApiId: 'ex5-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/89.png","large":"https://images.pokemontcg.io/ex5/89_hires.png"}',
    searchName: 'Island Cave (HL 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Life Herb',
    tcgApiId: 'ex5-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/90.png","large":"https://images.pokemontcg.io/ex5/90_hires.png"}',
    searchName: 'Life Herb (HL 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Magnetic Storm',
    tcgApiId: 'ex5-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/91.png","large":"https://images.pokemontcg.io/ex5/91_hires.png"}',
    searchName: 'Magnetic Storm (HL 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: "Steven's Advice",
    tcgApiId: 'ex5-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/92.png","large":"https://images.pokemontcg.io/ex5/92_hires.png"}',
    searchName: "Steven's Advice (HL 92)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Groudon ex',
    tcgApiId: 'ex5-93',
    number: '93',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/93.png","large":"https://images.pokemontcg.io/ex5/93_hires.png"}',
    searchName: 'Groudon ex (HL 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Kyogre ex',
    tcgApiId: 'ex5-94',
    number: '94',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/94.png","large":"https://images.pokemontcg.io/ex5/94_hires.png"}',
    searchName: 'Kyogre ex (HL 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Metagross ex',
    tcgApiId: 'ex5-95',
    number: '95',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/95.png","large":"https://images.pokemontcg.io/ex5/95_hires.png"}',
    searchName: 'Metagross ex (HL 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Ninetales ex',
    tcgApiId: 'ex5-96',
    number: '96',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/96.png","large":"https://images.pokemontcg.io/ex5/96_hires.png"}',
    searchName: 'Ninetales ex (HL 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Regice ex',
    tcgApiId: 'ex5-97',
    number: '97',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/97.png","large":"https://images.pokemontcg.io/ex5/97_hires.png"}',
    searchName: 'Regice ex (HL 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Regirock ex',
    tcgApiId: 'ex5-98',
    number: '98',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/98.png","large":"https://images.pokemontcg.io/ex5/98_hires.png"}',
    searchName: 'Regirock ex (HL 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Registeel ex',
    tcgApiId: 'ex5-99',
    number: '99',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/99.png","large":"https://images.pokemontcg.io/ex5/99_hires.png"}',
    searchName: 'Registeel ex (HL 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Vileplume ex',
    tcgApiId: 'ex5-100',
    number: '100',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/100.png","large":"https://images.pokemontcg.io/ex5/100_hires.png"}',
    searchName: 'Vileplume ex (HL 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Wigglytuff ex',
    tcgApiId: 'ex5-101',
    number: '101',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/101.png","large":"https://images.pokemontcg.io/ex5/101_hires.png"}',
    searchName: 'Wigglytuff ex (HL 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex5',
    name: 'Groudon',
    tcgApiId: 'ex5-102',
    number: '102',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ex5/102.png","large":"https://images.pokemontcg.io/ex5/102_hires.png"}',
    searchName: 'Groudon (HL 102)',
  },
];
