export const cardSeedEx6 = [
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Beedrill',
    tcgApiId: 'ex6-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/1.png","large":"https://images.pokemontcg.io/ex6/1_hires.png"}',
    searchName: 'Beedrill (RG 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Butterfree',
    tcgApiId: 'ex6-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/2.png","large":"https://images.pokemontcg.io/ex6/2_hires.png"}',
    searchName: 'Butterfree (RG 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Dewgong',
    tcgApiId: 'ex6-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/3.png","large":"https://images.pokemontcg.io/ex6/3_hires.png"}',
    searchName: 'Dewgong (RG 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Ditto',
    tcgApiId: 'ex6-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/4.png","large":"https://images.pokemontcg.io/ex6/4_hires.png"}',
    searchName: 'Ditto (RG 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Exeggutor',
    tcgApiId: 'ex6-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/5.png","large":"https://images.pokemontcg.io/ex6/5_hires.png"}',
    searchName: 'Exeggutor (RG 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Kangaskhan',
    tcgApiId: 'ex6-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/6.png","large":"https://images.pokemontcg.io/ex6/6_hires.png"}',
    searchName: 'Kangaskhan (RG 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Marowak',
    tcgApiId: 'ex6-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/7.png","large":"https://images.pokemontcg.io/ex6/7_hires.png"}',
    searchName: 'Marowak (RG 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Nidoking',
    tcgApiId: 'ex6-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/8.png","large":"https://images.pokemontcg.io/ex6/8_hires.png"}',
    searchName: 'Nidoking (RG 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Nidoqueen',
    tcgApiId: 'ex6-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/9.png","large":"https://images.pokemontcg.io/ex6/9_hires.png"}',
    searchName: 'Nidoqueen (RG 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Pidgeot',
    tcgApiId: 'ex6-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/10.png","large":"https://images.pokemontcg.io/ex6/10_hires.png"}',
    searchName: 'Pidgeot (RG 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Poliwrath',
    tcgApiId: 'ex6-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/11.png","large":"https://images.pokemontcg.io/ex6/11_hires.png"}',
    searchName: 'Poliwrath (RG 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Raichu',
    tcgApiId: 'ex6-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/12.png","large":"https://images.pokemontcg.io/ex6/12_hires.png"}',
    searchName: 'Raichu (RG 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Rapidash',
    tcgApiId: 'ex6-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/13.png","large":"https://images.pokemontcg.io/ex6/13_hires.png"}',
    searchName: 'Rapidash (RG 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Slowbro',
    tcgApiId: 'ex6-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/14.png","large":"https://images.pokemontcg.io/ex6/14_hires.png"}',
    searchName: 'Slowbro (RG 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Snorlax',
    tcgApiId: 'ex6-15',
    number: '15',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/15.png","large":"https://images.pokemontcg.io/ex6/15_hires.png"}',
    searchName: 'Snorlax (RG 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Tauros',
    tcgApiId: 'ex6-16',
    number: '16',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/16.png","large":"https://images.pokemontcg.io/ex6/16_hires.png"}',
    searchName: 'Tauros (RG 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Victreebel',
    tcgApiId: 'ex6-17',
    number: '17',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/17.png","large":"https://images.pokemontcg.io/ex6/17_hires.png"}',
    searchName: 'Victreebel (RG 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Arcanine',
    tcgApiId: 'ex6-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/18.png","large":"https://images.pokemontcg.io/ex6/18_hires.png"}',
    searchName: 'Arcanine (RG 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Chansey',
    tcgApiId: 'ex6-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/19.png","large":"https://images.pokemontcg.io/ex6/19_hires.png"}',
    searchName: 'Chansey (RG 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Cloyster',
    tcgApiId: 'ex6-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/20.png","large":"https://images.pokemontcg.io/ex6/20_hires.png"}',
    searchName: 'Cloyster (RG 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Dodrio',
    tcgApiId: 'ex6-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/21.png","large":"https://images.pokemontcg.io/ex6/21_hires.png"}',
    searchName: 'Dodrio (RG 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Dugtrio',
    tcgApiId: 'ex6-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/22.png","large":"https://images.pokemontcg.io/ex6/22_hires.png"}',
    searchName: 'Dugtrio (RG 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: "Farfetch'd",
    tcgApiId: 'ex6-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/23.png","large":"https://images.pokemontcg.io/ex6/23_hires.png"}',
    searchName: "Farfetch'd (RG 23)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Fearow',
    tcgApiId: 'ex6-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/24.png","large":"https://images.pokemontcg.io/ex6/24_hires.png"}',
    searchName: 'Fearow (RG 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Hypno',
    tcgApiId: 'ex6-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/25.png","large":"https://images.pokemontcg.io/ex6/25_hires.png"}',
    searchName: 'Hypno (RG 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Kingler',
    tcgApiId: 'ex6-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/26.png","large":"https://images.pokemontcg.io/ex6/26_hires.png"}',
    searchName: 'Kingler (RG 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Magneton',
    tcgApiId: 'ex6-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/27.png","large":"https://images.pokemontcg.io/ex6/27_hires.png"}',
    searchName: 'Magneton (RG 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Primeape',
    tcgApiId: 'ex6-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/28.png","large":"https://images.pokemontcg.io/ex6/28_hires.png"}',
    searchName: 'Primeape (RG 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Scyther',
    tcgApiId: 'ex6-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/29.png","large":"https://images.pokemontcg.io/ex6/29_hires.png"}',
    searchName: 'Scyther (RG 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Tangela',
    tcgApiId: 'ex6-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/30.png","large":"https://images.pokemontcg.io/ex6/30_hires.png"}',
    searchName: 'Tangela (RG 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Charmeleon',
    tcgApiId: 'ex6-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/31.png","large":"https://images.pokemontcg.io/ex6/31_hires.png"}',
    searchName: 'Charmeleon (RG 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Drowzee',
    tcgApiId: 'ex6-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/32.png","large":"https://images.pokemontcg.io/ex6/32_hires.png"}',
    searchName: 'Drowzee (RG 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Exeggcute',
    tcgApiId: 'ex6-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/33.png","large":"https://images.pokemontcg.io/ex6/33_hires.png"}',
    searchName: 'Exeggcute (RG 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Haunter',
    tcgApiId: 'ex6-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/34.png","large":"https://images.pokemontcg.io/ex6/34_hires.png"}',
    searchName: 'Haunter (RG 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Ivysaur',
    tcgApiId: 'ex6-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/35.png","large":"https://images.pokemontcg.io/ex6/35_hires.png"}',
    searchName: 'Ivysaur (RG 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Kakuna',
    tcgApiId: 'ex6-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/36.png","large":"https://images.pokemontcg.io/ex6/36_hires.png"}',
    searchName: 'Kakuna (RG 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Lickitung',
    tcgApiId: 'ex6-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/37.png","large":"https://images.pokemontcg.io/ex6/37_hires.png"}',
    searchName: 'Lickitung (RG 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Mankey',
    tcgApiId: 'ex6-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/38.png","large":"https://images.pokemontcg.io/ex6/38_hires.png"}',
    searchName: 'Mankey (RG 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Metapod',
    tcgApiId: 'ex6-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/39.png","large":"https://images.pokemontcg.io/ex6/39_hires.png"}',
    searchName: 'Metapod (RG 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Nidorina',
    tcgApiId: 'ex6-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/40.png","large":"https://images.pokemontcg.io/ex6/40_hires.png"}',
    searchName: 'Nidorina (RG 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Nidorino',
    tcgApiId: 'ex6-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/41.png","large":"https://images.pokemontcg.io/ex6/41_hires.png"}',
    searchName: 'Nidorino (RG 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Onix',
    tcgApiId: 'ex6-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/42.png","large":"https://images.pokemontcg.io/ex6/42_hires.png"}',
    searchName: 'Onix (RG 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Parasect',
    tcgApiId: 'ex6-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/43.png","large":"https://images.pokemontcg.io/ex6/43_hires.png"}',
    searchName: 'Parasect (RG 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Persian',
    tcgApiId: 'ex6-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/44.png","large":"https://images.pokemontcg.io/ex6/44_hires.png"}',
    searchName: 'Persian (RG 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Pidgeotto',
    tcgApiId: 'ex6-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/45.png","large":"https://images.pokemontcg.io/ex6/45_hires.png"}',
    searchName: 'Pidgeotto (RG 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Poliwhirl',
    tcgApiId: 'ex6-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/46.png","large":"https://images.pokemontcg.io/ex6/46_hires.png"}',
    searchName: 'Poliwhirl (RG 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Porygon',
    tcgApiId: 'ex6-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/47.png","large":"https://images.pokemontcg.io/ex6/47_hires.png"}',
    searchName: 'Porygon (RG 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Raticate',
    tcgApiId: 'ex6-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/48.png","large":"https://images.pokemontcg.io/ex6/48_hires.png"}',
    searchName: 'Raticate (RG 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Venomoth',
    tcgApiId: 'ex6-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/49.png","large":"https://images.pokemontcg.io/ex6/49_hires.png"}',
    searchName: 'Venomoth (RG 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Wartortle',
    tcgApiId: 'ex6-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/50.png","large":"https://images.pokemontcg.io/ex6/50_hires.png"}',
    searchName: 'Wartortle (RG 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Weepinbell',
    tcgApiId: 'ex6-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/51.png","large":"https://images.pokemontcg.io/ex6/51_hires.png"}',
    searchName: 'Weepinbell (RG 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Wigglytuff',
    tcgApiId: 'ex6-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/52.png","large":"https://images.pokemontcg.io/ex6/52_hires.png"}',
    searchName: 'Wigglytuff (RG 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Bellsprout',
    tcgApiId: 'ex6-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/53.png","large":"https://images.pokemontcg.io/ex6/53_hires.png"}',
    searchName: 'Bellsprout (RG 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Bulbasaur',
    tcgApiId: 'ex6-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/54.png","large":"https://images.pokemontcg.io/ex6/54_hires.png"}',
    searchName: 'Bulbasaur (RG 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Bulbasaur',
    tcgApiId: 'ex6-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/55.png","large":"https://images.pokemontcg.io/ex6/55_hires.png"}',
    searchName: 'Bulbasaur (RG 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Caterpie',
    tcgApiId: 'ex6-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/56.png","large":"https://images.pokemontcg.io/ex6/56_hires.png"}',
    searchName: 'Caterpie (RG 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Charmander',
    tcgApiId: 'ex6-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/57.png","large":"https://images.pokemontcg.io/ex6/57_hires.png"}',
    searchName: 'Charmander (RG 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Charmander',
    tcgApiId: 'ex6-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/58.png","large":"https://images.pokemontcg.io/ex6/58_hires.png"}',
    searchName: 'Charmander (RG 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Clefairy',
    tcgApiId: 'ex6-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/59.png","large":"https://images.pokemontcg.io/ex6/59_hires.png"}',
    searchName: 'Clefairy (RG 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Cubone',
    tcgApiId: 'ex6-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/60.png","large":"https://images.pokemontcg.io/ex6/60_hires.png"}',
    searchName: 'Cubone (RG 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Diglett',
    tcgApiId: 'ex6-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/61.png","large":"https://images.pokemontcg.io/ex6/61_hires.png"}',
    searchName: 'Diglett (RG 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Doduo',
    tcgApiId: 'ex6-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/62.png","large":"https://images.pokemontcg.io/ex6/62_hires.png"}',
    searchName: 'Doduo (RG 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Gastly',
    tcgApiId: 'ex6-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/63.png","large":"https://images.pokemontcg.io/ex6/63_hires.png"}',
    searchName: 'Gastly (RG 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Growlithe',
    tcgApiId: 'ex6-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/64.png","large":"https://images.pokemontcg.io/ex6/64_hires.png"}',
    searchName: 'Growlithe (RG 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Jigglypuff',
    tcgApiId: 'ex6-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/65.png","large":"https://images.pokemontcg.io/ex6/65_hires.png"}',
    searchName: 'Jigglypuff (RG 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Krabby',
    tcgApiId: 'ex6-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/66.png","large":"https://images.pokemontcg.io/ex6/66_hires.png"}',
    searchName: 'Krabby (RG 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Magikarp',
    tcgApiId: 'ex6-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/67.png","large":"https://images.pokemontcg.io/ex6/67_hires.png"}',
    searchName: 'Magikarp (RG 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Magnemite',
    tcgApiId: 'ex6-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/68.png","large":"https://images.pokemontcg.io/ex6/68_hires.png"}',
    searchName: 'Magnemite (RG 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Meowth',
    tcgApiId: 'ex6-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/69.png","large":"https://images.pokemontcg.io/ex6/69_hires.png"}',
    searchName: 'Meowth (RG 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Nidoran ♀',
    tcgApiId: 'ex6-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/70.png","large":"https://images.pokemontcg.io/ex6/70_hires.png"}',
    searchName: 'Nidoran ♀ (RG 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Nidoran ♂',
    tcgApiId: 'ex6-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/71.png","large":"https://images.pokemontcg.io/ex6/71_hires.png"}',
    searchName: 'Nidoran ♂ (RG 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Paras',
    tcgApiId: 'ex6-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/72.png","large":"https://images.pokemontcg.io/ex6/72_hires.png"}',
    searchName: 'Paras (RG 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Pidgey',
    tcgApiId: 'ex6-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/73.png","large":"https://images.pokemontcg.io/ex6/73_hires.png"}',
    searchName: 'Pidgey (RG 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Pikachu',
    tcgApiId: 'ex6-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/74.png","large":"https://images.pokemontcg.io/ex6/74_hires.png"}',
    searchName: 'Pikachu (RG 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Poliwag',
    tcgApiId: 'ex6-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/75.png","large":"https://images.pokemontcg.io/ex6/75_hires.png"}',
    searchName: 'Poliwag (RG 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Ponyta',
    tcgApiId: 'ex6-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/76.png","large":"https://images.pokemontcg.io/ex6/76_hires.png"}',
    searchName: 'Ponyta (RG 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Rattata',
    tcgApiId: 'ex6-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/77.png","large":"https://images.pokemontcg.io/ex6/77_hires.png"}',
    searchName: 'Rattata (RG 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Seel',
    tcgApiId: 'ex6-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/78.png","large":"https://images.pokemontcg.io/ex6/78_hires.png"}',
    searchName: 'Seel (RG 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Shellder',
    tcgApiId: 'ex6-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/79.png","large":"https://images.pokemontcg.io/ex6/79_hires.png"}',
    searchName: 'Shellder (RG 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Slowpoke',
    tcgApiId: 'ex6-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/80.png","large":"https://images.pokemontcg.io/ex6/80_hires.png"}',
    searchName: 'Slowpoke (RG 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Spearow',
    tcgApiId: 'ex6-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/81.png","large":"https://images.pokemontcg.io/ex6/81_hires.png"}',
    searchName: 'Spearow (RG 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Squirtle',
    tcgApiId: 'ex6-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/82.png","large":"https://images.pokemontcg.io/ex6/82_hires.png"}',
    searchName: 'Squirtle (RG 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Squirtle',
    tcgApiId: 'ex6-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/83.png","large":"https://images.pokemontcg.io/ex6/83_hires.png"}',
    searchName: 'Squirtle (RG 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Venonat',
    tcgApiId: 'ex6-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/84.png","large":"https://images.pokemontcg.io/ex6/84_hires.png"}',
    searchName: 'Venonat (RG 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Voltorb',
    tcgApiId: 'ex6-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/85.png","large":"https://images.pokemontcg.io/ex6/85_hires.png"}',
    searchName: 'Voltorb (RG 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Weedle',
    tcgApiId: 'ex6-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/86.png","large":"https://images.pokemontcg.io/ex6/86_hires.png"}',
    searchName: 'Weedle (RG 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: "Bill's Maintenance",
    tcgApiId: 'ex6-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/87.png","large":"https://images.pokemontcg.io/ex6/87_hires.png"}',
    searchName: "Bill's Maintenance (RG 87)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: "Celio's Network",
    tcgApiId: 'ex6-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/88.png","large":"https://images.pokemontcg.io/ex6/88_hires.png"}',
    searchName: "Celio's Network (RG 88)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Energy Removal 2',
    tcgApiId: 'ex6-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/89.png","large":"https://images.pokemontcg.io/ex6/89_hires.png"}',
    searchName: 'Energy Removal 2 (RG 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Energy Switch',
    tcgApiId: 'ex6-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/90.png","large":"https://images.pokemontcg.io/ex6/90_hires.png"}',
    searchName: 'Energy Switch (RG 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'EXP.ALL',
    tcgApiId: 'ex6-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/91.png","large":"https://images.pokemontcg.io/ex6/91_hires.png"}',
    searchName: 'EXP.ALL (RG 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Great Ball',
    tcgApiId: 'ex6-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/92.png","large":"https://images.pokemontcg.io/ex6/92_hires.png"}',
    searchName: 'Great Ball (RG 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Life Herb',
    tcgApiId: 'ex6-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/93.png","large":"https://images.pokemontcg.io/ex6/93_hires.png"}',
    searchName: 'Life Herb (RG 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Mt. Moon',
    tcgApiId: 'ex6-94',
    number: '94',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/94.png","large":"https://images.pokemontcg.io/ex6/94_hires.png"}',
    searchName: 'Mt. Moon (RG 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Poké Ball',
    tcgApiId: 'ex6-95',
    number: '95',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/95.png","large":"https://images.pokemontcg.io/ex6/95_hires.png"}',
    searchName: 'Poké Ball (RG 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'PokéDex HANDY909',
    tcgApiId: 'ex6-96',
    number: '96',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/96.png","large":"https://images.pokemontcg.io/ex6/96_hires.png"}',
    searchName: 'PokéDex HANDY909 (RG 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Pokémon Reversal',
    tcgApiId: 'ex6-97',
    number: '97',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/97.png","large":"https://images.pokemontcg.io/ex6/97_hires.png"}',
    searchName: 'Pokémon Reversal (RG 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: "Prof. Oak's Research",
    tcgApiId: 'ex6-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/98.png","large":"https://images.pokemontcg.io/ex6/98_hires.png"}',
    searchName: "Prof. Oak's Research (RG 98)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Super Scoop Up',
    tcgApiId: 'ex6-99',
    number: '99',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/99.png","large":"https://images.pokemontcg.io/ex6/99_hires.png"}',
    searchName: 'Super Scoop Up (RG 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'VS Seeker',
    tcgApiId: 'ex6-100',
    number: '100',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/100.png","large":"https://images.pokemontcg.io/ex6/100_hires.png"}',
    searchName: 'VS Seeker (RG 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Potion',
    tcgApiId: 'ex6-101',
    number: '101',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/101.png","large":"https://images.pokemontcg.io/ex6/101_hires.png"}',
    searchName: 'Potion (RG 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Switch',
    tcgApiId: 'ex6-102',
    number: '102',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/102.png","large":"https://images.pokemontcg.io/ex6/102_hires.png"}',
    searchName: 'Switch (RG 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Multi Energy',
    tcgApiId: 'ex6-103',
    number: '103',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/103.png","large":"https://images.pokemontcg.io/ex6/103_hires.png"}',
    searchName: 'Multi Energy (RG 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Blastoise ex',
    tcgApiId: 'ex6-104',
    number: '104',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/104.png","large":"https://images.pokemontcg.io/ex6/104_hires.png"}',
    searchName: 'Blastoise ex (RG 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Charizard ex',
    tcgApiId: 'ex6-105',
    number: '105',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/105.png","large":"https://images.pokemontcg.io/ex6/105_hires.png"}',
    searchName: 'Charizard ex (RG 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Clefable ex',
    tcgApiId: 'ex6-106',
    number: '106',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/106.png","large":"https://images.pokemontcg.io/ex6/106_hires.png"}',
    searchName: 'Clefable ex (RG 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Electrode ex',
    tcgApiId: 'ex6-107',
    number: '107',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/107.png","large":"https://images.pokemontcg.io/ex6/107_hires.png"}',
    searchName: 'Electrode ex (RG 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Gengar ex',
    tcgApiId: 'ex6-108',
    number: '108',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/108.png","large":"https://images.pokemontcg.io/ex6/108_hires.png"}',
    searchName: 'Gengar ex (RG 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Gyarados ex',
    tcgApiId: 'ex6-109',
    number: '109',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/109.png","large":"https://images.pokemontcg.io/ex6/109_hires.png"}',
    searchName: 'Gyarados ex (RG 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Mr. Mime ex',
    tcgApiId: 'ex6-110',
    number: '110',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/110.png","large":"https://images.pokemontcg.io/ex6/110_hires.png"}',
    searchName: 'Mr. Mime ex (RG 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Mr. Mime ex',
    tcgApiId: 'ex6-111',
    number: '111',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/111.png","large":"https://images.pokemontcg.io/ex6/111_hires.png"}',
    searchName: 'Mr. Mime ex (RG 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Venusaur ex',
    tcgApiId: 'ex6-112',
    number: '112',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/112.png","large":"https://images.pokemontcg.io/ex6/112_hires.png"}',
    searchName: 'Venusaur ex (RG 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Charmander',
    tcgApiId: 'ex6-113',
    number: '113',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/113.png","large":"https://images.pokemontcg.io/ex6/113_hires.png"}',
    searchName: 'Charmander (RG 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Articuno ex',
    tcgApiId: 'ex6-114',
    number: '114',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/114.png","large":"https://images.pokemontcg.io/ex6/114_hires.png"}',
    searchName: 'Articuno ex (RG 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Moltres ex',
    tcgApiId: 'ex6-115',
    number: '115',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/115.png","large":"https://images.pokemontcg.io/ex6/115_hires.png"}',
    searchName: 'Moltres ex (RG 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex6',
    name: 'Zapdos ex',
    tcgApiId: 'ex6-116',
    number: '116',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ex6/116.png","large":"https://images.pokemontcg.io/ex6/116_hires.png"}',
    searchName: 'Zapdos ex (RG 116)',
  },
];
