export const cardSeedEx7 = [
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Azumarill',
    tcgApiId: 'ex7-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/1.png","large":"https://images.pokemontcg.io/ex7/1_hires.png"}',
    searchName: 'Azumarill (TRR 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Ampharos',
    tcgApiId: 'ex7-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/2.png","large":"https://images.pokemontcg.io/ex7/2_hires.png"}',
    searchName: 'Dark Ampharos (TRR 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Crobat',
    tcgApiId: 'ex7-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/3.png","large":"https://images.pokemontcg.io/ex7/3_hires.png"}',
    searchName: 'Dark Crobat (TRR 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Electrode',
    tcgApiId: 'ex7-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/4.png","large":"https://images.pokemontcg.io/ex7/4_hires.png"}',
    searchName: 'Dark Electrode (TRR 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Houndoom',
    tcgApiId: 'ex7-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/5.png","large":"https://images.pokemontcg.io/ex7/5_hires.png"}',
    searchName: 'Dark Houndoom (TRR 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Hypno',
    tcgApiId: 'ex7-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/6.png","large":"https://images.pokemontcg.io/ex7/6_hires.png"}',
    searchName: 'Dark Hypno (TRR 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Marowak',
    tcgApiId: 'ex7-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/7.png","large":"https://images.pokemontcg.io/ex7/7_hires.png"}',
    searchName: 'Dark Marowak (TRR 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Octillery',
    tcgApiId: 'ex7-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/8.png","large":"https://images.pokemontcg.io/ex7/8_hires.png"}',
    searchName: 'Dark Octillery (TRR 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Slowking',
    tcgApiId: 'ex7-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/9.png","large":"https://images.pokemontcg.io/ex7/9_hires.png"}',
    searchName: 'Dark Slowking (TRR 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Steelix',
    tcgApiId: 'ex7-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/10.png","large":"https://images.pokemontcg.io/ex7/10_hires.png"}',
    searchName: 'Dark Steelix (TRR 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Jumpluff',
    tcgApiId: 'ex7-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/11.png","large":"https://images.pokemontcg.io/ex7/11_hires.png"}',
    searchName: 'Jumpluff (TRR 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Kingdra',
    tcgApiId: 'ex7-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/12.png","large":"https://images.pokemontcg.io/ex7/12_hires.png"}',
    searchName: 'Kingdra (TRR 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Piloswine',
    tcgApiId: 'ex7-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/13.png","large":"https://images.pokemontcg.io/ex7/13_hires.png"}',
    searchName: 'Piloswine (TRR 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Togetic',
    tcgApiId: 'ex7-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/14.png","large":"https://images.pokemontcg.io/ex7/14_hires.png"}',
    searchName: 'Togetic (TRR 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Dragonite',
    tcgApiId: 'ex7-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/15.png","large":"https://images.pokemontcg.io/ex7/15_hires.png"}',
    searchName: 'Dark Dragonite (TRR 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Muk',
    tcgApiId: 'ex7-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/16.png","large":"https://images.pokemontcg.io/ex7/16_hires.png"}',
    searchName: 'Dark Muk (TRR 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Raticate',
    tcgApiId: 'ex7-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/17.png","large":"https://images.pokemontcg.io/ex7/17_hires.png"}',
    searchName: 'Dark Raticate (TRR 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Sandslash',
    tcgApiId: 'ex7-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/18.png","large":"https://images.pokemontcg.io/ex7/18_hires.png"}',
    searchName: 'Dark Sandslash (TRR 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Tyranitar',
    tcgApiId: 'ex7-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/19.png","large":"https://images.pokemontcg.io/ex7/19_hires.png"}',
    searchName: 'Dark Tyranitar (TRR 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Tyranitar',
    tcgApiId: 'ex7-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/20.png","large":"https://images.pokemontcg.io/ex7/20_hires.png"}',
    searchName: 'Dark Tyranitar (TRR 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Delibird',
    tcgApiId: 'ex7-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/21.png","large":"https://images.pokemontcg.io/ex7/21_hires.png"}',
    searchName: 'Delibird (TRR 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Furret',
    tcgApiId: 'ex7-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/22.png","large":"https://images.pokemontcg.io/ex7/22_hires.png"}',
    searchName: 'Furret (TRR 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Ledian',
    tcgApiId: 'ex7-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/23.png","large":"https://images.pokemontcg.io/ex7/23_hires.png"}',
    searchName: 'Ledian (TRR 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Magby',
    tcgApiId: 'ex7-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/24.png","large":"https://images.pokemontcg.io/ex7/24_hires.png"}',
    searchName: 'Magby (TRR 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Misdreavus',
    tcgApiId: 'ex7-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/25.png","large":"https://images.pokemontcg.io/ex7/25_hires.png"}',
    searchName: 'Misdreavus (TRR 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Quagsire',
    tcgApiId: 'ex7-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/26.png","large":"https://images.pokemontcg.io/ex7/26_hires.png"}',
    searchName: 'Quagsire (TRR 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Qwilfish',
    tcgApiId: 'ex7-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/27.png","large":"https://images.pokemontcg.io/ex7/27_hires.png"}',
    searchName: 'Qwilfish (TRR 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Yanma',
    tcgApiId: 'ex7-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/28.png","large":"https://images.pokemontcg.io/ex7/28_hires.png"}',
    searchName: 'Yanma (TRR 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Arbok',
    tcgApiId: 'ex7-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/29.png","large":"https://images.pokemontcg.io/ex7/29_hires.png"}',
    searchName: 'Dark Arbok (TRR 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Ariados',
    tcgApiId: 'ex7-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/30.png","large":"https://images.pokemontcg.io/ex7/30_hires.png"}',
    searchName: 'Dark Ariados (TRR 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Dragonair',
    tcgApiId: 'ex7-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/31.png","large":"https://images.pokemontcg.io/ex7/31_hires.png"}',
    searchName: 'Dark Dragonair (TRR 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Dragonair',
    tcgApiId: 'ex7-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/32.png","large":"https://images.pokemontcg.io/ex7/32_hires.png"}',
    searchName: 'Dark Dragonair (TRR 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Flaaffy',
    tcgApiId: 'ex7-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/33.png","large":"https://images.pokemontcg.io/ex7/33_hires.png"}',
    searchName: 'Dark Flaaffy (TRR 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Golbat',
    tcgApiId: 'ex7-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/34.png","large":"https://images.pokemontcg.io/ex7/34_hires.png"}',
    searchName: 'Dark Golbat (TRR 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Golduck',
    tcgApiId: 'ex7-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/35.png","large":"https://images.pokemontcg.io/ex7/35_hires.png"}',
    searchName: 'Dark Golduck (TRR 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Gyarados',
    tcgApiId: 'ex7-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/36.png","large":"https://images.pokemontcg.io/ex7/36_hires.png"}',
    searchName: 'Dark Gyarados (TRR 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Houndoom',
    tcgApiId: 'ex7-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/37.png","large":"https://images.pokemontcg.io/ex7/37_hires.png"}',
    searchName: 'Dark Houndoom (TRR 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Magcargo',
    tcgApiId: 'ex7-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/38.png","large":"https://images.pokemontcg.io/ex7/38_hires.png"}',
    searchName: 'Dark Magcargo (TRR 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Magneton',
    tcgApiId: 'ex7-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/39.png","large":"https://images.pokemontcg.io/ex7/39_hires.png"}',
    searchName: 'Dark Magneton (TRR 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Pupitar',
    tcgApiId: 'ex7-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/40.png","large":"https://images.pokemontcg.io/ex7/40_hires.png"}',
    searchName: 'Dark Pupitar (TRR 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Pupitar',
    tcgApiId: 'ex7-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/41.png","large":"https://images.pokemontcg.io/ex7/41_hires.png"}',
    searchName: 'Dark Pupitar (TRR 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Weezing',
    tcgApiId: 'ex7-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/42.png","large":"https://images.pokemontcg.io/ex7/42_hires.png"}',
    searchName: 'Dark Weezing (TRR 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Heracross',
    tcgApiId: 'ex7-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/43.png","large":"https://images.pokemontcg.io/ex7/43_hires.png"}',
    searchName: 'Heracross (TRR 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Magmar',
    tcgApiId: 'ex7-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/44.png","large":"https://images.pokemontcg.io/ex7/44_hires.png"}',
    searchName: 'Magmar (TRR 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Mantine',
    tcgApiId: 'ex7-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/45.png","large":"https://images.pokemontcg.io/ex7/45_hires.png"}',
    searchName: 'Mantine (TRR 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Meowth",
    tcgApiId: 'ex7-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/46.png","large":"https://images.pokemontcg.io/ex7/46_hires.png"}',
    searchName: "Rocket's Meowth (TRR 46)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Wobbuffet",
    tcgApiId: 'ex7-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/47.png","large":"https://images.pokemontcg.io/ex7/47_hires.png"}',
    searchName: "Rocket's Wobbuffet (TRR 47)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Seadra',
    tcgApiId: 'ex7-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/48.png","large":"https://images.pokemontcg.io/ex7/48_hires.png"}',
    searchName: 'Seadra (TRR 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Skiploom',
    tcgApiId: 'ex7-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/49.png","large":"https://images.pokemontcg.io/ex7/49_hires.png"}',
    searchName: 'Skiploom (TRR 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Togepi',
    tcgApiId: 'ex7-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/50.png","large":"https://images.pokemontcg.io/ex7/50_hires.png"}',
    searchName: 'Togepi (TRR 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Cubone',
    tcgApiId: 'ex7-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/51.png","large":"https://images.pokemontcg.io/ex7/51_hires.png"}',
    searchName: 'Cubone (TRR 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dratini',
    tcgApiId: 'ex7-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/52.png","large":"https://images.pokemontcg.io/ex7/52_hires.png"}',
    searchName: 'Dratini (TRR 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dratini',
    tcgApiId: 'ex7-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/53.png","large":"https://images.pokemontcg.io/ex7/53_hires.png"}',
    searchName: 'Dratini (TRR 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Drowzee',
    tcgApiId: 'ex7-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/54.png","large":"https://images.pokemontcg.io/ex7/54_hires.png"}',
    searchName: 'Drowzee (TRR 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Ekans',
    tcgApiId: 'ex7-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/55.png","large":"https://images.pokemontcg.io/ex7/55_hires.png"}',
    searchName: 'Ekans (TRR 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Grimer',
    tcgApiId: 'ex7-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/56.png","large":"https://images.pokemontcg.io/ex7/56_hires.png"}',
    searchName: 'Grimer (TRR 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Hoppip',
    tcgApiId: 'ex7-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/57.png","large":"https://images.pokemontcg.io/ex7/57_hires.png"}',
    searchName: 'Hoppip (TRR 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Horsea',
    tcgApiId: 'ex7-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/58.png","large":"https://images.pokemontcg.io/ex7/58_hires.png"}',
    searchName: 'Horsea (TRR 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Houndour',
    tcgApiId: 'ex7-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/59.png","large":"https://images.pokemontcg.io/ex7/59_hires.png"}',
    searchName: 'Houndour (TRR 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Houndour',
    tcgApiId: 'ex7-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/60.png","large":"https://images.pokemontcg.io/ex7/60_hires.png"}',
    searchName: 'Houndour (TRR 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Koffing',
    tcgApiId: 'ex7-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/61.png","large":"https://images.pokemontcg.io/ex7/61_hires.png"}',
    searchName: 'Koffing (TRR 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Larvitar',
    tcgApiId: 'ex7-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/62.png","large":"https://images.pokemontcg.io/ex7/62_hires.png"}',
    searchName: 'Larvitar (TRR 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Larvitar',
    tcgApiId: 'ex7-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/63.png","large":"https://images.pokemontcg.io/ex7/63_hires.png"}',
    searchName: 'Larvitar (TRR 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Ledyba',
    tcgApiId: 'ex7-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/64.png","large":"https://images.pokemontcg.io/ex7/64_hires.png"}',
    searchName: 'Ledyba (TRR 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Magikarp',
    tcgApiId: 'ex7-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/65.png","large":"https://images.pokemontcg.io/ex7/65_hires.png"}',
    searchName: 'Magikarp (TRR 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Magnemite',
    tcgApiId: 'ex7-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/66.png","large":"https://images.pokemontcg.io/ex7/66_hires.png"}',
    searchName: 'Magnemite (TRR 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Mareep',
    tcgApiId: 'ex7-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/67.png","large":"https://images.pokemontcg.io/ex7/67_hires.png"}',
    searchName: 'Mareep (TRR 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Marill',
    tcgApiId: 'ex7-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/68.png","large":"https://images.pokemontcg.io/ex7/68_hires.png"}',
    searchName: 'Marill (TRR 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Onix',
    tcgApiId: 'ex7-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/69.png","large":"https://images.pokemontcg.io/ex7/69_hires.png"}',
    searchName: 'Onix (TRR 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Psyduck',
    tcgApiId: 'ex7-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/70.png","large":"https://images.pokemontcg.io/ex7/70_hires.png"}',
    searchName: 'Psyduck (TRR 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Rattata',
    tcgApiId: 'ex7-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/71.png","large":"https://images.pokemontcg.io/ex7/71_hires.png"}',
    searchName: 'Rattata (TRR 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Rattata',
    tcgApiId: 'ex7-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/72.png","large":"https://images.pokemontcg.io/ex7/72_hires.png"}',
    searchName: 'Rattata (TRR 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Remoraid',
    tcgApiId: 'ex7-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/73.png","large":"https://images.pokemontcg.io/ex7/73_hires.png"}',
    searchName: 'Remoraid (TRR 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Sandshrew',
    tcgApiId: 'ex7-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/74.png","large":"https://images.pokemontcg.io/ex7/74_hires.png"}',
    searchName: 'Sandshrew (TRR 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Sentret',
    tcgApiId: 'ex7-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/75.png","large":"https://images.pokemontcg.io/ex7/75_hires.png"}',
    searchName: 'Sentret (TRR 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Slowpoke',
    tcgApiId: 'ex7-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/76.png","large":"https://images.pokemontcg.io/ex7/76_hires.png"}',
    searchName: 'Slowpoke (TRR 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Slugma',
    tcgApiId: 'ex7-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/77.png","large":"https://images.pokemontcg.io/ex7/77_hires.png"}',
    searchName: 'Slugma (TRR 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Spinarak',
    tcgApiId: 'ex7-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/78.png","large":"https://images.pokemontcg.io/ex7/78_hires.png"}',
    searchName: 'Spinarak (TRR 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Swinub',
    tcgApiId: 'ex7-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/79.png","large":"https://images.pokemontcg.io/ex7/79_hires.png"}',
    searchName: 'Swinub (TRR 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Voltorb',
    tcgApiId: 'ex7-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/80.png","large":"https://images.pokemontcg.io/ex7/80_hires.png"}',
    searchName: 'Voltorb (TRR 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Wooper',
    tcgApiId: 'ex7-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/81.png","large":"https://images.pokemontcg.io/ex7/81_hires.png"}',
    searchName: 'Wooper (TRR 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Zubat',
    tcgApiId: 'ex7-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/82.png","large":"https://images.pokemontcg.io/ex7/82_hires.png"}',
    searchName: 'Zubat (TRR 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Copycat',
    tcgApiId: 'ex7-83',
    number: '83',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/83.png","large":"https://images.pokemontcg.io/ex7/83_hires.png"}',
    searchName: 'Copycat (TRR 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Pokémon Retriever',
    tcgApiId: 'ex7-84',
    number: '84',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/84.png","large":"https://images.pokemontcg.io/ex7/84_hires.png"}',
    searchName: 'Pokémon Retriever (TRR 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Pow! Hand Extension',
    tcgApiId: 'ex7-85',
    number: '85',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/85.png","large":"https://images.pokemontcg.io/ex7/85_hires.png"}',
    searchName: 'Pow! Hand Extension (TRR 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Admin.",
    tcgApiId: 'ex7-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/86.png","large":"https://images.pokemontcg.io/ex7/86_hires.png"}',
    searchName: "Rocket's Admin. (TRR 86)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Hideout",
    tcgApiId: 'ex7-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/87.png","large":"https://images.pokemontcg.io/ex7/87_hires.png"}',
    searchName: "Rocket's Hideout (TRR 87)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Mission",
    tcgApiId: 'ex7-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/88.png","large":"https://images.pokemontcg.io/ex7/88_hires.png"}',
    searchName: "Rocket's Mission (TRR 88)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Poké Ball",
    tcgApiId: 'ex7-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/89.png","large":"https://images.pokemontcg.io/ex7/89_hires.png"}',
    searchName: "Rocket's Poké Ball (TRR 89)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Tricky Gym",
    tcgApiId: 'ex7-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/90.png","large":"https://images.pokemontcg.io/ex7/90_hires.png"}',
    searchName: "Rocket's Tricky Gym (TRR 90)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Surprise! Time Machine',
    tcgApiId: 'ex7-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/91.png","large":"https://images.pokemontcg.io/ex7/91_hires.png"}',
    searchName: 'Surprise! Time Machine (TRR 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Swoop! Teleporter',
    tcgApiId: 'ex7-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/92.png","large":"https://images.pokemontcg.io/ex7/92_hires.png"}',
    searchName: 'Swoop! Teleporter (TRR 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Venture Bomb',
    tcgApiId: 'ex7-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/93.png","large":"https://images.pokemontcg.io/ex7/93_hires.png"}',
    searchName: 'Venture Bomb (TRR 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Dark Metal Energy',
    tcgApiId: 'ex7-94',
    number: '94',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/94.png","large":"https://images.pokemontcg.io/ex7/94_hires.png"}',
    searchName: 'Dark Metal Energy (TRR 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'R Energy',
    tcgApiId: 'ex7-95',
    number: '95',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/95.png","large":"https://images.pokemontcg.io/ex7/95_hires.png"}',
    searchName: 'R Energy (TRR 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Articuno ex",
    tcgApiId: 'ex7-96',
    number: '96',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/96.png","large":"https://images.pokemontcg.io/ex7/96_hires.png"}',
    searchName: "Rocket's Articuno ex (TRR 96)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Entei ex",
    tcgApiId: 'ex7-97',
    number: '97',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/97.png","large":"https://images.pokemontcg.io/ex7/97_hires.png"}',
    searchName: "Rocket's Entei ex (TRR 97)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Hitmonchan ex",
    tcgApiId: 'ex7-98',
    number: '98',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/98.png","large":"https://images.pokemontcg.io/ex7/98_hires.png"}',
    searchName: "Rocket's Hitmonchan ex (TRR 98)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Mewtwo ex",
    tcgApiId: 'ex7-99',
    number: '99',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/99.png","large":"https://images.pokemontcg.io/ex7/99_hires.png"}',
    searchName: "Rocket's Mewtwo ex (TRR 99)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Moltres ex",
    tcgApiId: 'ex7-100',
    number: '100',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/100.png","large":"https://images.pokemontcg.io/ex7/100_hires.png"}',
    searchName: "Rocket's Moltres ex (TRR 100)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Scizor ex",
    tcgApiId: 'ex7-101',
    number: '101',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/101.png","large":"https://images.pokemontcg.io/ex7/101_hires.png"}',
    searchName: "Rocket's Scizor ex (TRR 101)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Scyther ex",
    tcgApiId: 'ex7-102',
    number: '102',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/102.png","large":"https://images.pokemontcg.io/ex7/102_hires.png"}',
    searchName: "Rocket's Scyther ex (TRR 102)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Sneasel ex",
    tcgApiId: 'ex7-103',
    number: '103',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/103.png","large":"https://images.pokemontcg.io/ex7/103_hires.png"}',
    searchName: "Rocket's Sneasel ex (TRR 103)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Snorlax ex",
    tcgApiId: 'ex7-104',
    number: '104',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/104.png","large":"https://images.pokemontcg.io/ex7/104_hires.png"}',
    searchName: "Rocket's Snorlax ex (TRR 104)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Suicune ex",
    tcgApiId: 'ex7-105',
    number: '105',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/105.png","large":"https://images.pokemontcg.io/ex7/105_hires.png"}',
    searchName: "Rocket's Suicune ex (TRR 105)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: "Rocket's Zapdos ex",
    tcgApiId: 'ex7-106',
    number: '106',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/106.png","large":"https://images.pokemontcg.io/ex7/106_hires.png"}',
    searchName: "Rocket's Zapdos ex (TRR 106)",
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Mudkip ★',
    tcgApiId: 'ex7-107',
    number: '107',
    rarity: 'Rare Holo Star',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/107.png","large":"https://images.pokemontcg.io/ex7/107_hires.png"}',
    searchName: 'Mudkip ★ (TRR 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Torchic ★',
    tcgApiId: 'ex7-108',
    number: '108',
    rarity: 'Rare Holo Star',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/108.png","large":"https://images.pokemontcg.io/ex7/108_hires.png"}',
    searchName: 'Torchic ★ (TRR 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Treecko ★',
    tcgApiId: 'ex7-109',
    number: '109',
    rarity: 'Rare Holo Star',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/109.png","large":"https://images.pokemontcg.io/ex7/109_hires.png"}',
    searchName: 'Treecko ★ (TRR 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Charmeleon',
    tcgApiId: 'ex7-110',
    number: '110',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/110.png","large":"https://images.pokemontcg.io/ex7/110_hires.png"}',
    searchName: 'Charmeleon (TRR 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'ex7',
    name: 'Here Comes Team Rocket!',
    tcgApiId: 'ex7-111',
    number: '111',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/ex7/111.png","large":"https://images.pokemontcg.io/ex7/111_hires.png"}',
    searchName: 'Here Comes Team Rocket! (TRR 111)',
  },
];
