export const cardSeedGym2 = [
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Arcanine",
    tcgApiId: 'gym2-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/1.png","large":"https://images.pokemontcg.io/gym2/1_hires.png"}',
    searchName: "Blaine's Arcanine (G2 1)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Charizard",
    tcgApiId: 'gym2-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/2.png","large":"https://images.pokemontcg.io/gym2/2_hires.png"}',
    searchName: "Blaine's Charizard (G2 2)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Brock's Ninetales",
    tcgApiId: 'gym2-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/3.png","large":"https://images.pokemontcg.io/gym2/3_hires.png"}',
    searchName: "Brock's Ninetales (G2 3)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Erika's Venusaur",
    tcgApiId: 'gym2-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/4.png","large":"https://images.pokemontcg.io/gym2/4_hires.png"}',
    searchName: "Erika's Venusaur (G2 4)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Gyarados",
    tcgApiId: 'gym2-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/5.png","large":"https://images.pokemontcg.io/gym2/5_hires.png"}',
    searchName: "Giovanni's Gyarados (G2 5)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Machamp",
    tcgApiId: 'gym2-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/6.png","large":"https://images.pokemontcg.io/gym2/6_hires.png"}',
    searchName: "Giovanni's Machamp (G2 6)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Nidoking",
    tcgApiId: 'gym2-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/7.png","large":"https://images.pokemontcg.io/gym2/7_hires.png"}',
    searchName: "Giovanni's Nidoking (G2 7)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Persian",
    tcgApiId: 'gym2-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/8.png","large":"https://images.pokemontcg.io/gym2/8_hires.png"}',
    searchName: "Giovanni's Persian (G2 8)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Beedrill",
    tcgApiId: 'gym2-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/9.png","large":"https://images.pokemontcg.io/gym2/9_hires.png"}',
    searchName: "Koga's Beedrill (G2 9)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Ditto",
    tcgApiId: 'gym2-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/10.png","large":"https://images.pokemontcg.io/gym2/10_hires.png"}',
    searchName: "Koga's Ditto (G2 10)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Lt. Surge's Raichu",
    tcgApiId: 'gym2-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/11.png","large":"https://images.pokemontcg.io/gym2/11_hires.png"}',
    searchName: "Lt. Surge's Raichu (G2 11)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Golduck",
    tcgApiId: 'gym2-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/12.png","large":"https://images.pokemontcg.io/gym2/12_hires.png"}',
    searchName: "Misty's Golduck (G2 12)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Gyarados",
    tcgApiId: 'gym2-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/13.png","large":"https://images.pokemontcg.io/gym2/13_hires.png"}',
    searchName: "Misty's Gyarados (G2 13)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Rocket's Mewtwo",
    tcgApiId: 'gym2-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/14.png","large":"https://images.pokemontcg.io/gym2/14_hires.png"}',
    searchName: "Rocket's Mewtwo (G2 14)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Rocket's Zapdos",
    tcgApiId: 'gym2-15',
    number: '15',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/15.png","large":"https://images.pokemontcg.io/gym2/15_hires.png"}',
    searchName: "Rocket's Zapdos (G2 15)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Alakazam",
    tcgApiId: 'gym2-16',
    number: '16',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/16.png","large":"https://images.pokemontcg.io/gym2/16_hires.png"}',
    searchName: "Sabrina's Alakazam (G2 16)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Blaine',
    tcgApiId: 'gym2-17',
    number: '17',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/17.png","large":"https://images.pokemontcg.io/gym2/17_hires.png"}',
    searchName: 'Blaine (G2 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Giovanni',
    tcgApiId: 'gym2-18',
    number: '18',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/18.png","large":"https://images.pokemontcg.io/gym2/18_hires.png"}',
    searchName: 'Giovanni (G2 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Koga',
    tcgApiId: 'gym2-19',
    number: '19',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/19.png","large":"https://images.pokemontcg.io/gym2/19_hires.png"}',
    searchName: 'Koga (G2 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Sabrina',
    tcgApiId: 'gym2-20',
    number: '20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/20.png","large":"https://images.pokemontcg.io/gym2/20_hires.png"}',
    searchName: 'Sabrina (G2 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Ninetales",
    tcgApiId: 'gym2-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/21.png","large":"https://images.pokemontcg.io/gym2/21_hires.png"}',
    searchName: "Blaine's Ninetales (G2 21)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Brock's Dugtrio",
    tcgApiId: 'gym2-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/22.png","large":"https://images.pokemontcg.io/gym2/22_hires.png"}',
    searchName: "Brock's Dugtrio (G2 22)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Nidoqueen",
    tcgApiId: 'gym2-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/23.png","large":"https://images.pokemontcg.io/gym2/23_hires.png"}',
    searchName: "Giovanni's Nidoqueen (G2 23)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Pinsir",
    tcgApiId: 'gym2-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/24.png","large":"https://images.pokemontcg.io/gym2/24_hires.png"}',
    searchName: "Giovanni's Pinsir (G2 24)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Arbok",
    tcgApiId: 'gym2-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/25.png","large":"https://images.pokemontcg.io/gym2/25_hires.png"}',
    searchName: "Koga's Arbok (G2 25)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Muk",
    tcgApiId: 'gym2-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/26.png","large":"https://images.pokemontcg.io/gym2/26_hires.png"}',
    searchName: "Koga's Muk (G2 26)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Pidgeotto",
    tcgApiId: 'gym2-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/27.png","large":"https://images.pokemontcg.io/gym2/27_hires.png"}',
    searchName: "Koga's Pidgeotto (G2 27)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Lt. Surge's Jolteon",
    tcgApiId: 'gym2-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/28.png","large":"https://images.pokemontcg.io/gym2/28_hires.png"}',
    searchName: "Lt. Surge's Jolteon (G2 28)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Gengar",
    tcgApiId: 'gym2-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/29.png","large":"https://images.pokemontcg.io/gym2/29_hires.png"}',
    searchName: "Sabrina's Gengar (G2 29)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Golduck",
    tcgApiId: 'gym2-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/30.png","large":"https://images.pokemontcg.io/gym2/30_hires.png"}',
    searchName: "Sabrina's Golduck (G2 30)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Charmeleon",
    tcgApiId: 'gym2-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/31.png","large":"https://images.pokemontcg.io/gym2/31_hires.png"}',
    searchName: "Blaine's Charmeleon (G2 31)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Dodrio",
    tcgApiId: 'gym2-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/32.png","large":"https://images.pokemontcg.io/gym2/32_hires.png"}',
    searchName: "Blaine's Dodrio (G2 32)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Rapidash",
    tcgApiId: 'gym2-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/33.png","large":"https://images.pokemontcg.io/gym2/33_hires.png"}',
    searchName: "Blaine's Rapidash (G2 33)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Brock's Graveler",
    tcgApiId: 'gym2-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/34.png","large":"https://images.pokemontcg.io/gym2/34_hires.png"}',
    searchName: "Brock's Graveler (G2 34)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Brock's Primeape",
    tcgApiId: 'gym2-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/35.png","large":"https://images.pokemontcg.io/gym2/35_hires.png"}',
    searchName: "Brock's Primeape (G2 35)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Brock's Sandslash",
    tcgApiId: 'gym2-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/36.png","large":"https://images.pokemontcg.io/gym2/36_hires.png"}',
    searchName: "Brock's Sandslash (G2 36)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Brock's Vulpix",
    tcgApiId: 'gym2-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/37.png","large":"https://images.pokemontcg.io/gym2/37_hires.png"}',
    searchName: "Brock's Vulpix (G2 37)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Erika's Bellsprout",
    tcgApiId: 'gym2-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/38.png","large":"https://images.pokemontcg.io/gym2/38_hires.png"}',
    searchName: "Erika's Bellsprout (G2 38)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Erika's Bulbasaur",
    tcgApiId: 'gym2-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/39.png","large":"https://images.pokemontcg.io/gym2/39_hires.png"}',
    searchName: "Erika's Bulbasaur (G2 39)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Erika's Clefairy",
    tcgApiId: 'gym2-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/40.png","large":"https://images.pokemontcg.io/gym2/40_hires.png"}',
    searchName: "Erika's Clefairy (G2 40)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Erika's Ivysaur",
    tcgApiId: 'gym2-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/41.png","large":"https://images.pokemontcg.io/gym2/41_hires.png"}',
    searchName: "Erika's Ivysaur (G2 41)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Machoke",
    tcgApiId: 'gym2-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/42.png","large":"https://images.pokemontcg.io/gym2/42_hires.png"}',
    searchName: "Giovanni's Machoke (G2 42)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Meowth",
    tcgApiId: 'gym2-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/43.png","large":"https://images.pokemontcg.io/gym2/43_hires.png"}',
    searchName: "Giovanni's Meowth (G2 43)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Nidorina",
    tcgApiId: 'gym2-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/44.png","large":"https://images.pokemontcg.io/gym2/44_hires.png"}',
    searchName: "Giovanni's Nidorina (G2 44)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Nidorino",
    tcgApiId: 'gym2-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/45.png","large":"https://images.pokemontcg.io/gym2/45_hires.png"}',
    searchName: "Giovanni's Nidorino (G2 45)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Golbat",
    tcgApiId: 'gym2-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/46.png","large":"https://images.pokemontcg.io/gym2/46_hires.png"}',
    searchName: "Koga's Golbat (G2 46)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Kakuna",
    tcgApiId: 'gym2-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/47.png","large":"https://images.pokemontcg.io/gym2/47_hires.png"}',
    searchName: "Koga's Kakuna (G2 47)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Koffing",
    tcgApiId: 'gym2-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/48.png","large":"https://images.pokemontcg.io/gym2/48_hires.png"}',
    searchName: "Koga's Koffing (G2 48)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Pidgey",
    tcgApiId: 'gym2-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/49.png","large":"https://images.pokemontcg.io/gym2/49_hires.png"}',
    searchName: "Koga's Pidgey (G2 49)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Weezing",
    tcgApiId: 'gym2-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/50.png","large":"https://images.pokemontcg.io/gym2/50_hires.png"}',
    searchName: "Koga's Weezing (G2 50)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Lt. Surge's Eevee",
    tcgApiId: 'gym2-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/51.png","large":"https://images.pokemontcg.io/gym2/51_hires.png"}',
    searchName: "Lt. Surge's Eevee (G2 51)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Lt. Surge's Electrode",
    tcgApiId: 'gym2-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/52.png","large":"https://images.pokemontcg.io/gym2/52_hires.png"}',
    searchName: "Lt. Surge's Electrode (G2 52)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Lt. Surge's Raticate",
    tcgApiId: 'gym2-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/53.png","large":"https://images.pokemontcg.io/gym2/53_hires.png"}',
    searchName: "Lt. Surge's Raticate (G2 53)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Dewgong",
    tcgApiId: 'gym2-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/54.png","large":"https://images.pokemontcg.io/gym2/54_hires.png"}',
    searchName: "Misty's Dewgong (G2 54)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Haunter",
    tcgApiId: 'gym2-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/55.png","large":"https://images.pokemontcg.io/gym2/55_hires.png"}',
    searchName: "Sabrina's Haunter (G2 55)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Hypno",
    tcgApiId: 'gym2-56',
    number: '56',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/56.png","large":"https://images.pokemontcg.io/gym2/56_hires.png"}',
    searchName: "Sabrina's Hypno (G2 56)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Jynx",
    tcgApiId: 'gym2-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/57.png","large":"https://images.pokemontcg.io/gym2/57_hires.png"}',
    searchName: "Sabrina's Jynx (G2 57)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Kadabra",
    tcgApiId: 'gym2-58',
    number: '58',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/58.png","large":"https://images.pokemontcg.io/gym2/58_hires.png"}',
    searchName: "Sabrina's Kadabra (G2 58)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Mr. Mime",
    tcgApiId: 'gym2-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/59.png","large":"https://images.pokemontcg.io/gym2/59_hires.png"}',
    searchName: "Sabrina's Mr. Mime (G2 59)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Charmander",
    tcgApiId: 'gym2-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/60.png","large":"https://images.pokemontcg.io/gym2/60_hires.png"}',
    searchName: "Blaine's Charmander (G2 60)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Doduo",
    tcgApiId: 'gym2-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/61.png","large":"https://images.pokemontcg.io/gym2/61_hires.png"}',
    searchName: "Blaine's Doduo (G2 61)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Growlithe",
    tcgApiId: 'gym2-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/62.png","large":"https://images.pokemontcg.io/gym2/62_hires.png"}',
    searchName: "Blaine's Growlithe (G2 62)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Mankey",
    tcgApiId: 'gym2-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/63.png","large":"https://images.pokemontcg.io/gym2/63_hires.png"}',
    searchName: "Blaine's Mankey (G2 63)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Ponyta",
    tcgApiId: 'gym2-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/64.png","large":"https://images.pokemontcg.io/gym2/64_hires.png"}',
    searchName: "Blaine's Ponyta (G2 64)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Rhyhorn",
    tcgApiId: 'gym2-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/65.png","large":"https://images.pokemontcg.io/gym2/65_hires.png"}',
    searchName: "Blaine's Rhyhorn (G2 65)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Vulpix",
    tcgApiId: 'gym2-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/66.png","large":"https://images.pokemontcg.io/gym2/66_hires.png"}',
    searchName: "Blaine's Vulpix (G2 66)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Brock's Diglett",
    tcgApiId: 'gym2-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/67.png","large":"https://images.pokemontcg.io/gym2/67_hires.png"}',
    searchName: "Brock's Diglett (G2 67)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Brock's Geodude",
    tcgApiId: 'gym2-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/68.png","large":"https://images.pokemontcg.io/gym2/68_hires.png"}',
    searchName: "Brock's Geodude (G2 68)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Erika's Jigglypuff",
    tcgApiId: 'gym2-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/69.png","large":"https://images.pokemontcg.io/gym2/69_hires.png"}',
    searchName: "Erika's Jigglypuff (G2 69)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Erika's Oddish",
    tcgApiId: 'gym2-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/70.png","large":"https://images.pokemontcg.io/gym2/70_hires.png"}',
    searchName: "Erika's Oddish (G2 70)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Erika's Paras",
    tcgApiId: 'gym2-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/71.png","large":"https://images.pokemontcg.io/gym2/71_hires.png"}',
    searchName: "Erika's Paras (G2 71)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Machop",
    tcgApiId: 'gym2-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/72.png","large":"https://images.pokemontcg.io/gym2/72_hires.png"}',
    searchName: "Giovanni's Machop (G2 72)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Magikarp",
    tcgApiId: 'gym2-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/73.png","large":"https://images.pokemontcg.io/gym2/73_hires.png"}',
    searchName: "Giovanni's Magikarp (G2 73)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Meowth",
    tcgApiId: 'gym2-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/74.png","large":"https://images.pokemontcg.io/gym2/74_hires.png"}',
    searchName: "Giovanni's Meowth (G2 74)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Nidoran ♀",
    tcgApiId: 'gym2-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/75.png","large":"https://images.pokemontcg.io/gym2/75_hires.png"}',
    searchName: "Giovanni's Nidoran ♀ (G2 75)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Nidoran ♂",
    tcgApiId: 'gym2-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/76.png","large":"https://images.pokemontcg.io/gym2/76_hires.png"}',
    searchName: "Giovanni's Nidoran ♂ (G2 76)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Ekans",
    tcgApiId: 'gym2-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/77.png","large":"https://images.pokemontcg.io/gym2/77_hires.png"}',
    searchName: "Koga's Ekans (G2 77)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Grimer",
    tcgApiId: 'gym2-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/78.png","large":"https://images.pokemontcg.io/gym2/78_hires.png"}',
    searchName: "Koga's Grimer (G2 78)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Koffing",
    tcgApiId: 'gym2-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/79.png","large":"https://images.pokemontcg.io/gym2/79_hires.png"}',
    searchName: "Koga's Koffing (G2 79)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Pidgey",
    tcgApiId: 'gym2-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/80.png","large":"https://images.pokemontcg.io/gym2/80_hires.png"}',
    searchName: "Koga's Pidgey (G2 80)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Tangela",
    tcgApiId: 'gym2-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/81.png","large":"https://images.pokemontcg.io/gym2/81_hires.png"}',
    searchName: "Koga's Tangela (G2 81)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Weedle",
    tcgApiId: 'gym2-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/82.png","large":"https://images.pokemontcg.io/gym2/82_hires.png"}',
    searchName: "Koga's Weedle (G2 82)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Zubat",
    tcgApiId: 'gym2-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/83.png","large":"https://images.pokemontcg.io/gym2/83_hires.png"}',
    searchName: "Koga's Zubat (G2 83)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Lt. Surge's Pikachu",
    tcgApiId: 'gym2-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/84.png","large":"https://images.pokemontcg.io/gym2/84_hires.png"}',
    searchName: "Lt. Surge's Pikachu (G2 84)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Lt. Surge's Rattata",
    tcgApiId: 'gym2-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/85.png","large":"https://images.pokemontcg.io/gym2/85_hires.png"}',
    searchName: "Lt. Surge's Rattata (G2 85)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Lt. Surge's Voltorb",
    tcgApiId: 'gym2-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/86.png","large":"https://images.pokemontcg.io/gym2/86_hires.png"}',
    searchName: "Lt. Surge's Voltorb (G2 86)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Horsea",
    tcgApiId: 'gym2-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/87.png","large":"https://images.pokemontcg.io/gym2/87_hires.png"}',
    searchName: "Misty's Horsea (G2 87)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Magikarp",
    tcgApiId: 'gym2-88',
    number: '88',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/88.png","large":"https://images.pokemontcg.io/gym2/88_hires.png"}',
    searchName: "Misty's Magikarp (G2 88)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Poliwag",
    tcgApiId: 'gym2-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/89.png","large":"https://images.pokemontcg.io/gym2/89_hires.png"}',
    searchName: "Misty's Poliwag (G2 89)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Psyduck",
    tcgApiId: 'gym2-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/90.png","large":"https://images.pokemontcg.io/gym2/90_hires.png"}',
    searchName: "Misty's Psyduck (G2 90)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Seel",
    tcgApiId: 'gym2-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/91.png","large":"https://images.pokemontcg.io/gym2/91_hires.png"}',
    searchName: "Misty's Seel (G2 91)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Staryu",
    tcgApiId: 'gym2-92',
    number: '92',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/92.png","large":"https://images.pokemontcg.io/gym2/92_hires.png"}',
    searchName: "Misty's Staryu (G2 92)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Abra",
    tcgApiId: 'gym2-93',
    number: '93',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/93.png","large":"https://images.pokemontcg.io/gym2/93_hires.png"}',
    searchName: "Sabrina's Abra (G2 93)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Abra",
    tcgApiId: 'gym2-94',
    number: '94',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/94.png","large":"https://images.pokemontcg.io/gym2/94_hires.png"}',
    searchName: "Sabrina's Abra (G2 94)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Drowzee",
    tcgApiId: 'gym2-95',
    number: '95',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/95.png","large":"https://images.pokemontcg.io/gym2/95_hires.png"}',
    searchName: "Sabrina's Drowzee (G2 95)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Gastly",
    tcgApiId: 'gym2-96',
    number: '96',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/96.png","large":"https://images.pokemontcg.io/gym2/96_hires.png"}',
    searchName: "Sabrina's Gastly (G2 96)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Gastly",
    tcgApiId: 'gym2-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/97.png","large":"https://images.pokemontcg.io/gym2/97_hires.png"}',
    searchName: "Sabrina's Gastly (G2 97)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Porygon",
    tcgApiId: 'gym2-98',
    number: '98',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/98.png","large":"https://images.pokemontcg.io/gym2/98_hires.png"}',
    searchName: "Sabrina's Porygon (G2 98)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Psyduck",
    tcgApiId: 'gym2-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/99.png","large":"https://images.pokemontcg.io/gym2/99_hires.png"}',
    searchName: "Sabrina's Psyduck (G2 99)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Blaine',
    tcgApiId: 'gym2-100',
    number: '100',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/100.png","large":"https://images.pokemontcg.io/gym2/100_hires.png"}',
    searchName: 'Blaine (G2 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Brock's Protection",
    tcgApiId: 'gym2-101',
    number: '101',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/101.png","large":"https://images.pokemontcg.io/gym2/101_hires.png"}',
    searchName: "Brock's Protection (G2 101)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Chaos Gym',
    tcgApiId: 'gym2-102',
    number: '102',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/102.png","large":"https://images.pokemontcg.io/gym2/102_hires.png"}',
    searchName: 'Chaos Gym (G2 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Erika's Kindness",
    tcgApiId: 'gym2-103',
    number: '103',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/103.png","large":"https://images.pokemontcg.io/gym2/103_hires.png"}',
    searchName: "Erika's Kindness (G2 103)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Giovanni',
    tcgApiId: 'gym2-104',
    number: '104',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/104.png","large":"https://images.pokemontcg.io/gym2/104_hires.png"}',
    searchName: 'Giovanni (G2 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Giovanni's Last Resort",
    tcgApiId: 'gym2-105',
    number: '105',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/105.png","large":"https://images.pokemontcg.io/gym2/105_hires.png"}',
    searchName: "Giovanni's Last Resort (G2 105)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Koga',
    tcgApiId: 'gym2-106',
    number: '106',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/106.png","large":"https://images.pokemontcg.io/gym2/106_hires.png"}',
    searchName: 'Koga (G2 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Lt. Surge's Secret Plan",
    tcgApiId: 'gym2-107',
    number: '107',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/107.png","large":"https://images.pokemontcg.io/gym2/107_hires.png"}',
    searchName: "Lt. Surge's Secret Plan (G2 107)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Wish",
    tcgApiId: 'gym2-108',
    number: '108',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/108.png","large":"https://images.pokemontcg.io/gym2/108_hires.png"}',
    searchName: "Misty's Wish (G2 108)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Resistance Gym',
    tcgApiId: 'gym2-109',
    number: '109',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/109.png","large":"https://images.pokemontcg.io/gym2/109_hires.png"}',
    searchName: 'Resistance Gym (G2 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Sabrina',
    tcgApiId: 'gym2-110',
    number: '110',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/110.png","large":"https://images.pokemontcg.io/gym2/110_hires.png"}',
    searchName: 'Sabrina (G2 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Quiz #2",
    tcgApiId: 'gym2-111',
    number: '111',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/111.png","large":"https://images.pokemontcg.io/gym2/111_hires.png"}',
    searchName: "Blaine's Quiz #2 (G2 111)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Blaine's Quiz #3",
    tcgApiId: 'gym2-112',
    number: '112',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/112.png","large":"https://images.pokemontcg.io/gym2/112_hires.png"}',
    searchName: "Blaine's Quiz #3 (G2 112)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Cinnabar City Gym',
    tcgApiId: 'gym2-113',
    number: '113',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/113.png","large":"https://images.pokemontcg.io/gym2/113_hires.png"}',
    searchName: 'Cinnabar City Gym (G2 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Fuchsia City Gym',
    tcgApiId: 'gym2-114',
    number: '114',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/114.png","large":"https://images.pokemontcg.io/gym2/114_hires.png"}',
    searchName: 'Fuchsia City Gym (G2 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Koga's Ninja Trick",
    tcgApiId: 'gym2-115',
    number: '115',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/115.png","large":"https://images.pokemontcg.io/gym2/115_hires.png"}',
    searchName: "Koga's Ninja Trick (G2 115)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Master Ball',
    tcgApiId: 'gym2-116',
    number: '116',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/116.png","large":"https://images.pokemontcg.io/gym2/116_hires.png"}',
    searchName: 'Master Ball (G2 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Max Revive',
    tcgApiId: 'gym2-117',
    number: '117',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/117.png","large":"https://images.pokemontcg.io/gym2/117_hires.png"}',
    searchName: 'Max Revive (G2 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Misty's Tears",
    tcgApiId: 'gym2-118',
    number: '118',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/118.png","large":"https://images.pokemontcg.io/gym2/118_hires.png"}',
    searchName: "Misty's Tears (G2 118)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Rocket's Minefield Gym",
    tcgApiId: 'gym2-119',
    number: '119',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/119.png","large":"https://images.pokemontcg.io/gym2/119_hires.png"}',
    searchName: "Rocket's Minefield Gym (G2 119)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Rocket's Secret Experiment",
    tcgApiId: 'gym2-120',
    number: '120',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/120.png","large":"https://images.pokemontcg.io/gym2/120_hires.png"}',
    searchName: "Rocket's Secret Experiment (G2 120)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: "Sabrina's Psychic Control",
    tcgApiId: 'gym2-121',
    number: '121',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/121.png","large":"https://images.pokemontcg.io/gym2/121_hires.png"}',
    searchName: "Sabrina's Psychic Control (G2 121)",
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Saffron City Gym',
    tcgApiId: 'gym2-122',
    number: '122',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/122.png","large":"https://images.pokemontcg.io/gym2/122_hires.png"}',
    searchName: 'Saffron City Gym (G2 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Viridian City Gym',
    tcgApiId: 'gym2-123',
    number: '123',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/123.png","large":"https://images.pokemontcg.io/gym2/123_hires.png"}',
    searchName: 'Viridian City Gym (G2 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Fervor',
    tcgApiId: 'gym2-124',
    number: '124',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/124.png","large":"https://images.pokemontcg.io/gym2/124_hires.png"}',
    searchName: 'Fervor (G2 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Transparent Walls',
    tcgApiId: 'gym2-125',
    number: '125',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/125.png","large":"https://images.pokemontcg.io/gym2/125_hires.png"}',
    searchName: 'Transparent Walls (G2 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Warp Point',
    tcgApiId: 'gym2-126',
    number: '126',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/126.png","large":"https://images.pokemontcg.io/gym2/126_hires.png"}',
    searchName: 'Warp Point (G2 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Fighting Energy',
    tcgApiId: 'gym2-127',
    number: '127',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/127.png","large":"https://images.pokemontcg.io/gym2/127_hires.png"}',
    searchName: 'Fighting Energy (G2 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Fire Energy',
    tcgApiId: 'gym2-128',
    number: '128',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/128.png","large":"https://images.pokemontcg.io/gym2/128_hires.png"}',
    searchName: 'Fire Energy (G2 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Grass Energy',
    tcgApiId: 'gym2-129',
    number: '129',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/129.png","large":"https://images.pokemontcg.io/gym2/129_hires.png"}',
    searchName: 'Grass Energy (G2 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Lightning Energy',
    tcgApiId: 'gym2-130',
    number: '130',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/130.png","large":"https://images.pokemontcg.io/gym2/130_hires.png"}',
    searchName: 'Lightning Energy (G2 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Psychic Energy',
    tcgApiId: 'gym2-131',
    number: '131',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/131.png","large":"https://images.pokemontcg.io/gym2/131_hires.png"}',
    searchName: 'Psychic Energy (G2 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'gym2',
    name: 'Water Energy',
    tcgApiId: 'gym2-132',
    number: '132',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/gym2/132.png","large":"https://images.pokemontcg.io/gym2/132_hires.png"}',
    searchName: 'Water Energy (G2 132)',
  },
];
