export const cardSeedHgss1 = [
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Arcanine',
    tcgApiId: 'hgss1-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/1.png","large":"https://images.pokemontcg.io/hgss1/1_hires.png"}',
    searchName: 'Arcanine (HS 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Azumarill',
    tcgApiId: 'hgss1-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/2.png","large":"https://images.pokemontcg.io/hgss1/2_hires.png"}',
    searchName: 'Azumarill (HS 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Clefable',
    tcgApiId: 'hgss1-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/3.png","large":"https://images.pokemontcg.io/hgss1/3_hires.png"}',
    searchName: 'Clefable (HS 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Gyarados',
    tcgApiId: 'hgss1-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/4.png","large":"https://images.pokemontcg.io/hgss1/4_hires.png"}',
    searchName: 'Gyarados (HS 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Hitmontop',
    tcgApiId: 'hgss1-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/5.png","large":"https://images.pokemontcg.io/hgss1/5_hires.png"}',
    searchName: 'Hitmontop (HS 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Jumpluff',
    tcgApiId: 'hgss1-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/6.png","large":"https://images.pokemontcg.io/hgss1/6_hires.png"}',
    searchName: 'Jumpluff (HS 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Ninetales',
    tcgApiId: 'hgss1-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/7.png","large":"https://images.pokemontcg.io/hgss1/7_hires.png"}',
    searchName: 'Ninetales (HS 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Noctowl',
    tcgApiId: 'hgss1-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/8.png","large":"https://images.pokemontcg.io/hgss1/8_hires.png"}',
    searchName: 'Noctowl (HS 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Quagsire',
    tcgApiId: 'hgss1-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/9.png","large":"https://images.pokemontcg.io/hgss1/9_hires.png"}',
    searchName: 'Quagsire (HS 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Raichu',
    tcgApiId: 'hgss1-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/10.png","large":"https://images.pokemontcg.io/hgss1/10_hires.png"}',
    searchName: 'Raichu (HS 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Shuckle',
    tcgApiId: 'hgss1-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/11.png","large":"https://images.pokemontcg.io/hgss1/11_hires.png"}',
    searchName: 'Shuckle (HS 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Slowking',
    tcgApiId: 'hgss1-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/12.png","large":"https://images.pokemontcg.io/hgss1/12_hires.png"}',
    searchName: 'Slowking (HS 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Wobbuffet',
    tcgApiId: 'hgss1-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/13.png","large":"https://images.pokemontcg.io/hgss1/13_hires.png"}',
    searchName: 'Wobbuffet (HS 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Ampharos',
    tcgApiId: 'hgss1-14',
    number: '14',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/14.png","large":"https://images.pokemontcg.io/hgss1/14_hires.png"}',
    searchName: 'Ampharos (HS 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Ariados',
    tcgApiId: 'hgss1-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/15.png","large":"https://images.pokemontcg.io/hgss1/15_hires.png"}',
    searchName: 'Ariados (HS 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Butterfree',
    tcgApiId: 'hgss1-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/16.png","large":"https://images.pokemontcg.io/hgss1/16_hires.png"}',
    searchName: 'Butterfree (HS 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Cleffa',
    tcgApiId: 'hgss1-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/17.png","large":"https://images.pokemontcg.io/hgss1/17_hires.png"}',
    searchName: 'Cleffa (HS 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Exeggutor',
    tcgApiId: 'hgss1-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/18.png","large":"https://images.pokemontcg.io/hgss1/18_hires.png"}',
    searchName: 'Exeggutor (HS 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: "Farfetch'd",
    tcgApiId: 'hgss1-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/19.png","large":"https://images.pokemontcg.io/hgss1/19_hires.png"}',
    searchName: "Farfetch'd (HS 19)",
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Feraligatr',
    tcgApiId: 'hgss1-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/20.png","large":"https://images.pokemontcg.io/hgss1/20_hires.png"}',
    searchName: 'Feraligatr (HS 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Furret',
    tcgApiId: 'hgss1-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/21.png","large":"https://images.pokemontcg.io/hgss1/21_hires.png"}',
    searchName: 'Furret (HS 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Granbull',
    tcgApiId: 'hgss1-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/22.png","large":"https://images.pokemontcg.io/hgss1/22_hires.png"}',
    searchName: 'Granbull (HS 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Hypno',
    tcgApiId: 'hgss1-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/23.png","large":"https://images.pokemontcg.io/hgss1/23_hires.png"}',
    searchName: 'Hypno (HS 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Lapras',
    tcgApiId: 'hgss1-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/24.png","large":"https://images.pokemontcg.io/hgss1/24_hires.png"}',
    searchName: 'Lapras (HS 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Ledian',
    tcgApiId: 'hgss1-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/25.png","large":"https://images.pokemontcg.io/hgss1/25_hires.png"}',
    searchName: 'Ledian (HS 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Meganium',
    tcgApiId: 'hgss1-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/26.png","large":"https://images.pokemontcg.io/hgss1/26_hires.png"}',
    searchName: 'Meganium (HS 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Persian',
    tcgApiId: 'hgss1-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/27.png","large":"https://images.pokemontcg.io/hgss1/27_hires.png"}',
    searchName: 'Persian (HS 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Pichu',
    tcgApiId: 'hgss1-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/28.png","large":"https://images.pokemontcg.io/hgss1/28_hires.png"}',
    searchName: 'Pichu (HS 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Sandslash',
    tcgApiId: 'hgss1-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/29.png","large":"https://images.pokemontcg.io/hgss1/29_hires.png"}',
    searchName: 'Sandslash (HS 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Smoochum',
    tcgApiId: 'hgss1-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/30.png","large":"https://images.pokemontcg.io/hgss1/30_hires.png"}',
    searchName: 'Smoochum (HS 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Sunflora',
    tcgApiId: 'hgss1-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/31.png","large":"https://images.pokemontcg.io/hgss1/31_hires.png"}',
    searchName: 'Sunflora (HS 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Typhlosion',
    tcgApiId: 'hgss1-32',
    number: '32',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/32.png","large":"https://images.pokemontcg.io/hgss1/32_hires.png"}',
    searchName: 'Typhlosion (HS 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Tyrogue',
    tcgApiId: 'hgss1-33',
    number: '33',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/33.png","large":"https://images.pokemontcg.io/hgss1/33_hires.png"}',
    searchName: 'Tyrogue (HS 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Weezing',
    tcgApiId: 'hgss1-34',
    number: '34',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/34.png","large":"https://images.pokemontcg.io/hgss1/34_hires.png"}',
    searchName: 'Weezing (HS 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Bayleef',
    tcgApiId: 'hgss1-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/35.png","large":"https://images.pokemontcg.io/hgss1/35_hires.png"}',
    searchName: 'Bayleef (HS 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Blissey',
    tcgApiId: 'hgss1-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/36.png","large":"https://images.pokemontcg.io/hgss1/36_hires.png"}',
    searchName: 'Blissey (HS 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Corsola',
    tcgApiId: 'hgss1-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/37.png","large":"https://images.pokemontcg.io/hgss1/37_hires.png"}',
    searchName: 'Corsola (HS 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Croconaw',
    tcgApiId: 'hgss1-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/38.png","large":"https://images.pokemontcg.io/hgss1/38_hires.png"}',
    searchName: 'Croconaw (HS 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Delibird',
    tcgApiId: 'hgss1-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/39.png","large":"https://images.pokemontcg.io/hgss1/39_hires.png"}',
    searchName: 'Delibird (HS 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Donphan',
    tcgApiId: 'hgss1-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/40.png","large":"https://images.pokemontcg.io/hgss1/40_hires.png"}',
    searchName: 'Donphan (HS 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Dunsparce',
    tcgApiId: 'hgss1-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/41.png","large":"https://images.pokemontcg.io/hgss1/41_hires.png"}',
    searchName: 'Dunsparce (HS 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Flaaffy',
    tcgApiId: 'hgss1-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/42.png","large":"https://images.pokemontcg.io/hgss1/42_hires.png"}',
    searchName: 'Flaaffy (HS 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Heracross',
    tcgApiId: 'hgss1-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/43.png","large":"https://images.pokemontcg.io/hgss1/43_hires.png"}',
    searchName: 'Heracross (HS 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Igglybuff',
    tcgApiId: 'hgss1-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/44.png","large":"https://images.pokemontcg.io/hgss1/44_hires.png"}',
    searchName: 'Igglybuff (HS 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Mantine',
    tcgApiId: 'hgss1-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/45.png","large":"https://images.pokemontcg.io/hgss1/45_hires.png"}',
    searchName: 'Mantine (HS 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Metapod',
    tcgApiId: 'hgss1-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/46.png","large":"https://images.pokemontcg.io/hgss1/46_hires.png"}',
    searchName: 'Metapod (HS 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Miltank',
    tcgApiId: 'hgss1-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/47.png","large":"https://images.pokemontcg.io/hgss1/47_hires.png"}',
    searchName: 'Miltank (HS 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Parasect',
    tcgApiId: 'hgss1-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/48.png","large":"https://images.pokemontcg.io/hgss1/48_hires.png"}',
    searchName: 'Parasect (HS 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Quilava',
    tcgApiId: 'hgss1-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/49.png","large":"https://images.pokemontcg.io/hgss1/49_hires.png"}',
    searchName: 'Quilava (HS 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Qwilfish',
    tcgApiId: 'hgss1-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/50.png","large":"https://images.pokemontcg.io/hgss1/50_hires.png"}',
    searchName: 'Qwilfish (HS 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Skiploom',
    tcgApiId: 'hgss1-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/51.png","large":"https://images.pokemontcg.io/hgss1/51_hires.png"}',
    searchName: 'Skiploom (HS 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Slowbro',
    tcgApiId: 'hgss1-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/52.png","large":"https://images.pokemontcg.io/hgss1/52_hires.png"}',
    searchName: 'Slowbro (HS 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Starmie',
    tcgApiId: 'hgss1-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/53.png","large":"https://images.pokemontcg.io/hgss1/53_hires.png"}',
    searchName: 'Starmie (HS 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Unown',
    tcgApiId: 'hgss1-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/54.png","large":"https://images.pokemontcg.io/hgss1/54_hires.png"}',
    searchName: 'Unown (HS 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Unown',
    tcgApiId: 'hgss1-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/55.png","large":"https://images.pokemontcg.io/hgss1/55_hires.png"}',
    searchName: 'Unown (HS 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Wigglytuff',
    tcgApiId: 'hgss1-56',
    number: '56',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/56.png","large":"https://images.pokemontcg.io/hgss1/56_hires.png"}',
    searchName: 'Wigglytuff (HS 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Caterpie',
    tcgApiId: 'hgss1-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/57.png","large":"https://images.pokemontcg.io/hgss1/57_hires.png"}',
    searchName: 'Caterpie (HS 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Chansey',
    tcgApiId: 'hgss1-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/58.png","large":"https://images.pokemontcg.io/hgss1/58_hires.png"}',
    searchName: 'Chansey (HS 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Chikorita',
    tcgApiId: 'hgss1-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/59.png","large":"https://images.pokemontcg.io/hgss1/59_hires.png"}',
    searchName: 'Chikorita (HS 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Clefairy',
    tcgApiId: 'hgss1-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/60.png","large":"https://images.pokemontcg.io/hgss1/60_hires.png"}',
    searchName: 'Clefairy (HS 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Cyndaquil',
    tcgApiId: 'hgss1-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/61.png","large":"https://images.pokemontcg.io/hgss1/61_hires.png"}',
    searchName: 'Cyndaquil (HS 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Drowzee',
    tcgApiId: 'hgss1-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/62.png","large":"https://images.pokemontcg.io/hgss1/62_hires.png"}',
    searchName: 'Drowzee (HS 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Exeggcute',
    tcgApiId: 'hgss1-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/63.png","large":"https://images.pokemontcg.io/hgss1/63_hires.png"}',
    searchName: 'Exeggcute (HS 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Girafarig',
    tcgApiId: 'hgss1-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/64.png","large":"https://images.pokemontcg.io/hgss1/64_hires.png"}',
    searchName: 'Girafarig (HS 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Growlithe',
    tcgApiId: 'hgss1-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/65.png","large":"https://images.pokemontcg.io/hgss1/65_hires.png"}',
    searchName: 'Growlithe (HS 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Hoothoot',
    tcgApiId: 'hgss1-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/66.png","large":"https://images.pokemontcg.io/hgss1/66_hires.png"}',
    searchName: 'Hoothoot (HS 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Hoppip',
    tcgApiId: 'hgss1-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/67.png","large":"https://images.pokemontcg.io/hgss1/67_hires.png"}',
    searchName: 'Hoppip (HS 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Jigglypuff',
    tcgApiId: 'hgss1-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/68.png","large":"https://images.pokemontcg.io/hgss1/68_hires.png"}',
    searchName: 'Jigglypuff (HS 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Jynx',
    tcgApiId: 'hgss1-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/69.png","large":"https://images.pokemontcg.io/hgss1/69_hires.png"}',
    searchName: 'Jynx (HS 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Koffing',
    tcgApiId: 'hgss1-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/70.png","large":"https://images.pokemontcg.io/hgss1/70_hires.png"}',
    searchName: 'Koffing (HS 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Ledyba',
    tcgApiId: 'hgss1-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/71.png","large":"https://images.pokemontcg.io/hgss1/71_hires.png"}',
    searchName: 'Ledyba (HS 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Magikarp',
    tcgApiId: 'hgss1-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/72.png","large":"https://images.pokemontcg.io/hgss1/72_hires.png"}',
    searchName: 'Magikarp (HS 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Mareep',
    tcgApiId: 'hgss1-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/73.png","large":"https://images.pokemontcg.io/hgss1/73_hires.png"}',
    searchName: 'Mareep (HS 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Marill',
    tcgApiId: 'hgss1-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/74.png","large":"https://images.pokemontcg.io/hgss1/74_hires.png"}',
    searchName: 'Marill (HS 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Meowth',
    tcgApiId: 'hgss1-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/75.png","large":"https://images.pokemontcg.io/hgss1/75_hires.png"}',
    searchName: 'Meowth (HS 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Paras',
    tcgApiId: 'hgss1-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/76.png","large":"https://images.pokemontcg.io/hgss1/76_hires.png"}',
    searchName: 'Paras (HS 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Phanpy',
    tcgApiId: 'hgss1-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/77.png","large":"https://images.pokemontcg.io/hgss1/77_hires.png"}',
    searchName: 'Phanpy (HS 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Pikachu',
    tcgApiId: 'hgss1-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/78.png","large":"https://images.pokemontcg.io/hgss1/78_hires.png"}',
    searchName: 'Pikachu (HS 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Sandshrew',
    tcgApiId: 'hgss1-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/79.png","large":"https://images.pokemontcg.io/hgss1/79_hires.png"}',
    searchName: 'Sandshrew (HS 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Sentret',
    tcgApiId: 'hgss1-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/80.png","large":"https://images.pokemontcg.io/hgss1/80_hires.png"}',
    searchName: 'Sentret (HS 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Slowpoke',
    tcgApiId: 'hgss1-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/81.png","large":"https://images.pokemontcg.io/hgss1/81_hires.png"}',
    searchName: 'Slowpoke (HS 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Snubbull',
    tcgApiId: 'hgss1-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/82.png","large":"https://images.pokemontcg.io/hgss1/82_hires.png"}',
    searchName: 'Snubbull (HS 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Spinarak',
    tcgApiId: 'hgss1-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/83.png","large":"https://images.pokemontcg.io/hgss1/83_hires.png"}',
    searchName: 'Spinarak (HS 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Staryu',
    tcgApiId: 'hgss1-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/84.png","large":"https://images.pokemontcg.io/hgss1/84_hires.png"}',
    searchName: 'Staryu (HS 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Sunkern',
    tcgApiId: 'hgss1-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/85.png","large":"https://images.pokemontcg.io/hgss1/85_hires.png"}',
    searchName: 'Sunkern (HS 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Totodile',
    tcgApiId: 'hgss1-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/86.png","large":"https://images.pokemontcg.io/hgss1/86_hires.png"}',
    searchName: 'Totodile (HS 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Vulpix',
    tcgApiId: 'hgss1-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/87.png","large":"https://images.pokemontcg.io/hgss1/87_hires.png"}',
    searchName: 'Vulpix (HS 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Wooper',
    tcgApiId: 'hgss1-88',
    number: '88',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/88.png","large":"https://images.pokemontcg.io/hgss1/88_hires.png"}',
    searchName: 'Wooper (HS 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Bill',
    tcgApiId: 'hgss1-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/89.png","large":"https://images.pokemontcg.io/hgss1/89_hires.png"}',
    searchName: 'Bill (HS 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Copycat',
    tcgApiId: 'hgss1-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/90.png","large":"https://images.pokemontcg.io/hgss1/90_hires.png"}',
    searchName: 'Copycat (HS 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Energy Switch',
    tcgApiId: 'hgss1-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/91.png","large":"https://images.pokemontcg.io/hgss1/91_hires.png"}',
    searchName: 'Energy Switch (HS 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Fisherman',
    tcgApiId: 'hgss1-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/92.png","large":"https://images.pokemontcg.io/hgss1/92_hires.png"}',
    searchName: 'Fisherman (HS 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Full Heal',
    tcgApiId: 'hgss1-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/93.png","large":"https://images.pokemontcg.io/hgss1/93_hires.png"}',
    searchName: 'Full Heal (HS 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Moomoo Milk',
    tcgApiId: 'hgss1-94',
    number: '94',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/94.png","large":"https://images.pokemontcg.io/hgss1/94_hires.png"}',
    searchName: 'Moomoo Milk (HS 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Poké Ball',
    tcgApiId: 'hgss1-95',
    number: '95',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/95.png","large":"https://images.pokemontcg.io/hgss1/95_hires.png"}',
    searchName: 'Poké Ball (HS 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Pokégear 3.0',
    tcgApiId: 'hgss1-96',
    number: '96',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/96.png","large":"https://images.pokemontcg.io/hgss1/96_hires.png"}',
    searchName: 'Pokégear 3.0 (HS 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Pokémon Collector',
    tcgApiId: 'hgss1-97',
    number: '97',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/97.png","large":"https://images.pokemontcg.io/hgss1/97_hires.png"}',
    searchName: 'Pokémon Collector (HS 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Pokémon Communication',
    tcgApiId: 'hgss1-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/98.png","large":"https://images.pokemontcg.io/hgss1/98_hires.png"}',
    searchName: 'Pokémon Communication (HS 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Pokémon Reversal',
    tcgApiId: 'hgss1-99',
    number: '99',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/99.png","large":"https://images.pokemontcg.io/hgss1/99_hires.png"}',
    searchName: 'Pokémon Reversal (HS 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: "Professor Elm's Training Method",
    tcgApiId: 'hgss1-100',
    number: '100',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/100.png","large":"https://images.pokemontcg.io/hgss1/100_hires.png"}',
    searchName: "Professor Elm's Training Method (HS 100)",
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: "Professor Oak's New Theory",
    tcgApiId: 'hgss1-101',
    number: '101',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/101.png","large":"https://images.pokemontcg.io/hgss1/101_hires.png"}',
    searchName: "Professor Oak's New Theory (HS 101)",
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Switch',
    tcgApiId: 'hgss1-102',
    number: '102',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/102.png","large":"https://images.pokemontcg.io/hgss1/102_hires.png"}',
    searchName: 'Switch (HS 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Double Colorless Energy',
    tcgApiId: 'hgss1-103',
    number: '103',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/103.png","large":"https://images.pokemontcg.io/hgss1/103_hires.png"}',
    searchName: 'Double Colorless Energy (HS 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Rainbow Energy',
    tcgApiId: 'hgss1-104',
    number: '104',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/104.png","large":"https://images.pokemontcg.io/hgss1/104_hires.png"}',
    searchName: 'Rainbow Energy (HS 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Ampharos',
    tcgApiId: 'hgss1-105',
    number: '105',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/105.png","large":"https://images.pokemontcg.io/hgss1/105_hires.png"}',
    searchName: 'Ampharos (HS 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Blissey',
    tcgApiId: 'hgss1-106',
    number: '106',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/106.png","large":"https://images.pokemontcg.io/hgss1/106_hires.png"}',
    searchName: 'Blissey (HS 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Donphan',
    tcgApiId: 'hgss1-107',
    number: '107',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/107.png","large":"https://images.pokemontcg.io/hgss1/107_hires.png"}',
    searchName: 'Donphan (HS 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Feraligatr',
    tcgApiId: 'hgss1-108',
    number: '108',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/108.png","large":"https://images.pokemontcg.io/hgss1/108_hires.png"}',
    searchName: 'Feraligatr (HS 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Meganium',
    tcgApiId: 'hgss1-109',
    number: '109',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/109.png","large":"https://images.pokemontcg.io/hgss1/109_hires.png"}',
    searchName: 'Meganium (HS 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Typhlosion',
    tcgApiId: 'hgss1-110',
    number: '110',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/110.png","large":"https://images.pokemontcg.io/hgss1/110_hires.png"}',
    searchName: 'Typhlosion (HS 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Ho-Oh LEGEND',
    tcgApiId: 'hgss1-111',
    number: '111',
    rarity: 'LEGEND',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/111.png","large":"https://images.pokemontcg.io/hgss1/111_hires.png"}',
    searchName: 'Ho-Oh LEGEND (HS 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Ho-Oh LEGEND',
    tcgApiId: 'hgss1-112',
    number: '112',
    rarity: 'LEGEND',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/112.png","large":"https://images.pokemontcg.io/hgss1/112_hires.png"}',
    searchName: 'Ho-Oh LEGEND (HS 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Lugia LEGEND',
    tcgApiId: 'hgss1-113',
    number: '113',
    rarity: 'LEGEND',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/113.png","large":"https://images.pokemontcg.io/hgss1/113_hires.png"}',
    searchName: 'Lugia LEGEND (HS 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Lugia LEGEND',
    tcgApiId: 'hgss1-114',
    number: '114',
    rarity: 'LEGEND',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/114.png","large":"https://images.pokemontcg.io/hgss1/114_hires.png"}',
    searchName: 'Lugia LEGEND (HS 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Grass Energy',
    tcgApiId: 'hgss1-115',
    number: '115',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/115.png","large":"https://images.pokemontcg.io/hgss1/115_hires.png"}',
    searchName: 'Grass Energy (HS 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Fire Energy',
    tcgApiId: 'hgss1-116',
    number: '116',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/116.png","large":"https://images.pokemontcg.io/hgss1/116_hires.png"}',
    searchName: 'Fire Energy (HS 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Water Energy',
    tcgApiId: 'hgss1-117',
    number: '117',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/117.png","large":"https://images.pokemontcg.io/hgss1/117_hires.png"}',
    searchName: 'Water Energy (HS 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Lightning Energy',
    tcgApiId: 'hgss1-118',
    number: '118',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/118.png","large":"https://images.pokemontcg.io/hgss1/118_hires.png"}',
    searchName: 'Lightning Energy (HS 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Psychic Energy',
    tcgApiId: 'hgss1-119',
    number: '119',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/119.png","large":"https://images.pokemontcg.io/hgss1/119_hires.png"}',
    searchName: 'Psychic Energy (HS 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Fighting Energy',
    tcgApiId: 'hgss1-120',
    number: '120',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/120.png","large":"https://images.pokemontcg.io/hgss1/120_hires.png"}',
    searchName: 'Fighting Energy (HS 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Darkness Energy',
    tcgApiId: 'hgss1-121',
    number: '121',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/121.png","large":"https://images.pokemontcg.io/hgss1/121_hires.png"}',
    searchName: 'Darkness Energy (HS 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Metal Energy',
    tcgApiId: 'hgss1-122',
    number: '122',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/122.png","large":"https://images.pokemontcg.io/hgss1/122_hires.png"}',
    searchName: 'Metal Energy (HS 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Gyarados',
    tcgApiId: 'hgss1-123',
    number: '123',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/123.png","large":"https://images.pokemontcg.io/hgss1/123_hires.png"}',
    searchName: 'Gyarados (HS 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss1',
    name: 'Alph Lithograph',
    tcgApiId: 'hgss1-ONE',
    number: 'ONE',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/hgss1/ONE.png","large":"https://images.pokemontcg.io/hgss1/ONE_hires.png"}',
    searchName: 'Alph Lithograph (HS ONE)',
  },
];
