export const cardSeedHgss4 = [
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Aggron',
    tcgApiId: 'hgss4-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/1.png","large":"https://images.pokemontcg.io/hgss4/1_hires.png"}',
    searchName: 'Aggron (TM 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Altaria',
    tcgApiId: 'hgss4-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/2.png","large":"https://images.pokemontcg.io/hgss4/2_hires.png"}',
    searchName: 'Altaria (TM 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Celebi',
    tcgApiId: 'hgss4-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/3.png","large":"https://images.pokemontcg.io/hgss4/3_hires.png"}',
    searchName: 'Celebi (TM 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Drapion',
    tcgApiId: 'hgss4-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/4.png","large":"https://images.pokemontcg.io/hgss4/4_hires.png"}',
    searchName: 'Drapion (TM 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Mamoswine',
    tcgApiId: 'hgss4-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/5.png","large":"https://images.pokemontcg.io/hgss4/5_hires.png"}',
    searchName: 'Mamoswine (TM 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Nidoking',
    tcgApiId: 'hgss4-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/6.png","large":"https://images.pokemontcg.io/hgss4/6_hires.png"}',
    searchName: 'Nidoking (TM 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Porygon-Z',
    tcgApiId: 'hgss4-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/7.png","large":"https://images.pokemontcg.io/hgss4/7_hires.png"}',
    searchName: 'Porygon-Z (TM 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Rapidash',
    tcgApiId: 'hgss4-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/8.png","large":"https://images.pokemontcg.io/hgss4/8_hires.png"}',
    searchName: 'Rapidash (TM 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Solrock',
    tcgApiId: 'hgss4-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/9.png","large":"https://images.pokemontcg.io/hgss4/9_hires.png"}',
    searchName: 'Solrock (TM 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Spiritomb',
    tcgApiId: 'hgss4-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/10.png","large":"https://images.pokemontcg.io/hgss4/10_hires.png"}',
    searchName: 'Spiritomb (TM 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Venomoth',
    tcgApiId: 'hgss4-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/11.png","large":"https://images.pokemontcg.io/hgss4/11_hires.png"}',
    searchName: 'Venomoth (TM 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Victreebel',
    tcgApiId: 'hgss4-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/12.png","large":"https://images.pokemontcg.io/hgss4/12_hires.png"}',
    searchName: 'Victreebel (TM 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Ambipom',
    tcgApiId: 'hgss4-13',
    number: '13',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/13.png","large":"https://images.pokemontcg.io/hgss4/13_hires.png"}',
    searchName: 'Ambipom (TM 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Banette',
    tcgApiId: 'hgss4-14',
    number: '14',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/14.png","large":"https://images.pokemontcg.io/hgss4/14_hires.png"}',
    searchName: 'Banette (TM 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Bronzong',
    tcgApiId: 'hgss4-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/15.png","large":"https://images.pokemontcg.io/hgss4/15_hires.png"}',
    searchName: 'Bronzong (TM 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Carnivine',
    tcgApiId: 'hgss4-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/16.png","large":"https://images.pokemontcg.io/hgss4/16_hires.png"}',
    searchName: 'Carnivine (TM 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Ditto',
    tcgApiId: 'hgss4-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/17.png","large":"https://images.pokemontcg.io/hgss4/17_hires.png"}',
    searchName: 'Ditto (TM 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Dragonite',
    tcgApiId: 'hgss4-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/18.png","large":"https://images.pokemontcg.io/hgss4/18_hires.png"}',
    searchName: 'Dragonite (TM 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Dugtrio',
    tcgApiId: 'hgss4-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/19.png","large":"https://images.pokemontcg.io/hgss4/19_hires.png"}',
    searchName: 'Dugtrio (TM 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Electivire',
    tcgApiId: 'hgss4-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/20.png","large":"https://images.pokemontcg.io/hgss4/20_hires.png"}',
    searchName: 'Electivire (TM 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Elekid',
    tcgApiId: 'hgss4-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/21.png","large":"https://images.pokemontcg.io/hgss4/21_hires.png"}',
    searchName: 'Elekid (TM 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Golduck',
    tcgApiId: 'hgss4-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/22.png","large":"https://images.pokemontcg.io/hgss4/22_hires.png"}',
    searchName: 'Golduck (TM 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Grumpig',
    tcgApiId: 'hgss4-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/23.png","large":"https://images.pokemontcg.io/hgss4/23_hires.png"}',
    searchName: 'Grumpig (TM 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Kricketune',
    tcgApiId: 'hgss4-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/24.png","large":"https://images.pokemontcg.io/hgss4/24_hires.png"}',
    searchName: 'Kricketune (TM 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Lunatone',
    tcgApiId: 'hgss4-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/25.png","large":"https://images.pokemontcg.io/hgss4/25_hires.png"}',
    searchName: 'Lunatone (TM 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Machamp',
    tcgApiId: 'hgss4-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/26.png","large":"https://images.pokemontcg.io/hgss4/26_hires.png"}',
    searchName: 'Machamp (TM 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Magmortar',
    tcgApiId: 'hgss4-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/27.png","large":"https://images.pokemontcg.io/hgss4/27_hires.png"}',
    searchName: 'Magmortar (TM 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Nidoqueen',
    tcgApiId: 'hgss4-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/28.png","large":"https://images.pokemontcg.io/hgss4/28_hires.png"}',
    searchName: 'Nidoqueen (TM 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Pidgeot',
    tcgApiId: 'hgss4-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/29.png","large":"https://images.pokemontcg.io/hgss4/29_hires.png"}',
    searchName: 'Pidgeot (TM 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Sharpedo',
    tcgApiId: 'hgss4-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/30.png","large":"https://images.pokemontcg.io/hgss4/30_hires.png"}',
    searchName: 'Sharpedo (TM 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Wailord',
    tcgApiId: 'hgss4-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/31.png","large":"https://images.pokemontcg.io/hgss4/31_hires.png"}',
    searchName: 'Wailord (TM 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Dragonair',
    tcgApiId: 'hgss4-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/32.png","large":"https://images.pokemontcg.io/hgss4/32_hires.png"}',
    searchName: 'Dragonair (TM 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Electabuzz',
    tcgApiId: 'hgss4-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/33.png","large":"https://images.pokemontcg.io/hgss4/33_hires.png"}',
    searchName: 'Electabuzz (TM 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Electrode',
    tcgApiId: 'hgss4-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/34.png","large":"https://images.pokemontcg.io/hgss4/34_hires.png"}',
    searchName: 'Electrode (TM 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Haunter',
    tcgApiId: 'hgss4-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/35.png","large":"https://images.pokemontcg.io/hgss4/35_hires.png"}',
    searchName: 'Haunter (TM 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Kangaskhan',
    tcgApiId: 'hgss4-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/36.png","large":"https://images.pokemontcg.io/hgss4/36_hires.png"}',
    searchName: 'Kangaskhan (TM 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Lairon',
    tcgApiId: 'hgss4-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/37.png","large":"https://images.pokemontcg.io/hgss4/37_hires.png"}',
    searchName: 'Lairon (TM 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Lickilicky',
    tcgApiId: 'hgss4-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/38.png","large":"https://images.pokemontcg.io/hgss4/38_hires.png"}',
    searchName: 'Lickilicky (TM 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Luvdisc',
    tcgApiId: 'hgss4-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/39.png","large":"https://images.pokemontcg.io/hgss4/39_hires.png"}',
    searchName: 'Luvdisc (TM 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Machoke',
    tcgApiId: 'hgss4-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/40.png","large":"https://images.pokemontcg.io/hgss4/40_hires.png"}',
    searchName: 'Machoke (TM 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Magby',
    tcgApiId: 'hgss4-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/41.png","large":"https://images.pokemontcg.io/hgss4/41_hires.png"}',
    searchName: 'Magby (TM 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Magmar',
    tcgApiId: 'hgss4-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/42.png","large":"https://images.pokemontcg.io/hgss4/42_hires.png"}',
    searchName: 'Magmar (TM 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Magneton',
    tcgApiId: 'hgss4-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/43.png","large":"https://images.pokemontcg.io/hgss4/43_hires.png"}',
    searchName: 'Magneton (TM 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Marowak',
    tcgApiId: 'hgss4-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/44.png","large":"https://images.pokemontcg.io/hgss4/44_hires.png"}',
    searchName: 'Marowak (TM 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Nidorina',
    tcgApiId: 'hgss4-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/45.png","large":"https://images.pokemontcg.io/hgss4/45_hires.png"}',
    searchName: 'Nidorina (TM 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Nidorino',
    tcgApiId: 'hgss4-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/46.png","large":"https://images.pokemontcg.io/hgss4/46_hires.png"}',
    searchName: 'Nidorino (TM 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Pidgeotto',
    tcgApiId: 'hgss4-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/47.png","large":"https://images.pokemontcg.io/hgss4/47_hires.png"}',
    searchName: 'Pidgeotto (TM 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Piloswine',
    tcgApiId: 'hgss4-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/48.png","large":"https://images.pokemontcg.io/hgss4/48_hires.png"}',
    searchName: 'Piloswine (TM 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Porygon2',
    tcgApiId: 'hgss4-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/49.png","large":"https://images.pokemontcg.io/hgss4/49_hires.png"}',
    searchName: 'Porygon2 (TM 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Tentacruel',
    tcgApiId: 'hgss4-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/50.png","large":"https://images.pokemontcg.io/hgss4/50_hires.png"}',
    searchName: 'Tentacruel (TM 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Unown',
    tcgApiId: 'hgss4-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/51.png","large":"https://images.pokemontcg.io/hgss4/51_hires.png"}',
    searchName: 'Unown (TM 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Wailmer',
    tcgApiId: 'hgss4-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/52.png","large":"https://images.pokemontcg.io/hgss4/52_hires.png"}',
    searchName: 'Wailmer (TM 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Weepinbell',
    tcgApiId: 'hgss4-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/53.png","large":"https://images.pokemontcg.io/hgss4/53_hires.png"}',
    searchName: 'Weepinbell (TM 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Yanmega',
    tcgApiId: 'hgss4-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/54.png","large":"https://images.pokemontcg.io/hgss4/54_hires.png"}',
    searchName: 'Yanmega (TM 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Aipom',
    tcgApiId: 'hgss4-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/55.png","large":"https://images.pokemontcg.io/hgss4/55_hires.png"}',
    searchName: 'Aipom (TM 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Aron',
    tcgApiId: 'hgss4-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/56.png","large":"https://images.pokemontcg.io/hgss4/56_hires.png"}',
    searchName: 'Aron (TM 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Bellsprout',
    tcgApiId: 'hgss4-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/57.png","large":"https://images.pokemontcg.io/hgss4/57_hires.png"}',
    searchName: 'Bellsprout (TM 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Bronzor',
    tcgApiId: 'hgss4-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/58.png","large":"https://images.pokemontcg.io/hgss4/58_hires.png"}',
    searchName: 'Bronzor (TM 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Carvanha',
    tcgApiId: 'hgss4-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/59.png","large":"https://images.pokemontcg.io/hgss4/59_hires.png"}',
    searchName: 'Carvanha (TM 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Cubone',
    tcgApiId: 'hgss4-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/60.png","large":"https://images.pokemontcg.io/hgss4/60_hires.png"}',
    searchName: 'Cubone (TM 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Diglett',
    tcgApiId: 'hgss4-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/61.png","large":"https://images.pokemontcg.io/hgss4/61_hires.png"}',
    searchName: 'Diglett (TM 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Dratini',
    tcgApiId: 'hgss4-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/62.png","large":"https://images.pokemontcg.io/hgss4/62_hires.png"}',
    searchName: 'Dratini (TM 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Gastly',
    tcgApiId: 'hgss4-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/63.png","large":"https://images.pokemontcg.io/hgss4/63_hires.png"}',
    searchName: 'Gastly (TM 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Illumise',
    tcgApiId: 'hgss4-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/64.png","large":"https://images.pokemontcg.io/hgss4/64_hires.png"}',
    searchName: 'Illumise (TM 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Kricketot',
    tcgApiId: 'hgss4-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/65.png","large":"https://images.pokemontcg.io/hgss4/65_hires.png"}',
    searchName: 'Kricketot (TM 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Lickitung',
    tcgApiId: 'hgss4-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/66.png","large":"https://images.pokemontcg.io/hgss4/66_hires.png"}',
    searchName: 'Lickitung (TM 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Machop',
    tcgApiId: 'hgss4-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/67.png","large":"https://images.pokemontcg.io/hgss4/67_hires.png"}',
    searchName: 'Machop (TM 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Magnemite',
    tcgApiId: 'hgss4-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/68.png","large":"https://images.pokemontcg.io/hgss4/68_hires.png"}',
    searchName: 'Magnemite (TM 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Nidoran ♀',
    tcgApiId: 'hgss4-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/69.png","large":"https://images.pokemontcg.io/hgss4/69_hires.png"}',
    searchName: 'Nidoran ♀ (TM 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Nidoran ♂',
    tcgApiId: 'hgss4-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/70.png","large":"https://images.pokemontcg.io/hgss4/70_hires.png"}',
    searchName: 'Nidoran ♂ (TM 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Pidgey',
    tcgApiId: 'hgss4-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/71.png","large":"https://images.pokemontcg.io/hgss4/71_hires.png"}',
    searchName: 'Pidgey (TM 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Ponyta',
    tcgApiId: 'hgss4-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/72.png","large":"https://images.pokemontcg.io/hgss4/72_hires.png"}',
    searchName: 'Ponyta (TM 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Porygon',
    tcgApiId: 'hgss4-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/73.png","large":"https://images.pokemontcg.io/hgss4/73_hires.png"}',
    searchName: 'Porygon (TM 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Psyduck',
    tcgApiId: 'hgss4-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/74.png","large":"https://images.pokemontcg.io/hgss4/74_hires.png"}',
    searchName: 'Psyduck (TM 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Shuppet',
    tcgApiId: 'hgss4-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/75.png","large":"https://images.pokemontcg.io/hgss4/75_hires.png"}',
    searchName: 'Shuppet (TM 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Skorupi',
    tcgApiId: 'hgss4-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/76.png","large":"https://images.pokemontcg.io/hgss4/76_hires.png"}',
    searchName: 'Skorupi (TM 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Spoink',
    tcgApiId: 'hgss4-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/77.png","large":"https://images.pokemontcg.io/hgss4/77_hires.png"}',
    searchName: 'Spoink (TM 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Swablu',
    tcgApiId: 'hgss4-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/78.png","large":"https://images.pokemontcg.io/hgss4/78_hires.png"}',
    searchName: 'Swablu (TM 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Swinub',
    tcgApiId: 'hgss4-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/79.png","large":"https://images.pokemontcg.io/hgss4/79_hires.png"}',
    searchName: 'Swinub (TM 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Tentacool',
    tcgApiId: 'hgss4-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/80.png","large":"https://images.pokemontcg.io/hgss4/80_hires.png"}',
    searchName: 'Tentacool (TM 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Venonat',
    tcgApiId: 'hgss4-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/81.png","large":"https://images.pokemontcg.io/hgss4/81_hires.png"}',
    searchName: 'Venonat (TM 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Volbeat',
    tcgApiId: 'hgss4-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/82.png","large":"https://images.pokemontcg.io/hgss4/82_hires.png"}',
    searchName: 'Volbeat (TM 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Voltorb',
    tcgApiId: 'hgss4-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/83.png","large":"https://images.pokemontcg.io/hgss4/83_hires.png"}',
    searchName: 'Voltorb (TM 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Yanma',
    tcgApiId: 'hgss4-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/84.png","large":"https://images.pokemontcg.io/hgss4/84_hires.png"}',
    searchName: 'Yanma (TM 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Black Belt',
    tcgApiId: 'hgss4-85',
    number: '85',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/85.png","large":"https://images.pokemontcg.io/hgss4/85_hires.png"}',
    searchName: 'Black Belt (TM 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Indigo Plateau',
    tcgApiId: 'hgss4-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/86.png","large":"https://images.pokemontcg.io/hgss4/86_hires.png"}',
    searchName: 'Indigo Plateau (TM 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Junk Arm',
    tcgApiId: 'hgss4-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/87.png","large":"https://images.pokemontcg.io/hgss4/87_hires.png"}',
    searchName: 'Junk Arm (TM 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Seeker',
    tcgApiId: 'hgss4-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/88.png","large":"https://images.pokemontcg.io/hgss4/88_hires.png"}',
    searchName: 'Seeker (TM 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Twins',
    tcgApiId: 'hgss4-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/89.png","large":"https://images.pokemontcg.io/hgss4/89_hires.png"}',
    searchName: 'Twins (TM 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Rescue Energy',
    tcgApiId: 'hgss4-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/90.png","large":"https://images.pokemontcg.io/hgss4/90_hires.png"}',
    searchName: 'Rescue Energy (TM 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Absol',
    tcgApiId: 'hgss4-91',
    number: '91',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/91.png","large":"https://images.pokemontcg.io/hgss4/91_hires.png"}',
    searchName: 'Absol (TM 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Celebi',
    tcgApiId: 'hgss4-92',
    number: '92',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/92.png","large":"https://images.pokemontcg.io/hgss4/92_hires.png"}',
    searchName: 'Celebi (TM 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Electrode',
    tcgApiId: 'hgss4-93',
    number: '93',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/93.png","large":"https://images.pokemontcg.io/hgss4/93_hires.png"}',
    searchName: 'Electrode (TM 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Gengar',
    tcgApiId: 'hgss4-94',
    number: '94',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/94.png","large":"https://images.pokemontcg.io/hgss4/94_hires.png"}',
    searchName: 'Gengar (TM 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Machamp',
    tcgApiId: 'hgss4-95',
    number: '95',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/95.png","large":"https://images.pokemontcg.io/hgss4/95_hires.png"}',
    searchName: 'Machamp (TM 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Magnezone',
    tcgApiId: 'hgss4-96',
    number: '96',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/96.png","large":"https://images.pokemontcg.io/hgss4/96_hires.png"}',
    searchName: 'Magnezone (TM 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Mew',
    tcgApiId: 'hgss4-97',
    number: '97',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/97.png","large":"https://images.pokemontcg.io/hgss4/97_hires.png"}',
    searchName: 'Mew (TM 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Yanmega',
    tcgApiId: 'hgss4-98',
    number: '98',
    rarity: 'Rare Prime',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/98.png","large":"https://images.pokemontcg.io/hgss4/98_hires.png"}',
    searchName: 'Yanmega (TM 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Darkrai & Cresselia LEGEND',
    tcgApiId: 'hgss4-99',
    number: '99',
    rarity: 'LEGEND',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/99.png","large":"https://images.pokemontcg.io/hgss4/99_hires.png"}',
    searchName: 'Darkrai & Cresselia LEGEND (TM 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Darkrai & Cresselia LEGEND',
    tcgApiId: 'hgss4-100',
    number: '100',
    rarity: 'LEGEND',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/100.png","large":"https://images.pokemontcg.io/hgss4/100_hires.png"}',
    searchName: 'Darkrai & Cresselia LEGEND (TM 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Palkia & Dialga LEGEND',
    tcgApiId: 'hgss4-101',
    number: '101',
    rarity: 'LEGEND',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/101.png","large":"https://images.pokemontcg.io/hgss4/101_hires.png"}',
    searchName: 'Palkia & Dialga LEGEND (TM 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Palkia & Dialga LEGEND',
    tcgApiId: 'hgss4-102',
    number: '102',
    rarity: 'LEGEND',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/102.png","large":"https://images.pokemontcg.io/hgss4/102_hires.png"}',
    searchName: 'Palkia & Dialga LEGEND (TM 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'hgss4',
    name: 'Alph Lithograph',
    tcgApiId: 'hgss4-FOUR',
    number: 'FOUR',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/hgss4/FOUR.png","large":"https://images.pokemontcg.io/hgss4/FOUR_hires.png"}',
    searchName: 'Alph Lithograph (TM FOUR)',
  },
];
