export const cardSeedMcd22 = [
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Ledyba',
    tcgApiId: 'mcd22-1',
    number: '1',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/1.png","large":"https://images.pokemontcg.io/mcd22/1_hires.png"}',
    searchName: 'Ledyba (undefined 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Rowlet',
    tcgApiId: 'mcd22-2',
    number: '2',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/2.png","large":"https://images.pokemontcg.io/mcd22/2_hires.png"}',
    searchName: 'Rowlet (undefined 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Gossifleur',
    tcgApiId: 'mcd22-3',
    number: '3',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/3.png","large":"https://images.pokemontcg.io/mcd22/3_hires.png"}',
    searchName: 'Gossifleur (undefined 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Growlithe',
    tcgApiId: 'mcd22-4',
    number: '4',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/4.png","large":"https://images.pokemontcg.io/mcd22/4_hires.png"}',
    searchName: 'Growlithe (undefined 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Victini',
    tcgApiId: 'mcd22-5',
    number: '5',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/5.png","large":"https://images.pokemontcg.io/mcd22/5_hires.png"}',
    searchName: 'Victini (undefined 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Lapras',
    tcgApiId: 'mcd22-6',
    number: '6',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/6.png","large":"https://images.pokemontcg.io/mcd22/6_hires.png"}',
    searchName: 'Lapras (undefined 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Pikachu',
    tcgApiId: 'mcd22-7',
    number: '7',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/7.png","large":"https://images.pokemontcg.io/mcd22/7_hires.png"}',
    searchName: 'Pikachu (undefined 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Chinchou',
    tcgApiId: 'mcd22-8',
    number: '8',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/8.png","large":"https://images.pokemontcg.io/mcd22/8_hires.png"}',
    searchName: 'Chinchou (undefined 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Flaaffy',
    tcgApiId: 'mcd22-9',
    number: '9',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/9.png","large":"https://images.pokemontcg.io/mcd22/9_hires.png"}',
    searchName: 'Flaaffy (undefined 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Tynamo',
    tcgApiId: 'mcd22-10',
    number: '10',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/10.png","large":"https://images.pokemontcg.io/mcd22/10_hires.png"}',
    searchName: 'Tynamo (undefined 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Cutiefly',
    tcgApiId: 'mcd22-11',
    number: '11',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/11.png","large":"https://images.pokemontcg.io/mcd22/11_hires.png"}',
    searchName: 'Cutiefly (undefined 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Bewear',
    tcgApiId: 'mcd22-12',
    number: '12',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/12.png","large":"https://images.pokemontcg.io/mcd22/12_hires.png"}',
    searchName: 'Bewear (undefined 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Pangoro',
    tcgApiId: 'mcd22-13',
    number: '13',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/13.png","large":"https://images.pokemontcg.io/mcd22/13_hires.png"}',
    searchName: 'Pangoro (undefined 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Drampa',
    tcgApiId: 'mcd22-14',
    number: '14',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/14.png","large":"https://images.pokemontcg.io/mcd22/14_hires.png"}',
    searchName: 'Drampa (undefined 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd22',
    name: 'Smeargle',
    tcgApiId: 'mcd22-15',
    number: '15',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd22/15.png","large":"https://images.pokemontcg.io/mcd22/15_hires.png"}',
    searchName: 'Smeargle (undefined 15)',
  },
];
