export const cardSeedMcd21 = [
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Bulbasaur',
    tcgApiId: 'mcd21-1',
    number: '1',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/1.png","large":"https://images.pokemontcg.io/mcd21/1_hires.png"}',
    searchName: 'Bulbasaur (undefined 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Chikorita',
    tcgApiId: 'mcd21-2',
    number: '2',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/2.png","large":"https://images.pokemontcg.io/mcd21/2_hires.png"}',
    searchName: 'Chikorita (undefined 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Treecko',
    tcgApiId: 'mcd21-3',
    number: '3',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/3.png","large":"https://images.pokemontcg.io/mcd21/3_hires.png"}',
    searchName: 'Treecko (undefined 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Turtwig',
    tcgApiId: 'mcd21-4',
    number: '4',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/4.png","large":"https://images.pokemontcg.io/mcd21/4_hires.png"}',
    searchName: 'Turtwig (undefined 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Snivy',
    tcgApiId: 'mcd21-5',
    number: '5',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/5.png","large":"https://images.pokemontcg.io/mcd21/5_hires.png"}',
    searchName: 'Snivy (undefined 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Chespin',
    tcgApiId: 'mcd21-6',
    number: '6',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/6.png","large":"https://images.pokemontcg.io/mcd21/6_hires.png"}',
    searchName: 'Chespin (undefined 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Rowlet',
    tcgApiId: 'mcd21-7',
    number: '7',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/7.png","large":"https://images.pokemontcg.io/mcd21/7_hires.png"}',
    searchName: 'Rowlet (undefined 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Grookey',
    tcgApiId: 'mcd21-8',
    number: '8',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/8.png","large":"https://images.pokemontcg.io/mcd21/8_hires.png"}',
    searchName: 'Grookey (undefined 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Charmander',
    tcgApiId: 'mcd21-9',
    number: '9',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/9.png","large":"https://images.pokemontcg.io/mcd21/9_hires.png"}',
    searchName: 'Charmander (undefined 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Cyndaquil',
    tcgApiId: 'mcd21-10',
    number: '10',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/10.png","large":"https://images.pokemontcg.io/mcd21/10_hires.png"}',
    searchName: 'Cyndaquil (undefined 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Torchic',
    tcgApiId: 'mcd21-11',
    number: '11',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/11.png","large":"https://images.pokemontcg.io/mcd21/11_hires.png"}',
    searchName: 'Torchic (undefined 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Chimchar',
    tcgApiId: 'mcd21-12',
    number: '12',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/12.png","large":"https://images.pokemontcg.io/mcd21/12_hires.png"}',
    searchName: 'Chimchar (undefined 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Tepig',
    tcgApiId: 'mcd21-13',
    number: '13',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/13.png","large":"https://images.pokemontcg.io/mcd21/13_hires.png"}',
    searchName: 'Tepig (undefined 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Fennekin',
    tcgApiId: 'mcd21-14',
    number: '14',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/14.png","large":"https://images.pokemontcg.io/mcd21/14_hires.png"}',
    searchName: 'Fennekin (undefined 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Litten',
    tcgApiId: 'mcd21-15',
    number: '15',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/15.png","large":"https://images.pokemontcg.io/mcd21/15_hires.png"}',
    searchName: 'Litten (undefined 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Scorbunny',
    tcgApiId: 'mcd21-16',
    number: '16',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/16.png","large":"https://images.pokemontcg.io/mcd21/16_hires.png"}',
    searchName: 'Scorbunny (undefined 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Squirtle',
    tcgApiId: 'mcd21-17',
    number: '17',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/17.png","large":"https://images.pokemontcg.io/mcd21/17_hires.png"}',
    searchName: 'Squirtle (undefined 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Totodile',
    tcgApiId: 'mcd21-18',
    number: '18',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/18.png","large":"https://images.pokemontcg.io/mcd21/18_hires.png"}',
    searchName: 'Totodile (undefined 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Mudkip',
    tcgApiId: 'mcd21-19',
    number: '19',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/19.png","large":"https://images.pokemontcg.io/mcd21/19_hires.png"}',
    searchName: 'Mudkip (undefined 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Piplup',
    tcgApiId: 'mcd21-20',
    number: '20',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/20.png","large":"https://images.pokemontcg.io/mcd21/20_hires.png"}',
    searchName: 'Piplup (undefined 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Oshawott',
    tcgApiId: 'mcd21-21',
    number: '21',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/21.png","large":"https://images.pokemontcg.io/mcd21/21_hires.png"}',
    searchName: 'Oshawott (undefined 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Froakie',
    tcgApiId: 'mcd21-22',
    number: '22',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/22.png","large":"https://images.pokemontcg.io/mcd21/22_hires.png"}',
    searchName: 'Froakie (undefined 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Popplio',
    tcgApiId: 'mcd21-23',
    number: '23',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/23.png","large":"https://images.pokemontcg.io/mcd21/23_hires.png"}',
    searchName: 'Popplio (undefined 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Sobble',
    tcgApiId: 'mcd21-24',
    number: '24',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/24.png","large":"https://images.pokemontcg.io/mcd21/24_hires.png"}',
    searchName: 'Sobble (undefined 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'mcd21',
    name: 'Pikachu',
    tcgApiId: 'mcd21-25',
    number: '25',
    rarity: '',
    images:
      '{"small":"https://images.pokemontcg.io/mcd21/25.png","large":"https://images.pokemontcg.io/mcd21/25_hires.png"}',
    searchName: 'Pikachu (undefined 25)',
  },
];
