export const cardSeedNeo4 = [
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Ampharos',
    tcgApiId: 'neo4-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/1.png","large":"https://images.pokemontcg.io/neo4/1_hires.png"}',
    searchName: 'Dark Ampharos (N4 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Crobat',
    tcgApiId: 'neo4-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/2.png","large":"https://images.pokemontcg.io/neo4/2_hires.png"}',
    searchName: 'Dark Crobat (N4 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Donphan',
    tcgApiId: 'neo4-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/3.png","large":"https://images.pokemontcg.io/neo4/3_hires.png"}',
    searchName: 'Dark Donphan (N4 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Espeon',
    tcgApiId: 'neo4-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/4.png","large":"https://images.pokemontcg.io/neo4/4_hires.png"}',
    searchName: 'Dark Espeon (N4 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Feraligatr',
    tcgApiId: 'neo4-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/5.png","large":"https://images.pokemontcg.io/neo4/5_hires.png"}',
    searchName: 'Dark Feraligatr (N4 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Gengar',
    tcgApiId: 'neo4-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/6.png","large":"https://images.pokemontcg.io/neo4/6_hires.png"}',
    searchName: 'Dark Gengar (N4 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Houndoom',
    tcgApiId: 'neo4-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/7.png","large":"https://images.pokemontcg.io/neo4/7_hires.png"}',
    searchName: 'Dark Houndoom (N4 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Porygon2',
    tcgApiId: 'neo4-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/8.png","large":"https://images.pokemontcg.io/neo4/8_hires.png"}',
    searchName: 'Dark Porygon2 (N4 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Scizor',
    tcgApiId: 'neo4-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/9.png","large":"https://images.pokemontcg.io/neo4/9_hires.png"}',
    searchName: 'Dark Scizor (N4 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Typhlosion',
    tcgApiId: 'neo4-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/10.png","large":"https://images.pokemontcg.io/neo4/10_hires.png"}',
    searchName: 'Dark Typhlosion (N4 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Tyranitar',
    tcgApiId: 'neo4-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/11.png","large":"https://images.pokemontcg.io/neo4/11_hires.png"}',
    searchName: 'Dark Tyranitar (N4 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Arcanine',
    tcgApiId: 'neo4-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/12.png","large":"https://images.pokemontcg.io/neo4/12_hires.png"}',
    searchName: 'Light Arcanine (N4 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Azumarill',
    tcgApiId: 'neo4-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/13.png","large":"https://images.pokemontcg.io/neo4/13_hires.png"}',
    searchName: 'Light Azumarill (N4 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Dragonite',
    tcgApiId: 'neo4-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/14.png","large":"https://images.pokemontcg.io/neo4/14_hires.png"}',
    searchName: 'Light Dragonite (N4 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Togetic',
    tcgApiId: 'neo4-15',
    number: '15',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/15.png","large":"https://images.pokemontcg.io/neo4/15_hires.png"}',
    searchName: 'Light Togetic (N4 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Miracle Energy',
    tcgApiId: 'neo4-16',
    number: '16',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/16.png","large":"https://images.pokemontcg.io/neo4/16_hires.png"}',
    searchName: 'Miracle Energy (N4 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Ariados',
    tcgApiId: 'neo4-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/17.png","large":"https://images.pokemontcg.io/neo4/17_hires.png"}',
    searchName: 'Dark Ariados (N4 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Magcargo',
    tcgApiId: 'neo4-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/18.png","large":"https://images.pokemontcg.io/neo4/18_hires.png"}',
    searchName: 'Dark Magcargo (N4 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Omastar',
    tcgApiId: 'neo4-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/19.png","large":"https://images.pokemontcg.io/neo4/19_hires.png"}',
    searchName: 'Dark Omastar (N4 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Slowking',
    tcgApiId: 'neo4-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/20.png","large":"https://images.pokemontcg.io/neo4/20_hires.png"}',
    searchName: 'Dark Slowking (N4 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Ursaring',
    tcgApiId: 'neo4-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/21.png","large":"https://images.pokemontcg.io/neo4/21_hires.png"}',
    searchName: 'Dark Ursaring (N4 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Dragonair',
    tcgApiId: 'neo4-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/22.png","large":"https://images.pokemontcg.io/neo4/22_hires.png"}',
    searchName: 'Light Dragonair (N4 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Lanturn',
    tcgApiId: 'neo4-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/23.png","large":"https://images.pokemontcg.io/neo4/23_hires.png"}',
    searchName: 'Light Lanturn (N4 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Ledian',
    tcgApiId: 'neo4-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/24.png","large":"https://images.pokemontcg.io/neo4/24_hires.png"}',
    searchName: 'Light Ledian (N4 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Machamp',
    tcgApiId: 'neo4-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/25.png","large":"https://images.pokemontcg.io/neo4/25_hires.png"}',
    searchName: 'Light Machamp (N4 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Piloswine',
    tcgApiId: 'neo4-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/26.png","large":"https://images.pokemontcg.io/neo4/26_hires.png"}',
    searchName: 'Light Piloswine (N4 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [G]',
    tcgApiId: 'neo4-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/27.png","large":"https://images.pokemontcg.io/neo4/27_hires.png"}',
    searchName: 'Unown [G] (N4 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [H]',
    tcgApiId: 'neo4-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/28.png","large":"https://images.pokemontcg.io/neo4/28_hires.png"}',
    searchName: 'Unown [H] (N4 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [W]',
    tcgApiId: 'neo4-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/29.png","large":"https://images.pokemontcg.io/neo4/29_hires.png"}',
    searchName: 'Unown [W] (N4 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [X]',
    tcgApiId: 'neo4-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/30.png","large":"https://images.pokemontcg.io/neo4/30_hires.png"}',
    searchName: 'Unown [X] (N4 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Chansey',
    tcgApiId: 'neo4-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/31.png","large":"https://images.pokemontcg.io/neo4/31_hires.png"}',
    searchName: 'Chansey (N4 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Croconaw',
    tcgApiId: 'neo4-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/32.png","large":"https://images.pokemontcg.io/neo4/32_hires.png"}',
    searchName: 'Dark Croconaw (N4 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Exeggutor',
    tcgApiId: 'neo4-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/33.png","large":"https://images.pokemontcg.io/neo4/33_hires.png"}',
    searchName: 'Dark Exeggutor (N4 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Flaaffy',
    tcgApiId: 'neo4-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/34.png","large":"https://images.pokemontcg.io/neo4/34_hires.png"}',
    searchName: 'Dark Flaaffy (N4 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Forretress',
    tcgApiId: 'neo4-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/35.png","large":"https://images.pokemontcg.io/neo4/35_hires.png"}',
    searchName: 'Dark Forretress (N4 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Haunter',
    tcgApiId: 'neo4-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/36.png","large":"https://images.pokemontcg.io/neo4/36_hires.png"}',
    searchName: 'Dark Haunter (N4 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Omanyte',
    tcgApiId: 'neo4-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/37.png","large":"https://images.pokemontcg.io/neo4/37_hires.png"}',
    searchName: 'Dark Omanyte (N4 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Pupitar',
    tcgApiId: 'neo4-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/38.png","large":"https://images.pokemontcg.io/neo4/38_hires.png"}',
    searchName: 'Dark Pupitar (N4 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Quilava',
    tcgApiId: 'neo4-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/39.png","large":"https://images.pokemontcg.io/neo4/39_hires.png"}',
    searchName: 'Dark Quilava (N4 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Wigglytuff',
    tcgApiId: 'neo4-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/40.png","large":"https://images.pokemontcg.io/neo4/40_hires.png"}',
    searchName: 'Dark Wigglytuff (N4 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Heracross',
    tcgApiId: 'neo4-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/41.png","large":"https://images.pokemontcg.io/neo4/41_hires.png"}',
    searchName: 'Heracross (N4 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Hitmonlee',
    tcgApiId: 'neo4-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/42.png","large":"https://images.pokemontcg.io/neo4/42_hires.png"}',
    searchName: 'Hitmonlee (N4 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Houndour',
    tcgApiId: 'neo4-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/43.png","large":"https://images.pokemontcg.io/neo4/43_hires.png"}',
    searchName: 'Houndour (N4 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Jigglypuff',
    tcgApiId: 'neo4-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/44.png","large":"https://images.pokemontcg.io/neo4/44_hires.png"}',
    searchName: 'Jigglypuff (N4 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Dewgong',
    tcgApiId: 'neo4-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/45.png","large":"https://images.pokemontcg.io/neo4/45_hires.png"}',
    searchName: 'Light Dewgong (N4 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Flareon',
    tcgApiId: 'neo4-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/46.png","large":"https://images.pokemontcg.io/neo4/46_hires.png"}',
    searchName: 'Light Flareon (N4 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Golduck',
    tcgApiId: 'neo4-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/47.png","large":"https://images.pokemontcg.io/neo4/47_hires.png"}',
    searchName: 'Light Golduck (N4 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Jolteon',
    tcgApiId: 'neo4-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/48.png","large":"https://images.pokemontcg.io/neo4/48_hires.png"}',
    searchName: 'Light Jolteon (N4 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Machoke',
    tcgApiId: 'neo4-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/49.png","large":"https://images.pokemontcg.io/neo4/49_hires.png"}',
    searchName: 'Light Machoke (N4 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Ninetales',
    tcgApiId: 'neo4-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/50.png","large":"https://images.pokemontcg.io/neo4/50_hires.png"}',
    searchName: 'Light Ninetales (N4 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Slowbro',
    tcgApiId: 'neo4-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/51.png","large":"https://images.pokemontcg.io/neo4/51_hires.png"}',
    searchName: 'Light Slowbro (N4 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Vaporeon',
    tcgApiId: 'neo4-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/52.png","large":"https://images.pokemontcg.io/neo4/52_hires.png"}',
    searchName: 'Light Vaporeon (N4 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Venomoth',
    tcgApiId: 'neo4-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/53.png","large":"https://images.pokemontcg.io/neo4/53_hires.png"}',
    searchName: 'Light Venomoth (N4 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Wigglytuff',
    tcgApiId: 'neo4-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/54.png","large":"https://images.pokemontcg.io/neo4/54_hires.png"}',
    searchName: 'Light Wigglytuff (N4 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Scyther',
    tcgApiId: 'neo4-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/55.png","large":"https://images.pokemontcg.io/neo4/55_hires.png"}',
    searchName: 'Scyther (N4 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Togepi',
    tcgApiId: 'neo4-56',
    number: '56',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/56.png","large":"https://images.pokemontcg.io/neo4/56_hires.png"}',
    searchName: 'Togepi (N4 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [C]',
    tcgApiId: 'neo4-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/57.png","large":"https://images.pokemontcg.io/neo4/57_hires.png"}',
    searchName: 'Unown [C] (N4 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [P]',
    tcgApiId: 'neo4-58',
    number: '58',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/58.png","large":"https://images.pokemontcg.io/neo4/58_hires.png"}',
    searchName: 'Unown [P] (N4 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [Q]',
    tcgApiId: 'neo4-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/59.png","large":"https://images.pokemontcg.io/neo4/59_hires.png"}',
    searchName: 'Unown [Q] (N4 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [Z]',
    tcgApiId: 'neo4-60',
    number: '60',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/60.png","large":"https://images.pokemontcg.io/neo4/60_hires.png"}',
    searchName: 'Unown [Z] (N4 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Cyndaquil',
    tcgApiId: 'neo4-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/61.png","large":"https://images.pokemontcg.io/neo4/61_hires.png"}',
    searchName: 'Cyndaquil (N4 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dark Octillery',
    tcgApiId: 'neo4-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/62.png","large":"https://images.pokemontcg.io/neo4/62_hires.png"}',
    searchName: 'Dark Octillery (N4 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Dratini',
    tcgApiId: 'neo4-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/63.png","large":"https://images.pokemontcg.io/neo4/63_hires.png"}',
    searchName: 'Dratini (N4 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Exeggcute',
    tcgApiId: 'neo4-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/64.png","large":"https://images.pokemontcg.io/neo4/64_hires.png"}',
    searchName: 'Exeggcute (N4 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Gastly',
    tcgApiId: 'neo4-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/65.png","large":"https://images.pokemontcg.io/neo4/65_hires.png"}',
    searchName: 'Gastly (N4 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Girafarig',
    tcgApiId: 'neo4-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/66.png","large":"https://images.pokemontcg.io/neo4/66_hires.png"}',
    searchName: 'Girafarig (N4 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Gligar',
    tcgApiId: 'neo4-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/67.png","large":"https://images.pokemontcg.io/neo4/67_hires.png"}',
    searchName: 'Gligar (N4 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Growlithe',
    tcgApiId: 'neo4-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/68.png","large":"https://images.pokemontcg.io/neo4/68_hires.png"}',
    searchName: 'Growlithe (N4 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Hitmonchan',
    tcgApiId: 'neo4-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/69.png","large":"https://images.pokemontcg.io/neo4/69_hires.png"}',
    searchName: 'Hitmonchan (N4 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Larvitar',
    tcgApiId: 'neo4-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/70.png","large":"https://images.pokemontcg.io/neo4/70_hires.png"}',
    searchName: 'Larvitar (N4 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Ledyba',
    tcgApiId: 'neo4-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/71.png","large":"https://images.pokemontcg.io/neo4/71_hires.png"}',
    searchName: 'Ledyba (N4 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Light Sunflora',
    tcgApiId: 'neo4-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/72.png","large":"https://images.pokemontcg.io/neo4/72_hires.png"}',
    searchName: 'Light Sunflora (N4 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Machop',
    tcgApiId: 'neo4-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/73.png","large":"https://images.pokemontcg.io/neo4/73_hires.png"}',
    searchName: 'Machop (N4 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Mantine',
    tcgApiId: 'neo4-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/74.png","large":"https://images.pokemontcg.io/neo4/74_hires.png"}',
    searchName: 'Mantine (N4 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Mareep',
    tcgApiId: 'neo4-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/75.png","large":"https://images.pokemontcg.io/neo4/75_hires.png"}',
    searchName: 'Mareep (N4 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Phanpy',
    tcgApiId: 'neo4-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/76.png","large":"https://images.pokemontcg.io/neo4/76_hires.png"}',
    searchName: 'Phanpy (N4 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Pineco',
    tcgApiId: 'neo4-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/77.png","large":"https://images.pokemontcg.io/neo4/77_hires.png"}',
    searchName: 'Pineco (N4 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Porygon',
    tcgApiId: 'neo4-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/78.png","large":"https://images.pokemontcg.io/neo4/78_hires.png"}',
    searchName: 'Porygon (N4 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Psyduck',
    tcgApiId: 'neo4-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/79.png","large":"https://images.pokemontcg.io/neo4/79_hires.png"}',
    searchName: 'Psyduck (N4 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Remoraid',
    tcgApiId: 'neo4-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/80.png","large":"https://images.pokemontcg.io/neo4/80_hires.png"}',
    searchName: 'Remoraid (N4 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Seel',
    tcgApiId: 'neo4-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/81.png","large":"https://images.pokemontcg.io/neo4/81_hires.png"}',
    searchName: 'Seel (N4 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Slugma',
    tcgApiId: 'neo4-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/82.png","large":"https://images.pokemontcg.io/neo4/82_hires.png"}',
    searchName: 'Slugma (N4 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Sunkern',
    tcgApiId: 'neo4-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/83.png","large":"https://images.pokemontcg.io/neo4/83_hires.png"}',
    searchName: 'Sunkern (N4 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Swinub',
    tcgApiId: 'neo4-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/84.png","large":"https://images.pokemontcg.io/neo4/84_hires.png"}',
    searchName: 'Swinub (N4 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Totodile',
    tcgApiId: 'neo4-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/85.png","large":"https://images.pokemontcg.io/neo4/85_hires.png"}',
    searchName: 'Totodile (N4 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [L]',
    tcgApiId: 'neo4-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/86.png","large":"https://images.pokemontcg.io/neo4/86_hires.png"}',
    searchName: 'Unown [L] (N4 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [S]',
    tcgApiId: 'neo4-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/87.png","large":"https://images.pokemontcg.io/neo4/87_hires.png"}',
    searchName: 'Unown [S] (N4 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [T]',
    tcgApiId: 'neo4-88',
    number: '88',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/88.png","large":"https://images.pokemontcg.io/neo4/88_hires.png"}',
    searchName: 'Unown [T] (N4 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Unown [V]',
    tcgApiId: 'neo4-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/89.png","large":"https://images.pokemontcg.io/neo4/89_hires.png"}',
    searchName: 'Unown [V] (N4 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Venonat',
    tcgApiId: 'neo4-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/90.png","large":"https://images.pokemontcg.io/neo4/90_hires.png"}',
    searchName: 'Venonat (N4 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Vulpix',
    tcgApiId: 'neo4-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/91.png","large":"https://images.pokemontcg.io/neo4/91_hires.png"}',
    searchName: 'Vulpix (N4 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Broken Ground Gym',
    tcgApiId: 'neo4-92',
    number: '92',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/92.png","large":"https://images.pokemontcg.io/neo4/92_hires.png"}',
    searchName: 'Broken Ground Gym (N4 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'EXP.ALL',
    tcgApiId: 'neo4-93',
    number: '93',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/93.png","large":"https://images.pokemontcg.io/neo4/93_hires.png"}',
    searchName: 'EXP.ALL (N4 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: "Impostor Professor Oak's Invention",
    tcgApiId: 'neo4-94',
    number: '94',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/94.png","large":"https://images.pokemontcg.io/neo4/94_hires.png"}',
    searchName: "Impostor Professor Oak's Invention (N4 94)",
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Radio Tower',
    tcgApiId: 'neo4-95',
    number: '95',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/95.png","large":"https://images.pokemontcg.io/neo4/95_hires.png"}',
    searchName: 'Radio Tower (N4 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Thought Wave Machine',
    tcgApiId: 'neo4-96',
    number: '96',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/96.png","large":"https://images.pokemontcg.io/neo4/96_hires.png"}',
    searchName: 'Thought Wave Machine (N4 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Counterattack Claws',
    tcgApiId: 'neo4-97',
    number: '97',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/97.png","large":"https://images.pokemontcg.io/neo4/97_hires.png"}',
    searchName: 'Counterattack Claws (N4 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Energy Amplifier',
    tcgApiId: 'neo4-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/98.png","large":"https://images.pokemontcg.io/neo4/98_hires.png"}',
    searchName: 'Energy Amplifier (N4 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Energy Stadium',
    tcgApiId: 'neo4-99',
    number: '99',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/99.png","large":"https://images.pokemontcg.io/neo4/99_hires.png"}',
    searchName: 'Energy Stadium (N4 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Lucky Stadium',
    tcgApiId: 'neo4-100',
    number: '100',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/100.png","large":"https://images.pokemontcg.io/neo4/100_hires.png"}',
    searchName: 'Lucky Stadium (N4 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Magnifier',
    tcgApiId: 'neo4-101',
    number: '101',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/101.png","large":"https://images.pokemontcg.io/neo4/101_hires.png"}',
    searchName: 'Magnifier (N4 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Pokémon Personality Test',
    tcgApiId: 'neo4-102',
    number: '102',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/102.png","large":"https://images.pokemontcg.io/neo4/102_hires.png"}',
    searchName: 'Pokémon Personality Test (N4 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: "Team Rocket's Evil Deeds",
    tcgApiId: 'neo4-103',
    number: '103',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/103.png","large":"https://images.pokemontcg.io/neo4/103_hires.png"}',
    searchName: "Team Rocket's Evil Deeds (N4 103)",
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Heal Powder',
    tcgApiId: 'neo4-104',
    number: '104',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/104.png","large":"https://images.pokemontcg.io/neo4/104_hires.png"}',
    searchName: 'Heal Powder (N4 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Mail from Bill',
    tcgApiId: 'neo4-105',
    number: '105',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/105.png","large":"https://images.pokemontcg.io/neo4/105_hires.png"}',
    searchName: 'Mail from Bill (N4 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Shining Celebi',
    tcgApiId: 'neo4-106',
    number: '106',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/106.png","large":"https://images.pokemontcg.io/neo4/106_hires.png"}',
    searchName: 'Shining Celebi (N4 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Shining Charizard',
    tcgApiId: 'neo4-107',
    number: '107',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/107.png","large":"https://images.pokemontcg.io/neo4/107_hires.png"}',
    searchName: 'Shining Charizard (N4 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Shining Kabutops',
    tcgApiId: 'neo4-108',
    number: '108',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/108.png","large":"https://images.pokemontcg.io/neo4/108_hires.png"}',
    searchName: 'Shining Kabutops (N4 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Shining Mewtwo',
    tcgApiId: 'neo4-109',
    number: '109',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/109.png","large":"https://images.pokemontcg.io/neo4/109_hires.png"}',
    searchName: 'Shining Mewtwo (N4 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Shining Noctowl',
    tcgApiId: 'neo4-110',
    number: '110',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/110.png","large":"https://images.pokemontcg.io/neo4/110_hires.png"}',
    searchName: 'Shining Noctowl (N4 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Shining Raichu',
    tcgApiId: 'neo4-111',
    number: '111',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/111.png","large":"https://images.pokemontcg.io/neo4/111_hires.png"}',
    searchName: 'Shining Raichu (N4 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Shining Steelix',
    tcgApiId: 'neo4-112',
    number: '112',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/112.png","large":"https://images.pokemontcg.io/neo4/112_hires.png"}',
    searchName: 'Shining Steelix (N4 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'neo4',
    name: 'Shining Tyranitar',
    tcgApiId: 'neo4-113',
    number: '113',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/neo4/113.png","large":"https://images.pokemontcg.io/neo4/113_hires.png"}',
    searchName: 'Shining Tyranitar (N4 113)',
  },
];
