export const cardSeedPl2 = [
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Arcanine',
    tcgApiId: 'pl2-1',
    number: '1',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/1.png","large":"https://images.pokemontcg.io/pl2/1_hires.png"}',
    searchName: 'Arcanine (RR 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Bastiodon GL',
    tcgApiId: 'pl2-2',
    number: '2',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/2.png","large":"https://images.pokemontcg.io/pl2/2_hires.png"}',
    searchName: 'Bastiodon GL (RR 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Darkrai G',
    tcgApiId: 'pl2-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/3.png","large":"https://images.pokemontcg.io/pl2/3_hires.png"}',
    searchName: 'Darkrai G (RR 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Floatzel GL',
    tcgApiId: 'pl2-4',
    number: '4',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/4.png","large":"https://images.pokemontcg.io/pl2/4_hires.png"}',
    searchName: 'Floatzel GL (RR 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Flygon',
    tcgApiId: 'pl2-5',
    number: '5',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/5.png","large":"https://images.pokemontcg.io/pl2/5_hires.png"}',
    searchName: 'Flygon (RR 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Froslass GL',
    tcgApiId: 'pl2-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/6.png","large":"https://images.pokemontcg.io/pl2/6_hires.png"}',
    searchName: 'Froslass GL (RR 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Jirachi',
    tcgApiId: 'pl2-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/7.png","large":"https://images.pokemontcg.io/pl2/7_hires.png"}',
    searchName: 'Jirachi (RR 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Lucario GL',
    tcgApiId: 'pl2-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/8.png","large":"https://images.pokemontcg.io/pl2/8_hires.png"}',
    searchName: 'Lucario GL (RR 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Luxray GL',
    tcgApiId: 'pl2-9',
    number: '9',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/9.png","large":"https://images.pokemontcg.io/pl2/9_hires.png"}',
    searchName: 'Luxray GL (RR 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Mismagius GL',
    tcgApiId: 'pl2-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/10.png","large":"https://images.pokemontcg.io/pl2/10_hires.png"}',
    searchName: 'Mismagius GL (RR 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Rampardos GL',
    tcgApiId: 'pl2-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/11.png","large":"https://images.pokemontcg.io/pl2/11_hires.png"}',
    searchName: 'Rampardos GL (RR 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Roserade GL',
    tcgApiId: 'pl2-12',
    number: '12',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/12.png","large":"https://images.pokemontcg.io/pl2/12_hires.png"}',
    searchName: 'Roserade GL (RR 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Shiftry',
    tcgApiId: 'pl2-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/13.png","large":"https://images.pokemontcg.io/pl2/13_hires.png"}',
    searchName: 'Shiftry (RR 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Aggron',
    tcgApiId: 'pl2-14',
    number: '14',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/14.png","large":"https://images.pokemontcg.io/pl2/14_hires.png"}',
    searchName: 'Aggron (RR 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Beedrill',
    tcgApiId: 'pl2-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/15.png","large":"https://images.pokemontcg.io/pl2/15_hires.png"}',
    searchName: 'Beedrill (RR 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Bronzong E4',
    tcgApiId: 'pl2-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/16.png","large":"https://images.pokemontcg.io/pl2/16_hires.png"}',
    searchName: 'Bronzong E4 (RR 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Drapion E4',
    tcgApiId: 'pl2-17',
    number: '17',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/17.png","large":"https://images.pokemontcg.io/pl2/17_hires.png"}',
    searchName: 'Drapion E4 (RR 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Espeon E4',
    tcgApiId: 'pl2-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/18.png","large":"https://images.pokemontcg.io/pl2/18_hires.png"}',
    searchName: 'Espeon E4 (RR 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Flareon',
    tcgApiId: 'pl2-19',
    number: '19',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/19.png","large":"https://images.pokemontcg.io/pl2/19_hires.png"}',
    searchName: 'Flareon (RR 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Gallade E4',
    tcgApiId: 'pl2-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/20.png","large":"https://images.pokemontcg.io/pl2/20_hires.png"}',
    searchName: 'Gallade E4 (RR 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Gastrodon East Sea',
    tcgApiId: 'pl2-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/21.png","large":"https://images.pokemontcg.io/pl2/21_hires.png"}',
    searchName: 'Gastrodon East Sea (RR 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Gastrodon West Sea',
    tcgApiId: 'pl2-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/22.png","large":"https://images.pokemontcg.io/pl2/22_hires.png"}',
    searchName: 'Gastrodon West Sea (RR 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Golem E4',
    tcgApiId: 'pl2-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/23.png","large":"https://images.pokemontcg.io/pl2/23_hires.png"}',
    searchName: 'Golem E4 (RR 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Heracross E4',
    tcgApiId: 'pl2-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/24.png","large":"https://images.pokemontcg.io/pl2/24_hires.png"}',
    searchName: 'Heracross E4 (RR 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Hippowdon',
    tcgApiId: 'pl2-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/25.png","large":"https://images.pokemontcg.io/pl2/25_hires.png"}',
    searchName: 'Hippowdon (RR 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Jolteon',
    tcgApiId: 'pl2-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/26.png","large":"https://images.pokemontcg.io/pl2/26_hires.png"}',
    searchName: 'Jolteon (RR 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Mamoswine GL',
    tcgApiId: 'pl2-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/27.png","large":"https://images.pokemontcg.io/pl2/27_hires.png"}',
    searchName: 'Mamoswine GL (RR 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Mr. Mime E4',
    tcgApiId: 'pl2-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/28.png","large":"https://images.pokemontcg.io/pl2/28_hires.png"}',
    searchName: 'Mr. Mime E4 (RR 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Nidoking',
    tcgApiId: 'pl2-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/29.png","large":"https://images.pokemontcg.io/pl2/29_hires.png"}',
    searchName: 'Nidoking (RR 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Nidoqueen',
    tcgApiId: 'pl2-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/30.png","large":"https://images.pokemontcg.io/pl2/30_hires.png"}',
    searchName: 'Nidoqueen (RR 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Raichu GL',
    tcgApiId: 'pl2-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/31.png","large":"https://images.pokemontcg.io/pl2/31_hires.png"}',
    searchName: 'Raichu GL (RR 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Rhyperior E4',
    tcgApiId: 'pl2-32',
    number: '32',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/32.png","large":"https://images.pokemontcg.io/pl2/32_hires.png"}',
    searchName: 'Rhyperior E4 (RR 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Snorlax',
    tcgApiId: 'pl2-33',
    number: '33',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/33.png","large":"https://images.pokemontcg.io/pl2/33_hires.png"}',
    searchName: 'Snorlax (RR 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Vaporeon',
    tcgApiId: 'pl2-34',
    number: '34',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/34.png","large":"https://images.pokemontcg.io/pl2/34_hires.png"}',
    searchName: 'Vaporeon (RR 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Vespiquen E4',
    tcgApiId: 'pl2-35',
    number: '35',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/35.png","large":"https://images.pokemontcg.io/pl2/35_hires.png"}',
    searchName: 'Vespiquen E4 (RR 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Walrein',
    tcgApiId: 'pl2-36',
    number: '36',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/36.png","large":"https://images.pokemontcg.io/pl2/36_hires.png"}',
    searchName: 'Walrein (RR 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Yanmega E4',
    tcgApiId: 'pl2-37',
    number: '37',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/37.png","large":"https://images.pokemontcg.io/pl2/37_hires.png"}',
    searchName: 'Yanmega E4 (RR 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Alakazam E4',
    tcgApiId: 'pl2-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/38.png","large":"https://images.pokemontcg.io/pl2/38_hires.png"}',
    searchName: 'Alakazam E4 (RR 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Electrode G',
    tcgApiId: 'pl2-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/39.png","large":"https://images.pokemontcg.io/pl2/39_hires.png"}',
    searchName: 'Electrode G (RR 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Gengar GL',
    tcgApiId: 'pl2-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/40.png","large":"https://images.pokemontcg.io/pl2/40_hires.png"}',
    searchName: 'Gengar GL (RR 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Glaceon',
    tcgApiId: 'pl2-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/41.png","large":"https://images.pokemontcg.io/pl2/41_hires.png"}',
    searchName: 'Glaceon (RR 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Hippowdon E4',
    tcgApiId: 'pl2-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/42.png","large":"https://images.pokemontcg.io/pl2/42_hires.png"}',
    searchName: 'Hippowdon E4 (RR 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Infernape E4',
    tcgApiId: 'pl2-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/43.png","large":"https://images.pokemontcg.io/pl2/43_hires.png"}',
    searchName: 'Infernape E4 (RR 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Lairon',
    tcgApiId: 'pl2-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/44.png","large":"https://images.pokemontcg.io/pl2/44_hires.png"}',
    searchName: 'Lairon (RR 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Leafeon',
    tcgApiId: 'pl2-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/45.png","large":"https://images.pokemontcg.io/pl2/45_hires.png"}',
    searchName: 'Leafeon (RR 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Machamp GL',
    tcgApiId: 'pl2-46',
    number: '46',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/46.png","large":"https://images.pokemontcg.io/pl2/46_hires.png"}',
    searchName: 'Machamp GL (RR 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Rapidash E4',
    tcgApiId: 'pl2-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/47.png","large":"https://images.pokemontcg.io/pl2/47_hires.png"}',
    searchName: 'Rapidash E4 (RR 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Scizor E4',
    tcgApiId: 'pl2-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/48.png","large":"https://images.pokemontcg.io/pl2/48_hires.png"}',
    searchName: 'Scizor E4 (RR 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Sharpedo',
    tcgApiId: 'pl2-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/49.png","large":"https://images.pokemontcg.io/pl2/49_hires.png"}',
    searchName: 'Sharpedo (RR 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Starmie',
    tcgApiId: 'pl2-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/50.png","large":"https://images.pokemontcg.io/pl2/50_hires.png"}',
    searchName: 'Starmie (RR 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Steelix GL',
    tcgApiId: 'pl2-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/51.png","large":"https://images.pokemontcg.io/pl2/51_hires.png"}',
    searchName: 'Steelix GL (RR 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Tropius',
    tcgApiId: 'pl2-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/52.png","large":"https://images.pokemontcg.io/pl2/52_hires.png"}',
    searchName: 'Tropius (RR 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Vibrava',
    tcgApiId: 'pl2-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/53.png","large":"https://images.pokemontcg.io/pl2/53_hires.png"}',
    searchName: 'Vibrava (RR 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Whiscash E4',
    tcgApiId: 'pl2-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/54.png","large":"https://images.pokemontcg.io/pl2/54_hires.png"}',
    searchName: 'Whiscash E4 (RR 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Aerodactyl GL',
    tcgApiId: 'pl2-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/55.png","large":"https://images.pokemontcg.io/pl2/55_hires.png"}',
    searchName: 'Aerodactyl GL (RR 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Ambipom G',
    tcgApiId: 'pl2-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/56.png","large":"https://images.pokemontcg.io/pl2/56_hires.png"}',
    searchName: 'Ambipom G (RR 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Aron',
    tcgApiId: 'pl2-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/57.png","large":"https://images.pokemontcg.io/pl2/57_hires.png"}',
    searchName: 'Aron (RR 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Carvanha',
    tcgApiId: 'pl2-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/58.png","large":"https://images.pokemontcg.io/pl2/58_hires.png"}',
    searchName: 'Carvanha (RR 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Eevee',
    tcgApiId: 'pl2-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/59.png","large":"https://images.pokemontcg.io/pl2/59_hires.png"}',
    searchName: 'Eevee (RR 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Flareon E4',
    tcgApiId: 'pl2-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/60.png","large":"https://images.pokemontcg.io/pl2/60_hires.png"}',
    searchName: 'Flareon E4 (RR 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Forretress G',
    tcgApiId: 'pl2-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/61.png","large":"https://images.pokemontcg.io/pl2/61_hires.png"}',
    searchName: 'Forretress G (RR 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Gliscor E4',
    tcgApiId: 'pl2-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/62.png","large":"https://images.pokemontcg.io/pl2/62_hires.png"}',
    searchName: 'Gliscor E4 (RR 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Growlithe',
    tcgApiId: 'pl2-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/63.png","large":"https://images.pokemontcg.io/pl2/63_hires.png"}',
    searchName: 'Growlithe (RR 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Hippopotas',
    tcgApiId: 'pl2-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/64.png","large":"https://images.pokemontcg.io/pl2/64_hires.png"}',
    searchName: 'Hippopotas (RR 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Houndoom E4',
    tcgApiId: 'pl2-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/65.png","large":"https://images.pokemontcg.io/pl2/65_hires.png"}',
    searchName: 'Houndoom E4 (RR 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Kakuna',
    tcgApiId: 'pl2-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/66.png","large":"https://images.pokemontcg.io/pl2/66_hires.png"}',
    searchName: 'Kakuna (RR 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Kecleon',
    tcgApiId: 'pl2-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/67.png","large":"https://images.pokemontcg.io/pl2/67_hires.png"}',
    searchName: 'Kecleon (RR 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Koffing',
    tcgApiId: 'pl2-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/68.png","large":"https://images.pokemontcg.io/pl2/68_hires.png"}',
    searchName: 'Koffing (RR 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Munchlax',
    tcgApiId: 'pl2-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/69.png","large":"https://images.pokemontcg.io/pl2/69_hires.png"}',
    searchName: 'Munchlax (RR 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Munchlax',
    tcgApiId: 'pl2-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/70.png","large":"https://images.pokemontcg.io/pl2/70_hires.png"}',
    searchName: 'Munchlax (RR 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Nidoran ♀',
    tcgApiId: 'pl2-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/71.png","large":"https://images.pokemontcg.io/pl2/71_hires.png"}',
    searchName: 'Nidoran ♀ (RR 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Nidoran ♂',
    tcgApiId: 'pl2-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/72.png","large":"https://images.pokemontcg.io/pl2/72_hires.png"}',
    searchName: 'Nidoran ♂ (RR 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Nidorina',
    tcgApiId: 'pl2-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/73.png","large":"https://images.pokemontcg.io/pl2/73_hires.png"}',
    searchName: 'Nidorina (RR 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Nidorino',
    tcgApiId: 'pl2-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/74.png","large":"https://images.pokemontcg.io/pl2/74_hires.png"}',
    searchName: 'Nidorino (RR 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Nuzleaf',
    tcgApiId: 'pl2-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/75.png","large":"https://images.pokemontcg.io/pl2/75_hires.png"}',
    searchName: 'Nuzleaf (RR 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Quagsire GL',
    tcgApiId: 'pl2-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/76.png","large":"https://images.pokemontcg.io/pl2/76_hires.png"}',
    searchName: 'Quagsire GL (RR 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Sealeo',
    tcgApiId: 'pl2-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/77.png","large":"https://images.pokemontcg.io/pl2/77_hires.png"}',
    searchName: 'Sealeo (RR 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Seedot',
    tcgApiId: 'pl2-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/78.png","large":"https://images.pokemontcg.io/pl2/78_hires.png"}',
    searchName: 'Seedot (RR 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Shellos East Sea',
    tcgApiId: 'pl2-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/79.png","large":"https://images.pokemontcg.io/pl2/79_hires.png"}',
    searchName: 'Shellos East Sea (RR 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Shellos West Sea',
    tcgApiId: 'pl2-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/80.png","large":"https://images.pokemontcg.io/pl2/80_hires.png"}',
    searchName: 'Shellos West Sea (RR 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Snorlax',
    tcgApiId: 'pl2-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/81.png","large":"https://images.pokemontcg.io/pl2/81_hires.png"}',
    searchName: 'Snorlax (RR 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Spheal',
    tcgApiId: 'pl2-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/82.png","large":"https://images.pokemontcg.io/pl2/82_hires.png"}',
    searchName: 'Spheal (RR 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Staryu',
    tcgApiId: 'pl2-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/83.png","large":"https://images.pokemontcg.io/pl2/83_hires.png"}',
    searchName: 'Staryu (RR 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Trapinch',
    tcgApiId: 'pl2-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/84.png","large":"https://images.pokemontcg.io/pl2/84_hires.png"}',
    searchName: 'Trapinch (RR 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Turtwig GL',
    tcgApiId: 'pl2-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/85.png","large":"https://images.pokemontcg.io/pl2/85_hires.png"}',
    searchName: 'Turtwig GL (RR 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Weedle',
    tcgApiId: 'pl2-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/86.png","large":"https://images.pokemontcg.io/pl2/86_hires.png"}',
    searchName: 'Weedle (RR 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Weezing',
    tcgApiId: 'pl2-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/87.png","large":"https://images.pokemontcg.io/pl2/87_hires.png"}',
    searchName: 'Weezing (RR 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: "Aaron's Collection",
    tcgApiId: 'pl2-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/88.png","large":"https://images.pokemontcg.io/pl2/88_hires.png"}',
    searchName: "Aaron's Collection (RR 88)",
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: "Bebe's Search",
    tcgApiId: 'pl2-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/89.png","large":"https://images.pokemontcg.io/pl2/89_hires.png"}',
    searchName: "Bebe's Search (RR 89)",
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: "Bertha's Warmth",
    tcgApiId: 'pl2-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/90.png","large":"https://images.pokemontcg.io/pl2/90_hires.png"}',
    searchName: "Bertha's Warmth (RR 90)",
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: "Flint's Willpower",
    tcgApiId: 'pl2-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/91.png","large":"https://images.pokemontcg.io/pl2/91_hires.png"}',
    searchName: "Flint's Willpower (RR 91)",
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: "Lucian's Assignment",
    tcgApiId: 'pl2-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/92.png","large":"https://images.pokemontcg.io/pl2/92_hires.png"}',
    searchName: "Lucian's Assignment (RR 92)",
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Pokémon Contest Hall',
    tcgApiId: 'pl2-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/93.png","large":"https://images.pokemontcg.io/pl2/93_hires.png"}',
    searchName: 'Pokémon Contest Hall (RR 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Sunyshore City Gym',
    tcgApiId: 'pl2-94',
    number: '94',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/94.png","large":"https://images.pokemontcg.io/pl2/94_hires.png"}',
    searchName: 'Sunyshore City Gym (RR 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: "Team Galactic's Invention G-107 Technical Machine G",
    tcgApiId: 'pl2-95',
    number: '95',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/95.png","large":"https://images.pokemontcg.io/pl2/95_hires.png"}',
    searchName: "Team Galactic's Invention G-107 Technical Machine G (RR 95)",
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: "Team Galactic's Invention G-109 SP Radar",
    tcgApiId: 'pl2-96',
    number: '96',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/96.png","large":"https://images.pokemontcg.io/pl2/96_hires.png"}',
    searchName: "Team Galactic's Invention G-109 SP Radar (RR 96)",
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Underground Expedition',
    tcgApiId: 'pl2-97',
    number: '97',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/97.png","large":"https://images.pokemontcg.io/pl2/97_hires.png"}',
    searchName: 'Underground Expedition (RR 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: "Volkner's Philosophy",
    tcgApiId: 'pl2-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/98.png","large":"https://images.pokemontcg.io/pl2/98_hires.png"}',
    searchName: "Volkner's Philosophy (RR 98)",
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Darkness Energy',
    tcgApiId: 'pl2-99',
    number: '99',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/99.png","large":"https://images.pokemontcg.io/pl2/99_hires.png"}',
    searchName: 'Darkness Energy (RR 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Metal Energy',
    tcgApiId: 'pl2-100',
    number: '100',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/100.png","large":"https://images.pokemontcg.io/pl2/100_hires.png"}',
    searchName: 'Metal Energy (RR 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'SP Energy',
    tcgApiId: 'pl2-101',
    number: '101',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/101.png","large":"https://images.pokemontcg.io/pl2/101_hires.png"}',
    searchName: 'SP Energy (RR 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Upper Energy',
    tcgApiId: 'pl2-102',
    number: '102',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/102.png","large":"https://images.pokemontcg.io/pl2/102_hires.png"}',
    searchName: 'Upper Energy (RR 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Alakazam E4 LV.X',
    tcgApiId: 'pl2-103',
    number: '103',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/103.png","large":"https://images.pokemontcg.io/pl2/103_hires.png"}',
    searchName: 'Alakazam E4 LV.X (RR 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Floatzel GL LV.X',
    tcgApiId: 'pl2-104',
    number: '104',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/104.png","large":"https://images.pokemontcg.io/pl2/104_hires.png"}',
    searchName: 'Floatzel GL LV.X (RR 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Flygon LV.X',
    tcgApiId: 'pl2-105',
    number: '105',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/105.png","large":"https://images.pokemontcg.io/pl2/105_hires.png"}',
    searchName: 'Flygon LV.X (RR 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Gallade E4 LV.X',
    tcgApiId: 'pl2-106',
    number: '106',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/106.png","large":"https://images.pokemontcg.io/pl2/106_hires.png"}',
    searchName: 'Gallade E4 LV.X (RR 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Hippowdon LV.X',
    tcgApiId: 'pl2-107',
    number: '107',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/107.png","large":"https://images.pokemontcg.io/pl2/107_hires.png"}',
    searchName: 'Hippowdon LV.X (RR 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Infernape E4 LV.X',
    tcgApiId: 'pl2-108',
    number: '108',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/108.png","large":"https://images.pokemontcg.io/pl2/108_hires.png"}',
    searchName: 'Infernape E4 LV.X (RR 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Luxray GL LV.X',
    tcgApiId: 'pl2-109',
    number: '109',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/109.png","large":"https://images.pokemontcg.io/pl2/109_hires.png"}',
    searchName: 'Luxray GL LV.X (RR 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Mismagius GL LV.X',
    tcgApiId: 'pl2-110',
    number: '110',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/110.png","large":"https://images.pokemontcg.io/pl2/110_hires.png"}',
    searchName: 'Mismagius GL LV.X (RR 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Snorlax LV.X',
    tcgApiId: 'pl2-111',
    number: '111',
    rarity: 'Rare Holo LV.X',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/111.png","large":"https://images.pokemontcg.io/pl2/111_hires.png"}',
    searchName: 'Snorlax LV.X (RR 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Pikachu',
    tcgApiId: 'pl2-112',
    number: '112',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/112.png","large":"https://images.pokemontcg.io/pl2/112_hires.png"}',
    searchName: 'Pikachu (RR 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Flying Pikachu',
    tcgApiId: 'pl2-113',
    number: '113',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/113.png","large":"https://images.pokemontcg.io/pl2/113_hires.png"}',
    searchName: 'Flying Pikachu (RR 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Surfing Pikachu',
    tcgApiId: 'pl2-114',
    number: '114',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/114.png","large":"https://images.pokemontcg.io/pl2/114_hires.png"}',
    searchName: 'Surfing Pikachu (RR 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Fan Rotom',
    tcgApiId: 'pl2-RT1',
    number: 'RT1',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/RT1.png","large":"https://images.pokemontcg.io/pl2/RT1_hires.png"}',
    searchName: 'Fan Rotom (RR RT1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Frost Rotom',
    tcgApiId: 'pl2-RT2',
    number: 'RT2',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/RT2.png","large":"https://images.pokemontcg.io/pl2/RT2_hires.png"}',
    searchName: 'Frost Rotom (RR RT2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Heat Rotom',
    tcgApiId: 'pl2-RT3',
    number: 'RT3',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/RT3.png","large":"https://images.pokemontcg.io/pl2/RT3_hires.png"}',
    searchName: 'Heat Rotom (RR RT3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Mow Rotom',
    tcgApiId: 'pl2-RT4',
    number: 'RT4',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/RT4.png","large":"https://images.pokemontcg.io/pl2/RT4_hires.png"}',
    searchName: 'Mow Rotom (RR RT4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: 'Wash Rotom',
    tcgApiId: 'pl2-RT5',
    number: 'RT5',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/RT5.png","large":"https://images.pokemontcg.io/pl2/RT5_hires.png"}',
    searchName: 'Wash Rotom (RR RT5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'pl2',
    name: "Charon's Choice",
    tcgApiId: 'pl2-RT6',
    number: 'RT6',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/pl2/RT6.png","large":"https://images.pokemontcg.io/pl2/RT6_hires.png"}',
    searchName: "Charon's Choice (RR RT6)",
  },
];
