export const cardSeedPop7 = [
  {"tcgId":"pokemon","setId":"pop7","name":"Ampharos","tcgApiId":"pop7-1","number":"1","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop7/1.png\",\"large\":\"https://images.pokemontcg.io/pop7/1_hires.png\"}","searchName":"Ampharos (undefined 1)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Gallade","tcgApiId":"pop7-2","number":"2","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop7/2.png\",\"large\":\"https://images.pokemontcg.io/pop7/2_hires.png\"}","searchName":"Gallade (undefined 2)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Latias","tcgApiId":"pop7-3","number":"3","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop7/3.png\",\"large\":\"https://images.pokemontcg.io/pop7/3_hires.png\"}","searchName":"Latias (undefined 3)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Latios","tcgApiId":"pop7-4","number":"4","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop7/4.png\",\"large\":\"https://images.pokemontcg.io/pop7/4_hires.png\"}","searchName":"Latios (undefined 4)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Mothim","tcgApiId":"pop7-5","number":"5","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop7/5.png\",\"large\":\"https://images.pokemontcg.io/pop7/5_hires.png\"}","searchName":"Mothim (undefined 5)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Delibird","tcgApiId":"pop7-6","number":"6","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop7/6.png\",\"large\":\"https://images.pokemontcg.io/pop7/6_hires.png\"}","searchName":"Delibird (undefined 6)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Flaaffy","tcgApiId":"pop7-7","number":"7","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop7/7.png\",\"large\":\"https://images.pokemontcg.io/pop7/7_hires.png\"}","searchName":"Flaaffy (undefined 7)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Kirlia","tcgApiId":"pop7-8","number":"8","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop7/8.png\",\"large\":\"https://images.pokemontcg.io/pop7/8_hires.png\"}","searchName":"Kirlia (undefined 8)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Stantler","tcgApiId":"pop7-9","number":"9","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop7/9.png\",\"large\":\"https://images.pokemontcg.io/pop7/9_hires.png\"}","searchName":"Stantler (undefined 9)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Wormadam Sandy Cloak","tcgApiId":"pop7-10","number":"10","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop7/10.png\",\"large\":\"https://images.pokemontcg.io/pop7/10_hires.png\"}","searchName":"Wormadam Sandy Cloak (undefined 10)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Burmy Plant Cloak","tcgApiId":"pop7-11","number":"11","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop7/11.png\",\"large\":\"https://images.pokemontcg.io/pop7/11_hires.png\"}","searchName":"Burmy Plant Cloak (undefined 11)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Burmy Sandy Cloak","tcgApiId":"pop7-12","number":"12","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop7/12.png\",\"large\":\"https://images.pokemontcg.io/pop7/12_hires.png\"}","searchName":"Burmy Sandy Cloak (undefined 12)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Corsola","tcgApiId":"pop7-13","number":"13","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop7/13.png\",\"large\":\"https://images.pokemontcg.io/pop7/13_hires.png\"}","searchName":"Corsola (undefined 13)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Mareep","tcgApiId":"pop7-14","number":"14","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop7/14.png\",\"large\":\"https://images.pokemontcg.io/pop7/14_hires.png\"}","searchName":"Mareep (undefined 14)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Ralts","tcgApiId":"pop7-15","number":"15","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop7/15.png\",\"large\":\"https://images.pokemontcg.io/pop7/15_hires.png\"}","searchName":"Ralts (undefined 15)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Sentret","tcgApiId":"pop7-16","number":"16","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop7/16.png\",\"large\":\"https://images.pokemontcg.io/pop7/16_hires.png\"}","searchName":"Sentret (undefined 16)"},
  {"tcgId":"pokemon","setId":"pop7","name":"Spinda","tcgApiId":"pop7-17","number":"17","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop7/17.png\",\"large\":\"https://images.pokemontcg.io/pop7/17_hires.png\"}","searchName":"Spinda (undefined 17)"}
]
