export const cardSeedPop8 = [
  {"tcgId":"pokemon","setId":"pop8","name":"Heatran","tcgApiId":"pop8-1","number":"1","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop8/1.png\",\"large\":\"https://images.pokemontcg.io/pop8/1_hires.png\"}","searchName":"Heatran (undefined 1)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Lucario","tcgApiId":"pop8-2","number":"2","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop8/2.png\",\"large\":\"https://images.pokemontcg.io/pop8/2_hires.png\"}","searchName":"Lucario (undefined 2)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Luxray","tcgApiId":"pop8-3","number":"3","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop8/3.png\",\"large\":\"https://images.pokemontcg.io/pop8/3_hires.png\"}","searchName":"Luxray (undefined 3)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Probopass","tcgApiId":"pop8-4","number":"4","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop8/4.png\",\"large\":\"https://images.pokemontcg.io/pop8/4_hires.png\"}","searchName":"Probopass (undefined 4)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Yanmega","tcgApiId":"pop8-5","number":"5","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop8/5.png\",\"large\":\"https://images.pokemontcg.io/pop8/5_hires.png\"}","searchName":"Yanmega (undefined 5)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Cherrim","tcgApiId":"pop8-6","number":"6","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop8/6.png\",\"large\":\"https://images.pokemontcg.io/pop8/6_hires.png\"}","searchName":"Cherrim (undefined 6)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Carnivine","tcgApiId":"pop8-7","number":"7","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop8/7.png\",\"large\":\"https://images.pokemontcg.io/pop8/7_hires.png\"}","searchName":"Carnivine (undefined 7)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Luxio","tcgApiId":"pop8-8","number":"8","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop8/8.png\",\"large\":\"https://images.pokemontcg.io/pop8/8_hires.png\"}","searchName":"Luxio (undefined 8)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Night Maintenance","tcgApiId":"pop8-9","number":"9","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop8/9.png\",\"large\":\"https://images.pokemontcg.io/pop8/9_hires.png\"}","searchName":"Night Maintenance (undefined 9)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Rare Candy","tcgApiId":"pop8-10","number":"10","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop8/10.png\",\"large\":\"https://images.pokemontcg.io/pop8/10_hires.png\"}","searchName":"Rare Candy (undefined 10)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Roseanne's Research","tcgApiId":"pop8-11","number":"11","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop8/11.png\",\"large\":\"https://images.pokemontcg.io/pop8/11_hires.png\"}","searchName":"Roseanne's Research (undefined 11)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Chimchar","tcgApiId":"pop8-12","number":"12","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop8/12.png\",\"large\":\"https://images.pokemontcg.io/pop8/12_hires.png\"}","searchName":"Chimchar (undefined 12)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Croagunk","tcgApiId":"pop8-13","number":"13","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop8/13.png\",\"large\":\"https://images.pokemontcg.io/pop8/13_hires.png\"}","searchName":"Croagunk (undefined 13)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Happiny","tcgApiId":"pop8-14","number":"14","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop8/14.png\",\"large\":\"https://images.pokemontcg.io/pop8/14_hires.png\"}","searchName":"Happiny (undefined 14)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Piplup","tcgApiId":"pop8-15","number":"15","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop8/15.png\",\"large\":\"https://images.pokemontcg.io/pop8/15_hires.png\"}","searchName":"Piplup (undefined 15)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Riolu","tcgApiId":"pop8-16","number":"16","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop8/16.png\",\"large\":\"https://images.pokemontcg.io/pop8/16_hires.png\"}","searchName":"Riolu (undefined 16)"},
  {"tcgId":"pokemon","setId":"pop8","name":"Turtwig","tcgApiId":"pop8-17","number":"17","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop8/17.png\",\"large\":\"https://images.pokemontcg.io/pop8/17_hires.png\"}","searchName":"Turtwig (undefined 17)"}
]
