export const cardSeedPop9 = [
  {"tcgId":"pokemon","setId":"pop9","name":"Garchomp","tcgApiId":"pop9-1","number":"1","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop9/1.png\",\"large\":\"https://images.pokemontcg.io/pop9/1_hires.png\"}","searchName":"Garchomp (undefined 1)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Manaphy","tcgApiId":"pop9-2","number":"2","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop9/2.png\",\"large\":\"https://images.pokemontcg.io/pop9/2_hires.png\"}","searchName":"Manaphy (undefined 2)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Raichu","tcgApiId":"pop9-3","number":"3","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop9/3.png\",\"large\":\"https://images.pokemontcg.io/pop9/3_hires.png\"}","searchName":"Raichu (undefined 3)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Regigigas","tcgApiId":"pop9-4","number":"4","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop9/4.png\",\"large\":\"https://images.pokemontcg.io/pop9/4_hires.png\"}","searchName":"Regigigas (undefined 4)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Rotom","tcgApiId":"pop9-5","number":"5","rarity":"Rare","images":"{\"small\":\"https://images.pokemontcg.io/pop9/5.png\",\"large\":\"https://images.pokemontcg.io/pop9/5_hires.png\"}","searchName":"Rotom (undefined 5)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Buizel","tcgApiId":"pop9-6","number":"6","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop9/6.png\",\"large\":\"https://images.pokemontcg.io/pop9/6_hires.png\"}","searchName":"Buizel (undefined 6)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Croagunk","tcgApiId":"pop9-7","number":"7","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop9/7.png\",\"large\":\"https://images.pokemontcg.io/pop9/7_hires.png\"}","searchName":"Croagunk (undefined 7)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Gabite","tcgApiId":"pop9-8","number":"8","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop9/8.png\",\"large\":\"https://images.pokemontcg.io/pop9/8_hires.png\"}","searchName":"Gabite (undefined 8)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Lopunny","tcgApiId":"pop9-9","number":"9","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop9/9.png\",\"large\":\"https://images.pokemontcg.io/pop9/9_hires.png\"}","searchName":"Lopunny (undefined 9)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Pachirisu","tcgApiId":"pop9-10","number":"10","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop9/10.png\",\"large\":\"https://images.pokemontcg.io/pop9/10_hires.png\"}","searchName":"Pachirisu (undefined 10)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Pichu","tcgApiId":"pop9-11","number":"11","rarity":"Uncommon","images":"{\"small\":\"https://images.pokemontcg.io/pop9/11.png\",\"large\":\"https://images.pokemontcg.io/pop9/11_hires.png\"}","searchName":"Pichu (undefined 11)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Buneary","tcgApiId":"pop9-12","number":"12","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop9/12.png\",\"large\":\"https://images.pokemontcg.io/pop9/12_hires.png\"}","searchName":"Buneary (undefined 12)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Chimchar","tcgApiId":"pop9-13","number":"13","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop9/13.png\",\"large\":\"https://images.pokemontcg.io/pop9/13_hires.png\"}","searchName":"Chimchar (undefined 13)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Gible","tcgApiId":"pop9-14","number":"14","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop9/14.png\",\"large\":\"https://images.pokemontcg.io/pop9/14_hires.png\"}","searchName":"Gible (undefined 14)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Pikachu","tcgApiId":"pop9-15","number":"15","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop9/15.png\",\"large\":\"https://images.pokemontcg.io/pop9/15_hires.png\"}","searchName":"Pikachu (undefined 15)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Piplup","tcgApiId":"pop9-16","number":"16","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop9/16.png\",\"large\":\"https://images.pokemontcg.io/pop9/16_hires.png\"}","searchName":"Piplup (undefined 16)"},
  {"tcgId":"pokemon","setId":"pop9","name":"Turtwig","tcgApiId":"pop9-17","number":"17","rarity":"Common","images":"{\"small\":\"https://images.pokemontcg.io/pop9/17.png\",\"large\":\"https://images.pokemontcg.io/pop9/17_hires.png\"}","searchName":"Turtwig (undefined 17)"}
]
