export const cardSeedSm12 = [
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Venusaur & Snivy-GX',
    tcgApiId: 'sm12-1',
    number: '1',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/1.png","large":"https://images.pokemontcg.io/sm12/1_hires.png"}',
    searchName: 'Venusaur & Snivy-GX (CEC 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Oddish',
    tcgApiId: 'sm12-2',
    number: '2',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/2.png","large":"https://images.pokemontcg.io/sm12/2_hires.png"}',
    searchName: 'Oddish (CEC 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Gloom',
    tcgApiId: 'sm12-3',
    number: '3',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/3.png","large":"https://images.pokemontcg.io/sm12/3_hires.png"}',
    searchName: 'Gloom (CEC 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Vileplume-GX',
    tcgApiId: 'sm12-4',
    number: '4',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/4.png","large":"https://images.pokemontcg.io/sm12/4_hires.png"}',
    searchName: 'Vileplume-GX (CEC 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Tangela',
    tcgApiId: 'sm12-5',
    number: '5',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/5.png","large":"https://images.pokemontcg.io/sm12/5_hires.png"}',
    searchName: 'Tangela (CEC 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Tangrowth',
    tcgApiId: 'sm12-6',
    number: '6',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/6.png","large":"https://images.pokemontcg.io/sm12/6_hires.png"}',
    searchName: 'Tangrowth (CEC 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Sunkern',
    tcgApiId: 'sm12-7',
    number: '7',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/7.png","large":"https://images.pokemontcg.io/sm12/7_hires.png"}',
    searchName: 'Sunkern (CEC 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Sunflora',
    tcgApiId: 'sm12-8',
    number: '8',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/8.png","large":"https://images.pokemontcg.io/sm12/8_hires.png"}',
    searchName: 'Sunflora (CEC 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Heracross',
    tcgApiId: 'sm12-9',
    number: '9',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/9.png","large":"https://images.pokemontcg.io/sm12/9_hires.png"}',
    searchName: 'Heracross (CEC 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Lileep',
    tcgApiId: 'sm12-10',
    number: '10',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/10.png","large":"https://images.pokemontcg.io/sm12/10_hires.png"}',
    searchName: 'Lileep (CEC 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Cradily',
    tcgApiId: 'sm12-11',
    number: '11',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/11.png","large":"https://images.pokemontcg.io/sm12/11_hires.png"}',
    searchName: 'Cradily (CEC 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Tropius',
    tcgApiId: 'sm12-12',
    number: '12',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/12.png","large":"https://images.pokemontcg.io/sm12/12_hires.png"}',
    searchName: 'Tropius (CEC 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Kricketot',
    tcgApiId: 'sm12-13',
    number: '13',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/13.png","large":"https://images.pokemontcg.io/sm12/13_hires.png"}',
    searchName: 'Kricketot (CEC 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Kricketune',
    tcgApiId: 'sm12-14',
    number: '14',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/14.png","large":"https://images.pokemontcg.io/sm12/14_hires.png"}',
    searchName: 'Kricketune (CEC 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Deerling',
    tcgApiId: 'sm12-15',
    number: '15',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/15.png","large":"https://images.pokemontcg.io/sm12/15_hires.png"}',
    searchName: 'Deerling (CEC 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Sawsbuck',
    tcgApiId: 'sm12-16',
    number: '16',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/16.png","large":"https://images.pokemontcg.io/sm12/16_hires.png"}',
    searchName: 'Sawsbuck (CEC 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Rowlet',
    tcgApiId: 'sm12-17',
    number: '17',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/17.png","large":"https://images.pokemontcg.io/sm12/17_hires.png"}',
    searchName: 'Rowlet (CEC 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Rowlet',
    tcgApiId: 'sm12-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/18.png","large":"https://images.pokemontcg.io/sm12/18_hires.png"}',
    searchName: 'Rowlet (CEC 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Dartrix',
    tcgApiId: 'sm12-19',
    number: '19',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/19.png","large":"https://images.pokemontcg.io/sm12/19_hires.png"}',
    searchName: 'Dartrix (CEC 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Decidueye',
    tcgApiId: 'sm12-20',
    number: '20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/20.png","large":"https://images.pokemontcg.io/sm12/20_hires.png"}',
    searchName: 'Decidueye (CEC 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Buzzwole',
    tcgApiId: 'sm12-21',
    number: '21',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/21.png","large":"https://images.pokemontcg.io/sm12/21_hires.png"}',
    searchName: 'Buzzwole (CEC 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Charizard & Braixen-GX',
    tcgApiId: 'sm12-22',
    number: '22',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/22.png","large":"https://images.pokemontcg.io/sm12/22_hires.png"}',
    searchName: 'Charizard & Braixen-GX (CEC 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Ponyta',
    tcgApiId: 'sm12-23',
    number: '23',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/23.png","large":"https://images.pokemontcg.io/sm12/23_hires.png"}',
    searchName: 'Ponyta (CEC 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Rapidash',
    tcgApiId: 'sm12-24',
    number: '24',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/24.png","large":"https://images.pokemontcg.io/sm12/24_hires.png"}',
    searchName: 'Rapidash (CEC 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Flareon',
    tcgApiId: 'sm12-25',
    number: '25',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/25.png","large":"https://images.pokemontcg.io/sm12/25_hires.png"}',
    searchName: 'Flareon (CEC 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Slugma',
    tcgApiId: 'sm12-26',
    number: '26',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/26.png","large":"https://images.pokemontcg.io/sm12/26_hires.png"}',
    searchName: 'Slugma (CEC 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Magcargo',
    tcgApiId: 'sm12-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/27.png","large":"https://images.pokemontcg.io/sm12/27_hires.png"}',
    searchName: 'Magcargo (CEC 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Entei',
    tcgApiId: 'sm12-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/28.png","large":"https://images.pokemontcg.io/sm12/28_hires.png"}',
    searchName: 'Entei (CEC 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Torkoal',
    tcgApiId: 'sm12-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/29.png","large":"https://images.pokemontcg.io/sm12/29_hires.png"}',
    searchName: 'Torkoal (CEC 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Victini',
    tcgApiId: 'sm12-30',
    number: '30',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/30.png","large":"https://images.pokemontcg.io/sm12/30_hires.png"}',
    searchName: 'Victini (CEC 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Tepig',
    tcgApiId: 'sm12-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/31.png","large":"https://images.pokemontcg.io/sm12/31_hires.png"}',
    searchName: 'Tepig (CEC 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Pignite',
    tcgApiId: 'sm12-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/32.png","large":"https://images.pokemontcg.io/sm12/32_hires.png"}',
    searchName: 'Pignite (CEC 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Emboar',
    tcgApiId: 'sm12-33',
    number: '33',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/33.png","large":"https://images.pokemontcg.io/sm12/33_hires.png"}',
    searchName: 'Emboar (CEC 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Larvesta',
    tcgApiId: 'sm12-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/34.png","large":"https://images.pokemontcg.io/sm12/34_hires.png"}',
    searchName: 'Larvesta (CEC 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Volcarona-GX',
    tcgApiId: 'sm12-35',
    number: '35',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/35.png","large":"https://images.pokemontcg.io/sm12/35_hires.png"}',
    searchName: 'Volcarona-GX (CEC 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Litleo',
    tcgApiId: 'sm12-36',
    number: '36',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/36.png","large":"https://images.pokemontcg.io/sm12/36_hires.png"}',
    searchName: 'Litleo (CEC 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Pyroar',
    tcgApiId: 'sm12-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/37.png","large":"https://images.pokemontcg.io/sm12/37_hires.png"}',
    searchName: 'Pyroar (CEC 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Blastoise & Piplup-GX',
    tcgApiId: 'sm12-38',
    number: '38',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/38.png","large":"https://images.pokemontcg.io/sm12/38_hires.png"}',
    searchName: 'Blastoise & Piplup-GX (CEC 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Vulpix',
    tcgApiId: 'sm12-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/39.png","large":"https://images.pokemontcg.io/sm12/39_hires.png"}',
    searchName: 'Alolan Vulpix (CEC 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Psyduck',
    tcgApiId: 'sm12-40',
    number: '40',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/40.png","large":"https://images.pokemontcg.io/sm12/40_hires.png"}',
    searchName: 'Psyduck (CEC 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Golduck',
    tcgApiId: 'sm12-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/41.png","large":"https://images.pokemontcg.io/sm12/41_hires.png"}',
    searchName: 'Golduck (CEC 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Vaporeon',
    tcgApiId: 'sm12-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/42.png","large":"https://images.pokemontcg.io/sm12/42_hires.png"}',
    searchName: 'Vaporeon (CEC 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Sneasel',
    tcgApiId: 'sm12-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/43.png","large":"https://images.pokemontcg.io/sm12/43_hires.png"}',
    searchName: 'Sneasel (CEC 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Weavile',
    tcgApiId: 'sm12-44',
    number: '44',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/44.png","large":"https://images.pokemontcg.io/sm12/44_hires.png"}',
    searchName: 'Weavile (CEC 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Wailmer',
    tcgApiId: 'sm12-45',
    number: '45',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/45.png","large":"https://images.pokemontcg.io/sm12/45_hires.png"}',
    searchName: 'Wailmer (CEC 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Wailord',
    tcgApiId: 'sm12-46',
    number: '46',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/46.png","large":"https://images.pokemontcg.io/sm12/46_hires.png"}',
    searchName: 'Wailord (CEC 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Snorunt',
    tcgApiId: 'sm12-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/47.png","large":"https://images.pokemontcg.io/sm12/47_hires.png"}',
    searchName: 'Snorunt (CEC 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Glalie',
    tcgApiId: 'sm12-48',
    number: '48',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/48.png","large":"https://images.pokemontcg.io/sm12/48_hires.png"}',
    searchName: 'Glalie (CEC 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Spheal',
    tcgApiId: 'sm12-49',
    number: '49',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/49.png","large":"https://images.pokemontcg.io/sm12/49_hires.png"}',
    searchName: 'Spheal (CEC 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Spheal',
    tcgApiId: 'sm12-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/50.png","large":"https://images.pokemontcg.io/sm12/50_hires.png"}',
    searchName: 'Spheal (CEC 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Sealeo',
    tcgApiId: 'sm12-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/51.png","large":"https://images.pokemontcg.io/sm12/51_hires.png"}',
    searchName: 'Sealeo (CEC 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Walrein',
    tcgApiId: 'sm12-52',
    number: '52',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/52.png","large":"https://images.pokemontcg.io/sm12/52_hires.png"}',
    searchName: 'Walrein (CEC 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Kyogre',
    tcgApiId: 'sm12-53',
    number: '53',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/53.png","large":"https://images.pokemontcg.io/sm12/53_hires.png"}',
    searchName: 'Kyogre (CEC 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Piplup',
    tcgApiId: 'sm12-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/54.png","large":"https://images.pokemontcg.io/sm12/54_hires.png"}',
    searchName: 'Piplup (CEC 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Prinplup',
    tcgApiId: 'sm12-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/55.png","large":"https://images.pokemontcg.io/sm12/55_hires.png"}',
    searchName: 'Prinplup (CEC 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Empoleon',
    tcgApiId: 'sm12-56',
    number: '56',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/56.png","large":"https://images.pokemontcg.io/sm12/56_hires.png"}',
    searchName: 'Empoleon (CEC 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Phione',
    tcgApiId: 'sm12-57',
    number: '57',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/57.png","large":"https://images.pokemontcg.io/sm12/57_hires.png"}',
    searchName: 'Phione (CEC 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Tympole',
    tcgApiId: 'sm12-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/58.png","large":"https://images.pokemontcg.io/sm12/58_hires.png"}',
    searchName: 'Tympole (CEC 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Ducklett',
    tcgApiId: 'sm12-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/59.png","large":"https://images.pokemontcg.io/sm12/59_hires.png"}',
    searchName: 'Ducklett (CEC 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Swanna',
    tcgApiId: 'sm12-60',
    number: '60',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/60.png","large":"https://images.pokemontcg.io/sm12/60_hires.png"}',
    searchName: 'Swanna (CEC 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Black Kyurem',
    tcgApiId: 'sm12-61',
    number: '61',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/61.png","large":"https://images.pokemontcg.io/sm12/61_hires.png"}',
    searchName: 'Black Kyurem (CEC 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Wishiwashi',
    tcgApiId: 'sm12-62',
    number: '62',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/62.png","large":"https://images.pokemontcg.io/sm12/62_hires.png"}',
    searchName: 'Wishiwashi (CEC 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Wishiwashi-GX',
    tcgApiId: 'sm12-63',
    number: '63',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/63.png","large":"https://images.pokemontcg.io/sm12/63_hires.png"}',
    searchName: 'Wishiwashi-GX (CEC 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Dewpider',
    tcgApiId: 'sm12-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/64.png","large":"https://images.pokemontcg.io/sm12/64_hires.png"}',
    searchName: 'Dewpider (CEC 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Araquanid',
    tcgApiId: 'sm12-65',
    number: '65',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/65.png","large":"https://images.pokemontcg.io/sm12/65_hires.png"}',
    searchName: 'Araquanid (CEC 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Pikachu',
    tcgApiId: 'sm12-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/66.png","large":"https://images.pokemontcg.io/sm12/66_hires.png"}',
    searchName: 'Pikachu (CEC 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Raichu',
    tcgApiId: 'sm12-67',
    number: '67',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/67.png","large":"https://images.pokemontcg.io/sm12/67_hires.png"}',
    searchName: 'Raichu (CEC 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Magnemite',
    tcgApiId: 'sm12-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/68.png","large":"https://images.pokemontcg.io/sm12/68_hires.png"}',
    searchName: 'Magnemite (CEC 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Magneton',
    tcgApiId: 'sm12-69',
    number: '69',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/69.png","large":"https://images.pokemontcg.io/sm12/69_hires.png"}',
    searchName: 'Magneton (CEC 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Jolteon',
    tcgApiId: 'sm12-70',
    number: '70',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/70.png","large":"https://images.pokemontcg.io/sm12/70_hires.png"}',
    searchName: 'Jolteon (CEC 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Chinchou',
    tcgApiId: 'sm12-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/71.png","large":"https://images.pokemontcg.io/sm12/71_hires.png"}',
    searchName: 'Chinchou (CEC 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Lanturn',
    tcgApiId: 'sm12-72',
    number: '72',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/72.png","large":"https://images.pokemontcg.io/sm12/72_hires.png"}',
    searchName: 'Lanturn (CEC 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Togedemaru',
    tcgApiId: 'sm12-73',
    number: '73',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/73.png","large":"https://images.pokemontcg.io/sm12/73_hires.png"}',
    searchName: 'Togedemaru (CEC 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Togedemaru',
    tcgApiId: 'sm12-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/74.png","large":"https://images.pokemontcg.io/sm12/74_hires.png"}',
    searchName: 'Togedemaru (CEC 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Solgaleo & Lunala-GX',
    tcgApiId: 'sm12-75',
    number: '75',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/75.png","large":"https://images.pokemontcg.io/sm12/75_hires.png"}',
    searchName: 'Solgaleo & Lunala-GX (CEC 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Koffing',
    tcgApiId: 'sm12-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/76.png","large":"https://images.pokemontcg.io/sm12/76_hires.png"}',
    searchName: 'Koffing (CEC 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Weezing',
    tcgApiId: 'sm12-77',
    number: '77',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/77.png","large":"https://images.pokemontcg.io/sm12/77_hires.png"}',
    searchName: 'Weezing (CEC 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Natu',
    tcgApiId: 'sm12-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/78.png","large":"https://images.pokemontcg.io/sm12/78_hires.png"}',
    searchName: 'Natu (CEC 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Xatu',
    tcgApiId: 'sm12-79',
    number: '79',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/79.png","large":"https://images.pokemontcg.io/sm12/79_hires.png"}',
    searchName: 'Xatu (CEC 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Ralts',
    tcgApiId: 'sm12-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/80.png","large":"https://images.pokemontcg.io/sm12/80_hires.png"}',
    searchName: 'Ralts (CEC 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Kirlia',
    tcgApiId: 'sm12-81',
    number: '81',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/81.png","large":"https://images.pokemontcg.io/sm12/81_hires.png"}',
    searchName: 'Kirlia (CEC 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Gallade',
    tcgApiId: 'sm12-82',
    number: '82',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/82.png","large":"https://images.pokemontcg.io/sm12/82_hires.png"}',
    searchName: 'Gallade (CEC 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Duskull',
    tcgApiId: 'sm12-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/83.png","large":"https://images.pokemontcg.io/sm12/83_hires.png"}',
    searchName: 'Duskull (CEC 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Dusclops',
    tcgApiId: 'sm12-84',
    number: '84',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/84.png","large":"https://images.pokemontcg.io/sm12/84_hires.png"}',
    searchName: 'Dusclops (CEC 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Dusknoir',
    tcgApiId: 'sm12-85',
    number: '85',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/85.png","large":"https://images.pokemontcg.io/sm12/85_hires.png"}',
    searchName: 'Dusknoir (CEC 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Rotom',
    tcgApiId: 'sm12-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/86.png","large":"https://images.pokemontcg.io/sm12/86_hires.png"}',
    searchName: 'Rotom (CEC 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Woobat',
    tcgApiId: 'sm12-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/87.png","large":"https://images.pokemontcg.io/sm12/87_hires.png"}',
    searchName: 'Woobat (CEC 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Swoobat',
    tcgApiId: 'sm12-88',
    number: '88',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/88.png","large":"https://images.pokemontcg.io/sm12/88_hires.png"}',
    searchName: 'Swoobat (CEC 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Golett',
    tcgApiId: 'sm12-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/89.png","large":"https://images.pokemontcg.io/sm12/89_hires.png"}',
    searchName: 'Golett (CEC 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Golurk',
    tcgApiId: 'sm12-90',
    number: '90',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/90.png","large":"https://images.pokemontcg.io/sm12/90_hires.png"}',
    searchName: 'Golurk (CEC 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Skrelp',
    tcgApiId: 'sm12-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/91.png","large":"https://images.pokemontcg.io/sm12/91_hires.png"}',
    searchName: 'Skrelp (CEC 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Dragalge',
    tcgApiId: 'sm12-92',
    number: '92',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/92.png","large":"https://images.pokemontcg.io/sm12/92_hires.png"}',
    searchName: 'Dragalge (CEC 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Phantump',
    tcgApiId: 'sm12-93',
    number: '93',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/93.png","large":"https://images.pokemontcg.io/sm12/93_hires.png"}',
    searchName: 'Phantump (CEC 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Trevenant',
    tcgApiId: 'sm12-94',
    number: '94',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/94.png","large":"https://images.pokemontcg.io/sm12/94_hires.png"}',
    searchName: 'Trevenant (CEC 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Oricorio-GX',
    tcgApiId: 'sm12-95',
    number: '95',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/95.png","large":"https://images.pokemontcg.io/sm12/95_hires.png"}',
    searchName: 'Oricorio-GX (CEC 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mimikyu',
    tcgApiId: 'sm12-96',
    number: '96',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/96.png","large":"https://images.pokemontcg.io/sm12/96_hires.png"}',
    searchName: 'Mimikyu (CEC 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mimikyu',
    tcgApiId: 'sm12-97',
    number: '97',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/97.png","large":"https://images.pokemontcg.io/sm12/97_hires.png"}',
    searchName: 'Mimikyu (CEC 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Dhelmise',
    tcgApiId: 'sm12-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/98.png","large":"https://images.pokemontcg.io/sm12/98_hires.png"}',
    searchName: 'Dhelmise (CEC 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Cosmog',
    tcgApiId: 'sm12-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/99.png","large":"https://images.pokemontcg.io/sm12/99_hires.png"}',
    searchName: 'Cosmog (CEC 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Cosmog',
    tcgApiId: 'sm12-100',
    number: '100',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/100.png","large":"https://images.pokemontcg.io/sm12/100_hires.png"}',
    searchName: 'Cosmog (CEC 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Cosmoem',
    tcgApiId: 'sm12-101',
    number: '101',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/101.png","large":"https://images.pokemontcg.io/sm12/101_hires.png"}',
    searchName: 'Cosmoem (CEC 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Lunala',
    tcgApiId: 'sm12-102',
    number: '102',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/102.png","large":"https://images.pokemontcg.io/sm12/102_hires.png"}',
    searchName: 'Lunala (CEC 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Marshadow',
    tcgApiId: 'sm12-103',
    number: '103',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/103.png","large":"https://images.pokemontcg.io/sm12/103_hires.png"}',
    searchName: 'Marshadow (CEC 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Blacephalon',
    tcgApiId: 'sm12-104',
    number: '104',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/104.png","large":"https://images.pokemontcg.io/sm12/104_hires.png"}',
    searchName: 'Blacephalon (CEC 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Onix',
    tcgApiId: 'sm12-105',
    number: '105',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/105.png","large":"https://images.pokemontcg.io/sm12/105_hires.png"}',
    searchName: 'Onix (CEC 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Nosepass',
    tcgApiId: 'sm12-106',
    number: '106',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/106.png","large":"https://images.pokemontcg.io/sm12/106_hires.png"}',
    searchName: 'Nosepass (CEC 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Trapinch',
    tcgApiId: 'sm12-107',
    number: '107',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/107.png","large":"https://images.pokemontcg.io/sm12/107_hires.png"}',
    searchName: 'Trapinch (CEC 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Trapinch',
    tcgApiId: 'sm12-108',
    number: '108',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/108.png","large":"https://images.pokemontcg.io/sm12/108_hires.png"}',
    searchName: 'Trapinch (CEC 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Vibrava',
    tcgApiId: 'sm12-109',
    number: '109',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/109.png","large":"https://images.pokemontcg.io/sm12/109_hires.png"}',
    searchName: 'Vibrava (CEC 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Flygon-GX',
    tcgApiId: 'sm12-110',
    number: '110',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/110.png","large":"https://images.pokemontcg.io/sm12/110_hires.png"}',
    searchName: 'Flygon-GX (CEC 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Anorith',
    tcgApiId: 'sm12-111',
    number: '111',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/111.png","large":"https://images.pokemontcg.io/sm12/111_hires.png"}',
    searchName: 'Anorith (CEC 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Armaldo',
    tcgApiId: 'sm12-112',
    number: '112',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/112.png","large":"https://images.pokemontcg.io/sm12/112_hires.png"}',
    searchName: 'Armaldo (CEC 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Groudon',
    tcgApiId: 'sm12-113',
    number: '113',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/113.png","large":"https://images.pokemontcg.io/sm12/113_hires.png"}',
    searchName: 'Groudon (CEC 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Drilbur',
    tcgApiId: 'sm12-114',
    number: '114',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/114.png","large":"https://images.pokemontcg.io/sm12/114_hires.png"}',
    searchName: 'Drilbur (CEC 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Excadrill',
    tcgApiId: 'sm12-115',
    number: '115',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/115.png","large":"https://images.pokemontcg.io/sm12/115_hires.png"}',
    searchName: 'Excadrill (CEC 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Palpitoad',
    tcgApiId: 'sm12-116',
    number: '116',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/116.png","large":"https://images.pokemontcg.io/sm12/116_hires.png"}',
    searchName: 'Palpitoad (CEC 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Seismitoad',
    tcgApiId: 'sm12-117',
    number: '117',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/117.png","large":"https://images.pokemontcg.io/sm12/117_hires.png"}',
    searchName: 'Seismitoad (CEC 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Throh',
    tcgApiId: 'sm12-118',
    number: '118',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/118.png","large":"https://images.pokemontcg.io/sm12/118_hires.png"}',
    searchName: 'Throh (CEC 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Pancham',
    tcgApiId: 'sm12-119',
    number: '119',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/119.png","large":"https://images.pokemontcg.io/sm12/119_hires.png"}',
    searchName: 'Pancham (CEC 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Pangoro',
    tcgApiId: 'sm12-120',
    number: '120',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/120.png","large":"https://images.pokemontcg.io/sm12/120_hires.png"}',
    searchName: 'Pangoro (CEC 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Crabrawler',
    tcgApiId: 'sm12-121',
    number: '121',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/121.png","large":"https://images.pokemontcg.io/sm12/121_hires.png"}',
    searchName: 'Crabrawler (CEC 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Crabominable',
    tcgApiId: 'sm12-122',
    number: '122',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/122.png","large":"https://images.pokemontcg.io/sm12/122_hires.png"}',
    searchName: 'Crabominable (CEC 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Rockruff',
    tcgApiId: 'sm12-123',
    number: '123',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/123.png","large":"https://images.pokemontcg.io/sm12/123_hires.png"}',
    searchName: 'Rockruff (CEC 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Lycanroc',
    tcgApiId: 'sm12-124',
    number: '124',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/124.png","large":"https://images.pokemontcg.io/sm12/124_hires.png"}',
    searchName: 'Lycanroc (CEC 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Passimian',
    tcgApiId: 'sm12-125',
    number: '125',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/125.png","large":"https://images.pokemontcg.io/sm12/125_hires.png"}',
    searchName: 'Passimian (CEC 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Sandygast',
    tcgApiId: 'sm12-126',
    number: '126',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/126.png","large":"https://images.pokemontcg.io/sm12/126_hires.png"}',
    searchName: 'Sandygast (CEC 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Palossand',
    tcgApiId: 'sm12-127',
    number: '127',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/127.png","large":"https://images.pokemontcg.io/sm12/127_hires.png"}',
    searchName: 'Palossand (CEC 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Meowth',
    tcgApiId: 'sm12-128',
    number: '128',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/128.png","large":"https://images.pokemontcg.io/sm12/128_hires.png"}',
    searchName: 'Alolan Meowth (CEC 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Persian-GX',
    tcgApiId: 'sm12-129',
    number: '129',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/129.png","large":"https://images.pokemontcg.io/sm12/129_hires.png"}',
    searchName: 'Alolan Persian-GX (CEC 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Grimer',
    tcgApiId: 'sm12-130',
    number: '130',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/130.png","large":"https://images.pokemontcg.io/sm12/130_hires.png"}',
    searchName: 'Alolan Grimer (CEC 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Muk',
    tcgApiId: 'sm12-131',
    number: '131',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/131.png","large":"https://images.pokemontcg.io/sm12/131_hires.png"}',
    searchName: 'Alolan Muk (CEC 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Carvanha',
    tcgApiId: 'sm12-132',
    number: '132',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/132.png","large":"https://images.pokemontcg.io/sm12/132_hires.png"}',
    searchName: 'Carvanha (CEC 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Absol',
    tcgApiId: 'sm12-133',
    number: '133',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/133.png","large":"https://images.pokemontcg.io/sm12/133_hires.png"}',
    searchName: 'Absol (CEC 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Pawniard',
    tcgApiId: 'sm12-134',
    number: '134',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/134.png","large":"https://images.pokemontcg.io/sm12/134_hires.png"}',
    searchName: 'Pawniard (CEC 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Bisharp',
    tcgApiId: 'sm12-135',
    number: '135',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/135.png","large":"https://images.pokemontcg.io/sm12/135_hires.png"}',
    searchName: 'Bisharp (CEC 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Guzzlord',
    tcgApiId: 'sm12-136',
    number: '136',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/136.png","large":"https://images.pokemontcg.io/sm12/136_hires.png"}',
    searchName: 'Guzzlord (CEC 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Sandshrew',
    tcgApiId: 'sm12-137',
    number: '137',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/137.png","large":"https://images.pokemontcg.io/sm12/137_hires.png"}',
    searchName: 'Alolan Sandshrew (CEC 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Sandslash',
    tcgApiId: 'sm12-138',
    number: '138',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/138.png","large":"https://images.pokemontcg.io/sm12/138_hires.png"}',
    searchName: 'Alolan Sandslash (CEC 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Steelix',
    tcgApiId: 'sm12-139',
    number: '139',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/139.png","large":"https://images.pokemontcg.io/sm12/139_hires.png"}',
    searchName: 'Steelix (CEC 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mawile',
    tcgApiId: 'sm12-140',
    number: '140',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/140.png","large":"https://images.pokemontcg.io/sm12/140_hires.png"}',
    searchName: 'Mawile (CEC 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Probopass',
    tcgApiId: 'sm12-141',
    number: '141',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/141.png","large":"https://images.pokemontcg.io/sm12/141_hires.png"}',
    searchName: 'Probopass (CEC 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Solgaleo',
    tcgApiId: 'sm12-142',
    number: '142',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/142.png","large":"https://images.pokemontcg.io/sm12/142_hires.png"}',
    searchName: 'Solgaleo (CEC 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Togepi & Cleffa & Igglybuff-GX',
    tcgApiId: 'sm12-143',
    number: '143',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/143.png","large":"https://images.pokemontcg.io/sm12/143_hires.png"}',
    searchName: 'Togepi & Cleffa & Igglybuff-GX (CEC 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Togepi & Cleffa & Igglybuff-GX',
    tcgApiId: 'sm12-143a',
    number: '143a',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/143a.png","large":"https://images.pokemontcg.io/sm12/143a_hires.png"}',
    searchName: 'Togepi & Cleffa & Igglybuff-GX (CEC 143a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Clefairy',
    tcgApiId: 'sm12-144',
    number: '144',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/144.png","large":"https://images.pokemontcg.io/sm12/144_hires.png"}',
    searchName: 'Clefairy (CEC 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Ninetales',
    tcgApiId: 'sm12-145',
    number: '145',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/145.png","large":"https://images.pokemontcg.io/sm12/145_hires.png"}',
    searchName: 'Alolan Ninetales (CEC 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Azurill',
    tcgApiId: 'sm12-146',
    number: '146',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/146.png","large":"https://images.pokemontcg.io/sm12/146_hires.png"}',
    searchName: 'Azurill (CEC 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Cottonee',
    tcgApiId: 'sm12-147',
    number: '147',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/147.png","large":"https://images.pokemontcg.io/sm12/147_hires.png"}',
    searchName: 'Cottonee (CEC 147)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Whimsicott',
    tcgApiId: 'sm12-148',
    number: '148',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/148.png","large":"https://images.pokemontcg.io/sm12/148_hires.png"}',
    searchName: 'Whimsicott (CEC 148)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Flabébé',
    tcgApiId: 'sm12-149',
    number: '149',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/149.png","large":"https://images.pokemontcg.io/sm12/149_hires.png"}',
    searchName: 'Flabébé (CEC 149)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Flabébé',
    tcgApiId: 'sm12-150',
    number: '150',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/150.png","large":"https://images.pokemontcg.io/sm12/150_hires.png"}',
    searchName: 'Flabébé (CEC 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Floette',
    tcgApiId: 'sm12-151',
    number: '151',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/151.png","large":"https://images.pokemontcg.io/sm12/151_hires.png"}',
    searchName: 'Floette (CEC 151)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Florges',
    tcgApiId: 'sm12-152',
    number: '152',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/152.png","large":"https://images.pokemontcg.io/sm12/152_hires.png"}',
    searchName: 'Florges (CEC 152)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Swirlix',
    tcgApiId: 'sm12-153',
    number: '153',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/153.png","large":"https://images.pokemontcg.io/sm12/153_hires.png"}',
    searchName: 'Swirlix (CEC 153)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Slurpuff',
    tcgApiId: 'sm12-154',
    number: '154',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/154.png","large":"https://images.pokemontcg.io/sm12/154_hires.png"}',
    searchName: 'Slurpuff (CEC 154)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Sylveon',
    tcgApiId: 'sm12-155',
    number: '155',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/155.png","large":"https://images.pokemontcg.io/sm12/155_hires.png"}',
    searchName: 'Sylveon (CEC 155)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Arceus & Dialga & Palkia-GX',
    tcgApiId: 'sm12-156',
    number: '156',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/156.png","large":"https://images.pokemontcg.io/sm12/156_hires.png"}',
    searchName: 'Arceus & Dialga & Palkia-GX (CEC 156)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Reshiram & Zekrom-GX',
    tcgApiId: 'sm12-157',
    number: '157',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/157.png","large":"https://images.pokemontcg.io/sm12/157_hires.png"}',
    searchName: 'Reshiram & Zekrom-GX (CEC 157)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Naganadel & Guzzlord-GX',
    tcgApiId: 'sm12-158',
    number: '158',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/158.png","large":"https://images.pokemontcg.io/sm12/158_hires.png"}',
    searchName: 'Naganadel & Guzzlord-GX (CEC 158)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Drampa',
    tcgApiId: 'sm12-159',
    number: '159',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/159.png","large":"https://images.pokemontcg.io/sm12/159_hires.png"}',
    searchName: 'Drampa (CEC 159)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Jangmo-o',
    tcgApiId: 'sm12-160',
    number: '160',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/160.png","large":"https://images.pokemontcg.io/sm12/160_hires.png"}',
    searchName: 'Jangmo-o (CEC 160)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Jangmo-o',
    tcgApiId: 'sm12-161',
    number: '161',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/161.png","large":"https://images.pokemontcg.io/sm12/161_hires.png"}',
    searchName: 'Jangmo-o (CEC 161)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Hakamo-o',
    tcgApiId: 'sm12-162',
    number: '162',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/162.png","large":"https://images.pokemontcg.io/sm12/162_hires.png"}',
    searchName: 'Hakamo-o (CEC 162)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Kommo-o',
    tcgApiId: 'sm12-163',
    number: '163',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/163.png","large":"https://images.pokemontcg.io/sm12/163_hires.png"}',
    searchName: 'Kommo-o (CEC 163)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Ultra Necrozma',
    tcgApiId: 'sm12-164',
    number: '164',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/164.png","large":"https://images.pokemontcg.io/sm12/164_hires.png"}',
    searchName: 'Ultra Necrozma (CEC 164)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mega Lopunny & Jigglypuff-GX',
    tcgApiId: 'sm12-165',
    number: '165',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/165.png","large":"https://images.pokemontcg.io/sm12/165_hires.png"}',
    searchName: 'Mega Lopunny & Jigglypuff-GX (CEC 165)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Eevee',
    tcgApiId: 'sm12-166',
    number: '166',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/166.png","large":"https://images.pokemontcg.io/sm12/166_hires.png"}',
    searchName: 'Eevee (CEC 166)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Eevee',
    tcgApiId: 'sm12-167',
    number: '167',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/167.png","large":"https://images.pokemontcg.io/sm12/167_hires.png"}',
    searchName: 'Eevee (CEC 167)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Igglybuff',
    tcgApiId: 'sm12-168',
    number: '168',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/168.png","large":"https://images.pokemontcg.io/sm12/168_hires.png"}',
    searchName: 'Igglybuff (CEC 168)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Aipom',
    tcgApiId: 'sm12-169',
    number: '169',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/169.png","large":"https://images.pokemontcg.io/sm12/169_hires.png"}',
    searchName: 'Aipom (CEC 169)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Ambipom',
    tcgApiId: 'sm12-170',
    number: '170',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/170.png","large":"https://images.pokemontcg.io/sm12/170_hires.png"}',
    searchName: 'Ambipom (CEC 170)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Teddiursa',
    tcgApiId: 'sm12-171',
    number: '171',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/171.png","large":"https://images.pokemontcg.io/sm12/171_hires.png"}',
    searchName: 'Teddiursa (CEC 171)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Ursaring',
    tcgApiId: 'sm12-172',
    number: '172',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/172.png","large":"https://images.pokemontcg.io/sm12/172_hires.png"}',
    searchName: 'Ursaring (CEC 172)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Zangoose',
    tcgApiId: 'sm12-173',
    number: '173',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/173.png","large":"https://images.pokemontcg.io/sm12/173_hires.png"}',
    searchName: 'Zangoose (CEC 173)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Lillipup',
    tcgApiId: 'sm12-174',
    number: '174',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/174.png","large":"https://images.pokemontcg.io/sm12/174_hires.png"}',
    searchName: 'Lillipup (CEC 174)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Herdier',
    tcgApiId: 'sm12-175',
    number: '175',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/175.png","large":"https://images.pokemontcg.io/sm12/175_hires.png"}',
    searchName: 'Herdier (CEC 175)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Stoutland',
    tcgApiId: 'sm12-176',
    number: '176',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/176.png","large":"https://images.pokemontcg.io/sm12/176_hires.png"}',
    searchName: 'Stoutland (CEC 176)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Rufflet',
    tcgApiId: 'sm12-177',
    number: '177',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/177.png","large":"https://images.pokemontcg.io/sm12/177_hires.png"}',
    searchName: 'Rufflet (CEC 177)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Braviary',
    tcgApiId: 'sm12-178',
    number: '178',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/178.png","large":"https://images.pokemontcg.io/sm12/178_hires.png"}',
    searchName: 'Braviary (CEC 178)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Helioptile',
    tcgApiId: 'sm12-179',
    number: '179',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/179.png","large":"https://images.pokemontcg.io/sm12/179_hires.png"}',
    searchName: 'Helioptile (CEC 179)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Heliolisk',
    tcgApiId: 'sm12-180',
    number: '180',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/180.png","large":"https://images.pokemontcg.io/sm12/180_hires.png"}',
    searchName: 'Heliolisk (CEC 180)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Stufful',
    tcgApiId: 'sm12-181',
    number: '181',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/181.png","large":"https://images.pokemontcg.io/sm12/181_hires.png"}',
    searchName: 'Stufful (CEC 181)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Bewear',
    tcgApiId: 'sm12-182',
    number: '182',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/182.png","large":"https://images.pokemontcg.io/sm12/182_hires.png"}',
    searchName: 'Bewear (CEC 182)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Type: Null',
    tcgApiId: 'sm12-183',
    number: '183',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/183.png","large":"https://images.pokemontcg.io/sm12/183_hires.png"}',
    searchName: 'Type: Null (CEC 183)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Silvally-GX',
    tcgApiId: 'sm12-184',
    number: '184',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/184.png","large":"https://images.pokemontcg.io/sm12/184_hires.png"}',
    searchName: 'Silvally-GX (CEC 184)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Beastite',
    tcgApiId: 'sm12-185',
    number: '185',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/185.png","large":"https://images.pokemontcg.io/sm12/185_hires.png"}',
    searchName: 'Beastite (CEC 185)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Bellelba & Brycen-Man',
    tcgApiId: 'sm12-186',
    number: '186',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/186.png","large":"https://images.pokemontcg.io/sm12/186_hires.png"}',
    searchName: 'Bellelba & Brycen-Man (CEC 186)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Chaotic Swell',
    tcgApiId: 'sm12-187',
    number: '187',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/187.png","large":"https://images.pokemontcg.io/sm12/187_hires.png"}',
    searchName: 'Chaotic Swell (CEC 187)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Clay',
    tcgApiId: 'sm12-188',
    number: '188',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/188.png","large":"https://images.pokemontcg.io/sm12/188_hires.png"}',
    searchName: 'Clay (CEC 188)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Cynthia & Caitlin',
    tcgApiId: 'sm12-189',
    number: '189',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/189.png","large":"https://images.pokemontcg.io/sm12/189_hires.png"}',
    searchName: 'Cynthia & Caitlin (CEC 189)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Dragonium Z: Dragon Claw',
    tcgApiId: 'sm12-190',
    number: '190',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/190.png","large":"https://images.pokemontcg.io/sm12/190_hires.png"}',
    searchName: 'Dragonium Z: Dragon Claw (CEC 190)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Erika',
    tcgApiId: 'sm12-191',
    number: '191',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/191.png","large":"https://images.pokemontcg.io/sm12/191_hires.png"}',
    searchName: 'Erika (CEC 191)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Great Catcher',
    tcgApiId: 'sm12-192',
    number: '192',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/192.png","large":"https://images.pokemontcg.io/sm12/192_hires.png"}',
    searchName: 'Great Catcher (CEC 192)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Guzma & Hala',
    tcgApiId: 'sm12-193',
    number: '193',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/193.png","large":"https://images.pokemontcg.io/sm12/193_hires.png"}',
    searchName: 'Guzma & Hala (CEC 193)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Island Challenge Amulet',
    tcgApiId: 'sm12-194',
    number: '194',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/194.png","large":"https://images.pokemontcg.io/sm12/194_hires.png"}',
    searchName: 'Island Challenge Amulet (CEC 194)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "Lana's Fishing Rod",
    tcgApiId: 'sm12-195',
    number: '195',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/195.png","large":"https://images.pokemontcg.io/sm12/195_hires.png"}',
    searchName: "Lana's Fishing Rod (CEC 195)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "Lillie's Full Force",
    tcgApiId: 'sm12-196',
    number: '196',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/196.png","large":"https://images.pokemontcg.io/sm12/196_hires.png"}',
    searchName: "Lillie's Full Force (CEC 196)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "Lillie's Poké Doll",
    tcgApiId: 'sm12-197',
    number: '197',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/197.png","large":"https://images.pokemontcg.io/sm12/197_hires.png"}',
    searchName: "Lillie's Poké Doll (CEC 197)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mallow & Lana',
    tcgApiId: 'sm12-198',
    number: '198',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/198.png","large":"https://images.pokemontcg.io/sm12/198_hires.png"}',
    searchName: 'Mallow & Lana (CEC 198)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Misty & Lorelei',
    tcgApiId: 'sm12-199',
    number: '199',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/199.png","large":"https://images.pokemontcg.io/sm12/199_hires.png"}',
    searchName: 'Misty & Lorelei (CEC 199)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "N's Resolve",
    tcgApiId: 'sm12-200',
    number: '200',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/200.png","large":"https://images.pokemontcg.io/sm12/200_hires.png"}',
    searchName: "N's Resolve (CEC 200)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "Professor Oak's Setup",
    tcgApiId: 'sm12-201',
    number: '201',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/201.png","large":"https://images.pokemontcg.io/sm12/201_hires.png"}',
    searchName: "Professor Oak's Setup (CEC 201)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Red & Blue',
    tcgApiId: 'sm12-202',
    number: '202',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/202.png","large":"https://images.pokemontcg.io/sm12/202_hires.png"}',
    searchName: 'Red & Blue (CEC 202)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Roller Skater',
    tcgApiId: 'sm12-203',
    number: '203',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/203.png","large":"https://images.pokemontcg.io/sm12/203_hires.png"}',
    searchName: 'Roller Skater (CEC 203)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Rosa',
    tcgApiId: 'sm12-204',
    number: '204',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/204.png","large":"https://images.pokemontcg.io/sm12/204_hires.png"}',
    searchName: 'Rosa (CEC 204)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Roxie',
    tcgApiId: 'sm12-205',
    number: '205',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/205.png","large":"https://images.pokemontcg.io/sm12/205_hires.png"}',
    searchName: 'Roxie (CEC 205)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Tag Call',
    tcgApiId: 'sm12-206',
    number: '206',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/206.png","large":"https://images.pokemontcg.io/sm12/206_hires.png"}',
    searchName: 'Tag Call (CEC 206)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Unidentified Fossil',
    tcgApiId: 'sm12-207',
    number: '207',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/207.png","large":"https://images.pokemontcg.io/sm12/207_hires.png"}',
    searchName: 'Unidentified Fossil (CEC 207)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Will',
    tcgApiId: 'sm12-208',
    number: '208',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/208.png","large":"https://images.pokemontcg.io/sm12/208_hires.png"}',
    searchName: 'Will (CEC 208)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Draw Energy',
    tcgApiId: 'sm12-209',
    number: '209',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/209.png","large":"https://images.pokemontcg.io/sm12/209_hires.png"}',
    searchName: 'Draw Energy (CEC 209)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Venusaur & Snivy-GX',
    tcgApiId: 'sm12-210',
    number: '210',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/210.png","large":"https://images.pokemontcg.io/sm12/210_hires.png"}',
    searchName: 'Venusaur & Snivy-GX (CEC 210)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Vileplume-GX',
    tcgApiId: 'sm12-211',
    number: '211',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/211.png","large":"https://images.pokemontcg.io/sm12/211_hires.png"}',
    searchName: 'Vileplume-GX (CEC 211)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Charizard & Braixen-GX',
    tcgApiId: 'sm12-212',
    number: '212',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/212.png","large":"https://images.pokemontcg.io/sm12/212_hires.png"}',
    searchName: 'Charizard & Braixen-GX (CEC 212)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Volcarona-GX',
    tcgApiId: 'sm12-213',
    number: '213',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/213.png","large":"https://images.pokemontcg.io/sm12/213_hires.png"}',
    searchName: 'Volcarona-GX (CEC 213)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Blastoise & Piplup-GX',
    tcgApiId: 'sm12-214',
    number: '214',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/214.png","large":"https://images.pokemontcg.io/sm12/214_hires.png"}',
    searchName: 'Blastoise & Piplup-GX (CEC 214)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Blastoise & Piplup-GX',
    tcgApiId: 'sm12-215',
    number: '215',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/215.png","large":"https://images.pokemontcg.io/sm12/215_hires.png"}',
    searchName: 'Blastoise & Piplup-GX (CEC 215)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Solgaleo & Lunala-GX',
    tcgApiId: 'sm12-216',
    number: '216',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/216.png","large":"https://images.pokemontcg.io/sm12/216_hires.png"}',
    searchName: 'Solgaleo & Lunala-GX (CEC 216)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Oricorio-GX',
    tcgApiId: 'sm12-217',
    number: '217',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/217.png","large":"https://images.pokemontcg.io/sm12/217_hires.png"}',
    searchName: 'Oricorio-GX (CEC 217)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Flygon-GX',
    tcgApiId: 'sm12-218',
    number: '218',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/218.png","large":"https://images.pokemontcg.io/sm12/218_hires.png"}',
    searchName: 'Flygon-GX (CEC 218)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Persian-GX',
    tcgApiId: 'sm12-219',
    number: '219',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/219.png","large":"https://images.pokemontcg.io/sm12/219_hires.png"}',
    searchName: 'Alolan Persian-GX (CEC 219)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Arceus & Dialga & Palkia-GX',
    tcgApiId: 'sm12-220',
    number: '220',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/220.png","large":"https://images.pokemontcg.io/sm12/220_hires.png"}',
    searchName: 'Arceus & Dialga & Palkia-GX (CEC 220)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Arceus & Dialga & Palkia-GX',
    tcgApiId: 'sm12-221',
    number: '221',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/221.png","large":"https://images.pokemontcg.io/sm12/221_hires.png"}',
    searchName: 'Arceus & Dialga & Palkia-GX (CEC 221)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Reshiram & Zekrom-GX',
    tcgApiId: 'sm12-222',
    number: '222',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/222.png","large":"https://images.pokemontcg.io/sm12/222_hires.png"}',
    searchName: 'Reshiram & Zekrom-GX (CEC 222)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Naganadel & Guzzlord-GX',
    tcgApiId: 'sm12-223',
    number: '223',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/223.png","large":"https://images.pokemontcg.io/sm12/223_hires.png"}',
    searchName: 'Naganadel & Guzzlord-GX (CEC 223)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Naganadel & Guzzlord-GX',
    tcgApiId: 'sm12-224',
    number: '224',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/224.png","large":"https://images.pokemontcg.io/sm12/224_hires.png"}',
    searchName: 'Naganadel & Guzzlord-GX (CEC 224)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mega Lopunny & Jigglypuff-GX',
    tcgApiId: 'sm12-225',
    number: '225',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/225.png","large":"https://images.pokemontcg.io/sm12/225_hires.png"}',
    searchName: 'Mega Lopunny & Jigglypuff-GX (CEC 225)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mega Lopunny & Jigglypuff-GX',
    tcgApiId: 'sm12-226',
    number: '226',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/226.png","large":"https://images.pokemontcg.io/sm12/226_hires.png"}',
    searchName: 'Mega Lopunny & Jigglypuff-GX (CEC 226)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Silvally-GX',
    tcgApiId: 'sm12-227',
    number: '227',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/227.png","large":"https://images.pokemontcg.io/sm12/227_hires.png"}',
    searchName: 'Silvally-GX (CEC 227)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Cynthia & Caitlin',
    tcgApiId: 'sm12-228',
    number: '228',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/228.png","large":"https://images.pokemontcg.io/sm12/228_hires.png"}',
    searchName: 'Cynthia & Caitlin (CEC 228)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Guzma & Hala',
    tcgApiId: 'sm12-229',
    number: '229',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/229.png","large":"https://images.pokemontcg.io/sm12/229_hires.png"}',
    searchName: 'Guzma & Hala (CEC 229)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "Lillie's Full Force",
    tcgApiId: 'sm12-230',
    number: '230',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/230.png","large":"https://images.pokemontcg.io/sm12/230_hires.png"}',
    searchName: "Lillie's Full Force (CEC 230)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mallow & Lana',
    tcgApiId: 'sm12-231',
    number: '231',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/231.png","large":"https://images.pokemontcg.io/sm12/231_hires.png"}',
    searchName: 'Mallow & Lana (CEC 231)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "N's Resolve",
    tcgApiId: 'sm12-232',
    number: '232',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/232.png","large":"https://images.pokemontcg.io/sm12/232_hires.png"}',
    searchName: "N's Resolve (CEC 232)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "Professor Oak's Setup",
    tcgApiId: 'sm12-233',
    number: '233',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/233.png","large":"https://images.pokemontcg.io/sm12/233_hires.png"}',
    searchName: "Professor Oak's Setup (CEC 233)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Red & Blue',
    tcgApiId: 'sm12-234',
    number: '234',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/234.png","large":"https://images.pokemontcg.io/sm12/234_hires.png"}',
    searchName: 'Red & Blue (CEC 234)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Roller Skater',
    tcgApiId: 'sm12-235',
    number: '235',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/235.png","large":"https://images.pokemontcg.io/sm12/235_hires.png"}',
    searchName: 'Roller Skater (CEC 235)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Rosa',
    tcgApiId: 'sm12-236',
    number: '236',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/236.png","large":"https://images.pokemontcg.io/sm12/236_hires.png"}',
    searchName: 'Rosa (CEC 236)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Torkoal',
    tcgApiId: 'sm12-237',
    number: '237',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/237.png","large":"https://images.pokemontcg.io/sm12/237_hires.png"}',
    searchName: 'Torkoal (CEC 237)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Weavile',
    tcgApiId: 'sm12-238',
    number: '238',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/238.png","large":"https://images.pokemontcg.io/sm12/238_hires.png"}',
    searchName: 'Weavile (CEC 238)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Piplup',
    tcgApiId: 'sm12-239',
    number: '239',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/239.png","large":"https://images.pokemontcg.io/sm12/239_hires.png"}',
    searchName: 'Piplup (CEC 239)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Wishiwashi',
    tcgApiId: 'sm12-240',
    number: '240',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/240.png","large":"https://images.pokemontcg.io/sm12/240_hires.png"}',
    searchName: 'Wishiwashi (CEC 240)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Pikachu',
    tcgApiId: 'sm12-241',
    number: '241',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/241.png","large":"https://images.pokemontcg.io/sm12/241_hires.png"}',
    searchName: 'Pikachu (CEC 241)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Magnemite',
    tcgApiId: 'sm12-242',
    number: '242',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/242.png","large":"https://images.pokemontcg.io/sm12/242_hires.png"}',
    searchName: 'Magnemite (CEC 242)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Koffing',
    tcgApiId: 'sm12-243',
    number: '243',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/243.png","large":"https://images.pokemontcg.io/sm12/243_hires.png"}',
    searchName: 'Koffing (CEC 243)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Gallade',
    tcgApiId: 'sm12-244',
    number: '244',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/244.png","large":"https://images.pokemontcg.io/sm12/244_hires.png"}',
    searchName: 'Gallade (CEC 244)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mimikyu',
    tcgApiId: 'sm12-245',
    number: '245',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/245.png","large":"https://images.pokemontcg.io/sm12/245_hires.png"}',
    searchName: 'Mimikyu (CEC 245)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Excadrill',
    tcgApiId: 'sm12-246',
    number: '246',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/246.png","large":"https://images.pokemontcg.io/sm12/246_hires.png"}',
    searchName: 'Excadrill (CEC 246)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Steelix',
    tcgApiId: 'sm12-247',
    number: '247',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/247.png","large":"https://images.pokemontcg.io/sm12/247_hires.png"}',
    searchName: 'Steelix (CEC 247)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Stoutland',
    tcgApiId: 'sm12-248',
    number: '248',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/248.png","large":"https://images.pokemontcg.io/sm12/248_hires.png"}',
    searchName: 'Stoutland (CEC 248)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Venusaur & Snivy-GX',
    tcgApiId: 'sm12-249',
    number: '249',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/249.png","large":"https://images.pokemontcg.io/sm12/249_hires.png"}',
    searchName: 'Venusaur & Snivy-GX (CEC 249)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Vileplume-GX',
    tcgApiId: 'sm12-250',
    number: '250',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/250.png","large":"https://images.pokemontcg.io/sm12/250_hires.png"}',
    searchName: 'Vileplume-GX (CEC 250)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Charizard & Braixen-GX',
    tcgApiId: 'sm12-251',
    number: '251',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/251.png","large":"https://images.pokemontcg.io/sm12/251_hires.png"}',
    searchName: 'Charizard & Braixen-GX (CEC 251)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Volcarona-GX',
    tcgApiId: 'sm12-252',
    number: '252',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/252.png","large":"https://images.pokemontcg.io/sm12/252_hires.png"}',
    searchName: 'Volcarona-GX (CEC 252)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Blastoise & Piplup-GX',
    tcgApiId: 'sm12-253',
    number: '253',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/253.png","large":"https://images.pokemontcg.io/sm12/253_hires.png"}',
    searchName: 'Blastoise & Piplup-GX (CEC 253)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Solgaleo & Lunala-GX',
    tcgApiId: 'sm12-254',
    number: '254',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/254.png","large":"https://images.pokemontcg.io/sm12/254_hires.png"}',
    searchName: 'Solgaleo & Lunala-GX (CEC 254)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Oricorio-GX',
    tcgApiId: 'sm12-255',
    number: '255',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/255.png","large":"https://images.pokemontcg.io/sm12/255_hires.png"}',
    searchName: 'Oricorio-GX (CEC 255)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Flygon-GX',
    tcgApiId: 'sm12-256',
    number: '256',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/256.png","large":"https://images.pokemontcg.io/sm12/256_hires.png"}',
    searchName: 'Flygon-GX (CEC 256)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Alolan Persian-GX',
    tcgApiId: 'sm12-257',
    number: '257',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/257.png","large":"https://images.pokemontcg.io/sm12/257_hires.png"}',
    searchName: 'Alolan Persian-GX (CEC 257)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Arceus & Dialga & Palkia-GX',
    tcgApiId: 'sm12-258',
    number: '258',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/258.png","large":"https://images.pokemontcg.io/sm12/258_hires.png"}',
    searchName: 'Arceus & Dialga & Palkia-GX (CEC 258)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Reshiram & Zekrom-GX',
    tcgApiId: 'sm12-259',
    number: '259',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/259.png","large":"https://images.pokemontcg.io/sm12/259_hires.png"}',
    searchName: 'Reshiram & Zekrom-GX (CEC 259)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Naganadel & Guzzlord-GX',
    tcgApiId: 'sm12-260',
    number: '260',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/260.png","large":"https://images.pokemontcg.io/sm12/260_hires.png"}',
    searchName: 'Naganadel & Guzzlord-GX (CEC 260)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Mega Lopunny & Jigglypuff-GX',
    tcgApiId: 'sm12-261',
    number: '261',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/261.png","large":"https://images.pokemontcg.io/sm12/261_hires.png"}',
    searchName: 'Mega Lopunny & Jigglypuff-GX (CEC 261)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Silvally-GX',
    tcgApiId: 'sm12-262',
    number: '262',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/262.png","large":"https://images.pokemontcg.io/sm12/262_hires.png"}',
    searchName: 'Silvally-GX (CEC 262)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Giant Hearth',
    tcgApiId: 'sm12-263',
    number: '263',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/263.png","large":"https://images.pokemontcg.io/sm12/263_hires.png"}',
    searchName: 'Giant Hearth (CEC 263)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Great Catcher',
    tcgApiId: 'sm12-264',
    number: '264',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/264.png","large":"https://images.pokemontcg.io/sm12/264_hires.png"}',
    searchName: 'Great Catcher (CEC 264)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Island Challenge Amulet',
    tcgApiId: 'sm12-265',
    number: '265',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/265.png","large":"https://images.pokemontcg.io/sm12/265_hires.png"}',
    searchName: 'Island Challenge Amulet (CEC 265)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "Lana's Fishing Rod",
    tcgApiId: 'sm12-266',
    number: '266',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/266.png","large":"https://images.pokemontcg.io/sm12/266_hires.png"}',
    searchName: "Lana's Fishing Rod (CEC 266)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: "Lillie's Poké Doll",
    tcgApiId: 'sm12-267',
    number: '267',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/267.png","large":"https://images.pokemontcg.io/sm12/267_hires.png"}',
    searchName: "Lillie's Poké Doll (CEC 267)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Martial Arts Dojo',
    tcgApiId: 'sm12-268',
    number: '268',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/268.png","large":"https://images.pokemontcg.io/sm12/268_hires.png"}',
    searchName: 'Martial Arts Dojo (CEC 268)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Power Plant',
    tcgApiId: 'sm12-269',
    number: '269',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/269.png","large":"https://images.pokemontcg.io/sm12/269_hires.png"}',
    searchName: 'Power Plant (CEC 269)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Tag Call',
    tcgApiId: 'sm12-270',
    number: '270',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/270.png","large":"https://images.pokemontcg.io/sm12/270_hires.png"}',
    searchName: 'Tag Call (CEC 270)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm12',
    name: 'Draw Energy',
    tcgApiId: 'sm12-271',
    number: '271',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm12/271.png","large":"https://images.pokemontcg.io/sm12/271_hires.png"}',
    searchName: 'Draw Energy (CEC 271)',
  },
];
