export const cardSeedSm35 = [
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Bulbasaur',
    tcgApiId: 'sm35-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/1.png","large":"https://images.pokemontcg.io/sm35/1_hires.png"}',
    searchName: 'Bulbasaur (SLG 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Ivysaur',
    tcgApiId: 'sm35-2',
    number: '2',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/2.png","large":"https://images.pokemontcg.io/sm35/2_hires.png"}',
    searchName: 'Ivysaur (SLG 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Venusaur',
    tcgApiId: 'sm35-3',
    number: '3',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/3.png","large":"https://images.pokemontcg.io/sm35/3_hires.png"}',
    searchName: 'Venusaur (SLG 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Shroomish',
    tcgApiId: 'sm35-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/4.png","large":"https://images.pokemontcg.io/sm35/4_hires.png"}',
    searchName: 'Shroomish (SLG 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Breloom',
    tcgApiId: 'sm35-5',
    number: '5',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/5.png","large":"https://images.pokemontcg.io/sm35/5_hires.png"}',
    searchName: 'Breloom (SLG 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Carnivine',
    tcgApiId: 'sm35-6',
    number: '6',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/6.png","large":"https://images.pokemontcg.io/sm35/6_hires.png"}',
    searchName: 'Carnivine (SLG 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Shaymin',
    tcgApiId: 'sm35-7',
    number: '7',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/7.png","large":"https://images.pokemontcg.io/sm35/7_hires.png"}',
    searchName: 'Shaymin (SLG 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Virizion',
    tcgApiId: 'sm35-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/8.png","large":"https://images.pokemontcg.io/sm35/8_hires.png"}',
    searchName: 'Virizion (SLG 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Shining Genesect',
    tcgApiId: 'sm35-9',
    number: '9',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/9.png","large":"https://images.pokemontcg.io/sm35/9_hires.png"}',
    searchName: 'Shining Genesect (SLG 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Entei-GX',
    tcgApiId: 'sm35-10',
    number: '10',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/10.png","large":"https://images.pokemontcg.io/sm35/10_hires.png"}',
    searchName: 'Entei-GX (SLG 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Entei-GX',
    tcgApiId: 'sm35-10a',
    number: '10a',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/10a.png","large":"https://images.pokemontcg.io/sm35/10a_hires.png"}',
    searchName: 'Entei-GX (SLG 10a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Torkoal',
    tcgApiId: 'sm35-11',
    number: '11',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/11.png","large":"https://images.pokemontcg.io/sm35/11_hires.png"}',
    searchName: 'Torkoal (SLG 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Larvesta',
    tcgApiId: 'sm35-12',
    number: '12',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/12.png","large":"https://images.pokemontcg.io/sm35/12_hires.png"}',
    searchName: 'Larvesta (SLG 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Volcarona',
    tcgApiId: 'sm35-13',
    number: '13',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/13.png","large":"https://images.pokemontcg.io/sm35/13_hires.png"}',
    searchName: 'Volcarona (SLG 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Reshiram',
    tcgApiId: 'sm35-14',
    number: '14',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/14.png","large":"https://images.pokemontcg.io/sm35/14_hires.png"}',
    searchName: 'Reshiram (SLG 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Litten',
    tcgApiId: 'sm35-15',
    number: '15',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/15.png","large":"https://images.pokemontcg.io/sm35/15_hires.png"}',
    searchName: 'Litten (SLG 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Torracat',
    tcgApiId: 'sm35-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/16.png","large":"https://images.pokemontcg.io/sm35/16_hires.png"}',
    searchName: 'Torracat (SLG 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Incineroar',
    tcgApiId: 'sm35-17',
    number: '17',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/17.png","large":"https://images.pokemontcg.io/sm35/17_hires.png"}',
    searchName: 'Incineroar (SLG 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Totodile',
    tcgApiId: 'sm35-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/18.png","large":"https://images.pokemontcg.io/sm35/18_hires.png"}',
    searchName: 'Totodile (SLG 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Croconaw',
    tcgApiId: 'sm35-19',
    number: '19',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/19.png","large":"https://images.pokemontcg.io/sm35/19_hires.png"}',
    searchName: 'Croconaw (SLG 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Feraligatr',
    tcgApiId: 'sm35-20',
    number: '20',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/20.png","large":"https://images.pokemontcg.io/sm35/20_hires.png"}',
    searchName: 'Feraligatr (SLG 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Qwilfish',
    tcgApiId: 'sm35-21',
    number: '21',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/21.png","large":"https://images.pokemontcg.io/sm35/21_hires.png"}',
    searchName: 'Qwilfish (SLG 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Buizel',
    tcgApiId: 'sm35-22',
    number: '22',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/22.png","large":"https://images.pokemontcg.io/sm35/22_hires.png"}',
    searchName: 'Buizel (SLG 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Floatzel',
    tcgApiId: 'sm35-23',
    number: '23',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/23.png","large":"https://images.pokemontcg.io/sm35/23_hires.png"}',
    searchName: 'Floatzel (SLG 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Palkia',
    tcgApiId: 'sm35-24',
    number: '24',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/24.png","large":"https://images.pokemontcg.io/sm35/24_hires.png"}',
    searchName: 'Palkia (SLG 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Manaphy',
    tcgApiId: 'sm35-25',
    number: '25',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/25.png","large":"https://images.pokemontcg.io/sm35/25_hires.png"}',
    searchName: 'Manaphy (SLG 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Keldeo',
    tcgApiId: 'sm35-26',
    number: '26',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/26.png","large":"https://images.pokemontcg.io/sm35/26_hires.png"}',
    searchName: 'Keldeo (SLG 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Shining Volcanion',
    tcgApiId: 'sm35-27',
    number: '27',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/27.png","large":"https://images.pokemontcg.io/sm35/27_hires.png"}',
    searchName: 'Shining Volcanion (SLG 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Pikachu',
    tcgApiId: 'sm35-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/28.png","large":"https://images.pokemontcg.io/sm35/28_hires.png"}',
    searchName: 'Pikachu (SLG 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Raichu-GX',
    tcgApiId: 'sm35-29',
    number: '29',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/29.png","large":"https://images.pokemontcg.io/sm35/29_hires.png"}',
    searchName: 'Raichu-GX (SLG 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Voltorb',
    tcgApiId: 'sm35-30',
    number: '30',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/30.png","large":"https://images.pokemontcg.io/sm35/30_hires.png"}',
    searchName: 'Voltorb (SLG 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Electrode',
    tcgApiId: 'sm35-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/31.png","large":"https://images.pokemontcg.io/sm35/31_hires.png"}',
    searchName: 'Electrode (SLG 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Raikou',
    tcgApiId: 'sm35-32',
    number: '32',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/32.png","large":"https://images.pokemontcg.io/sm35/32_hires.png"}',
    searchName: 'Raikou (SLG 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Plusle',
    tcgApiId: 'sm35-33',
    number: '33',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/33.png","large":"https://images.pokemontcg.io/sm35/33_hires.png"}',
    searchName: 'Plusle (SLG 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Minun',
    tcgApiId: 'sm35-34',
    number: '34',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/34.png","large":"https://images.pokemontcg.io/sm35/34_hires.png"}',
    searchName: 'Minun (SLG 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Zekrom',
    tcgApiId: 'sm35-35',
    number: '35',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/35.png","large":"https://images.pokemontcg.io/sm35/35_hires.png"}',
    searchName: 'Zekrom (SLG 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Ekans',
    tcgApiId: 'sm35-36',
    number: '36',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/36.png","large":"https://images.pokemontcg.io/sm35/36_hires.png"}',
    searchName: 'Ekans (SLG 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Arbok',
    tcgApiId: 'sm35-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/37.png","large":"https://images.pokemontcg.io/sm35/37_hires.png"}',
    searchName: 'Arbok (SLG 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Jynx',
    tcgApiId: 'sm35-38',
    number: '38',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/38.png","large":"https://images.pokemontcg.io/sm35/38_hires.png"}',
    searchName: 'Jynx (SLG 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Mewtwo-GX',
    tcgApiId: 'sm35-39',
    number: '39',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/39.png","large":"https://images.pokemontcg.io/sm35/39_hires.png"}',
    searchName: 'Mewtwo-GX (SLG 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Shining Mew',
    tcgApiId: 'sm35-40',
    number: '40',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/40.png","large":"https://images.pokemontcg.io/sm35/40_hires.png"}',
    searchName: 'Shining Mew (SLG 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Latios',
    tcgApiId: 'sm35-41',
    number: '41',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/41.png","large":"https://images.pokemontcg.io/sm35/41_hires.png"}',
    searchName: 'Latios (SLG 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Shining Jirachi',
    tcgApiId: 'sm35-42',
    number: '42',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/42.png","large":"https://images.pokemontcg.io/sm35/42_hires.png"}',
    searchName: 'Shining Jirachi (SLG 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Golett',
    tcgApiId: 'sm35-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/43.png","large":"https://images.pokemontcg.io/sm35/43_hires.png"}',
    searchName: 'Golett (SLG 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Golurk',
    tcgApiId: 'sm35-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/44.png","large":"https://images.pokemontcg.io/sm35/44_hires.png"}',
    searchName: 'Golurk (SLG 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Marshadow',
    tcgApiId: 'sm35-45',
    number: '45',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/45.png","large":"https://images.pokemontcg.io/sm35/45_hires.png"}',
    searchName: 'Marshadow (SLG 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Stunfisk',
    tcgApiId: 'sm35-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/46.png","large":"https://images.pokemontcg.io/sm35/46_hires.png"}',
    searchName: 'Stunfisk (SLG 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Spiritomb',
    tcgApiId: 'sm35-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/47.png","large":"https://images.pokemontcg.io/sm35/47_hires.png"}',
    searchName: 'Spiritomb (SLG 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Purrloin',
    tcgApiId: 'sm35-48',
    number: '48',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/48.png","large":"https://images.pokemontcg.io/sm35/48_hires.png"}',
    searchName: 'Purrloin (SLG 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Liepard',
    tcgApiId: 'sm35-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/49.png","large":"https://images.pokemontcg.io/sm35/49_hires.png"}',
    searchName: 'Liepard (SLG 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Scraggy',
    tcgApiId: 'sm35-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/50.png","large":"https://images.pokemontcg.io/sm35/50_hires.png"}',
    searchName: 'Scraggy (SLG 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Scrafty',
    tcgApiId: 'sm35-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/51.png","large":"https://images.pokemontcg.io/sm35/51_hires.png"}',
    searchName: 'Scrafty (SLG 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Zorua',
    tcgApiId: 'sm35-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/52.png","large":"https://images.pokemontcg.io/sm35/52_hires.png"}',
    searchName: 'Zorua (SLG 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Zoroark-GX',
    tcgApiId: 'sm35-53',
    number: '53',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/53.png","large":"https://images.pokemontcg.io/sm35/53_hires.png"}',
    searchName: 'Zoroark-GX (SLG 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Yveltal',
    tcgApiId: 'sm35-54',
    number: '54',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/54.png","large":"https://images.pokemontcg.io/sm35/54_hires.png"}',
    searchName: 'Yveltal (SLG 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Hoopa',
    tcgApiId: 'sm35-55',
    number: '55',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/55.png","large":"https://images.pokemontcg.io/sm35/55_hires.png"}',
    searchName: 'Hoopa (SLG 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Shining Rayquaza',
    tcgApiId: 'sm35-56',
    number: '56',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/56.png","large":"https://images.pokemontcg.io/sm35/56_hires.png"}',
    searchName: 'Shining Rayquaza (SLG 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Shining Arceus',
    tcgApiId: 'sm35-57',
    number: '57',
    rarity: 'Rare Shining',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/57.png","large":"https://images.pokemontcg.io/sm35/57_hires.png"}',
    searchName: 'Shining Arceus (SLG 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Damage Mover',
    tcgApiId: 'sm35-58',
    number: '58',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/58.png","large":"https://images.pokemontcg.io/sm35/58_hires.png"}',
    searchName: 'Damage Mover (SLG 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Energy Retrieval',
    tcgApiId: 'sm35-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/59.png","large":"https://images.pokemontcg.io/sm35/59_hires.png"}',
    searchName: 'Energy Retrieval (SLG 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Great Ball',
    tcgApiId: 'sm35-60',
    number: '60',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/60.png","large":"https://images.pokemontcg.io/sm35/60_hires.png"}',
    searchName: 'Great Ball (SLG 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Hau',
    tcgApiId: 'sm35-61',
    number: '61',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/61.png","large":"https://images.pokemontcg.io/sm35/61_hires.png"}',
    searchName: 'Hau (SLG 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Lillie',
    tcgApiId: 'sm35-62',
    number: '62',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/62.png","large":"https://images.pokemontcg.io/sm35/62_hires.png"}',
    searchName: 'Lillie (SLG 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Pokémon Breeder',
    tcgApiId: 'sm35-63',
    number: '63',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/63.png","large":"https://images.pokemontcg.io/sm35/63_hires.png"}',
    searchName: 'Pokémon Breeder (SLG 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Pokémon Catcher',
    tcgApiId: 'sm35-64',
    number: '64',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/64.png","large":"https://images.pokemontcg.io/sm35/64_hires.png"}',
    searchName: 'Pokémon Catcher (SLG 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Sophocles',
    tcgApiId: 'sm35-65',
    number: '65',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/65.png","large":"https://images.pokemontcg.io/sm35/65_hires.png"}',
    searchName: 'Sophocles (SLG 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Super Scoop Up',
    tcgApiId: 'sm35-66',
    number: '66',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/66.png","large":"https://images.pokemontcg.io/sm35/66_hires.png"}',
    searchName: 'Super Scoop Up (SLG 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Switch',
    tcgApiId: 'sm35-67',
    number: '67',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/67.png","large":"https://images.pokemontcg.io/sm35/67_hires.png"}',
    searchName: 'Switch (SLG 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Ultra Ball',
    tcgApiId: 'sm35-68',
    number: '68',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/68.png","large":"https://images.pokemontcg.io/sm35/68_hires.png"}',
    searchName: 'Ultra Ball (SLG 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Ultra Ball',
    tcgApiId: 'sm35-68a',
    number: '68a',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/68a.png","large":"https://images.pokemontcg.io/sm35/68a_hires.png"}',
    searchName: 'Ultra Ball (SLG 68a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Double Colorless Energy',
    tcgApiId: 'sm35-69',
    number: '69',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/69.png","large":"https://images.pokemontcg.io/sm35/69_hires.png"}',
    searchName: 'Double Colorless Energy (SLG 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Warp Energy',
    tcgApiId: 'sm35-70',
    number: '70',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/70.png","large":"https://images.pokemontcg.io/sm35/70_hires.png"}',
    searchName: 'Warp Energy (SLG 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Entei-GX',
    tcgApiId: 'sm35-71',
    number: '71',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/71.png","large":"https://images.pokemontcg.io/sm35/71_hires.png"}',
    searchName: 'Entei-GX (SLG 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Mewtwo-GX',
    tcgApiId: 'sm35-72',
    number: '72',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/72.png","large":"https://images.pokemontcg.io/sm35/72_hires.png"}',
    searchName: 'Mewtwo-GX (SLG 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Pokémon Breeder',
    tcgApiId: 'sm35-73',
    number: '73',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/73.png","large":"https://images.pokemontcg.io/sm35/73_hires.png"}',
    searchName: 'Pokémon Breeder (SLG 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Entei-GX',
    tcgApiId: 'sm35-74',
    number: '74',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/74.png","large":"https://images.pokemontcg.io/sm35/74_hires.png"}',
    searchName: 'Entei-GX (SLG 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Raichu-GX',
    tcgApiId: 'sm35-75',
    number: '75',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/75.png","large":"https://images.pokemontcg.io/sm35/75_hires.png"}',
    searchName: 'Raichu-GX (SLG 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Mewtwo-GX',
    tcgApiId: 'sm35-76',
    number: '76',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/76.png","large":"https://images.pokemontcg.io/sm35/76_hires.png"}',
    searchName: 'Mewtwo-GX (SLG 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Zoroark-GX',
    tcgApiId: 'sm35-77',
    number: '77',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/77.png","large":"https://images.pokemontcg.io/sm35/77_hires.png"}',
    searchName: 'Zoroark-GX (SLG 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Zoroark-GX',
    tcgApiId: 'sm35-77a',
    number: '77a',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/77a.png","large":"https://images.pokemontcg.io/sm35/77a_hires.png"}',
    searchName: 'Zoroark-GX (SLG 77a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm35',
    name: 'Mewtwo-GX',
    tcgApiId: 'sm35-78',
    number: '78',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm35/78.png","large":"https://images.pokemontcg.io/sm35/78_hires.png"}',
    searchName: 'Mewtwo-GX (SLG 78)',
  },
];
