export const cardSeedSm6 = [
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Exeggcute',
    tcgApiId: 'sm6-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/1.png","large":"https://images.pokemontcg.io/sm6/1_hires.png"}',
    searchName: 'Exeggcute (FLI 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Alolan Exeggutor',
    tcgApiId: 'sm6-2',
    number: '2',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/2.png","large":"https://images.pokemontcg.io/sm6/2_hires.png"}',
    searchName: 'Alolan Exeggutor (FLI 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Alolan Exeggutor',
    tcgApiId: 'sm6-2a',
    number: '2a',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/2a.png","large":"https://images.pokemontcg.io/sm6/2a_hires.png"}',
    searchName: 'Alolan Exeggutor (FLI 2a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Snover',
    tcgApiId: 'sm6-3',
    number: '3',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/3.png","large":"https://images.pokemontcg.io/sm6/3_hires.png"}',
    searchName: 'Snover (FLI 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Abomasnow',
    tcgApiId: 'sm6-4',
    number: '4',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/4.png","large":"https://images.pokemontcg.io/sm6/4_hires.png"}',
    searchName: 'Abomasnow (FLI 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Scatterbug',
    tcgApiId: 'sm6-5',
    number: '5',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/5.png","large":"https://images.pokemontcg.io/sm6/5_hires.png"}',
    searchName: 'Scatterbug (FLI 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Scatterbug',
    tcgApiId: 'sm6-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/6.png","large":"https://images.pokemontcg.io/sm6/6_hires.png"}',
    searchName: 'Scatterbug (FLI 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Spewpa',
    tcgApiId: 'sm6-7',
    number: '7',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/7.png","large":"https://images.pokemontcg.io/sm6/7_hires.png"}',
    searchName: 'Spewpa (FLI 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Vivillon',
    tcgApiId: 'sm6-8',
    number: '8',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/8.png","large":"https://images.pokemontcg.io/sm6/8_hires.png"}',
    searchName: 'Vivillon (FLI 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Skiddo',
    tcgApiId: 'sm6-9',
    number: '9',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/9.png","large":"https://images.pokemontcg.io/sm6/9_hires.png"}',
    searchName: 'Skiddo (FLI 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Gogoat',
    tcgApiId: 'sm6-10',
    number: '10',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/10.png","large":"https://images.pokemontcg.io/sm6/10_hires.png"}',
    searchName: 'Gogoat (FLI 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Pheromosa',
    tcgApiId: 'sm6-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/11.png","large":"https://images.pokemontcg.io/sm6/11_hires.png"}',
    searchName: 'Pheromosa (FLI 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Alolan Marowak',
    tcgApiId: 'sm6-12',
    number: '12',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/12.png","large":"https://images.pokemontcg.io/sm6/12_hires.png"}',
    searchName: 'Alolan Marowak (FLI 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Heatran',
    tcgApiId: 'sm6-13',
    number: '13',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/13.png","large":"https://images.pokemontcg.io/sm6/13_hires.png"}',
    searchName: 'Heatran (FLI 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Fennekin',
    tcgApiId: 'sm6-14',
    number: '14',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/14.png","large":"https://images.pokemontcg.io/sm6/14_hires.png"}',
    searchName: 'Fennekin (FLI 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Fennekin',
    tcgApiId: 'sm6-15',
    number: '15',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/15.png","large":"https://images.pokemontcg.io/sm6/15_hires.png"}',
    searchName: 'Fennekin (FLI 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Braixen',
    tcgApiId: 'sm6-16',
    number: '16',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/16.png","large":"https://images.pokemontcg.io/sm6/16_hires.png"}',
    searchName: 'Braixen (FLI 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Delphox',
    tcgApiId: 'sm6-17',
    number: '17',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/17.png","large":"https://images.pokemontcg.io/sm6/17_hires.png"}',
    searchName: 'Delphox (FLI 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Litleo',
    tcgApiId: 'sm6-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/18.png","large":"https://images.pokemontcg.io/sm6/18_hires.png"}',
    searchName: 'Litleo (FLI 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Pyroar',
    tcgApiId: 'sm6-19',
    number: '19',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/19.png","large":"https://images.pokemontcg.io/sm6/19_hires.png"}',
    searchName: 'Pyroar (FLI 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Palkia-GX',
    tcgApiId: 'sm6-20',
    number: '20',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/20.png","large":"https://images.pokemontcg.io/sm6/20_hires.png"}',
    searchName: 'Palkia-GX (FLI 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Froakie',
    tcgApiId: 'sm6-21',
    number: '21',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/21.png","large":"https://images.pokemontcg.io/sm6/21_hires.png"}',
    searchName: 'Froakie (FLI 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Froakie',
    tcgApiId: 'sm6-22',
    number: '22',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/22.png","large":"https://images.pokemontcg.io/sm6/22_hires.png"}',
    searchName: 'Froakie (FLI 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Frogadier',
    tcgApiId: 'sm6-23',
    number: '23',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/23.png","large":"https://images.pokemontcg.io/sm6/23_hires.png"}',
    searchName: 'Frogadier (FLI 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Greninja-GX',
    tcgApiId: 'sm6-24',
    number: '24',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/24.png","large":"https://images.pokemontcg.io/sm6/24_hires.png"}',
    searchName: 'Greninja-GX (FLI 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Clauncher',
    tcgApiId: 'sm6-25',
    number: '25',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/25.png","large":"https://images.pokemontcg.io/sm6/25_hires.png"}',
    searchName: 'Clauncher (FLI 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Clawitzer',
    tcgApiId: 'sm6-26',
    number: '26',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/26.png","large":"https://images.pokemontcg.io/sm6/26_hires.png"}',
    searchName: 'Clawitzer (FLI 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Amaura',
    tcgApiId: 'sm6-27',
    number: '27',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/27.png","large":"https://images.pokemontcg.io/sm6/27_hires.png"}',
    searchName: 'Amaura (FLI 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Aurorus',
    tcgApiId: 'sm6-28',
    number: '28',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/28.png","large":"https://images.pokemontcg.io/sm6/28_hires.png"}',
    searchName: 'Aurorus (FLI 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Bergmite',
    tcgApiId: 'sm6-29',
    number: '29',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/29.png","large":"https://images.pokemontcg.io/sm6/29_hires.png"}',
    searchName: 'Bergmite (FLI 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Avalugg',
    tcgApiId: 'sm6-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/30.png","large":"https://images.pokemontcg.io/sm6/30_hires.png"}',
    searchName: 'Avalugg (FLI 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Volcanion ◇',
    tcgApiId: 'sm6-31',
    number: '31',
    rarity: 'Rare Prism Star',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/31.png","large":"https://images.pokemontcg.io/sm6/31_hires.png"}',
    searchName: 'Volcanion ◇ (FLI 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Dewpider',
    tcgApiId: 'sm6-32',
    number: '32',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/32.png","large":"https://images.pokemontcg.io/sm6/32_hires.png"}',
    searchName: 'Dewpider (FLI 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Araquanid',
    tcgApiId: 'sm6-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/33.png","large":"https://images.pokemontcg.io/sm6/33_hires.png"}',
    searchName: 'Araquanid (FLI 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Magnemite',
    tcgApiId: 'sm6-34',
    number: '34',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/34.png","large":"https://images.pokemontcg.io/sm6/34_hires.png"}',
    searchName: 'Magnemite (FLI 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Magneton',
    tcgApiId: 'sm6-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/35.png","large":"https://images.pokemontcg.io/sm6/35_hires.png"}',
    searchName: 'Magneton (FLI 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Magnezone',
    tcgApiId: 'sm6-36',
    number: '36',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/36.png","large":"https://images.pokemontcg.io/sm6/36_hires.png"}',
    searchName: 'Magnezone (FLI 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Helioptile',
    tcgApiId: 'sm6-37',
    number: '37',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/37.png","large":"https://images.pokemontcg.io/sm6/37_hires.png"}',
    searchName: 'Helioptile (FLI 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Heliolisk',
    tcgApiId: 'sm6-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/38.png","large":"https://images.pokemontcg.io/sm6/38_hires.png"}',
    searchName: 'Heliolisk (FLI 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Xurkitree',
    tcgApiId: 'sm6-39',
    number: '39',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/39.png","large":"https://images.pokemontcg.io/sm6/39_hires.png"}',
    searchName: 'Xurkitree (FLI 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Rotom',
    tcgApiId: 'sm6-40',
    number: '40',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/40.png","large":"https://images.pokemontcg.io/sm6/40_hires.png"}',
    searchName: 'Rotom (FLI 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Uxie',
    tcgApiId: 'sm6-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/41.png","large":"https://images.pokemontcg.io/sm6/41_hires.png"}',
    searchName: 'Uxie (FLI 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Mesprit',
    tcgApiId: 'sm6-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/42.png","large":"https://images.pokemontcg.io/sm6/42_hires.png"}',
    searchName: 'Mesprit (FLI 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Azelf',
    tcgApiId: 'sm6-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/43.png","large":"https://images.pokemontcg.io/sm6/43_hires.png"}',
    searchName: 'Azelf (FLI 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Espurr',
    tcgApiId: 'sm6-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/44.png","large":"https://images.pokemontcg.io/sm6/44_hires.png"}',
    searchName: 'Espurr (FLI 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Meowstic',
    tcgApiId: 'sm6-45',
    number: '45',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/45.png","large":"https://images.pokemontcg.io/sm6/45_hires.png"}',
    searchName: 'Meowstic (FLI 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Honedge',
    tcgApiId: 'sm6-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/46.png","large":"https://images.pokemontcg.io/sm6/46_hires.png"}',
    searchName: 'Honedge (FLI 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Honedge',
    tcgApiId: 'sm6-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/47.png","large":"https://images.pokemontcg.io/sm6/47_hires.png"}',
    searchName: 'Honedge (FLI 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Doublade',
    tcgApiId: 'sm6-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/48.png","large":"https://images.pokemontcg.io/sm6/48_hires.png"}',
    searchName: 'Doublade (FLI 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Aegislash',
    tcgApiId: 'sm6-49',
    number: '49',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/49.png","large":"https://images.pokemontcg.io/sm6/49_hires.png"}',
    searchName: 'Aegislash (FLI 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Inkay',
    tcgApiId: 'sm6-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/50.png","large":"https://images.pokemontcg.io/sm6/50_hires.png"}',
    searchName: 'Inkay (FLI 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Malamar',
    tcgApiId: 'sm6-51',
    number: '51',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/51.png","large":"https://images.pokemontcg.io/sm6/51_hires.png"}',
    searchName: 'Malamar (FLI 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Skrelp',
    tcgApiId: 'sm6-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/52.png","large":"https://images.pokemontcg.io/sm6/52_hires.png"}',
    searchName: 'Skrelp (FLI 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Dragalge',
    tcgApiId: 'sm6-53',
    number: '53',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/53.png","large":"https://images.pokemontcg.io/sm6/53_hires.png"}',
    searchName: 'Dragalge (FLI 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Hoopa',
    tcgApiId: 'sm6-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/54.png","large":"https://images.pokemontcg.io/sm6/54_hires.png"}',
    searchName: 'Hoopa (FLI 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Poipole',
    tcgApiId: 'sm6-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/55.png","large":"https://images.pokemontcg.io/sm6/55_hires.png"}',
    searchName: 'Poipole (FLI 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Naganadel-GX',
    tcgApiId: 'sm6-56',
    number: '56',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/56.png","large":"https://images.pokemontcg.io/sm6/56_hires.png"}',
    searchName: 'Naganadel-GX (FLI 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Cubone',
    tcgApiId: 'sm6-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/57.png","large":"https://images.pokemontcg.io/sm6/57_hires.png"}',
    searchName: 'Cubone (FLI 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Torterra',
    tcgApiId: 'sm6-58',
    number: '58',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/58.png","large":"https://images.pokemontcg.io/sm6/58_hires.png"}',
    searchName: 'Torterra (FLI 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Infernape',
    tcgApiId: 'sm6-59',
    number: '59',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/59.png","large":"https://images.pokemontcg.io/sm6/59_hires.png"}',
    searchName: 'Infernape (FLI 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Gible',
    tcgApiId: 'sm6-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/60.png","large":"https://images.pokemontcg.io/sm6/60_hires.png"}',
    searchName: 'Gible (FLI 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Gabite',
    tcgApiId: 'sm6-61',
    number: '61',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/61.png","large":"https://images.pokemontcg.io/sm6/61_hires.png"}',
    searchName: 'Gabite (FLI 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Garchomp',
    tcgApiId: 'sm6-62',
    number: '62',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/62.png","large":"https://images.pokemontcg.io/sm6/62_hires.png"}',
    searchName: 'Garchomp (FLI 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Croagunk',
    tcgApiId: 'sm6-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/63.png","large":"https://images.pokemontcg.io/sm6/63_hires.png"}',
    searchName: 'Croagunk (FLI 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Toxicroak',
    tcgApiId: 'sm6-64',
    number: '64',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/64.png","large":"https://images.pokemontcg.io/sm6/64_hires.png"}',
    searchName: 'Toxicroak (FLI 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Pancham',
    tcgApiId: 'sm6-65',
    number: '65',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/65.png","large":"https://images.pokemontcg.io/sm6/65_hires.png"}',
    searchName: 'Pancham (FLI 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Binacle',
    tcgApiId: 'sm6-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/66.png","large":"https://images.pokemontcg.io/sm6/66_hires.png"}',
    searchName: 'Binacle (FLI 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Barbaracle',
    tcgApiId: 'sm6-67',
    number: '67',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/67.png","large":"https://images.pokemontcg.io/sm6/67_hires.png"}',
    searchName: 'Barbaracle (FLI 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Tyrunt',
    tcgApiId: 'sm6-68',
    number: '68',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/68.png","large":"https://images.pokemontcg.io/sm6/68_hires.png"}',
    searchName: 'Tyrunt (FLI 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Tyrantrum',
    tcgApiId: 'sm6-69',
    number: '69',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/69.png","large":"https://images.pokemontcg.io/sm6/69_hires.png"}',
    searchName: 'Tyrantrum (FLI 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Hawlucha',
    tcgApiId: 'sm6-70',
    number: '70',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/70.png","large":"https://images.pokemontcg.io/sm6/70_hires.png"}',
    searchName: 'Hawlucha (FLI 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Zygarde',
    tcgApiId: 'sm6-71',
    number: '71',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/71.png","large":"https://images.pokemontcg.io/sm6/71_hires.png"}',
    searchName: 'Zygarde (FLI 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Zygarde',
    tcgApiId: 'sm6-72',
    number: '72',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/72.png","large":"https://images.pokemontcg.io/sm6/72_hires.png"}',
    searchName: 'Zygarde (FLI 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Zygarde-GX',
    tcgApiId: 'sm6-73',
    number: '73',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/73.png","large":"https://images.pokemontcg.io/sm6/73_hires.png"}',
    searchName: 'Zygarde-GX (FLI 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Diancie ◇',
    tcgApiId: 'sm6-74',
    number: '74',
    rarity: 'Rare Prism Star',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/74.png","large":"https://images.pokemontcg.io/sm6/74_hires.png"}',
    searchName: 'Diancie ◇ (FLI 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Rockruff',
    tcgApiId: 'sm6-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/75.png","large":"https://images.pokemontcg.io/sm6/75_hires.png"}',
    searchName: 'Rockruff (FLI 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Lycanroc',
    tcgApiId: 'sm6-76',
    number: '76',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/76.png","large":"https://images.pokemontcg.io/sm6/76_hires.png"}',
    searchName: 'Lycanroc (FLI 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Buzzwole',
    tcgApiId: 'sm6-77',
    number: '77',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/77.png","large":"https://images.pokemontcg.io/sm6/77_hires.png"}',
    searchName: 'Buzzwole (FLI 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Pangoro',
    tcgApiId: 'sm6-78',
    number: '78',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/78.png","large":"https://images.pokemontcg.io/sm6/78_hires.png"}',
    searchName: 'Pangoro (FLI 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Yveltal-GX',
    tcgApiId: 'sm6-79',
    number: '79',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/79.png","large":"https://images.pokemontcg.io/sm6/79_hires.png"}',
    searchName: 'Yveltal-GX (FLI 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Guzzlord',
    tcgApiId: 'sm6-80',
    number: '80',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/80.png","large":"https://images.pokemontcg.io/sm6/80_hires.png"}',
    searchName: 'Guzzlord (FLI 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Empoleon',
    tcgApiId: 'sm6-81',
    number: '81',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/81.png","large":"https://images.pokemontcg.io/sm6/81_hires.png"}',
    searchName: 'Empoleon (FLI 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Dialga-GX',
    tcgApiId: 'sm6-82',
    number: '82',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/82.png","large":"https://images.pokemontcg.io/sm6/82_hires.png"}',
    searchName: 'Dialga-GX (FLI 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Flabébé',
    tcgApiId: 'sm6-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/83.png","large":"https://images.pokemontcg.io/sm6/83_hires.png"}',
    searchName: 'Flabébé (FLI 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Flabébé',
    tcgApiId: 'sm6-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/84.png","large":"https://images.pokemontcg.io/sm6/84_hires.png"}',
    searchName: 'Flabébé (FLI 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Floette',
    tcgApiId: 'sm6-85',
    number: '85',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/85.png","large":"https://images.pokemontcg.io/sm6/85_hires.png"}',
    searchName: 'Floette (FLI 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Florges',
    tcgApiId: 'sm6-86',
    number: '86',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/86.png","large":"https://images.pokemontcg.io/sm6/86_hires.png"}',
    searchName: 'Florges (FLI 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Sylveon',
    tcgApiId: 'sm6-87',
    number: '87',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/87.png","large":"https://images.pokemontcg.io/sm6/87_hires.png"}',
    searchName: 'Sylveon (FLI 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Dedenne',
    tcgApiId: 'sm6-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/88.png","large":"https://images.pokemontcg.io/sm6/88_hires.png"}',
    searchName: 'Dedenne (FLI 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Klefki',
    tcgApiId: 'sm6-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/89.png","large":"https://images.pokemontcg.io/sm6/89_hires.png"}',
    searchName: 'Klefki (FLI 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Xerneas-GX',
    tcgApiId: 'sm6-90',
    number: '90',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/90.png","large":"https://images.pokemontcg.io/sm6/90_hires.png"}',
    searchName: 'Xerneas-GX (FLI 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Goomy',
    tcgApiId: 'sm6-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/91.png","large":"https://images.pokemontcg.io/sm6/91_hires.png"}',
    searchName: 'Goomy (FLI 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Goomy',
    tcgApiId: 'sm6-92',
    number: '92',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/92.png","large":"https://images.pokemontcg.io/sm6/92_hires.png"}',
    searchName: 'Goomy (FLI 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Sliggoo',
    tcgApiId: 'sm6-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/93.png","large":"https://images.pokemontcg.io/sm6/93_hires.png"}',
    searchName: 'Sliggoo (FLI 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Goodra',
    tcgApiId: 'sm6-94',
    number: '94',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/94.png","large":"https://images.pokemontcg.io/sm6/94_hires.png"}',
    searchName: 'Goodra (FLI 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Ultra Necrozma-GX',
    tcgApiId: 'sm6-95',
    number: '95',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/95.png","large":"https://images.pokemontcg.io/sm6/95_hires.png"}',
    searchName: 'Ultra Necrozma-GX (FLI 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Arceus ◇',
    tcgApiId: 'sm6-96',
    number: '96',
    rarity: 'Rare Prism Star',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/96.png","large":"https://images.pokemontcg.io/sm6/96_hires.png"}',
    searchName: 'Arceus ◇ (FLI 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Bunnelby',
    tcgApiId: 'sm6-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/97.png","large":"https://images.pokemontcg.io/sm6/97_hires.png"}',
    searchName: 'Bunnelby (FLI 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Diggersby',
    tcgApiId: 'sm6-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/98.png","large":"https://images.pokemontcg.io/sm6/98_hires.png"}',
    searchName: 'Diggersby (FLI 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Furfrou',
    tcgApiId: 'sm6-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/99.png","large":"https://images.pokemontcg.io/sm6/99_hires.png"}',
    searchName: 'Furfrou (FLI 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Noibat',
    tcgApiId: 'sm6-100',
    number: '100',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/100.png","large":"https://images.pokemontcg.io/sm6/100_hires.png"}',
    searchName: 'Noibat (FLI 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Noivern',
    tcgApiId: 'sm6-101',
    number: '101',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/101.png","large":"https://images.pokemontcg.io/sm6/101_hires.png"}',
    searchName: 'Noivern (FLI 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Beast Ring',
    tcgApiId: 'sm6-102',
    number: '102',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/102.png","large":"https://images.pokemontcg.io/sm6/102_hires.png"}',
    searchName: 'Beast Ring (FLI 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Beast Ring',
    tcgApiId: 'sm6-102a',
    number: '102a',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/102a.png","large":"https://images.pokemontcg.io/sm6/102a_hires.png"}',
    searchName: 'Beast Ring (FLI 102a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Bonnie',
    tcgApiId: 'sm6-103',
    number: '103',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/103.png","large":"https://images.pokemontcg.io/sm6/103_hires.png"}',
    searchName: 'Bonnie (FLI 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Crasher Wake',
    tcgApiId: 'sm6-104',
    number: '104',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/104.png","large":"https://images.pokemontcg.io/sm6/104_hires.png"}',
    searchName: 'Crasher Wake (FLI 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Diantha',
    tcgApiId: 'sm6-105',
    number: '105',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/105.png","large":"https://images.pokemontcg.io/sm6/105_hires.png"}',
    searchName: 'Diantha (FLI 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Eneporter',
    tcgApiId: 'sm6-106',
    number: '106',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/106.png","large":"https://images.pokemontcg.io/sm6/106_hires.png"}',
    searchName: 'Eneporter (FLI 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Fossil Excavation Map',
    tcgApiId: 'sm6-107',
    number: '107',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/107.png","large":"https://images.pokemontcg.io/sm6/107_hires.png"}',
    searchName: 'Fossil Excavation Map (FLI 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Judge',
    tcgApiId: 'sm6-108',
    number: '108',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/108.png","large":"https://images.pokemontcg.io/sm6/108_hires.png"}',
    searchName: 'Judge (FLI 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Lady',
    tcgApiId: 'sm6-109',
    number: '109',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/109.png","large":"https://images.pokemontcg.io/sm6/109_hires.png"}',
    searchName: 'Lady (FLI 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Lysandre ◇',
    tcgApiId: 'sm6-110',
    number: '110',
    rarity: 'Rare Prism Star',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/110.png","large":"https://images.pokemontcg.io/sm6/110_hires.png"}',
    searchName: 'Lysandre ◇ (FLI 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Lysandre Labs',
    tcgApiId: 'sm6-111',
    number: '111',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/111.png","large":"https://images.pokemontcg.io/sm6/111_hires.png"}',
    searchName: 'Lysandre Labs (FLI 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Metal Frying Pan',
    tcgApiId: 'sm6-112',
    number: '112',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/112.png","large":"https://images.pokemontcg.io/sm6/112_hires.png"}',
    searchName: 'Metal Frying Pan (FLI 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Metal Frying Pan',
    tcgApiId: 'sm6-112a',
    number: '112a',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/112a.png","large":"https://images.pokemontcg.io/sm6/112a_hires.png"}',
    searchName: 'Metal Frying Pan (FLI 112a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Mysterious Treasure',
    tcgApiId: 'sm6-113',
    number: '113',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/113.png","large":"https://images.pokemontcg.io/sm6/113_hires.png"}',
    searchName: 'Mysterious Treasure (FLI 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Mysterious Treasure',
    tcgApiId: 'sm6-113a',
    number: '113a',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/113a.png","large":"https://images.pokemontcg.io/sm6/113a_hires.png"}',
    searchName: 'Mysterious Treasure (FLI 113a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Ultra Recon Squad',
    tcgApiId: 'sm6-114',
    number: '114',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/114.png","large":"https://images.pokemontcg.io/sm6/114_hires.png"}',
    searchName: 'Ultra Recon Squad (FLI 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Ultra Space',
    tcgApiId: 'sm6-115',
    number: '115',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/115.png","large":"https://images.pokemontcg.io/sm6/115_hires.png"}',
    searchName: 'Ultra Space (FLI 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Unidentified Fossil',
    tcgApiId: 'sm6-116',
    number: '116',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/116.png","large":"https://images.pokemontcg.io/sm6/116_hires.png"}',
    searchName: 'Unidentified Fossil (FLI 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Beast Energy ◇',
    tcgApiId: 'sm6-117',
    number: '117',
    rarity: 'Rare Prism Star',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/117.png","large":"https://images.pokemontcg.io/sm6/117_hires.png"}',
    searchName: 'Beast Energy ◇ (FLI 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Unit Energy FightingDarknessFairy',
    tcgApiId: 'sm6-118',
    number: '118',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/118.png","large":"https://images.pokemontcg.io/sm6/118_hires.png"}',
    searchName: 'Unit Energy FightingDarknessFairy (FLI 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Palkia-GX',
    tcgApiId: 'sm6-119',
    number: '119',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/119.png","large":"https://images.pokemontcg.io/sm6/119_hires.png"}',
    searchName: 'Palkia-GX (FLI 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Greninja-GX',
    tcgApiId: 'sm6-120',
    number: '120',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/120.png","large":"https://images.pokemontcg.io/sm6/120_hires.png"}',
    searchName: 'Greninja-GX (FLI 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Naganadel-GX',
    tcgApiId: 'sm6-121',
    number: '121',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/121.png","large":"https://images.pokemontcg.io/sm6/121_hires.png"}',
    searchName: 'Naganadel-GX (FLI 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Lucario-GX',
    tcgApiId: 'sm6-122',
    number: '122',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/122.png","large":"https://images.pokemontcg.io/sm6/122_hires.png"}',
    searchName: 'Lucario-GX (FLI 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Zygarde-GX',
    tcgApiId: 'sm6-123',
    number: '123',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/123.png","large":"https://images.pokemontcg.io/sm6/123_hires.png"}',
    searchName: 'Zygarde-GX (FLI 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Yveltal-GX',
    tcgApiId: 'sm6-124',
    number: '124',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/124.png","large":"https://images.pokemontcg.io/sm6/124_hires.png"}',
    searchName: 'Yveltal-GX (FLI 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Dialga-GX',
    tcgApiId: 'sm6-125',
    number: '125',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/125.png","large":"https://images.pokemontcg.io/sm6/125_hires.png"}',
    searchName: 'Dialga-GX (FLI 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Xerneas-GX',
    tcgApiId: 'sm6-126',
    number: '126',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/126.png","large":"https://images.pokemontcg.io/sm6/126_hires.png"}',
    searchName: 'Xerneas-GX (FLI 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Ultra Necrozma-GX',
    tcgApiId: 'sm6-127',
    number: '127',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/127.png","large":"https://images.pokemontcg.io/sm6/127_hires.png"}',
    searchName: 'Ultra Necrozma-GX (FLI 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Bonnie',
    tcgApiId: 'sm6-128',
    number: '128',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/128.png","large":"https://images.pokemontcg.io/sm6/128_hires.png"}',
    searchName: 'Bonnie (FLI 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Crasher Wake',
    tcgApiId: 'sm6-129',
    number: '129',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/129.png","large":"https://images.pokemontcg.io/sm6/129_hires.png"}',
    searchName: 'Crasher Wake (FLI 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Diantha',
    tcgApiId: 'sm6-130',
    number: '130',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/130.png","large":"https://images.pokemontcg.io/sm6/130_hires.png"}',
    searchName: 'Diantha (FLI 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Ultra Recon Squad',
    tcgApiId: 'sm6-131',
    number: '131',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/131.png","large":"https://images.pokemontcg.io/sm6/131_hires.png"}',
    searchName: 'Ultra Recon Squad (FLI 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Palkia-GX',
    tcgApiId: 'sm6-132',
    number: '132',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/132.png","large":"https://images.pokemontcg.io/sm6/132_hires.png"}',
    searchName: 'Palkia-GX (FLI 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Greninja-GX',
    tcgApiId: 'sm6-133',
    number: '133',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/133.png","large":"https://images.pokemontcg.io/sm6/133_hires.png"}',
    searchName: 'Greninja-GX (FLI 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Naganadel-GX',
    tcgApiId: 'sm6-134',
    number: '134',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/134.png","large":"https://images.pokemontcg.io/sm6/134_hires.png"}',
    searchName: 'Naganadel-GX (FLI 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Lucario-GX',
    tcgApiId: 'sm6-135',
    number: '135',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/135.png","large":"https://images.pokemontcg.io/sm6/135_hires.png"}',
    searchName: 'Lucario-GX (FLI 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Zygarde-GX',
    tcgApiId: 'sm6-136',
    number: '136',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/136.png","large":"https://images.pokemontcg.io/sm6/136_hires.png"}',
    searchName: 'Zygarde-GX (FLI 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Yveltal-GX',
    tcgApiId: 'sm6-137',
    number: '137',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/137.png","large":"https://images.pokemontcg.io/sm6/137_hires.png"}',
    searchName: 'Yveltal-GX (FLI 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Dialga-GX',
    tcgApiId: 'sm6-138',
    number: '138',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/138.png","large":"https://images.pokemontcg.io/sm6/138_hires.png"}',
    searchName: 'Dialga-GX (FLI 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Xerneas-GX',
    tcgApiId: 'sm6-139',
    number: '139',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/139.png","large":"https://images.pokemontcg.io/sm6/139_hires.png"}',
    searchName: 'Xerneas-GX (FLI 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Ultra Necrozma-GX',
    tcgApiId: 'sm6-140',
    number: '140',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/140.png","large":"https://images.pokemontcg.io/sm6/140_hires.png"}',
    searchName: 'Ultra Necrozma-GX (FLI 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Beast Ring',
    tcgApiId: 'sm6-141',
    number: '141',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/141.png","large":"https://images.pokemontcg.io/sm6/141_hires.png"}',
    searchName: 'Beast Ring (FLI 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Eneporter',
    tcgApiId: 'sm6-142',
    number: '142',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/142.png","large":"https://images.pokemontcg.io/sm6/142_hires.png"}',
    searchName: 'Eneporter (FLI 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Energy Recycler',
    tcgApiId: 'sm6-143',
    number: '143',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/143.png","large":"https://images.pokemontcg.io/sm6/143_hires.png"}',
    searchName: 'Energy Recycler (FLI 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Metal Frying Pan',
    tcgApiId: 'sm6-144',
    number: '144',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/144.png","large":"https://images.pokemontcg.io/sm6/144_hires.png"}',
    searchName: 'Metal Frying Pan (FLI 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Mysterious Treasure',
    tcgApiId: 'sm6-145',
    number: '145',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/145.png","large":"https://images.pokemontcg.io/sm6/145_hires.png"}',
    searchName: 'Mysterious Treasure (FLI 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm6',
    name: 'Unit Energy FightingDarknessFairy',
    tcgApiId: 'sm6-146',
    number: '146',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm6/146.png","large":"https://images.pokemontcg.io/sm6/146_hires.png"}',
    searchName: 'Unit Energy FightingDarknessFairy (FLI 146)',
  },
];
