export const cardSeedSm75 = [
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Charmander',
    tcgApiId: 'sm75-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/1.png","large":"https://images.pokemontcg.io/sm75/1_hires.png"}',
    searchName: 'Charmander (DRM 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Charmeleon',
    tcgApiId: 'sm75-2',
    number: '2',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/2.png","large":"https://images.pokemontcg.io/sm75/2_hires.png"}',
    searchName: 'Charmeleon (DRM 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Charizard',
    tcgApiId: 'sm75-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/3.png","large":"https://images.pokemontcg.io/sm75/3_hires.png"}',
    searchName: 'Charizard (DRM 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Torchic',
    tcgApiId: 'sm75-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/4.png","large":"https://images.pokemontcg.io/sm75/4_hires.png"}',
    searchName: 'Torchic (DRM 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Combusken',
    tcgApiId: 'sm75-5',
    number: '5',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/5.png","large":"https://images.pokemontcg.io/sm75/5_hires.png"}',
    searchName: 'Combusken (DRM 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Blaziken',
    tcgApiId: 'sm75-6',
    number: '6',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/6.png","large":"https://images.pokemontcg.io/sm75/6_hires.png"}',
    searchName: 'Blaziken (DRM 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Victini ◇',
    tcgApiId: 'sm75-7',
    number: '7',
    rarity: 'Rare Prism Star',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/7.png","large":"https://images.pokemontcg.io/sm75/7_hires.png"}',
    searchName: 'Victini ◇ (DRM 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Darumaka',
    tcgApiId: 'sm75-8',
    number: '8',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/8.png","large":"https://images.pokemontcg.io/sm75/8_hires.png"}',
    searchName: 'Darumaka (DRM 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Darmanitan',
    tcgApiId: 'sm75-9',
    number: '9',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/9.png","large":"https://images.pokemontcg.io/sm75/9_hires.png"}',
    searchName: 'Darmanitan (DRM 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Heatmor',
    tcgApiId: 'sm75-10',
    number: '10',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/10.png","large":"https://images.pokemontcg.io/sm75/10_hires.png"}',
    searchName: 'Heatmor (DRM 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Reshiram-GX',
    tcgApiId: 'sm75-11',
    number: '11',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/11.png","large":"https://images.pokemontcg.io/sm75/11_hires.png"}',
    searchName: 'Reshiram-GX (DRM 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Litten',
    tcgApiId: 'sm75-12',
    number: '12',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/12.png","large":"https://images.pokemontcg.io/sm75/12_hires.png"}',
    searchName: 'Litten (DRM 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Salandit',
    tcgApiId: 'sm75-13',
    number: '13',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/13.png","large":"https://images.pokemontcg.io/sm75/13_hires.png"}',
    searchName: 'Salandit (DRM 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Salazzle',
    tcgApiId: 'sm75-14',
    number: '14',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/14.png","large":"https://images.pokemontcg.io/sm75/14_hires.png"}',
    searchName: 'Salazzle (DRM 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Horsea',
    tcgApiId: 'sm75-15',
    number: '15',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/15.png","large":"https://images.pokemontcg.io/sm75/15_hires.png"}',
    searchName: 'Horsea (DRM 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Horsea',
    tcgApiId: 'sm75-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/16.png","large":"https://images.pokemontcg.io/sm75/16_hires.png"}',
    searchName: 'Horsea (DRM 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Seadra',
    tcgApiId: 'sm75-17',
    number: '17',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/17.png","large":"https://images.pokemontcg.io/sm75/17_hires.png"}',
    searchName: 'Seadra (DRM 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Kingdra-GX',
    tcgApiId: 'sm75-18',
    number: '18',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/18.png","large":"https://images.pokemontcg.io/sm75/18_hires.png"}',
    searchName: 'Kingdra-GX (DRM 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Magikarp',
    tcgApiId: 'sm75-19',
    number: '19',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/19.png","large":"https://images.pokemontcg.io/sm75/19_hires.png"}',
    searchName: 'Magikarp (DRM 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Gyarados',
    tcgApiId: 'sm75-20',
    number: '20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/20.png","large":"https://images.pokemontcg.io/sm75/20_hires.png"}',
    searchName: 'Gyarados (DRM 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Lapras',
    tcgApiId: 'sm75-21',
    number: '21',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/21.png","large":"https://images.pokemontcg.io/sm75/21_hires.png"}',
    searchName: 'Lapras (DRM 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Totodile',
    tcgApiId: 'sm75-22',
    number: '22',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/22.png","large":"https://images.pokemontcg.io/sm75/22_hires.png"}',
    searchName: 'Totodile (DRM 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Croconaw',
    tcgApiId: 'sm75-23',
    number: '23',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/23.png","large":"https://images.pokemontcg.io/sm75/23_hires.png"}',
    searchName: 'Croconaw (DRM 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Feraligatr',
    tcgApiId: 'sm75-24',
    number: '24',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/24.png","large":"https://images.pokemontcg.io/sm75/24_hires.png"}',
    searchName: 'Feraligatr (DRM 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Wooper',
    tcgApiId: 'sm75-25',
    number: '25',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/25.png","large":"https://images.pokemontcg.io/sm75/25_hires.png"}',
    searchName: 'Wooper (DRM 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Quagsire',
    tcgApiId: 'sm75-26',
    number: '26',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/26.png","large":"https://images.pokemontcg.io/sm75/26_hires.png"}',
    searchName: 'Quagsire (DRM 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Corsola',
    tcgApiId: 'sm75-27',
    number: '27',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/27.png","large":"https://images.pokemontcg.io/sm75/27_hires.png"}',
    searchName: 'Corsola (DRM 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Feebas',
    tcgApiId: 'sm75-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/28.png","large":"https://images.pokemontcg.io/sm75/28_hires.png"}',
    searchName: 'Feebas (DRM 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Milotic',
    tcgApiId: 'sm75-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/29.png","large":"https://images.pokemontcg.io/sm75/29_hires.png"}',
    searchName: 'Milotic (DRM 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Phione',
    tcgApiId: 'sm75-30',
    number: '30',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/30.png","large":"https://images.pokemontcg.io/sm75/30_hires.png"}',
    searchName: 'Phione (DRM 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Wishiwashi',
    tcgApiId: 'sm75-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/31.png","large":"https://images.pokemontcg.io/sm75/31_hires.png"}',
    searchName: 'Wishiwashi (DRM 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Trapinch',
    tcgApiId: 'sm75-32',
    number: '32',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/32.png","large":"https://images.pokemontcg.io/sm75/32_hires.png"}',
    searchName: 'Trapinch (DRM 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Hydreigon',
    tcgApiId: 'sm75-33',
    number: '33',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/33.png","large":"https://images.pokemontcg.io/sm75/33_hires.png"}',
    searchName: 'Hydreigon (DRM 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Dratini',
    tcgApiId: 'sm75-34',
    number: '34',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/34.png","large":"https://images.pokemontcg.io/sm75/34_hires.png"}',
    searchName: 'Dratini (DRM 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Dratini',
    tcgApiId: 'sm75-35',
    number: '35',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/35.png","large":"https://images.pokemontcg.io/sm75/35_hires.png"}',
    searchName: 'Dratini (DRM 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Dragonair',
    tcgApiId: 'sm75-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/36.png","large":"https://images.pokemontcg.io/sm75/36_hires.png"}',
    searchName: 'Dragonair (DRM 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Dragonite-GX',
    tcgApiId: 'sm75-37',
    number: '37',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/37.png","large":"https://images.pokemontcg.io/sm75/37_hires.png"}',
    searchName: 'Dragonite-GX (DRM 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Vibrava',
    tcgApiId: 'sm75-38',
    number: '38',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/38.png","large":"https://images.pokemontcg.io/sm75/38_hires.png"}',
    searchName: 'Vibrava (DRM 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Flygon',
    tcgApiId: 'sm75-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/39.png","large":"https://images.pokemontcg.io/sm75/39_hires.png"}',
    searchName: 'Flygon (DRM 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Altaria',
    tcgApiId: 'sm75-40',
    number: '40',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/40.png","large":"https://images.pokemontcg.io/sm75/40_hires.png"}',
    searchName: 'Altaria (DRM 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Altaria',
    tcgApiId: 'sm75-40a',
    number: '40a',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/40a.png","large":"https://images.pokemontcg.io/sm75/40a_hires.png"}',
    searchName: 'Altaria (DRM 40a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Altaria-GX',
    tcgApiId: 'sm75-41',
    number: '41',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/41.png","large":"https://images.pokemontcg.io/sm75/41_hires.png"}',
    searchName: 'Altaria-GX (DRM 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Bagon',
    tcgApiId: 'sm75-42',
    number: '42',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/42.png","large":"https://images.pokemontcg.io/sm75/42_hires.png"}',
    searchName: 'Bagon (DRM 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Shelgon',
    tcgApiId: 'sm75-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/43.png","large":"https://images.pokemontcg.io/sm75/43_hires.png"}',
    searchName: 'Shelgon (DRM 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Salamence-GX',
    tcgApiId: 'sm75-44',
    number: '44',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/44.png","large":"https://images.pokemontcg.io/sm75/44_hires.png"}',
    searchName: 'Salamence-GX (DRM 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Druddigon',
    tcgApiId: 'sm75-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/45.png","large":"https://images.pokemontcg.io/sm75/45_hires.png"}',
    searchName: 'Druddigon (DRM 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Zekrom',
    tcgApiId: 'sm75-46',
    number: '46',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/46.png","large":"https://images.pokemontcg.io/sm75/46_hires.png"}',
    searchName: 'Zekrom (DRM 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Kyurem',
    tcgApiId: 'sm75-47',
    number: '47',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/47.png","large":"https://images.pokemontcg.io/sm75/47_hires.png"}',
    searchName: 'Kyurem (DRM 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'White Kyurem-GX',
    tcgApiId: 'sm75-48',
    number: '48',
    rarity: 'Rare Holo GX',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/48.png","large":"https://images.pokemontcg.io/sm75/48_hires.png"}',
    searchName: 'White Kyurem-GX (DRM 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Zygarde',
    tcgApiId: 'sm75-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/49.png","large":"https://images.pokemontcg.io/sm75/49_hires.png"}',
    searchName: 'Zygarde (DRM 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Turtonator',
    tcgApiId: 'sm75-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/50.png","large":"https://images.pokemontcg.io/sm75/50_hires.png"}',
    searchName: 'Turtonator (DRM 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Drampa',
    tcgApiId: 'sm75-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/51.png","large":"https://images.pokemontcg.io/sm75/51_hires.png"}',
    searchName: 'Drampa (DRM 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Jangmo-o',
    tcgApiId: 'sm75-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/52.png","large":"https://images.pokemontcg.io/sm75/52_hires.png"}',
    searchName: 'Jangmo-o (DRM 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Hakamo-o',
    tcgApiId: 'sm75-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/53.png","large":"https://images.pokemontcg.io/sm75/53_hires.png"}',
    searchName: 'Hakamo-o (DRM 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Kommo-o',
    tcgApiId: 'sm75-54',
    number: '54',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/54.png","large":"https://images.pokemontcg.io/sm75/54_hires.png"}',
    searchName: 'Kommo-o (DRM 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Kangaskhan',
    tcgApiId: 'sm75-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/55.png","large":"https://images.pokemontcg.io/sm75/55_hires.png"}',
    searchName: 'Kangaskhan (DRM 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Swablu',
    tcgApiId: 'sm75-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/56.png","large":"https://images.pokemontcg.io/sm75/56_hires.png"}',
    searchName: 'Swablu (DRM 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Swablu',
    tcgApiId: 'sm75-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/57.png","large":"https://images.pokemontcg.io/sm75/57_hires.png"}',
    searchName: 'Swablu (DRM 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: "Blaine's Last Stand",
    tcgApiId: 'sm75-58',
    number: '58',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/58.png","large":"https://images.pokemontcg.io/sm75/58_hires.png"}',
    searchName: "Blaine's Last Stand (DRM 58)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Dragon Talon',
    tcgApiId: 'sm75-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/59.png","large":"https://images.pokemontcg.io/sm75/59_hires.png"}',
    searchName: 'Dragon Talon (DRM 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Fiery Flint',
    tcgApiId: 'sm75-60',
    number: '60',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/60.png","large":"https://images.pokemontcg.io/sm75/60_hires.png"}',
    searchName: 'Fiery Flint (DRM 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Fiery Flint',
    tcgApiId: 'sm75-60a',
    number: '60a',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/60a.png","large":"https://images.pokemontcg.io/sm75/60a_hires.png"}',
    searchName: 'Fiery Flint (DRM 60a)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Lance ◇',
    tcgApiId: 'sm75-61',
    number: '61',
    rarity: 'Rare Prism Star',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/61.png","large":"https://images.pokemontcg.io/sm75/61_hires.png"}',
    searchName: 'Lance ◇ (DRM 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Switch Raft',
    tcgApiId: 'sm75-62',
    number: '62',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/62.png","large":"https://images.pokemontcg.io/sm75/62_hires.png"}',
    searchName: 'Switch Raft (DRM 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Wela Volcano Park',
    tcgApiId: 'sm75-63',
    number: '63',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/63.png","large":"https://images.pokemontcg.io/sm75/63_hires.png"}',
    searchName: 'Wela Volcano Park (DRM 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Zinnia',
    tcgApiId: 'sm75-64',
    number: '64',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/64.png","large":"https://images.pokemontcg.io/sm75/64_hires.png"}',
    searchName: 'Zinnia (DRM 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Reshiram-GX',
    tcgApiId: 'sm75-65',
    number: '65',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/65.png","large":"https://images.pokemontcg.io/sm75/65_hires.png"}',
    searchName: 'Reshiram-GX (DRM 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Kingdra-GX',
    tcgApiId: 'sm75-66',
    number: '66',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/66.png","large":"https://images.pokemontcg.io/sm75/66_hires.png"}',
    searchName: 'Kingdra-GX (DRM 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Dragonite-GX',
    tcgApiId: 'sm75-67',
    number: '67',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/67.png","large":"https://images.pokemontcg.io/sm75/67_hires.png"}',
    searchName: 'Dragonite-GX (DRM 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Altaria-GX',
    tcgApiId: 'sm75-68',
    number: '68',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/68.png","large":"https://images.pokemontcg.io/sm75/68_hires.png"}',
    searchName: 'Altaria-GX (DRM 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: "Blaine's Last Stand",
    tcgApiId: 'sm75-69',
    number: '69',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/69.png","large":"https://images.pokemontcg.io/sm75/69_hires.png"}',
    searchName: "Blaine's Last Stand (DRM 69)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Zinnia',
    tcgApiId: 'sm75-70',
    number: '70',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/70.png","large":"https://images.pokemontcg.io/sm75/70_hires.png"}',
    searchName: 'Zinnia (DRM 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Reshiram-GX',
    tcgApiId: 'sm75-71',
    number: '71',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/71.png","large":"https://images.pokemontcg.io/sm75/71_hires.png"}',
    searchName: 'Reshiram-GX (DRM 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Altaria-GX',
    tcgApiId: 'sm75-72',
    number: '72',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/72.png","large":"https://images.pokemontcg.io/sm75/72_hires.png"}',
    searchName: 'Altaria-GX (DRM 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Salamence-GX',
    tcgApiId: 'sm75-73',
    number: '73',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/73.png","large":"https://images.pokemontcg.io/sm75/73_hires.png"}',
    searchName: 'Salamence-GX (DRM 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'White Kyurem-GX',
    tcgApiId: 'sm75-74',
    number: '74',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/74.png","large":"https://images.pokemontcg.io/sm75/74_hires.png"}',
    searchName: 'White Kyurem-GX (DRM 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Dragon Talon',
    tcgApiId: 'sm75-75',
    number: '75',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/75.png","large":"https://images.pokemontcg.io/sm75/75_hires.png"}',
    searchName: 'Dragon Talon (DRM 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Fiery Flint',
    tcgApiId: 'sm75-76',
    number: '76',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/76.png","large":"https://images.pokemontcg.io/sm75/76_hires.png"}',
    searchName: 'Fiery Flint (DRM 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Switch Raft',
    tcgApiId: 'sm75-77',
    number: '77',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/77.png","large":"https://images.pokemontcg.io/sm75/77_hires.png"}',
    searchName: 'Switch Raft (DRM 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sm75',
    name: 'Ultra Necrozma-GX',
    tcgApiId: 'sm75-78',
    number: '78',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/sm75/78.png","large":"https://images.pokemontcg.io/sm75/78_hires.png"}',
    searchName: 'Ultra Necrozma-GX (DRM 78)',
  },
];
