export const cardSeedSv1 = [
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pineco',
    tcgApiId: 'sv1-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/1.png","large":"https://images.pokemontcg.io/sv1/1_hires.png"}',
    searchName: 'Pineco (SVI 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Heracross',
    tcgApiId: 'sv1-2',
    number: '2',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/2.png","large":"https://images.pokemontcg.io/sv1/2_hires.png"}',
    searchName: 'Heracross (SVI 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Shroomish',
    tcgApiId: 'sv1-3',
    number: '3',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/3.png","large":"https://images.pokemontcg.io/sv1/3_hires.png"}',
    searchName: 'Shroomish (SVI 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Breloom',
    tcgApiId: 'sv1-4',
    number: '4',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/4.png","large":"https://images.pokemontcg.io/sv1/4_hires.png"}',
    searchName: 'Breloom (SVI 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Cacnea',
    tcgApiId: 'sv1-5',
    number: '5',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/5.png","large":"https://images.pokemontcg.io/sv1/5_hires.png"}',
    searchName: 'Cacnea (SVI 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Cacturne',
    tcgApiId: 'sv1-6',
    number: '6',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/6.png","large":"https://images.pokemontcg.io/sv1/6_hires.png"}',
    searchName: 'Cacturne (SVI 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Tropius',
    tcgApiId: 'sv1-7',
    number: '7',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/7.png","large":"https://images.pokemontcg.io/sv1/7_hires.png"}',
    searchName: 'Tropius (SVI 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Scatterbug',
    tcgApiId: 'sv1-8',
    number: '8',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/8.png","large":"https://images.pokemontcg.io/sv1/8_hires.png"}',
    searchName: 'Scatterbug (SVI 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Spewpa',
    tcgApiId: 'sv1-9',
    number: '9',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/9.png","large":"https://images.pokemontcg.io/sv1/9_hires.png"}',
    searchName: 'Spewpa (SVI 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Vivillon',
    tcgApiId: 'sv1-10',
    number: '10',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/10.png","large":"https://images.pokemontcg.io/sv1/10_hires.png"}',
    searchName: 'Vivillon (SVI 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Skiddo',
    tcgApiId: 'sv1-11',
    number: '11',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/11.png","large":"https://images.pokemontcg.io/sv1/11_hires.png"}',
    searchName: 'Skiddo (SVI 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Gogoat',
    tcgApiId: 'sv1-12',
    number: '12',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/12.png","large":"https://images.pokemontcg.io/sv1/12_hires.png"}',
    searchName: 'Gogoat (SVI 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Sprigatito',
    tcgApiId: 'sv1-13',
    number: '13',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/13.png","large":"https://images.pokemontcg.io/sv1/13_hires.png"}',
    searchName: 'Sprigatito (SVI 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Floragato',
    tcgApiId: 'sv1-14',
    number: '14',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/14.png","large":"https://images.pokemontcg.io/sv1/14_hires.png"}',
    searchName: 'Floragato (SVI 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Meowscarada',
    tcgApiId: 'sv1-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/15.png","large":"https://images.pokemontcg.io/sv1/15_hires.png"}',
    searchName: 'Meowscarada (SVI 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Tarountula',
    tcgApiId: 'sv1-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/16.png","large":"https://images.pokemontcg.io/sv1/16_hires.png"}',
    searchName: 'Tarountula (SVI 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Tarountula',
    tcgApiId: 'sv1-17',
    number: '17',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/17.png","large":"https://images.pokemontcg.io/sv1/17_hires.png"}',
    searchName: 'Tarountula (SVI 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Tarountula',
    tcgApiId: 'sv1-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/18.png","large":"https://images.pokemontcg.io/sv1/18_hires.png"}',
    searchName: 'Tarountula (SVI 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Spidops ex',
    tcgApiId: 'sv1-19',
    number: '19',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/19.png","large":"https://images.pokemontcg.io/sv1/19_hires.png"}',
    searchName: 'Spidops ex (SVI 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Smoliv',
    tcgApiId: 'sv1-20',
    number: '20',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/20.png","large":"https://images.pokemontcg.io/sv1/20_hires.png"}',
    searchName: 'Smoliv (SVI 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Smoliv',
    tcgApiId: 'sv1-21',
    number: '21',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/21.png","large":"https://images.pokemontcg.io/sv1/21_hires.png"}',
    searchName: 'Smoliv (SVI 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Dolliv',
    tcgApiId: 'sv1-22',
    number: '22',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/22.png","large":"https://images.pokemontcg.io/sv1/22_hires.png"}',
    searchName: 'Dolliv (SVI 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Arboliva',
    tcgApiId: 'sv1-23',
    number: '23',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/23.png","large":"https://images.pokemontcg.io/sv1/23_hires.png"}',
    searchName: 'Arboliva (SVI 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Toedscool',
    tcgApiId: 'sv1-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/24.png","large":"https://images.pokemontcg.io/sv1/24_hires.png"}',
    searchName: 'Toedscool (SVI 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Toedscool',
    tcgApiId: 'sv1-25',
    number: '25',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/25.png","large":"https://images.pokemontcg.io/sv1/25_hires.png"}',
    searchName: 'Toedscool (SVI 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Toedscruel',
    tcgApiId: 'sv1-26',
    number: '26',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/26.png","large":"https://images.pokemontcg.io/sv1/26_hires.png"}',
    searchName: 'Toedscruel (SVI 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Capsakid',
    tcgApiId: 'sv1-27',
    number: '27',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/27.png","large":"https://images.pokemontcg.io/sv1/27_hires.png"}',
    searchName: 'Capsakid (SVI 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Capsakid',
    tcgApiId: 'sv1-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/28.png","large":"https://images.pokemontcg.io/sv1/28_hires.png"}',
    searchName: 'Capsakid (SVI 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Scovillain',
    tcgApiId: 'sv1-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/29.png","large":"https://images.pokemontcg.io/sv1/29_hires.png"}',
    searchName: 'Scovillain (SVI 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Growlithe',
    tcgApiId: 'sv1-30',
    number: '30',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/30.png","large":"https://images.pokemontcg.io/sv1/30_hires.png"}',
    searchName: 'Growlithe (SVI 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Growlithe',
    tcgApiId: 'sv1-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/31.png","large":"https://images.pokemontcg.io/sv1/31_hires.png"}',
    searchName: 'Growlithe (SVI 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Arcanine ex',
    tcgApiId: 'sv1-32',
    number: '32',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/32.png","large":"https://images.pokemontcg.io/sv1/32_hires.png"}',
    searchName: 'Arcanine ex (SVI 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Houndour',
    tcgApiId: 'sv1-33',
    number: '33',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/33.png","large":"https://images.pokemontcg.io/sv1/33_hires.png"}',
    searchName: 'Houndour (SVI 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Houndoom',
    tcgApiId: 'sv1-34',
    number: '34',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/34.png","large":"https://images.pokemontcg.io/sv1/34_hires.png"}',
    searchName: 'Houndoom (SVI 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Torkoal',
    tcgApiId: 'sv1-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/35.png","large":"https://images.pokemontcg.io/sv1/35_hires.png"}',
    searchName: 'Torkoal (SVI 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Fuecoco',
    tcgApiId: 'sv1-36',
    number: '36',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/36.png","large":"https://images.pokemontcg.io/sv1/36_hires.png"}',
    searchName: 'Fuecoco (SVI 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Crocalor',
    tcgApiId: 'sv1-37',
    number: '37',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/37.png","large":"https://images.pokemontcg.io/sv1/37_hires.png"}',
    searchName: 'Crocalor (SVI 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Skeledirge',
    tcgApiId: 'sv1-38',
    number: '38',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/38.png","large":"https://images.pokemontcg.io/sv1/38_hires.png"}',
    searchName: 'Skeledirge (SVI 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Charcadet',
    tcgApiId: 'sv1-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/39.png","large":"https://images.pokemontcg.io/sv1/39_hires.png"}',
    searchName: 'Charcadet (SVI 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Charcadet',
    tcgApiId: 'sv1-40',
    number: '40',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/40.png","large":"https://images.pokemontcg.io/sv1/40_hires.png"}',
    searchName: 'Charcadet (SVI 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Armarouge',
    tcgApiId: 'sv1-41',
    number: '41',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/41.png","large":"https://images.pokemontcg.io/sv1/41_hires.png"}',
    searchName: 'Armarouge (SVI 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Slowpoke',
    tcgApiId: 'sv1-42',
    number: '42',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/42.png","large":"https://images.pokemontcg.io/sv1/42_hires.png"}',
    searchName: 'Slowpoke (SVI 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Slowbro',
    tcgApiId: 'sv1-43',
    number: '43',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/43.png","large":"https://images.pokemontcg.io/sv1/43_hires.png"}',
    searchName: 'Slowbro (SVI 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Magikarp',
    tcgApiId: 'sv1-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/44.png","large":"https://images.pokemontcg.io/sv1/44_hires.png"}',
    searchName: 'Magikarp (SVI 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Gyarados ex',
    tcgApiId: 'sv1-45',
    number: '45',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/45.png","large":"https://images.pokemontcg.io/sv1/45_hires.png"}',
    searchName: 'Gyarados ex (SVI 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Buizel',
    tcgApiId: 'sv1-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/46.png","large":"https://images.pokemontcg.io/sv1/46_hires.png"}',
    searchName: 'Buizel (SVI 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Floatzel',
    tcgApiId: 'sv1-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/47.png","large":"https://images.pokemontcg.io/sv1/47_hires.png"}',
    searchName: 'Floatzel (SVI 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Alomomola',
    tcgApiId: 'sv1-48',
    number: '48',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/48.png","large":"https://images.pokemontcg.io/sv1/48_hires.png"}',
    searchName: 'Alomomola (SVI 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Clauncher',
    tcgApiId: 'sv1-49',
    number: '49',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/49.png","large":"https://images.pokemontcg.io/sv1/49_hires.png"}',
    searchName: 'Clauncher (SVI 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Clawitzer',
    tcgApiId: 'sv1-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/50.png","large":"https://images.pokemontcg.io/sv1/50_hires.png"}',
    searchName: 'Clawitzer (SVI 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Bruxish',
    tcgApiId: 'sv1-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/51.png","large":"https://images.pokemontcg.io/sv1/51_hires.png"}',
    searchName: 'Bruxish (SVI 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Quaxly',
    tcgApiId: 'sv1-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/52.png","large":"https://images.pokemontcg.io/sv1/52_hires.png"}',
    searchName: 'Quaxly (SVI 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Quaxwell',
    tcgApiId: 'sv1-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/53.png","large":"https://images.pokemontcg.io/sv1/53_hires.png"}',
    searchName: 'Quaxwell (SVI 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Quaquaval',
    tcgApiId: 'sv1-54',
    number: '54',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/54.png","large":"https://images.pokemontcg.io/sv1/54_hires.png"}',
    searchName: 'Quaquaval (SVI 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Wiglett',
    tcgApiId: 'sv1-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/55.png","large":"https://images.pokemontcg.io/sv1/55_hires.png"}',
    searchName: 'Wiglett (SVI 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Wiglett',
    tcgApiId: 'sv1-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/56.png","large":"https://images.pokemontcg.io/sv1/56_hires.png"}',
    searchName: 'Wiglett (SVI 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Wugtrio',
    tcgApiId: 'sv1-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/57.png","large":"https://images.pokemontcg.io/sv1/57_hires.png"}',
    searchName: 'Wugtrio (SVI 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Cetoddle',
    tcgApiId: 'sv1-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/58.png","large":"https://images.pokemontcg.io/sv1/58_hires.png"}',
    searchName: 'Cetoddle (SVI 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Cetoddle',
    tcgApiId: 'sv1-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/59.png","large":"https://images.pokemontcg.io/sv1/59_hires.png"}',
    searchName: 'Cetoddle (SVI 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Cetitan',
    tcgApiId: 'sv1-60',
    number: '60',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/60.png","large":"https://images.pokemontcg.io/sv1/60_hires.png"}',
    searchName: 'Cetitan (SVI 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Dondozo',
    tcgApiId: 'sv1-61',
    number: '61',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/61.png","large":"https://images.pokemontcg.io/sv1/61_hires.png"}',
    searchName: 'Dondozo (SVI 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Tatsugiri',
    tcgApiId: 'sv1-62',
    number: '62',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/62.png","large":"https://images.pokemontcg.io/sv1/62_hires.png"}',
    searchName: 'Tatsugiri (SVI 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Magnemite',
    tcgApiId: 'sv1-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/63.png","large":"https://images.pokemontcg.io/sv1/63_hires.png"}',
    searchName: 'Magnemite (SVI 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Magneton',
    tcgApiId: 'sv1-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/64.png","large":"https://images.pokemontcg.io/sv1/64_hires.png"}',
    searchName: 'Magneton (SVI 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Magnezone ex',
    tcgApiId: 'sv1-65',
    number: '65',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/65.png","large":"https://images.pokemontcg.io/sv1/65_hires.png"}',
    searchName: 'Magnezone ex (SVI 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Mareep',
    tcgApiId: 'sv1-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/66.png","large":"https://images.pokemontcg.io/sv1/66_hires.png"}',
    searchName: 'Mareep (SVI 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Flaaffy',
    tcgApiId: 'sv1-67',
    number: '67',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/67.png","large":"https://images.pokemontcg.io/sv1/67_hires.png"}',
    searchName: 'Flaaffy (SVI 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pachirisu',
    tcgApiId: 'sv1-68',
    number: '68',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/68.png","large":"https://images.pokemontcg.io/sv1/68_hires.png"}',
    searchName: 'Pachirisu (SVI 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Rotom',
    tcgApiId: 'sv1-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/69.png","large":"https://images.pokemontcg.io/sv1/69_hires.png"}',
    searchName: 'Rotom (SVI 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Rotom',
    tcgApiId: 'sv1-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/70.png","large":"https://images.pokemontcg.io/sv1/70_hires.png"}',
    searchName: 'Rotom (SVI 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Toxel',
    tcgApiId: 'sv1-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/71.png","large":"https://images.pokemontcg.io/sv1/71_hires.png"}',
    searchName: 'Toxel (SVI 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Toxtricity',
    tcgApiId: 'sv1-72',
    number: '72',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/72.png","large":"https://images.pokemontcg.io/sv1/72_hires.png"}',
    searchName: 'Toxtricity (SVI 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pawmi',
    tcgApiId: 'sv1-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/73.png","large":"https://images.pokemontcg.io/sv1/73_hires.png"}',
    searchName: 'Pawmi (SVI 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pawmi',
    tcgApiId: 'sv1-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/74.png","large":"https://images.pokemontcg.io/sv1/74_hires.png"}',
    searchName: 'Pawmi (SVI 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pawmo',
    tcgApiId: 'sv1-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/75.png","large":"https://images.pokemontcg.io/sv1/75_hires.png"}',
    searchName: 'Pawmo (SVI 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pawmot',
    tcgApiId: 'sv1-76',
    number: '76',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/76.png","large":"https://images.pokemontcg.io/sv1/76_hires.png"}',
    searchName: 'Pawmot (SVI 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Wattrel',
    tcgApiId: 'sv1-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/77.png","large":"https://images.pokemontcg.io/sv1/77_hires.png"}',
    searchName: 'Wattrel (SVI 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Wattrel',
    tcgApiId: 'sv1-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/78.png","large":"https://images.pokemontcg.io/sv1/78_hires.png"}',
    searchName: 'Wattrel (SVI 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Kilowattrel',
    tcgApiId: 'sv1-79',
    number: '79',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/79.png","large":"https://images.pokemontcg.io/sv1/79_hires.png"}',
    searchName: 'Kilowattrel (SVI 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Miraidon',
    tcgApiId: 'sv1-80',
    number: '80',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/80.png","large":"https://images.pokemontcg.io/sv1/80_hires.png"}',
    searchName: 'Miraidon (SVI 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Miraidon ex',
    tcgApiId: 'sv1-81',
    number: '81',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/81.png","large":"https://images.pokemontcg.io/sv1/81_hires.png"}',
    searchName: 'Miraidon ex (SVI 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Drowzee',
    tcgApiId: 'sv1-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/82.png","large":"https://images.pokemontcg.io/sv1/82_hires.png"}',
    searchName: 'Drowzee (SVI 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Hypno',
    tcgApiId: 'sv1-83',
    number: '83',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/83.png","large":"https://images.pokemontcg.io/sv1/83_hires.png"}',
    searchName: 'Hypno (SVI 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Ralts',
    tcgApiId: 'sv1-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/84.png","large":"https://images.pokemontcg.io/sv1/84_hires.png"}',
    searchName: 'Ralts (SVI 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Kirlia',
    tcgApiId: 'sv1-85',
    number: '85',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/85.png","large":"https://images.pokemontcg.io/sv1/85_hires.png"}',
    searchName: 'Kirlia (SVI 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Gardevoir ex',
    tcgApiId: 'sv1-86',
    number: '86',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/86.png","large":"https://images.pokemontcg.io/sv1/86_hires.png"}',
    searchName: 'Gardevoir ex (SVI 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Shuppet',
    tcgApiId: 'sv1-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/87.png","large":"https://images.pokemontcg.io/sv1/87_hires.png"}',
    searchName: 'Shuppet (SVI 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Banette ex',
    tcgApiId: 'sv1-88',
    number: '88',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/88.png","large":"https://images.pokemontcg.io/sv1/88_hires.png"}',
    searchName: 'Banette ex (SVI 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Drifloon',
    tcgApiId: 'sv1-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/89.png","large":"https://images.pokemontcg.io/sv1/89_hires.png"}',
    searchName: 'Drifloon (SVI 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Drifblim',
    tcgApiId: 'sv1-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/90.png","large":"https://images.pokemontcg.io/sv1/90_hires.png"}',
    searchName: 'Drifblim (SVI 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Flabébé',
    tcgApiId: 'sv1-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/91.png","large":"https://images.pokemontcg.io/sv1/91_hires.png"}',
    searchName: 'Flabébé (SVI 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Floette',
    tcgApiId: 'sv1-92',
    number: '92',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/92.png","large":"https://images.pokemontcg.io/sv1/92_hires.png"}',
    searchName: 'Floette (SVI 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Florges',
    tcgApiId: 'sv1-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/93.png","large":"https://images.pokemontcg.io/sv1/93_hires.png"}',
    searchName: 'Florges (SVI 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Dedenne',
    tcgApiId: 'sv1-94',
    number: '94',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/94.png","large":"https://images.pokemontcg.io/sv1/94_hires.png"}',
    searchName: 'Dedenne (SVI 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Dedenne',
    tcgApiId: 'sv1-95',
    number: '95',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/95.png","large":"https://images.pokemontcg.io/sv1/95_hires.png"}',
    searchName: 'Dedenne (SVI 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Klefki',
    tcgApiId: 'sv1-96',
    number: '96',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/96.png","large":"https://images.pokemontcg.io/sv1/96_hires.png"}',
    searchName: 'Klefki (SVI 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Fidough',
    tcgApiId: 'sv1-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/97.png","large":"https://images.pokemontcg.io/sv1/97_hires.png"}',
    searchName: 'Fidough (SVI 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Fidough',
    tcgApiId: 'sv1-98',
    number: '98',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/98.png","large":"https://images.pokemontcg.io/sv1/98_hires.png"}',
    searchName: 'Fidough (SVI 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Dachsbun',
    tcgApiId: 'sv1-99',
    number: '99',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/99.png","large":"https://images.pokemontcg.io/sv1/99_hires.png"}',
    searchName: 'Dachsbun (SVI 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Flittle',
    tcgApiId: 'sv1-100',
    number: '100',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/100.png","large":"https://images.pokemontcg.io/sv1/100_hires.png"}',
    searchName: 'Flittle (SVI 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Flittle',
    tcgApiId: 'sv1-101',
    number: '101',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/101.png","large":"https://images.pokemontcg.io/sv1/101_hires.png"}',
    searchName: 'Flittle (SVI 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Flittle',
    tcgApiId: 'sv1-102',
    number: '102',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/102.png","large":"https://images.pokemontcg.io/sv1/102_hires.png"}',
    searchName: 'Flittle (SVI 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Espathra',
    tcgApiId: 'sv1-103',
    number: '103',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/103.png","large":"https://images.pokemontcg.io/sv1/103_hires.png"}',
    searchName: 'Espathra (SVI 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Greavard',
    tcgApiId: 'sv1-104',
    number: '104',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/104.png","large":"https://images.pokemontcg.io/sv1/104_hires.png"}',
    searchName: 'Greavard (SVI 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Greavard',
    tcgApiId: 'sv1-105',
    number: '105',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/105.png","large":"https://images.pokemontcg.io/sv1/105_hires.png"}',
    searchName: 'Greavard (SVI 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Houndstone',
    tcgApiId: 'sv1-106',
    number: '106',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/106.png","large":"https://images.pokemontcg.io/sv1/106_hires.png"}',
    searchName: 'Houndstone (SVI 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Mankey',
    tcgApiId: 'sv1-107',
    number: '107',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/107.png","large":"https://images.pokemontcg.io/sv1/107_hires.png"}',
    searchName: 'Mankey (SVI 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Primeape',
    tcgApiId: 'sv1-108',
    number: '108',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/108.png","large":"https://images.pokemontcg.io/sv1/108_hires.png"}',
    searchName: 'Primeape (SVI 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Annihilape',
    tcgApiId: 'sv1-109',
    number: '109',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/109.png","large":"https://images.pokemontcg.io/sv1/109_hires.png"}',
    searchName: 'Annihilape (SVI 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Meditite',
    tcgApiId: 'sv1-110',
    number: '110',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/110.png","large":"https://images.pokemontcg.io/sv1/110_hires.png"}',
    searchName: 'Meditite (SVI 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Medicham',
    tcgApiId: 'sv1-111',
    number: '111',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/111.png","large":"https://images.pokemontcg.io/sv1/111_hires.png"}',
    searchName: 'Medicham (SVI 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Riolu',
    tcgApiId: 'sv1-112',
    number: '112',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/112.png","large":"https://images.pokemontcg.io/sv1/112_hires.png"}',
    searchName: 'Riolu (SVI 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Riolu',
    tcgApiId: 'sv1-113',
    number: '113',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/113.png","large":"https://images.pokemontcg.io/sv1/113_hires.png"}',
    searchName: 'Riolu (SVI 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Lucario',
    tcgApiId: 'sv1-114',
    number: '114',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/114.png","large":"https://images.pokemontcg.io/sv1/114_hires.png"}',
    searchName: 'Lucario (SVI 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Sandile',
    tcgApiId: 'sv1-115',
    number: '115',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/115.png","large":"https://images.pokemontcg.io/sv1/115_hires.png"}',
    searchName: 'Sandile (SVI 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Krokorok',
    tcgApiId: 'sv1-116',
    number: '116',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/116.png","large":"https://images.pokemontcg.io/sv1/116_hires.png"}',
    searchName: 'Krokorok (SVI 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Krookodile',
    tcgApiId: 'sv1-117',
    number: '117',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/117.png","large":"https://images.pokemontcg.io/sv1/117_hires.png"}',
    searchName: 'Krookodile (SVI 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Hawlucha',
    tcgApiId: 'sv1-118',
    number: '118',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/118.png","large":"https://images.pokemontcg.io/sv1/118_hires.png"}',
    searchName: 'Hawlucha (SVI 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Silicobra',
    tcgApiId: 'sv1-119',
    number: '119',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/119.png","large":"https://images.pokemontcg.io/sv1/119_hires.png"}',
    searchName: 'Silicobra (SVI 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Sandaconda',
    tcgApiId: 'sv1-120',
    number: '120',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/120.png","large":"https://images.pokemontcg.io/sv1/120_hires.png"}',
    searchName: 'Sandaconda (SVI 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Stonjourner',
    tcgApiId: 'sv1-121',
    number: '121',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/121.png","large":"https://images.pokemontcg.io/sv1/121_hires.png"}',
    searchName: 'Stonjourner (SVI 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Klawf',
    tcgApiId: 'sv1-122',
    number: '122',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/122.png","large":"https://images.pokemontcg.io/sv1/122_hires.png"}',
    searchName: 'Klawf (SVI 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Great Tusk ex',
    tcgApiId: 'sv1-123',
    number: '123',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/123.png","large":"https://images.pokemontcg.io/sv1/123_hires.png"}',
    searchName: 'Great Tusk ex (SVI 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Koraidon',
    tcgApiId: 'sv1-124',
    number: '124',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/124.png","large":"https://images.pokemontcg.io/sv1/124_hires.png"}',
    searchName: 'Koraidon (SVI 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Koraidon ex',
    tcgApiId: 'sv1-125',
    number: '125',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/125.png","large":"https://images.pokemontcg.io/sv1/125_hires.png"}',
    searchName: 'Koraidon ex (SVI 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Grimer',
    tcgApiId: 'sv1-126',
    number: '126',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/126.png","large":"https://images.pokemontcg.io/sv1/126_hires.png"}',
    searchName: 'Grimer (SVI 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Muk',
    tcgApiId: 'sv1-127',
    number: '127',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/127.png","large":"https://images.pokemontcg.io/sv1/127_hires.png"}',
    searchName: 'Muk (SVI 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Seviper',
    tcgApiId: 'sv1-128',
    number: '128',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/128.png","large":"https://images.pokemontcg.io/sv1/128_hires.png"}',
    searchName: 'Seviper (SVI 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Spiritomb',
    tcgApiId: 'sv1-129',
    number: '129',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/129.png","large":"https://images.pokemontcg.io/sv1/129_hires.png"}',
    searchName: 'Spiritomb (SVI 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Croagunk',
    tcgApiId: 'sv1-130',
    number: '130',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/130.png","large":"https://images.pokemontcg.io/sv1/130_hires.png"}',
    searchName: 'Croagunk (SVI 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Toxicroak ex',
    tcgApiId: 'sv1-131',
    number: '131',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/131.png","large":"https://images.pokemontcg.io/sv1/131_hires.png"}',
    searchName: 'Toxicroak ex (SVI 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pawniard',
    tcgApiId: 'sv1-132',
    number: '132',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/132.png","large":"https://images.pokemontcg.io/sv1/132_hires.png"}',
    searchName: 'Pawniard (SVI 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Bisharp',
    tcgApiId: 'sv1-133',
    number: '133',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/133.png","large":"https://images.pokemontcg.io/sv1/133_hires.png"}',
    searchName: 'Bisharp (SVI 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Kingambit',
    tcgApiId: 'sv1-134',
    number: '134',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/134.png","large":"https://images.pokemontcg.io/sv1/134_hires.png"}',
    searchName: 'Kingambit (SVI 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Maschiff',
    tcgApiId: 'sv1-135',
    number: '135',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/135.png","large":"https://images.pokemontcg.io/sv1/135_hires.png"}',
    searchName: 'Maschiff (SVI 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Maschiff',
    tcgApiId: 'sv1-136',
    number: '136',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/136.png","large":"https://images.pokemontcg.io/sv1/136_hires.png"}',
    searchName: 'Maschiff (SVI 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Mabosstiff',
    tcgApiId: 'sv1-137',
    number: '137',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/137.png","large":"https://images.pokemontcg.io/sv1/137_hires.png"}',
    searchName: 'Mabosstiff (SVI 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Bombirdier',
    tcgApiId: 'sv1-138',
    number: '138',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/138.png","large":"https://images.pokemontcg.io/sv1/138_hires.png"}',
    searchName: 'Bombirdier (SVI 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Forretress',
    tcgApiId: 'sv1-139',
    number: '139',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/139.png","large":"https://images.pokemontcg.io/sv1/139_hires.png"}',
    searchName: 'Forretress (SVI 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Varoom',
    tcgApiId: 'sv1-140',
    number: '140',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/140.png","large":"https://images.pokemontcg.io/sv1/140_hires.png"}',
    searchName: 'Varoom (SVI 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Varoom',
    tcgApiId: 'sv1-141',
    number: '141',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/141.png","large":"https://images.pokemontcg.io/sv1/141_hires.png"}',
    searchName: 'Varoom (SVI 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Revavroom',
    tcgApiId: 'sv1-142',
    number: '142',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/142.png","large":"https://images.pokemontcg.io/sv1/142_hires.png"}',
    searchName: 'Revavroom (SVI 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Iron Treads ex',
    tcgApiId: 'sv1-143',
    number: '143',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/143.png","large":"https://images.pokemontcg.io/sv1/143_hires.png"}',
    searchName: 'Iron Treads ex (SVI 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Chansey',
    tcgApiId: 'sv1-144',
    number: '144',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/144.png","large":"https://images.pokemontcg.io/sv1/144_hires.png"}',
    searchName: 'Chansey (SVI 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Blissey',
    tcgApiId: 'sv1-145',
    number: '145',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/145.png","large":"https://images.pokemontcg.io/sv1/145_hires.png"}',
    searchName: 'Blissey (SVI 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Zangoose',
    tcgApiId: 'sv1-146',
    number: '146',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/146.png","large":"https://images.pokemontcg.io/sv1/146_hires.png"}',
    searchName: 'Zangoose (SVI 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Zangoose',
    tcgApiId: 'sv1-147',
    number: '147',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/147.png","large":"https://images.pokemontcg.io/sv1/147_hires.png"}',
    searchName: 'Zangoose (SVI 147)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Starly',
    tcgApiId: 'sv1-148',
    number: '148',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/148.png","large":"https://images.pokemontcg.io/sv1/148_hires.png"}',
    searchName: 'Starly (SVI 148)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Staravia',
    tcgApiId: 'sv1-149',
    number: '149',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/149.png","large":"https://images.pokemontcg.io/sv1/149_hires.png"}',
    searchName: 'Staravia (SVI 149)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Staraptor',
    tcgApiId: 'sv1-150',
    number: '150',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/150.png","large":"https://images.pokemontcg.io/sv1/150_hires.png"}',
    searchName: 'Staraptor (SVI 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Skwovet',
    tcgApiId: 'sv1-151',
    number: '151',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/151.png","large":"https://images.pokemontcg.io/sv1/151_hires.png"}',
    searchName: 'Skwovet (SVI 151)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Greedent',
    tcgApiId: 'sv1-152',
    number: '152',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/152.png","large":"https://images.pokemontcg.io/sv1/152_hires.png"}',
    searchName: 'Greedent (SVI 152)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Indeedee',
    tcgApiId: 'sv1-153',
    number: '153',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/153.png","large":"https://images.pokemontcg.io/sv1/153_hires.png"}',
    searchName: 'Indeedee (SVI 153)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Lechonk',
    tcgApiId: 'sv1-154',
    number: '154',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/154.png","large":"https://images.pokemontcg.io/sv1/154_hires.png"}',
    searchName: 'Lechonk (SVI 154)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Lechonk',
    tcgApiId: 'sv1-155',
    number: '155',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/155.png","large":"https://images.pokemontcg.io/sv1/155_hires.png"}',
    searchName: 'Lechonk (SVI 155)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Lechonk',
    tcgApiId: 'sv1-156',
    number: '156',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/156.png","large":"https://images.pokemontcg.io/sv1/156_hires.png"}',
    searchName: 'Lechonk (SVI 156)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Oinkologne',
    tcgApiId: 'sv1-157',
    number: '157',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/157.png","large":"https://images.pokemontcg.io/sv1/157_hires.png"}',
    searchName: 'Oinkologne (SVI 157)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Oinkologne ex',
    tcgApiId: 'sv1-158',
    number: '158',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/158.png","large":"https://images.pokemontcg.io/sv1/158_hires.png"}',
    searchName: 'Oinkologne ex (SVI 158)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Tandemaus',
    tcgApiId: 'sv1-159',
    number: '159',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/159.png","large":"https://images.pokemontcg.io/sv1/159_hires.png"}',
    searchName: 'Tandemaus (SVI 159)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Tandemaus',
    tcgApiId: 'sv1-160',
    number: '160',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/160.png","large":"https://images.pokemontcg.io/sv1/160_hires.png"}',
    searchName: 'Tandemaus (SVI 160)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Maushold',
    tcgApiId: 'sv1-161',
    number: '161',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/161.png","large":"https://images.pokemontcg.io/sv1/161_hires.png"}',
    searchName: 'Maushold (SVI 161)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Squawkabilly',
    tcgApiId: 'sv1-162',
    number: '162',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/162.png","large":"https://images.pokemontcg.io/sv1/162_hires.png"}',
    searchName: 'Squawkabilly (SVI 162)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Cyclizar',
    tcgApiId: 'sv1-163',
    number: '163',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/163.png","large":"https://images.pokemontcg.io/sv1/163_hires.png"}',
    searchName: 'Cyclizar (SVI 163)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Cyclizar',
    tcgApiId: 'sv1-164',
    number: '164',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/164.png","large":"https://images.pokemontcg.io/sv1/164_hires.png"}',
    searchName: 'Cyclizar (SVI 164)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Flamigo',
    tcgApiId: 'sv1-165',
    number: '165',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/165.png","large":"https://images.pokemontcg.io/sv1/165_hires.png"}',
    searchName: 'Flamigo (SVI 165)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Arven',
    tcgApiId: 'sv1-166',
    number: '166',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/166.png","large":"https://images.pokemontcg.io/sv1/166_hires.png"}',
    searchName: 'Arven (SVI 166)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Beach Court',
    tcgApiId: 'sv1-167',
    number: '167',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/167.png","large":"https://images.pokemontcg.io/sv1/167_hires.png"}',
    searchName: 'Beach Court (SVI 167)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Crushing Hammer',
    tcgApiId: 'sv1-168',
    number: '168',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/168.png","large":"https://images.pokemontcg.io/sv1/168_hires.png"}',
    searchName: 'Crushing Hammer (SVI 168)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Defiance Band',
    tcgApiId: 'sv1-169',
    number: '169',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/169.png","large":"https://images.pokemontcg.io/sv1/169_hires.png"}',
    searchName: 'Defiance Band (SVI 169)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Electric Generator',
    tcgApiId: 'sv1-170',
    number: '170',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/170.png","large":"https://images.pokemontcg.io/sv1/170_hires.png"}',
    searchName: 'Electric Generator (SVI 170)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Energy Retrieval',
    tcgApiId: 'sv1-171',
    number: '171',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/171.png","large":"https://images.pokemontcg.io/sv1/171_hires.png"}',
    searchName: 'Energy Retrieval (SVI 171)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Energy Search',
    tcgApiId: 'sv1-172',
    number: '172',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/172.png","large":"https://images.pokemontcg.io/sv1/172_hires.png"}',
    searchName: 'Energy Search (SVI 172)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Energy Switch',
    tcgApiId: 'sv1-173',
    number: '173',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/173.png","large":"https://images.pokemontcg.io/sv1/173_hires.png"}',
    searchName: 'Energy Switch (SVI 173)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Exp. Share',
    tcgApiId: 'sv1-174',
    number: '174',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/174.png","large":"https://images.pokemontcg.io/sv1/174_hires.png"}',
    searchName: 'Exp. Share (SVI 174)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Jacq',
    tcgApiId: 'sv1-175',
    number: '175',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/175.png","large":"https://images.pokemontcg.io/sv1/175_hires.png"}',
    searchName: 'Jacq (SVI 175)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Judge',
    tcgApiId: 'sv1-176',
    number: '176',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/176.png","large":"https://images.pokemontcg.io/sv1/176_hires.png"}',
    searchName: 'Judge (SVI 176)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Katy',
    tcgApiId: 'sv1-177',
    number: '177',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/177.png","large":"https://images.pokemontcg.io/sv1/177_hires.png"}',
    searchName: 'Katy (SVI 177)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Mesagoza',
    tcgApiId: 'sv1-178',
    number: '178',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/178.png","large":"https://images.pokemontcg.io/sv1/178_hires.png"}',
    searchName: 'Mesagoza (SVI 178)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Miriam',
    tcgApiId: 'sv1-179',
    number: '179',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/179.png","large":"https://images.pokemontcg.io/sv1/179_hires.png"}',
    searchName: 'Miriam (SVI 179)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Nemona',
    tcgApiId: 'sv1-180',
    number: '180',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/180.png","large":"https://images.pokemontcg.io/sv1/180_hires.png"}',
    searchName: 'Nemona (SVI 180)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Nest Ball',
    tcgApiId: 'sv1-181',
    number: '181',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/181.png","large":"https://images.pokemontcg.io/sv1/181_hires.png"}',
    searchName: 'Nest Ball (SVI 181)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pal Pad',
    tcgApiId: 'sv1-182',
    number: '182',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/182.png","large":"https://images.pokemontcg.io/sv1/182_hires.png"}',
    searchName: 'Pal Pad (SVI 182)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Penny',
    tcgApiId: 'sv1-183',
    number: '183',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/183.png","large":"https://images.pokemontcg.io/sv1/183_hires.png"}',
    searchName: 'Penny (SVI 183)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Picnic Basket',
    tcgApiId: 'sv1-184',
    number: '184',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/184.png","large":"https://images.pokemontcg.io/sv1/184_hires.png"}',
    searchName: 'Picnic Basket (SVI 184)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Poké Ball',
    tcgApiId: 'sv1-185',
    number: '185',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/185.png","large":"https://images.pokemontcg.io/sv1/185_hires.png"}',
    searchName: 'Poké Ball (SVI 185)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pokégear 3.0',
    tcgApiId: 'sv1-186',
    number: '186',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/186.png","large":"https://images.pokemontcg.io/sv1/186_hires.png"}',
    searchName: 'Pokégear 3.0 (SVI 186)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pokémon Catcher',
    tcgApiId: 'sv1-187',
    number: '187',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/187.png","large":"https://images.pokemontcg.io/sv1/187_hires.png"}',
    searchName: 'Pokémon Catcher (SVI 187)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Potion',
    tcgApiId: 'sv1-188',
    number: '188',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/188.png","large":"https://images.pokemontcg.io/sv1/188_hires.png"}',
    searchName: 'Potion (SVI 188)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: "Professor's Research (Professor Sada)",
    tcgApiId: 'sv1-189',
    number: '189',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/189.png","large":"https://images.pokemontcg.io/sv1/189_hires.png"}',
    searchName: "Professor's Research (Professor Sada) (SVI 189)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: "Professor's Research (Professor Turo)",
    tcgApiId: 'sv1-190',
    number: '190',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/190.png","large":"https://images.pokemontcg.io/sv1/190_hires.png"}',
    searchName: "Professor's Research (Professor Turo) (SVI 190)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Rare Candy',
    tcgApiId: 'sv1-191',
    number: '191',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/191.png","large":"https://images.pokemontcg.io/sv1/191_hires.png"}',
    searchName: 'Rare Candy (SVI 191)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Rock Chestplate',
    tcgApiId: 'sv1-192',
    number: '192',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/192.png","large":"https://images.pokemontcg.io/sv1/192_hires.png"}',
    searchName: 'Rock Chestplate (SVI 192)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Rocky Helmet',
    tcgApiId: 'sv1-193',
    number: '193',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/193.png","large":"https://images.pokemontcg.io/sv1/193_hires.png"}',
    searchName: 'Rocky Helmet (SVI 193)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Switch',
    tcgApiId: 'sv1-194',
    number: '194',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/194.png","large":"https://images.pokemontcg.io/sv1/194_hires.png"}',
    searchName: 'Switch (SVI 194)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Team Star Grunt',
    tcgApiId: 'sv1-195',
    number: '195',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/195.png","large":"https://images.pokemontcg.io/sv1/195_hires.png"}',
    searchName: 'Team Star Grunt (SVI 195)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Ultra Ball',
    tcgApiId: 'sv1-196',
    number: '196',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/196.png","large":"https://images.pokemontcg.io/sv1/196_hires.png"}',
    searchName: 'Ultra Ball (SVI 196)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Vitality Band',
    tcgApiId: 'sv1-197',
    number: '197',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/197.png","large":"https://images.pokemontcg.io/sv1/197_hires.png"}',
    searchName: 'Vitality Band (SVI 197)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Youngster',
    tcgApiId: 'sv1-198',
    number: '198',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/198.png","large":"https://images.pokemontcg.io/sv1/198_hires.png"}',
    searchName: 'Youngster (SVI 198)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Tarountula',
    tcgApiId: 'sv1-199',
    number: '199',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/199.png","large":"https://images.pokemontcg.io/sv1/199_hires.png"}',
    searchName: 'Tarountula (SVI 199)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Dolliv',
    tcgApiId: 'sv1-200',
    number: '200',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/200.png","large":"https://images.pokemontcg.io/sv1/200_hires.png"}',
    searchName: 'Dolliv (SVI 200)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Toedscool',
    tcgApiId: 'sv1-201',
    number: '201',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/201.png","large":"https://images.pokemontcg.io/sv1/201_hires.png"}',
    searchName: 'Toedscool (SVI 201)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Scovillain',
    tcgApiId: 'sv1-202',
    number: '202',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/202.png","large":"https://images.pokemontcg.io/sv1/202_hires.png"}',
    searchName: 'Scovillain (SVI 202)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Armarouge',
    tcgApiId: 'sv1-203',
    number: '203',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/203.png","large":"https://images.pokemontcg.io/sv1/203_hires.png"}',
    searchName: 'Armarouge (SVI 203)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Slowpoke',
    tcgApiId: 'sv1-204',
    number: '204',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/204.png","large":"https://images.pokemontcg.io/sv1/204_hires.png"}',
    searchName: 'Slowpoke (SVI 204)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Clauncher',
    tcgApiId: 'sv1-205',
    number: '205',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/205.png","large":"https://images.pokemontcg.io/sv1/205_hires.png"}',
    searchName: 'Clauncher (SVI 205)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Wiglett',
    tcgApiId: 'sv1-206',
    number: '206',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/206.png","large":"https://images.pokemontcg.io/sv1/206_hires.png"}',
    searchName: 'Wiglett (SVI 206)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Dondozo',
    tcgApiId: 'sv1-207',
    number: '207',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/207.png","large":"https://images.pokemontcg.io/sv1/207_hires.png"}',
    searchName: 'Dondozo (SVI 207)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pachirisu',
    tcgApiId: 'sv1-208',
    number: '208',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/208.png","large":"https://images.pokemontcg.io/sv1/208_hires.png"}',
    searchName: 'Pachirisu (SVI 208)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Pawmot',
    tcgApiId: 'sv1-209',
    number: '209',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/209.png","large":"https://images.pokemontcg.io/sv1/209_hires.png"}',
    searchName: 'Pawmot (SVI 209)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Drowzee',
    tcgApiId: 'sv1-210',
    number: '210',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/210.png","large":"https://images.pokemontcg.io/sv1/210_hires.png"}',
    searchName: 'Drowzee (SVI 210)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Ralts',
    tcgApiId: 'sv1-211',
    number: '211',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/211.png","large":"https://images.pokemontcg.io/sv1/211_hires.png"}',
    searchName: 'Ralts (SVI 211)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Kirlia',
    tcgApiId: 'sv1-212',
    number: '212',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/212.png","large":"https://images.pokemontcg.io/sv1/212_hires.png"}',
    searchName: 'Kirlia (SVI 212)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Fidough',
    tcgApiId: 'sv1-213',
    number: '213',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/213.png","large":"https://images.pokemontcg.io/sv1/213_hires.png"}',
    searchName: 'Fidough (SVI 213)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Greavard',
    tcgApiId: 'sv1-214',
    number: '214',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/214.png","large":"https://images.pokemontcg.io/sv1/214_hires.png"}',
    searchName: 'Greavard (SVI 214)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Riolu',
    tcgApiId: 'sv1-215',
    number: '215',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/215.png","large":"https://images.pokemontcg.io/sv1/215_hires.png"}',
    searchName: 'Riolu (SVI 215)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Sandile',
    tcgApiId: 'sv1-216',
    number: '216',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/216.png","large":"https://images.pokemontcg.io/sv1/216_hires.png"}',
    searchName: 'Sandile (SVI 216)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Klawf',
    tcgApiId: 'sv1-217',
    number: '217',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/217.png","large":"https://images.pokemontcg.io/sv1/217_hires.png"}',
    searchName: 'Klawf (SVI 217)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Mabosstiff',
    tcgApiId: 'sv1-218',
    number: '218',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/218.png","large":"https://images.pokemontcg.io/sv1/218_hires.png"}',
    searchName: 'Mabosstiff (SVI 218)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Bombirdier',
    tcgApiId: 'sv1-219',
    number: '219',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/219.png","large":"https://images.pokemontcg.io/sv1/219_hires.png"}',
    searchName: 'Bombirdier (SVI 219)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Kingambit',
    tcgApiId: 'sv1-220',
    number: '220',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/220.png","large":"https://images.pokemontcg.io/sv1/220_hires.png"}',
    searchName: 'Kingambit (SVI 220)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Starly',
    tcgApiId: 'sv1-221',
    number: '221',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/221.png","large":"https://images.pokemontcg.io/sv1/221_hires.png"}',
    searchName: 'Starly (SVI 221)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Skwovet',
    tcgApiId: 'sv1-222',
    number: '222',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/222.png","large":"https://images.pokemontcg.io/sv1/222_hires.png"}',
    searchName: 'Skwovet (SVI 222)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Spidops ex',
    tcgApiId: 'sv1-223',
    number: '223',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/223.png","large":"https://images.pokemontcg.io/sv1/223_hires.png"}',
    searchName: 'Spidops ex (SVI 223)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Arcanine ex',
    tcgApiId: 'sv1-224',
    number: '224',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/224.png","large":"https://images.pokemontcg.io/sv1/224_hires.png"}',
    searchName: 'Arcanine ex (SVI 224)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Gyarados ex',
    tcgApiId: 'sv1-225',
    number: '225',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/225.png","large":"https://images.pokemontcg.io/sv1/225_hires.png"}',
    searchName: 'Gyarados ex (SVI 225)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Magnezone ex',
    tcgApiId: 'sv1-226',
    number: '226',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/226.png","large":"https://images.pokemontcg.io/sv1/226_hires.png"}',
    searchName: 'Magnezone ex (SVI 226)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Miraidon ex',
    tcgApiId: 'sv1-227',
    number: '227',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/227.png","large":"https://images.pokemontcg.io/sv1/227_hires.png"}',
    searchName: 'Miraidon ex (SVI 227)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Gardevoir ex',
    tcgApiId: 'sv1-228',
    number: '228',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/228.png","large":"https://images.pokemontcg.io/sv1/228_hires.png"}',
    searchName: 'Gardevoir ex (SVI 228)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Banette ex',
    tcgApiId: 'sv1-229',
    number: '229',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/229.png","large":"https://images.pokemontcg.io/sv1/229_hires.png"}',
    searchName: 'Banette ex (SVI 229)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Great Tusk ex',
    tcgApiId: 'sv1-230',
    number: '230',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/230.png","large":"https://images.pokemontcg.io/sv1/230_hires.png"}',
    searchName: 'Great Tusk ex (SVI 230)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Koraidon ex',
    tcgApiId: 'sv1-231',
    number: '231',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/231.png","large":"https://images.pokemontcg.io/sv1/231_hires.png"}',
    searchName: 'Koraidon ex (SVI 231)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Toxicroak ex',
    tcgApiId: 'sv1-232',
    number: '232',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/232.png","large":"https://images.pokemontcg.io/sv1/232_hires.png"}',
    searchName: 'Toxicroak ex (SVI 232)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Iron Treads ex',
    tcgApiId: 'sv1-233',
    number: '233',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/233.png","large":"https://images.pokemontcg.io/sv1/233_hires.png"}',
    searchName: 'Iron Treads ex (SVI 233)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Oinkologne ex',
    tcgApiId: 'sv1-234',
    number: '234',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/234.png","large":"https://images.pokemontcg.io/sv1/234_hires.png"}',
    searchName: 'Oinkologne ex (SVI 234)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Arven',
    tcgApiId: 'sv1-235',
    number: '235',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/235.png","large":"https://images.pokemontcg.io/sv1/235_hires.png"}',
    searchName: 'Arven (SVI 235)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Jacq',
    tcgApiId: 'sv1-236',
    number: '236',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/236.png","large":"https://images.pokemontcg.io/sv1/236_hires.png"}',
    searchName: 'Jacq (SVI 236)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Katy',
    tcgApiId: 'sv1-237',
    number: '237',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/237.png","large":"https://images.pokemontcg.io/sv1/237_hires.png"}',
    searchName: 'Katy (SVI 237)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Miriam',
    tcgApiId: 'sv1-238',
    number: '238',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/238.png","large":"https://images.pokemontcg.io/sv1/238_hires.png"}',
    searchName: 'Miriam (SVI 238)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Penny',
    tcgApiId: 'sv1-239',
    number: '239',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/239.png","large":"https://images.pokemontcg.io/sv1/239_hires.png"}',
    searchName: 'Penny (SVI 239)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: "Professor's Research (Professor Sada)",
    tcgApiId: 'sv1-240',
    number: '240',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/240.png","large":"https://images.pokemontcg.io/sv1/240_hires.png"}',
    searchName: "Professor's Research (Professor Sada) (SVI 240)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: "Professor's Research (Professor Turo)",
    tcgApiId: 'sv1-241',
    number: '241',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/241.png","large":"https://images.pokemontcg.io/sv1/241_hires.png"}',
    searchName: "Professor's Research (Professor Turo) (SVI 241)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Team Star Grunt',
    tcgApiId: 'sv1-242',
    number: '242',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/242.png","large":"https://images.pokemontcg.io/sv1/242_hires.png"}',
    searchName: 'Team Star Grunt (SVI 242)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Spidops ex',
    tcgApiId: 'sv1-243',
    number: '243',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/243.png","large":"https://images.pokemontcg.io/sv1/243_hires.png"}',
    searchName: 'Spidops ex (SVI 243)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Miraidon ex',
    tcgApiId: 'sv1-244',
    number: '244',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/244.png","large":"https://images.pokemontcg.io/sv1/244_hires.png"}',
    searchName: 'Miraidon ex (SVI 244)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Gardevoir ex',
    tcgApiId: 'sv1-245',
    number: '245',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/245.png","large":"https://images.pokemontcg.io/sv1/245_hires.png"}',
    searchName: 'Gardevoir ex (SVI 245)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Great Tusk ex',
    tcgApiId: 'sv1-246',
    number: '246',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/246.png","large":"https://images.pokemontcg.io/sv1/246_hires.png"}',
    searchName: 'Great Tusk ex (SVI 246)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Koraidon ex',
    tcgApiId: 'sv1-247',
    number: '247',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/247.png","large":"https://images.pokemontcg.io/sv1/247_hires.png"}',
    searchName: 'Koraidon ex (SVI 247)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Iron Treads ex',
    tcgApiId: 'sv1-248',
    number: '248',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/248.png","large":"https://images.pokemontcg.io/sv1/248_hires.png"}',
    searchName: 'Iron Treads ex (SVI 248)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Arven',
    tcgApiId: 'sv1-249',
    number: '249',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/249.png","large":"https://images.pokemontcg.io/sv1/249_hires.png"}',
    searchName: 'Arven (SVI 249)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Jacq',
    tcgApiId: 'sv1-250',
    number: '250',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/250.png","large":"https://images.pokemontcg.io/sv1/250_hires.png"}',
    searchName: 'Jacq (SVI 250)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Miriam',
    tcgApiId: 'sv1-251',
    number: '251',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/251.png","large":"https://images.pokemontcg.io/sv1/251_hires.png"}',
    searchName: 'Miriam (SVI 251)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Penny',
    tcgApiId: 'sv1-252',
    number: '252',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/252.png","large":"https://images.pokemontcg.io/sv1/252_hires.png"}',
    searchName: 'Penny (SVI 252)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Miraidon ex',
    tcgApiId: 'sv1-253',
    number: '253',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/253.png","large":"https://images.pokemontcg.io/sv1/253_hires.png"}',
    searchName: 'Miraidon ex (SVI 253)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Koraidon ex',
    tcgApiId: 'sv1-254',
    number: '254',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/254.png","large":"https://images.pokemontcg.io/sv1/254_hires.png"}',
    searchName: 'Koraidon ex (SVI 254)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Nest Ball',
    tcgApiId: 'sv1-255',
    number: '255',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/255.png","large":"https://images.pokemontcg.io/sv1/255_hires.png"}',
    searchName: 'Nest Ball (SVI 255)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Rare Candy',
    tcgApiId: 'sv1-256',
    number: '256',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/256.png","large":"https://images.pokemontcg.io/sv1/256_hires.png"}',
    searchName: 'Rare Candy (SVI 256)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Basic Lightning Energy',
    tcgApiId: 'sv1-257',
    number: '257',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/257.png","large":"https://images.pokemontcg.io/sv1/257_hires.png"}',
    searchName: 'Basic Lightning Energy (SVI 257)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv1',
    name: 'Basic Fighting Energy',
    tcgApiId: 'sv1-258',
    number: '258',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv1/258.png","large":"https://images.pokemontcg.io/sv1/258_hires.png"}',
    searchName: 'Basic Fighting Energy (SVI 258)',
  },
];
