export const cardSeedSv3 = [
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Oddish',
    tcgApiId: 'sv3-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/1.png","large":"https://images.pokemontcg.io/sv3/1_hires.png"}',
    searchName: 'Oddish (OBF 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Gloom',
    tcgApiId: 'sv3-2',
    number: '2',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/2.png","large":"https://images.pokemontcg.io/sv3/2_hires.png"}',
    searchName: 'Gloom (OBF 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bellossom',
    tcgApiId: 'sv3-3',
    number: '3',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/3.png","large":"https://images.pokemontcg.io/sv3/3_hires.png"}',
    searchName: 'Bellossom (OBF 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Scyther',
    tcgApiId: 'sv3-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/4.png","large":"https://images.pokemontcg.io/sv3/4_hires.png"}',
    searchName: 'Scyther (OBF 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Shuckle',
    tcgApiId: 'sv3-5',
    number: '5',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/5.png","large":"https://images.pokemontcg.io/sv3/5_hires.png"}',
    searchName: 'Shuckle (OBF 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Surskit',
    tcgApiId: 'sv3-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/6.png","large":"https://images.pokemontcg.io/sv3/6_hires.png"}',
    searchName: 'Surskit (OBF 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Masquerain',
    tcgApiId: 'sv3-7',
    number: '7',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/7.png","large":"https://images.pokemontcg.io/sv3/7_hires.png"}',
    searchName: 'Masquerain (OBF 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Combee',
    tcgApiId: 'sv3-8',
    number: '8',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/8.png","large":"https://images.pokemontcg.io/sv3/8_hires.png"}',
    searchName: 'Combee (OBF 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Foongus',
    tcgApiId: 'sv3-9',
    number: '9',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/9.png","large":"https://images.pokemontcg.io/sv3/9_hires.png"}',
    searchName: 'Foongus (OBF 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Amoonguss',
    tcgApiId: 'sv3-10',
    number: '10',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/10.png","large":"https://images.pokemontcg.io/sv3/10_hires.png"}',
    searchName: 'Amoonguss (OBF 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Phantump',
    tcgApiId: 'sv3-11',
    number: '11',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/11.png","large":"https://images.pokemontcg.io/sv3/11_hires.png"}',
    searchName: 'Phantump (OBF 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Trevenant',
    tcgApiId: 'sv3-12',
    number: '12',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/12.png","large":"https://images.pokemontcg.io/sv3/12_hires.png"}',
    searchName: 'Trevenant (OBF 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Rowlet',
    tcgApiId: 'sv3-13',
    number: '13',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/13.png","large":"https://images.pokemontcg.io/sv3/13_hires.png"}',
    searchName: 'Rowlet (OBF 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Dartrix',
    tcgApiId: 'sv3-14',
    number: '14',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/14.png","large":"https://images.pokemontcg.io/sv3/14_hires.png"}',
    searchName: 'Dartrix (OBF 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Decidueye ex',
    tcgApiId: 'sv3-15',
    number: '15',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/15.png","large":"https://images.pokemontcg.io/sv3/15_hires.png"}',
    searchName: 'Decidueye ex (OBF 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bounsweet',
    tcgApiId: 'sv3-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/16.png","large":"https://images.pokemontcg.io/sv3/16_hires.png"}',
    searchName: 'Bounsweet (OBF 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Steenee',
    tcgApiId: 'sv3-17',
    number: '17',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/17.png","large":"https://images.pokemontcg.io/sv3/17_hires.png"}',
    searchName: 'Steenee (OBF 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Tsareena',
    tcgApiId: 'sv3-18',
    number: '18',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/18.png","large":"https://images.pokemontcg.io/sv3/18_hires.png"}',
    searchName: 'Tsareena (OBF 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Smoliv',
    tcgApiId: 'sv3-19',
    number: '19',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/19.png","large":"https://images.pokemontcg.io/sv3/19_hires.png"}',
    searchName: 'Smoliv (OBF 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Dolliv',
    tcgApiId: 'sv3-20',
    number: '20',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/20.png","large":"https://images.pokemontcg.io/sv3/20_hires.png"}',
    searchName: 'Dolliv (OBF 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Arboliva',
    tcgApiId: 'sv3-21',
    number: '21',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/21.png","large":"https://images.pokemontcg.io/sv3/21_hires.png"}',
    searchName: 'Arboliva (OBF 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Toedscruel ex',
    tcgApiId: 'sv3-22',
    number: '22',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/22.png","large":"https://images.pokemontcg.io/sv3/22_hires.png"}',
    searchName: 'Toedscruel ex (OBF 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Capsakid',
    tcgApiId: 'sv3-23',
    number: '23',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/23.png","large":"https://images.pokemontcg.io/sv3/23_hires.png"}',
    searchName: 'Capsakid (OBF 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Capsakid',
    tcgApiId: 'sv3-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/24.png","large":"https://images.pokemontcg.io/sv3/24_hires.png"}',
    searchName: 'Capsakid (OBF 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Scovillain',
    tcgApiId: 'sv3-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/25.png","large":"https://images.pokemontcg.io/sv3/25_hires.png"}',
    searchName: 'Scovillain (OBF 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Charmander',
    tcgApiId: 'sv3-26',
    number: '26',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/26.png","large":"https://images.pokemontcg.io/sv3/26_hires.png"}',
    searchName: 'Charmander (OBF 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Charmeleon',
    tcgApiId: 'sv3-27',
    number: '27',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/27.png","large":"https://images.pokemontcg.io/sv3/27_hires.png"}',
    searchName: 'Charmeleon (OBF 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Vulpix',
    tcgApiId: 'sv3-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/28.png","large":"https://images.pokemontcg.io/sv3/28_hires.png"}',
    searchName: 'Vulpix (OBF 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Ninetales',
    tcgApiId: 'sv3-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/29.png","large":"https://images.pokemontcg.io/sv3/29_hires.png"}',
    searchName: 'Ninetales (OBF 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Entei',
    tcgApiId: 'sv3-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/30.png","large":"https://images.pokemontcg.io/sv3/30_hires.png"}',
    searchName: 'Entei (OBF 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Numel',
    tcgApiId: 'sv3-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/31.png","large":"https://images.pokemontcg.io/sv3/31_hires.png"}',
    searchName: 'Numel (OBF 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Camerupt',
    tcgApiId: 'sv3-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/32.png","large":"https://images.pokemontcg.io/sv3/32_hires.png"}',
    searchName: 'Camerupt (OBF 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Victini ex',
    tcgApiId: 'sv3-33',
    number: '33',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/33.png","large":"https://images.pokemontcg.io/sv3/33_hires.png"}',
    searchName: 'Victini ex (OBF 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Darumaka',
    tcgApiId: 'sv3-34',
    number: '34',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/34.png","large":"https://images.pokemontcg.io/sv3/34_hires.png"}',
    searchName: 'Darumaka (OBF 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Darmanitan',
    tcgApiId: 'sv3-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/35.png","large":"https://images.pokemontcg.io/sv3/35_hires.png"}',
    searchName: 'Darmanitan (OBF 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Litwick',
    tcgApiId: 'sv3-36',
    number: '36',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/36.png","large":"https://images.pokemontcg.io/sv3/36_hires.png"}',
    searchName: 'Litwick (OBF 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Lampent',
    tcgApiId: 'sv3-37',
    number: '37',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/37.png","large":"https://images.pokemontcg.io/sv3/37_hires.png"}',
    searchName: 'Lampent (OBF 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Chandelure',
    tcgApiId: 'sv3-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/38.png","large":"https://images.pokemontcg.io/sv3/38_hires.png"}',
    searchName: 'Chandelure (OBF 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Heatmor',
    tcgApiId: 'sv3-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/39.png","large":"https://images.pokemontcg.io/sv3/39_hires.png"}',
    searchName: 'Heatmor (OBF 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Larvesta',
    tcgApiId: 'sv3-40',
    number: '40',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/40.png","large":"https://images.pokemontcg.io/sv3/40_hires.png"}',
    searchName: 'Larvesta (OBF 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Volcarona',
    tcgApiId: 'sv3-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/41.png","large":"https://images.pokemontcg.io/sv3/41_hires.png"}',
    searchName: 'Volcarona (OBF 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Eiscue ex',
    tcgApiId: 'sv3-42',
    number: '42',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/42.png","large":"https://images.pokemontcg.io/sv3/42_hires.png"}',
    searchName: 'Eiscue ex (OBF 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Charcadet',
    tcgApiId: 'sv3-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/43.png","large":"https://images.pokemontcg.io/sv3/43_hires.png"}',
    searchName: 'Charcadet (OBF 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Armarouge',
    tcgApiId: 'sv3-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/44.png","large":"https://images.pokemontcg.io/sv3/44_hires.png"}',
    searchName: 'Armarouge (OBF 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Lapras',
    tcgApiId: 'sv3-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/45.png","large":"https://images.pokemontcg.io/sv3/45_hires.png"}',
    searchName: 'Lapras (OBF 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Carvanha',
    tcgApiId: 'sv3-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/46.png","large":"https://images.pokemontcg.io/sv3/46_hires.png"}',
    searchName: 'Carvanha (OBF 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Sharpedo',
    tcgApiId: 'sv3-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/47.png","large":"https://images.pokemontcg.io/sv3/47_hires.png"}',
    searchName: 'Sharpedo (OBF 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Buizel',
    tcgApiId: 'sv3-48',
    number: '48',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/48.png","large":"https://images.pokemontcg.io/sv3/48_hires.png"}',
    searchName: 'Buizel (OBF 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Floatzel',
    tcgApiId: 'sv3-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/49.png","large":"https://images.pokemontcg.io/sv3/49_hires.png"}',
    searchName: 'Floatzel (OBF 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Tympole',
    tcgApiId: 'sv3-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/50.png","large":"https://images.pokemontcg.io/sv3/50_hires.png"}',
    searchName: 'Tympole (OBF 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Palpitoad',
    tcgApiId: 'sv3-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/51.png","large":"https://images.pokemontcg.io/sv3/51_hires.png"}',
    searchName: 'Palpitoad (OBF 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Seismitoad',
    tcgApiId: 'sv3-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/52.png","large":"https://images.pokemontcg.io/sv3/52_hires.png"}',
    searchName: 'Seismitoad (OBF 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Cubchoo',
    tcgApiId: 'sv3-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/53.png","large":"https://images.pokemontcg.io/sv3/53_hires.png"}',
    searchName: 'Cubchoo (OBF 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Beartic',
    tcgApiId: 'sv3-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/54.png","large":"https://images.pokemontcg.io/sv3/54_hires.png"}',
    searchName: 'Beartic (OBF 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Cryogonal',
    tcgApiId: 'sv3-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/55.png","large":"https://images.pokemontcg.io/sv3/55_hires.png"}',
    searchName: 'Cryogonal (OBF 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Froakie',
    tcgApiId: 'sv3-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/56.png","large":"https://images.pokemontcg.io/sv3/56_hires.png"}',
    searchName: 'Froakie (OBF 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Frogadier',
    tcgApiId: 'sv3-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/57.png","large":"https://images.pokemontcg.io/sv3/57_hires.png"}',
    searchName: 'Frogadier (OBF 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Wiglett',
    tcgApiId: 'sv3-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/58.png","large":"https://images.pokemontcg.io/sv3/58_hires.png"}',
    searchName: 'Wiglett (OBF 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Wugtrio',
    tcgApiId: 'sv3-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/59.png","large":"https://images.pokemontcg.io/sv3/59_hires.png"}',
    searchName: 'Wugtrio (OBF 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Finizen',
    tcgApiId: 'sv3-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/60.png","large":"https://images.pokemontcg.io/sv3/60_hires.png"}',
    searchName: 'Finizen (OBF 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Finizen',
    tcgApiId: 'sv3-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/61.png","large":"https://images.pokemontcg.io/sv3/61_hires.png"}',
    searchName: 'Finizen (OBF 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Palafin',
    tcgApiId: 'sv3-62',
    number: '62',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/62.png","large":"https://images.pokemontcg.io/sv3/62_hires.png"}',
    searchName: 'Palafin (OBF 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Magnemite',
    tcgApiId: 'sv3-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/63.png","large":"https://images.pokemontcg.io/sv3/63_hires.png"}',
    searchName: 'Magnemite (OBF 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Magneton',
    tcgApiId: 'sv3-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/64.png","large":"https://images.pokemontcg.io/sv3/64_hires.png"}',
    searchName: 'Magneton (OBF 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Magnezone',
    tcgApiId: 'sv3-65',
    number: '65',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/65.png","large":"https://images.pokemontcg.io/sv3/65_hires.png"}',
    searchName: 'Magnezone (OBF 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Tyranitar ex',
    tcgApiId: 'sv3-66',
    number: '66',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/66.png","large":"https://images.pokemontcg.io/sv3/66_hires.png"}',
    searchName: 'Tyranitar ex (OBF 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Tynamo',
    tcgApiId: 'sv3-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/67.png","large":"https://images.pokemontcg.io/sv3/67_hires.png"}',
    searchName: 'Tynamo (OBF 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Eelektrik',
    tcgApiId: 'sv3-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/68.png","large":"https://images.pokemontcg.io/sv3/68_hires.png"}',
    searchName: 'Eelektrik (OBF 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Eelektross',
    tcgApiId: 'sv3-69',
    number: '69',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/69.png","large":"https://images.pokemontcg.io/sv3/69_hires.png"}',
    searchName: 'Eelektross (OBF 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Thundurus',
    tcgApiId: 'sv3-70',
    number: '70',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/70.png","large":"https://images.pokemontcg.io/sv3/70_hires.png"}',
    searchName: 'Thundurus (OBF 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Toxel',
    tcgApiId: 'sv3-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/71.png","large":"https://images.pokemontcg.io/sv3/71_hires.png"}',
    searchName: 'Toxel (OBF 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Toxtricity',
    tcgApiId: 'sv3-72',
    number: '72',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/72.png","large":"https://images.pokemontcg.io/sv3/72_hires.png"}',
    searchName: 'Toxtricity (OBF 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pawmot ex',
    tcgApiId: 'sv3-73',
    number: '73',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/73.png","large":"https://images.pokemontcg.io/sv3/73_hires.png"}',
    searchName: 'Pawmot ex (OBF 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Tadbulb',
    tcgApiId: 'sv3-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/74.png","large":"https://images.pokemontcg.io/sv3/74_hires.png"}',
    searchName: 'Tadbulb (OBF 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Tadbulb',
    tcgApiId: 'sv3-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/75.png","large":"https://images.pokemontcg.io/sv3/75_hires.png"}',
    searchName: 'Tadbulb (OBF 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Tadbulb',
    tcgApiId: 'sv3-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/76.png","large":"https://images.pokemontcg.io/sv3/76_hires.png"}',
    searchName: 'Tadbulb (OBF 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bellibolt',
    tcgApiId: 'sv3-77',
    number: '77',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/77.png","large":"https://images.pokemontcg.io/sv3/77_hires.png"}',
    searchName: 'Bellibolt (OBF 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bellibolt',
    tcgApiId: 'sv3-78',
    number: '78',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/78.png","large":"https://images.pokemontcg.io/sv3/78_hires.png"}',
    searchName: 'Bellibolt (OBF 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Miraidon ex',
    tcgApiId: 'sv3-79',
    number: '79',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/79.png","large":"https://images.pokemontcg.io/sv3/79_hires.png"}',
    searchName: 'Miraidon ex (OBF 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Cleffa',
    tcgApiId: 'sv3-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/80.png","large":"https://images.pokemontcg.io/sv3/80_hires.png"}',
    searchName: 'Cleffa (OBF 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Clefairy',
    tcgApiId: 'sv3-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/81.png","large":"https://images.pokemontcg.io/sv3/81_hires.png"}',
    searchName: 'Clefairy (OBF 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Clefable ex',
    tcgApiId: 'sv3-82',
    number: '82',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/82.png","large":"https://images.pokemontcg.io/sv3/82_hires.png"}',
    searchName: 'Clefable ex (OBF 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Togepi',
    tcgApiId: 'sv3-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/83.png","large":"https://images.pokemontcg.io/sv3/83_hires.png"}',
    searchName: 'Togepi (OBF 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Togetic',
    tcgApiId: 'sv3-84',
    number: '84',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/84.png","large":"https://images.pokemontcg.io/sv3/84_hires.png"}',
    searchName: 'Togetic (OBF 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Togekiss',
    tcgApiId: 'sv3-85',
    number: '85',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/85.png","large":"https://images.pokemontcg.io/sv3/85_hires.png"}',
    searchName: 'Togekiss (OBF 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Espeon',
    tcgApiId: 'sv3-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/86.png","large":"https://images.pokemontcg.io/sv3/86_hires.png"}',
    searchName: 'Espeon (OBF 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Snubbull',
    tcgApiId: 'sv3-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/87.png","large":"https://images.pokemontcg.io/sv3/87_hires.png"}',
    searchName: 'Snubbull (OBF 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Granbull',
    tcgApiId: 'sv3-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/88.png","large":"https://images.pokemontcg.io/sv3/88_hires.png"}',
    searchName: 'Granbull (OBF 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Mawile',
    tcgApiId: 'sv3-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/89.png","large":"https://images.pokemontcg.io/sv3/89_hires.png"}',
    searchName: 'Mawile (OBF 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Spoink',
    tcgApiId: 'sv3-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/90.png","large":"https://images.pokemontcg.io/sv3/90_hires.png"}',
    searchName: 'Spoink (OBF 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Grumpig',
    tcgApiId: 'sv3-91',
    number: '91',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/91.png","large":"https://images.pokemontcg.io/sv3/91_hires.png"}',
    searchName: 'Grumpig (OBF 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Lunatone',
    tcgApiId: 'sv3-92',
    number: '92',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/92.png","large":"https://images.pokemontcg.io/sv3/92_hires.png"}',
    searchName: 'Lunatone (OBF 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Solrock',
    tcgApiId: 'sv3-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/93.png","large":"https://images.pokemontcg.io/sv3/93_hires.png"}',
    searchName: 'Solrock (OBF 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Baltoy',
    tcgApiId: 'sv3-94',
    number: '94',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/94.png","large":"https://images.pokemontcg.io/sv3/94_hires.png"}',
    searchName: 'Baltoy (OBF 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Claydol',
    tcgApiId: 'sv3-95',
    number: '95',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/95.png","large":"https://images.pokemontcg.io/sv3/95_hires.png"}',
    searchName: 'Claydol (OBF 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Vespiquen ex',
    tcgApiId: 'sv3-96',
    number: '96',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/96.png","large":"https://images.pokemontcg.io/sv3/96_hires.png"}',
    searchName: 'Vespiquen ex (OBF 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Sinistea',
    tcgApiId: 'sv3-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/97.png","large":"https://images.pokemontcg.io/sv3/97_hires.png"}',
    searchName: 'Sinistea (OBF 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Polteageist',
    tcgApiId: 'sv3-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/98.png","large":"https://images.pokemontcg.io/sv3/98_hires.png"}',
    searchName: 'Polteageist (OBF 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Greavard',
    tcgApiId: 'sv3-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/99.png","large":"https://images.pokemontcg.io/sv3/99_hires.png"}',
    searchName: 'Greavard (OBF 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Greavard',
    tcgApiId: 'sv3-100',
    number: '100',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/100.png","large":"https://images.pokemontcg.io/sv3/100_hires.png"}',
    searchName: 'Greavard (OBF 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Houndstone',
    tcgApiId: 'sv3-101',
    number: '101',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/101.png","large":"https://images.pokemontcg.io/sv3/101_hires.png"}',
    searchName: 'Houndstone (OBF 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Houndstone ex',
    tcgApiId: 'sv3-102',
    number: '102',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/102.png","large":"https://images.pokemontcg.io/sv3/102_hires.png"}',
    searchName: 'Houndstone ex (OBF 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Diglett',
    tcgApiId: 'sv3-103',
    number: '103',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/103.png","large":"https://images.pokemontcg.io/sv3/103_hires.png"}',
    searchName: 'Diglett (OBF 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Dugtrio',
    tcgApiId: 'sv3-104',
    number: '104',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/104.png","large":"https://images.pokemontcg.io/sv3/104_hires.png"}',
    searchName: 'Dugtrio (OBF 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Larvitar',
    tcgApiId: 'sv3-105',
    number: '105',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/105.png","large":"https://images.pokemontcg.io/sv3/105_hires.png"}',
    searchName: 'Larvitar (OBF 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pupitar',
    tcgApiId: 'sv3-106',
    number: '106',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/106.png","large":"https://images.pokemontcg.io/sv3/106_hires.png"}',
    searchName: 'Pupitar (OBF 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Nosepass',
    tcgApiId: 'sv3-107',
    number: '107',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/107.png","large":"https://images.pokemontcg.io/sv3/107_hires.png"}',
    searchName: 'Nosepass (OBF 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Barboach',
    tcgApiId: 'sv3-108',
    number: '108',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/108.png","large":"https://images.pokemontcg.io/sv3/108_hires.png"}',
    searchName: 'Barboach (OBF 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Whiscash',
    tcgApiId: 'sv3-109',
    number: '109',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/109.png","large":"https://images.pokemontcg.io/sv3/109_hires.png"}',
    searchName: 'Whiscash (OBF 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bonsly',
    tcgApiId: 'sv3-110',
    number: '110',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/110.png","large":"https://images.pokemontcg.io/sv3/110_hires.png"}',
    searchName: 'Bonsly (OBF 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Drilbur',
    tcgApiId: 'sv3-111',
    number: '111',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/111.png","large":"https://images.pokemontcg.io/sv3/111_hires.png"}',
    searchName: 'Drilbur (OBF 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Stunfisk',
    tcgApiId: 'sv3-112',
    number: '112',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/112.png","large":"https://images.pokemontcg.io/sv3/112_hires.png"}',
    searchName: 'Stunfisk (OBF 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Diggersby',
    tcgApiId: 'sv3-113',
    number: '113',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/113.png","large":"https://images.pokemontcg.io/sv3/113_hires.png"}',
    searchName: 'Diggersby (OBF 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Crabrawler',
    tcgApiId: 'sv3-114',
    number: '114',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/114.png","large":"https://images.pokemontcg.io/sv3/114_hires.png"}',
    searchName: 'Crabrawler (OBF 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Crabominable',
    tcgApiId: 'sv3-115',
    number: '115',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/115.png","large":"https://images.pokemontcg.io/sv3/115_hires.png"}',
    searchName: 'Crabominable (OBF 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Rockruff',
    tcgApiId: 'sv3-116',
    number: '116',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/116.png","large":"https://images.pokemontcg.io/sv3/116_hires.png"}',
    searchName: 'Rockruff (OBF 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Lycanroc',
    tcgApiId: 'sv3-117',
    number: '117',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/117.png","large":"https://images.pokemontcg.io/sv3/117_hires.png"}',
    searchName: 'Lycanroc (OBF 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Toedscool',
    tcgApiId: 'sv3-118',
    number: '118',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/118.png","large":"https://images.pokemontcg.io/sv3/118_hires.png"}',
    searchName: 'Toedscool (OBF 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Toedscruel',
    tcgApiId: 'sv3-119',
    number: '119',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/119.png","large":"https://images.pokemontcg.io/sv3/119_hires.png"}',
    searchName: 'Toedscruel (OBF 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Klawf ex',
    tcgApiId: 'sv3-120',
    number: '120',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/120.png","large":"https://images.pokemontcg.io/sv3/120_hires.png"}',
    searchName: 'Klawf ex (OBF 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Glimmet',
    tcgApiId: 'sv3-121',
    number: '121',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/121.png","large":"https://images.pokemontcg.io/sv3/121_hires.png"}',
    searchName: 'Glimmet (OBF 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Glimmet',
    tcgApiId: 'sv3-122',
    number: '122',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/122.png","large":"https://images.pokemontcg.io/sv3/122_hires.png"}',
    searchName: 'Glimmet (OBF 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Glimmora ex',
    tcgApiId: 'sv3-123',
    number: '123',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/123.png","large":"https://images.pokemontcg.io/sv3/123_hires.png"}',
    searchName: 'Glimmora ex (OBF 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Koraidon ex',
    tcgApiId: 'sv3-124',
    number: '124',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/124.png","large":"https://images.pokemontcg.io/sv3/124_hires.png"}',
    searchName: 'Koraidon ex (OBF 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Charizard ex',
    tcgApiId: 'sv3-125',
    number: '125',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/125.png","large":"https://images.pokemontcg.io/sv3/125_hires.png"}',
    searchName: 'Charizard ex (OBF 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Paldean Wooper',
    tcgApiId: 'sv3-126',
    number: '126',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/126.png","large":"https://images.pokemontcg.io/sv3/126_hires.png"}',
    searchName: 'Paldean Wooper (OBF 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Paldean Wooper',
    tcgApiId: 'sv3-127',
    number: '127',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/127.png","large":"https://images.pokemontcg.io/sv3/127_hires.png"}',
    searchName: 'Paldean Wooper (OBF 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Paldean Clodsire',
    tcgApiId: 'sv3-128',
    number: '128',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/128.png","large":"https://images.pokemontcg.io/sv3/128_hires.png"}',
    searchName: 'Paldean Clodsire (OBF 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Paldean Clodsire',
    tcgApiId: 'sv3-129',
    number: '129',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/129.png","large":"https://images.pokemontcg.io/sv3/129_hires.png"}',
    searchName: 'Paldean Clodsire (OBF 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Umbreon',
    tcgApiId: 'sv3-130',
    number: '130',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/130.png","large":"https://images.pokemontcg.io/sv3/130_hires.png"}',
    searchName: 'Umbreon (OBF 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Houndour',
    tcgApiId: 'sv3-131',
    number: '131',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/131.png","large":"https://images.pokemontcg.io/sv3/131_hires.png"}',
    searchName: 'Houndour (OBF 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Houndour',
    tcgApiId: 'sv3-132',
    number: '132',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/132.png","large":"https://images.pokemontcg.io/sv3/132_hires.png"}',
    searchName: 'Houndour (OBF 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Houndoom',
    tcgApiId: 'sv3-133',
    number: '133',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/133.png","large":"https://images.pokemontcg.io/sv3/133_hires.png"}',
    searchName: 'Houndoom (OBF 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Houndoom ex',
    tcgApiId: 'sv3-134',
    number: '134',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/134.png","large":"https://images.pokemontcg.io/sv3/134_hires.png"}',
    searchName: 'Houndoom ex (OBF 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Absol ex',
    tcgApiId: 'sv3-135',
    number: '135',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/135.png","large":"https://images.pokemontcg.io/sv3/135_hires.png"}',
    searchName: 'Absol ex (OBF 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Darkrai',
    tcgApiId: 'sv3-136',
    number: '136',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/136.png","large":"https://images.pokemontcg.io/sv3/136_hires.png"}',
    searchName: 'Darkrai (OBF 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Inkay',
    tcgApiId: 'sv3-137',
    number: '137',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/137.png","large":"https://images.pokemontcg.io/sv3/137_hires.png"}',
    searchName: 'Inkay (OBF 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Malamar',
    tcgApiId: 'sv3-138',
    number: '138',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/138.png","large":"https://images.pokemontcg.io/sv3/138_hires.png"}',
    searchName: 'Malamar (OBF 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Salandit',
    tcgApiId: 'sv3-139',
    number: '139',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/139.png","large":"https://images.pokemontcg.io/sv3/139_hires.png"}',
    searchName: 'Salandit (OBF 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Salazzle',
    tcgApiId: 'sv3-140',
    number: '140',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/140.png","large":"https://images.pokemontcg.io/sv3/140_hires.png"}',
    searchName: 'Salazzle (OBF 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Scizor',
    tcgApiId: 'sv3-141',
    number: '141',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/141.png","large":"https://images.pokemontcg.io/sv3/141_hires.png"}',
    searchName: 'Scizor (OBF 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Skarmory',
    tcgApiId: 'sv3-142',
    number: '142',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/142.png","large":"https://images.pokemontcg.io/sv3/142_hires.png"}',
    searchName: 'Skarmory (OBF 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Mawile',
    tcgApiId: 'sv3-143',
    number: '143',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/143.png","large":"https://images.pokemontcg.io/sv3/143_hires.png"}',
    searchName: 'Mawile (OBF 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bronzor',
    tcgApiId: 'sv3-144',
    number: '144',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/144.png","large":"https://images.pokemontcg.io/sv3/144_hires.png"}',
    searchName: 'Bronzor (OBF 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bronzong',
    tcgApiId: 'sv3-145',
    number: '145',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/145.png","large":"https://images.pokemontcg.io/sv3/145_hires.png"}',
    searchName: 'Bronzong (OBF 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Probopass',
    tcgApiId: 'sv3-146',
    number: '146',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/146.png","large":"https://images.pokemontcg.io/sv3/146_hires.png"}',
    searchName: 'Probopass (OBF 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Excadrill',
    tcgApiId: 'sv3-147',
    number: '147',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/147.png","large":"https://images.pokemontcg.io/sv3/147_hires.png"}',
    searchName: 'Excadrill (OBF 147)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pawniard',
    tcgApiId: 'sv3-148',
    number: '148',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/148.png","large":"https://images.pokemontcg.io/sv3/148_hires.png"}',
    searchName: 'Pawniard (OBF 148)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bisharp',
    tcgApiId: 'sv3-149',
    number: '149',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/149.png","large":"https://images.pokemontcg.io/sv3/149_hires.png"}',
    searchName: 'Bisharp (OBF 149)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Kingambit',
    tcgApiId: 'sv3-150',
    number: '150',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/150.png","large":"https://images.pokemontcg.io/sv3/150_hires.png"}',
    searchName: 'Kingambit (OBF 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Togedemaru',
    tcgApiId: 'sv3-151',
    number: '151',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/151.png","large":"https://images.pokemontcg.io/sv3/151_hires.png"}',
    searchName: 'Togedemaru (OBF 151)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Meltan',
    tcgApiId: 'sv3-152',
    number: '152',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/152.png","large":"https://images.pokemontcg.io/sv3/152_hires.png"}',
    searchName: 'Meltan (OBF 152)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Melmetal ex',
    tcgApiId: 'sv3-153',
    number: '153',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/153.png","large":"https://images.pokemontcg.io/sv3/153_hires.png"}',
    searchName: 'Melmetal ex (OBF 153)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Varoom',
    tcgApiId: 'sv3-154',
    number: '154',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/154.png","large":"https://images.pokemontcg.io/sv3/154_hires.png"}',
    searchName: 'Varoom (OBF 154)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Varoom',
    tcgApiId: 'sv3-155',
    number: '155',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/155.png","large":"https://images.pokemontcg.io/sv3/155_hires.png"}',
    searchName: 'Varoom (OBF 155)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Revavroom ex',
    tcgApiId: 'sv3-156',
    number: '156',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/156.png","large":"https://images.pokemontcg.io/sv3/156_hires.png"}',
    searchName: 'Revavroom ex (OBF 156)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Dratini',
    tcgApiId: 'sv3-157',
    number: '157',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/157.png","large":"https://images.pokemontcg.io/sv3/157_hires.png"}',
    searchName: 'Dratini (OBF 157)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Dragonair',
    tcgApiId: 'sv3-158',
    number: '158',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/158.png","large":"https://images.pokemontcg.io/sv3/158_hires.png"}',
    searchName: 'Dragonair (OBF 158)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Dragonite ex',
    tcgApiId: 'sv3-159',
    number: '159',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/159.png","large":"https://images.pokemontcg.io/sv3/159_hires.png"}',
    searchName: 'Dragonite ex (OBF 159)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Altaria',
    tcgApiId: 'sv3-160',
    number: '160',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/160.png","large":"https://images.pokemontcg.io/sv3/160_hires.png"}',
    searchName: 'Altaria (OBF 160)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Drampa',
    tcgApiId: 'sv3-161',
    number: '161',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/161.png","large":"https://images.pokemontcg.io/sv3/161_hires.png"}',
    searchName: 'Drampa (OBF 161)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pidgey',
    tcgApiId: 'sv3-162',
    number: '162',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/162.png","large":"https://images.pokemontcg.io/sv3/162_hires.png"}',
    searchName: 'Pidgey (OBF 162)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pidgeotto',
    tcgApiId: 'sv3-163',
    number: '163',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/163.png","large":"https://images.pokemontcg.io/sv3/163_hires.png"}',
    searchName: 'Pidgeotto (OBF 163)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pidgeot ex',
    tcgApiId: 'sv3-164',
    number: '164',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/164.png","large":"https://images.pokemontcg.io/sv3/164_hires.png"}',
    searchName: 'Pidgeot ex (OBF 164)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Kangaskhan',
    tcgApiId: 'sv3-165',
    number: '165',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/165.png","large":"https://images.pokemontcg.io/sv3/165_hires.png"}',
    searchName: 'Kangaskhan (OBF 165)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Eevee',
    tcgApiId: 'sv3-166',
    number: '166',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/166.png","large":"https://images.pokemontcg.io/sv3/166_hires.png"}',
    searchName: 'Eevee (OBF 166)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Zigzagoon',
    tcgApiId: 'sv3-167',
    number: '167',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/167.png","large":"https://images.pokemontcg.io/sv3/167_hires.png"}',
    searchName: 'Zigzagoon (OBF 167)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Linoone',
    tcgApiId: 'sv3-168',
    number: '168',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/168.png","large":"https://images.pokemontcg.io/sv3/168_hires.png"}',
    searchName: 'Linoone (OBF 168)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Swablu',
    tcgApiId: 'sv3-169',
    number: '169',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/169.png","large":"https://images.pokemontcg.io/sv3/169_hires.png"}',
    searchName: 'Swablu (OBF 169)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Lillipup',
    tcgApiId: 'sv3-170',
    number: '170',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/170.png","large":"https://images.pokemontcg.io/sv3/170_hires.png"}',
    searchName: 'Lillipup (OBF 170)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Herdier',
    tcgApiId: 'sv3-171',
    number: '171',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/171.png","large":"https://images.pokemontcg.io/sv3/171_hires.png"}',
    searchName: 'Herdier (OBF 171)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Stoutland',
    tcgApiId: 'sv3-172',
    number: '172',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/172.png","large":"https://images.pokemontcg.io/sv3/172_hires.png"}',
    searchName: 'Stoutland (OBF 172)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Audino',
    tcgApiId: 'sv3-173',
    number: '173',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/173.png","large":"https://images.pokemontcg.io/sv3/173_hires.png"}',
    searchName: 'Audino (OBF 173)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bouffalant',
    tcgApiId: 'sv3-174',
    number: '174',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/174.png","large":"https://images.pokemontcg.io/sv3/174_hires.png"}',
    searchName: 'Bouffalant (OBF 174)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bunnelby',
    tcgApiId: 'sv3-175',
    number: '175',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/175.png","large":"https://images.pokemontcg.io/sv3/175_hires.png"}',
    searchName: 'Bunnelby (OBF 175)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Yungoos',
    tcgApiId: 'sv3-176',
    number: '176',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/176.png","large":"https://images.pokemontcg.io/sv3/176_hires.png"}',
    searchName: 'Yungoos (OBF 176)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Gumshoos',
    tcgApiId: 'sv3-177',
    number: '177',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/177.png","large":"https://images.pokemontcg.io/sv3/177_hires.png"}',
    searchName: 'Gumshoos (OBF 177)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Skwovet',
    tcgApiId: 'sv3-178',
    number: '178',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/178.png","large":"https://images.pokemontcg.io/sv3/178_hires.png"}',
    searchName: 'Skwovet (OBF 178)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Greedent ex',
    tcgApiId: 'sv3-179',
    number: '179',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/179.png","large":"https://images.pokemontcg.io/sv3/179_hires.png"}',
    searchName: 'Greedent ex (OBF 179)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Lechonk',
    tcgApiId: 'sv3-180',
    number: '180',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/180.png","large":"https://images.pokemontcg.io/sv3/180_hires.png"}',
    searchName: 'Lechonk (OBF 180)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Lechonk',
    tcgApiId: 'sv3-181',
    number: '181',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/181.png","large":"https://images.pokemontcg.io/sv3/181_hires.png"}',
    searchName: 'Lechonk (OBF 181)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Lechonk',
    tcgApiId: 'sv3-182',
    number: '182',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/182.png","large":"https://images.pokemontcg.io/sv3/182_hires.png"}',
    searchName: 'Lechonk (OBF 182)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Oinkologne',
    tcgApiId: 'sv3-183',
    number: '183',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/183.png","large":"https://images.pokemontcg.io/sv3/183_hires.png"}',
    searchName: 'Oinkologne (OBF 183)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Oinkologne',
    tcgApiId: 'sv3-184',
    number: '184',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/184.png","large":"https://images.pokemontcg.io/sv3/184_hires.png"}',
    searchName: 'Oinkologne (OBF 184)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Flamigo',
    tcgApiId: 'sv3-185',
    number: '185',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/185.png","large":"https://images.pokemontcg.io/sv3/185_hires.png"}',
    searchName: 'Flamigo (OBF 185)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Arven',
    tcgApiId: 'sv3-186',
    number: '186',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/186.png","large":"https://images.pokemontcg.io/sv3/186_hires.png"}',
    searchName: 'Arven (OBF 186)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Brassius',
    tcgApiId: 'sv3-187',
    number: '187',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/187.png","large":"https://images.pokemontcg.io/sv3/187_hires.png"}',
    searchName: 'Brassius (OBF 187)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Geeta',
    tcgApiId: 'sv3-188',
    number: '188',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/188.png","large":"https://images.pokemontcg.io/sv3/188_hires.png"}',
    searchName: 'Geeta (OBF 188)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Letter of Encouragement',
    tcgApiId: 'sv3-189',
    number: '189',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/189.png","large":"https://images.pokemontcg.io/sv3/189_hires.png"}',
    searchName: 'Letter of Encouragement (OBF 189)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Ortega',
    tcgApiId: 'sv3-190',
    number: '190',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/190.png","large":"https://images.pokemontcg.io/sv3/190_hires.png"}',
    searchName: 'Ortega (OBF 190)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Patrol Cap',
    tcgApiId: 'sv3-191',
    number: '191',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/191.png","large":"https://images.pokemontcg.io/sv3/191_hires.png"}',
    searchName: 'Patrol Cap (OBF 191)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pokémon League Headquarters',
    tcgApiId: 'sv3-192',
    number: '192',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/192.png","large":"https://images.pokemontcg.io/sv3/192_hires.png"}',
    searchName: 'Pokémon League Headquarters (OBF 192)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Poppy',
    tcgApiId: 'sv3-193',
    number: '193',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/193.png","large":"https://images.pokemontcg.io/sv3/193_hires.png"}',
    searchName: 'Poppy (OBF 193)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Ryme',
    tcgApiId: 'sv3-194',
    number: '194',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/194.png","large":"https://images.pokemontcg.io/sv3/194_hires.png"}',
    searchName: 'Ryme (OBF 194)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Team Star Grunt',
    tcgApiId: 'sv3-195',
    number: '195',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/195.png","large":"https://images.pokemontcg.io/sv3/195_hires.png"}',
    searchName: 'Team Star Grunt (OBF 195)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Town Store',
    tcgApiId: 'sv3-196',
    number: '196',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/196.png","large":"https://images.pokemontcg.io/sv3/196_hires.png"}',
    searchName: 'Town Store (OBF 196)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Vengeful Punch',
    tcgApiId: 'sv3-197',
    number: '197',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/197.png","large":"https://images.pokemontcg.io/sv3/197_hires.png"}',
    searchName: 'Vengeful Punch (OBF 197)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Gloom',
    tcgApiId: 'sv3-198',
    number: '198',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/198.png","large":"https://images.pokemontcg.io/sv3/198_hires.png"}',
    searchName: 'Gloom (OBF 198)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Ninetales',
    tcgApiId: 'sv3-199',
    number: '199',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/199.png","large":"https://images.pokemontcg.io/sv3/199_hires.png"}',
    searchName: 'Ninetales (OBF 199)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Palafin',
    tcgApiId: 'sv3-200',
    number: '200',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/200.png","large":"https://images.pokemontcg.io/sv3/200_hires.png"}',
    searchName: 'Palafin (OBF 200)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Bellibolt',
    tcgApiId: 'sv3-201',
    number: '201',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/201.png","large":"https://images.pokemontcg.io/sv3/201_hires.png"}',
    searchName: 'Bellibolt (OBF 201)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Cleffa',
    tcgApiId: 'sv3-202',
    number: '202',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/202.png","large":"https://images.pokemontcg.io/sv3/202_hires.png"}',
    searchName: 'Cleffa (OBF 202)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Larvitar',
    tcgApiId: 'sv3-203',
    number: '203',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/203.png","large":"https://images.pokemontcg.io/sv3/203_hires.png"}',
    searchName: 'Larvitar (OBF 203)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Houndour',
    tcgApiId: 'sv3-204',
    number: '204',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/204.png","large":"https://images.pokemontcg.io/sv3/204_hires.png"}',
    searchName: 'Houndour (OBF 204)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Scizor',
    tcgApiId: 'sv3-205',
    number: '205',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/205.png","large":"https://images.pokemontcg.io/sv3/205_hires.png"}',
    searchName: 'Scizor (OBF 205)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Varoom',
    tcgApiId: 'sv3-206',
    number: '206',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/206.png","large":"https://images.pokemontcg.io/sv3/206_hires.png"}',
    searchName: 'Varoom (OBF 206)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pidgey',
    tcgApiId: 'sv3-207',
    number: '207',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/207.png","large":"https://images.pokemontcg.io/sv3/207_hires.png"}',
    searchName: 'Pidgey (OBF 207)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pidgeotto',
    tcgApiId: 'sv3-208',
    number: '208',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/208.png","large":"https://images.pokemontcg.io/sv3/208_hires.png"}',
    searchName: 'Pidgeotto (OBF 208)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Lechonk',
    tcgApiId: 'sv3-209',
    number: '209',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/209.png","large":"https://images.pokemontcg.io/sv3/209_hires.png"}',
    searchName: 'Lechonk (OBF 209)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Eiscue ex',
    tcgApiId: 'sv3-210',
    number: '210',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/210.png","large":"https://images.pokemontcg.io/sv3/210_hires.png"}',
    searchName: 'Eiscue ex (OBF 210)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Tyranitar ex',
    tcgApiId: 'sv3-211',
    number: '211',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/211.png","large":"https://images.pokemontcg.io/sv3/211_hires.png"}',
    searchName: 'Tyranitar ex (OBF 211)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Vespiquen ex',
    tcgApiId: 'sv3-212',
    number: '212',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/212.png","large":"https://images.pokemontcg.io/sv3/212_hires.png"}',
    searchName: 'Vespiquen ex (OBF 212)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Glimmora ex',
    tcgApiId: 'sv3-213',
    number: '213',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/213.png","large":"https://images.pokemontcg.io/sv3/213_hires.png"}',
    searchName: 'Glimmora ex (OBF 213)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Absol ex',
    tcgApiId: 'sv3-214',
    number: '214',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/214.png","large":"https://images.pokemontcg.io/sv3/214_hires.png"}',
    searchName: 'Absol ex (OBF 214)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Charizard ex',
    tcgApiId: 'sv3-215',
    number: '215',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/215.png","large":"https://images.pokemontcg.io/sv3/215_hires.png"}',
    searchName: 'Charizard ex (OBF 215)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Revavroom ex',
    tcgApiId: 'sv3-216',
    number: '216',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/216.png","large":"https://images.pokemontcg.io/sv3/216_hires.png"}',
    searchName: 'Revavroom ex (OBF 216)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pidgeot ex',
    tcgApiId: 'sv3-217',
    number: '217',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/217.png","large":"https://images.pokemontcg.io/sv3/217_hires.png"}',
    searchName: 'Pidgeot ex (OBF 217)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Geeta',
    tcgApiId: 'sv3-218',
    number: '218',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/218.png","large":"https://images.pokemontcg.io/sv3/218_hires.png"}',
    searchName: 'Geeta (OBF 218)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Ortega',
    tcgApiId: 'sv3-219',
    number: '219',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/219.png","large":"https://images.pokemontcg.io/sv3/219_hires.png"}',
    searchName: 'Ortega (OBF 219)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Poppy',
    tcgApiId: 'sv3-220',
    number: '220',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/220.png","large":"https://images.pokemontcg.io/sv3/220_hires.png"}',
    searchName: 'Poppy (OBF 220)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Ryme',
    tcgApiId: 'sv3-221',
    number: '221',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/221.png","large":"https://images.pokemontcg.io/sv3/221_hires.png"}',
    searchName: 'Ryme (OBF 221)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Eiscue ex',
    tcgApiId: 'sv3-222',
    number: '222',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/222.png","large":"https://images.pokemontcg.io/sv3/222_hires.png"}',
    searchName: 'Eiscue ex (OBF 222)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Charizard ex',
    tcgApiId: 'sv3-223',
    number: '223',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/223.png","large":"https://images.pokemontcg.io/sv3/223_hires.png"}',
    searchName: 'Charizard ex (OBF 223)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Revavroom ex',
    tcgApiId: 'sv3-224',
    number: '224',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/224.png","large":"https://images.pokemontcg.io/sv3/224_hires.png"}',
    searchName: 'Revavroom ex (OBF 224)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Pidgeot ex',
    tcgApiId: 'sv3-225',
    number: '225',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/225.png","large":"https://images.pokemontcg.io/sv3/225_hires.png"}',
    searchName: 'Pidgeot ex (OBF 225)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Geeta',
    tcgApiId: 'sv3-226',
    number: '226',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/226.png","large":"https://images.pokemontcg.io/sv3/226_hires.png"}',
    searchName: 'Geeta (OBF 226)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Poppy',
    tcgApiId: 'sv3-227',
    number: '227',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/227.png","large":"https://images.pokemontcg.io/sv3/227_hires.png"}',
    searchName: 'Poppy (OBF 227)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Charizard ex',
    tcgApiId: 'sv3-228',
    number: '228',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/228.png","large":"https://images.pokemontcg.io/sv3/228_hires.png"}',
    searchName: 'Charizard ex (OBF 228)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Artazon',
    tcgApiId: 'sv3-229',
    number: '229',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/229.png","large":"https://images.pokemontcg.io/sv3/229_hires.png"}',
    searchName: 'Artazon (OBF 229)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv3',
    name: 'Basic Fire Energy',
    tcgApiId: 'sv3-230',
    number: '230',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv3/230.png","large":"https://images.pokemontcg.io/sv3/230_hires.png"}',
    searchName: 'Basic Fire Energy (OBF 230)',
  },
];
