export const cardSeedSv6pt5 = [
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Joltik',
    tcgApiId: 'sv6pt5-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/1.png","large":"https://images.pokemontcg.io/sv6pt5/1_hires.png"}',
    searchName: 'Joltik (SFA 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Galvantula',
    tcgApiId: 'sv6pt5-2',
    number: '2',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/2.png","large":"https://images.pokemontcg.io/sv6pt5/2_hires.png"}',
    searchName: 'Galvantula (SFA 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Rowlet',
    tcgApiId: 'sv6pt5-3',
    number: '3',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/3.png","large":"https://images.pokemontcg.io/sv6pt5/3_hires.png"}',
    searchName: 'Rowlet (SFA 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Dartrix',
    tcgApiId: 'sv6pt5-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/4.png","large":"https://images.pokemontcg.io/sv6pt5/4_hires.png"}',
    searchName: 'Dartrix (SFA 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Decidueye',
    tcgApiId: 'sv6pt5-5',
    number: '5',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/5.png","large":"https://images.pokemontcg.io/sv6pt5/5_hires.png"}',
    searchName: 'Decidueye (SFA 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Tapu Bulu',
    tcgApiId: 'sv6pt5-6',
    number: '6',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/6.png","large":"https://images.pokemontcg.io/sv6pt5/6_hires.png"}',
    searchName: 'Tapu Bulu (SFA 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Houndour',
    tcgApiId: 'sv6pt5-7',
    number: '7',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/7.png","large":"https://images.pokemontcg.io/sv6pt5/7_hires.png"}',
    searchName: 'Houndour (SFA 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Houndoom',
    tcgApiId: 'sv6pt5-8',
    number: '8',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/8.png","large":"https://images.pokemontcg.io/sv6pt5/8_hires.png"}',
    searchName: 'Houndoom (SFA 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Iron Moth',
    tcgApiId: 'sv6pt5-9',
    number: '9',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/9.png","large":"https://images.pokemontcg.io/sv6pt5/9_hires.png"}',
    searchName: 'Iron Moth (SFA 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Horsea',
    tcgApiId: 'sv6pt5-10',
    number: '10',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/10.png","large":"https://images.pokemontcg.io/sv6pt5/10_hires.png"}',
    searchName: 'Horsea (SFA 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Seadra',
    tcgApiId: 'sv6pt5-11',
    number: '11',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/11.png","large":"https://images.pokemontcg.io/sv6pt5/11_hires.png"}',
    searchName: 'Seadra (SFA 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Kingdra ex',
    tcgApiId: 'sv6pt5-12',
    number: '12',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/12.png","large":"https://images.pokemontcg.io/sv6pt5/12_hires.png"}',
    searchName: 'Kingdra ex (SFA 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Sneasel',
    tcgApiId: 'sv6pt5-13',
    number: '13',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/13.png","large":"https://images.pokemontcg.io/sv6pt5/13_hires.png"}',
    searchName: 'Sneasel (SFA 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Weavile',
    tcgApiId: 'sv6pt5-14',
    number: '14',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/14.png","large":"https://images.pokemontcg.io/sv6pt5/14_hires.png"}',
    searchName: 'Weavile (SFA 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Revavroom ex',
    tcgApiId: 'sv6pt5-15',
    number: '15',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/15.png","large":"https://images.pokemontcg.io/sv6pt5/15_hires.png"}',
    searchName: 'Revavroom ex (SFA 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Drowzee',
    tcgApiId: 'sv6pt5-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/16.png","large":"https://images.pokemontcg.io/sv6pt5/16_hires.png"}',
    searchName: 'Drowzee (SFA 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Hypno',
    tcgApiId: 'sv6pt5-17',
    number: '17',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/17.png","large":"https://images.pokemontcg.io/sv6pt5/17_hires.png"}',
    searchName: 'Hypno (SFA 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Duskull',
    tcgApiId: 'sv6pt5-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/18.png","large":"https://images.pokemontcg.io/sv6pt5/18_hires.png"}',
    searchName: 'Duskull (SFA 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Dusclops',
    tcgApiId: 'sv6pt5-19',
    number: '19',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/19.png","large":"https://images.pokemontcg.io/sv6pt5/19_hires.png"}',
    searchName: 'Dusclops (SFA 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Dusknoir',
    tcgApiId: 'sv6pt5-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/20.png","large":"https://images.pokemontcg.io/sv6pt5/20_hires.png"}',
    searchName: 'Dusknoir (SFA 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Cresselia',
    tcgApiId: 'sv6pt5-21',
    number: '21',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/21.png","large":"https://images.pokemontcg.io/sv6pt5/21_hires.png"}',
    searchName: 'Cresselia (SFA 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Sylveon',
    tcgApiId: 'sv6pt5-22',
    number: '22',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/22.png","large":"https://images.pokemontcg.io/sv6pt5/22_hires.png"}',
    searchName: 'Sylveon (SFA 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Croagunk',
    tcgApiId: 'sv6pt5-23',
    number: '23',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/23.png","large":"https://images.pokemontcg.io/sv6pt5/23_hires.png"}',
    searchName: 'Croagunk (SFA 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Toxicroak',
    tcgApiId: 'sv6pt5-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/24.png","large":"https://images.pokemontcg.io/sv6pt5/24_hires.png"}',
    searchName: 'Toxicroak (SFA 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Bloodmoon Ursaluna',
    tcgApiId: 'sv6pt5-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/25.png","large":"https://images.pokemontcg.io/sv6pt5/25_hires.png"}',
    searchName: 'Bloodmoon Ursaluna (SFA 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Slither Wing',
    tcgApiId: 'sv6pt5-26',
    number: '26',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/26.png","large":"https://images.pokemontcg.io/sv6pt5/26_hires.png"}',
    searchName: 'Slither Wing (SFA 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Zubat',
    tcgApiId: 'sv6pt5-27',
    number: '27',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/27.png","large":"https://images.pokemontcg.io/sv6pt5/27_hires.png"}',
    searchName: 'Zubat (SFA 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Golbat',
    tcgApiId: 'sv6pt5-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/28.png","large":"https://images.pokemontcg.io/sv6pt5/28_hires.png"}',
    searchName: 'Golbat (SFA 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Crobat',
    tcgApiId: 'sv6pt5-29',
    number: '29',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/29.png","large":"https://images.pokemontcg.io/sv6pt5/29_hires.png"}',
    searchName: 'Crobat (SFA 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Absol',
    tcgApiId: 'sv6pt5-30',
    number: '30',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/30.png","large":"https://images.pokemontcg.io/sv6pt5/30_hires.png"}',
    searchName: 'Absol (SFA 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Zorua',
    tcgApiId: 'sv6pt5-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/31.png","large":"https://images.pokemontcg.io/sv6pt5/31_hires.png"}',
    searchName: 'Zorua (SFA 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Zoroark',
    tcgApiId: 'sv6pt5-32',
    number: '32',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/32.png","large":"https://images.pokemontcg.io/sv6pt5/32_hires.png"}',
    searchName: 'Zoroark (SFA 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Inkay',
    tcgApiId: 'sv6pt5-33',
    number: '33',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/33.png","large":"https://images.pokemontcg.io/sv6pt5/33_hires.png"}',
    searchName: 'Inkay (SFA 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Malamar',
    tcgApiId: 'sv6pt5-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/34.png","large":"https://images.pokemontcg.io/sv6pt5/34_hires.png"}',
    searchName: 'Malamar (SFA 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Yveltal',
    tcgApiId: 'sv6pt5-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/35.png","large":"https://images.pokemontcg.io/sv6pt5/35_hires.png"}',
    searchName: 'Yveltal (SFA 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Okidogi ex',
    tcgApiId: 'sv6pt5-36',
    number: '36',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/36.png","large":"https://images.pokemontcg.io/sv6pt5/36_hires.png"}',
    searchName: 'Okidogi ex (SFA 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Munkidori ex',
    tcgApiId: 'sv6pt5-37',
    number: '37',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/37.png","large":"https://images.pokemontcg.io/sv6pt5/37_hires.png"}',
    searchName: 'Munkidori ex (SFA 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Fezandipiti ex',
    tcgApiId: 'sv6pt5-38',
    number: '38',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/38.png","large":"https://images.pokemontcg.io/sv6pt5/38_hires.png"}',
    searchName: 'Fezandipiti ex (SFA 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Pecharunt ex',
    tcgApiId: 'sv6pt5-39',
    number: '39',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/39.png","large":"https://images.pokemontcg.io/sv6pt5/39_hires.png"}',
    searchName: 'Pecharunt ex (SFA 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Genesect',
    tcgApiId: 'sv6pt5-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/40.png","large":"https://images.pokemontcg.io/sv6pt5/40_hires.png"}',
    searchName: 'Genesect (SFA 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Cufant',
    tcgApiId: 'sv6pt5-41',
    number: '41',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/41.png","large":"https://images.pokemontcg.io/sv6pt5/41_hires.png"}',
    searchName: 'Cufant (SFA 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Copperajah',
    tcgApiId: 'sv6pt5-42',
    number: '42',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/42.png","large":"https://images.pokemontcg.io/sv6pt5/42_hires.png"}',
    searchName: 'Copperajah (SFA 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Varoom',
    tcgApiId: 'sv6pt5-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/43.png","large":"https://images.pokemontcg.io/sv6pt5/43_hires.png"}',
    searchName: 'Varoom (SFA 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Axew',
    tcgApiId: 'sv6pt5-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/44.png","large":"https://images.pokemontcg.io/sv6pt5/44_hires.png"}',
    searchName: 'Axew (SFA 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Fraxure',
    tcgApiId: 'sv6pt5-45',
    number: '45',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/45.png","large":"https://images.pokemontcg.io/sv6pt5/45_hires.png"}',
    searchName: 'Fraxure (SFA 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Haxorus',
    tcgApiId: 'sv6pt5-46',
    number: '46',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/46.png","large":"https://images.pokemontcg.io/sv6pt5/46_hires.png"}',
    searchName: 'Haxorus (SFA 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Kyurem',
    tcgApiId: 'sv6pt5-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/47.png","large":"https://images.pokemontcg.io/sv6pt5/47_hires.png"}',
    searchName: 'Kyurem (SFA 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Meowth',
    tcgApiId: 'sv6pt5-48',
    number: '48',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/48.png","large":"https://images.pokemontcg.io/sv6pt5/48_hires.png"}',
    searchName: 'Meowth (SFA 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Persian',
    tcgApiId: 'sv6pt5-49',
    number: '49',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/49.png","large":"https://images.pokemontcg.io/sv6pt5/49_hires.png"}',
    searchName: 'Persian (SFA 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Eevee',
    tcgApiId: 'sv6pt5-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/50.png","large":"https://images.pokemontcg.io/sv6pt5/50_hires.png"}',
    searchName: 'Eevee (SFA 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Furfrou',
    tcgApiId: 'sv6pt5-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/51.png","large":"https://images.pokemontcg.io/sv6pt5/51_hires.png"}',
    searchName: 'Furfrou (SFA 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Stufful',
    tcgApiId: 'sv6pt5-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/52.png","large":"https://images.pokemontcg.io/sv6pt5/52_hires.png"}',
    searchName: 'Stufful (SFA 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Bewear',
    tcgApiId: 'sv6pt5-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/53.png","large":"https://images.pokemontcg.io/sv6pt5/53_hires.png"}',
    searchName: 'Bewear (SFA 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Academy at Night',
    tcgApiId: 'sv6pt5-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/54.png","large":"https://images.pokemontcg.io/sv6pt5/54_hires.png"}',
    searchName: 'Academy at Night (SFA 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Binding Mochi',
    tcgApiId: 'sv6pt5-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/55.png","large":"https://images.pokemontcg.io/sv6pt5/55_hires.png"}',
    searchName: 'Binding Mochi (SFA 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Cassiopeia',
    tcgApiId: 'sv6pt5-56',
    number: '56',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/56.png","large":"https://images.pokemontcg.io/sv6pt5/56_hires.png"}',
    searchName: 'Cassiopeia (SFA 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: "Colress's Tenacity",
    tcgApiId: 'sv6pt5-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/57.png","large":"https://images.pokemontcg.io/sv6pt5/57_hires.png"}',
    searchName: "Colress's Tenacity (SFA 57)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Dangerous Laser',
    tcgApiId: 'sv6pt5-58',
    number: '58',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/58.png","large":"https://images.pokemontcg.io/sv6pt5/58_hires.png"}',
    searchName: 'Dangerous Laser (SFA 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: "Janine's Secret Art",
    tcgApiId: 'sv6pt5-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/59.png","large":"https://images.pokemontcg.io/sv6pt5/59_hires.png"}',
    searchName: "Janine's Secret Art (SFA 59)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Neutralization Zone',
    tcgApiId: 'sv6pt5-60',
    number: '60',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/60.png","large":"https://images.pokemontcg.io/sv6pt5/60_hires.png"}',
    searchName: 'Neutralization Zone (SFA 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Night Stretcher',
    tcgApiId: 'sv6pt5-61',
    number: '61',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/61.png","large":"https://images.pokemontcg.io/sv6pt5/61_hires.png"}',
    searchName: 'Night Stretcher (SFA 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Poké Vital A',
    tcgApiId: 'sv6pt5-62',
    number: '62',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/62.png","large":"https://images.pokemontcg.io/sv6pt5/62_hires.png"}',
    searchName: 'Poké Vital A (SFA 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Powerglass',
    tcgApiId: 'sv6pt5-63',
    number: '63',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/63.png","large":"https://images.pokemontcg.io/sv6pt5/63_hires.png"}',
    searchName: 'Powerglass (SFA 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: "Xerosic's Machinations",
    tcgApiId: 'sv6pt5-64',
    number: '64',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/64.png","large":"https://images.pokemontcg.io/sv6pt5/64_hires.png"}',
    searchName: "Xerosic's Machinations (SFA 64)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Tapu Bulu',
    tcgApiId: 'sv6pt5-65',
    number: '65',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/65.png","large":"https://images.pokemontcg.io/sv6pt5/65_hires.png"}',
    searchName: 'Tapu Bulu (SFA 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Houndoom',
    tcgApiId: 'sv6pt5-66',
    number: '66',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/66.png","large":"https://images.pokemontcg.io/sv6pt5/66_hires.png"}',
    searchName: 'Houndoom (SFA 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Horsea',
    tcgApiId: 'sv6pt5-67',
    number: '67',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/67.png","large":"https://images.pokemontcg.io/sv6pt5/67_hires.png"}',
    searchName: 'Horsea (SFA 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Duskull',
    tcgApiId: 'sv6pt5-68',
    number: '68',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/68.png","large":"https://images.pokemontcg.io/sv6pt5/68_hires.png"}',
    searchName: 'Duskull (SFA 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Dusclops',
    tcgApiId: 'sv6pt5-69',
    number: '69',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/69.png","large":"https://images.pokemontcg.io/sv6pt5/69_hires.png"}',
    searchName: 'Dusclops (SFA 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Dusknoir',
    tcgApiId: 'sv6pt5-70',
    number: '70',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/70.png","large":"https://images.pokemontcg.io/sv6pt5/70_hires.png"}',
    searchName: 'Dusknoir (SFA 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Cresselia',
    tcgApiId: 'sv6pt5-71',
    number: '71',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/71.png","large":"https://images.pokemontcg.io/sv6pt5/71_hires.png"}',
    searchName: 'Cresselia (SFA 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Munkidori',
    tcgApiId: 'sv6pt5-72',
    number: '72',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/72.png","large":"https://images.pokemontcg.io/sv6pt5/72_hires.png"}',
    searchName: 'Munkidori (SFA 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Fezandipiti',
    tcgApiId: 'sv6pt5-73',
    number: '73',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/73.png","large":"https://images.pokemontcg.io/sv6pt5/73_hires.png"}',
    searchName: 'Fezandipiti (SFA 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Okidogi',
    tcgApiId: 'sv6pt5-74',
    number: '74',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/74.png","large":"https://images.pokemontcg.io/sv6pt5/74_hires.png"}',
    searchName: 'Okidogi (SFA 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Zorua',
    tcgApiId: 'sv6pt5-75',
    number: '75',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/75.png","large":"https://images.pokemontcg.io/sv6pt5/75_hires.png"}',
    searchName: 'Zorua (SFA 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Cufant',
    tcgApiId: 'sv6pt5-76',
    number: '76',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/76.png","large":"https://images.pokemontcg.io/sv6pt5/76_hires.png"}',
    searchName: 'Cufant (SFA 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Fraxure',
    tcgApiId: 'sv6pt5-77',
    number: '77',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/77.png","large":"https://images.pokemontcg.io/sv6pt5/77_hires.png"}',
    searchName: 'Fraxure (SFA 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Persian',
    tcgApiId: 'sv6pt5-78',
    number: '78',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/78.png","large":"https://images.pokemontcg.io/sv6pt5/78_hires.png"}',
    searchName: 'Persian (SFA 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Bewear',
    tcgApiId: 'sv6pt5-79',
    number: '79',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/79.png","large":"https://images.pokemontcg.io/sv6pt5/79_hires.png"}',
    searchName: 'Bewear (SFA 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Kingdra ex',
    tcgApiId: 'sv6pt5-80',
    number: '80',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/80.png","large":"https://images.pokemontcg.io/sv6pt5/80_hires.png"}',
    searchName: 'Kingdra ex (SFA 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Revavroom ex',
    tcgApiId: 'sv6pt5-81',
    number: '81',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/81.png","large":"https://images.pokemontcg.io/sv6pt5/81_hires.png"}',
    searchName: 'Revavroom ex (SFA 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Okidogi ex',
    tcgApiId: 'sv6pt5-82',
    number: '82',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/82.png","large":"https://images.pokemontcg.io/sv6pt5/82_hires.png"}',
    searchName: 'Okidogi ex (SFA 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Munkidori ex',
    tcgApiId: 'sv6pt5-83',
    number: '83',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/83.png","large":"https://images.pokemontcg.io/sv6pt5/83_hires.png"}',
    searchName: 'Munkidori ex (SFA 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Fezandipiti ex',
    tcgApiId: 'sv6pt5-84',
    number: '84',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/84.png","large":"https://images.pokemontcg.io/sv6pt5/84_hires.png"}',
    searchName: 'Fezandipiti ex (SFA 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Pecharunt ex',
    tcgApiId: 'sv6pt5-85',
    number: '85',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/85.png","large":"https://images.pokemontcg.io/sv6pt5/85_hires.png"}',
    searchName: 'Pecharunt ex (SFA 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Cassiopeia',
    tcgApiId: 'sv6pt5-86',
    number: '86',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/86.png","large":"https://images.pokemontcg.io/sv6pt5/86_hires.png"}',
    searchName: 'Cassiopeia (SFA 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: "Colress's Tenacity",
    tcgApiId: 'sv6pt5-87',
    number: '87',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/87.png","large":"https://images.pokemontcg.io/sv6pt5/87_hires.png"}',
    searchName: "Colress's Tenacity (SFA 87)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: "Janine's Secret Art",
    tcgApiId: 'sv6pt5-88',
    number: '88',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/88.png","large":"https://images.pokemontcg.io/sv6pt5/88_hires.png"}',
    searchName: "Janine's Secret Art (SFA 88)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: "Xerosic's Machinations",
    tcgApiId: 'sv6pt5-89',
    number: '89',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/89.png","large":"https://images.pokemontcg.io/sv6pt5/89_hires.png"}',
    searchName: "Xerosic's Machinations (SFA 89)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Okidogi ex',
    tcgApiId: 'sv6pt5-90',
    number: '90',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/90.png","large":"https://images.pokemontcg.io/sv6pt5/90_hires.png"}',
    searchName: 'Okidogi ex (SFA 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Munkidori ex',
    tcgApiId: 'sv6pt5-91',
    number: '91',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/91.png","large":"https://images.pokemontcg.io/sv6pt5/91_hires.png"}',
    searchName: 'Munkidori ex (SFA 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Fezandipiti ex',
    tcgApiId: 'sv6pt5-92',
    number: '92',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/92.png","large":"https://images.pokemontcg.io/sv6pt5/92_hires.png"}',
    searchName: 'Fezandipiti ex (SFA 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Pecharunt ex',
    tcgApiId: 'sv6pt5-93',
    number: '93',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/93.png","large":"https://images.pokemontcg.io/sv6pt5/93_hires.png"}',
    searchName: 'Pecharunt ex (SFA 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Cassiopeia',
    tcgApiId: 'sv6pt5-94',
    number: '94',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/94.png","large":"https://images.pokemontcg.io/sv6pt5/94_hires.png"}',
    searchName: 'Cassiopeia (SFA 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Pecharunt ex',
    tcgApiId: 'sv6pt5-95',
    number: '95',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/95.png","large":"https://images.pokemontcg.io/sv6pt5/95_hires.png"}',
    searchName: 'Pecharunt ex (SFA 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Earthen Vessel',
    tcgApiId: 'sv6pt5-96',
    number: '96',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/96.png","large":"https://images.pokemontcg.io/sv6pt5/96_hires.png"}',
    searchName: 'Earthen Vessel (SFA 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Powerglass',
    tcgApiId: 'sv6pt5-97',
    number: '97',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/97.png","large":"https://images.pokemontcg.io/sv6pt5/97_hires.png"}',
    searchName: 'Powerglass (SFA 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Basic Darkness Energy',
    tcgApiId: 'sv6pt5-98',
    number: '98',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/98.png","large":"https://images.pokemontcg.io/sv6pt5/98_hires.png"}',
    searchName: 'Basic Darkness Energy (SFA 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv6pt5',
    name: 'Basic Metal Energy',
    tcgApiId: 'sv6pt5-99',
    number: '99',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv6pt5/99.png","large":"https://images.pokemontcg.io/sv6pt5/99_hires.png"}',
    searchName: 'Basic Metal Energy (SFA 99)',
  },
];
