export const cardSeedSv8 = [
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Exeggcute',
    tcgApiId: 'sv8-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/1.png","large":"https://images.pokemontcg.io/sv8/1_hires.png"}',
    searchName: 'Exeggcute (SSP 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Exeggcute',
    tcgApiId: 'sv8-2',
    number: '2',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/2.png","large":"https://images.pokemontcg.io/sv8/2_hires.png"}',
    searchName: 'Exeggcute (SSP 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Exeggutor',
    tcgApiId: 'sv8-3',
    number: '3',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/3.png","large":"https://images.pokemontcg.io/sv8/3_hires.png"}',
    searchName: 'Exeggutor (SSP 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Durant ex',
    tcgApiId: 'sv8-4',
    number: '4',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/4.png","large":"https://images.pokemontcg.io/sv8/4_hires.png"}',
    searchName: 'Durant ex (SSP 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Scatterbug',
    tcgApiId: 'sv8-5',
    number: '5',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/5.png","large":"https://images.pokemontcg.io/sv8/5_hires.png"}',
    searchName: 'Scatterbug (SSP 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Spewpa',
    tcgApiId: 'sv8-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/6.png","large":"https://images.pokemontcg.io/sv8/6_hires.png"}',
    searchName: 'Spewpa (SSP 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Vivillon',
    tcgApiId: 'sv8-7',
    number: '7',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/7.png","large":"https://images.pokemontcg.io/sv8/7_hires.png"}',
    searchName: 'Vivillon (SSP 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Morelull',
    tcgApiId: 'sv8-8',
    number: '8',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/8.png","large":"https://images.pokemontcg.io/sv8/8_hires.png"}',
    searchName: 'Morelull (SSP 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Shiinotic',
    tcgApiId: 'sv8-9',
    number: '9',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/9.png","large":"https://images.pokemontcg.io/sv8/9_hires.png"}',
    searchName: 'Shiinotic (SSP 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Dhelmise',
    tcgApiId: 'sv8-10',
    number: '10',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/10.png","large":"https://images.pokemontcg.io/sv8/10_hires.png"}',
    searchName: 'Dhelmise (SSP 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Zarude',
    tcgApiId: 'sv8-11',
    number: '11',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/11.png","large":"https://images.pokemontcg.io/sv8/11_hires.png"}',
    searchName: 'Zarude (SSP 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Capsakid',
    tcgApiId: 'sv8-12',
    number: '12',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/12.png","large":"https://images.pokemontcg.io/sv8/12_hires.png"}',
    searchName: 'Capsakid (SSP 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Rellor',
    tcgApiId: 'sv8-13',
    number: '13',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/13.png","large":"https://images.pokemontcg.io/sv8/13_hires.png"}',
    searchName: 'Rellor (SSP 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Rabsca',
    tcgApiId: 'sv8-14',
    number: '14',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/14.png","large":"https://images.pokemontcg.io/sv8/14_hires.png"}',
    searchName: 'Rabsca (SSP 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Wo-Chien',
    tcgApiId: 'sv8-15',
    number: '15',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/15.png","large":"https://images.pokemontcg.io/sv8/15_hires.png"}',
    searchName: 'Wo-Chien (SSP 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Vulpix',
    tcgApiId: 'sv8-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/16.png","large":"https://images.pokemontcg.io/sv8/16_hires.png"}',
    searchName: 'Vulpix (SSP 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Ninetales',
    tcgApiId: 'sv8-17',
    number: '17',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/17.png","large":"https://images.pokemontcg.io/sv8/17_hires.png"}',
    searchName: 'Ninetales (SSP 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Paldean Tauros',
    tcgApiId: 'sv8-18',
    number: '18',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/18.png","large":"https://images.pokemontcg.io/sv8/18_hires.png"}',
    searchName: 'Paldean Tauros (SSP 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Ho-Oh',
    tcgApiId: 'sv8-19',
    number: '19',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/19.png","large":"https://images.pokemontcg.io/sv8/19_hires.png"}',
    searchName: 'Ho-Oh (SSP 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Castform Sunny Form',
    tcgApiId: 'sv8-20',
    number: '20',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/20.png","large":"https://images.pokemontcg.io/sv8/20_hires.png"}',
    searchName: 'Castform Sunny Form (SSP 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Victini',
    tcgApiId: 'sv8-21',
    number: '21',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/21.png","large":"https://images.pokemontcg.io/sv8/21_hires.png"}',
    searchName: 'Victini (SSP 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Pansear',
    tcgApiId: 'sv8-22',
    number: '22',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/22.png","large":"https://images.pokemontcg.io/sv8/22_hires.png"}',
    searchName: 'Pansear (SSP 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Simisear',
    tcgApiId: 'sv8-23',
    number: '23',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/23.png","large":"https://images.pokemontcg.io/sv8/23_hires.png"}',
    searchName: 'Simisear (SSP 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Larvesta',
    tcgApiId: 'sv8-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/24.png","large":"https://images.pokemontcg.io/sv8/24_hires.png"}',
    searchName: 'Larvesta (SSP 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Volcarona',
    tcgApiId: 'sv8-25',
    number: '25',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/25.png","large":"https://images.pokemontcg.io/sv8/25_hires.png"}',
    searchName: 'Volcarona (SSP 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Oricorio',
    tcgApiId: 'sv8-26',
    number: '26',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/26.png","large":"https://images.pokemontcg.io/sv8/26_hires.png"}',
    searchName: 'Oricorio (SSP 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Sizzlipede',
    tcgApiId: 'sv8-27',
    number: '27',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/27.png","large":"https://images.pokemontcg.io/sv8/27_hires.png"}',
    searchName: 'Sizzlipede (SSP 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Centiskorch',
    tcgApiId: 'sv8-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/28.png","large":"https://images.pokemontcg.io/sv8/28_hires.png"}',
    searchName: 'Centiskorch (SSP 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Fuecoco',
    tcgApiId: 'sv8-29',
    number: '29',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/29.png","large":"https://images.pokemontcg.io/sv8/29_hires.png"}',
    searchName: 'Fuecoco (SSP 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Crocalor',
    tcgApiId: 'sv8-30',
    number: '30',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/30.png","large":"https://images.pokemontcg.io/sv8/30_hires.png"}',
    searchName: 'Crocalor (SSP 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Skeledirge',
    tcgApiId: 'sv8-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/31.png","large":"https://images.pokemontcg.io/sv8/31_hires.png"}',
    searchName: 'Skeledirge (SSP 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Charcadet',
    tcgApiId: 'sv8-32',
    number: '32',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/32.png","large":"https://images.pokemontcg.io/sv8/32_hires.png"}',
    searchName: 'Charcadet (SSP 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Charcadet',
    tcgApiId: 'sv8-33',
    number: '33',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/33.png","large":"https://images.pokemontcg.io/sv8/33_hires.png"}',
    searchName: 'Charcadet (SSP 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Armarouge',
    tcgApiId: 'sv8-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/34.png","large":"https://images.pokemontcg.io/sv8/34_hires.png"}',
    searchName: 'Armarouge (SSP 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Ceruledge',
    tcgApiId: 'sv8-35',
    number: '35',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/35.png","large":"https://images.pokemontcg.io/sv8/35_hires.png"}',
    searchName: 'Ceruledge (SSP 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Ceruledge ex',
    tcgApiId: 'sv8-36',
    number: '36',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/36.png","large":"https://images.pokemontcg.io/sv8/36_hires.png"}',
    searchName: 'Ceruledge ex (SSP 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Scovillain ex',
    tcgApiId: 'sv8-37',
    number: '37',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/37.png","large":"https://images.pokemontcg.io/sv8/37_hires.png"}',
    searchName: 'Scovillain ex (SSP 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Gouging Fire',
    tcgApiId: 'sv8-38',
    number: '38',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/38.png","large":"https://images.pokemontcg.io/sv8/38_hires.png"}',
    searchName: 'Gouging Fire (SSP 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Paldean Tauros',
    tcgApiId: 'sv8-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/39.png","large":"https://images.pokemontcg.io/sv8/39_hires.png"}',
    searchName: 'Paldean Tauros (SSP 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Mantine',
    tcgApiId: 'sv8-40',
    number: '40',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/40.png","large":"https://images.pokemontcg.io/sv8/40_hires.png"}',
    searchName: 'Mantine (SSP 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Feebas',
    tcgApiId: 'sv8-41',
    number: '41',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/41.png","large":"https://images.pokemontcg.io/sv8/41_hires.png"}',
    searchName: 'Feebas (SSP 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Milotic ex',
    tcgApiId: 'sv8-42',
    number: '42',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/42.png","large":"https://images.pokemontcg.io/sv8/42_hires.png"}',
    searchName: 'Milotic ex (SSP 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Spheal',
    tcgApiId: 'sv8-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/43.png","large":"https://images.pokemontcg.io/sv8/43_hires.png"}',
    searchName: 'Spheal (SSP 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Sealeo',
    tcgApiId: 'sv8-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/44.png","large":"https://images.pokemontcg.io/sv8/44_hires.png"}',
    searchName: 'Sealeo (SSP 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Walrein',
    tcgApiId: 'sv8-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/45.png","large":"https://images.pokemontcg.io/sv8/45_hires.png"}',
    searchName: 'Walrein (SSP 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Shellos',
    tcgApiId: 'sv8-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/46.png","large":"https://images.pokemontcg.io/sv8/46_hires.png"}',
    searchName: 'Shellos (SSP 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Cryogonal',
    tcgApiId: 'sv8-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/47.png","large":"https://images.pokemontcg.io/sv8/47_hires.png"}',
    searchName: 'Cryogonal (SSP 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Black Kyurem ex',
    tcgApiId: 'sv8-48',
    number: '48',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/48.png","large":"https://images.pokemontcg.io/sv8/48_hires.png"}',
    searchName: 'Black Kyurem ex (SSP 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Bruxish',
    tcgApiId: 'sv8-49',
    number: '49',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/49.png","large":"https://images.pokemontcg.io/sv8/49_hires.png"}',
    searchName: 'Bruxish (SSP 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Quaxly',
    tcgApiId: 'sv8-50',
    number: '50',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/50.png","large":"https://images.pokemontcg.io/sv8/50_hires.png"}',
    searchName: 'Quaxly (SSP 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Quaxwell',
    tcgApiId: 'sv8-51',
    number: '51',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/51.png","large":"https://images.pokemontcg.io/sv8/51_hires.png"}',
    searchName: 'Quaxwell (SSP 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Quaquaval',
    tcgApiId: 'sv8-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/52.png","large":"https://images.pokemontcg.io/sv8/52_hires.png"}',
    searchName: 'Quaquaval (SSP 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Cetoddle',
    tcgApiId: 'sv8-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/53.png","large":"https://images.pokemontcg.io/sv8/53_hires.png"}',
    searchName: 'Cetoddle (SSP 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Cetitan',
    tcgApiId: 'sv8-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/54.png","large":"https://images.pokemontcg.io/sv8/54_hires.png"}',
    searchName: 'Cetitan (SSP 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Iron Bundle',
    tcgApiId: 'sv8-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/55.png","large":"https://images.pokemontcg.io/sv8/55_hires.png"}',
    searchName: 'Iron Bundle (SSP 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Chien-Pao',
    tcgApiId: 'sv8-56',
    number: '56',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/56.png","large":"https://images.pokemontcg.io/sv8/56_hires.png"}',
    searchName: 'Chien-Pao (SSP 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Pikachu ex',
    tcgApiId: 'sv8-57',
    number: '57',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/57.png","large":"https://images.pokemontcg.io/sv8/57_hires.png"}',
    searchName: 'Pikachu ex (SSP 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Magnemite',
    tcgApiId: 'sv8-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/58.png","large":"https://images.pokemontcg.io/sv8/58_hires.png"}',
    searchName: 'Magnemite (SSP 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Magneton',
    tcgApiId: 'sv8-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/59.png","large":"https://images.pokemontcg.io/sv8/59_hires.png"}',
    searchName: 'Magneton (SSP 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Magnezone',
    tcgApiId: 'sv8-60',
    number: '60',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/60.png","large":"https://images.pokemontcg.io/sv8/60_hires.png"}',
    searchName: 'Magnezone (SSP 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Rotom',
    tcgApiId: 'sv8-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/61.png","large":"https://images.pokemontcg.io/sv8/61_hires.png"}',
    searchName: 'Rotom (SSP 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Blitzle',
    tcgApiId: 'sv8-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/62.png","large":"https://images.pokemontcg.io/sv8/62_hires.png"}',
    searchName: 'Blitzle (SSP 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Zebstrika',
    tcgApiId: 'sv8-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/63.png","large":"https://images.pokemontcg.io/sv8/63_hires.png"}',
    searchName: 'Zebstrika (SSP 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Stunfisk',
    tcgApiId: 'sv8-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/64.png","large":"https://images.pokemontcg.io/sv8/64_hires.png"}',
    searchName: 'Stunfisk (SSP 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Tapu Koko',
    tcgApiId: 'sv8-65',
    number: '65',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/65.png","large":"https://images.pokemontcg.io/sv8/65_hires.png"}',
    searchName: 'Tapu Koko (SSP 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Wattrel',
    tcgApiId: 'sv8-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/66.png","large":"https://images.pokemontcg.io/sv8/66_hires.png"}',
    searchName: 'Wattrel (SSP 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Kilowattrel',
    tcgApiId: 'sv8-67',
    number: '67',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/67.png","large":"https://images.pokemontcg.io/sv8/67_hires.png"}',
    searchName: 'Kilowattrel (SSP 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Kilowattrel ex',
    tcgApiId: 'sv8-68',
    number: '68',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/68.png","large":"https://images.pokemontcg.io/sv8/68_hires.png"}',
    searchName: 'Kilowattrel ex (SSP 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Miraidon',
    tcgApiId: 'sv8-69',
    number: '69',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/69.png","large":"https://images.pokemontcg.io/sv8/69_hires.png"}',
    searchName: 'Miraidon (SSP 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Togepi',
    tcgApiId: 'sv8-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/70.png","large":"https://images.pokemontcg.io/sv8/70_hires.png"}',
    searchName: 'Togepi (SSP 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Togetic',
    tcgApiId: 'sv8-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/71.png","large":"https://images.pokemontcg.io/sv8/71_hires.png"}',
    searchName: 'Togetic (SSP 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Togekiss',
    tcgApiId: 'sv8-72',
    number: '72',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/72.png","large":"https://images.pokemontcg.io/sv8/72_hires.png"}',
    searchName: 'Togekiss (SSP 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Marill',
    tcgApiId: 'sv8-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/73.png","large":"https://images.pokemontcg.io/sv8/73_hires.png"}',
    searchName: 'Marill (SSP 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Azumarill',
    tcgApiId: 'sv8-74',
    number: '74',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/74.png","large":"https://images.pokemontcg.io/sv8/74_hires.png"}',
    searchName: 'Azumarill (SSP 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Smoochum',
    tcgApiId: 'sv8-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/75.png","large":"https://images.pokemontcg.io/sv8/75_hires.png"}',
    searchName: 'Smoochum (SSP 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Latias ex',
    tcgApiId: 'sv8-76',
    number: '76',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/76.png","large":"https://images.pokemontcg.io/sv8/76_hires.png"}',
    searchName: 'Latias ex (SSP 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Latios',
    tcgApiId: 'sv8-77',
    number: '77',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/77.png","large":"https://images.pokemontcg.io/sv8/77_hires.png"}',
    searchName: 'Latios (SSP 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Uxie',
    tcgApiId: 'sv8-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/78.png","large":"https://images.pokemontcg.io/sv8/78_hires.png"}',
    searchName: 'Uxie (SSP 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Mesprit',
    tcgApiId: 'sv8-79',
    number: '79',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/79.png","large":"https://images.pokemontcg.io/sv8/79_hires.png"}',
    searchName: 'Mesprit (SSP 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Azelf',
    tcgApiId: 'sv8-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/80.png","large":"https://images.pokemontcg.io/sv8/80_hires.png"}',
    searchName: 'Azelf (SSP 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Sigilyph',
    tcgApiId: 'sv8-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/81.png","large":"https://images.pokemontcg.io/sv8/81_hires.png"}',
    searchName: 'Sigilyph (SSP 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Yamask',
    tcgApiId: 'sv8-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/82.png","large":"https://images.pokemontcg.io/sv8/82_hires.png"}',
    searchName: 'Yamask (SSP 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Cofagrigus',
    tcgApiId: 'sv8-83',
    number: '83',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/83.png","large":"https://images.pokemontcg.io/sv8/83_hires.png"}',
    searchName: 'Cofagrigus (SSP 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Espurr',
    tcgApiId: 'sv8-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/84.png","large":"https://images.pokemontcg.io/sv8/84_hires.png"}',
    searchName: 'Espurr (SSP 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Meowstic',
    tcgApiId: 'sv8-85',
    number: '85',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/85.png","large":"https://images.pokemontcg.io/sv8/85_hires.png"}',
    searchName: 'Meowstic (SSP 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Sylveon ex',
    tcgApiId: 'sv8-86',
    number: '86',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/86.png","large":"https://images.pokemontcg.io/sv8/86_hires.png"}',
    searchName: 'Sylveon ex (SSP 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Dedenne',
    tcgApiId: 'sv8-87',
    number: '87',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/87.png","large":"https://images.pokemontcg.io/sv8/87_hires.png"}',
    searchName: 'Dedenne (SSP 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Xerneas',
    tcgApiId: 'sv8-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/88.png","large":"https://images.pokemontcg.io/sv8/88_hires.png"}',
    searchName: 'Xerneas (SSP 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Oricorio',
    tcgApiId: 'sv8-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/89.png","large":"https://images.pokemontcg.io/sv8/89_hires.png"}',
    searchName: 'Oricorio (SSP 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Sandygast',
    tcgApiId: 'sv8-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/90.png","large":"https://images.pokemontcg.io/sv8/90_hires.png"}',
    searchName: 'Sandygast (SSP 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Palossand ex',
    tcgApiId: 'sv8-91',
    number: '91',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/91.png","large":"https://images.pokemontcg.io/sv8/91_hires.png"}',
    searchName: 'Palossand ex (SSP 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Tapu Lele',
    tcgApiId: 'sv8-92',
    number: '92',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/92.png","large":"https://images.pokemontcg.io/sv8/92_hires.png"}',
    searchName: 'Tapu Lele (SSP 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Indeedee',
    tcgApiId: 'sv8-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/93.png","large":"https://images.pokemontcg.io/sv8/93_hires.png"}',
    searchName: 'Indeedee (SSP 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Flittle',
    tcgApiId: 'sv8-94',
    number: '94',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/94.png","large":"https://images.pokemontcg.io/sv8/94_hires.png"}',
    searchName: 'Flittle (SSP 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Espathra',
    tcgApiId: 'sv8-95',
    number: '95',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/95.png","large":"https://images.pokemontcg.io/sv8/95_hires.png"}',
    searchName: 'Espathra (SSP 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Flutter Mane',
    tcgApiId: 'sv8-96',
    number: '96',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/96.png","large":"https://images.pokemontcg.io/sv8/96_hires.png"}',
    searchName: 'Flutter Mane (SSP 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Gimmighoul',
    tcgApiId: 'sv8-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/97.png","large":"https://images.pokemontcg.io/sv8/97_hires.png"}',
    searchName: 'Gimmighoul (SSP 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Mankey',
    tcgApiId: 'sv8-98',
    number: '98',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/98.png","large":"https://images.pokemontcg.io/sv8/98_hires.png"}',
    searchName: 'Mankey (SSP 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Primeape',
    tcgApiId: 'sv8-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/99.png","large":"https://images.pokemontcg.io/sv8/99_hires.png"}',
    searchName: 'Primeape (SSP 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Annihilape',
    tcgApiId: 'sv8-100',
    number: '100',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/100.png","large":"https://images.pokemontcg.io/sv8/100_hires.png"}',
    searchName: 'Annihilape (SSP 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Paldean Tauros',
    tcgApiId: 'sv8-101',
    number: '101',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/101.png","large":"https://images.pokemontcg.io/sv8/101_hires.png"}',
    searchName: 'Paldean Tauros (SSP 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Phanpy',
    tcgApiId: 'sv8-102',
    number: '102',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/102.png","large":"https://images.pokemontcg.io/sv8/102_hires.png"}',
    searchName: 'Phanpy (SSP 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Donphan',
    tcgApiId: 'sv8-103',
    number: '103',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/103.png","large":"https://images.pokemontcg.io/sv8/103_hires.png"}',
    searchName: 'Donphan (SSP 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Trapinch',
    tcgApiId: 'sv8-104',
    number: '104',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/104.png","large":"https://images.pokemontcg.io/sv8/104_hires.png"}',
    searchName: 'Trapinch (SSP 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Vibrava',
    tcgApiId: 'sv8-105',
    number: '105',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/105.png","large":"https://images.pokemontcg.io/sv8/105_hires.png"}',
    searchName: 'Vibrava (SSP 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Flygon ex',
    tcgApiId: 'sv8-106',
    number: '106',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/106.png","large":"https://images.pokemontcg.io/sv8/106_hires.png"}',
    searchName: 'Flygon ex (SSP 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Gastrodon',
    tcgApiId: 'sv8-107',
    number: '107',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/107.png","large":"https://images.pokemontcg.io/sv8/107_hires.png"}',
    searchName: 'Gastrodon (SSP 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Drilbur',
    tcgApiId: 'sv8-108',
    number: '108',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/108.png","large":"https://images.pokemontcg.io/sv8/108_hires.png"}',
    searchName: 'Drilbur (SSP 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Excadrill',
    tcgApiId: 'sv8-109',
    number: '109',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/109.png","large":"https://images.pokemontcg.io/sv8/109_hires.png"}',
    searchName: 'Excadrill (SSP 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Landorus',
    tcgApiId: 'sv8-110',
    number: '110',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/110.png","large":"https://images.pokemontcg.io/sv8/110_hires.png"}',
    searchName: 'Landorus (SSP 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Passimian',
    tcgApiId: 'sv8-111',
    number: '111',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/111.png","large":"https://images.pokemontcg.io/sv8/111_hires.png"}',
    searchName: 'Passimian (SSP 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Clobbopus',
    tcgApiId: 'sv8-112',
    number: '112',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/112.png","large":"https://images.pokemontcg.io/sv8/112_hires.png"}',
    searchName: 'Clobbopus (SSP 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Grapploct',
    tcgApiId: 'sv8-113',
    number: '113',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/113.png","large":"https://images.pokemontcg.io/sv8/113_hires.png"}',
    searchName: 'Grapploct (SSP 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Glimmet',
    tcgApiId: 'sv8-114',
    number: '114',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/114.png","large":"https://images.pokemontcg.io/sv8/114_hires.png"}',
    searchName: 'Glimmet (SSP 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Glimmora',
    tcgApiId: 'sv8-115',
    number: '115',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/115.png","large":"https://images.pokemontcg.io/sv8/115_hires.png"}',
    searchName: 'Glimmora (SSP 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Koraidon',
    tcgApiId: 'sv8-116',
    number: '116',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/116.png","large":"https://images.pokemontcg.io/sv8/116_hires.png"}',
    searchName: 'Koraidon (SSP 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Deino',
    tcgApiId: 'sv8-117',
    number: '117',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/117.png","large":"https://images.pokemontcg.io/sv8/117_hires.png"}',
    searchName: 'Deino (SSP 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Zweilous',
    tcgApiId: 'sv8-118',
    number: '118',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/118.png","large":"https://images.pokemontcg.io/sv8/118_hires.png"}',
    searchName: 'Zweilous (SSP 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Hydreigon ex',
    tcgApiId: 'sv8-119',
    number: '119',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/119.png","large":"https://images.pokemontcg.io/sv8/119_hires.png"}',
    searchName: 'Hydreigon ex (SSP 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Shroodle',
    tcgApiId: 'sv8-120',
    number: '120',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/120.png","large":"https://images.pokemontcg.io/sv8/120_hires.png"}',
    searchName: 'Shroodle (SSP 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Grafaiai',
    tcgApiId: 'sv8-121',
    number: '121',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/121.png","large":"https://images.pokemontcg.io/sv8/121_hires.png"}',
    searchName: 'Grafaiai (SSP 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Alolan Diglett',
    tcgApiId: 'sv8-122',
    number: '122',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/122.png","large":"https://images.pokemontcg.io/sv8/122_hires.png"}',
    searchName: 'Alolan Diglett (SSP 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Alolan Dugtrio',
    tcgApiId: 'sv8-123',
    number: '123',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/123.png","large":"https://images.pokemontcg.io/sv8/123_hires.png"}',
    searchName: 'Alolan Dugtrio (SSP 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Skarmory',
    tcgApiId: 'sv8-124',
    number: '124',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/124.png","large":"https://images.pokemontcg.io/sv8/124_hires.png"}',
    searchName: 'Skarmory (SSP 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Registeel',
    tcgApiId: 'sv8-125',
    number: '125',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/125.png","large":"https://images.pokemontcg.io/sv8/125_hires.png"}',
    searchName: 'Registeel (SSP 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Bronzor',
    tcgApiId: 'sv8-126',
    number: '126',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/126.png","large":"https://images.pokemontcg.io/sv8/126_hires.png"}',
    searchName: 'Bronzor (SSP 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Bronzong',
    tcgApiId: 'sv8-127',
    number: '127',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/127.png","large":"https://images.pokemontcg.io/sv8/127_hires.png"}',
    searchName: 'Bronzong (SSP 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Klefki',
    tcgApiId: 'sv8-128',
    number: '128',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/128.png","large":"https://images.pokemontcg.io/sv8/128_hires.png"}',
    searchName: 'Klefki (SSP 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Duraludon',
    tcgApiId: 'sv8-129',
    number: '129',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/129.png","large":"https://images.pokemontcg.io/sv8/129_hires.png"}',
    searchName: 'Duraludon (SSP 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Archaludon ex',
    tcgApiId: 'sv8-130',
    number: '130',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/130.png","large":"https://images.pokemontcg.io/sv8/130_hires.png"}',
    searchName: 'Archaludon ex (SSP 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Gholdengo',
    tcgApiId: 'sv8-131',
    number: '131',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/131.png","large":"https://images.pokemontcg.io/sv8/131_hires.png"}',
    searchName: 'Gholdengo (SSP 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Iron Crown',
    tcgApiId: 'sv8-132',
    number: '132',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/132.png","large":"https://images.pokemontcg.io/sv8/132_hires.png"}',
    searchName: 'Iron Crown (SSP 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Alolan Exeggutor ex',
    tcgApiId: 'sv8-133',
    number: '133',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/133.png","large":"https://images.pokemontcg.io/sv8/133_hires.png"}',
    searchName: 'Alolan Exeggutor ex (SSP 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Altaria',
    tcgApiId: 'sv8-134',
    number: '134',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/134.png","large":"https://images.pokemontcg.io/sv8/134_hires.png"}',
    searchName: 'Altaria (SSP 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Dialga',
    tcgApiId: 'sv8-135',
    number: '135',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/135.png","large":"https://images.pokemontcg.io/sv8/135_hires.png"}',
    searchName: 'Dialga (SSP 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Palkia',
    tcgApiId: 'sv8-136',
    number: '136',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/136.png","large":"https://images.pokemontcg.io/sv8/136_hires.png"}',
    searchName: 'Palkia (SSP 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Turtonator',
    tcgApiId: 'sv8-137',
    number: '137',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/137.png","large":"https://images.pokemontcg.io/sv8/137_hires.png"}',
    searchName: 'Turtonator (SSP 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Applin',
    tcgApiId: 'sv8-138',
    number: '138',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/138.png","large":"https://images.pokemontcg.io/sv8/138_hires.png"}',
    searchName: 'Applin (SSP 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Flapple',
    tcgApiId: 'sv8-139',
    number: '139',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/139.png","large":"https://images.pokemontcg.io/sv8/139_hires.png"}',
    searchName: 'Flapple (SSP 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Appletun',
    tcgApiId: 'sv8-140',
    number: '140',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/140.png","large":"https://images.pokemontcg.io/sv8/140_hires.png"}',
    searchName: 'Appletun (SSP 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Eternatus',
    tcgApiId: 'sv8-141',
    number: '141',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/141.png","large":"https://images.pokemontcg.io/sv8/141_hires.png"}',
    searchName: 'Eternatus (SSP 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Tatsugiri ex',
    tcgApiId: 'sv8-142',
    number: '142',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/142.png","large":"https://images.pokemontcg.io/sv8/142_hires.png"}',
    searchName: 'Tatsugiri ex (SSP 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Eevee',
    tcgApiId: 'sv8-143',
    number: '143',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/143.png","large":"https://images.pokemontcg.io/sv8/143_hires.png"}',
    searchName: 'Eevee (SSP 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Snorlax',
    tcgApiId: 'sv8-144',
    number: '144',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/144.png","large":"https://images.pokemontcg.io/sv8/144_hires.png"}',
    searchName: 'Snorlax (SSP 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Slakoth',
    tcgApiId: 'sv8-145',
    number: '145',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/145.png","large":"https://images.pokemontcg.io/sv8/145_hires.png"}',
    searchName: 'Slakoth (SSP 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Vigoroth',
    tcgApiId: 'sv8-146',
    number: '146',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/146.png","large":"https://images.pokemontcg.io/sv8/146_hires.png"}',
    searchName: 'Vigoroth (SSP 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Slaking ex',
    tcgApiId: 'sv8-147',
    number: '147',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/147.png","large":"https://images.pokemontcg.io/sv8/147_hires.png"}',
    searchName: 'Slaking ex (SSP 147)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Swablu',
    tcgApiId: 'sv8-148',
    number: '148',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/148.png","large":"https://images.pokemontcg.io/sv8/148_hires.png"}',
    searchName: 'Swablu (SSP 148)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Zangoose',
    tcgApiId: 'sv8-149',
    number: '149',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/149.png","large":"https://images.pokemontcg.io/sv8/149_hires.png"}',
    searchName: 'Zangoose (SSP 149)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Kecleon',
    tcgApiId: 'sv8-150',
    number: '150',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/150.png","large":"https://images.pokemontcg.io/sv8/150_hires.png"}',
    searchName: 'Kecleon (SSP 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Bouffalant',
    tcgApiId: 'sv8-151',
    number: '151',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/151.png","large":"https://images.pokemontcg.io/sv8/151_hires.png"}',
    searchName: 'Bouffalant (SSP 151)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Rufflet',
    tcgApiId: 'sv8-152',
    number: '152',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/152.png","large":"https://images.pokemontcg.io/sv8/152_hires.png"}',
    searchName: 'Rufflet (SSP 152)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Braviary',
    tcgApiId: 'sv8-153',
    number: '153',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/153.png","large":"https://images.pokemontcg.io/sv8/153_hires.png"}',
    searchName: 'Braviary (SSP 153)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Helioptile',
    tcgApiId: 'sv8-154',
    number: '154',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/154.png","large":"https://images.pokemontcg.io/sv8/154_hires.png"}',
    searchName: 'Helioptile (SSP 154)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Heliolisk',
    tcgApiId: 'sv8-155',
    number: '155',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/155.png","large":"https://images.pokemontcg.io/sv8/155_hires.png"}',
    searchName: 'Heliolisk (SSP 155)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Oranguru',
    tcgApiId: 'sv8-156',
    number: '156',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/156.png","large":"https://images.pokemontcg.io/sv8/156_hires.png"}',
    searchName: 'Oranguru (SSP 156)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Tandemaus',
    tcgApiId: 'sv8-157',
    number: '157',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/157.png","large":"https://images.pokemontcg.io/sv8/157_hires.png"}',
    searchName: 'Tandemaus (SSP 157)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Maushold',
    tcgApiId: 'sv8-158',
    number: '158',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/158.png","large":"https://images.pokemontcg.io/sv8/158_hires.png"}',
    searchName: 'Maushold (SSP 158)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Cyclizar ex',
    tcgApiId: 'sv8-159',
    number: '159',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/159.png","large":"https://images.pokemontcg.io/sv8/159_hires.png"}',
    searchName: 'Cyclizar ex (SSP 159)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Flamigo ex',
    tcgApiId: 'sv8-160',
    number: '160',
    rarity: 'Double Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/160.png","large":"https://images.pokemontcg.io/sv8/160_hires.png"}',
    searchName: 'Flamigo ex (SSP 160)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Terapagos',
    tcgApiId: 'sv8-161',
    number: '161',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/161.png","large":"https://images.pokemontcg.io/sv8/161_hires.png"}',
    searchName: 'Terapagos (SSP 161)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Amulet of Hope',
    tcgApiId: 'sv8-162',
    number: '162',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/162.png","large":"https://images.pokemontcg.io/sv8/162_hires.png"}',
    searchName: 'Amulet of Hope (SSP 162)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Babiri Berry',
    tcgApiId: 'sv8-163',
    number: '163',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/163.png","large":"https://images.pokemontcg.io/sv8/163_hires.png"}',
    searchName: 'Babiri Berry (SSP 163)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Brilliant Blender',
    tcgApiId: 'sv8-164',
    number: '164',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/164.png","large":"https://images.pokemontcg.io/sv8/164_hires.png"}',
    searchName: 'Brilliant Blender (SSP 164)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Call Bell',
    tcgApiId: 'sv8-165',
    number: '165',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/165.png","large":"https://images.pokemontcg.io/sv8/165_hires.png"}',
    searchName: 'Call Bell (SSP 165)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Chill Teaser Toy',
    tcgApiId: 'sv8-166',
    number: '166',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/166.png","large":"https://images.pokemontcg.io/sv8/166_hires.png"}',
    searchName: 'Chill Teaser Toy (SSP 166)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: "Clemont's Quick Wit",
    tcgApiId: 'sv8-167',
    number: '167',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/167.png","large":"https://images.pokemontcg.io/sv8/167_hires.png"}',
    searchName: "Clemont's Quick Wit (SSP 167)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Colbur Berry',
    tcgApiId: 'sv8-168',
    number: '168',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/168.png","large":"https://images.pokemontcg.io/sv8/168_hires.png"}',
    searchName: 'Colbur Berry (SSP 168)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Counter Gain',
    tcgApiId: 'sv8-169',
    number: '169',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/169.png","large":"https://images.pokemontcg.io/sv8/169_hires.png"}',
    searchName: 'Counter Gain (SSP 169)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Cyrano',
    tcgApiId: 'sv8-170',
    number: '170',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/170.png","large":"https://images.pokemontcg.io/sv8/170_hires.png"}',
    searchName: 'Cyrano (SSP 170)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Deduction Kit',
    tcgApiId: 'sv8-171',
    number: '171',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/171.png","large":"https://images.pokemontcg.io/sv8/171_hires.png"}',
    searchName: 'Deduction Kit (SSP 171)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Dragon Elixir',
    tcgApiId: 'sv8-172',
    number: '172',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/172.png","large":"https://images.pokemontcg.io/sv8/172_hires.png"}',
    searchName: 'Dragon Elixir (SSP 172)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Drasna',
    tcgApiId: 'sv8-173',
    number: '173',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/173.png","large":"https://images.pokemontcg.io/sv8/173_hires.png"}',
    searchName: 'Drasna (SSP 173)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Drayton',
    tcgApiId: 'sv8-174',
    number: '174',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/174.png","large":"https://images.pokemontcg.io/sv8/174_hires.png"}',
    searchName: 'Drayton (SSP 174)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Dusk Ball',
    tcgApiId: 'sv8-175',
    number: '175',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/175.png","large":"https://images.pokemontcg.io/sv8/175_hires.png"}',
    searchName: 'Dusk Ball (SSP 175)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Energy Search Pro',
    tcgApiId: 'sv8-176',
    number: '176',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/176.png","large":"https://images.pokemontcg.io/sv8/176_hires.png"}',
    searchName: 'Energy Search Pro (SSP 176)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Gravity Mountain',
    tcgApiId: 'sv8-177',
    number: '177',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/177.png","large":"https://images.pokemontcg.io/sv8/177_hires.png"}',
    searchName: 'Gravity Mountain (SSP 177)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: "Jasmine's Gaze",
    tcgApiId: 'sv8-178',
    number: '178',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/178.png","large":"https://images.pokemontcg.io/sv8/178_hires.png"}',
    searchName: "Jasmine's Gaze (SSP 178)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: "Lisia's Appeal",
    tcgApiId: 'sv8-179',
    number: '179',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/179.png","large":"https://images.pokemontcg.io/sv8/179_hires.png"}',
    searchName: "Lisia's Appeal (SSP 179)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Lively Stadium',
    tcgApiId: 'sv8-180',
    number: '180',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/180.png","large":"https://images.pokemontcg.io/sv8/180_hires.png"}',
    searchName: 'Lively Stadium (SSP 180)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Meddling Memo',
    tcgApiId: 'sv8-181',
    number: '181',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/181.png","large":"https://images.pokemontcg.io/sv8/181_hires.png"}',
    searchName: 'Meddling Memo (SSP 181)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Megaton Blower',
    tcgApiId: 'sv8-182',
    number: '182',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/182.png","large":"https://images.pokemontcg.io/sv8/182_hires.png"}',
    searchName: 'Megaton Blower (SSP 182)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Miracle Headset',
    tcgApiId: 'sv8-183',
    number: '183',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/183.png","large":"https://images.pokemontcg.io/sv8/183_hires.png"}',
    searchName: 'Miracle Headset (SSP 183)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Passho Berry',
    tcgApiId: 'sv8-184',
    number: '184',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/184.png","large":"https://images.pokemontcg.io/sv8/184_hires.png"}',
    searchName: 'Passho Berry (SSP 184)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Precious Trolley',
    tcgApiId: 'sv8-185',
    number: '185',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/185.png","large":"https://images.pokemontcg.io/sv8/185_hires.png"}',
    searchName: 'Precious Trolley (SSP 185)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Scramble Switch',
    tcgApiId: 'sv8-186',
    number: '186',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/186.png","large":"https://images.pokemontcg.io/sv8/186_hires.png"}',
    searchName: 'Scramble Switch (SSP 186)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Surfer',
    tcgApiId: 'sv8-187',
    number: '187',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/187.png","large":"https://images.pokemontcg.io/sv8/187_hires.png"}',
    searchName: 'Surfer (SSP 187)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Technical Machine: Fluorite',
    tcgApiId: 'sv8-188',
    number: '188',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/188.png","large":"https://images.pokemontcg.io/sv8/188_hires.png"}',
    searchName: 'Technical Machine: Fluorite (SSP 188)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Tera Orb',
    tcgApiId: 'sv8-189',
    number: '189',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/189.png","large":"https://images.pokemontcg.io/sv8/189_hires.png"}',
    searchName: 'Tera Orb (SSP 189)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Tyme',
    tcgApiId: 'sv8-190',
    number: '190',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/190.png","large":"https://images.pokemontcg.io/sv8/190_hires.png"}',
    searchName: 'Tyme (SSP 190)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Enriching Energy',
    tcgApiId: 'sv8-191',
    number: '191',
    rarity: 'ACE SPEC Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/191.png","large":"https://images.pokemontcg.io/sv8/191_hires.png"}',
    searchName: 'Enriching Energy (SSP 191)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Exeggcute',
    tcgApiId: 'sv8-192',
    number: '192',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/192.png","large":"https://images.pokemontcg.io/sv8/192_hires.png"}',
    searchName: 'Exeggcute (SSP 192)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Vivillon',
    tcgApiId: 'sv8-193',
    number: '193',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/193.png","large":"https://images.pokemontcg.io/sv8/193_hires.png"}',
    searchName: 'Vivillon (SSP 193)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Shiinotic',
    tcgApiId: 'sv8-194',
    number: '194',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/194.png","large":"https://images.pokemontcg.io/sv8/194_hires.png"}',
    searchName: 'Shiinotic (SSP 194)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Castform Sunny Form',
    tcgApiId: 'sv8-195',
    number: '195',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/195.png","large":"https://images.pokemontcg.io/sv8/195_hires.png"}',
    searchName: 'Castform Sunny Form (SSP 195)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Larvesta',
    tcgApiId: 'sv8-196',
    number: '196',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/196.png","large":"https://images.pokemontcg.io/sv8/196_hires.png"}',
    searchName: 'Larvesta (SSP 196)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Ceruledge',
    tcgApiId: 'sv8-197',
    number: '197',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/197.png","large":"https://images.pokemontcg.io/sv8/197_hires.png"}',
    searchName: 'Ceruledge (SSP 197)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Feebas',
    tcgApiId: 'sv8-198',
    number: '198',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/198.png","large":"https://images.pokemontcg.io/sv8/198_hires.png"}',
    searchName: 'Feebas (SSP 198)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Spheal',
    tcgApiId: 'sv8-199',
    number: '199',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/199.png","large":"https://images.pokemontcg.io/sv8/199_hires.png"}',
    searchName: 'Spheal (SSP 199)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Bruxish',
    tcgApiId: 'sv8-200',
    number: '200',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/200.png","large":"https://images.pokemontcg.io/sv8/200_hires.png"}',
    searchName: 'Bruxish (SSP 200)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Cetitan',
    tcgApiId: 'sv8-201',
    number: '201',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/201.png","large":"https://images.pokemontcg.io/sv8/201_hires.png"}',
    searchName: 'Cetitan (SSP 201)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Stunfisk',
    tcgApiId: 'sv8-202',
    number: '202',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/202.png","large":"https://images.pokemontcg.io/sv8/202_hires.png"}',
    searchName: 'Stunfisk (SSP 202)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Latios',
    tcgApiId: 'sv8-203',
    number: '203',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/203.png","large":"https://images.pokemontcg.io/sv8/203_hires.png"}',
    searchName: 'Latios (SSP 203)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Mesprit',
    tcgApiId: 'sv8-204',
    number: '204',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/204.png","large":"https://images.pokemontcg.io/sv8/204_hires.png"}',
    searchName: 'Mesprit (SSP 204)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Phanpy',
    tcgApiId: 'sv8-205',
    number: '205',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/205.png","large":"https://images.pokemontcg.io/sv8/205_hires.png"}',
    searchName: 'Phanpy (SSP 205)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Vibrava',
    tcgApiId: 'sv8-206',
    number: '206',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/206.png","large":"https://images.pokemontcg.io/sv8/206_hires.png"}',
    searchName: 'Vibrava (SSP 206)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Clobbopus',
    tcgApiId: 'sv8-207',
    number: '207',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/207.png","large":"https://images.pokemontcg.io/sv8/207_hires.png"}',
    searchName: 'Clobbopus (SSP 207)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Alolan Dugtrio',
    tcgApiId: 'sv8-208',
    number: '208',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/208.png","large":"https://images.pokemontcg.io/sv8/208_hires.png"}',
    searchName: 'Alolan Dugtrio (SSP 208)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Skarmory',
    tcgApiId: 'sv8-209',
    number: '209',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/209.png","large":"https://images.pokemontcg.io/sv8/209_hires.png"}',
    searchName: 'Skarmory (SSP 209)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Flapple',
    tcgApiId: 'sv8-210',
    number: '210',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/210.png","large":"https://images.pokemontcg.io/sv8/210_hires.png"}',
    searchName: 'Flapple (SSP 210)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Appletun',
    tcgApiId: 'sv8-211',
    number: '211',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/211.png","large":"https://images.pokemontcg.io/sv8/211_hires.png"}',
    searchName: 'Appletun (SSP 211)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Slakoth',
    tcgApiId: 'sv8-212',
    number: '212',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/212.png","large":"https://images.pokemontcg.io/sv8/212_hires.png"}',
    searchName: 'Slakoth (SSP 212)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Kecleon',
    tcgApiId: 'sv8-213',
    number: '213',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/213.png","large":"https://images.pokemontcg.io/sv8/213_hires.png"}',
    searchName: 'Kecleon (SSP 213)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Braviary',
    tcgApiId: 'sv8-214',
    number: '214',
    rarity: 'Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/214.png","large":"https://images.pokemontcg.io/sv8/214_hires.png"}',
    searchName: 'Braviary (SSP 214)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Durant ex',
    tcgApiId: 'sv8-215',
    number: '215',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/215.png","large":"https://images.pokemontcg.io/sv8/215_hires.png"}',
    searchName: 'Durant ex (SSP 215)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Scovillain ex',
    tcgApiId: 'sv8-216',
    number: '216',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/216.png","large":"https://images.pokemontcg.io/sv8/216_hires.png"}',
    searchName: 'Scovillain ex (SSP 216)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Milotic ex',
    tcgApiId: 'sv8-217',
    number: '217',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/217.png","large":"https://images.pokemontcg.io/sv8/217_hires.png"}',
    searchName: 'Milotic ex (SSP 217)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Black Kyurem ex',
    tcgApiId: 'sv8-218',
    number: '218',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/218.png","large":"https://images.pokemontcg.io/sv8/218_hires.png"}',
    searchName: 'Black Kyurem ex (SSP 218)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Pikachu ex',
    tcgApiId: 'sv8-219',
    number: '219',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/219.png","large":"https://images.pokemontcg.io/sv8/219_hires.png"}',
    searchName: 'Pikachu ex (SSP 219)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Latias ex',
    tcgApiId: 'sv8-220',
    number: '220',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/220.png","large":"https://images.pokemontcg.io/sv8/220_hires.png"}',
    searchName: 'Latias ex (SSP 220)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Palossand ex',
    tcgApiId: 'sv8-221',
    number: '221',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/221.png","large":"https://images.pokemontcg.io/sv8/221_hires.png"}',
    searchName: 'Palossand ex (SSP 221)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Flygon ex',
    tcgApiId: 'sv8-222',
    number: '222',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/222.png","large":"https://images.pokemontcg.io/sv8/222_hires.png"}',
    searchName: 'Flygon ex (SSP 222)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Hydreigon ex',
    tcgApiId: 'sv8-223',
    number: '223',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/223.png","large":"https://images.pokemontcg.io/sv8/223_hires.png"}',
    searchName: 'Hydreigon ex (SSP 223)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Archaludon ex',
    tcgApiId: 'sv8-224',
    number: '224',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/224.png","large":"https://images.pokemontcg.io/sv8/224_hires.png"}',
    searchName: 'Archaludon ex (SSP 224)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Alolan Exeggutor ex',
    tcgApiId: 'sv8-225',
    number: '225',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/225.png","large":"https://images.pokemontcg.io/sv8/225_hires.png"}',
    searchName: 'Alolan Exeggutor ex (SSP 225)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Tatsugiri ex',
    tcgApiId: 'sv8-226',
    number: '226',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/226.png","large":"https://images.pokemontcg.io/sv8/226_hires.png"}',
    searchName: 'Tatsugiri ex (SSP 226)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Slaking ex',
    tcgApiId: 'sv8-227',
    number: '227',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/227.png","large":"https://images.pokemontcg.io/sv8/227_hires.png"}',
    searchName: 'Slaking ex (SSP 227)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Cyclizar ex',
    tcgApiId: 'sv8-228',
    number: '228',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/228.png","large":"https://images.pokemontcg.io/sv8/228_hires.png"}',
    searchName: 'Cyclizar ex (SSP 228)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: "Clemont's Quick Wit",
    tcgApiId: 'sv8-229',
    number: '229',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/229.png","large":"https://images.pokemontcg.io/sv8/229_hires.png"}',
    searchName: "Clemont's Quick Wit (SSP 229)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Cyrano',
    tcgApiId: 'sv8-230',
    number: '230',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/230.png","large":"https://images.pokemontcg.io/sv8/230_hires.png"}',
    searchName: 'Cyrano (SSP 230)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Drasna',
    tcgApiId: 'sv8-231',
    number: '231',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/231.png","large":"https://images.pokemontcg.io/sv8/231_hires.png"}',
    searchName: 'Drasna (SSP 231)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Drayton',
    tcgApiId: 'sv8-232',
    number: '232',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/232.png","large":"https://images.pokemontcg.io/sv8/232_hires.png"}',
    searchName: 'Drayton (SSP 232)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: "Jasmine's Gaze",
    tcgApiId: 'sv8-233',
    number: '233',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/233.png","large":"https://images.pokemontcg.io/sv8/233_hires.png"}',
    searchName: "Jasmine's Gaze (SSP 233)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: "Lisia's Appeal",
    tcgApiId: 'sv8-234',
    number: '234',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/234.png","large":"https://images.pokemontcg.io/sv8/234_hires.png"}',
    searchName: "Lisia's Appeal (SSP 234)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Surfer',
    tcgApiId: 'sv8-235',
    number: '235',
    rarity: 'Ultra Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/235.png","large":"https://images.pokemontcg.io/sv8/235_hires.png"}',
    searchName: 'Surfer (SSP 235)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Durant ex',
    tcgApiId: 'sv8-236',
    number: '236',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/236.png","large":"https://images.pokemontcg.io/sv8/236_hires.png"}',
    searchName: 'Durant ex (SSP 236)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Milotic ex',
    tcgApiId: 'sv8-237',
    number: '237',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/237.png","large":"https://images.pokemontcg.io/sv8/237_hires.png"}',
    searchName: 'Milotic ex (SSP 237)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Pikachu ex',
    tcgApiId: 'sv8-238',
    number: '238',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/238.png","large":"https://images.pokemontcg.io/sv8/238_hires.png"}',
    searchName: 'Pikachu ex (SSP 238)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Latias ex',
    tcgApiId: 'sv8-239',
    number: '239',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/239.png","large":"https://images.pokemontcg.io/sv8/239_hires.png"}',
    searchName: 'Latias ex (SSP 239)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Hydreigon ex',
    tcgApiId: 'sv8-240',
    number: '240',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/240.png","large":"https://images.pokemontcg.io/sv8/240_hires.png"}',
    searchName: 'Hydreigon ex (SSP 240)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Archaludon ex',
    tcgApiId: 'sv8-241',
    number: '241',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/241.png","large":"https://images.pokemontcg.io/sv8/241_hires.png"}',
    searchName: 'Archaludon ex (SSP 241)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Alolan Exeggutor ex',
    tcgApiId: 'sv8-242',
    number: '242',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/242.png","large":"https://images.pokemontcg.io/sv8/242_hires.png"}',
    searchName: 'Alolan Exeggutor ex (SSP 242)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: "Clemont's Quick Wit",
    tcgApiId: 'sv8-243',
    number: '243',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/243.png","large":"https://images.pokemontcg.io/sv8/243_hires.png"}',
    searchName: "Clemont's Quick Wit (SSP 243)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Drayton',
    tcgApiId: 'sv8-244',
    number: '244',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/244.png","large":"https://images.pokemontcg.io/sv8/244_hires.png"}',
    searchName: 'Drayton (SSP 244)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: "Jasmine's Gaze",
    tcgApiId: 'sv8-245',
    number: '245',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/245.png","large":"https://images.pokemontcg.io/sv8/245_hires.png"}',
    searchName: "Jasmine's Gaze (SSP 245)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: "Lisia's Appeal",
    tcgApiId: 'sv8-246',
    number: '246',
    rarity: 'Special Illustration Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/246.png","large":"https://images.pokemontcg.io/sv8/246_hires.png"}',
    searchName: "Lisia's Appeal (SSP 246)",
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Pikachu ex',
    tcgApiId: 'sv8-247',
    number: '247',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/247.png","large":"https://images.pokemontcg.io/sv8/247_hires.png"}',
    searchName: 'Pikachu ex (SSP 247)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Alolan Exeggutor ex',
    tcgApiId: 'sv8-248',
    number: '248',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/248.png","large":"https://images.pokemontcg.io/sv8/248_hires.png"}',
    searchName: 'Alolan Exeggutor ex (SSP 248)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Counter Gain',
    tcgApiId: 'sv8-249',
    number: '249',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/249.png","large":"https://images.pokemontcg.io/sv8/249_hires.png"}',
    searchName: 'Counter Gain (SSP 249)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Gravity Mountain',
    tcgApiId: 'sv8-250',
    number: '250',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/250.png","large":"https://images.pokemontcg.io/sv8/250_hires.png"}',
    searchName: 'Gravity Mountain (SSP 250)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Night Stretcher',
    tcgApiId: 'sv8-251',
    number: '251',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/251.png","large":"https://images.pokemontcg.io/sv8/251_hires.png"}',
    searchName: 'Night Stretcher (SSP 251)',
  },
  {
    tcgId: 'pokemon',
    setId: 'sv8',
    name: 'Jet Energy',
    tcgApiId: 'sv8-252',
    number: '252',
    rarity: 'Hyper Rare',
    images:
      '{"small":"https://images.pokemontcg.io/sv8/252.png","large":"https://images.pokemontcg.io/sv8/252_hires.png"}',
    searchName: 'Jet Energy (SSP 252)',
  },
];
