export const cardSeedSvp = [
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Sprigatito',
    tcgApiId: 'svp-1',
    number: '1',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/1.png","large":"https://images.pokemontcg.io/svp/1_hires.png"}',
    searchName: 'Sprigatito (PR-SV 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Fuecoco',
    tcgApiId: 'svp-2',
    number: '2',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/2.png","large":"https://images.pokemontcg.io/svp/2_hires.png"}',
    searchName: 'Fuecoco (PR-SV 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Quaxly',
    tcgApiId: 'svp-3',
    number: '3',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/3.png","large":"https://images.pokemontcg.io/svp/3_hires.png"}',
    searchName: 'Quaxly (PR-SV 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Mimikyu ex',
    tcgApiId: 'svp-4',
    number: '4',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/4.png","large":"https://images.pokemontcg.io/svp/4_hires.png"}',
    searchName: 'Mimikyu ex (PR-SV 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Quaquaval',
    tcgApiId: 'svp-5',
    number: '5',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/5.png","large":"https://images.pokemontcg.io/svp/5_hires.png"}',
    searchName: 'Quaquaval (PR-SV 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pawmot',
    tcgApiId: 'svp-6',
    number: '6',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/6.png","large":"https://images.pokemontcg.io/svp/6_hires.png"}',
    searchName: 'Pawmot (PR-SV 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Hawlucha',
    tcgApiId: 'svp-7',
    number: '7',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/7.png","large":"https://images.pokemontcg.io/svp/7_hires.png"}',
    searchName: 'Hawlucha (PR-SV 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Revavroom',
    tcgApiId: 'svp-8',
    number: '8',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/8.png","large":"https://images.pokemontcg.io/svp/8_hires.png"}',
    searchName: 'Revavroom (PR-SV 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Spidops',
    tcgApiId: 'svp-9',
    number: '9',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/9.png","large":"https://images.pokemontcg.io/svp/9_hires.png"}',
    searchName: 'Spidops (PR-SV 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Espathra',
    tcgApiId: 'svp-10',
    number: '10',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/10.png","large":"https://images.pokemontcg.io/svp/10_hires.png"}',
    searchName: 'Espathra (PR-SV 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Arcanine',
    tcgApiId: 'svp-11',
    number: '11',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/11.png","large":"https://images.pokemontcg.io/svp/11_hires.png"}',
    searchName: 'Arcanine (PR-SV 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Dondozo',
    tcgApiId: 'svp-12',
    number: '12',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/12.png","large":"https://images.pokemontcg.io/svp/12_hires.png"}',
    searchName: 'Dondozo (PR-SV 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Miraidon',
    tcgApiId: 'svp-13',
    number: '13',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/13.png","large":"https://images.pokemontcg.io/svp/13_hires.png"}',
    searchName: 'Miraidon (PR-SV 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Koraidon',
    tcgApiId: 'svp-14',
    number: '14',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/14.png","large":"https://images.pokemontcg.io/svp/14_hires.png"}',
    searchName: 'Koraidon (PR-SV 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Flaaffy',
    tcgApiId: 'svp-15',
    number: '15',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/15.png","large":"https://images.pokemontcg.io/svp/15_hires.png"}',
    searchName: 'Flaaffy (PR-SV 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Ampharos ex',
    tcgApiId: 'svp-16',
    number: '16',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/16.png","large":"https://images.pokemontcg.io/svp/16_hires.png"}',
    searchName: 'Ampharos ex (PR-SV 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Lucario ex',
    tcgApiId: 'svp-17',
    number: '17',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/17.png","large":"https://images.pokemontcg.io/svp/17_hires.png"}',
    searchName: 'Lucario ex (PR-SV 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Cyclizar ex',
    tcgApiId: 'svp-18',
    number: '18',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/18.png","large":"https://images.pokemontcg.io/svp/18_hires.png"}',
    searchName: 'Cyclizar ex (PR-SV 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Baxcalibur',
    tcgApiId: 'svp-19',
    number: '19',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/19.png","large":"https://images.pokemontcg.io/svp/19_hires.png"}',
    searchName: 'Baxcalibur (PR-SV 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Tinkaton',
    tcgApiId: 'svp-20',
    number: '20',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/20.png","large":"https://images.pokemontcg.io/svp/20_hires.png"}',
    searchName: 'Tinkaton (PR-SV 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Murkrow',
    tcgApiId: 'svp-21',
    number: '21',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/21.png","large":"https://images.pokemontcg.io/svp/21_hires.png"}',
    searchName: 'Murkrow (PR-SV 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pelipper',
    tcgApiId: 'svp-22',
    number: '22',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/22.png","large":"https://images.pokemontcg.io/svp/22_hires.png"}',
    searchName: 'Pelipper (PR-SV 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Smoliv',
    tcgApiId: 'svp-23',
    number: '23',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/23.png","large":"https://images.pokemontcg.io/svp/23_hires.png"}',
    searchName: 'Smoliv (PR-SV 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Growlithe',
    tcgApiId: 'svp-24',
    number: '24',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/24.png","large":"https://images.pokemontcg.io/svp/24_hires.png"}',
    searchName: 'Growlithe (PR-SV 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Tinkatink',
    tcgApiId: 'svp-25',
    number: '25',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/25.png","large":"https://images.pokemontcg.io/svp/25_hires.png"}',
    searchName: 'Tinkatink (PR-SV 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Varoom',
    tcgApiId: 'svp-26',
    number: '26',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/26.png","large":"https://images.pokemontcg.io/svp/26_hires.png"}',
    searchName: 'Varoom (PR-SV 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pikachu',
    tcgApiId: 'svp-27',
    number: '27',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/27.png","large":"https://images.pokemontcg.io/svp/27_hires.png"}',
    searchName: 'Pikachu (PR-SV 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Miraidon ex',
    tcgApiId: 'svp-28',
    number: '28',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/28.png","large":"https://images.pokemontcg.io/svp/28_hires.png"}',
    searchName: 'Miraidon ex (PR-SV 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Koraidon ex',
    tcgApiId: 'svp-29',
    number: '29',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/29.png","large":"https://images.pokemontcg.io/svp/29_hires.png"}',
    searchName: 'Koraidon ex (PR-SV 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Chien-Pao ex',
    tcgApiId: 'svp-30',
    number: '30',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/30.png","large":"https://images.pokemontcg.io/svp/30_hires.png"}',
    searchName: 'Chien-Pao ex (PR-SV 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Tinkaton ex',
    tcgApiId: 'svp-31',
    number: '31',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/31.png","large":"https://images.pokemontcg.io/svp/31_hires.png"}',
    searchName: 'Tinkaton ex (PR-SV 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Annihilape ex',
    tcgApiId: 'svp-32',
    number: '32',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/32.png","large":"https://images.pokemontcg.io/svp/32_hires.png"}',
    searchName: 'Annihilape ex (PR-SV 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Meowscarada ex',
    tcgApiId: 'svp-33',
    number: '33',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/33.png","large":"https://images.pokemontcg.io/svp/33_hires.png"}',
    searchName: 'Meowscarada ex (PR-SV 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Skeledirge ex',
    tcgApiId: 'svp-34',
    number: '34',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/34.png","large":"https://images.pokemontcg.io/svp/34_hires.png"}',
    searchName: 'Skeledirge ex (PR-SV 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Quaquaval ex',
    tcgApiId: 'svp-35',
    number: '35',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/35.png","large":"https://images.pokemontcg.io/svp/35_hires.png"}',
    searchName: 'Quaquaval ex (PR-SV 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Palafin',
    tcgApiId: 'svp-36',
    number: '36',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/36.png","large":"https://images.pokemontcg.io/svp/36_hires.png"}',
    searchName: 'Palafin (PR-SV 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Cleffa',
    tcgApiId: 'svp-37',
    number: '37',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/37.png","large":"https://images.pokemontcg.io/svp/37_hires.png"}',
    searchName: 'Cleffa (PR-SV 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Togekiss',
    tcgApiId: 'svp-38',
    number: '38',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/38.png","large":"https://images.pokemontcg.io/svp/38_hires.png"}',
    searchName: 'Togekiss (PR-SV 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Mawile',
    tcgApiId: 'svp-39',
    number: '39',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/39.png","large":"https://images.pokemontcg.io/svp/39_hires.png"}',
    searchName: 'Mawile (PR-SV 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pawmi',
    tcgApiId: 'svp-40',
    number: '40',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/40.png","large":"https://images.pokemontcg.io/svp/40_hires.png"}',
    searchName: 'Pawmi (PR-SV 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Paldean Wooper',
    tcgApiId: 'svp-41',
    number: '41',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/41.png","large":"https://images.pokemontcg.io/svp/41_hires.png"}',
    searchName: 'Paldean Wooper (PR-SV 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Houndstone',
    tcgApiId: 'svp-42',
    number: '42',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/42.png","large":"https://images.pokemontcg.io/svp/42_hires.png"}',
    searchName: 'Houndstone (PR-SV 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Eevee',
    tcgApiId: 'svp-43',
    number: '43',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/43.png","large":"https://images.pokemontcg.io/svp/43_hires.png"}',
    searchName: 'Eevee (PR-SV 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Charmander',
    tcgApiId: 'svp-44',
    number: '44',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/44.png","large":"https://images.pokemontcg.io/svp/44_hires.png"}',
    searchName: 'Charmander (PR-SV 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Paradise Resort',
    tcgApiId: 'svp-45',
    number: '45',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/45.png","large":"https://images.pokemontcg.io/svp/45_hires.png"}',
    searchName: 'Paradise Resort (PR-SV 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Bulbasaur',
    tcgApiId: 'svp-46',
    number: '46',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/46.png","large":"https://images.pokemontcg.io/svp/46_hires.png"}',
    searchName: 'Bulbasaur (PR-SV 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Charmander',
    tcgApiId: 'svp-47',
    number: '47',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/47.png","large":"https://images.pokemontcg.io/svp/47_hires.png"}',
    searchName: 'Charmander (PR-SV 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Squirtle',
    tcgApiId: 'svp-48',
    number: '48',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/48.png","large":"https://images.pokemontcg.io/svp/48_hires.png"}',
    searchName: 'Squirtle (PR-SV 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Zapdos ex',
    tcgApiId: 'svp-49',
    number: '49',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/49.png","large":"https://images.pokemontcg.io/svp/49_hires.png"}',
    searchName: 'Zapdos ex (PR-SV 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Alakazam ex',
    tcgApiId: 'svp-50',
    number: '50',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/50.png","large":"https://images.pokemontcg.io/svp/50_hires.png"}',
    searchName: 'Alakazam ex (PR-SV 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Snorlax',
    tcgApiId: 'svp-51',
    number: '51',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/51.png","large":"https://images.pokemontcg.io/svp/51_hires.png"}',
    searchName: 'Snorlax (PR-SV 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Mewtwo',
    tcgApiId: 'svp-52',
    number: '52',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/52.png","large":"https://images.pokemontcg.io/svp/52_hires.png"}',
    searchName: 'Mewtwo (PR-SV 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Mew ex',
    tcgApiId: 'svp-53',
    number: '53',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/53.png","large":"https://images.pokemontcg.io/svp/53_hires.png"}',
    searchName: 'Mew ex (PR-SV 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Greninja ex',
    tcgApiId: 'svp-54',
    number: '54',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/54.png","large":"https://images.pokemontcg.io/svp/54_hires.png"}',
    searchName: 'Greninja ex (PR-SV 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Kangaskhan ex',
    tcgApiId: 'svp-55',
    number: '55',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/55.png","large":"https://images.pokemontcg.io/svp/55_hires.png"}',
    searchName: 'Kangaskhan ex (PR-SV 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Charizard ex',
    tcgApiId: 'svp-56',
    number: '56',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/56.png","large":"https://images.pokemontcg.io/svp/56_hires.png"}',
    searchName: 'Charizard ex (PR-SV 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Chi-Yu',
    tcgApiId: 'svp-57',
    number: '57',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/57.png","large":"https://images.pokemontcg.io/svp/57_hires.png"}',
    searchName: 'Chi-Yu (PR-SV 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Iron Bundle',
    tcgApiId: 'svp-58',
    number: '58',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/58.png","large":"https://images.pokemontcg.io/svp/58_hires.png"}',
    searchName: 'Iron Bundle (PR-SV 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Xatu',
    tcgApiId: 'svp-59',
    number: '59',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/59.png","large":"https://images.pokemontcg.io/svp/59_hires.png"}',
    searchName: 'Xatu (PR-SV 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Aegislash',
    tcgApiId: 'svp-60',
    number: '60',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/60.png","large":"https://images.pokemontcg.io/svp/60_hires.png"}',
    searchName: 'Aegislash (PR-SV 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pineco',
    tcgApiId: 'svp-61',
    number: '61',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/61.png","large":"https://images.pokemontcg.io/svp/61_hires.png"}',
    searchName: 'Pineco (PR-SV 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Sinistea',
    tcgApiId: 'svp-62',
    number: '62',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/62.png","large":"https://images.pokemontcg.io/svp/62_hires.png"}',
    searchName: 'Sinistea (PR-SV 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Cetitan',
    tcgApiId: 'svp-63',
    number: '63',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/63.png","large":"https://images.pokemontcg.io/svp/63_hires.png"}',
    searchName: 'Cetitan (PR-SV 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Arctibax',
    tcgApiId: 'svp-64',
    number: '64',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/64.png","large":"https://images.pokemontcg.io/svp/64_hires.png"}',
    searchName: 'Arctibax (PR-SV 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Scream Tail',
    tcgApiId: 'svp-65',
    number: '65',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/65.png","large":"https://images.pokemontcg.io/svp/65_hires.png"}',
    searchName: 'Scream Tail (PR-SV 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Iron Bundle',
    tcgApiId: 'svp-66',
    number: '66',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/66.png","large":"https://images.pokemontcg.io/svp/66_hires.png"}',
    searchName: 'Iron Bundle (PR-SV 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Roaring Moon ex',
    tcgApiId: 'svp-67',
    number: '67',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/67.png","large":"https://images.pokemontcg.io/svp/67_hires.png"}',
    searchName: 'Roaring Moon ex (PR-SV 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Iron Valiant ex',
    tcgApiId: 'svp-68',
    number: '68',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/68.png","large":"https://images.pokemontcg.io/svp/68_hires.png"}',
    searchName: 'Iron Valiant ex (PR-SV 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Fidough',
    tcgApiId: 'svp-69',
    number: '69',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/69.png","large":"https://images.pokemontcg.io/svp/69_hires.png"}',
    searchName: 'Fidough (PR-SV 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Greavard',
    tcgApiId: 'svp-70',
    number: '70',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/70.png","large":"https://images.pokemontcg.io/svp/70_hires.png"}',
    searchName: 'Greavard (PR-SV 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Maschiff',
    tcgApiId: 'svp-71',
    number: '71',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/71.png","large":"https://images.pokemontcg.io/svp/71_hires.png"}',
    searchName: 'Maschiff (PR-SV 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Great Tusk ex',
    tcgApiId: 'svp-72',
    number: '72',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/72.png","large":"https://images.pokemontcg.io/svp/72_hires.png"}',
    searchName: 'Great Tusk ex (PR-SV 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Iron Treads ex',
    tcgApiId: 'svp-73',
    number: '73',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/73.png","large":"https://images.pokemontcg.io/svp/73_hires.png"}',
    searchName: 'Iron Treads ex (PR-SV 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Charizard ex',
    tcgApiId: 'svp-74',
    number: '74',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/74.png","large":"https://images.pokemontcg.io/svp/74_hires.png"}',
    searchName: 'Charizard ex (PR-SV 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Mimikyu',
    tcgApiId: 'svp-75',
    number: '75',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/75.png","large":"https://images.pokemontcg.io/svp/75_hires.png"}',
    searchName: 'Mimikyu (PR-SV 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Sprigatito',
    tcgApiId: 'svp-76',
    number: '76',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/76.png","large":"https://images.pokemontcg.io/svp/76_hires.png"}',
    searchName: 'Sprigatito (PR-SV 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Floragato',
    tcgApiId: 'svp-77',
    number: '77',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/77.png","large":"https://images.pokemontcg.io/svp/77_hires.png"}',
    searchName: 'Floragato (PR-SV 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Meowscarada ex',
    tcgApiId: 'svp-78',
    number: '78',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/78.png","large":"https://images.pokemontcg.io/svp/78_hires.png"}',
    searchName: 'Meowscarada ex (PR-SV 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Fuecoco',
    tcgApiId: 'svp-79',
    number: '79',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/79.png","large":"https://images.pokemontcg.io/svp/79_hires.png"}',
    searchName: 'Fuecoco (PR-SV 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Crocalor',
    tcgApiId: 'svp-80',
    number: '80',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/80.png","large":"https://images.pokemontcg.io/svp/80_hires.png"}',
    searchName: 'Crocalor (PR-SV 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Skeledirge ex',
    tcgApiId: 'svp-81',
    number: '81',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/81.png","large":"https://images.pokemontcg.io/svp/81_hires.png"}',
    searchName: 'Skeledirge ex (PR-SV 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Quaxly',
    tcgApiId: 'svp-82',
    number: '82',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/82.png","large":"https://images.pokemontcg.io/svp/82_hires.png"}',
    searchName: 'Quaxly (PR-SV 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Quaxwell',
    tcgApiId: 'svp-83',
    number: '83',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/83.png","large":"https://images.pokemontcg.io/svp/83_hires.png"}',
    searchName: 'Quaxwell (PR-SV 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Quaquaval ex',
    tcgApiId: 'svp-84',
    number: '84',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/84.png","large":"https://images.pokemontcg.io/svp/84_hires.png"}',
    searchName: 'Quaquaval ex (PR-SV 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pikachu with Grey Felt Hat',
    tcgApiId: 'svp-85',
    number: '85',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/85.png","large":"https://images.pokemontcg.io/svp/85_hires.png"}',
    searchName: 'Pikachu with Grey Felt Hat (PR-SV 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Mabosstiff ex',
    tcgApiId: 'svp-86',
    number: '86',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/86.png","large":"https://images.pokemontcg.io/svp/86_hires.png"}',
    searchName: 'Mabosstiff ex (PR-SV 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Sprigatito ex',
    tcgApiId: 'svp-87',
    number: '87',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/87.png","large":"https://images.pokemontcg.io/svp/87_hires.png"}',
    searchName: 'Sprigatito ex (PR-SV 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pikachu',
    tcgApiId: 'svp-88',
    number: '88',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/88.png","large":"https://images.pokemontcg.io/svp/88_hires.png"}',
    searchName: 'Pikachu (PR-SV 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Feraligatr',
    tcgApiId: 'svp-89',
    number: '89',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/89.png","large":"https://images.pokemontcg.io/svp/89_hires.png"}',
    searchName: 'Feraligatr (PR-SV 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Metang',
    tcgApiId: 'svp-90',
    number: '90',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/90.png","large":"https://images.pokemontcg.io/svp/90_hires.png"}',
    searchName: 'Metang (PR-SV 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Koraidon',
    tcgApiId: 'svp-91',
    number: '91',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/91.png","large":"https://images.pokemontcg.io/svp/91_hires.png"}',
    searchName: 'Koraidon (PR-SV 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Miraidon',
    tcgApiId: 'svp-92',
    number: '92',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/92.png","large":"https://images.pokemontcg.io/svp/92_hires.png"}',
    searchName: 'Miraidon (PR-SV 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Carvanha',
    tcgApiId: 'svp-93',
    number: '93',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/93.png","large":"https://images.pokemontcg.io/svp/93_hires.png"}',
    searchName: 'Carvanha (PR-SV 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Bellibolt',
    tcgApiId: 'svp-94',
    number: '94',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/94.png","large":"https://images.pokemontcg.io/svp/94_hires.png"}',
    searchName: 'Bellibolt (PR-SV 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Cleffa',
    tcgApiId: 'svp-95',
    number: '95',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/95.png","large":"https://images.pokemontcg.io/svp/95_hires.png"}',
    searchName: 'Cleffa (PR-SV 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Cyclizar',
    tcgApiId: 'svp-96',
    number: '96',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/96.png","large":"https://images.pokemontcg.io/svp/96_hires.png"}',
    searchName: 'Cyclizar (PR-SV 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Flutter Mane',
    tcgApiId: 'svp-97',
    number: '97',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/97.png","large":"https://images.pokemontcg.io/svp/97_hires.png"}',
    searchName: 'Flutter Mane (PR-SV 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Iron Thorns',
    tcgApiId: 'svp-98',
    number: '98',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/98.png","large":"https://images.pokemontcg.io/svp/98_hires.png"}',
    searchName: 'Iron Thorns (PR-SV 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Shroodle',
    tcgApiId: 'svp-99',
    number: '99',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/99.png","large":"https://images.pokemontcg.io/svp/99_hires.png"}',
    searchName: 'Shroodle (PR-SV 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Grafaiai ex',
    tcgApiId: 'svp-100',
    number: '100',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/100.png","large":"https://images.pokemontcg.io/svp/100_hires.png"}',
    searchName: 'Grafaiai ex (PR-SV 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pikachu',
    tcgApiId: 'svp-101',
    number: '101',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/101.png","large":"https://images.pokemontcg.io/svp/101_hires.png"}',
    searchName: 'Pikachu (PR-SV 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Oddish',
    tcgApiId: 'svp-102',
    number: '102',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/102.png","large":"https://images.pokemontcg.io/svp/102_hires.png"}',
    searchName: 'Oddish (PR-SV 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Houndoom ex',
    tcgApiId: 'svp-103',
    number: '103',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/103.png","large":"https://images.pokemontcg.io/svp/103_hires.png"}',
    searchName: 'Houndoom ex (PR-SV 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Melmetal ex',
    tcgApiId: 'svp-104',
    number: '104',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/104.png","large":"https://images.pokemontcg.io/svp/104_hires.png"}',
    searchName: 'Melmetal ex (PR-SV 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Armarouge ex',
    tcgApiId: 'svp-105',
    number: '105',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/105.png","large":"https://images.pokemontcg.io/svp/105_hires.png"}',
    searchName: 'Armarouge ex (PR-SV 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pikachu ex',
    tcgApiId: 'svp-106',
    number: '106',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/106.png","large":"https://images.pokemontcg.io/svp/106_hires.png"}',
    searchName: 'Pikachu ex (PR-SV 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Mareep',
    tcgApiId: 'svp-107',
    number: '107',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/107.png","large":"https://images.pokemontcg.io/svp/107_hires.png"}',
    searchName: 'Mareep (PR-SV 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Flaaffy',
    tcgApiId: 'svp-108',
    number: '108',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/108.png","large":"https://images.pokemontcg.io/svp/108_hires.png"}',
    searchName: 'Flaaffy (PR-SV 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Ampharos',
    tcgApiId: 'svp-109',
    number: '109',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/109.png","large":"https://images.pokemontcg.io/svp/109_hires.png"}',
    searchName: 'Ampharos (PR-SV 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Darkrai ex',
    tcgApiId: 'svp-110',
    number: '110',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/110.png","large":"https://images.pokemontcg.io/svp/110_hires.png"}',
    searchName: 'Darkrai ex (PR-SV 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pawniard',
    tcgApiId: 'svp-111',
    number: '111',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/111.png","large":"https://images.pokemontcg.io/svp/111_hires.png"}',
    searchName: 'Pawniard (PR-SV 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Bisharp',
    tcgApiId: 'svp-112',
    number: '112',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/112.png","large":"https://images.pokemontcg.io/svp/112_hires.png"}',
    searchName: 'Bisharp (PR-SV 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Kingambit',
    tcgApiId: 'svp-113',
    number: '113',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/113.png","large":"https://images.pokemontcg.io/svp/113_hires.png"}',
    searchName: 'Kingambit (PR-SV 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Picnicker',
    tcgApiId: 'svp-114',
    number: '114',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/114.png","large":"https://images.pokemontcg.io/svp/114_hires.png"}',
    searchName: 'Picnicker (PR-SV 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Thwackey',
    tcgApiId: 'svp-115',
    number: '115',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/115.png","large":"https://images.pokemontcg.io/svp/115_hires.png"}',
    searchName: 'Thwackey (PR-SV 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Infernape',
    tcgApiId: 'svp-116',
    number: '116',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/116.png","large":"https://images.pokemontcg.io/svp/116_hires.png"}',
    searchName: 'Infernape (PR-SV 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Froslass',
    tcgApiId: 'svp-117',
    number: '117',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/117.png","large":"https://images.pokemontcg.io/svp/117_hires.png"}',
    searchName: 'Froslass (PR-SV 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Tatsugiri',
    tcgApiId: 'svp-118',
    number: '118',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/118.png","large":"https://images.pokemontcg.io/svp/118_hires.png"}',
    searchName: 'Tatsugiri (PR-SV 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Toxel',
    tcgApiId: 'svp-119',
    number: '119',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/119.png","large":"https://images.pokemontcg.io/svp/119_hires.png"}',
    searchName: 'Toxel (PR-SV 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pupitar',
    tcgApiId: 'svp-120',
    number: '120',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/120.png","large":"https://images.pokemontcg.io/svp/120_hires.png"}',
    searchName: 'Pupitar (PR-SV 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Revavroom',
    tcgApiId: 'svp-121',
    number: '121',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/121.png","large":"https://images.pokemontcg.io/svp/121_hires.png"}',
    searchName: 'Revavroom (PR-SV 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Snorlax',
    tcgApiId: 'svp-122',
    number: '122',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/122.png","large":"https://images.pokemontcg.io/svp/122_hires.png"}',
    searchName: 'Snorlax (PR-SV 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Teal Mask Ogerpon',
    tcgApiId: 'svp-123',
    number: '123',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/123.png","large":"https://images.pokemontcg.io/svp/123_hires.png"}',
    searchName: 'Teal Mask Ogerpon (PR-SV 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Iono',
    tcgApiId: 'svp-124',
    number: '124',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/124.png","large":"https://images.pokemontcg.io/svp/124_hires.png"}',
    searchName: 'Iono (PR-SV 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Armarouge ex',
    tcgApiId: 'svp-125',
    number: '125',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/125.png","large":"https://images.pokemontcg.io/svp/125_hires.png"}',
    searchName: 'Armarouge ex (PR-SV 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Palafin ex',
    tcgApiId: 'svp-126',
    number: '126',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/126.png","large":"https://images.pokemontcg.io/svp/126_hires.png"}',
    searchName: 'Palafin ex (PR-SV 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Walking Wake ex',
    tcgApiId: 'svp-127',
    number: '127',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/127.png","large":"https://images.pokemontcg.io/svp/127_hires.png"}',
    searchName: 'Walking Wake ex (PR-SV 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Iron Leaves ex',
    tcgApiId: 'svp-128',
    number: '128',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/128.png","large":"https://images.pokemontcg.io/svp/128_hires.png"}',
    searchName: 'Iron Leaves ex (PR-SV 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pecharunt',
    tcgApiId: 'svp-129',
    number: '129',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/129.png","large":"https://images.pokemontcg.io/svp/129_hires.png"}',
    searchName: 'Pecharunt (PR-SV 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Kingambit',
    tcgApiId: 'svp-130',
    number: '130',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/130.png","large":"https://images.pokemontcg.io/svp/130_hires.png"}',
    searchName: 'Kingambit (PR-SV 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Kingdra ex',
    tcgApiId: 'svp-131',
    number: '131',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/131.png","large":"https://images.pokemontcg.io/svp/131_hires.png"}',
    searchName: 'Kingdra ex (PR-SV 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Greninja ex',
    tcgApiId: 'svp-132',
    number: '132',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/132.png","large":"https://images.pokemontcg.io/svp/132_hires.png"}',
    searchName: 'Greninja ex (PR-SV 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Ledian',
    tcgApiId: 'svp-133',
    number: '133',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/133.png","large":"https://images.pokemontcg.io/svp/133_hires.png"}',
    searchName: 'Ledian (PR-SV 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Crabominable',
    tcgApiId: 'svp-134',
    number: '134',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/134.png","large":"https://images.pokemontcg.io/svp/134_hires.png"}',
    searchName: 'Crabominable (PR-SV 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Drifblim',
    tcgApiId: 'svp-135',
    number: '135',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/135.png","large":"https://images.pokemontcg.io/svp/135_hires.png"}',
    searchName: 'Drifblim (PR-SV 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Bouffalant',
    tcgApiId: 'svp-136',
    number: '136',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/136.png","large":"https://images.pokemontcg.io/svp/136_hires.png"}',
    searchName: 'Bouffalant (PR-SV 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Horsea',
    tcgApiId: 'svp-137',
    number: '137',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/137.png","large":"https://images.pokemontcg.io/svp/137_hires.png"}',
    searchName: 'Horsea (PR-SV 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Porygon2',
    tcgApiId: 'svp-138',
    number: '138',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/138.png","large":"https://images.pokemontcg.io/svp/138_hires.png"}',
    searchName: 'Porygon2 (PR-SV 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Latias',
    tcgApiId: 'svp-139',
    number: '139',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/139.png","large":"https://images.pokemontcg.io/svp/139_hires.png"}',
    searchName: 'Latias (PR-SV 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Tinkaton',
    tcgApiId: 'svp-140',
    number: '140',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/140.png","large":"https://images.pokemontcg.io/svp/140_hires.png"}',
    searchName: 'Tinkaton (PR-SV 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Noctowl',
    tcgApiId: 'svp-141',
    number: '141',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/141.png","large":"https://images.pokemontcg.io/svp/141_hires.png"}',
    searchName: 'Noctowl (PR-SV 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Victini ex',
    tcgApiId: 'svp-142',
    number: '142',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/142.png","large":"https://images.pokemontcg.io/svp/142_hires.png"}',
    searchName: 'Victini ex (PR-SV 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Miraidon ex',
    tcgApiId: 'svp-143',
    number: '143',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/143.png","large":"https://images.pokemontcg.io/svp/143_hires.png"}',
    searchName: 'Miraidon ex (PR-SV 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Gouging Fire ex',
    tcgApiId: 'svp-144',
    number: '144',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/144.png","large":"https://images.pokemontcg.io/svp/144_hires.png"}',
    searchName: 'Gouging Fire ex (PR-SV 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Raging Bolt ex',
    tcgApiId: 'svp-145',
    number: '145',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/145.png","large":"https://images.pokemontcg.io/svp/145_hires.png"}',
    searchName: 'Raging Bolt ex (PR-SV 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Iron Crown ex',
    tcgApiId: 'svp-146',
    number: '146',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/146.png","large":"https://images.pokemontcg.io/svp/146_hires.png"}',
    searchName: 'Iron Crown ex (PR-SV 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Iron Boulder ex',
    tcgApiId: 'svp-147',
    number: '147',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/147.png","large":"https://images.pokemontcg.io/svp/147_hires.png"}',
    searchName: 'Iron Boulder ex (PR-SV 147)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Miraidon',
    tcgApiId: 'svp-148',
    number: '148',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/148.png","large":"https://images.pokemontcg.io/svp/148_hires.png"}',
    searchName: 'Miraidon (PR-SV 148)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pecharunt',
    tcgApiId: 'svp-149',
    number: '149',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/149.png","large":"https://images.pokemontcg.io/svp/149_hires.png"}',
    searchName: 'Pecharunt (PR-SV 149)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Paradise Resort',
    tcgApiId: 'svp-150',
    number: '150',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/150.png","large":"https://images.pokemontcg.io/svp/150_hires.png"}',
    searchName: 'Paradise Resort (PR-SV 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Gouging Fire',
    tcgApiId: 'svp-151',
    number: '151',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/151.png","large":"https://images.pokemontcg.io/svp/151_hires.png"}',
    searchName: 'Gouging Fire (PR-SV 151)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Chien-Pao',
    tcgApiId: 'svp-152',
    number: '152',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/152.png","large":"https://images.pokemontcg.io/svp/152_hires.png"}',
    searchName: 'Chien-Pao (PR-SV 152)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Magneton',
    tcgApiId: 'svp-153',
    number: '153',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/153.png","large":"https://images.pokemontcg.io/svp/153_hires.png"}',
    searchName: 'Magneton (PR-SV 153)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Indeedee',
    tcgApiId: 'svp-154',
    number: '154',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/154.png","large":"https://images.pokemontcg.io/svp/154_hires.png"}',
    searchName: 'Indeedee (PR-SV 154)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Wooper',
    tcgApiId: 'svp-155',
    number: '155',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/155.png","large":"https://images.pokemontcg.io/svp/155_hires.png"}',
    searchName: 'Wooper (PR-SV 155)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Quagsire',
    tcgApiId: 'svp-156',
    number: '156',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/156.png","large":"https://images.pokemontcg.io/svp/156_hires.png"}',
    searchName: 'Quagsire (PR-SV 156)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Zapdos',
    tcgApiId: 'svp-157',
    number: '157',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/157.png","large":"https://images.pokemontcg.io/svp/157_hires.png"}',
    searchName: 'Zapdos (PR-SV 157)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Pachirisu',
    tcgApiId: 'svp-158',
    number: '158',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/158.png","large":"https://images.pokemontcg.io/svp/158_hires.png"}',
    searchName: 'Pachirisu (PR-SV 158)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Magneton',
    tcgApiId: 'svp-159',
    number: '159',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/159.png","large":"https://images.pokemontcg.io/svp/159_hires.png"}',
    searchName: 'Magneton (PR-SV 159)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Squawkabilly ex',
    tcgApiId: 'svp-160',
    number: '160',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/160.png","large":"https://images.pokemontcg.io/svp/160_hires.png"}',
    searchName: 'Squawkabilly ex (PR-SV 160)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Charizard ex',
    tcgApiId: 'svp-161',
    number: '161',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/161.png","large":"https://images.pokemontcg.io/svp/161_hires.png"}',
    searchName: 'Charizard ex (PR-SV 161)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Houndstone ex',
    tcgApiId: 'svp-162',
    number: '162',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/162.png","large":"https://images.pokemontcg.io/svp/162_hires.png"}',
    searchName: 'Houndstone ex (PR-SV 162)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Cinderace ex',
    tcgApiId: 'svp-163',
    number: '163',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/163.png","large":"https://images.pokemontcg.io/svp/163_hires.png"}',
    searchName: 'Cinderace ex (PR-SV 163)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Lapras ex',
    tcgApiId: 'svp-164',
    number: '164',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/164.png","large":"https://images.pokemontcg.io/svp/164_hires.png"}',
    searchName: 'Lapras ex (PR-SV 164)',
  },
  {
    tcgId: 'pokemon',
    setId: 'svp',
    name: 'Terapagos ex',
    tcgApiId: 'svp-165',
    number: '165',
    rarity: 'Promo',
    images:
      '{"small":"https://images.pokemontcg.io/svp/165.png","large":"https://images.pokemontcg.io/svp/165_hires.png"}',
    searchName: 'Terapagos ex (PR-SV 165)',
  },
];
