export const cardSeedSwsh2 = [
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Caterpie',
    tcgApiId: 'swsh2-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/1.png","large":"https://images.pokemontcg.io/swsh2/1_hires.png"}',
    searchName: 'Caterpie (RCL 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Metapod',
    tcgApiId: 'swsh2-2',
    number: '2',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/2.png","large":"https://images.pokemontcg.io/swsh2/2_hires.png"}',
    searchName: 'Metapod (RCL 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Butterfree',
    tcgApiId: 'swsh2-3',
    number: '3',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/3.png","large":"https://images.pokemontcg.io/swsh2/3_hires.png"}',
    searchName: 'Butterfree (RCL 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Scyther',
    tcgApiId: 'swsh2-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/4.png","large":"https://images.pokemontcg.io/swsh2/4_hires.png"}',
    searchName: 'Scyther (RCL 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Shuckle',
    tcgApiId: 'swsh2-5',
    number: '5',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/5.png","large":"https://images.pokemontcg.io/swsh2/5_hires.png"}',
    searchName: 'Shuckle (RCL 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Heracross',
    tcgApiId: 'swsh2-6',
    number: '6',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/6.png","large":"https://images.pokemontcg.io/swsh2/6_hires.png"}',
    searchName: 'Heracross (RCL 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Lotad',
    tcgApiId: 'swsh2-7',
    number: '7',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/7.png","large":"https://images.pokemontcg.io/swsh2/7_hires.png"}',
    searchName: 'Lotad (RCL 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Lombre',
    tcgApiId: 'swsh2-8',
    number: '8',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/8.png","large":"https://images.pokemontcg.io/swsh2/8_hires.png"}',
    searchName: 'Lombre (RCL 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Ludicolo',
    tcgApiId: 'swsh2-9',
    number: '9',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/9.png","large":"https://images.pokemontcg.io/swsh2/9_hires.png"}',
    searchName: 'Ludicolo (RCL 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Surskit',
    tcgApiId: 'swsh2-10',
    number: '10',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/10.png","large":"https://images.pokemontcg.io/swsh2/10_hires.png"}',
    searchName: 'Surskit (RCL 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Masquerain',
    tcgApiId: 'swsh2-11',
    number: '11',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/11.png","large":"https://images.pokemontcg.io/swsh2/11_hires.png"}',
    searchName: 'Masquerain (RCL 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Snover',
    tcgApiId: 'swsh2-12',
    number: '12',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/12.png","large":"https://images.pokemontcg.io/swsh2/12_hires.png"}',
    searchName: 'Snover (RCL 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Abomasnow',
    tcgApiId: 'swsh2-13',
    number: '13',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/13.png","large":"https://images.pokemontcg.io/swsh2/13_hires.png"}',
    searchName: 'Abomasnow (RCL 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Phantump',
    tcgApiId: 'swsh2-14',
    number: '14',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/14.png","large":"https://images.pokemontcg.io/swsh2/14_hires.png"}',
    searchName: 'Phantump (RCL 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Trevenant',
    tcgApiId: 'swsh2-15',
    number: '15',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/15.png","large":"https://images.pokemontcg.io/swsh2/15_hires.png"}',
    searchName: 'Trevenant (RCL 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Grubbin',
    tcgApiId: 'swsh2-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/16.png","large":"https://images.pokemontcg.io/swsh2/16_hires.png"}',
    searchName: 'Grubbin (RCL 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Rillaboom V',
    tcgApiId: 'swsh2-17',
    number: '17',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/17.png","large":"https://images.pokemontcg.io/swsh2/17_hires.png"}',
    searchName: 'Rillaboom V (RCL 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Rillaboom VMAX',
    tcgApiId: 'swsh2-18',
    number: '18',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/18.png","large":"https://images.pokemontcg.io/swsh2/18_hires.png"}',
    searchName: 'Rillaboom VMAX (RCL 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Eldegoss V',
    tcgApiId: 'swsh2-19',
    number: '19',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/19.png","large":"https://images.pokemontcg.io/swsh2/19_hires.png"}',
    searchName: 'Eldegoss V (RCL 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Applin',
    tcgApiId: 'swsh2-20',
    number: '20',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/20.png","large":"https://images.pokemontcg.io/swsh2/20_hires.png"}',
    searchName: 'Applin (RCL 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Applin',
    tcgApiId: 'swsh2-21',
    number: '21',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/21.png","large":"https://images.pokemontcg.io/swsh2/21_hires.png"}',
    searchName: 'Applin (RCL 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Flapple',
    tcgApiId: 'swsh2-22',
    number: '22',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/22.png","large":"https://images.pokemontcg.io/swsh2/22_hires.png"}',
    searchName: 'Flapple (RCL 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Appletun',
    tcgApiId: 'swsh2-23',
    number: '23',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/23.png","large":"https://images.pokemontcg.io/swsh2/23_hires.png"}',
    searchName: 'Appletun (RCL 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Vulpix',
    tcgApiId: 'swsh2-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/24.png","large":"https://images.pokemontcg.io/swsh2/24_hires.png"}',
    searchName: 'Vulpix (RCL 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Ninetales',
    tcgApiId: 'swsh2-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/25.png","large":"https://images.pokemontcg.io/swsh2/25_hires.png"}',
    searchName: 'Ninetales (RCL 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Ninetales V',
    tcgApiId: 'swsh2-26',
    number: '26',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/26.png","large":"https://images.pokemontcg.io/swsh2/26_hires.png"}',
    searchName: 'Ninetales V (RCL 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Growlithe',
    tcgApiId: 'swsh2-27',
    number: '27',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/27.png","large":"https://images.pokemontcg.io/swsh2/27_hires.png"}',
    searchName: 'Growlithe (RCL 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Arcanine',
    tcgApiId: 'swsh2-28',
    number: '28',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/28.png","large":"https://images.pokemontcg.io/swsh2/28_hires.png"}',
    searchName: 'Arcanine (RCL 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Magmar',
    tcgApiId: 'swsh2-29',
    number: '29',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/29.png","large":"https://images.pokemontcg.io/swsh2/29_hires.png"}',
    searchName: 'Magmar (RCL 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Magmortar',
    tcgApiId: 'swsh2-30',
    number: '30',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/30.png","large":"https://images.pokemontcg.io/swsh2/30_hires.png"}',
    searchName: 'Magmortar (RCL 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Litwick',
    tcgApiId: 'swsh2-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/31.png","large":"https://images.pokemontcg.io/swsh2/31_hires.png"}',
    searchName: 'Litwick (RCL 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Lampent',
    tcgApiId: 'swsh2-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/32.png","large":"https://images.pokemontcg.io/swsh2/32_hires.png"}',
    searchName: 'Lampent (RCL 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Chandelure',
    tcgApiId: 'swsh2-33',
    number: '33',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/33.png","large":"https://images.pokemontcg.io/swsh2/33_hires.png"}',
    searchName: 'Chandelure (RCL 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Heatmor',
    tcgApiId: 'swsh2-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/34.png","large":"https://images.pokemontcg.io/swsh2/34_hires.png"}',
    searchName: 'Heatmor (RCL 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Cinderace V',
    tcgApiId: 'swsh2-35',
    number: '35',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/35.png","large":"https://images.pokemontcg.io/swsh2/35_hires.png"}',
    searchName: 'Cinderace V (RCL 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Cinderace VMAX',
    tcgApiId: 'swsh2-36',
    number: '36',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/36.png","large":"https://images.pokemontcg.io/swsh2/36_hires.png"}',
    searchName: 'Cinderace VMAX (RCL 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Mr. Mime',
    tcgApiId: 'swsh2-37',
    number: '37',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/37.png","large":"https://images.pokemontcg.io/swsh2/37_hires.png"}',
    searchName: 'Galarian Mr. Mime (RCL 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Mr. Rime',
    tcgApiId: 'swsh2-38',
    number: '38',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/38.png","large":"https://images.pokemontcg.io/swsh2/38_hires.png"}',
    searchName: 'Galarian Mr. Rime (RCL 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Magikarp',
    tcgApiId: 'swsh2-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/39.png","large":"https://images.pokemontcg.io/swsh2/39_hires.png"}',
    searchName: 'Magikarp (RCL 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Gyarados',
    tcgApiId: 'swsh2-40',
    number: '40',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/40.png","large":"https://images.pokemontcg.io/swsh2/40_hires.png"}',
    searchName: 'Gyarados (RCL 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Wingull',
    tcgApiId: 'swsh2-41',
    number: '41',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/41.png","large":"https://images.pokemontcg.io/swsh2/41_hires.png"}',
    searchName: 'Wingull (RCL 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Pelipper',
    tcgApiId: 'swsh2-42',
    number: '42',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/42.png","large":"https://images.pokemontcg.io/swsh2/42_hires.png"}',
    searchName: 'Pelipper (RCL 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Milotic V',
    tcgApiId: 'swsh2-43',
    number: '43',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/43.png","large":"https://images.pokemontcg.io/swsh2/43_hires.png"}',
    searchName: 'Milotic V (RCL 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Tympole',
    tcgApiId: 'swsh2-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/44.png","large":"https://images.pokemontcg.io/swsh2/44_hires.png"}',
    searchName: 'Tympole (RCL 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Palpitoad',
    tcgApiId: 'swsh2-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/45.png","large":"https://images.pokemontcg.io/swsh2/45_hires.png"}',
    searchName: 'Palpitoad (RCL 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Seismitoad',
    tcgApiId: 'swsh2-46',
    number: '46',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/46.png","large":"https://images.pokemontcg.io/swsh2/46_hires.png"}',
    searchName: 'Seismitoad (RCL 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Darumaka',
    tcgApiId: 'swsh2-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/47.png","large":"https://images.pokemontcg.io/swsh2/47_hires.png"}',
    searchName: 'Galarian Darumaka (RCL 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Darmanitan',
    tcgApiId: 'swsh2-48',
    number: '48',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/48.png","large":"https://images.pokemontcg.io/swsh2/48_hires.png"}',
    searchName: 'Galarian Darmanitan (RCL 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Inteleon V',
    tcgApiId: 'swsh2-49',
    number: '49',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/49.png","large":"https://images.pokemontcg.io/swsh2/49_hires.png"}',
    searchName: 'Inteleon V (RCL 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Inteleon VMAX',
    tcgApiId: 'swsh2-50',
    number: '50',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/50.png","large":"https://images.pokemontcg.io/swsh2/50_hires.png"}',
    searchName: 'Inteleon VMAX (RCL 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Cramorant',
    tcgApiId: 'swsh2-51',
    number: '51',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/51.png","large":"https://images.pokemontcg.io/swsh2/51_hires.png"}',
    searchName: 'Cramorant (RCL 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Arrokuda',
    tcgApiId: 'swsh2-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/52.png","large":"https://images.pokemontcg.io/swsh2/52_hires.png"}',
    searchName: 'Arrokuda (RCL 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Barraskewda',
    tcgApiId: 'swsh2-53',
    number: '53',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/53.png","large":"https://images.pokemontcg.io/swsh2/53_hires.png"}',
    searchName: 'Barraskewda (RCL 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Eiscue',
    tcgApiId: 'swsh2-54',
    number: '54',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/54.png","large":"https://images.pokemontcg.io/swsh2/54_hires.png"}',
    searchName: 'Eiscue (RCL 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Eiscue V',
    tcgApiId: 'swsh2-55',
    number: '55',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/55.png","large":"https://images.pokemontcg.io/swsh2/55_hires.png"}',
    searchName: 'Eiscue V (RCL 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Voltorb',
    tcgApiId: 'swsh2-56',
    number: '56',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/56.png","large":"https://images.pokemontcg.io/swsh2/56_hires.png"}',
    searchName: 'Voltorb (RCL 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Electrode',
    tcgApiId: 'swsh2-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/57.png","large":"https://images.pokemontcg.io/swsh2/57_hires.png"}',
    searchName: 'Electrode (RCL 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Electabuzz',
    tcgApiId: 'swsh2-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/58.png","large":"https://images.pokemontcg.io/swsh2/58_hires.png"}',
    searchName: 'Electabuzz (RCL 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Electivire',
    tcgApiId: 'swsh2-59',
    number: '59',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/59.png","large":"https://images.pokemontcg.io/swsh2/59_hires.png"}',
    searchName: 'Electivire (RCL 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Shinx',
    tcgApiId: 'swsh2-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/60.png","large":"https://images.pokemontcg.io/swsh2/60_hires.png"}',
    searchName: 'Shinx (RCL 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Luxio',
    tcgApiId: 'swsh2-61',
    number: '61',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/61.png","large":"https://images.pokemontcg.io/swsh2/61_hires.png"}',
    searchName: 'Luxio (RCL 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Luxray',
    tcgApiId: 'swsh2-62',
    number: '62',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/62.png","large":"https://images.pokemontcg.io/swsh2/62_hires.png"}',
    searchName: 'Luxray (RCL 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Helioptile',
    tcgApiId: 'swsh2-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/63.png","large":"https://images.pokemontcg.io/swsh2/63_hires.png"}',
    searchName: 'Helioptile (RCL 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Heliolisk',
    tcgApiId: 'swsh2-64',
    number: '64',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/64.png","large":"https://images.pokemontcg.io/swsh2/64_hires.png"}',
    searchName: 'Heliolisk (RCL 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Charjabug',
    tcgApiId: 'swsh2-65',
    number: '65',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/65.png","large":"https://images.pokemontcg.io/swsh2/65_hires.png"}',
    searchName: 'Charjabug (RCL 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Vikavolt',
    tcgApiId: 'swsh2-66',
    number: '66',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/66.png","large":"https://images.pokemontcg.io/swsh2/66_hires.png"}',
    searchName: 'Vikavolt (RCL 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Boltund V',
    tcgApiId: 'swsh2-67',
    number: '67',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/67.png","large":"https://images.pokemontcg.io/swsh2/67_hires.png"}',
    searchName: 'Boltund V (RCL 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Toxel',
    tcgApiId: 'swsh2-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/68.png","large":"https://images.pokemontcg.io/swsh2/68_hires.png"}',
    searchName: 'Toxel (RCL 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Toxtricity',
    tcgApiId: 'swsh2-69',
    number: '69',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/69.png","large":"https://images.pokemontcg.io/swsh2/69_hires.png"}',
    searchName: 'Toxtricity (RCL 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Toxtricity V',
    tcgApiId: 'swsh2-70',
    number: '70',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/70.png","large":"https://images.pokemontcg.io/swsh2/70_hires.png"}',
    searchName: 'Toxtricity V (RCL 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Toxtricity VMAX',
    tcgApiId: 'swsh2-71',
    number: '71',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/71.png","large":"https://images.pokemontcg.io/swsh2/71_hires.png"}',
    searchName: 'Toxtricity VMAX (RCL 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Pincurchin V',
    tcgApiId: 'swsh2-72',
    number: '72',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/72.png","large":"https://images.pokemontcg.io/swsh2/72_hires.png"}',
    searchName: 'Pincurchin V (RCL 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Morpeko',
    tcgApiId: 'swsh2-73',
    number: '73',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/73.png","large":"https://images.pokemontcg.io/swsh2/73_hires.png"}',
    searchName: 'Morpeko (RCL 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Clefairy',
    tcgApiId: 'swsh2-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/74.png","large":"https://images.pokemontcg.io/swsh2/74_hires.png"}',
    searchName: 'Clefairy (RCL 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Clefable',
    tcgApiId: 'swsh2-75',
    number: '75',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/75.png","large":"https://images.pokemontcg.io/swsh2/75_hires.png"}',
    searchName: 'Clefable (RCL 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Natu',
    tcgApiId: 'swsh2-76',
    number: '76',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/76.png","large":"https://images.pokemontcg.io/swsh2/76_hires.png"}',
    searchName: 'Natu (RCL 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Xatu',
    tcgApiId: 'swsh2-77',
    number: '77',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/77.png","large":"https://images.pokemontcg.io/swsh2/77_hires.png"}',
    searchName: 'Xatu (RCL 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Corsola',
    tcgApiId: 'swsh2-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/78.png","large":"https://images.pokemontcg.io/swsh2/78_hires.png"}',
    searchName: 'Galarian Corsola (RCL 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Cursola',
    tcgApiId: 'swsh2-79',
    number: '79',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/79.png","large":"https://images.pokemontcg.io/swsh2/79_hires.png"}',
    searchName: 'Galarian Cursola (RCL 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Sigilyph',
    tcgApiId: 'swsh2-80',
    number: '80',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/80.png","large":"https://images.pokemontcg.io/swsh2/80_hires.png"}',
    searchName: 'Sigilyph (RCL 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Sandygast',
    tcgApiId: 'swsh2-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/81.png","large":"https://images.pokemontcg.io/swsh2/81_hires.png"}',
    searchName: 'Sandygast (RCL 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Palossand',
    tcgApiId: 'swsh2-82',
    number: '82',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/82.png","large":"https://images.pokemontcg.io/swsh2/82_hires.png"}',
    searchName: 'Palossand (RCL 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Hatenna',
    tcgApiId: 'swsh2-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/83.png","large":"https://images.pokemontcg.io/swsh2/83_hires.png"}',
    searchName: 'Hatenna (RCL 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Hattrem',
    tcgApiId: 'swsh2-84',
    number: '84',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/84.png","large":"https://images.pokemontcg.io/swsh2/84_hires.png"}',
    searchName: 'Hattrem (RCL 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Hatterene',
    tcgApiId: 'swsh2-85',
    number: '85',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/85.png","large":"https://images.pokemontcg.io/swsh2/85_hires.png"}',
    searchName: 'Hatterene (RCL 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Milcery',
    tcgApiId: 'swsh2-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/86.png","large":"https://images.pokemontcg.io/swsh2/86_hires.png"}',
    searchName: 'Milcery (RCL 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Alcremie',
    tcgApiId: 'swsh2-87',
    number: '87',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/87.png","large":"https://images.pokemontcg.io/swsh2/87_hires.png"}',
    searchName: 'Alcremie (RCL 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Indeedee',
    tcgApiId: 'swsh2-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/88.png","large":"https://images.pokemontcg.io/swsh2/88_hires.png"}',
    searchName: 'Indeedee (RCL 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Dreepy',
    tcgApiId: 'swsh2-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/89.png","large":"https://images.pokemontcg.io/swsh2/89_hires.png"}',
    searchName: 'Dreepy (RCL 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Drakloak',
    tcgApiId: 'swsh2-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/90.png","large":"https://images.pokemontcg.io/swsh2/90_hires.png"}',
    searchName: 'Drakloak (RCL 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Dragapult',
    tcgApiId: 'swsh2-91',
    number: '91',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/91.png","large":"https://images.pokemontcg.io/swsh2/91_hires.png"}',
    searchName: 'Dragapult (RCL 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Dragapult V',
    tcgApiId: 'swsh2-92',
    number: '92',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/92.png","large":"https://images.pokemontcg.io/swsh2/92_hires.png"}',
    searchName: 'Dragapult V (RCL 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Dragapult VMAX',
    tcgApiId: 'swsh2-93',
    number: '93',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/93.png","large":"https://images.pokemontcg.io/swsh2/93_hires.png"}',
    searchName: 'Dragapult VMAX (RCL 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: "Galarian Farfetch'd",
    tcgApiId: 'swsh2-94',
    number: '94',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/94.png","large":"https://images.pokemontcg.io/swsh2/94_hires.png"}',
    searchName: "Galarian Farfetch'd (RCL 94)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: "Galarian Sirfetch'd",
    tcgApiId: 'swsh2-95',
    number: '95',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/95.png","large":"https://images.pokemontcg.io/swsh2/95_hires.png"}',
    searchName: "Galarian Sirfetch'd (RCL 95)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Nosepass',
    tcgApiId: 'swsh2-96',
    number: '96',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/96.png","large":"https://images.pokemontcg.io/swsh2/96_hires.png"}',
    searchName: 'Nosepass (RCL 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Meditite',
    tcgApiId: 'swsh2-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/97.png","large":"https://images.pokemontcg.io/swsh2/97_hires.png"}',
    searchName: 'Meditite (RCL 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Medicham',
    tcgApiId: 'swsh2-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/98.png","large":"https://images.pokemontcg.io/swsh2/98_hires.png"}',
    searchName: 'Medicham (RCL 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Barboach',
    tcgApiId: 'swsh2-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/99.png","large":"https://images.pokemontcg.io/swsh2/99_hires.png"}',
    searchName: 'Barboach (RCL 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Whiscash',
    tcgApiId: 'swsh2-100',
    number: '100',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/100.png","large":"https://images.pokemontcg.io/swsh2/100_hires.png"}',
    searchName: 'Whiscash (RCL 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Yamask',
    tcgApiId: 'swsh2-101',
    number: '101',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/101.png","large":"https://images.pokemontcg.io/swsh2/101_hires.png"}',
    searchName: 'Galarian Yamask (RCL 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Runerigus',
    tcgApiId: 'swsh2-102',
    number: '102',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/102.png","large":"https://images.pokemontcg.io/swsh2/102_hires.png"}',
    searchName: 'Galarian Runerigus (RCL 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Binacle',
    tcgApiId: 'swsh2-103',
    number: '103',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/103.png","large":"https://images.pokemontcg.io/swsh2/103_hires.png"}',
    searchName: 'Binacle (RCL 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Barbaracle',
    tcgApiId: 'swsh2-104',
    number: '104',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/104.png","large":"https://images.pokemontcg.io/swsh2/104_hires.png"}',
    searchName: 'Barbaracle (RCL 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Rolycoly',
    tcgApiId: 'swsh2-105',
    number: '105',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/105.png","large":"https://images.pokemontcg.io/swsh2/105_hires.png"}',
    searchName: 'Rolycoly (RCL 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Carkol',
    tcgApiId: 'swsh2-106',
    number: '106',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/106.png","large":"https://images.pokemontcg.io/swsh2/106_hires.png"}',
    searchName: 'Carkol (RCL 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Coalossal',
    tcgApiId: 'swsh2-107',
    number: '107',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/107.png","large":"https://images.pokemontcg.io/swsh2/107_hires.png"}',
    searchName: 'Coalossal (RCL 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Sandaconda V',
    tcgApiId: 'swsh2-108',
    number: '108',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/108.png","large":"https://images.pokemontcg.io/swsh2/108_hires.png"}',
    searchName: 'Sandaconda V (RCL 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Falinks',
    tcgApiId: 'swsh2-109',
    number: '109',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/109.png","large":"https://images.pokemontcg.io/swsh2/109_hires.png"}',
    searchName: 'Falinks (RCL 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Falinks V',
    tcgApiId: 'swsh2-110',
    number: '110',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/110.png","large":"https://images.pokemontcg.io/swsh2/110_hires.png"}',
    searchName: 'Falinks V (RCL 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Stonjourner',
    tcgApiId: 'swsh2-111',
    number: '111',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/111.png","large":"https://images.pokemontcg.io/swsh2/111_hires.png"}',
    searchName: 'Stonjourner (RCL 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Koffing',
    tcgApiId: 'swsh2-112',
    number: '112',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/112.png","large":"https://images.pokemontcg.io/swsh2/112_hires.png"}',
    searchName: 'Koffing (RCL 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Weezing',
    tcgApiId: 'swsh2-113',
    number: '113',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/113.png","large":"https://images.pokemontcg.io/swsh2/113_hires.png"}',
    searchName: 'Galarian Weezing (RCL 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Stunky',
    tcgApiId: 'swsh2-114',
    number: '114',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/114.png","large":"https://images.pokemontcg.io/swsh2/114_hires.png"}',
    searchName: 'Stunky (RCL 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Skuntank',
    tcgApiId: 'swsh2-115',
    number: '115',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/115.png","large":"https://images.pokemontcg.io/swsh2/115_hires.png"}',
    searchName: 'Skuntank (RCL 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Spiritomb',
    tcgApiId: 'swsh2-116',
    number: '116',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/116.png","large":"https://images.pokemontcg.io/swsh2/116_hires.png"}',
    searchName: 'Spiritomb (RCL 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Trubbish',
    tcgApiId: 'swsh2-117',
    number: '117',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/117.png","large":"https://images.pokemontcg.io/swsh2/117_hires.png"}',
    searchName: 'Trubbish (RCL 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Garbodor',
    tcgApiId: 'swsh2-118',
    number: '118',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/118.png","large":"https://images.pokemontcg.io/swsh2/118_hires.png"}',
    searchName: 'Garbodor (RCL 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Vullaby',
    tcgApiId: 'swsh2-119',
    number: '119',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/119.png","large":"https://images.pokemontcg.io/swsh2/119_hires.png"}',
    searchName: 'Vullaby (RCL 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Mandibuzz',
    tcgApiId: 'swsh2-120',
    number: '120',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/120.png","large":"https://images.pokemontcg.io/swsh2/120_hires.png"}',
    searchName: 'Mandibuzz (RCL 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Malamar V',
    tcgApiId: 'swsh2-121',
    number: '121',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/121.png","large":"https://images.pokemontcg.io/swsh2/121_hires.png"}',
    searchName: 'Malamar V (RCL 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Malamar VMAX',
    tcgApiId: 'swsh2-122',
    number: '122',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/122.png","large":"https://images.pokemontcg.io/swsh2/122_hires.png"}',
    searchName: 'Malamar VMAX (RCL 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Impidimp',
    tcgApiId: 'swsh2-123',
    number: '123',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/123.png","large":"https://images.pokemontcg.io/swsh2/123_hires.png"}',
    searchName: 'Impidimp (RCL 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Morgrem',
    tcgApiId: 'swsh2-124',
    number: '124',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/124.png","large":"https://images.pokemontcg.io/swsh2/124_hires.png"}',
    searchName: 'Morgrem (RCL 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Grimmsnarl',
    tcgApiId: 'swsh2-125',
    number: '125',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/125.png","large":"https://images.pokemontcg.io/swsh2/125_hires.png"}',
    searchName: 'Grimmsnarl (RCL 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Meowth',
    tcgApiId: 'swsh2-126',
    number: '126',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/126.png","large":"https://images.pokemontcg.io/swsh2/126_hires.png"}',
    searchName: 'Galarian Meowth (RCL 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Perrserker',
    tcgApiId: 'swsh2-127',
    number: '127',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/127.png","large":"https://images.pokemontcg.io/swsh2/127_hires.png"}',
    searchName: 'Galarian Perrserker (RCL 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Scizor',
    tcgApiId: 'swsh2-128',
    number: '128',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/128.png","large":"https://images.pokemontcg.io/swsh2/128_hires.png"}',
    searchName: 'Scizor (RCL 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Bronzor',
    tcgApiId: 'swsh2-129',
    number: '129',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/129.png","large":"https://images.pokemontcg.io/swsh2/129_hires.png"}',
    searchName: 'Bronzor (RCL 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Bronzong',
    tcgApiId: 'swsh2-130',
    number: '130',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/130.png","large":"https://images.pokemontcg.io/swsh2/130_hires.png"}',
    searchName: 'Bronzong (RCL 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Probopass',
    tcgApiId: 'swsh2-131',
    number: '131',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/131.png","large":"https://images.pokemontcg.io/swsh2/131_hires.png"}',
    searchName: 'Probopass (RCL 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Durant',
    tcgApiId: 'swsh2-132',
    number: '132',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/132.png","large":"https://images.pokemontcg.io/swsh2/132_hires.png"}',
    searchName: 'Durant (RCL 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Honedge',
    tcgApiId: 'swsh2-133',
    number: '133',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/133.png","large":"https://images.pokemontcg.io/swsh2/133_hires.png"}',
    searchName: 'Honedge (RCL 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Doublade',
    tcgApiId: 'swsh2-134',
    number: '134',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/134.png","large":"https://images.pokemontcg.io/swsh2/134_hires.png"}',
    searchName: 'Doublade (RCL 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Aegislash',
    tcgApiId: 'swsh2-135',
    number: '135',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/135.png","large":"https://images.pokemontcg.io/swsh2/135_hires.png"}',
    searchName: 'Aegislash (RCL 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Copperajah V',
    tcgApiId: 'swsh2-136',
    number: '136',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/136.png","large":"https://images.pokemontcg.io/swsh2/136_hires.png"}',
    searchName: 'Copperajah V (RCL 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Copperajah VMAX',
    tcgApiId: 'swsh2-137',
    number: '137',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/137.png","large":"https://images.pokemontcg.io/swsh2/137_hires.png"}',
    searchName: 'Copperajah VMAX (RCL 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Duraludon',
    tcgApiId: 'swsh2-138',
    number: '138',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/138.png","large":"https://images.pokemontcg.io/swsh2/138_hires.png"}',
    searchName: 'Duraludon (RCL 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Zacian',
    tcgApiId: 'swsh2-139',
    number: '139',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/139.png","large":"https://images.pokemontcg.io/swsh2/139_hires.png"}',
    searchName: 'Zacian (RCL 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Zamazenta',
    tcgApiId: 'swsh2-140',
    number: '140',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/140.png","large":"https://images.pokemontcg.io/swsh2/140_hires.png"}',
    searchName: 'Zamazenta (RCL 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Snorlax',
    tcgApiId: 'swsh2-141',
    number: '141',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/141.png","large":"https://images.pokemontcg.io/swsh2/141_hires.png"}',
    searchName: 'Snorlax (RCL 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Chatot',
    tcgApiId: 'swsh2-142',
    number: '142',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/142.png","large":"https://images.pokemontcg.io/swsh2/142_hires.png"}',
    searchName: 'Chatot (RCL 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Pidove',
    tcgApiId: 'swsh2-143',
    number: '143',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/143.png","large":"https://images.pokemontcg.io/swsh2/143_hires.png"}',
    searchName: 'Pidove (RCL 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Tranquill',
    tcgApiId: 'swsh2-144',
    number: '144',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/144.png","large":"https://images.pokemontcg.io/swsh2/144_hires.png"}',
    searchName: 'Tranquill (RCL 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Unfezant',
    tcgApiId: 'swsh2-145',
    number: '145',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/145.png","large":"https://images.pokemontcg.io/swsh2/145_hires.png"}',
    searchName: 'Unfezant (RCL 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Bunnelby',
    tcgApiId: 'swsh2-146',
    number: '146',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/146.png","large":"https://images.pokemontcg.io/swsh2/146_hires.png"}',
    searchName: 'Bunnelby (RCL 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Diggersby',
    tcgApiId: 'swsh2-147',
    number: '147',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/147.png","large":"https://images.pokemontcg.io/swsh2/147_hires.png"}',
    searchName: 'Diggersby (RCL 147)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Hawlucha',
    tcgApiId: 'swsh2-148',
    number: '148',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/148.png","large":"https://images.pokemontcg.io/swsh2/148_hires.png"}',
    searchName: 'Hawlucha (RCL 148)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Stufful',
    tcgApiId: 'swsh2-149',
    number: '149',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/149.png","large":"https://images.pokemontcg.io/swsh2/149_hires.png"}',
    searchName: 'Stufful (RCL 149)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Bewear',
    tcgApiId: 'swsh2-150',
    number: '150',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/150.png","large":"https://images.pokemontcg.io/swsh2/150_hires.png"}',
    searchName: 'Bewear (RCL 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Skwovet',
    tcgApiId: 'swsh2-151',
    number: '151',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/151.png","large":"https://images.pokemontcg.io/swsh2/151_hires.png"}',
    searchName: 'Skwovet (RCL 151)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Greedent',
    tcgApiId: 'swsh2-152',
    number: '152',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/152.png","large":"https://images.pokemontcg.io/swsh2/152_hires.png"}',
    searchName: 'Greedent (RCL 152)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Dubwool V',
    tcgApiId: 'swsh2-153',
    number: '153',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/153.png","large":"https://images.pokemontcg.io/swsh2/153_hires.png"}',
    searchName: 'Dubwool V (RCL 153)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: "Boss's Orders",
    tcgApiId: 'swsh2-154',
    number: '154',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/154.png","large":"https://images.pokemontcg.io/swsh2/154_hires.png"}',
    searchName: "Boss's Orders (RCL 154)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Burning Scarf',
    tcgApiId: 'swsh2-155',
    number: '155',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/155.png","large":"https://images.pokemontcg.io/swsh2/155_hires.png"}',
    searchName: 'Burning Scarf (RCL 155)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Capacious Bucket',
    tcgApiId: 'swsh2-156',
    number: '156',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/156.png","large":"https://images.pokemontcg.io/swsh2/156_hires.png"}',
    searchName: 'Capacious Bucket (RCL 156)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Cursed Shovel',
    tcgApiId: 'swsh2-157',
    number: '157',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/157.png","large":"https://images.pokemontcg.io/swsh2/157_hires.png"}',
    searchName: 'Cursed Shovel (RCL 157)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Dan',
    tcgApiId: 'swsh2-158',
    number: '158',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/158.png","large":"https://images.pokemontcg.io/swsh2/158_hires.png"}',
    searchName: 'Dan (RCL 158)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Full Heal',
    tcgApiId: 'swsh2-159',
    number: '159',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/159.png","large":"https://images.pokemontcg.io/swsh2/159_hires.png"}',
    searchName: 'Full Heal (RCL 159)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galar Mine',
    tcgApiId: 'swsh2-160',
    number: '160',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/160.png","large":"https://images.pokemontcg.io/swsh2/160_hires.png"}',
    searchName: 'Galar Mine (RCL 160)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Milo',
    tcgApiId: 'swsh2-161',
    number: '161',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/161.png","large":"https://images.pokemontcg.io/swsh2/161_hires.png"}',
    searchName: 'Milo (RCL 161)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Nugget',
    tcgApiId: 'swsh2-162',
    number: '162',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/162.png","large":"https://images.pokemontcg.io/swsh2/162_hires.png"}',
    searchName: 'Nugget (RCL 162)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Oleana',
    tcgApiId: 'swsh2-163',
    number: '163',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/163.png","large":"https://images.pokemontcg.io/swsh2/163_hires.png"}',
    searchName: 'Oleana (RCL 163)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Poké Ball',
    tcgApiId: 'swsh2-164',
    number: '164',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/164.png","large":"https://images.pokemontcg.io/swsh2/164_hires.png"}',
    searchName: 'Poké Ball (RCL 164)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Scoop Up Net',
    tcgApiId: 'swsh2-165',
    number: '165',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/165.png","large":"https://images.pokemontcg.io/swsh2/165_hires.png"}',
    searchName: 'Scoop Up Net (RCL 165)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Skyla',
    tcgApiId: 'swsh2-166',
    number: '166',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/166.png","large":"https://images.pokemontcg.io/swsh2/166_hires.png"}',
    searchName: 'Skyla (RCL 166)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Sonia',
    tcgApiId: 'swsh2-167',
    number: '167',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/167.png","large":"https://images.pokemontcg.io/swsh2/167_hires.png"}',
    searchName: 'Sonia (RCL 167)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Tool Scrapper',
    tcgApiId: 'swsh2-168',
    number: '168',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/168.png","large":"https://images.pokemontcg.io/swsh2/168_hires.png"}',
    searchName: 'Tool Scrapper (RCL 168)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Training Court',
    tcgApiId: 'swsh2-169',
    number: '169',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/169.png","large":"https://images.pokemontcg.io/swsh2/169_hires.png"}',
    searchName: 'Training Court (RCL 169)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Turffield Stadium',
    tcgApiId: 'swsh2-170',
    number: '170',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/170.png","large":"https://images.pokemontcg.io/swsh2/170_hires.png"}',
    searchName: 'Turffield Stadium (RCL 170)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Capture Energy',
    tcgApiId: 'swsh2-171',
    number: '171',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/171.png","large":"https://images.pokemontcg.io/swsh2/171_hires.png"}',
    searchName: 'Capture Energy (RCL 171)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Horror Psychic Energy',
    tcgApiId: 'swsh2-172',
    number: '172',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/172.png","large":"https://images.pokemontcg.io/swsh2/172_hires.png"}',
    searchName: 'Horror Psychic Energy (RCL 172)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Speed Lightning Energy',
    tcgApiId: 'swsh2-173',
    number: '173',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/173.png","large":"https://images.pokemontcg.io/swsh2/173_hires.png"}',
    searchName: 'Speed Lightning Energy (RCL 173)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Twin Energy',
    tcgApiId: 'swsh2-174',
    number: '174',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/174.png","large":"https://images.pokemontcg.io/swsh2/174_hires.png"}',
    searchName: 'Twin Energy (RCL 174)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Rillaboom V',
    tcgApiId: 'swsh2-175',
    number: '175',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/175.png","large":"https://images.pokemontcg.io/swsh2/175_hires.png"}',
    searchName: 'Rillaboom V (RCL 175)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Eldegoss V',
    tcgApiId: 'swsh2-176',
    number: '176',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/176.png","large":"https://images.pokemontcg.io/swsh2/176_hires.png"}',
    searchName: 'Eldegoss V (RCL 176)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Ninetales V',
    tcgApiId: 'swsh2-177',
    number: '177',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/177.png","large":"https://images.pokemontcg.io/swsh2/177_hires.png"}',
    searchName: 'Ninetales V (RCL 177)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Cinderace V',
    tcgApiId: 'swsh2-178',
    number: '178',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/178.png","large":"https://images.pokemontcg.io/swsh2/178_hires.png"}',
    searchName: 'Cinderace V (RCL 178)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Milotic V',
    tcgApiId: 'swsh2-179',
    number: '179',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/179.png","large":"https://images.pokemontcg.io/swsh2/179_hires.png"}',
    searchName: 'Milotic V (RCL 179)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Inteleon V',
    tcgApiId: 'swsh2-180',
    number: '180',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/180.png","large":"https://images.pokemontcg.io/swsh2/180_hires.png"}',
    searchName: 'Inteleon V (RCL 180)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Boltund V',
    tcgApiId: 'swsh2-181',
    number: '181',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/181.png","large":"https://images.pokemontcg.io/swsh2/181_hires.png"}',
    searchName: 'Boltund V (RCL 181)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Toxtricity V',
    tcgApiId: 'swsh2-182',
    number: '182',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/182.png","large":"https://images.pokemontcg.io/swsh2/182_hires.png"}',
    searchName: 'Toxtricity V (RCL 182)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Dragapult V',
    tcgApiId: 'swsh2-183',
    number: '183',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/183.png","large":"https://images.pokemontcg.io/swsh2/183_hires.png"}',
    searchName: 'Dragapult V (RCL 183)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Sandaconda V',
    tcgApiId: 'swsh2-184',
    number: '184',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/184.png","large":"https://images.pokemontcg.io/swsh2/184_hires.png"}',
    searchName: 'Sandaconda V (RCL 184)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Falinks V',
    tcgApiId: 'swsh2-185',
    number: '185',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/185.png","large":"https://images.pokemontcg.io/swsh2/185_hires.png"}',
    searchName: 'Falinks V (RCL 185)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Malamar V',
    tcgApiId: 'swsh2-186',
    number: '186',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/186.png","large":"https://images.pokemontcg.io/swsh2/186_hires.png"}',
    searchName: 'Malamar V (RCL 186)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Copperajah V',
    tcgApiId: 'swsh2-187',
    number: '187',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/187.png","large":"https://images.pokemontcg.io/swsh2/187_hires.png"}',
    searchName: 'Copperajah V (RCL 187)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Dubwool V',
    tcgApiId: 'swsh2-188',
    number: '188',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/188.png","large":"https://images.pokemontcg.io/swsh2/188_hires.png"}',
    searchName: 'Dubwool V (RCL 188)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: "Boss's Orders",
    tcgApiId: 'swsh2-189',
    number: '189',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/189.png","large":"https://images.pokemontcg.io/swsh2/189_hires.png"}',
    searchName: "Boss's Orders (RCL 189)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Milo',
    tcgApiId: 'swsh2-190',
    number: '190',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/190.png","large":"https://images.pokemontcg.io/swsh2/190_hires.png"}',
    searchName: 'Milo (RCL 190)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Oleana',
    tcgApiId: 'swsh2-191',
    number: '191',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/191.png","large":"https://images.pokemontcg.io/swsh2/191_hires.png"}',
    searchName: 'Oleana (RCL 191)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Sonia',
    tcgApiId: 'swsh2-192',
    number: '192',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/192.png","large":"https://images.pokemontcg.io/swsh2/192_hires.png"}',
    searchName: 'Sonia (RCL 192)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Rillaboom VMAX',
    tcgApiId: 'swsh2-193',
    number: '193',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/193.png","large":"https://images.pokemontcg.io/swsh2/193_hires.png"}',
    searchName: 'Rillaboom VMAX (RCL 193)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Cinderace VMAX',
    tcgApiId: 'swsh2-194',
    number: '194',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/194.png","large":"https://images.pokemontcg.io/swsh2/194_hires.png"}',
    searchName: 'Cinderace VMAX (RCL 194)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Inteleon VMAX',
    tcgApiId: 'swsh2-195',
    number: '195',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/195.png","large":"https://images.pokemontcg.io/swsh2/195_hires.png"}',
    searchName: 'Inteleon VMAX (RCL 195)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Toxtricity VMAX',
    tcgApiId: 'swsh2-196',
    number: '196',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/196.png","large":"https://images.pokemontcg.io/swsh2/196_hires.png"}',
    searchName: 'Toxtricity VMAX (RCL 196)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Dragapult VMAX',
    tcgApiId: 'swsh2-197',
    number: '197',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/197.png","large":"https://images.pokemontcg.io/swsh2/197_hires.png"}',
    searchName: 'Dragapult VMAX (RCL 197)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Malamar VMAX',
    tcgApiId: 'swsh2-198',
    number: '198',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/198.png","large":"https://images.pokemontcg.io/swsh2/198_hires.png"}',
    searchName: 'Malamar VMAX (RCL 198)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Copperajah VMAX',
    tcgApiId: 'swsh2-199',
    number: '199',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/199.png","large":"https://images.pokemontcg.io/swsh2/199_hires.png"}',
    searchName: 'Copperajah VMAX (RCL 199)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: "Boss's Orders",
    tcgApiId: 'swsh2-200',
    number: '200',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/200.png","large":"https://images.pokemontcg.io/swsh2/200_hires.png"}',
    searchName: "Boss's Orders (RCL 200)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Milo',
    tcgApiId: 'swsh2-201',
    number: '201',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/201.png","large":"https://images.pokemontcg.io/swsh2/201_hires.png"}',
    searchName: 'Milo (RCL 201)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Oleana',
    tcgApiId: 'swsh2-202',
    number: '202',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/202.png","large":"https://images.pokemontcg.io/swsh2/202_hires.png"}',
    searchName: 'Oleana (RCL 202)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Sonia',
    tcgApiId: 'swsh2-203',
    number: '203',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/203.png","large":"https://images.pokemontcg.io/swsh2/203_hires.png"}',
    searchName: 'Sonia (RCL 203)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Frosmoth',
    tcgApiId: 'swsh2-204',
    number: '204',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/204.png","large":"https://images.pokemontcg.io/swsh2/204_hires.png"}',
    searchName: 'Frosmoth (RCL 204)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Galarian Perrserker',
    tcgApiId: 'swsh2-205',
    number: '205',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/205.png","large":"https://images.pokemontcg.io/swsh2/205_hires.png"}',
    searchName: 'Galarian Perrserker (RCL 205)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Big Charm',
    tcgApiId: 'swsh2-206',
    number: '206',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/206.png","large":"https://images.pokemontcg.io/swsh2/206_hires.png"}',
    searchName: 'Big Charm (RCL 206)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Scoop Up Net',
    tcgApiId: 'swsh2-207',
    number: '207',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/207.png","large":"https://images.pokemontcg.io/swsh2/207_hires.png"}',
    searchName: 'Scoop Up Net (RCL 207)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Tool Scrapper',
    tcgApiId: 'swsh2-208',
    number: '208',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/208.png","large":"https://images.pokemontcg.io/swsh2/208_hires.png"}',
    searchName: 'Tool Scrapper (RCL 208)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh2',
    name: 'Twin Energy',
    tcgApiId: 'swsh2-209',
    number: '209',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh2/209.png","large":"https://images.pokemontcg.io/swsh2/209_hires.png"}',
    searchName: 'Twin Energy (RCL 209)',
  },
];
