export const cardSeedSwsh12pt5gg = [
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Hisuian Voltorb',
    tcgApiId: 'swsh12pt5gg-GG01',
    number: 'GG01',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG01.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG01_hires.png"}',
    searchName: 'Hisuian Voltorb (CRZ GG01)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Kricketune',
    tcgApiId: 'swsh12pt5gg-GG02',
    number: 'GG02',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG02.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG02_hires.png"}',
    searchName: 'Kricketune (CRZ GG02)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Magmortar',
    tcgApiId: 'swsh12pt5gg-GG03',
    number: 'GG03',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG03.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG03_hires.png"}',
    searchName: 'Magmortar (CRZ GG03)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Oricorio',
    tcgApiId: 'swsh12pt5gg-GG04',
    number: 'GG04',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG04.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG04_hires.png"}',
    searchName: 'Oricorio (CRZ GG04)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Lapras',
    tcgApiId: 'swsh12pt5gg-GG05',
    number: 'GG05',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG05.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG05_hires.png"}',
    searchName: 'Lapras (CRZ GG05)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Manaphy',
    tcgApiId: 'swsh12pt5gg-GG06',
    number: 'GG06',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG06.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG06_hires.png"}',
    searchName: 'Manaphy (CRZ GG06)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Keldeo',
    tcgApiId: 'swsh12pt5gg-GG07',
    number: 'GG07',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG07.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG07_hires.png"}',
    searchName: 'Keldeo (CRZ GG07)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Electivire',
    tcgApiId: 'swsh12pt5gg-GG08',
    number: 'GG08',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG08.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG08_hires.png"}',
    searchName: 'Electivire (CRZ GG08)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Toxtricity',
    tcgApiId: 'swsh12pt5gg-GG09',
    number: 'GG09',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG09.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG09_hires.png"}',
    searchName: 'Toxtricity (CRZ GG09)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Mew',
    tcgApiId: 'swsh12pt5gg-GG10',
    number: 'GG10',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG10.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG10_hires.png"}',
    searchName: 'Mew (CRZ GG10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Lunatone',
    tcgApiId: 'swsh12pt5gg-GG11',
    number: 'GG11',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG11.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG11_hires.png"}',
    searchName: 'Lunatone (CRZ GG11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Deoxys',
    tcgApiId: 'swsh12pt5gg-GG12',
    number: 'GG12',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG12.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG12_hires.png"}',
    searchName: 'Deoxys (CRZ GG12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Diancie',
    tcgApiId: 'swsh12pt5gg-GG13',
    number: 'GG13',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG13.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG13_hires.png"}',
    searchName: 'Diancie (CRZ GG13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Comfey',
    tcgApiId: 'swsh12pt5gg-GG14',
    number: 'GG14',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG14.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG14_hires.png"}',
    searchName: 'Comfey (CRZ GG14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Solrock',
    tcgApiId: 'swsh12pt5gg-GG15',
    number: 'GG15',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG15.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG15_hires.png"}',
    searchName: 'Solrock (CRZ GG15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Absol',
    tcgApiId: 'swsh12pt5gg-GG16',
    number: 'GG16',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG16.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG16_hires.png"}',
    searchName: 'Absol (CRZ GG16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Thievul',
    tcgApiId: 'swsh12pt5gg-GG17',
    number: 'GG17',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG17.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG17_hires.png"}',
    searchName: 'Thievul (CRZ GG17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Magnezone',
    tcgApiId: 'swsh12pt5gg-GG18',
    number: 'GG18',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG18.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG18_hires.png"}',
    searchName: 'Magnezone (CRZ GG18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Altaria',
    tcgApiId: 'swsh12pt5gg-GG19',
    number: 'GG19',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG19.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG19_hires.png"}',
    searchName: 'Altaria (CRZ GG19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Latias',
    tcgApiId: 'swsh12pt5gg-GG20',
    number: 'GG20',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG20.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG20_hires.png"}',
    searchName: 'Latias (CRZ GG20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Hisuian Goodra',
    tcgApiId: 'swsh12pt5gg-GG21',
    number: 'GG21',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG21.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG21_hires.png"}',
    searchName: 'Hisuian Goodra (CRZ GG21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Ditto',
    tcgApiId: 'swsh12pt5gg-GG22',
    number: 'GG22',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG22.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG22_hires.png"}',
    searchName: 'Ditto (CRZ GG22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Dunsparce',
    tcgApiId: 'swsh12pt5gg-GG23',
    number: 'GG23',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG23.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG23_hires.png"}',
    searchName: 'Dunsparce (CRZ GG23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Miltank',
    tcgApiId: 'swsh12pt5gg-GG24',
    number: 'GG24',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG24.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG24_hires.png"}',
    searchName: 'Miltank (CRZ GG24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Bibarel',
    tcgApiId: 'swsh12pt5gg-GG25',
    number: 'GG25',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG25.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG25_hires.png"}',
    searchName: 'Bibarel (CRZ GG25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Riolu',
    tcgApiId: 'swsh12pt5gg-GG26',
    number: 'GG26',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG26.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG26_hires.png"}',
    searchName: 'Riolu (CRZ GG26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Swablu',
    tcgApiId: 'swsh12pt5gg-GG27',
    number: 'GG27',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG27.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG27_hires.png"}',
    searchName: 'Swablu (CRZ GG27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Duskull',
    tcgApiId: 'swsh12pt5gg-GG28',
    number: 'GG28',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG28.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG28_hires.png"}',
    searchName: 'Duskull (CRZ GG28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Bidoof',
    tcgApiId: 'swsh12pt5gg-GG29',
    number: 'GG29',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG29.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG29_hires.png"}',
    searchName: 'Bidoof (CRZ GG29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Pikachu',
    tcgApiId: 'swsh12pt5gg-GG30',
    number: 'GG30',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG30.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG30_hires.png"}',
    searchName: 'Pikachu (CRZ GG30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Turtwig',
    tcgApiId: 'swsh12pt5gg-GG31',
    number: 'GG31',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG31.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG31_hires.png"}',
    searchName: 'Turtwig (CRZ GG31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Paras',
    tcgApiId: 'swsh12pt5gg-GG32',
    number: 'GG32',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG32.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG32_hires.png"}',
    searchName: 'Paras (CRZ GG32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Poochyena',
    tcgApiId: 'swsh12pt5gg-GG33',
    number: 'GG33',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG33.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG33_hires.png"}',
    searchName: 'Poochyena (CRZ GG33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Mareep',
    tcgApiId: 'swsh12pt5gg-GG34',
    number: 'GG34',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG34.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG34_hires.png"}',
    searchName: 'Mareep (CRZ GG34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Leafeon VSTAR',
    tcgApiId: 'swsh12pt5gg-GG35',
    number: 'GG35',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG35.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG35_hires.png"}',
    searchName: 'Leafeon VSTAR (CRZ GG35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Entei V',
    tcgApiId: 'swsh12pt5gg-GG36',
    number: 'GG36',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG36.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG36_hires.png"}',
    searchName: 'Entei V (CRZ GG36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Simisear VSTAR',
    tcgApiId: 'swsh12pt5gg-GG37',
    number: 'GG37',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG37.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG37_hires.png"}',
    searchName: 'Simisear VSTAR (CRZ GG37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Suicune V',
    tcgApiId: 'swsh12pt5gg-GG38',
    number: 'GG38',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG38.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG38_hires.png"}',
    searchName: 'Suicune V (CRZ GG38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Lumineon V',
    tcgApiId: 'swsh12pt5gg-GG39',
    number: 'GG39',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG39.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG39_hires.png"}',
    searchName: 'Lumineon V (CRZ GG39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Glaceon VSTAR',
    tcgApiId: 'swsh12pt5gg-GG40',
    number: 'GG40',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG40.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG40_hires.png"}',
    searchName: 'Glaceon VSTAR (CRZ GG40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Raikou V',
    tcgApiId: 'swsh12pt5gg-GG41',
    number: 'GG41',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG41.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG41_hires.png"}',
    searchName: 'Raikou V (CRZ GG41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Zeraora VMAX',
    tcgApiId: 'swsh12pt5gg-GG42',
    number: 'GG42',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG42.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG42_hires.png"}',
    searchName: 'Zeraora VMAX (CRZ GG42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Zeraora VSTAR',
    tcgApiId: 'swsh12pt5gg-GG43',
    number: 'GG43',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG43.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG43_hires.png"}',
    searchName: 'Zeraora VSTAR (CRZ GG43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Mewtwo VSTAR',
    tcgApiId: 'swsh12pt5gg-GG44',
    number: 'GG44',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG44.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG44_hires.png"}',
    searchName: 'Mewtwo VSTAR (CRZ GG44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Deoxys VMAX',
    tcgApiId: 'swsh12pt5gg-GG45',
    number: 'GG45',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG45.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG45_hires.png"}',
    searchName: 'Deoxys VMAX (CRZ GG45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Deoxys VSTAR',
    tcgApiId: 'swsh12pt5gg-GG46',
    number: 'GG46',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG46.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG46_hires.png"}',
    searchName: 'Deoxys VSTAR (CRZ GG46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Hatterene VMAX',
    tcgApiId: 'swsh12pt5gg-GG47',
    number: 'GG47',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG47.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG47_hires.png"}',
    searchName: 'Hatterene VMAX (CRZ GG47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Zacian V',
    tcgApiId: 'swsh12pt5gg-GG48',
    number: 'GG48',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG48.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG48_hires.png"}',
    searchName: 'Zacian V (CRZ GG48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Drapion V',
    tcgApiId: 'swsh12pt5gg-GG49',
    number: 'GG49',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG49.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG49_hires.png"}',
    searchName: 'Drapion V (CRZ GG49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Darkrai VSTAR',
    tcgApiId: 'swsh12pt5gg-GG50',
    number: 'GG50',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG50.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG50_hires.png"}',
    searchName: 'Darkrai VSTAR (CRZ GG50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Hisuian Samurott V',
    tcgApiId: 'swsh12pt5gg-GG51',
    number: 'GG51',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG51.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG51_hires.png"}',
    searchName: 'Hisuian Samurott V (CRZ GG51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Hisuian Samurott VSTAR',
    tcgApiId: 'swsh12pt5gg-GG52',
    number: 'GG52',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG52.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG52_hires.png"}',
    searchName: 'Hisuian Samurott VSTAR (CRZ GG52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Hoopa V',
    tcgApiId: 'swsh12pt5gg-GG53',
    number: 'GG53',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG53.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG53_hires.png"}',
    searchName: 'Hoopa V (CRZ GG53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Zamazenta V',
    tcgApiId: 'swsh12pt5gg-GG54',
    number: 'GG54',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG54.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG54_hires.png"}',
    searchName: 'Zamazenta V (CRZ GG54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Regigigas VSTAR',
    tcgApiId: 'swsh12pt5gg-GG55',
    number: 'GG55',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG55.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG55_hires.png"}',
    searchName: 'Regigigas VSTAR (CRZ GG55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Hisuian Zoroark VSTAR',
    tcgApiId: 'swsh12pt5gg-GG56',
    number: 'GG56',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG56.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG56_hires.png"}',
    searchName: 'Hisuian Zoroark VSTAR (CRZ GG56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Adaman',
    tcgApiId: 'swsh12pt5gg-GG57',
    number: 'GG57',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG57.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG57_hires.png"}',
    searchName: 'Adaman (CRZ GG57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: "Cheren's Care",
    tcgApiId: 'swsh12pt5gg-GG58',
    number: 'GG58',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG58.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG58_hires.png"}',
    searchName: "Cheren's Care (CRZ GG58)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: "Colress's Experiment",
    tcgApiId: 'swsh12pt5gg-GG59',
    number: 'GG59',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG59.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG59_hires.png"}',
    searchName: "Colress's Experiment (CRZ GG59)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: "Cynthia's Ambition",
    tcgApiId: 'swsh12pt5gg-GG60',
    number: 'GG60',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG60.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG60_hires.png"}',
    searchName: "Cynthia's Ambition (CRZ GG60)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: "Gardenia's Vigor",
    tcgApiId: 'swsh12pt5gg-GG61',
    number: 'GG61',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG61.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG61_hires.png"}',
    searchName: "Gardenia's Vigor (CRZ GG61)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Grant',
    tcgApiId: 'swsh12pt5gg-GG62',
    number: 'GG62',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG62.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG62_hires.png"}',
    searchName: 'Grant (CRZ GG62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Irida',
    tcgApiId: 'swsh12pt5gg-GG63',
    number: 'GG63',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG63.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG63_hires.png"}',
    searchName: 'Irida (CRZ GG63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Melony',
    tcgApiId: 'swsh12pt5gg-GG64',
    number: 'GG64',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG64.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG64_hires.png"}',
    searchName: 'Melony (CRZ GG64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Raihan',
    tcgApiId: 'swsh12pt5gg-GG65',
    number: 'GG65',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG65.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG65_hires.png"}',
    searchName: 'Raihan (CRZ GG65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Roxanne',
    tcgApiId: 'swsh12pt5gg-GG66',
    number: 'GG66',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG66.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG66_hires.png"}',
    searchName: 'Roxanne (CRZ GG66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Origin Forme Palkia VSTAR',
    tcgApiId: 'swsh12pt5gg-GG67',
    number: 'GG67',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG67.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG67_hires.png"}',
    searchName: 'Origin Forme Palkia VSTAR (CRZ GG67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Origin Forme Dialga VSTAR',
    tcgApiId: 'swsh12pt5gg-GG68',
    number: 'GG68',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG68.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG68_hires.png"}',
    searchName: 'Origin Forme Dialga VSTAR (CRZ GG68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Giratina VSTAR',
    tcgApiId: 'swsh12pt5gg-GG69',
    number: 'GG69',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG69.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG69_hires.png"}',
    searchName: 'Giratina VSTAR (CRZ GG69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12pt5gg',
    name: 'Arceus VSTAR',
    tcgApiId: 'swsh12pt5gg-GG70',
    number: 'GG70',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12pt5gg/GG70.png","large":"https://images.pokemontcg.io/swsh12pt5gg/GG70_hires.png"}',
    searchName: 'Arceus VSTAR (CRZ GG70)',
  },
];
