export const cardSeedSwsh11 = [
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Oddish',
    tcgApiId: 'swsh11-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/1.png","large":"https://images.pokemontcg.io/swsh11/1_hires.png"}',
    searchName: 'Oddish (LOR 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Gloom',
    tcgApiId: 'swsh11-2',
    number: '2',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/2.png","large":"https://images.pokemontcg.io/swsh11/2_hires.png"}',
    searchName: 'Gloom (LOR 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Vileplume',
    tcgApiId: 'swsh11-3',
    number: '3',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/3.png","large":"https://images.pokemontcg.io/swsh11/3_hires.png"}',
    searchName: 'Vileplume (LOR 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Paras',
    tcgApiId: 'swsh11-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/4.png","large":"https://images.pokemontcg.io/swsh11/4_hires.png"}',
    searchName: 'Paras (LOR 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Parasect',
    tcgApiId: 'swsh11-5',
    number: '5',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/5.png","large":"https://images.pokemontcg.io/swsh11/5_hires.png"}',
    searchName: 'Parasect (LOR 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Wurmple',
    tcgApiId: 'swsh11-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/6.png","large":"https://images.pokemontcg.io/swsh11/6_hires.png"}',
    searchName: 'Wurmple (LOR 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Silcoon',
    tcgApiId: 'swsh11-7',
    number: '7',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/7.png","large":"https://images.pokemontcg.io/swsh11/7_hires.png"}',
    searchName: 'Silcoon (LOR 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Beautifly',
    tcgApiId: 'swsh11-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/8.png","large":"https://images.pokemontcg.io/swsh11/8_hires.png"}',
    searchName: 'Beautifly (LOR 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Cascoon',
    tcgApiId: 'swsh11-9',
    number: '9',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/9.png","large":"https://images.pokemontcg.io/swsh11/9_hires.png"}',
    searchName: 'Cascoon (LOR 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Dustox',
    tcgApiId: 'swsh11-10',
    number: '10',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/10.png","large":"https://images.pokemontcg.io/swsh11/10_hires.png"}',
    searchName: 'Dustox (LOR 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Seedot',
    tcgApiId: 'swsh11-11',
    number: '11',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/11.png","large":"https://images.pokemontcg.io/swsh11/11_hires.png"}',
    searchName: 'Seedot (LOR 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Nuzleaf',
    tcgApiId: 'swsh11-12',
    number: '12',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/12.png","large":"https://images.pokemontcg.io/swsh11/12_hires.png"}',
    searchName: 'Nuzleaf (LOR 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Shiftry',
    tcgApiId: 'swsh11-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/13.png","large":"https://images.pokemontcg.io/swsh11/13_hires.png"}',
    searchName: 'Shiftry (LOR 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Roselia',
    tcgApiId: 'swsh11-14',
    number: '14',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/14.png","large":"https://images.pokemontcg.io/swsh11/14_hires.png"}',
    searchName: 'Roselia (LOR 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Roserade',
    tcgApiId: 'swsh11-15',
    number: '15',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/15.png","large":"https://images.pokemontcg.io/swsh11/15_hires.png"}',
    searchName: 'Roserade (LOR 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Phantump',
    tcgApiId: 'swsh11-16',
    number: '16',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/16.png","large":"https://images.pokemontcg.io/swsh11/16_hires.png"}',
    searchName: 'Phantump (LOR 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Trevenant',
    tcgApiId: 'swsh11-17',
    number: '17',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/17.png","large":"https://images.pokemontcg.io/swsh11/17_hires.png"}',
    searchName: 'Trevenant (LOR 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Blipbug',
    tcgApiId: 'swsh11-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/18.png","large":"https://images.pokemontcg.io/swsh11/18_hires.png"}',
    searchName: 'Blipbug (LOR 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Dottler',
    tcgApiId: 'swsh11-19',
    number: '19',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/19.png","large":"https://images.pokemontcg.io/swsh11/19_hires.png"}',
    searchName: 'Dottler (LOR 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Orbeetle',
    tcgApiId: 'swsh11-20',
    number: '20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/20.png","large":"https://images.pokemontcg.io/swsh11/20_hires.png"}',
    searchName: 'Orbeetle (LOR 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Slugma',
    tcgApiId: 'swsh11-21',
    number: '21',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/21.png","large":"https://images.pokemontcg.io/swsh11/21_hires.png"}',
    searchName: 'Slugma (LOR 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Magcargo',
    tcgApiId: 'swsh11-22',
    number: '22',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/22.png","large":"https://images.pokemontcg.io/swsh11/22_hires.png"}',
    searchName: 'Magcargo (LOR 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Torkoal',
    tcgApiId: 'swsh11-23',
    number: '23',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/23.png","large":"https://images.pokemontcg.io/swsh11/23_hires.png"}',
    searchName: 'Torkoal (LOR 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Litwick',
    tcgApiId: 'swsh11-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/24.png","large":"https://images.pokemontcg.io/swsh11/24_hires.png"}',
    searchName: 'Litwick (LOR 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lampent',
    tcgApiId: 'swsh11-25',
    number: '25',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/25.png","large":"https://images.pokemontcg.io/swsh11/25_hires.png"}',
    searchName: 'Lampent (LOR 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Chandelure',
    tcgApiId: 'swsh11-26',
    number: '26',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/26.png","large":"https://images.pokemontcg.io/swsh11/26_hires.png"}',
    searchName: 'Chandelure (LOR 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Delphox V',
    tcgApiId: 'swsh11-27',
    number: '27',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/27.png","large":"https://images.pokemontcg.io/swsh11/27_hires.png"}',
    searchName: 'Delphox V (LOR 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Litleo',
    tcgApiId: 'swsh11-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/28.png","large":"https://images.pokemontcg.io/swsh11/28_hires.png"}',
    searchName: 'Litleo (LOR 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Pyroar',
    tcgApiId: 'swsh11-29',
    number: '29',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/29.png","large":"https://images.pokemontcg.io/swsh11/29_hires.png"}',
    searchName: 'Pyroar (LOR 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Poliwag',
    tcgApiId: 'swsh11-30',
    number: '30',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/30.png","large":"https://images.pokemontcg.io/swsh11/30_hires.png"}',
    searchName: 'Poliwag (LOR 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Poliwhirl',
    tcgApiId: 'swsh11-31',
    number: '31',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/31.png","large":"https://images.pokemontcg.io/swsh11/31_hires.png"}',
    searchName: 'Poliwhirl (LOR 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Politoed',
    tcgApiId: 'swsh11-32',
    number: '32',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/32.png","large":"https://images.pokemontcg.io/swsh11/32_hires.png"}',
    searchName: 'Politoed (LOR 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Seel',
    tcgApiId: 'swsh11-33',
    number: '33',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/33.png","large":"https://images.pokemontcg.io/swsh11/33_hires.png"}',
    searchName: 'Seel (LOR 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Dewgong',
    tcgApiId: 'swsh11-34',
    number: '34',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/34.png","large":"https://images.pokemontcg.io/swsh11/34_hires.png"}',
    searchName: 'Dewgong (LOR 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Horsea',
    tcgApiId: 'swsh11-35',
    number: '35',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/35.png","large":"https://images.pokemontcg.io/swsh11/35_hires.png"}',
    searchName: 'Horsea (LOR 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Seadra',
    tcgApiId: 'swsh11-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/36.png","large":"https://images.pokemontcg.io/swsh11/36_hires.png"}',
    searchName: 'Seadra (LOR 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Kingdra',
    tcgApiId: 'swsh11-37',
    number: '37',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/37.png","large":"https://images.pokemontcg.io/swsh11/37_hires.png"}',
    searchName: 'Kingdra (LOR 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Luvdisc',
    tcgApiId: 'swsh11-38',
    number: '38',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/38.png","large":"https://images.pokemontcg.io/swsh11/38_hires.png"}',
    searchName: 'Luvdisc (LOR 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Shellos',
    tcgApiId: 'swsh11-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/39.png","large":"https://images.pokemontcg.io/swsh11/39_hires.png"}',
    searchName: 'Shellos (LOR 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Finneon',
    tcgApiId: 'swsh11-40',
    number: '40',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/40.png","large":"https://images.pokemontcg.io/swsh11/40_hires.png"}',
    searchName: 'Finneon (LOR 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lumineon',
    tcgApiId: 'swsh11-41',
    number: '41',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/41.png","large":"https://images.pokemontcg.io/swsh11/41_hires.png"}',
    searchName: 'Lumineon (LOR 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Snover',
    tcgApiId: 'swsh11-42',
    number: '42',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/42.png","large":"https://images.pokemontcg.io/swsh11/42_hires.png"}',
    searchName: 'Snover (LOR 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Abomasnow',
    tcgApiId: 'swsh11-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/43.png","large":"https://images.pokemontcg.io/swsh11/43_hires.png"}',
    searchName: 'Abomasnow (LOR 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Basculin',
    tcgApiId: 'swsh11-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/44.png","large":"https://images.pokemontcg.io/swsh11/44_hires.png"}',
    searchName: 'Hisuian Basculin (LOR 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Basculegion',
    tcgApiId: 'swsh11-45',
    number: '45',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/45.png","large":"https://images.pokemontcg.io/swsh11/45_hires.png"}',
    searchName: 'Hisuian Basculegion (LOR 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Ducklett',
    tcgApiId: 'swsh11-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/46.png","large":"https://images.pokemontcg.io/swsh11/46_hires.png"}',
    searchName: 'Ducklett (LOR 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Swanna',
    tcgApiId: 'swsh11-47',
    number: '47',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/47.png","large":"https://images.pokemontcg.io/swsh11/47_hires.png"}',
    searchName: 'Swanna (LOR 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Kyurem V',
    tcgApiId: 'swsh11-48',
    number: '48',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/48.png","large":"https://images.pokemontcg.io/swsh11/48_hires.png"}',
    searchName: 'Kyurem V (LOR 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Kyurem VMAX',
    tcgApiId: 'swsh11-49',
    number: '49',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/49.png","large":"https://images.pokemontcg.io/swsh11/49_hires.png"}',
    searchName: 'Kyurem VMAX (LOR 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Cramorant',
    tcgApiId: 'swsh11-50',
    number: '50',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/50.png","large":"https://images.pokemontcg.io/swsh11/50_hires.png"}',
    searchName: 'Cramorant (LOR 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Glastrier',
    tcgApiId: 'swsh11-51',
    number: '51',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/51.png","large":"https://images.pokemontcg.io/swsh11/51_hires.png"}',
    searchName: 'Glastrier (LOR 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Pikachu',
    tcgApiId: 'swsh11-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/52.png","large":"https://images.pokemontcg.io/swsh11/52_hires.png"}',
    searchName: 'Pikachu (LOR 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Raichu',
    tcgApiId: 'swsh11-53',
    number: '53',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/53.png","large":"https://images.pokemontcg.io/swsh11/53_hires.png"}',
    searchName: 'Raichu (LOR 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Electrike',
    tcgApiId: 'swsh11-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/54.png","large":"https://images.pokemontcg.io/swsh11/54_hires.png"}',
    searchName: 'Electrike (LOR 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Manectric',
    tcgApiId: 'swsh11-55',
    number: '55',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/55.png","large":"https://images.pokemontcg.io/swsh11/55_hires.png"}',
    searchName: 'Manectric (LOR 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Magnezone V',
    tcgApiId: 'swsh11-56',
    number: '56',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/56.png","large":"https://images.pokemontcg.io/swsh11/56_hires.png"}',
    searchName: 'Magnezone V (LOR 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Magnezone VSTAR',
    tcgApiId: 'swsh11-57',
    number: '57',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/57.png","large":"https://images.pokemontcg.io/swsh11/57_hires.png"}',
    searchName: 'Magnezone VSTAR (LOR 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Rotom V',
    tcgApiId: 'swsh11-58',
    number: '58',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/58.png","large":"https://images.pokemontcg.io/swsh11/58_hires.png"}',
    searchName: 'Rotom V (LOR 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Tynamo',
    tcgApiId: 'swsh11-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/59.png","large":"https://images.pokemontcg.io/swsh11/59_hires.png"}',
    searchName: 'Tynamo (LOR 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Eelektrik',
    tcgApiId: 'swsh11-60',
    number: '60',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/60.png","large":"https://images.pokemontcg.io/swsh11/60_hires.png"}',
    searchName: 'Eelektrik (LOR 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Eelektross',
    tcgApiId: 'swsh11-61',
    number: '61',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/61.png","large":"https://images.pokemontcg.io/swsh11/61_hires.png"}',
    searchName: 'Eelektross (LOR 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Clefairy',
    tcgApiId: 'swsh11-62',
    number: '62',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/62.png","large":"https://images.pokemontcg.io/swsh11/62_hires.png"}',
    searchName: 'Clefairy (LOR 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Clefable',
    tcgApiId: 'swsh11-63',
    number: '63',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/63.png","large":"https://images.pokemontcg.io/swsh11/63_hires.png"}',
    searchName: 'Clefable (LOR 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Gastly',
    tcgApiId: 'swsh11-64',
    number: '64',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/64.png","large":"https://images.pokemontcg.io/swsh11/64_hires.png"}',
    searchName: 'Gastly (LOR 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Haunter',
    tcgApiId: 'swsh11-65',
    number: '65',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/65.png","large":"https://images.pokemontcg.io/swsh11/65_hires.png"}',
    searchName: 'Haunter (LOR 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Gengar',
    tcgApiId: 'swsh11-66',
    number: '66',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/66.png","large":"https://images.pokemontcg.io/swsh11/66_hires.png"}',
    searchName: 'Gengar (LOR 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Mr. Mime',
    tcgApiId: 'swsh11-67',
    number: '67',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/67.png","large":"https://images.pokemontcg.io/swsh11/67_hires.png"}',
    searchName: 'Mr. Mime (LOR 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Jynx',
    tcgApiId: 'swsh11-68',
    number: '68',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/68.png","large":"https://images.pokemontcg.io/swsh11/68_hires.png"}',
    searchName: 'Jynx (LOR 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Radiant Gardevoir',
    tcgApiId: 'swsh11-69',
    number: '69',
    rarity: 'Radiant Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/69.png","large":"https://images.pokemontcg.io/swsh11/69_hires.png"}',
    searchName: 'Radiant Gardevoir (LOR 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Sableye',
    tcgApiId: 'swsh11-70',
    number: '70',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/70.png","large":"https://images.pokemontcg.io/swsh11/70_hires.png"}',
    searchName: 'Sableye (LOR 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Mawile',
    tcgApiId: 'swsh11-71',
    number: '71',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/71.png","large":"https://images.pokemontcg.io/swsh11/71_hires.png"}',
    searchName: 'Mawile (LOR 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Shuppet',
    tcgApiId: 'swsh11-72',
    number: '72',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/72.png","large":"https://images.pokemontcg.io/swsh11/72_hires.png"}',
    searchName: 'Shuppet (LOR 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Banette',
    tcgApiId: 'swsh11-73',
    number: '73',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/73.png","large":"https://images.pokemontcg.io/swsh11/73_hires.png"}',
    searchName: 'Banette (LOR 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Cresselia',
    tcgApiId: 'swsh11-74',
    number: '74',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/74.png","large":"https://images.pokemontcg.io/swsh11/74_hires.png"}',
    searchName: 'Cresselia (LOR 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Zorua',
    tcgApiId: 'swsh11-75',
    number: '75',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/75.png","large":"https://images.pokemontcg.io/swsh11/75_hires.png"}',
    searchName: 'Hisuian Zorua (LOR 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Zoroark',
    tcgApiId: 'swsh11-76',
    number: '76',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/76.png","large":"https://images.pokemontcg.io/swsh11/76_hires.png"}',
    searchName: 'Hisuian Zoroark (LOR 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Inkay',
    tcgApiId: 'swsh11-77',
    number: '77',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/77.png","large":"https://images.pokemontcg.io/swsh11/77_hires.png"}',
    searchName: 'Inkay (LOR 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Malamar',
    tcgApiId: 'swsh11-78',
    number: '78',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/78.png","large":"https://images.pokemontcg.io/swsh11/78_hires.png"}',
    searchName: 'Malamar (LOR 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Comfey',
    tcgApiId: 'swsh11-79',
    number: '79',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/79.png","large":"https://images.pokemontcg.io/swsh11/79_hires.png"}',
    searchName: 'Comfey (LOR 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Mimikyu',
    tcgApiId: 'swsh11-80',
    number: '80',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/80.png","large":"https://images.pokemontcg.io/swsh11/80_hires.png"}',
    searchName: 'Mimikyu (LOR 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Spectrier',
    tcgApiId: 'swsh11-81',
    number: '81',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/81.png","large":"https://images.pokemontcg.io/swsh11/81_hires.png"}',
    searchName: 'Spectrier (LOR 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Enamorus V',
    tcgApiId: 'swsh11-82',
    number: '82',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/82.png","large":"https://images.pokemontcg.io/swsh11/82_hires.png"}',
    searchName: 'Enamorus V (LOR 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Growlithe',
    tcgApiId: 'swsh11-83',
    number: '83',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/83.png","large":"https://images.pokemontcg.io/swsh11/83_hires.png"}',
    searchName: 'Hisuian Growlithe (LOR 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Arcanine',
    tcgApiId: 'swsh11-84',
    number: '84',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/84.png","large":"https://images.pokemontcg.io/swsh11/84_hires.png"}',
    searchName: 'Hisuian Arcanine (LOR 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Poliwrath',
    tcgApiId: 'swsh11-85',
    number: '85',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/85.png","large":"https://images.pokemontcg.io/swsh11/85_hires.png"}',
    searchName: 'Poliwrath (LOR 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Machop',
    tcgApiId: 'swsh11-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/86.png","large":"https://images.pokemontcg.io/swsh11/86_hires.png"}',
    searchName: 'Machop (LOR 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Machoke',
    tcgApiId: 'swsh11-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/87.png","large":"https://images.pokemontcg.io/swsh11/87_hires.png"}',
    searchName: 'Machoke (LOR 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Machamp',
    tcgApiId: 'swsh11-88',
    number: '88',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/88.png","large":"https://images.pokemontcg.io/swsh11/88_hires.png"}',
    searchName: 'Machamp (LOR 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Rhyhorn',
    tcgApiId: 'swsh11-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/89.png","large":"https://images.pokemontcg.io/swsh11/89_hires.png"}',
    searchName: 'Rhyhorn (LOR 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Rhydon',
    tcgApiId: 'swsh11-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/90.png","large":"https://images.pokemontcg.io/swsh11/90_hires.png"}',
    searchName: 'Rhydon (LOR 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Rhyperior',
    tcgApiId: 'swsh11-91',
    number: '91',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/91.png","large":"https://images.pokemontcg.io/swsh11/91_hires.png"}',
    searchName: 'Rhyperior (LOR 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Aerodactyl V',
    tcgApiId: 'swsh11-92',
    number: '92',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/92.png","large":"https://images.pokemontcg.io/swsh11/92_hires.png"}',
    searchName: 'Aerodactyl V (LOR 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Aerodactyl VSTAR',
    tcgApiId: 'swsh11-93',
    number: '93',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/93.png","large":"https://images.pokemontcg.io/swsh11/93_hires.png"}',
    searchName: 'Aerodactyl VSTAR (LOR 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Sudowoodo',
    tcgApiId: 'swsh11-94',
    number: '94',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/94.png","large":"https://images.pokemontcg.io/swsh11/94_hires.png"}',
    searchName: 'Sudowoodo (LOR 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Gligar',
    tcgApiId: 'swsh11-95',
    number: '95',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/95.png","large":"https://images.pokemontcg.io/swsh11/95_hires.png"}',
    searchName: 'Gligar (LOR 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Gliscor',
    tcgApiId: 'swsh11-96',
    number: '96',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/96.png","large":"https://images.pokemontcg.io/swsh11/96_hires.png"}',
    searchName: 'Gliscor (LOR 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Makuhita',
    tcgApiId: 'swsh11-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/97.png","large":"https://images.pokemontcg.io/swsh11/97_hires.png"}',
    searchName: 'Makuhita (LOR 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hariyama',
    tcgApiId: 'swsh11-98',
    number: '98',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/98.png","large":"https://images.pokemontcg.io/swsh11/98_hires.png"}',
    searchName: 'Hariyama (LOR 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Meditite',
    tcgApiId: 'swsh11-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/99.png","large":"https://images.pokemontcg.io/swsh11/99_hires.png"}',
    searchName: 'Meditite (LOR 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Medicham',
    tcgApiId: 'swsh11-100',
    number: '100',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/100.png","large":"https://images.pokemontcg.io/swsh11/100_hires.png"}',
    searchName: 'Medicham (LOR 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Relicanth',
    tcgApiId: 'swsh11-101',
    number: '101',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/101.png","large":"https://images.pokemontcg.io/swsh11/101_hires.png"}',
    searchName: 'Relicanth (LOR 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Gastrodon',
    tcgApiId: 'swsh11-102',
    number: '102',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/102.png","large":"https://images.pokemontcg.io/swsh11/102_hires.png"}',
    searchName: 'Gastrodon (LOR 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Mienfoo',
    tcgApiId: 'swsh11-103',
    number: '103',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/103.png","large":"https://images.pokemontcg.io/swsh11/103_hires.png"}',
    searchName: 'Mienfoo (LOR 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Mienshao',
    tcgApiId: 'swsh11-104',
    number: '104',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/104.png","large":"https://images.pokemontcg.io/swsh11/104_hires.png"}',
    searchName: 'Mienshao (LOR 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Landorus',
    tcgApiId: 'swsh11-105',
    number: '105',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/105.png","large":"https://images.pokemontcg.io/swsh11/105_hires.png"}',
    searchName: 'Landorus (LOR 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Binacle',
    tcgApiId: 'swsh11-106',
    number: '106',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/106.png","large":"https://images.pokemontcg.io/swsh11/106_hires.png"}',
    searchName: 'Binacle (LOR 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Barbaracle',
    tcgApiId: 'swsh11-107',
    number: '107',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/107.png","large":"https://images.pokemontcg.io/swsh11/107_hires.png"}',
    searchName: 'Barbaracle (LOR 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Carbink',
    tcgApiId: 'swsh11-108',
    number: '108',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/108.png","large":"https://images.pokemontcg.io/swsh11/108_hires.png"}',
    searchName: 'Carbink (LOR 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Rockruff',
    tcgApiId: 'swsh11-109',
    number: '109',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/109.png","large":"https://images.pokemontcg.io/swsh11/109_hires.png"}',
    searchName: 'Rockruff (LOR 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Falinks',
    tcgApiId: 'swsh11-110',
    number: '110',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/110.png","large":"https://images.pokemontcg.io/swsh11/110_hires.png"}',
    searchName: 'Falinks (LOR 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Stonjourner',
    tcgApiId: 'swsh11-111',
    number: '111',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/111.png","large":"https://images.pokemontcg.io/swsh11/111_hires.png"}',
    searchName: 'Stonjourner (LOR 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Spinarak',
    tcgApiId: 'swsh11-112',
    number: '112',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/112.png","large":"https://images.pokemontcg.io/swsh11/112_hires.png"}',
    searchName: 'Spinarak (LOR 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Ariados',
    tcgApiId: 'swsh11-113',
    number: '113',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/113.png","large":"https://images.pokemontcg.io/swsh11/113_hires.png"}',
    searchName: 'Ariados (LOR 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Murkrow',
    tcgApiId: 'swsh11-114',
    number: '114',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/114.png","large":"https://images.pokemontcg.io/swsh11/114_hires.png"}',
    searchName: 'Murkrow (LOR 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Honchkrow',
    tcgApiId: 'swsh11-115',
    number: '115',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/115.png","large":"https://images.pokemontcg.io/swsh11/115_hires.png"}',
    searchName: 'Honchkrow (LOR 115)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Seviper',
    tcgApiId: 'swsh11-116',
    number: '116',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/116.png","large":"https://images.pokemontcg.io/swsh11/116_hires.png"}',
    searchName: 'Seviper (LOR 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Spiritomb',
    tcgApiId: 'swsh11-117',
    number: '117',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/117.png","large":"https://images.pokemontcg.io/swsh11/117_hires.png"}',
    searchName: 'Spiritomb (LOR 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Drapion V',
    tcgApiId: 'swsh11-118',
    number: '118',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/118.png","large":"https://images.pokemontcg.io/swsh11/118_hires.png"}',
    searchName: 'Drapion V (LOR 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Drapion VSTAR',
    tcgApiId: 'swsh11-119',
    number: '119',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/119.png","large":"https://images.pokemontcg.io/swsh11/119_hires.png"}',
    searchName: 'Drapion VSTAR (LOR 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Darkrai',
    tcgApiId: 'swsh11-120',
    number: '120',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/120.png","large":"https://images.pokemontcg.io/swsh11/120_hires.png"}',
    searchName: 'Darkrai (LOR 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Inkay',
    tcgApiId: 'swsh11-121',
    number: '121',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/121.png","large":"https://images.pokemontcg.io/swsh11/121_hires.png"}',
    searchName: 'Inkay (LOR 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hoopa',
    tcgApiId: 'swsh11-122',
    number: '122',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/122.png","large":"https://images.pokemontcg.io/swsh11/122_hires.png"}',
    searchName: 'Hoopa (LOR 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Radiant Hisuian Sneasler',
    tcgApiId: 'swsh11-123',
    number: '123',
    rarity: 'Radiant Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/123.png","large":"https://images.pokemontcg.io/swsh11/123_hires.png"}',
    searchName: 'Radiant Hisuian Sneasler (LOR 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Radiant Steelix',
    tcgApiId: 'swsh11-124',
    number: '124',
    rarity: 'Radiant Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/124.png","large":"https://images.pokemontcg.io/swsh11/124_hires.png"}',
    searchName: 'Radiant Steelix (LOR 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Bronzor',
    tcgApiId: 'swsh11-125',
    number: '125',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/125.png","large":"https://images.pokemontcg.io/swsh11/125_hires.png"}',
    searchName: 'Bronzor (LOR 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Bronzong',
    tcgApiId: 'swsh11-126',
    number: '126',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/126.png","large":"https://images.pokemontcg.io/swsh11/126_hires.png"}',
    searchName: 'Bronzong (LOR 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Galarian Stunfisk',
    tcgApiId: 'swsh11-127',
    number: '127',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/127.png","large":"https://images.pokemontcg.io/swsh11/127_hires.png"}',
    searchName: 'Galarian Stunfisk (LOR 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Magearna',
    tcgApiId: 'swsh11-128',
    number: '128',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/128.png","large":"https://images.pokemontcg.io/swsh11/128_hires.png"}',
    searchName: 'Magearna (LOR 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Galarian Perrserker V',
    tcgApiId: 'swsh11-129',
    number: '129',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/129.png","large":"https://images.pokemontcg.io/swsh11/129_hires.png"}',
    searchName: 'Galarian Perrserker V (LOR 129)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Giratina V',
    tcgApiId: 'swsh11-130',
    number: '130',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/130.png","large":"https://images.pokemontcg.io/swsh11/130_hires.png"}',
    searchName: 'Giratina V (LOR 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Giratina VSTAR',
    tcgApiId: 'swsh11-131',
    number: '131',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/131.png","large":"https://images.pokemontcg.io/swsh11/131_hires.png"}',
    searchName: 'Giratina VSTAR (LOR 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Goomy',
    tcgApiId: 'swsh11-132',
    number: '132',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/132.png","large":"https://images.pokemontcg.io/swsh11/132_hires.png"}',
    searchName: 'Goomy (LOR 132)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Sliggoo',
    tcgApiId: 'swsh11-133',
    number: '133',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/133.png","large":"https://images.pokemontcg.io/swsh11/133_hires.png"}',
    searchName: 'Hisuian Sliggoo (LOR 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Goodra',
    tcgApiId: 'swsh11-134',
    number: '134',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/134.png","large":"https://images.pokemontcg.io/swsh11/134_hires.png"}',
    searchName: 'Hisuian Goodra (LOR 134)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Goodra V',
    tcgApiId: 'swsh11-135',
    number: '135',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/135.png","large":"https://images.pokemontcg.io/swsh11/135_hires.png"}',
    searchName: 'Hisuian Goodra V (LOR 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Goodra VSTAR',
    tcgApiId: 'swsh11-136',
    number: '136',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/136.png","large":"https://images.pokemontcg.io/swsh11/136_hires.png"}',
    searchName: 'Hisuian Goodra VSTAR (LOR 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Pidgeot V',
    tcgApiId: 'swsh11-137',
    number: '137',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/137.png","large":"https://images.pokemontcg.io/swsh11/137_hires.png"}',
    searchName: 'Pidgeot V (LOR 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lickitung',
    tcgApiId: 'swsh11-138',
    number: '138',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/138.png","large":"https://images.pokemontcg.io/swsh11/138_hires.png"}',
    searchName: 'Lickitung (LOR 138)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lickilicky',
    tcgApiId: 'swsh11-139',
    number: '139',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/139.png","large":"https://images.pokemontcg.io/swsh11/139_hires.png"}',
    searchName: 'Lickilicky (LOR 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Porygon',
    tcgApiId: 'swsh11-140',
    number: '140',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/140.png","large":"https://images.pokemontcg.io/swsh11/140_hires.png"}',
    searchName: 'Porygon (LOR 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Porygon2',
    tcgApiId: 'swsh11-141',
    number: '141',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/141.png","large":"https://images.pokemontcg.io/swsh11/141_hires.png"}',
    searchName: 'Porygon2 (LOR 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Porygon-Z',
    tcgApiId: 'swsh11-142',
    number: '142',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/142.png","large":"https://images.pokemontcg.io/swsh11/142_hires.png"}',
    searchName: 'Porygon-Z (LOR 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Snorlax',
    tcgApiId: 'swsh11-143',
    number: '143',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/143.png","large":"https://images.pokemontcg.io/swsh11/143_hires.png"}',
    searchName: 'Snorlax (LOR 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Aipom',
    tcgApiId: 'swsh11-144',
    number: '144',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/144.png","large":"https://images.pokemontcg.io/swsh11/144_hires.png"}',
    searchName: 'Aipom (LOR 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Ambipom',
    tcgApiId: 'swsh11-145',
    number: '145',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/145.png","large":"https://images.pokemontcg.io/swsh11/145_hires.png"}',
    searchName: 'Ambipom (LOR 145)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Zoroark V',
    tcgApiId: 'swsh11-146',
    number: '146',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/146.png","large":"https://images.pokemontcg.io/swsh11/146_hires.png"}',
    searchName: 'Hisuian Zoroark V (LOR 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Zoroark VSTAR',
    tcgApiId: 'swsh11-147',
    number: '147',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/147.png","large":"https://images.pokemontcg.io/swsh11/147_hires.png"}',
    searchName: 'Hisuian Zoroark VSTAR (LOR 147)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Bouffalant',
    tcgApiId: 'swsh11-148',
    number: '148',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/148.png","large":"https://images.pokemontcg.io/swsh11/148_hires.png"}',
    searchName: 'Bouffalant (LOR 148)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Komala',
    tcgApiId: 'swsh11-149',
    number: '149',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/149.png","large":"https://images.pokemontcg.io/swsh11/149_hires.png"}',
    searchName: 'Komala (LOR 149)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Skwovet',
    tcgApiId: 'swsh11-150',
    number: '150',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/150.png","large":"https://images.pokemontcg.io/swsh11/150_hires.png"}',
    searchName: 'Skwovet (LOR 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Greedent',
    tcgApiId: 'swsh11-151',
    number: '151',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/151.png","large":"https://images.pokemontcg.io/swsh11/151_hires.png"}',
    searchName: 'Greedent (LOR 151)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Arc Phone',
    tcgApiId: 'swsh11-152',
    number: '152',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/152.png","large":"https://images.pokemontcg.io/swsh11/152_hires.png"}',
    searchName: 'Arc Phone (LOR 152)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Arezu',
    tcgApiId: 'swsh11-153',
    number: '153',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/153.png","large":"https://images.pokemontcg.io/swsh11/153_hires.png"}',
    searchName: 'Arezu (LOR 153)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Box of Disaster',
    tcgApiId: 'swsh11-154',
    number: '154',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/154.png","large":"https://images.pokemontcg.io/swsh11/154_hires.png"}',
    searchName: 'Box of Disaster (LOR 154)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: "Colress's Experiment",
    tcgApiId: 'swsh11-155',
    number: '155',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/155.png","large":"https://images.pokemontcg.io/swsh11/155_hires.png"}',
    searchName: "Colress's Experiment (LOR 155)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Damage Pump',
    tcgApiId: 'swsh11-156',
    number: '156',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/156.png","large":"https://images.pokemontcg.io/swsh11/156_hires.png"}',
    searchName: 'Damage Pump (LOR 156)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Fantina',
    tcgApiId: 'swsh11-157',
    number: '157',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/157.png","large":"https://images.pokemontcg.io/swsh11/157_hires.png"}',
    searchName: 'Fantina (LOR 157)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Iscan',
    tcgApiId: 'swsh11-158',
    number: '158',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/158.png","large":"https://images.pokemontcg.io/swsh11/158_hires.png"}',
    searchName: 'Iscan (LOR 158)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lady',
    tcgApiId: 'swsh11-159',
    number: '159',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/159.png","large":"https://images.pokemontcg.io/swsh11/159_hires.png"}',
    searchName: 'Lady (LOR 159)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lake Acuity',
    tcgApiId: 'swsh11-160',
    number: '160',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/160.png","large":"https://images.pokemontcg.io/swsh11/160_hires.png"}',
    searchName: 'Lake Acuity (LOR 160)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lost City',
    tcgApiId: 'swsh11-161',
    number: '161',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/161.png","large":"https://images.pokemontcg.io/swsh11/161_hires.png"}',
    searchName: 'Lost City (LOR 161)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lost Vacuum',
    tcgApiId: 'swsh11-162',
    number: '162',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/162.png","large":"https://images.pokemontcg.io/swsh11/162_hires.png"}',
    searchName: 'Lost Vacuum (LOR 162)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Mirage Gate',
    tcgApiId: 'swsh11-163',
    number: '163',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/163.png","large":"https://images.pokemontcg.io/swsh11/163_hires.png"}',
    searchName: 'Mirage Gate (LOR 163)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Miss Fortune Sisters',
    tcgApiId: 'swsh11-164',
    number: '164',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/164.png","large":"https://images.pokemontcg.io/swsh11/164_hires.png"}',
    searchName: 'Miss Fortune Sisters (LOR 164)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Panic Mask',
    tcgApiId: 'swsh11-165',
    number: '165',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/165.png","large":"https://images.pokemontcg.io/swsh11/165_hires.png"}',
    searchName: 'Panic Mask (LOR 165)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Riley',
    tcgApiId: 'swsh11-166',
    number: '166',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/166.png","large":"https://images.pokemontcg.io/swsh11/166_hires.png"}',
    searchName: 'Riley (LOR 166)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Thorton',
    tcgApiId: 'swsh11-167',
    number: '167',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/167.png","large":"https://images.pokemontcg.io/swsh11/167_hires.png"}',
    searchName: 'Thorton (LOR 167)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Tool Box',
    tcgApiId: 'swsh11-168',
    number: '168',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/168.png","large":"https://images.pokemontcg.io/swsh11/168_hires.png"}',
    searchName: 'Tool Box (LOR 168)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Volo',
    tcgApiId: 'swsh11-169',
    number: '169',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/169.png","large":"https://images.pokemontcg.io/swsh11/169_hires.png"}',
    searchName: 'Volo (LOR 169)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Windup Arm',
    tcgApiId: 'swsh11-170',
    number: '170',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/170.png","large":"https://images.pokemontcg.io/swsh11/170_hires.png"}',
    searchName: 'Windup Arm (LOR 170)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Gift Energy',
    tcgApiId: 'swsh11-171',
    number: '171',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/171.png","large":"https://images.pokemontcg.io/swsh11/171_hires.png"}',
    searchName: 'Gift Energy (LOR 171)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Electrode V',
    tcgApiId: 'swsh11-172',
    number: '172',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/172.png","large":"https://images.pokemontcg.io/swsh11/172_hires.png"}',
    searchName: 'Hisuian Electrode V (LOR 172)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Delphox V',
    tcgApiId: 'swsh11-173',
    number: '173',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/173.png","large":"https://images.pokemontcg.io/swsh11/173_hires.png"}',
    searchName: 'Delphox V (LOR 173)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Kyurem V',
    tcgApiId: 'swsh11-174',
    number: '174',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/174.png","large":"https://images.pokemontcg.io/swsh11/174_hires.png"}',
    searchName: 'Kyurem V (LOR 174)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Magnezone V',
    tcgApiId: 'swsh11-175',
    number: '175',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/175.png","large":"https://images.pokemontcg.io/swsh11/175_hires.png"}',
    searchName: 'Magnezone V (LOR 175)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Rotom V',
    tcgApiId: 'swsh11-176',
    number: '176',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/176.png","large":"https://images.pokemontcg.io/swsh11/176_hires.png"}',
    searchName: 'Rotom V (LOR 176)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Rotom V',
    tcgApiId: 'swsh11-177',
    number: '177',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/177.png","large":"https://images.pokemontcg.io/swsh11/177_hires.png"}',
    searchName: 'Rotom V (LOR 177)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Enamorus V',
    tcgApiId: 'swsh11-178',
    number: '178',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/178.png","large":"https://images.pokemontcg.io/swsh11/178_hires.png"}',
    searchName: 'Enamorus V (LOR 178)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Aerodactyl V',
    tcgApiId: 'swsh11-179',
    number: '179',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/179.png","large":"https://images.pokemontcg.io/swsh11/179_hires.png"}',
    searchName: 'Aerodactyl V (LOR 179)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Aerodactyl V',
    tcgApiId: 'swsh11-180',
    number: '180',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/180.png","large":"https://images.pokemontcg.io/swsh11/180_hires.png"}',
    searchName: 'Aerodactyl V (LOR 180)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Gallade V',
    tcgApiId: 'swsh11-181',
    number: '181',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/181.png","large":"https://images.pokemontcg.io/swsh11/181_hires.png"}',
    searchName: 'Gallade V (LOR 181)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Drapion V',
    tcgApiId: 'swsh11-182',
    number: '182',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/182.png","large":"https://images.pokemontcg.io/swsh11/182_hires.png"}',
    searchName: 'Drapion V (LOR 182)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Galarian Perrserker V',
    tcgApiId: 'swsh11-183',
    number: '183',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/183.png","large":"https://images.pokemontcg.io/swsh11/183_hires.png"}',
    searchName: 'Galarian Perrserker V (LOR 183)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Galarian Perrserker V',
    tcgApiId: 'swsh11-184',
    number: '184',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/184.png","large":"https://images.pokemontcg.io/swsh11/184_hires.png"}',
    searchName: 'Galarian Perrserker V (LOR 184)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Giratina V',
    tcgApiId: 'swsh11-185',
    number: '185',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/185.png","large":"https://images.pokemontcg.io/swsh11/185_hires.png"}',
    searchName: 'Giratina V (LOR 185)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Giratina V',
    tcgApiId: 'swsh11-186',
    number: '186',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/186.png","large":"https://images.pokemontcg.io/swsh11/186_hires.png"}',
    searchName: 'Giratina V (LOR 186)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Goodra V',
    tcgApiId: 'swsh11-187',
    number: '187',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/187.png","large":"https://images.pokemontcg.io/swsh11/187_hires.png"}',
    searchName: 'Hisuian Goodra V (LOR 187)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Pidgeot V',
    tcgApiId: 'swsh11-188',
    number: '188',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/188.png","large":"https://images.pokemontcg.io/swsh11/188_hires.png"}',
    searchName: 'Pidgeot V (LOR 188)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Arezu',
    tcgApiId: 'swsh11-189',
    number: '189',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/189.png","large":"https://images.pokemontcg.io/swsh11/189_hires.png"}',
    searchName: 'Arezu (LOR 189)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: "Colress's Experiment",
    tcgApiId: 'swsh11-190',
    number: '190',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/190.png","large":"https://images.pokemontcg.io/swsh11/190_hires.png"}',
    searchName: "Colress's Experiment (LOR 190)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Fantina',
    tcgApiId: 'swsh11-191',
    number: '191',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/191.png","large":"https://images.pokemontcg.io/swsh11/191_hires.png"}',
    searchName: 'Fantina (LOR 191)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Iscan',
    tcgApiId: 'swsh11-192',
    number: '192',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/192.png","large":"https://images.pokemontcg.io/swsh11/192_hires.png"}',
    searchName: 'Iscan (LOR 192)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lady',
    tcgApiId: 'swsh11-193',
    number: '193',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/193.png","large":"https://images.pokemontcg.io/swsh11/193_hires.png"}',
    searchName: 'Lady (LOR 193)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Miss Fortune Sisters',
    tcgApiId: 'swsh11-194',
    number: '194',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/194.png","large":"https://images.pokemontcg.io/swsh11/194_hires.png"}',
    searchName: 'Miss Fortune Sisters (LOR 194)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Thorton',
    tcgApiId: 'swsh11-195',
    number: '195',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/195.png","large":"https://images.pokemontcg.io/swsh11/195_hires.png"}',
    searchName: 'Thorton (LOR 195)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Volo',
    tcgApiId: 'swsh11-196',
    number: '196',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/196.png","large":"https://images.pokemontcg.io/swsh11/196_hires.png"}',
    searchName: 'Volo (LOR 196)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Kyurem VMAX',
    tcgApiId: 'swsh11-197',
    number: '197',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/197.png","large":"https://images.pokemontcg.io/swsh11/197_hires.png"}',
    searchName: 'Kyurem VMAX (LOR 197)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Magnezone VSTAR',
    tcgApiId: 'swsh11-198',
    number: '198',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/198.png","large":"https://images.pokemontcg.io/swsh11/198_hires.png"}',
    searchName: 'Magnezone VSTAR (LOR 198)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Aerodactyl VSTAR',
    tcgApiId: 'swsh11-199',
    number: '199',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/199.png","large":"https://images.pokemontcg.io/swsh11/199_hires.png"}',
    searchName: 'Aerodactyl VSTAR (LOR 199)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Drapion VSTAR',
    tcgApiId: 'swsh11-200',
    number: '200',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/200.png","large":"https://images.pokemontcg.io/swsh11/200_hires.png"}',
    searchName: 'Drapion VSTAR (LOR 200)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Giratina VSTAR',
    tcgApiId: 'swsh11-201',
    number: '201',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/201.png","large":"https://images.pokemontcg.io/swsh11/201_hires.png"}',
    searchName: 'Giratina VSTAR (LOR 201)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Goodra VSTAR',
    tcgApiId: 'swsh11-202',
    number: '202',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/202.png","large":"https://images.pokemontcg.io/swsh11/202_hires.png"}',
    searchName: 'Hisuian Goodra VSTAR (LOR 202)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Zoroark VSTAR',
    tcgApiId: 'swsh11-203',
    number: '203',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/203.png","large":"https://images.pokemontcg.io/swsh11/203_hires.png"}',
    searchName: 'Hisuian Zoroark VSTAR (LOR 203)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Arezu',
    tcgApiId: 'swsh11-204',
    number: '204',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/204.png","large":"https://images.pokemontcg.io/swsh11/204_hires.png"}',
    searchName: 'Arezu (LOR 204)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: "Colress's Experiment",
    tcgApiId: 'swsh11-205',
    number: '205',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/205.png","large":"https://images.pokemontcg.io/swsh11/205_hires.png"}',
    searchName: "Colress's Experiment (LOR 205)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Fantina',
    tcgApiId: 'swsh11-206',
    number: '206',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/206.png","large":"https://images.pokemontcg.io/swsh11/206_hires.png"}',
    searchName: 'Fantina (LOR 206)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Iscan',
    tcgApiId: 'swsh11-207',
    number: '207',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/207.png","large":"https://images.pokemontcg.io/swsh11/207_hires.png"}',
    searchName: 'Iscan (LOR 207)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lady',
    tcgApiId: 'swsh11-208',
    number: '208',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/208.png","large":"https://images.pokemontcg.io/swsh11/208_hires.png"}',
    searchName: 'Lady (LOR 208)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Miss Fortune Sisters',
    tcgApiId: 'swsh11-209',
    number: '209',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/209.png","large":"https://images.pokemontcg.io/swsh11/209_hires.png"}',
    searchName: 'Miss Fortune Sisters (LOR 209)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Thorton',
    tcgApiId: 'swsh11-210',
    number: '210',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/210.png","large":"https://images.pokemontcg.io/swsh11/210_hires.png"}',
    searchName: 'Thorton (LOR 210)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Volo',
    tcgApiId: 'swsh11-211',
    number: '211',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/211.png","large":"https://images.pokemontcg.io/swsh11/211_hires.png"}',
    searchName: 'Volo (LOR 211)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Giratina VSTAR',
    tcgApiId: 'swsh11-212',
    number: '212',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/212.png","large":"https://images.pokemontcg.io/swsh11/212_hires.png"}',
    searchName: 'Giratina VSTAR (LOR 212)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Hisuian Zoroark VSTAR',
    tcgApiId: 'swsh11-213',
    number: '213',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/213.png","large":"https://images.pokemontcg.io/swsh11/213_hires.png"}',
    searchName: 'Hisuian Zoroark VSTAR (LOR 213)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Box of Disaster',
    tcgApiId: 'swsh11-214',
    number: '214',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/214.png","large":"https://images.pokemontcg.io/swsh11/214_hires.png"}',
    searchName: 'Box of Disaster (LOR 214)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Collapsed Stadium',
    tcgApiId: 'swsh11-215',
    number: '215',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/215.png","large":"https://images.pokemontcg.io/swsh11/215_hires.png"}',
    searchName: 'Collapsed Stadium (LOR 215)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Dark Patch',
    tcgApiId: 'swsh11-216',
    number: '216',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/216.png","large":"https://images.pokemontcg.io/swsh11/216_hires.png"}',
    searchName: 'Dark Patch (LOR 216)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11',
    name: 'Lost Vacuum',
    tcgApiId: 'swsh11-217',
    number: '217',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11/217.png","large":"https://images.pokemontcg.io/swsh11/217_hires.png"}',
    searchName: 'Lost Vacuum (LOR 217)',
  },
];
