export const cardSeedSwsh35 = [
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Venusaur V',
    tcgApiId: 'swsh35-1',
    number: '1',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/1.png","large":"https://images.pokemontcg.io/swsh35/1_hires.png"}',
    searchName: 'Venusaur V (CPA 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Weedle',
    tcgApiId: 'swsh35-2',
    number: '2',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/2.png","large":"https://images.pokemontcg.io/swsh35/2_hires.png"}',
    searchName: 'Weedle (CPA 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Kakuna',
    tcgApiId: 'swsh35-3',
    number: '3',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/3.png","large":"https://images.pokemontcg.io/swsh35/3_hires.png"}',
    searchName: 'Kakuna (CPA 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Beedrill',
    tcgApiId: 'swsh35-4',
    number: '4',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/4.png","large":"https://images.pokemontcg.io/swsh35/4_hires.png"}',
    searchName: 'Beedrill (CPA 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Eldegoss V',
    tcgApiId: 'swsh35-5',
    number: '5',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/5.png","large":"https://images.pokemontcg.io/swsh35/5_hires.png"}',
    searchName: 'Eldegoss V (CPA 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Vulpix',
    tcgApiId: 'swsh35-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/6.png","large":"https://images.pokemontcg.io/swsh35/6_hires.png"}',
    searchName: 'Vulpix (CPA 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Victini',
    tcgApiId: 'swsh35-7',
    number: '7',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/7.png","large":"https://images.pokemontcg.io/swsh35/7_hires.png"}',
    searchName: 'Victini (CPA 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Incineroar V',
    tcgApiId: 'swsh35-8',
    number: '8',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/8.png","large":"https://images.pokemontcg.io/swsh35/8_hires.png"}',
    searchName: 'Incineroar V (CPA 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Sizzlipede',
    tcgApiId: 'swsh35-9',
    number: '9',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/9.png","large":"https://images.pokemontcg.io/swsh35/9_hires.png"}',
    searchName: 'Sizzlipede (CPA 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Centiskorch',
    tcgApiId: 'swsh35-10',
    number: '10',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/10.png","large":"https://images.pokemontcg.io/swsh35/10_hires.png"}',
    searchName: 'Centiskorch (CPA 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Carvanha',
    tcgApiId: 'swsh35-11',
    number: '11',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/11.png","large":"https://images.pokemontcg.io/swsh35/11_hires.png"}',
    searchName: 'Carvanha (CPA 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Sharpedo',
    tcgApiId: 'swsh35-12',
    number: '12',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/12.png","large":"https://images.pokemontcg.io/swsh35/12_hires.png"}',
    searchName: 'Sharpedo (CPA 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Wailord V',
    tcgApiId: 'swsh35-13',
    number: '13',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/13.png","large":"https://images.pokemontcg.io/swsh35/13_hires.png"}',
    searchName: 'Wailord V (CPA 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Drednaw V',
    tcgApiId: 'swsh35-14',
    number: '14',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/14.png","large":"https://images.pokemontcg.io/swsh35/14_hires.png"}',
    searchName: 'Drednaw V (CPA 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Drednaw VMAX',
    tcgApiId: 'swsh35-15',
    number: '15',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/15.png","large":"https://images.pokemontcg.io/swsh35/15_hires.png"}',
    searchName: 'Drednaw VMAX (CPA 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Gardevoir V',
    tcgApiId: 'swsh35-16',
    number: '16',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/16.png","large":"https://images.pokemontcg.io/swsh35/16_hires.png"}',
    searchName: 'Gardevoir V (CPA 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Gardevoir VMAX',
    tcgApiId: 'swsh35-17',
    number: '17',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/17.png","large":"https://images.pokemontcg.io/swsh35/17_hires.png"}',
    searchName: 'Gardevoir VMAX (CPA 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Hatenna',
    tcgApiId: 'swsh35-18',
    number: '18',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/18.png","large":"https://images.pokemontcg.io/swsh35/18_hires.png"}',
    searchName: 'Hatenna (CPA 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Hattrem',
    tcgApiId: 'swsh35-19',
    number: '19',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/19.png","large":"https://images.pokemontcg.io/swsh35/19_hires.png"}',
    searchName: 'Hattrem (CPA 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Hatterene',
    tcgApiId: 'swsh35-20',
    number: '20',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/20.png","large":"https://images.pokemontcg.io/swsh35/20_hires.png"}',
    searchName: 'Hatterene (CPA 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Galarian Cursola V',
    tcgApiId: 'swsh35-21',
    number: '21',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/21.png","large":"https://images.pokemontcg.io/swsh35/21_hires.png"}',
    searchName: 'Galarian Cursola V (CPA 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Alcremie V',
    tcgApiId: 'swsh35-22',
    number: '22',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/22.png","large":"https://images.pokemontcg.io/swsh35/22_hires.png"}',
    searchName: 'Alcremie V (CPA 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Alcremie VMAX',
    tcgApiId: 'swsh35-23',
    number: '23',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/23.png","large":"https://images.pokemontcg.io/swsh35/23_hires.png"}',
    searchName: 'Alcremie VMAX (CPA 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Machop',
    tcgApiId: 'swsh35-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/24.png","large":"https://images.pokemontcg.io/swsh35/24_hires.png"}',
    searchName: 'Machop (CPA 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Machoke',
    tcgApiId: 'swsh35-25',
    number: '25',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/25.png","large":"https://images.pokemontcg.io/swsh35/25_hires.png"}',
    searchName: 'Machoke (CPA 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Machamp',
    tcgApiId: 'swsh35-26',
    number: '26',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/26.png","large":"https://images.pokemontcg.io/swsh35/26_hires.png"}',
    searchName: 'Machamp (CPA 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Lucario V',
    tcgApiId: 'swsh35-27',
    number: '27',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/27.png","large":"https://images.pokemontcg.io/swsh35/27_hires.png"}',
    searchName: 'Lucario V (CPA 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Zygarde',
    tcgApiId: 'swsh35-28',
    number: '28',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/28.png","large":"https://images.pokemontcg.io/swsh35/28_hires.png"}',
    searchName: 'Zygarde (CPA 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Rockruff',
    tcgApiId: 'swsh35-29',
    number: '29',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/29.png","large":"https://images.pokemontcg.io/swsh35/29_hires.png"}',
    searchName: 'Rockruff (CPA 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Lycanroc',
    tcgApiId: 'swsh35-30',
    number: '30',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/30.png","large":"https://images.pokemontcg.io/swsh35/30_hires.png"}',
    searchName: 'Lycanroc (CPA 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Rolycoly',
    tcgApiId: 'swsh35-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/31.png","large":"https://images.pokemontcg.io/swsh35/31_hires.png"}',
    searchName: 'Rolycoly (CPA 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Grapploct V',
    tcgApiId: 'swsh35-32',
    number: '32',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/32.png","large":"https://images.pokemontcg.io/swsh35/32_hires.png"}',
    searchName: 'Grapploct V (CPA 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Ekans',
    tcgApiId: 'swsh35-33',
    number: '33',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/33.png","large":"https://images.pokemontcg.io/swsh35/33_hires.png"}',
    searchName: 'Ekans (CPA 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Arbok',
    tcgApiId: 'swsh35-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/34.png","large":"https://images.pokemontcg.io/swsh35/34_hires.png"}',
    searchName: 'Arbok (CPA 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Galarian Zigzagoon',
    tcgApiId: 'swsh35-35',
    number: '35',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/35.png","large":"https://images.pokemontcg.io/swsh35/35_hires.png"}',
    searchName: 'Galarian Zigzagoon (CPA 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Galarian Linoone',
    tcgApiId: 'swsh35-36',
    number: '36',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/36.png","large":"https://images.pokemontcg.io/swsh35/36_hires.png"}',
    searchName: 'Galarian Linoone (CPA 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Galarian Obstagoon',
    tcgApiId: 'swsh35-37',
    number: '37',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/37.png","large":"https://images.pokemontcg.io/swsh35/37_hires.png"}',
    searchName: 'Galarian Obstagoon (CPA 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Absol',
    tcgApiId: 'swsh35-38',
    number: '38',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/38.png","large":"https://images.pokemontcg.io/swsh35/38_hires.png"}',
    searchName: 'Absol (CPA 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Purrloin',
    tcgApiId: 'swsh35-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/39.png","large":"https://images.pokemontcg.io/swsh35/39_hires.png"}',
    searchName: 'Purrloin (CPA 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Liepard',
    tcgApiId: 'swsh35-40',
    number: '40',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/40.png","large":"https://images.pokemontcg.io/swsh35/40_hires.png"}',
    searchName: 'Liepard (CPA 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Scraggy',
    tcgApiId: 'swsh35-41',
    number: '41',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/41.png","large":"https://images.pokemontcg.io/swsh35/41_hires.png"}',
    searchName: 'Scraggy (CPA 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Scrafty',
    tcgApiId: 'swsh35-42',
    number: '42',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/42.png","large":"https://images.pokemontcg.io/swsh35/42_hires.png"}',
    searchName: 'Scrafty (CPA 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Trubbish',
    tcgApiId: 'swsh35-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/43.png","large":"https://images.pokemontcg.io/swsh35/43_hires.png"}',
    searchName: 'Trubbish (CPA 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Inkay',
    tcgApiId: 'swsh35-44',
    number: '44',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/44.png","large":"https://images.pokemontcg.io/swsh35/44_hires.png"}',
    searchName: 'Inkay (CPA 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Malamar',
    tcgApiId: 'swsh35-45',
    number: '45',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/45.png","large":"https://images.pokemontcg.io/swsh35/45_hires.png"}',
    searchName: 'Malamar (CPA 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Nickit',
    tcgApiId: 'swsh35-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/46.png","large":"https://images.pokemontcg.io/swsh35/46_hires.png"}',
    searchName: 'Nickit (CPA 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Duraludon V',
    tcgApiId: 'swsh35-47',
    number: '47',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/47.png","large":"https://images.pokemontcg.io/swsh35/47_hires.png"}',
    searchName: 'Duraludon V (CPA 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Swablu',
    tcgApiId: 'swsh35-48',
    number: '48',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/48.png","large":"https://images.pokemontcg.io/swsh35/48_hires.png"}',
    searchName: 'Swablu (CPA 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Altaria',
    tcgApiId: 'swsh35-49',
    number: '49',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/49.png","large":"https://images.pokemontcg.io/swsh35/49_hires.png"}',
    searchName: 'Altaria (CPA 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Bede',
    tcgApiId: 'swsh35-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/50.png","large":"https://images.pokemontcg.io/swsh35/50_hires.png"}',
    searchName: 'Bede (CPA 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Full Heal',
    tcgApiId: 'swsh35-51',
    number: '51',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/51.png","large":"https://images.pokemontcg.io/swsh35/51_hires.png"}',
    searchName: 'Full Heal (CPA 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Great Ball',
    tcgApiId: 'swsh35-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/52.png","large":"https://images.pokemontcg.io/swsh35/52_hires.png"}',
    searchName: 'Great Ball (CPA 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Hop',
    tcgApiId: 'swsh35-53',
    number: '53',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/53.png","large":"https://images.pokemontcg.io/swsh35/53_hires.png"}',
    searchName: 'Hop (CPA 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Hyper Potion',
    tcgApiId: 'swsh35-54',
    number: '54',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/54.png","large":"https://images.pokemontcg.io/swsh35/54_hires.png"}',
    searchName: 'Hyper Potion (CPA 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Kabu',
    tcgApiId: 'swsh35-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/55.png","large":"https://images.pokemontcg.io/swsh35/55_hires.png"}',
    searchName: 'Kabu (CPA 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Marnie',
    tcgApiId: 'swsh35-56',
    number: '56',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/56.png","large":"https://images.pokemontcg.io/swsh35/56_hires.png"}',
    searchName: 'Marnie (CPA 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Milo',
    tcgApiId: 'swsh35-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/57.png","large":"https://images.pokemontcg.io/swsh35/57_hires.png"}',
    searchName: 'Milo (CPA 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Piers',
    tcgApiId: 'swsh35-58',
    number: '58',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/58.png","large":"https://images.pokemontcg.io/swsh35/58_hires.png"}',
    searchName: 'Piers (CPA 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Poké Ball',
    tcgApiId: 'swsh35-59',
    number: '59',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/59.png","large":"https://images.pokemontcg.io/swsh35/59_hires.png"}',
    searchName: 'Poké Ball (CPA 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Pokémon Center Lady',
    tcgApiId: 'swsh35-60',
    number: '60',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/60.png","large":"https://images.pokemontcg.io/swsh35/60_hires.png"}',
    searchName: 'Pokémon Center Lady (CPA 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Potion',
    tcgApiId: 'swsh35-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/61.png","large":"https://images.pokemontcg.io/swsh35/61_hires.png"}',
    searchName: 'Potion (CPA 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: "Professor's Research (Professor Magnolia)",
    tcgApiId: 'swsh35-62',
    number: '62',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/62.png","large":"https://images.pokemontcg.io/swsh35/62_hires.png"}',
    searchName: "Professor's Research (Professor Magnolia) (CPA 62)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Rotom Bike',
    tcgApiId: 'swsh35-63',
    number: '63',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/63.png","large":"https://images.pokemontcg.io/swsh35/63_hires.png"}',
    searchName: 'Rotom Bike (CPA 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Rotom Phone',
    tcgApiId: 'swsh35-64',
    number: '64',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/64.png","large":"https://images.pokemontcg.io/swsh35/64_hires.png"}',
    searchName: 'Rotom Phone (CPA 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Sonia',
    tcgApiId: 'swsh35-65',
    number: '65',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/65.png","large":"https://images.pokemontcg.io/swsh35/65_hires.png"}',
    searchName: 'Sonia (CPA 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Suspicious Food Tin',
    tcgApiId: 'swsh35-66',
    number: '66',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/66.png","large":"https://images.pokemontcg.io/swsh35/66_hires.png"}',
    searchName: 'Suspicious Food Tin (CPA 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Team Yell Grunt',
    tcgApiId: 'swsh35-67',
    number: '67',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/67.png","large":"https://images.pokemontcg.io/swsh35/67_hires.png"}',
    searchName: 'Team Yell Grunt (CPA 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Turffield Stadium',
    tcgApiId: 'swsh35-68',
    number: '68',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/68.png","large":"https://images.pokemontcg.io/swsh35/68_hires.png"}',
    searchName: 'Turffield Stadium (CPA 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Drednaw V',
    tcgApiId: 'swsh35-69',
    number: '69',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/69.png","large":"https://images.pokemontcg.io/swsh35/69_hires.png"}',
    searchName: 'Drednaw V (CPA 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Gardevoir V',
    tcgApiId: 'swsh35-70',
    number: '70',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/70.png","large":"https://images.pokemontcg.io/swsh35/70_hires.png"}',
    searchName: 'Gardevoir V (CPA 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Galarian Cursola V',
    tcgApiId: 'swsh35-71',
    number: '71',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/71.png","large":"https://images.pokemontcg.io/swsh35/71_hires.png"}',
    searchName: 'Galarian Cursola V (CPA 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Grapploct V',
    tcgApiId: 'swsh35-72',
    number: '72',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/72.png","large":"https://images.pokemontcg.io/swsh35/72_hires.png"}',
    searchName: 'Grapploct V (CPA 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Hop',
    tcgApiId: 'swsh35-73',
    number: '73',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/73.png","large":"https://images.pokemontcg.io/swsh35/73_hires.png"}',
    searchName: 'Hop (CPA 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Charizard VMAX',
    tcgApiId: 'swsh35-74',
    number: '74',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/74.png","large":"https://images.pokemontcg.io/swsh35/74_hires.png"}',
    searchName: 'Charizard VMAX (CPA 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Drednaw VMAX',
    tcgApiId: 'swsh35-75',
    number: '75',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/75.png","large":"https://images.pokemontcg.io/swsh35/75_hires.png"}',
    searchName: 'Drednaw VMAX (CPA 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Gardevoir VMAX',
    tcgApiId: 'swsh35-76',
    number: '76',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/76.png","large":"https://images.pokemontcg.io/swsh35/76_hires.png"}',
    searchName: 'Gardevoir VMAX (CPA 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Kabu',
    tcgApiId: 'swsh35-77',
    number: '77',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/77.png","large":"https://images.pokemontcg.io/swsh35/77_hires.png"}',
    searchName: 'Kabu (CPA 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Piers',
    tcgApiId: 'swsh35-78',
    number: '78',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/78.png","large":"https://images.pokemontcg.io/swsh35/78_hires.png"}',
    searchName: 'Piers (CPA 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Charizard V',
    tcgApiId: 'swsh35-79',
    number: '79',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/79.png","large":"https://images.pokemontcg.io/swsh35/79_hires.png"}',
    searchName: 'Charizard V (CPA 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh35',
    name: 'Suspicious Food Tin',
    tcgApiId: 'swsh35-80',
    number: '80',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh35/80.png","large":"https://images.pokemontcg.io/swsh35/80_hires.png"}',
    searchName: 'Suspicious Food Tin (CPA 80)',
  },
];
