export const cardSeedSwsh11tg = [
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Parasect',
    tcgApiId: 'swsh11tg-TG01',
    number: 'TG01',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG01.png","large":"https://images.pokemontcg.io/swsh11tg/TG01_hires.png"}',
    searchName: 'Parasect (LOR TG01)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Roserade',
    tcgApiId: 'swsh11tg-TG02',
    number: 'TG02',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG02.png","large":"https://images.pokemontcg.io/swsh11tg/TG02_hires.png"}',
    searchName: 'Roserade (LOR TG02)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Charizard',
    tcgApiId: 'swsh11tg-TG03',
    number: 'TG03',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG03.png","large":"https://images.pokemontcg.io/swsh11tg/TG03_hires.png"}',
    searchName: 'Charizard (LOR TG03)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Chandelure',
    tcgApiId: 'swsh11tg-TG04',
    number: 'TG04',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG04.png","large":"https://images.pokemontcg.io/swsh11tg/TG04_hires.png"}',
    searchName: 'Chandelure (LOR TG04)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Pikachu',
    tcgApiId: 'swsh11tg-TG05',
    number: 'TG05',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG05.png","large":"https://images.pokemontcg.io/swsh11tg/TG05_hires.png"}',
    searchName: 'Pikachu (LOR TG05)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Gengar',
    tcgApiId: 'swsh11tg-TG06',
    number: 'TG06',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG06.png","large":"https://images.pokemontcg.io/swsh11tg/TG06_hires.png"}',
    searchName: 'Gengar (LOR TG06)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Banette',
    tcgApiId: 'swsh11tg-TG07',
    number: 'TG07',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG07.png","large":"https://images.pokemontcg.io/swsh11tg/TG07_hires.png"}',
    searchName: 'Banette (LOR TG07)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Hisuian Arcanine',
    tcgApiId: 'swsh11tg-TG08',
    number: 'TG08',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG08.png","large":"https://images.pokemontcg.io/swsh11tg/TG08_hires.png"}',
    searchName: 'Hisuian Arcanine (LOR TG08)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Spiritomb',
    tcgApiId: 'swsh11tg-TG09',
    number: 'TG09',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG09.png","large":"https://images.pokemontcg.io/swsh11tg/TG09_hires.png"}',
    searchName: 'Spiritomb (LOR TG09)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Snorlax',
    tcgApiId: 'swsh11tg-TG10',
    number: 'TG10',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG10.png","large":"https://images.pokemontcg.io/swsh11tg/TG10_hires.png"}',
    searchName: 'Snorlax (LOR TG10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Castform',
    tcgApiId: 'swsh11tg-TG11',
    number: 'TG11',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG11.png","large":"https://images.pokemontcg.io/swsh11tg/TG11_hires.png"}',
    searchName: 'Castform (LOR TG11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Orbeetle V',
    tcgApiId: 'swsh11tg-TG12',
    number: 'TG12',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG12.png","large":"https://images.pokemontcg.io/swsh11tg/TG12_hires.png"}',
    searchName: 'Orbeetle V (LOR TG12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Orbeetle VMAX',
    tcgApiId: 'swsh11tg-TG13',
    number: 'TG13',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG13.png","large":"https://images.pokemontcg.io/swsh11tg/TG13_hires.png"}',
    searchName: 'Orbeetle VMAX (LOR TG13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Centiskorch V',
    tcgApiId: 'swsh11tg-TG14',
    number: 'TG14',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG14.png","large":"https://images.pokemontcg.io/swsh11tg/TG14_hires.png"}',
    searchName: 'Centiskorch V (LOR TG14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Centiskorch VMAX',
    tcgApiId: 'swsh11tg-TG15',
    number: 'TG15',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG15.png","large":"https://images.pokemontcg.io/swsh11tg/TG15_hires.png"}',
    searchName: 'Centiskorch VMAX (LOR TG15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Pikachu V',
    tcgApiId: 'swsh11tg-TG16',
    number: 'TG16',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG16.png","large":"https://images.pokemontcg.io/swsh11tg/TG16_hires.png"}',
    searchName: 'Pikachu V (LOR TG16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Pikachu VMAX',
    tcgApiId: 'swsh11tg-TG17',
    number: 'TG17',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG17.png","large":"https://images.pokemontcg.io/swsh11tg/TG17_hires.png"}',
    searchName: 'Pikachu VMAX (LOR TG17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Enamorus V',
    tcgApiId: 'swsh11tg-TG18',
    number: 'TG18',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG18.png","large":"https://images.pokemontcg.io/swsh11tg/TG18_hires.png"}',
    searchName: 'Enamorus V (LOR TG18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Gallade V',
    tcgApiId: 'swsh11tg-TG19',
    number: 'TG19',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG19.png","large":"https://images.pokemontcg.io/swsh11tg/TG19_hires.png"}',
    searchName: 'Gallade V (LOR TG19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Crobat V',
    tcgApiId: 'swsh11tg-TG20',
    number: 'TG20',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG20.png","large":"https://images.pokemontcg.io/swsh11tg/TG20_hires.png"}',
    searchName: 'Crobat V (LOR TG20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Eternatus V',
    tcgApiId: 'swsh11tg-TG21',
    number: 'TG21',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG21.png","large":"https://images.pokemontcg.io/swsh11tg/TG21_hires.png"}',
    searchName: 'Eternatus V (LOR TG21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Eternatus VMAX',
    tcgApiId: 'swsh11tg-TG22',
    number: 'TG22',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG22.png","large":"https://images.pokemontcg.io/swsh11tg/TG22_hires.png"}',
    searchName: 'Eternatus VMAX (LOR TG22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: "Adventurer's Discovery",
    tcgApiId: 'swsh11tg-TG23',
    number: 'TG23',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG23.png","large":"https://images.pokemontcg.io/swsh11tg/TG23_hires.png"}',
    searchName: "Adventurer's Discovery (LOR TG23)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: "Boss's Orders",
    tcgApiId: 'swsh11tg-TG24',
    number: 'TG24',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG24.png","large":"https://images.pokemontcg.io/swsh11tg/TG24_hires.png"}',
    searchName: "Boss's Orders (LOR TG24)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Cook',
    tcgApiId: 'swsh11tg-TG25',
    number: 'TG25',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG25.png","large":"https://images.pokemontcg.io/swsh11tg/TG25_hires.png"}',
    searchName: 'Cook (LOR TG25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Kabu',
    tcgApiId: 'swsh11tg-TG26',
    number: 'TG26',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG26.png","large":"https://images.pokemontcg.io/swsh11tg/TG26_hires.png"}',
    searchName: 'Kabu (LOR TG26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Nessa',
    tcgApiId: 'swsh11tg-TG27',
    number: 'TG27',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG27.png","large":"https://images.pokemontcg.io/swsh11tg/TG27_hires.png"}',
    searchName: 'Nessa (LOR TG27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Opal',
    tcgApiId: 'swsh11tg-TG28',
    number: 'TG28',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG28.png","large":"https://images.pokemontcg.io/swsh11tg/TG28_hires.png"}',
    searchName: 'Opal (LOR TG28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Pikachu VMAX',
    tcgApiId: 'swsh11tg-TG29',
    number: 'TG29',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG29.png","large":"https://images.pokemontcg.io/swsh11tg/TG29_hires.png"}',
    searchName: 'Pikachu VMAX (LOR TG29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh11tg',
    name: 'Mew VMAX',
    tcgApiId: 'swsh11tg-TG30',
    number: 'TG30',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh11tg/TG30.png","large":"https://images.pokemontcg.io/swsh11tg/TG30_hires.png"}',
    searchName: 'Mew VMAX (LOR TG30)',
  },
];
