export const cardSeedSwsh12tg = [
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Braixen',
    tcgApiId: 'swsh12tg-TG01',
    number: 'TG01',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG01.png","large":"https://images.pokemontcg.io/swsh12tg/TG01_hires.png"}',
    searchName: 'Braixen (SIT TG01)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Milotic',
    tcgApiId: 'swsh12tg-TG02',
    number: 'TG02',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG02.png","large":"https://images.pokemontcg.io/swsh12tg/TG02_hires.png"}',
    searchName: 'Milotic (SIT TG02)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Flaaffy',
    tcgApiId: 'swsh12tg-TG03',
    number: 'TG03',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG03.png","large":"https://images.pokemontcg.io/swsh12tg/TG03_hires.png"}',
    searchName: 'Flaaffy (SIT TG03)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Jynx',
    tcgApiId: 'swsh12tg-TG04',
    number: 'TG04',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG04.png","large":"https://images.pokemontcg.io/swsh12tg/TG04_hires.png"}',
    searchName: 'Jynx (SIT TG04)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Gardevoir',
    tcgApiId: 'swsh12tg-TG05',
    number: 'TG05',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG05.png","large":"https://images.pokemontcg.io/swsh12tg/TG05_hires.png"}',
    searchName: 'Gardevoir (SIT TG05)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Malamar',
    tcgApiId: 'swsh12tg-TG06',
    number: 'TG06',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG06.png","large":"https://images.pokemontcg.io/swsh12tg/TG06_hires.png"}',
    searchName: 'Malamar (SIT TG06)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Rockruff',
    tcgApiId: 'swsh12tg-TG07',
    number: 'TG07',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG07.png","large":"https://images.pokemontcg.io/swsh12tg/TG07_hires.png"}',
    searchName: 'Rockruff (SIT TG07)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Passimian',
    tcgApiId: 'swsh12tg-TG08',
    number: 'TG08',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG08.png","large":"https://images.pokemontcg.io/swsh12tg/TG08_hires.png"}',
    searchName: 'Passimian (SIT TG08)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Druddigon',
    tcgApiId: 'swsh12tg-TG09',
    number: 'TG09',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG09.png","large":"https://images.pokemontcg.io/swsh12tg/TG09_hires.png"}',
    searchName: 'Druddigon (SIT TG09)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Smeargle',
    tcgApiId: 'swsh12tg-TG10',
    number: 'TG10',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG10.png","large":"https://images.pokemontcg.io/swsh12tg/TG10_hires.png"}',
    searchName: 'Smeargle (SIT TG10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Altaria',
    tcgApiId: 'swsh12tg-TG11',
    number: 'TG11',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG11.png","large":"https://images.pokemontcg.io/swsh12tg/TG11_hires.png"}',
    searchName: 'Altaria (SIT TG11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Kricketune V',
    tcgApiId: 'swsh12tg-TG12',
    number: 'TG12',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG12.png","large":"https://images.pokemontcg.io/swsh12tg/TG12_hires.png"}',
    searchName: 'Kricketune V (SIT TG12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Serperior V',
    tcgApiId: 'swsh12tg-TG13',
    number: 'TG13',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG13.png","large":"https://images.pokemontcg.io/swsh12tg/TG13_hires.png"}',
    searchName: 'Serperior V (SIT TG13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Blaziken V',
    tcgApiId: 'swsh12tg-TG14',
    number: 'TG14',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG14.png","large":"https://images.pokemontcg.io/swsh12tg/TG14_hires.png"}',
    searchName: 'Blaziken V (SIT TG14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Blaziken VMAX',
    tcgApiId: 'swsh12tg-TG15',
    number: 'TG15',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG15.png","large":"https://images.pokemontcg.io/swsh12tg/TG15_hires.png"}',
    searchName: 'Blaziken VMAX (SIT TG15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Zeraora V',
    tcgApiId: 'swsh12tg-TG16',
    number: 'TG16',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG16.png","large":"https://images.pokemontcg.io/swsh12tg/TG16_hires.png"}',
    searchName: 'Zeraora V (SIT TG16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Mawile V',
    tcgApiId: 'swsh12tg-TG17',
    number: 'TG17',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG17.png","large":"https://images.pokemontcg.io/swsh12tg/TG17_hires.png"}',
    searchName: 'Mawile V (SIT TG17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Corviknight V',
    tcgApiId: 'swsh12tg-TG18',
    number: 'TG18',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG18.png","large":"https://images.pokemontcg.io/swsh12tg/TG18_hires.png"}',
    searchName: 'Corviknight V (SIT TG18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Corviknight VMAX',
    tcgApiId: 'swsh12tg-TG19',
    number: 'TG19',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG19.png","large":"https://images.pokemontcg.io/swsh12tg/TG19_hires.png"}',
    searchName: 'Corviknight VMAX (SIT TG19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Rayquaza VMAX',
    tcgApiId: 'swsh12tg-TG20',
    number: 'TG20',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG20.png","large":"https://images.pokemontcg.io/swsh12tg/TG20_hires.png"}',
    searchName: 'Rayquaza VMAX (SIT TG20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Duraludon VMAX',
    tcgApiId: 'swsh12tg-TG21',
    number: 'TG21',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG21.png","large":"https://images.pokemontcg.io/swsh12tg/TG21_hires.png"}',
    searchName: 'Duraludon VMAX (SIT TG21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Blissey V',
    tcgApiId: 'swsh12tg-TG22',
    number: 'TG22',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG22.png","large":"https://images.pokemontcg.io/swsh12tg/TG22_hires.png"}',
    searchName: 'Blissey V (SIT TG22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Friends in Galar',
    tcgApiId: 'swsh12tg-TG23',
    number: 'TG23',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG23.png","large":"https://images.pokemontcg.io/swsh12tg/TG23_hires.png"}',
    searchName: 'Friends in Galar (SIT TG23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Gordie',
    tcgApiId: 'swsh12tg-TG24',
    number: 'TG24',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG24.png","large":"https://images.pokemontcg.io/swsh12tg/TG24_hires.png"}',
    searchName: 'Gordie (SIT TG24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Judge',
    tcgApiId: 'swsh12tg-TG25',
    number: 'TG25',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG25.png","large":"https://images.pokemontcg.io/swsh12tg/TG25_hires.png"}',
    searchName: 'Judge (SIT TG25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Professor Burnet',
    tcgApiId: 'swsh12tg-TG26',
    number: 'TG26',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG26.png","large":"https://images.pokemontcg.io/swsh12tg/TG26_hires.png"}',
    searchName: 'Professor Burnet (SIT TG26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Raihan',
    tcgApiId: 'swsh12tg-TG27',
    number: 'TG27',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG27.png","large":"https://images.pokemontcg.io/swsh12tg/TG27_hires.png"}',
    searchName: 'Raihan (SIT TG27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Sordward & Shielbert',
    tcgApiId: 'swsh12tg-TG28',
    number: 'TG28',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG28.png","large":"https://images.pokemontcg.io/swsh12tg/TG28_hires.png"}',
    searchName: 'Sordward & Shielbert (SIT TG28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Rayquaza VMAX',
    tcgApiId: 'swsh12tg-TG29',
    number: 'TG29',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG29.png","large":"https://images.pokemontcg.io/swsh12tg/TG29_hires.png"}',
    searchName: 'Rayquaza VMAX (SIT TG29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh12tg',
    name: 'Duraludon VMAX',
    tcgApiId: 'swsh12tg-TG30',
    number: 'TG30',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh12tg/TG30.png","large":"https://images.pokemontcg.io/swsh12tg/TG30_hires.png"}',
    searchName: 'Duraludon VMAX (SIT TG30)',
  },
];
