export const cardSeedSwsh9 = [
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Exeggcute',
    tcgApiId: 'swsh9-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/1.png","large":"https://images.pokemontcg.io/swsh9/1_hires.png"}',
    searchName: 'Exeggcute (BRS 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Exeggutor',
    tcgApiId: 'swsh9-2',
    number: '2',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/2.png","large":"https://images.pokemontcg.io/swsh9/2_hires.png"}',
    searchName: 'Exeggutor (BRS 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Shroomish',
    tcgApiId: 'swsh9-3',
    number: '3',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/3.png","large":"https://images.pokemontcg.io/swsh9/3_hires.png"}',
    searchName: 'Shroomish (BRS 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Breloom',
    tcgApiId: 'swsh9-4',
    number: '4',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/4.png","large":"https://images.pokemontcg.io/swsh9/4_hires.png"}',
    searchName: 'Breloom (BRS 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Tropius',
    tcgApiId: 'swsh9-5',
    number: '5',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/5.png","large":"https://images.pokemontcg.io/swsh9/5_hires.png"}',
    searchName: 'Tropius (BRS 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Turtwig',
    tcgApiId: 'swsh9-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/6.png","large":"https://images.pokemontcg.io/swsh9/6_hires.png"}',
    searchName: 'Turtwig (BRS 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Grotle',
    tcgApiId: 'swsh9-7',
    number: '7',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/7.png","large":"https://images.pokemontcg.io/swsh9/7_hires.png"}',
    searchName: 'Grotle (BRS 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Torterra',
    tcgApiId: 'swsh9-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/8.png","large":"https://images.pokemontcg.io/swsh9/8_hires.png"}',
    searchName: 'Torterra (BRS 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Burmy',
    tcgApiId: 'swsh9-9',
    number: '9',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/9.png","large":"https://images.pokemontcg.io/swsh9/9_hires.png"}',
    searchName: 'Burmy (BRS 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Wormadam',
    tcgApiId: 'swsh9-10',
    number: '10',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/10.png","large":"https://images.pokemontcg.io/swsh9/10_hires.png"}',
    searchName: 'Wormadam (BRS 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Mothim',
    tcgApiId: 'swsh9-11',
    number: '11',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/11.png","large":"https://images.pokemontcg.io/swsh9/11_hires.png"}',
    searchName: 'Mothim (BRS 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Cherubi',
    tcgApiId: 'swsh9-12',
    number: '12',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/12.png","large":"https://images.pokemontcg.io/swsh9/12_hires.png"}',
    searchName: 'Cherubi (BRS 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Shaymin V',
    tcgApiId: 'swsh9-13',
    number: '13',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/13.png","large":"https://images.pokemontcg.io/swsh9/13_hires.png"}',
    searchName: 'Shaymin V (BRS 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Shaymin VSTAR',
    tcgApiId: 'swsh9-14',
    number: '14',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/14.png","large":"https://images.pokemontcg.io/swsh9/14_hires.png"}',
    searchName: 'Shaymin VSTAR (BRS 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Karrablast',
    tcgApiId: 'swsh9-15',
    number: '15',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/15.png","large":"https://images.pokemontcg.io/swsh9/15_hires.png"}',
    searchName: 'Karrablast (BRS 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Zarude V',
    tcgApiId: 'swsh9-16',
    number: '16',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/16.png","large":"https://images.pokemontcg.io/swsh9/16_hires.png"}',
    searchName: 'Zarude V (BRS 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Charizard V',
    tcgApiId: 'swsh9-17',
    number: '17',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/17.png","large":"https://images.pokemontcg.io/swsh9/17_hires.png"}',
    searchName: 'Charizard V (BRS 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Charizard VSTAR',
    tcgApiId: 'swsh9-18',
    number: '18',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/18.png","large":"https://images.pokemontcg.io/swsh9/18_hires.png"}',
    searchName: 'Charizard VSTAR (BRS 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Magmar',
    tcgApiId: 'swsh9-19',
    number: '19',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/19.png","large":"https://images.pokemontcg.io/swsh9/19_hires.png"}',
    searchName: 'Magmar (BRS 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Magmortar',
    tcgApiId: 'swsh9-20',
    number: '20',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/20.png","large":"https://images.pokemontcg.io/swsh9/20_hires.png"}',
    searchName: 'Magmortar (BRS 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Moltres',
    tcgApiId: 'swsh9-21',
    number: '21',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/21.png","large":"https://images.pokemontcg.io/swsh9/21_hires.png"}',
    searchName: 'Moltres (BRS 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Entei V',
    tcgApiId: 'swsh9-22',
    number: '22',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/22.png","large":"https://images.pokemontcg.io/swsh9/22_hires.png"}',
    searchName: 'Entei V (BRS 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Torkoal',
    tcgApiId: 'swsh9-23',
    number: '23',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/23.png","large":"https://images.pokemontcg.io/swsh9/23_hires.png"}',
    searchName: 'Torkoal (BRS 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Chimchar',
    tcgApiId: 'swsh9-24',
    number: '24',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/24.png","large":"https://images.pokemontcg.io/swsh9/24_hires.png"}',
    searchName: 'Chimchar (BRS 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Monferno',
    tcgApiId: 'swsh9-25',
    number: '25',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/25.png","large":"https://images.pokemontcg.io/swsh9/25_hires.png"}',
    searchName: 'Monferno (BRS 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Infernape',
    tcgApiId: 'swsh9-26',
    number: '26',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/26.png","large":"https://images.pokemontcg.io/swsh9/26_hires.png"}',
    searchName: 'Infernape (BRS 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Simisear V',
    tcgApiId: 'swsh9-27',
    number: '27',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/27.png","large":"https://images.pokemontcg.io/swsh9/27_hires.png"}',
    searchName: 'Simisear V (BRS 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Kingler V',
    tcgApiId: 'swsh9-28',
    number: '28',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/28.png","large":"https://images.pokemontcg.io/swsh9/28_hires.png"}',
    searchName: 'Kingler V (BRS 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Kingler VMAX',
    tcgApiId: 'swsh9-29',
    number: '29',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/29.png","large":"https://images.pokemontcg.io/swsh9/29_hires.png"}',
    searchName: 'Kingler VMAX (BRS 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Staryu',
    tcgApiId: 'swsh9-30',
    number: '30',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/30.png","large":"https://images.pokemontcg.io/swsh9/30_hires.png"}',
    searchName: 'Staryu (BRS 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Lapras',
    tcgApiId: 'swsh9-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/31.png","large":"https://images.pokemontcg.io/swsh9/31_hires.png"}',
    searchName: 'Lapras (BRS 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Corphish',
    tcgApiId: 'swsh9-32',
    number: '32',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/32.png","large":"https://images.pokemontcg.io/swsh9/32_hires.png"}',
    searchName: 'Corphish (BRS 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Crawdaunt',
    tcgApiId: 'swsh9-33',
    number: '33',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/33.png","large":"https://images.pokemontcg.io/swsh9/33_hires.png"}',
    searchName: 'Crawdaunt (BRS 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Snorunt',
    tcgApiId: 'swsh9-34',
    number: '34',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/34.png","large":"https://images.pokemontcg.io/swsh9/34_hires.png"}',
    searchName: 'Snorunt (BRS 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Piplup',
    tcgApiId: 'swsh9-35',
    number: '35',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/35.png","large":"https://images.pokemontcg.io/swsh9/35_hires.png"}',
    searchName: 'Piplup (BRS 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Prinplup',
    tcgApiId: 'swsh9-36',
    number: '36',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/36.png","large":"https://images.pokemontcg.io/swsh9/36_hires.png"}',
    searchName: 'Prinplup (BRS 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Empoleon',
    tcgApiId: 'swsh9-37',
    number: '37',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/37.png","large":"https://images.pokemontcg.io/swsh9/37_hires.png"}',
    searchName: 'Empoleon (BRS 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Buizel',
    tcgApiId: 'swsh9-38',
    number: '38',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/38.png","large":"https://images.pokemontcg.io/swsh9/38_hires.png"}',
    searchName: 'Buizel (BRS 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Floatzel',
    tcgApiId: 'swsh9-39',
    number: '39',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/39.png","large":"https://images.pokemontcg.io/swsh9/39_hires.png"}',
    searchName: 'Floatzel (BRS 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Lumineon V',
    tcgApiId: 'swsh9-40',
    number: '40',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/40.png","large":"https://images.pokemontcg.io/swsh9/40_hires.png"}',
    searchName: 'Lumineon V (BRS 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Manaphy',
    tcgApiId: 'swsh9-41',
    number: '41',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/41.png","large":"https://images.pokemontcg.io/swsh9/41_hires.png"}',
    searchName: 'Manaphy (BRS 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Cubchoo',
    tcgApiId: 'swsh9-42',
    number: '42',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/42.png","large":"https://images.pokemontcg.io/swsh9/42_hires.png"}',
    searchName: 'Cubchoo (BRS 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Beartic',
    tcgApiId: 'swsh9-43',
    number: '43',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/43.png","large":"https://images.pokemontcg.io/swsh9/43_hires.png"}',
    searchName: 'Beartic (BRS 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Eiscue',
    tcgApiId: 'swsh9-44',
    number: '44',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/44.png","large":"https://images.pokemontcg.io/swsh9/44_hires.png"}',
    searchName: 'Eiscue (BRS 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Raichu V',
    tcgApiId: 'swsh9-45',
    number: '45',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/45.png","large":"https://images.pokemontcg.io/swsh9/45_hires.png"}',
    searchName: 'Raichu V (BRS 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Electabuzz',
    tcgApiId: 'swsh9-46',
    number: '46',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/46.png","large":"https://images.pokemontcg.io/swsh9/46_hires.png"}',
    searchName: 'Electabuzz (BRS 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Electivire',
    tcgApiId: 'swsh9-47',
    number: '47',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/47.png","large":"https://images.pokemontcg.io/swsh9/47_hires.png"}',
    searchName: 'Electivire (BRS 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Raikou V',
    tcgApiId: 'swsh9-48',
    number: '48',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/48.png","large":"https://images.pokemontcg.io/swsh9/48_hires.png"}',
    searchName: 'Raikou V (BRS 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Shinx',
    tcgApiId: 'swsh9-49',
    number: '49',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/49.png","large":"https://images.pokemontcg.io/swsh9/49_hires.png"}',
    searchName: 'Shinx (BRS 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Luxio',
    tcgApiId: 'swsh9-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/50.png","large":"https://images.pokemontcg.io/swsh9/50_hires.png"}',
    searchName: 'Luxio (BRS 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Luxray',
    tcgApiId: 'swsh9-51',
    number: '51',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/51.png","large":"https://images.pokemontcg.io/swsh9/51_hires.png"}',
    searchName: 'Luxray (BRS 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Pachirisu',
    tcgApiId: 'swsh9-52',
    number: '52',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/52.png","large":"https://images.pokemontcg.io/swsh9/52_hires.png"}',
    searchName: 'Pachirisu (BRS 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Clefairy',
    tcgApiId: 'swsh9-53',
    number: '53',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/53.png","large":"https://images.pokemontcg.io/swsh9/53_hires.png"}',
    searchName: 'Clefairy (BRS 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Clefable',
    tcgApiId: 'swsh9-54',
    number: '54',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/54.png","large":"https://images.pokemontcg.io/swsh9/54_hires.png"}',
    searchName: 'Clefable (BRS 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Starmie',
    tcgApiId: 'swsh9-55',
    number: '55',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/55.png","large":"https://images.pokemontcg.io/swsh9/55_hires.png"}',
    searchName: 'Starmie (BRS 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Mewtwo',
    tcgApiId: 'swsh9-56',
    number: '56',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/56.png","large":"https://images.pokemontcg.io/swsh9/56_hires.png"}',
    searchName: 'Mewtwo (BRS 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Granbull V',
    tcgApiId: 'swsh9-57',
    number: '57',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/57.png","large":"https://images.pokemontcg.io/swsh9/57_hires.png"}',
    searchName: 'Granbull V (BRS 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Baltoy',
    tcgApiId: 'swsh9-58',
    number: '58',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/58.png","large":"https://images.pokemontcg.io/swsh9/58_hires.png"}',
    searchName: 'Baltoy (BRS 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Claydol',
    tcgApiId: 'swsh9-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/59.png","large":"https://images.pokemontcg.io/swsh9/59_hires.png"}',
    searchName: 'Claydol (BRS 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Duskull',
    tcgApiId: 'swsh9-60',
    number: '60',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/60.png","large":"https://images.pokemontcg.io/swsh9/60_hires.png"}',
    searchName: 'Duskull (BRS 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Dusclops',
    tcgApiId: 'swsh9-61',
    number: '61',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/61.png","large":"https://images.pokemontcg.io/swsh9/61_hires.png"}',
    searchName: 'Dusclops (BRS 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Dusknoir',
    tcgApiId: 'swsh9-62',
    number: '62',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/62.png","large":"https://images.pokemontcg.io/swsh9/62_hires.png"}',
    searchName: 'Dusknoir (BRS 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Chimecho',
    tcgApiId: 'swsh9-63',
    number: '63',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/63.png","large":"https://images.pokemontcg.io/swsh9/63_hires.png"}',
    searchName: 'Chimecho (BRS 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Whimsicott V',
    tcgApiId: 'swsh9-64',
    number: '64',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/64.png","large":"https://images.pokemontcg.io/swsh9/64_hires.png"}',
    searchName: 'Whimsicott V (BRS 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Whimsicott VSTAR',
    tcgApiId: 'swsh9-65',
    number: '65',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/65.png","large":"https://images.pokemontcg.io/swsh9/65_hires.png"}',
    searchName: 'Whimsicott VSTAR (BRS 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Sigilyph',
    tcgApiId: 'swsh9-66',
    number: '66',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/66.png","large":"https://images.pokemontcg.io/swsh9/66_hires.png"}',
    searchName: 'Sigilyph (BRS 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Dedenne',
    tcgApiId: 'swsh9-67',
    number: '67',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/67.png","large":"https://images.pokemontcg.io/swsh9/67_hires.png"}',
    searchName: 'Dedenne (BRS 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Mimikyu V',
    tcgApiId: 'swsh9-68',
    number: '68',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/68.png","large":"https://images.pokemontcg.io/swsh9/68_hires.png"}',
    searchName: 'Mimikyu V (BRS 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Mimikyu VMAX',
    tcgApiId: 'swsh9-69',
    number: '69',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/69.png","large":"https://images.pokemontcg.io/swsh9/69_hires.png"}',
    searchName: 'Mimikyu VMAX (BRS 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Milcery',
    tcgApiId: 'swsh9-70',
    number: '70',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/70.png","large":"https://images.pokemontcg.io/swsh9/70_hires.png"}',
    searchName: 'Milcery (BRS 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Alcremie',
    tcgApiId: 'swsh9-71',
    number: '71',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/71.png","large":"https://images.pokemontcg.io/swsh9/71_hires.png"}',
    searchName: 'Alcremie (BRS 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Hitmontop',
    tcgApiId: 'swsh9-72',
    number: '72',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/72.png","large":"https://images.pokemontcg.io/swsh9/72_hires.png"}',
    searchName: 'Hitmontop (BRS 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Nosepass',
    tcgApiId: 'swsh9-73',
    number: '73',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/73.png","large":"https://images.pokemontcg.io/swsh9/73_hires.png"}',
    searchName: 'Nosepass (BRS 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Trapinch',
    tcgApiId: 'swsh9-74',
    number: '74',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/74.png","large":"https://images.pokemontcg.io/swsh9/74_hires.png"}',
    searchName: 'Trapinch (BRS 74)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Vibrava',
    tcgApiId: 'swsh9-75',
    number: '75',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/75.png","large":"https://images.pokemontcg.io/swsh9/75_hires.png"}',
    searchName: 'Vibrava (BRS 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Flygon',
    tcgApiId: 'swsh9-76',
    number: '76',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/76.png","large":"https://images.pokemontcg.io/swsh9/76_hires.png"}',
    searchName: 'Flygon (BRS 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Wormadam',
    tcgApiId: 'swsh9-77',
    number: '77',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/77.png","large":"https://images.pokemontcg.io/swsh9/77_hires.png"}',
    searchName: 'Wormadam (BRS 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Riolu',
    tcgApiId: 'swsh9-78',
    number: '78',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/78.png","large":"https://images.pokemontcg.io/swsh9/78_hires.png"}',
    searchName: 'Riolu (BRS 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Lucario',
    tcgApiId: 'swsh9-79',
    number: '79',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/79.png","large":"https://images.pokemontcg.io/swsh9/79_hires.png"}',
    searchName: 'Lucario (BRS 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Throh',
    tcgApiId: 'swsh9-80',
    number: '80',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/80.png","large":"https://images.pokemontcg.io/swsh9/80_hires.png"}',
    searchName: 'Throh (BRS 80)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Sawk',
    tcgApiId: 'swsh9-81',
    number: '81',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/81.png","large":"https://images.pokemontcg.io/swsh9/81_hires.png"}',
    searchName: 'Sawk (BRS 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Golett',
    tcgApiId: 'swsh9-82',
    number: '82',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/82.png","large":"https://images.pokemontcg.io/swsh9/82_hires.png"}',
    searchName: 'Golett (BRS 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Golurk',
    tcgApiId: 'swsh9-83',
    number: '83',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/83.png","large":"https://images.pokemontcg.io/swsh9/83_hires.png"}',
    searchName: 'Golurk (BRS 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Grimer',
    tcgApiId: 'swsh9-84',
    number: '84',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/84.png","large":"https://images.pokemontcg.io/swsh9/84_hires.png"}',
    searchName: 'Grimer (BRS 84)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Muk',
    tcgApiId: 'swsh9-85',
    number: '85',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/85.png","large":"https://images.pokemontcg.io/swsh9/85_hires.png"}',
    searchName: 'Muk (BRS 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Sneasel',
    tcgApiId: 'swsh9-86',
    number: '86',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/86.png","large":"https://images.pokemontcg.io/swsh9/86_hires.png"}',
    searchName: 'Sneasel (BRS 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Weavile',
    tcgApiId: 'swsh9-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/87.png","large":"https://images.pokemontcg.io/swsh9/87_hires.png"}',
    searchName: 'Weavile (BRS 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Honchkrow V',
    tcgApiId: 'swsh9-88',
    number: '88',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/88.png","large":"https://images.pokemontcg.io/swsh9/88_hires.png"}',
    searchName: 'Honchkrow V (BRS 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Spiritomb',
    tcgApiId: 'swsh9-89',
    number: '89',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/89.png","large":"https://images.pokemontcg.io/swsh9/89_hires.png"}',
    searchName: 'Spiritomb (BRS 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Purrloin',
    tcgApiId: 'swsh9-90',
    number: '90',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/90.png","large":"https://images.pokemontcg.io/swsh9/90_hires.png"}',
    searchName: 'Purrloin (BRS 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Liepard',
    tcgApiId: 'swsh9-91',
    number: '91',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/91.png","large":"https://images.pokemontcg.io/swsh9/91_hires.png"}',
    searchName: 'Liepard (BRS 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Impidimp',
    tcgApiId: 'swsh9-92',
    number: '92',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/92.png","large":"https://images.pokemontcg.io/swsh9/92_hires.png"}',
    searchName: 'Impidimp (BRS 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Morgrem',
    tcgApiId: 'swsh9-93',
    number: '93',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/93.png","large":"https://images.pokemontcg.io/swsh9/93_hires.png"}',
    searchName: 'Morgrem (BRS 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Grimmsnarl',
    tcgApiId: 'swsh9-94',
    number: '94',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/94.png","large":"https://images.pokemontcg.io/swsh9/94_hires.png"}',
    searchName: 'Grimmsnarl (BRS 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Morpeko V',
    tcgApiId: 'swsh9-95',
    number: '95',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/95.png","large":"https://images.pokemontcg.io/swsh9/95_hires.png"}',
    searchName: 'Morpeko V (BRS 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Aggron V',
    tcgApiId: 'swsh9-96',
    number: '96',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/96.png","large":"https://images.pokemontcg.io/swsh9/96_hires.png"}',
    searchName: 'Aggron V (BRS 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Aggron VMAX',
    tcgApiId: 'swsh9-97',
    number: '97',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/97.png","large":"https://images.pokemontcg.io/swsh9/97_hires.png"}',
    searchName: 'Aggron VMAX (BRS 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Wormadam',
    tcgApiId: 'swsh9-98',
    number: '98',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/98.png","large":"https://images.pokemontcg.io/swsh9/98_hires.png"}',
    searchName: 'Wormadam (BRS 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Probopass',
    tcgApiId: 'swsh9-99',
    number: '99',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/99.png","large":"https://images.pokemontcg.io/swsh9/99_hires.png"}',
    searchName: 'Probopass (BRS 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Heatran',
    tcgApiId: 'swsh9-100',
    number: '100',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/100.png","large":"https://images.pokemontcg.io/swsh9/100_hires.png"}',
    searchName: 'Heatran (BRS 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Escavalier',
    tcgApiId: 'swsh9-101',
    number: '101',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/101.png","large":"https://images.pokemontcg.io/swsh9/101_hires.png"}',
    searchName: 'Escavalier (BRS 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Klink',
    tcgApiId: 'swsh9-102',
    number: '102',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/102.png","large":"https://images.pokemontcg.io/swsh9/102_hires.png"}',
    searchName: 'Klink (BRS 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Klang',
    tcgApiId: 'swsh9-103',
    number: '103',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/103.png","large":"https://images.pokemontcg.io/swsh9/103_hires.png"}',
    searchName: 'Klang (BRS 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Klinklang',
    tcgApiId: 'swsh9-104',
    number: '104',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/104.png","large":"https://images.pokemontcg.io/swsh9/104_hires.png"}',
    searchName: 'Klinklang (BRS 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Zamazenta V',
    tcgApiId: 'swsh9-105',
    number: '105',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/105.png","large":"https://images.pokemontcg.io/swsh9/105_hires.png"}',
    searchName: 'Zamazenta V (BRS 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Flygon V',
    tcgApiId: 'swsh9-106',
    number: '106',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/106.png","large":"https://images.pokemontcg.io/swsh9/106_hires.png"}',
    searchName: 'Flygon V (BRS 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Gible',
    tcgApiId: 'swsh9-107',
    number: '107',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/107.png","large":"https://images.pokemontcg.io/swsh9/107_hires.png"}',
    searchName: 'Gible (BRS 107)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Gabite',
    tcgApiId: 'swsh9-108',
    number: '108',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/108.png","large":"https://images.pokemontcg.io/swsh9/108_hires.png"}',
    searchName: 'Gabite (BRS 108)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Garchomp',
    tcgApiId: 'swsh9-109',
    number: '109',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/109.png","large":"https://images.pokemontcg.io/swsh9/109_hires.png"}',
    searchName: 'Garchomp (BRS 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Axew',
    tcgApiId: 'swsh9-110',
    number: '110',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/110.png","large":"https://images.pokemontcg.io/swsh9/110_hires.png"}',
    searchName: 'Axew (BRS 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Fraxure',
    tcgApiId: 'swsh9-111',
    number: '111',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/111.png","large":"https://images.pokemontcg.io/swsh9/111_hires.png"}',
    searchName: 'Fraxure (BRS 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Haxorus',
    tcgApiId: 'swsh9-112',
    number: '112',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/112.png","large":"https://images.pokemontcg.io/swsh9/112_hires.png"}',
    searchName: 'Haxorus (BRS 112)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Druddigon',
    tcgApiId: 'swsh9-113',
    number: '113',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/113.png","large":"https://images.pokemontcg.io/swsh9/113_hires.png"}',
    searchName: 'Druddigon (BRS 113)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Dracovish V',
    tcgApiId: 'swsh9-114',
    number: '114',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/114.png","large":"https://images.pokemontcg.io/swsh9/114_hires.png"}',
    searchName: 'Dracovish V (BRS 114)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Farfetch'd",
    tcgApiId: 'swsh9-115',
    number: '115',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/115.png","large":"https://images.pokemontcg.io/swsh9/115_hires.png"}',
    searchName: "Farfetch'd (BRS 115)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Castform',
    tcgApiId: 'swsh9-116',
    number: '116',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/116.png","large":"https://images.pokemontcg.io/swsh9/116_hires.png"}',
    searchName: 'Castform (BRS 116)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Starly',
    tcgApiId: 'swsh9-117',
    number: '117',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/117.png","large":"https://images.pokemontcg.io/swsh9/117_hires.png"}',
    searchName: 'Starly (BRS 117)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Staravia',
    tcgApiId: 'swsh9-118',
    number: '118',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/118.png","large":"https://images.pokemontcg.io/swsh9/118_hires.png"}',
    searchName: 'Staravia (BRS 118)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Staraptor',
    tcgApiId: 'swsh9-119',
    number: '119',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/119.png","large":"https://images.pokemontcg.io/swsh9/119_hires.png"}',
    searchName: 'Staraptor (BRS 119)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Bidoof',
    tcgApiId: 'swsh9-120',
    number: '120',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/120.png","large":"https://images.pokemontcg.io/swsh9/120_hires.png"}',
    searchName: 'Bidoof (BRS 120)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Bibarel',
    tcgApiId: 'swsh9-121',
    number: '121',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/121.png","large":"https://images.pokemontcg.io/swsh9/121_hires.png"}',
    searchName: 'Bibarel (BRS 121)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Arceus V',
    tcgApiId: 'swsh9-122',
    number: '122',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/122.png","large":"https://images.pokemontcg.io/swsh9/122_hires.png"}',
    searchName: 'Arceus V (BRS 122)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Arceus VSTAR',
    tcgApiId: 'swsh9-123',
    number: '123',
    rarity: 'Rare Holo VSTAR',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/123.png","large":"https://images.pokemontcg.io/swsh9/123_hires.png"}',
    searchName: 'Arceus VSTAR (BRS 123)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Minccino',
    tcgApiId: 'swsh9-124',
    number: '124',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/124.png","large":"https://images.pokemontcg.io/swsh9/124_hires.png"}',
    searchName: 'Minccino (BRS 124)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Cinccino',
    tcgApiId: 'swsh9-125',
    number: '125',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/125.png","large":"https://images.pokemontcg.io/swsh9/125_hires.png"}',
    searchName: 'Cinccino (BRS 125)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Tornadus',
    tcgApiId: 'swsh9-126',
    number: '126',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/126.png","large":"https://images.pokemontcg.io/swsh9/126_hires.png"}',
    searchName: 'Tornadus (BRS 126)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Hawlucha',
    tcgApiId: 'swsh9-127',
    number: '127',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/127.png","large":"https://images.pokemontcg.io/swsh9/127_hires.png"}',
    searchName: 'Hawlucha (BRS 127)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Drampa V',
    tcgApiId: 'swsh9-128',
    number: '128',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/128.png","large":"https://images.pokemontcg.io/swsh9/128_hires.png"}',
    searchName: 'Drampa V (BRS 128)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Acerola's Premonition",
    tcgApiId: 'swsh9-129',
    number: '129',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/129.png","large":"https://images.pokemontcg.io/swsh9/129_hires.png"}',
    searchName: "Acerola's Premonition (BRS 129)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Barry',
    tcgApiId: 'swsh9-130',
    number: '130',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/130.png","large":"https://images.pokemontcg.io/swsh9/130_hires.png"}',
    searchName: 'Barry (BRS 130)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Blunder Policy',
    tcgApiId: 'swsh9-131',
    number: '131',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/131.png","large":"https://images.pokemontcg.io/swsh9/131_hires.png"}',
    searchName: 'Blunder Policy (BRS 131)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Boss's Orders",
    tcgApiId: 'swsh9-132',
    number: '132',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/132.png","large":"https://images.pokemontcg.io/swsh9/132_hires.png"}',
    searchName: "Boss's Orders (BRS 132)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Café Master',
    tcgApiId: 'swsh9-133',
    number: '133',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/133.png","large":"https://images.pokemontcg.io/swsh9/133_hires.png"}',
    searchName: 'Café Master (BRS 133)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Cheren's Care",
    tcgApiId: 'swsh9-134',
    number: '134',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/134.png","large":"https://images.pokemontcg.io/swsh9/134_hires.png"}',
    searchName: "Cheren's Care (BRS 134)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Choice Belt',
    tcgApiId: 'swsh9-135',
    number: '135',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/135.png","large":"https://images.pokemontcg.io/swsh9/135_hires.png"}',
    searchName: 'Choice Belt (BRS 135)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Cleansing Gloves',
    tcgApiId: 'swsh9-136',
    number: '136',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/136.png","large":"https://images.pokemontcg.io/swsh9/136_hires.png"}',
    searchName: 'Cleansing Gloves (BRS 136)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Collapsed Stadium',
    tcgApiId: 'swsh9-137',
    number: '137',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/137.png","large":"https://images.pokemontcg.io/swsh9/137_hires.png"}',
    searchName: 'Collapsed Stadium (BRS 137)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Cynthia's Ambition",
    tcgApiId: 'swsh9-138',
    number: '138',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/138.png","large":"https://images.pokemontcg.io/swsh9/138_hires.png"}',
    searchName: "Cynthia's Ambition (BRS 138)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Fresh Water Set',
    tcgApiId: 'swsh9-139',
    number: '139',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/139.png","large":"https://images.pokemontcg.io/swsh9/139_hires.png"}',
    searchName: 'Fresh Water Set (BRS 139)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Friends in Galar',
    tcgApiId: 'swsh9-140',
    number: '140',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/140.png","large":"https://images.pokemontcg.io/swsh9/140_hires.png"}',
    searchName: 'Friends in Galar (BRS 140)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Gloria',
    tcgApiId: 'swsh9-141',
    number: '141',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/141.png","large":"https://images.pokemontcg.io/swsh9/141_hires.png"}',
    searchName: 'Gloria (BRS 141)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Hunting Gloves',
    tcgApiId: 'swsh9-142',
    number: '142',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/142.png","large":"https://images.pokemontcg.io/swsh9/142_hires.png"}',
    searchName: 'Hunting Gloves (BRS 142)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Kindler',
    tcgApiId: 'swsh9-143',
    number: '143',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/143.png","large":"https://images.pokemontcg.io/swsh9/143_hires.png"}',
    searchName: 'Kindler (BRS 143)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Magma Basin',
    tcgApiId: 'swsh9-144',
    number: '144',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/144.png","large":"https://images.pokemontcg.io/swsh9/144_hires.png"}',
    searchName: 'Magma Basin (BRS 144)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Marnie's Pride",
    tcgApiId: 'swsh9-145',
    number: '145',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/145.png","large":"https://images.pokemontcg.io/swsh9/145_hires.png"}',
    searchName: "Marnie's Pride (BRS 145)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Pot Helmet',
    tcgApiId: 'swsh9-146',
    number: '146',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/146.png","large":"https://images.pokemontcg.io/swsh9/146_hires.png"}',
    searchName: 'Pot Helmet (BRS 146)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Professor's Research",
    tcgApiId: 'swsh9-147',
    number: '147',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/147.png","large":"https://images.pokemontcg.io/swsh9/147_hires.png"}',
    searchName: "Professor's Research (BRS 147)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Roseanne's Backup",
    tcgApiId: 'swsh9-148',
    number: '148',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/148.png","large":"https://images.pokemontcg.io/swsh9/148_hires.png"}',
    searchName: "Roseanne's Backup (BRS 148)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Team Yell's Cheer",
    tcgApiId: 'swsh9-149',
    number: '149',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/149.png","large":"https://images.pokemontcg.io/swsh9/149_hires.png"}',
    searchName: "Team Yell's Cheer (BRS 149)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Ultra Ball',
    tcgApiId: 'swsh9-150',
    number: '150',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/150.png","large":"https://images.pokemontcg.io/swsh9/150_hires.png"}',
    searchName: 'Ultra Ball (BRS 150)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Double Turbo Energy',
    tcgApiId: 'swsh9-151',
    number: '151',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/151.png","large":"https://images.pokemontcg.io/swsh9/151_hires.png"}',
    searchName: 'Double Turbo Energy (BRS 151)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Shaymin V',
    tcgApiId: 'swsh9-152',
    number: '152',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/152.png","large":"https://images.pokemontcg.io/swsh9/152_hires.png"}',
    searchName: 'Shaymin V (BRS 152)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Charizard V',
    tcgApiId: 'swsh9-153',
    number: '153',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/153.png","large":"https://images.pokemontcg.io/swsh9/153_hires.png"}',
    searchName: 'Charizard V (BRS 153)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Charizard V',
    tcgApiId: 'swsh9-154',
    number: '154',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/154.png","large":"https://images.pokemontcg.io/swsh9/154_hires.png"}',
    searchName: 'Charizard V (BRS 154)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Lumineon V',
    tcgApiId: 'swsh9-155',
    number: '155',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/155.png","large":"https://images.pokemontcg.io/swsh9/155_hires.png"}',
    searchName: 'Lumineon V (BRS 155)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Lumineon V',
    tcgApiId: 'swsh9-156',
    number: '156',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/156.png","large":"https://images.pokemontcg.io/swsh9/156_hires.png"}',
    searchName: 'Lumineon V (BRS 156)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Pikachu V',
    tcgApiId: 'swsh9-157',
    number: '157',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/157.png","large":"https://images.pokemontcg.io/swsh9/157_hires.png"}',
    searchName: 'Pikachu V (BRS 157)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Raichu V',
    tcgApiId: 'swsh9-158',
    number: '158',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/158.png","large":"https://images.pokemontcg.io/swsh9/158_hires.png"}',
    searchName: 'Raichu V (BRS 158)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Granbull V',
    tcgApiId: 'swsh9-159',
    number: '159',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/159.png","large":"https://images.pokemontcg.io/swsh9/159_hires.png"}',
    searchName: 'Granbull V (BRS 159)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Whimsicott V',
    tcgApiId: 'swsh9-160',
    number: '160',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/160.png","large":"https://images.pokemontcg.io/swsh9/160_hires.png"}',
    searchName: 'Whimsicott V (BRS 160)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Honchkrow V',
    tcgApiId: 'swsh9-161',
    number: '161',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/161.png","large":"https://images.pokemontcg.io/swsh9/161_hires.png"}',
    searchName: 'Honchkrow V (BRS 161)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Honchkrow V',
    tcgApiId: 'swsh9-162',
    number: '162',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/162.png","large":"https://images.pokemontcg.io/swsh9/162_hires.png"}',
    searchName: 'Honchkrow V (BRS 162)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Zamazenta V',
    tcgApiId: 'swsh9-163',
    number: '163',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/163.png","large":"https://images.pokemontcg.io/swsh9/163_hires.png"}',
    searchName: 'Zamazenta V (BRS 163)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Flygon V',
    tcgApiId: 'swsh9-164',
    number: '164',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/164.png","large":"https://images.pokemontcg.io/swsh9/164_hires.png"}',
    searchName: 'Flygon V (BRS 164)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Arceus V',
    tcgApiId: 'swsh9-165',
    number: '165',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/165.png","large":"https://images.pokemontcg.io/swsh9/165_hires.png"}',
    searchName: 'Arceus V (BRS 165)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Arceus V',
    tcgApiId: 'swsh9-166',
    number: '166',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/166.png","large":"https://images.pokemontcg.io/swsh9/166_hires.png"}',
    searchName: 'Arceus V (BRS 166)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Barry',
    tcgApiId: 'swsh9-167',
    number: '167',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/167.png","large":"https://images.pokemontcg.io/swsh9/167_hires.png"}',
    searchName: 'Barry (BRS 167)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Cheren's Care",
    tcgApiId: 'swsh9-168',
    number: '168',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/168.png","large":"https://images.pokemontcg.io/swsh9/168_hires.png"}',
    searchName: "Cheren's Care (BRS 168)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Cynthia's Ambition",
    tcgApiId: 'swsh9-169',
    number: '169',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/169.png","large":"https://images.pokemontcg.io/swsh9/169_hires.png"}',
    searchName: "Cynthia's Ambition (BRS 169)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Kindler',
    tcgApiId: 'swsh9-170',
    number: '170',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/170.png","large":"https://images.pokemontcg.io/swsh9/170_hires.png"}',
    searchName: 'Kindler (BRS 170)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Marnie's Pride",
    tcgApiId: 'swsh9-171',
    number: '171',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/171.png","large":"https://images.pokemontcg.io/swsh9/171_hires.png"}',
    searchName: "Marnie's Pride (BRS 171)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Roseanne's Backup",
    tcgApiId: 'swsh9-172',
    number: '172',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/172.png","large":"https://images.pokemontcg.io/swsh9/172_hires.png"}',
    searchName: "Roseanne's Backup (BRS 172)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Shaymin VSTAR',
    tcgApiId: 'swsh9-173',
    number: '173',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/173.png","large":"https://images.pokemontcg.io/swsh9/173_hires.png"}',
    searchName: 'Shaymin VSTAR (BRS 173)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Charizard VSTAR',
    tcgApiId: 'swsh9-174',
    number: '174',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/174.png","large":"https://images.pokemontcg.io/swsh9/174_hires.png"}',
    searchName: 'Charizard VSTAR (BRS 174)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Whimsicott VSTAR',
    tcgApiId: 'swsh9-175',
    number: '175',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/175.png","large":"https://images.pokemontcg.io/swsh9/175_hires.png"}',
    searchName: 'Whimsicott VSTAR (BRS 175)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Arceus VSTAR',
    tcgApiId: 'swsh9-176',
    number: '176',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/176.png","large":"https://images.pokemontcg.io/swsh9/176_hires.png"}',
    searchName: 'Arceus VSTAR (BRS 176)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Cheren's Care",
    tcgApiId: 'swsh9-177',
    number: '177',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/177.png","large":"https://images.pokemontcg.io/swsh9/177_hires.png"}',
    searchName: "Cheren's Care (BRS 177)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Cynthia's Ambition",
    tcgApiId: 'swsh9-178',
    number: '178',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/178.png","large":"https://images.pokemontcg.io/swsh9/178_hires.png"}',
    searchName: "Cynthia's Ambition (BRS 178)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Kindler',
    tcgApiId: 'swsh9-179',
    number: '179',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/179.png","large":"https://images.pokemontcg.io/swsh9/179_hires.png"}',
    searchName: 'Kindler (BRS 179)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: "Roseanne's Backup",
    tcgApiId: 'swsh9-180',
    number: '180',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/180.png","large":"https://images.pokemontcg.io/swsh9/180_hires.png"}',
    searchName: "Roseanne's Backup (BRS 180)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Galarian Articuno V',
    tcgApiId: 'swsh9-181',
    number: '181',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/181.png","large":"https://images.pokemontcg.io/swsh9/181_hires.png"}',
    searchName: 'Galarian Articuno V (BRS 181)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Galarian Zapdos V',
    tcgApiId: 'swsh9-182',
    number: '182',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/182.png","large":"https://images.pokemontcg.io/swsh9/182_hires.png"}',
    searchName: 'Galarian Zapdos V (BRS 182)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Galarian Moltres V',
    tcgApiId: 'swsh9-183',
    number: '183',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/183.png","large":"https://images.pokemontcg.io/swsh9/183_hires.png"}',
    searchName: 'Galarian Moltres V (BRS 183)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Arceus VSTAR',
    tcgApiId: 'swsh9-184',
    number: '184',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/184.png","large":"https://images.pokemontcg.io/swsh9/184_hires.png"}',
    searchName: 'Arceus VSTAR (BRS 184)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Magma Basin',
    tcgApiId: 'swsh9-185',
    number: '185',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/185.png","large":"https://images.pokemontcg.io/swsh9/185_hires.png"}',
    searchName: 'Magma Basin (BRS 185)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9',
    name: 'Ultra Ball',
    tcgApiId: 'swsh9-186',
    number: '186',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9/186.png","large":"https://images.pokemontcg.io/swsh9/186_hires.png"}',
    searchName: 'Ultra Ball (BRS 186)',
  },
];
