export const cardSeedSwsh9tg = [
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Flareon',
    tcgApiId: 'swsh9tg-TG01',
    number: 'TG01',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG01.png","large":"https://images.pokemontcg.io/swsh9tg/TG01_hires.png"}',
    searchName: 'Flareon (BRS TG01)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Vaporeon',
    tcgApiId: 'swsh9tg-TG02',
    number: 'TG02',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG02.png","large":"https://images.pokemontcg.io/swsh9tg/TG02_hires.png"}',
    searchName: 'Vaporeon (BRS TG02)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Octillery',
    tcgApiId: 'swsh9tg-TG03',
    number: 'TG03',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG03.png","large":"https://images.pokemontcg.io/swsh9tg/TG03_hires.png"}',
    searchName: 'Octillery (BRS TG03)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Jolteon',
    tcgApiId: 'swsh9tg-TG04',
    number: 'TG04',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG04.png","large":"https://images.pokemontcg.io/swsh9tg/TG04_hires.png"}',
    searchName: 'Jolteon (BRS TG04)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Zekrom',
    tcgApiId: 'swsh9tg-TG05',
    number: 'TG05',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG05.png","large":"https://images.pokemontcg.io/swsh9tg/TG05_hires.png"}',
    searchName: 'Zekrom (BRS TG05)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Dusknoir',
    tcgApiId: 'swsh9tg-TG06',
    number: 'TG06',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG06.png","large":"https://images.pokemontcg.io/swsh9tg/TG06_hires.png"}',
    searchName: 'Dusknoir (BRS TG06)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Dedenne',
    tcgApiId: 'swsh9tg-TG07',
    number: 'TG07',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG07.png","large":"https://images.pokemontcg.io/swsh9tg/TG07_hires.png"}',
    searchName: 'Dedenne (BRS TG07)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Alcremie',
    tcgApiId: 'swsh9tg-TG08',
    number: 'TG08',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG08.png","large":"https://images.pokemontcg.io/swsh9tg/TG08_hires.png"}',
    searchName: 'Alcremie (BRS TG08)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Ariados',
    tcgApiId: 'swsh9tg-TG09',
    number: 'TG09',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG09.png","large":"https://images.pokemontcg.io/swsh9tg/TG09_hires.png"}',
    searchName: 'Ariados (BRS TG09)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Houndoom',
    tcgApiId: 'swsh9tg-TG10',
    number: 'TG10',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG10.png","large":"https://images.pokemontcg.io/swsh9tg/TG10_hires.png"}',
    searchName: 'Houndoom (BRS TG10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Eevee',
    tcgApiId: 'swsh9tg-TG11',
    number: 'TG11',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG11.png","large":"https://images.pokemontcg.io/swsh9tg/TG11_hires.png"}',
    searchName: 'Eevee (BRS TG11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Oranguru',
    tcgApiId: 'swsh9tg-TG12',
    number: 'TG12',
    rarity: 'Trainer Gallery Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG12.png","large":"https://images.pokemontcg.io/swsh9tg/TG12_hires.png"}',
    searchName: 'Oranguru (BRS TG12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Boltund V',
    tcgApiId: 'swsh9tg-TG13',
    number: 'TG13',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG13.png","large":"https://images.pokemontcg.io/swsh9tg/TG13_hires.png"}',
    searchName: 'Boltund V (BRS TG13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Sylveon V',
    tcgApiId: 'swsh9tg-TG14',
    number: 'TG14',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG14.png","large":"https://images.pokemontcg.io/swsh9tg/TG14_hires.png"}',
    searchName: 'Sylveon V (BRS TG14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Sylveon VMAX',
    tcgApiId: 'swsh9tg-TG15',
    number: 'TG15',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG15.png","large":"https://images.pokemontcg.io/swsh9tg/TG15_hires.png"}',
    searchName: 'Sylveon VMAX (BRS TG15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Mimikyu V',
    tcgApiId: 'swsh9tg-TG16',
    number: 'TG16',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG16.png","large":"https://images.pokemontcg.io/swsh9tg/TG16_hires.png"}',
    searchName: 'Mimikyu V (BRS TG16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Mimikyu VMAX',
    tcgApiId: 'swsh9tg-TG17',
    number: 'TG17',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG17.png","large":"https://images.pokemontcg.io/swsh9tg/TG17_hires.png"}',
    searchName: 'Mimikyu VMAX (BRS TG17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Single Strike Urshifu V',
    tcgApiId: 'swsh9tg-TG18',
    number: 'TG18',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG18.png","large":"https://images.pokemontcg.io/swsh9tg/TG18_hires.png"}',
    searchName: 'Single Strike Urshifu V (BRS TG18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Single Strike Urshifu VMAX',
    tcgApiId: 'swsh9tg-TG19',
    number: 'TG19',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG19.png","large":"https://images.pokemontcg.io/swsh9tg/TG19_hires.png"}',
    searchName: 'Single Strike Urshifu VMAX (BRS TG19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Rapid Strike Urshifu V',
    tcgApiId: 'swsh9tg-TG20',
    number: 'TG20',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG20.png","large":"https://images.pokemontcg.io/swsh9tg/TG20_hires.png"}',
    searchName: 'Rapid Strike Urshifu V (BRS TG20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Rapid Strike Urshifu VMAX',
    tcgApiId: 'swsh9tg-TG21',
    number: 'TG21',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG21.png","large":"https://images.pokemontcg.io/swsh9tg/TG21_hires.png"}',
    searchName: 'Rapid Strike Urshifu VMAX (BRS TG21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Umbreon V',
    tcgApiId: 'swsh9tg-TG22',
    number: 'TG22',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG22.png","large":"https://images.pokemontcg.io/swsh9tg/TG22_hires.png"}',
    searchName: 'Umbreon V (BRS TG22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Umbreon VMAX',
    tcgApiId: 'swsh9tg-TG23',
    number: 'TG23',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG23.png","large":"https://images.pokemontcg.io/swsh9tg/TG23_hires.png"}',
    searchName: 'Umbreon VMAX (BRS TG23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: "Acerola's Premonition",
    tcgApiId: 'swsh9tg-TG24',
    number: 'TG24',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG24.png","large":"https://images.pokemontcg.io/swsh9tg/TG24_hires.png"}',
    searchName: "Acerola's Premonition (BRS TG24)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Café Master',
    tcgApiId: 'swsh9tg-TG25',
    number: 'TG25',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG25.png","large":"https://images.pokemontcg.io/swsh9tg/TG25_hires.png"}',
    searchName: 'Café Master (BRS TG25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Gloria',
    tcgApiId: 'swsh9tg-TG26',
    number: 'TG26',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG26.png","large":"https://images.pokemontcg.io/swsh9tg/TG26_hires.png"}',
    searchName: 'Gloria (BRS TG26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Rapid Strike Style Mustard',
    tcgApiId: 'swsh9tg-TG27',
    number: 'TG27',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG27.png","large":"https://images.pokemontcg.io/swsh9tg/TG27_hires.png"}',
    searchName: 'Rapid Strike Style Mustard (BRS TG27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Single Strike Style Mustard',
    tcgApiId: 'swsh9tg-TG28',
    number: 'TG28',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG28.png","large":"https://images.pokemontcg.io/swsh9tg/TG28_hires.png"}',
    searchName: 'Single Strike Style Mustard (BRS TG28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Single Strike Urshifu VMAX',
    tcgApiId: 'swsh9tg-TG29',
    number: 'TG29',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG29.png","large":"https://images.pokemontcg.io/swsh9tg/TG29_hires.png"}',
    searchName: 'Single Strike Urshifu VMAX (BRS TG29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh9tg',
    name: 'Rapid Strike Urshifu VMAX',
    tcgApiId: 'swsh9tg-TG30',
    number: 'TG30',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/swsh9tg/TG30.png","large":"https://images.pokemontcg.io/swsh9tg/TG30_hires.png"}',
    searchName: 'Rapid Strike Urshifu VMAX (BRS TG30)',
  },
];
