export const cardSeedSwsh45 = [
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Yanma',
    tcgApiId: 'swsh45-1',
    number: '1',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/1.png","large":"https://images.pokemontcg.io/swsh45/1_hires.png"}',
    searchName: 'Yanma (SHF 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Yanmega',
    tcgApiId: 'swsh45-2',
    number: '2',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/2.png","large":"https://images.pokemontcg.io/swsh45/2_hires.png"}',
    searchName: 'Yanmega (SHF 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Celebi',
    tcgApiId: 'swsh45-3',
    number: '3',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/3.png","large":"https://images.pokemontcg.io/swsh45/3_hires.png"}',
    searchName: 'Celebi (SHF 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Cacnea',
    tcgApiId: 'swsh45-4',
    number: '4',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/4.png","large":"https://images.pokemontcg.io/swsh45/4_hires.png"}',
    searchName: 'Cacnea (SHF 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Tropius',
    tcgApiId: 'swsh45-5',
    number: '5',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/5.png","large":"https://images.pokemontcg.io/swsh45/5_hires.png"}',
    searchName: 'Tropius (SHF 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Rowlet',
    tcgApiId: 'swsh45-6',
    number: '6',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/6.png","large":"https://images.pokemontcg.io/swsh45/6_hires.png"}',
    searchName: 'Rowlet (SHF 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Dartrix',
    tcgApiId: 'swsh45-7',
    number: '7',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/7.png","large":"https://images.pokemontcg.io/swsh45/7_hires.png"}',
    searchName: 'Dartrix (SHF 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Decidueye',
    tcgApiId: 'swsh45-8',
    number: '8',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/8.png","large":"https://images.pokemontcg.io/swsh45/8_hires.png"}',
    searchName: 'Decidueye (SHF 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Dhelmise V',
    tcgApiId: 'swsh45-9',
    number: '9',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/9.png","large":"https://images.pokemontcg.io/swsh45/9_hires.png"}',
    searchName: 'Dhelmise V (SHF 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Dhelmise VMAX',
    tcgApiId: 'swsh45-10',
    number: '10',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/10.png","large":"https://images.pokemontcg.io/swsh45/10_hires.png"}',
    searchName: 'Dhelmise VMAX (SHF 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Grookey',
    tcgApiId: 'swsh45-11',
    number: '11',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/11.png","large":"https://images.pokemontcg.io/swsh45/11_hires.png"}',
    searchName: 'Grookey (SHF 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Thwackey',
    tcgApiId: 'swsh45-12',
    number: '12',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/12.png","large":"https://images.pokemontcg.io/swsh45/12_hires.png"}',
    searchName: 'Thwackey (SHF 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Rillaboom',
    tcgApiId: 'swsh45-13',
    number: '13',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/13.png","large":"https://images.pokemontcg.io/swsh45/13_hires.png"}',
    searchName: 'Rillaboom (SHF 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Gossifleur',
    tcgApiId: 'swsh45-14',
    number: '14',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/14.png","large":"https://images.pokemontcg.io/swsh45/14_hires.png"}',
    searchName: 'Gossifleur (SHF 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Eldegoss',
    tcgApiId: 'swsh45-15',
    number: '15',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/15.png","large":"https://images.pokemontcg.io/swsh45/15_hires.png"}',
    searchName: 'Eldegoss (SHF 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Zarude',
    tcgApiId: 'swsh45-16',
    number: '16',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/16.png","large":"https://images.pokemontcg.io/swsh45/16_hires.png"}',
    searchName: 'Zarude (SHF 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Reshiram',
    tcgApiId: 'swsh45-17',
    number: '17',
    rarity: 'Amazing Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/17.png","large":"https://images.pokemontcg.io/swsh45/17_hires.png"}',
    searchName: 'Reshiram (SHF 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Cinderace V',
    tcgApiId: 'swsh45-18',
    number: '18',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/18.png","large":"https://images.pokemontcg.io/swsh45/18_hires.png"}',
    searchName: 'Cinderace V (SHF 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Cinderace VMAX',
    tcgApiId: 'swsh45-19',
    number: '19',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/19.png","large":"https://images.pokemontcg.io/swsh45/19_hires.png"}',
    searchName: 'Cinderace VMAX (SHF 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Horsea',
    tcgApiId: 'swsh45-20',
    number: '20',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/20.png","large":"https://images.pokemontcg.io/swsh45/20_hires.png"}',
    searchName: 'Horsea (SHF 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Kyogre',
    tcgApiId: 'swsh45-21',
    number: '21',
    rarity: 'Amazing Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/21.png","large":"https://images.pokemontcg.io/swsh45/21_hires.png"}',
    searchName: 'Kyogre (SHF 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Buizel',
    tcgApiId: 'swsh45-22',
    number: '22',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/22.png","large":"https://images.pokemontcg.io/swsh45/22_hires.png"}',
    searchName: 'Buizel (SHF 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Floatzel',
    tcgApiId: 'swsh45-23',
    number: '23',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/23.png","large":"https://images.pokemontcg.io/swsh45/23_hires.png"}',
    searchName: 'Floatzel (SHF 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Manaphy',
    tcgApiId: 'swsh45-24',
    number: '24',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/24.png","large":"https://images.pokemontcg.io/swsh45/24_hires.png"}',
    searchName: 'Manaphy (SHF 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Volcanion',
    tcgApiId: 'swsh45-25',
    number: '25',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/25.png","large":"https://images.pokemontcg.io/swsh45/25_hires.png"}',
    searchName: 'Volcanion (SHF 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Chewtle',
    tcgApiId: 'swsh45-26',
    number: '26',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/26.png","large":"https://images.pokemontcg.io/swsh45/26_hires.png"}',
    searchName: 'Chewtle (SHF 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Drednaw',
    tcgApiId: 'swsh45-27',
    number: '27',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/27.png","large":"https://images.pokemontcg.io/swsh45/27_hires.png"}',
    searchName: 'Drednaw (SHF 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Cramorant',
    tcgApiId: 'swsh45-28',
    number: '28',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/28.png","large":"https://images.pokemontcg.io/swsh45/28_hires.png"}',
    searchName: 'Cramorant (SHF 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Snom',
    tcgApiId: 'swsh45-29',
    number: '29',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/29.png","large":"https://images.pokemontcg.io/swsh45/29_hires.png"}',
    searchName: 'Snom (SHF 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Frosmoth',
    tcgApiId: 'swsh45-30',
    number: '30',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/30.png","large":"https://images.pokemontcg.io/swsh45/30_hires.png"}',
    searchName: 'Frosmoth (SHF 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Shinx',
    tcgApiId: 'swsh45-31',
    number: '31',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/31.png","large":"https://images.pokemontcg.io/swsh45/31_hires.png"}',
    searchName: 'Shinx (SHF 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Luxio',
    tcgApiId: 'swsh45-32',
    number: '32',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/32.png","large":"https://images.pokemontcg.io/swsh45/32_hires.png"}',
    searchName: 'Luxio (SHF 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Luxray',
    tcgApiId: 'swsh45-33',
    number: '33',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/33.png","large":"https://images.pokemontcg.io/swsh45/33_hires.png"}',
    searchName: 'Luxray (SHF 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Rotom',
    tcgApiId: 'swsh45-34',
    number: '34',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/34.png","large":"https://images.pokemontcg.io/swsh45/34_hires.png"}',
    searchName: 'Rotom (SHF 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Morpeko',
    tcgApiId: 'swsh45-35',
    number: '35',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/35.png","large":"https://images.pokemontcg.io/swsh45/35_hires.png"}',
    searchName: 'Morpeko (SHF 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Morpeko',
    tcgApiId: 'swsh45-36',
    number: '36',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/36.png","large":"https://images.pokemontcg.io/swsh45/36_hires.png"}',
    searchName: 'Morpeko (SHF 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Morpeko V',
    tcgApiId: 'swsh45-37',
    number: '37',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/37.png","large":"https://images.pokemontcg.io/swsh45/37_hires.png"}',
    searchName: 'Morpeko V (SHF 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Morpeko VMAX',
    tcgApiId: 'swsh45-38',
    number: '38',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/38.png","large":"https://images.pokemontcg.io/swsh45/38_hires.png"}',
    searchName: 'Morpeko VMAX (SHF 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Indeedee V',
    tcgApiId: 'swsh45-39',
    number: '39',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/39.png","large":"https://images.pokemontcg.io/swsh45/39_hires.png"}',
    searchName: 'Indeedee V (SHF 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Trapinch',
    tcgApiId: 'swsh45-40',
    number: '40',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/40.png","large":"https://images.pokemontcg.io/swsh45/40_hires.png"}',
    searchName: 'Trapinch (SHF 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Koffing',
    tcgApiId: 'swsh45-41',
    number: '41',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/41.png","large":"https://images.pokemontcg.io/swsh45/41_hires.png"}',
    searchName: 'Koffing (SHF 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Galarian Weezing',
    tcgApiId: 'swsh45-42',
    number: '42',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/42.png","large":"https://images.pokemontcg.io/swsh45/42_hires.png"}',
    searchName: 'Galarian Weezing (SHF 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Spinarak',
    tcgApiId: 'swsh45-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/43.png","large":"https://images.pokemontcg.io/swsh45/43_hires.png"}',
    searchName: 'Spinarak (SHF 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Crobat V',
    tcgApiId: 'swsh45-44',
    number: '44',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/44.png","large":"https://images.pokemontcg.io/swsh45/44_hires.png"}',
    searchName: 'Crobat V (SHF 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Crobat VMAX',
    tcgApiId: 'swsh45-45',
    number: '45',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/45.png","large":"https://images.pokemontcg.io/swsh45/45_hires.png"}',
    searchName: 'Crobat VMAX (SHF 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Yveltal',
    tcgApiId: 'swsh45-46',
    number: '46',
    rarity: 'Amazing Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/46.png","large":"https://images.pokemontcg.io/swsh45/46_hires.png"}',
    searchName: 'Yveltal (SHF 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Nickit',
    tcgApiId: 'swsh45-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/47.png","large":"https://images.pokemontcg.io/swsh45/47_hires.png"}',
    searchName: 'Nickit (SHF 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Thievul',
    tcgApiId: 'swsh45-48',
    number: '48',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/48.png","large":"https://images.pokemontcg.io/swsh45/48_hires.png"}',
    searchName: 'Thievul (SHF 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Cufant',
    tcgApiId: 'swsh45-49',
    number: '49',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/49.png","large":"https://images.pokemontcg.io/swsh45/49_hires.png"}',
    searchName: 'Cufant (SHF 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Ditto V',
    tcgApiId: 'swsh45-50',
    number: '50',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/50.png","large":"https://images.pokemontcg.io/swsh45/50_hires.png"}',
    searchName: 'Ditto V (SHF 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Ditto VMAX',
    tcgApiId: 'swsh45-51',
    number: '51',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/51.png","large":"https://images.pokemontcg.io/swsh45/51_hires.png"}',
    searchName: 'Ditto VMAX (SHF 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Eevee',
    tcgApiId: 'swsh45-52',
    number: '52',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/52.png","large":"https://images.pokemontcg.io/swsh45/52_hires.png"}',
    searchName: 'Eevee (SHF 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Greedent V',
    tcgApiId: 'swsh45-53',
    number: '53',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/53.png","large":"https://images.pokemontcg.io/swsh45/53_hires.png"}',
    searchName: 'Greedent V (SHF 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Cramorant V',
    tcgApiId: 'swsh45-54',
    number: '54',
    rarity: 'Rare Holo V',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/54.png","large":"https://images.pokemontcg.io/swsh45/54_hires.png"}',
    searchName: 'Cramorant V (SHF 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Cramorant VMAX',
    tcgApiId: 'swsh45-55',
    number: '55',
    rarity: 'Rare Holo VMAX',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/55.png","large":"https://images.pokemontcg.io/swsh45/55_hires.png"}',
    searchName: 'Cramorant VMAX (SHF 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Indeedee',
    tcgApiId: 'swsh45-56',
    number: '56',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/56.png","large":"https://images.pokemontcg.io/swsh45/56_hires.png"}',
    searchName: 'Indeedee (SHF 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Ball Guy',
    tcgApiId: 'swsh45-57',
    number: '57',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/57.png","large":"https://images.pokemontcg.io/swsh45/57_hires.png"}',
    searchName: 'Ball Guy (SHF 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: "Boss's Orders",
    tcgApiId: 'swsh45-58',
    number: '58',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/58.png","large":"https://images.pokemontcg.io/swsh45/58_hires.png"}',
    searchName: "Boss's Orders (SHF 58)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Gym Trainer',
    tcgApiId: 'swsh45-59',
    number: '59',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/59.png","large":"https://images.pokemontcg.io/swsh45/59_hires.png"}',
    searchName: 'Gym Trainer (SHF 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: "Professor's Research",
    tcgApiId: 'swsh45-60',
    number: '60',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/60.png","large":"https://images.pokemontcg.io/swsh45/60_hires.png"}',
    searchName: "Professor's Research (SHF 60)",
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Rusted Shield',
    tcgApiId: 'swsh45-61',
    number: '61',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/61.png","large":"https://images.pokemontcg.io/swsh45/61_hires.png"}',
    searchName: 'Rusted Shield (SHF 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Rusted Sword',
    tcgApiId: 'swsh45-62',
    number: '62',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/62.png","large":"https://images.pokemontcg.io/swsh45/62_hires.png"}',
    searchName: 'Rusted Sword (SHF 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Team Yell Towel',
    tcgApiId: 'swsh45-63',
    number: '63',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/63.png","large":"https://images.pokemontcg.io/swsh45/63_hires.png"}',
    searchName: 'Team Yell Towel (SHF 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Alcremie V',
    tcgApiId: 'swsh45-64',
    number: '64',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/64.png","large":"https://images.pokemontcg.io/swsh45/64_hires.png"}',
    searchName: 'Alcremie V (SHF 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Ball Guy',
    tcgApiId: 'swsh45-65',
    number: '65',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/65.png","large":"https://images.pokemontcg.io/swsh45/65_hires.png"}',
    searchName: 'Ball Guy (SHF 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Bird Keeper',
    tcgApiId: 'swsh45-66',
    number: '66',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/66.png","large":"https://images.pokemontcg.io/swsh45/66_hires.png"}',
    searchName: 'Bird Keeper (SHF 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Cara Liss',
    tcgApiId: 'swsh45-67',
    number: '67',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/67.png","large":"https://images.pokemontcg.io/swsh45/67_hires.png"}',
    searchName: 'Cara Liss (SHF 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Gym Trainer',
    tcgApiId: 'swsh45-68',
    number: '68',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/68.png","large":"https://images.pokemontcg.io/swsh45/68_hires.png"}',
    searchName: 'Gym Trainer (SHF 68)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Piers',
    tcgApiId: 'swsh45-69',
    number: '69',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/69.png","large":"https://images.pokemontcg.io/swsh45/69_hires.png"}',
    searchName: 'Piers (SHF 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Poké Kid',
    tcgApiId: 'swsh45-70',
    number: '70',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/70.png","large":"https://images.pokemontcg.io/swsh45/70_hires.png"}',
    searchName: 'Poké Kid (SHF 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Rose',
    tcgApiId: 'swsh45-71',
    number: '71',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/71.png","large":"https://images.pokemontcg.io/swsh45/71_hires.png"}',
    searchName: 'Rose (SHF 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Skyla',
    tcgApiId: 'swsh45-72',
    number: '72',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/72.png","large":"https://images.pokemontcg.io/swsh45/72_hires.png"}',
    searchName: 'Skyla (SHF 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'swsh45',
    name: 'Alcremie VMAX',
    tcgApiId: 'swsh45-73',
    number: '73',
    rarity: 'Rare Rainbow',
    images:
      '{"small":"https://images.pokemontcg.io/swsh45/73.png","large":"https://images.pokemontcg.io/swsh45/73_hires.png"}',
    searchName: 'Alcremie VMAX (SHF 73)',
  },
];
