export const cardSeedTk1b = [
  {"tcgId":"pokemon","setId":"tk1b","name":"Electrike","tcgApiId":"tk1b-1","number":"1","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/1.png\",\"large\":\"https://images.pokemontcg.io/tk1b/1_hires.png\"}","searchName":"Electrike (undefined 1)"},
  {"tcgId":"pokemon","setId":"tk1b","name":"Latios","tcgApiId":"tk1b-2","number":"2","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/2.png\",\"large\":\"https://images.pokemontcg.io/tk1b/2_hires.png\"}","searchName":"Latios (undefined 2)"},
  {"tcgId":"pokemon","setId":"tk1b","name":"Linoone","tcgApiId":"tk1b-3","number":"3","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/3.png\",\"large\":\"https://images.pokemontcg.io/tk1b/3_hires.png\"}","searchName":"Linoone (undefined 3)"},
  {"tcgId":"pokemon","setId":"tk1b","name":"Magnemite","tcgApiId":"tk1b-4","number":"4","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/4.png\",\"large\":\"https://images.pokemontcg.io/tk1b/4_hires.png\"}","searchName":"Magnemite (undefined 4)"},
  {"tcgId":"pokemon","setId":"tk1b","name":"Magneton","tcgApiId":"tk1b-5","number":"5","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/5.png\",\"large\":\"https://images.pokemontcg.io/tk1b/5_hires.png\"}","searchName":"Magneton (undefined 5)"},
  {"tcgId":"pokemon","setId":"tk1b","name":"Pikachu","tcgApiId":"tk1b-6","number":"6","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/6.png\",\"large\":\"https://images.pokemontcg.io/tk1b/6_hires.png\"}","searchName":"Pikachu (undefined 6)"},
  {"tcgId":"pokemon","setId":"tk1b","name":"Zigzagoon","tcgApiId":"tk1b-7","number":"7","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/7.png\",\"large\":\"https://images.pokemontcg.io/tk1b/7_hires.png\"}","searchName":"Zigzagoon (undefined 7)"},
  {"tcgId":"pokemon","setId":"tk1b","name":"Potion","tcgApiId":"tk1b-8","number":"8","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/8.png\",\"large\":\"https://images.pokemontcg.io/tk1b/8_hires.png\"}","searchName":"Potion (undefined 8)"},
  {"tcgId":"pokemon","setId":"tk1b","name":"Energy Search","tcgApiId":"tk1b-9","number":"9","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/9.png\",\"large\":\"https://images.pokemontcg.io/tk1b/9_hires.png\"}","searchName":"Energy Search (undefined 9)"},
  {"tcgId":"pokemon","setId":"tk1b","name":"Lightning Energy","tcgApiId":"tk1b-10","number":"10","rarity":"","images":"{\"small\":\"https://images.pokemontcg.io/tk1b/10.png\",\"large\":\"https://images.pokemontcg.io/tk1b/10_hires.png\"}","searchName":"Lightning Energy (undefined 10)"}
]
