export const cardSeedXy12 = [
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Venusaur-EX',
    tcgApiId: 'xy12-1',
    number: '1',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/1.png","large":"https://images.pokemontcg.io/xy12/1_hires.png"}',
    searchName: 'Venusaur-EX (EVO 1)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'M Venusaur-EX',
    tcgApiId: 'xy12-2',
    number: '2',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/2.png","large":"https://images.pokemontcg.io/xy12/2_hires.png"}',
    searchName: 'M Venusaur-EX (EVO 2)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Caterpie',
    tcgApiId: 'xy12-3',
    number: '3',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/3.png","large":"https://images.pokemontcg.io/xy12/3_hires.png"}',
    searchName: 'Caterpie (EVO 3)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Metapod',
    tcgApiId: 'xy12-4',
    number: '4',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/4.png","large":"https://images.pokemontcg.io/xy12/4_hires.png"}',
    searchName: 'Metapod (EVO 4)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Weedle',
    tcgApiId: 'xy12-5',
    number: '5',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/5.png","large":"https://images.pokemontcg.io/xy12/5_hires.png"}',
    searchName: 'Weedle (EVO 5)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Kakuna',
    tcgApiId: 'xy12-6',
    number: '6',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/6.png","large":"https://images.pokemontcg.io/xy12/6_hires.png"}',
    searchName: 'Kakuna (EVO 6)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Beedrill',
    tcgApiId: 'xy12-7',
    number: '7',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/7.png","large":"https://images.pokemontcg.io/xy12/7_hires.png"}',
    searchName: 'Beedrill (EVO 7)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Tangela',
    tcgApiId: 'xy12-8',
    number: '8',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/8.png","large":"https://images.pokemontcg.io/xy12/8_hires.png"}',
    searchName: 'Tangela (EVO 8)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Charmander',
    tcgApiId: 'xy12-9',
    number: '9',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/9.png","large":"https://images.pokemontcg.io/xy12/9_hires.png"}',
    searchName: 'Charmander (EVO 9)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Charmeleon',
    tcgApiId: 'xy12-10',
    number: '10',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/10.png","large":"https://images.pokemontcg.io/xy12/10_hires.png"}',
    searchName: 'Charmeleon (EVO 10)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Charizard',
    tcgApiId: 'xy12-11',
    number: '11',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/11.png","large":"https://images.pokemontcg.io/xy12/11_hires.png"}',
    searchName: 'Charizard (EVO 11)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Charizard-EX',
    tcgApiId: 'xy12-12',
    number: '12',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/12.png","large":"https://images.pokemontcg.io/xy12/12_hires.png"}',
    searchName: 'Charizard-EX (EVO 12)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'M Charizard-EX',
    tcgApiId: 'xy12-13',
    number: '13',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/13.png","large":"https://images.pokemontcg.io/xy12/13_hires.png"}',
    searchName: 'M Charizard-EX (EVO 13)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Vulpix',
    tcgApiId: 'xy12-14',
    number: '14',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/14.png","large":"https://images.pokemontcg.io/xy12/14_hires.png"}',
    searchName: 'Vulpix (EVO 14)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Ninetales',
    tcgApiId: 'xy12-15',
    number: '15',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/15.png","large":"https://images.pokemontcg.io/xy12/15_hires.png"}',
    searchName: 'Ninetales (EVO 15)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Ninetales BREAK',
    tcgApiId: 'xy12-16',
    number: '16',
    rarity: 'Rare BREAK',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/16.png","large":"https://images.pokemontcg.io/xy12/16_hires.png"}',
    searchName: 'Ninetales BREAK (EVO 16)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Growlithe',
    tcgApiId: 'xy12-17',
    number: '17',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/17.png","large":"https://images.pokemontcg.io/xy12/17_hires.png"}',
    searchName: 'Growlithe (EVO 17)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Arcanine',
    tcgApiId: 'xy12-18',
    number: '18',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/18.png","large":"https://images.pokemontcg.io/xy12/18_hires.png"}',
    searchName: 'Arcanine (EVO 18)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Ponyta',
    tcgApiId: 'xy12-19',
    number: '19',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/19.png","large":"https://images.pokemontcg.io/xy12/19_hires.png"}',
    searchName: 'Ponyta (EVO 19)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Magmar',
    tcgApiId: 'xy12-20',
    number: '20',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/20.png","large":"https://images.pokemontcg.io/xy12/20_hires.png"}',
    searchName: 'Magmar (EVO 20)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Blastoise-EX',
    tcgApiId: 'xy12-21',
    number: '21',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/21.png","large":"https://images.pokemontcg.io/xy12/21_hires.png"}',
    searchName: 'Blastoise-EX (EVO 21)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'M Blastoise-EX',
    tcgApiId: 'xy12-22',
    number: '22',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/22.png","large":"https://images.pokemontcg.io/xy12/22_hires.png"}',
    searchName: 'M Blastoise-EX (EVO 22)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Poliwag',
    tcgApiId: 'xy12-23',
    number: '23',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/23.png","large":"https://images.pokemontcg.io/xy12/23_hires.png"}',
    searchName: 'Poliwag (EVO 23)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Poliwhirl',
    tcgApiId: 'xy12-24',
    number: '24',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/24.png","large":"https://images.pokemontcg.io/xy12/24_hires.png"}',
    searchName: 'Poliwhirl (EVO 24)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Poliwrath',
    tcgApiId: 'xy12-25',
    number: '25',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/25.png","large":"https://images.pokemontcg.io/xy12/25_hires.png"}',
    searchName: 'Poliwrath (EVO 25)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Slowbro-EX',
    tcgApiId: 'xy12-26',
    number: '26',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/26.png","large":"https://images.pokemontcg.io/xy12/26_hires.png"}',
    searchName: 'Slowbro-EX (EVO 26)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'M Slowbro-EX',
    tcgApiId: 'xy12-27',
    number: '27',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/27.png","large":"https://images.pokemontcg.io/xy12/27_hires.png"}',
    searchName: 'M Slowbro-EX (EVO 27)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Seel',
    tcgApiId: 'xy12-28',
    number: '28',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/28.png","large":"https://images.pokemontcg.io/xy12/28_hires.png"}',
    searchName: 'Seel (EVO 28)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Dewgong',
    tcgApiId: 'xy12-29',
    number: '29',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/29.png","large":"https://images.pokemontcg.io/xy12/29_hires.png"}',
    searchName: 'Dewgong (EVO 29)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Staryu',
    tcgApiId: 'xy12-30',
    number: '30',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/30.png","large":"https://images.pokemontcg.io/xy12/30_hires.png"}',
    searchName: 'Staryu (EVO 30)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Starmie',
    tcgApiId: 'xy12-31',
    number: '31',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/31.png","large":"https://images.pokemontcg.io/xy12/31_hires.png"}',
    searchName: 'Starmie (EVO 31)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Starmie BREAK',
    tcgApiId: 'xy12-32',
    number: '32',
    rarity: 'Rare BREAK',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/32.png","large":"https://images.pokemontcg.io/xy12/32_hires.png"}',
    searchName: 'Starmie BREAK (EVO 32)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Magikarp',
    tcgApiId: 'xy12-33',
    number: '33',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/33.png","large":"https://images.pokemontcg.io/xy12/33_hires.png"}',
    searchName: 'Magikarp (EVO 33)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Gyarados',
    tcgApiId: 'xy12-34',
    number: '34',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/34.png","large":"https://images.pokemontcg.io/xy12/34_hires.png"}',
    searchName: 'Gyarados (EVO 34)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Pikachu',
    tcgApiId: 'xy12-35',
    number: '35',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/35.png","large":"https://images.pokemontcg.io/xy12/35_hires.png"}',
    searchName: 'Pikachu (EVO 35)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Raichu',
    tcgApiId: 'xy12-36',
    number: '36',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/36.png","large":"https://images.pokemontcg.io/xy12/36_hires.png"}',
    searchName: 'Raichu (EVO 36)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Magnemite',
    tcgApiId: 'xy12-37',
    number: '37',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/37.png","large":"https://images.pokemontcg.io/xy12/37_hires.png"}',
    searchName: 'Magnemite (EVO 37)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Magneton',
    tcgApiId: 'xy12-38',
    number: '38',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/38.png","large":"https://images.pokemontcg.io/xy12/38_hires.png"}',
    searchName: 'Magneton (EVO 38)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Voltorb',
    tcgApiId: 'xy12-39',
    number: '39',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/39.png","large":"https://images.pokemontcg.io/xy12/39_hires.png"}',
    searchName: 'Voltorb (EVO 39)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Electrode',
    tcgApiId: 'xy12-40',
    number: '40',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/40.png","large":"https://images.pokemontcg.io/xy12/40_hires.png"}',
    searchName: 'Electrode (EVO 40)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Electabuzz',
    tcgApiId: 'xy12-41',
    number: '41',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/41.png","large":"https://images.pokemontcg.io/xy12/41_hires.png"}',
    searchName: 'Electabuzz (EVO 41)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Zapdos',
    tcgApiId: 'xy12-42',
    number: '42',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/42.png","large":"https://images.pokemontcg.io/xy12/42_hires.png"}',
    searchName: 'Zapdos (EVO 42)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Nidoran ♂',
    tcgApiId: 'xy12-43',
    number: '43',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/43.png","large":"https://images.pokemontcg.io/xy12/43_hires.png"}',
    searchName: 'Nidoran ♂ (EVO 43)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Nidorino',
    tcgApiId: 'xy12-44',
    number: '44',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/44.png","large":"https://images.pokemontcg.io/xy12/44_hires.png"}',
    searchName: 'Nidorino (EVO 44)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Nidoking',
    tcgApiId: 'xy12-45',
    number: '45',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/45.png","large":"https://images.pokemontcg.io/xy12/45_hires.png"}',
    searchName: 'Nidoking (EVO 45)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Nidoking BREAK',
    tcgApiId: 'xy12-46',
    number: '46',
    rarity: 'Rare BREAK',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/46.png","large":"https://images.pokemontcg.io/xy12/46_hires.png"}',
    searchName: 'Nidoking BREAK (EVO 46)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Gastly',
    tcgApiId: 'xy12-47',
    number: '47',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/47.png","large":"https://images.pokemontcg.io/xy12/47_hires.png"}',
    searchName: 'Gastly (EVO 47)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Haunter',
    tcgApiId: 'xy12-48',
    number: '48',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/48.png","large":"https://images.pokemontcg.io/xy12/48_hires.png"}',
    searchName: 'Haunter (EVO 48)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Drowzee',
    tcgApiId: 'xy12-49',
    number: '49',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/49.png","large":"https://images.pokemontcg.io/xy12/49_hires.png"}',
    searchName: 'Drowzee (EVO 49)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Koffing',
    tcgApiId: 'xy12-50',
    number: '50',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/50.png","large":"https://images.pokemontcg.io/xy12/50_hires.png"}',
    searchName: 'Koffing (EVO 50)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Mewtwo',
    tcgApiId: 'xy12-51',
    number: '51',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/51.png","large":"https://images.pokemontcg.io/xy12/51_hires.png"}',
    searchName: 'Mewtwo (EVO 51)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Mewtwo-EX',
    tcgApiId: 'xy12-52',
    number: '52',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/52.png","large":"https://images.pokemontcg.io/xy12/52_hires.png"}',
    searchName: 'Mewtwo-EX (EVO 52)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Mew',
    tcgApiId: 'xy12-53',
    number: '53',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/53.png","large":"https://images.pokemontcg.io/xy12/53_hires.png"}',
    searchName: 'Mew (EVO 53)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Sandshrew',
    tcgApiId: 'xy12-54',
    number: '54',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/54.png","large":"https://images.pokemontcg.io/xy12/54_hires.png"}',
    searchName: 'Sandshrew (EVO 54)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Diglett',
    tcgApiId: 'xy12-55',
    number: '55',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/55.png","large":"https://images.pokemontcg.io/xy12/55_hires.png"}',
    searchName: 'Diglett (EVO 55)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Dugtrio',
    tcgApiId: 'xy12-56',
    number: '56',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/56.png","large":"https://images.pokemontcg.io/xy12/56_hires.png"}',
    searchName: 'Dugtrio (EVO 56)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Machop',
    tcgApiId: 'xy12-57',
    number: '57',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/57.png","large":"https://images.pokemontcg.io/xy12/57_hires.png"}',
    searchName: 'Machop (EVO 57)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Machoke',
    tcgApiId: 'xy12-58',
    number: '58',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/58.png","large":"https://images.pokemontcg.io/xy12/58_hires.png"}',
    searchName: 'Machoke (EVO 58)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Machamp',
    tcgApiId: 'xy12-59',
    number: '59',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/59.png","large":"https://images.pokemontcg.io/xy12/59_hires.png"}',
    searchName: 'Machamp (EVO 59)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Machamp BREAK',
    tcgApiId: 'xy12-60',
    number: '60',
    rarity: 'Rare BREAK',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/60.png","large":"https://images.pokemontcg.io/xy12/60_hires.png"}',
    searchName: 'Machamp BREAK (EVO 60)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Onix',
    tcgApiId: 'xy12-61',
    number: '61',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/61.png","large":"https://images.pokemontcg.io/xy12/61_hires.png"}',
    searchName: 'Onix (EVO 61)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Hitmonchan',
    tcgApiId: 'xy12-62',
    number: '62',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/62.png","large":"https://images.pokemontcg.io/xy12/62_hires.png"}',
    searchName: 'Hitmonchan (EVO 62)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Clefairy',
    tcgApiId: 'xy12-63',
    number: '63',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/63.png","large":"https://images.pokemontcg.io/xy12/63_hires.png"}',
    searchName: 'Clefairy (EVO 63)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Pidgeot-EX',
    tcgApiId: 'xy12-64',
    number: '64',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/64.png","large":"https://images.pokemontcg.io/xy12/64_hires.png"}',
    searchName: 'Pidgeot-EX (EVO 64)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'M Pidgeot-EX',
    tcgApiId: 'xy12-65',
    number: '65',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/65.png","large":"https://images.pokemontcg.io/xy12/65_hires.png"}',
    searchName: 'M Pidgeot-EX (EVO 65)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Rattata',
    tcgApiId: 'xy12-66',
    number: '66',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/66.png","large":"https://images.pokemontcg.io/xy12/66_hires.png"}',
    searchName: 'Rattata (EVO 66)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Raticate',
    tcgApiId: 'xy12-67',
    number: '67',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/67.png","large":"https://images.pokemontcg.io/xy12/67_hires.png"}',
    searchName: 'Raticate (EVO 67)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: "Farfetch'd",
    tcgApiId: 'xy12-68',
    number: '68',
    rarity: 'Rare',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/68.png","large":"https://images.pokemontcg.io/xy12/68_hires.png"}',
    searchName: "Farfetch'd (EVO 68)",
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Doduo',
    tcgApiId: 'xy12-69',
    number: '69',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/69.png","large":"https://images.pokemontcg.io/xy12/69_hires.png"}',
    searchName: 'Doduo (EVO 69)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Chansey',
    tcgApiId: 'xy12-70',
    number: '70',
    rarity: 'Rare Holo',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/70.png","large":"https://images.pokemontcg.io/xy12/70_hires.png"}',
    searchName: 'Chansey (EVO 70)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Porygon',
    tcgApiId: 'xy12-71',
    number: '71',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/71.png","large":"https://images.pokemontcg.io/xy12/71_hires.png"}',
    searchName: 'Porygon (EVO 71)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Dragonite-EX',
    tcgApiId: 'xy12-72',
    number: '72',
    rarity: 'Rare Holo EX',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/72.png","large":"https://images.pokemontcg.io/xy12/72_hires.png"}',
    searchName: 'Dragonite-EX (EVO 72)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Blastoise Spirit Link',
    tcgApiId: 'xy12-73',
    number: '73',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/73.png","large":"https://images.pokemontcg.io/xy12/73_hires.png"}',
    searchName: 'Blastoise Spirit Link (EVO 73)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: "Brock's Grit",
    tcgApiId: 'xy12-74',
    number: '74',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/74.png","large":"https://images.pokemontcg.io/xy12/74_hires.png"}',
    searchName: "Brock's Grit (EVO 74)",
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Charizard Spirit Link',
    tcgApiId: 'xy12-75',
    number: '75',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/75.png","large":"https://images.pokemontcg.io/xy12/75_hires.png"}',
    searchName: 'Charizard Spirit Link (EVO 75)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Devolution Spray',
    tcgApiId: 'xy12-76',
    number: '76',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/76.png","large":"https://images.pokemontcg.io/xy12/76_hires.png"}',
    searchName: 'Devolution Spray (EVO 76)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Energy Retrieval',
    tcgApiId: 'xy12-77',
    number: '77',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/77.png","large":"https://images.pokemontcg.io/xy12/77_hires.png"}',
    searchName: 'Energy Retrieval (EVO 77)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Full Heal',
    tcgApiId: 'xy12-78',
    number: '78',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/78.png","large":"https://images.pokemontcg.io/xy12/78_hires.png"}',
    searchName: 'Full Heal (EVO 78)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Maintenance',
    tcgApiId: 'xy12-79',
    number: '79',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/79.png","large":"https://images.pokemontcg.io/xy12/79_hires.png"}',
    searchName: 'Maintenance (EVO 79)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: "Misty's Determination",
    tcgApiId: 'xy12-80',
    number: '80',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/80.png","large":"https://images.pokemontcg.io/xy12/80_hires.png"}',
    searchName: "Misty's Determination (EVO 80)",
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Pidgeot Spirit Link',
    tcgApiId: 'xy12-81',
    number: '81',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/81.png","large":"https://images.pokemontcg.io/xy12/81_hires.png"}',
    searchName: 'Pidgeot Spirit Link (EVO 81)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Pokédex',
    tcgApiId: 'xy12-82',
    number: '82',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/82.png","large":"https://images.pokemontcg.io/xy12/82_hires.png"}',
    searchName: 'Pokédex (EVO 82)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Potion',
    tcgApiId: 'xy12-83',
    number: '83',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/83.png","large":"https://images.pokemontcg.io/xy12/83_hires.png"}',
    searchName: 'Potion (EVO 83)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: "Professor Oak's Hint",
    tcgApiId: 'xy12-84',
    number: '84',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/84.png","large":"https://images.pokemontcg.io/xy12/84_hires.png"}',
    searchName: "Professor Oak's Hint (EVO 84)",
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Revive',
    tcgApiId: 'xy12-85',
    number: '85',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/85.png","large":"https://images.pokemontcg.io/xy12/85_hires.png"}',
    searchName: 'Revive (EVO 85)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Slowbro Spirit Link',
    tcgApiId: 'xy12-86',
    number: '86',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/86.png","large":"https://images.pokemontcg.io/xy12/86_hires.png"}',
    searchName: 'Slowbro Spirit Link (EVO 86)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Super Potion',
    tcgApiId: 'xy12-87',
    number: '87',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/87.png","large":"https://images.pokemontcg.io/xy12/87_hires.png"}',
    searchName: 'Super Potion (EVO 87)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Switch',
    tcgApiId: 'xy12-88',
    number: '88',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/88.png","large":"https://images.pokemontcg.io/xy12/88_hires.png"}',
    searchName: 'Switch (EVO 88)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Venusaur Spirit Link',
    tcgApiId: 'xy12-89',
    number: '89',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/89.png","large":"https://images.pokemontcg.io/xy12/89_hires.png"}',
    searchName: 'Venusaur Spirit Link (EVO 89)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Double Colorless Energy',
    tcgApiId: 'xy12-90',
    number: '90',
    rarity: 'Uncommon',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/90.png","large":"https://images.pokemontcg.io/xy12/90_hires.png"}',
    searchName: 'Double Colorless Energy (EVO 90)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Grass Energy',
    tcgApiId: 'xy12-91',
    number: '91',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/91.png","large":"https://images.pokemontcg.io/xy12/91_hires.png"}',
    searchName: 'Grass Energy (EVO 91)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Fire Energy',
    tcgApiId: 'xy12-92',
    number: '92',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/92.png","large":"https://images.pokemontcg.io/xy12/92_hires.png"}',
    searchName: 'Fire Energy (EVO 92)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Water Energy',
    tcgApiId: 'xy12-93',
    number: '93',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/93.png","large":"https://images.pokemontcg.io/xy12/93_hires.png"}',
    searchName: 'Water Energy (EVO 93)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Lightning Energy',
    tcgApiId: 'xy12-94',
    number: '94',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/94.png","large":"https://images.pokemontcg.io/xy12/94_hires.png"}',
    searchName: 'Lightning Energy (EVO 94)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Psychic Energy',
    tcgApiId: 'xy12-95',
    number: '95',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/95.png","large":"https://images.pokemontcg.io/xy12/95_hires.png"}',
    searchName: 'Psychic Energy (EVO 95)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Fighting Energy',
    tcgApiId: 'xy12-96',
    number: '96',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/96.png","large":"https://images.pokemontcg.io/xy12/96_hires.png"}',
    searchName: 'Fighting Energy (EVO 96)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Darkness Energy',
    tcgApiId: 'xy12-97',
    number: '97',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/97.png","large":"https://images.pokemontcg.io/xy12/97_hires.png"}',
    searchName: 'Darkness Energy (EVO 97)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Metal Energy',
    tcgApiId: 'xy12-98',
    number: '98',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/98.png","large":"https://images.pokemontcg.io/xy12/98_hires.png"}',
    searchName: 'Metal Energy (EVO 98)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Fairy Energy',
    tcgApiId: 'xy12-99',
    number: '99',
    rarity: 'Common',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/99.png","large":"https://images.pokemontcg.io/xy12/99_hires.png"}',
    searchName: 'Fairy Energy (EVO 99)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'M Venusaur-EX',
    tcgApiId: 'xy12-100',
    number: '100',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/100.png","large":"https://images.pokemontcg.io/xy12/100_hires.png"}',
    searchName: 'M Venusaur-EX (EVO 100)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'M Charizard-EX',
    tcgApiId: 'xy12-101',
    number: '101',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/101.png","large":"https://images.pokemontcg.io/xy12/101_hires.png"}',
    searchName: 'M Charizard-EX (EVO 101)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'M Blastoise-EX',
    tcgApiId: 'xy12-102',
    number: '102',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/102.png","large":"https://images.pokemontcg.io/xy12/102_hires.png"}',
    searchName: 'M Blastoise-EX (EVO 102)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Mewtwo-EX',
    tcgApiId: 'xy12-103',
    number: '103',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/103.png","large":"https://images.pokemontcg.io/xy12/103_hires.png"}',
    searchName: 'Mewtwo-EX (EVO 103)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Pidgeot-EX',
    tcgApiId: 'xy12-104',
    number: '104',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/104.png","large":"https://images.pokemontcg.io/xy12/104_hires.png"}',
    searchName: 'Pidgeot-EX (EVO 104)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'M Pidgeot-EX',
    tcgApiId: 'xy12-105',
    number: '105',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/105.png","large":"https://images.pokemontcg.io/xy12/105_hires.png"}',
    searchName: 'M Pidgeot-EX (EVO 105)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Dragonite-EX',
    tcgApiId: 'xy12-106',
    number: '106',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/106.png","large":"https://images.pokemontcg.io/xy12/106_hires.png"}',
    searchName: 'Dragonite-EX (EVO 106)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: "Brock's Grit",
    tcgApiId: 'xy12-107',
    number: '107',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/107.png","large":"https://images.pokemontcg.io/xy12/107_hires.png"}',
    searchName: "Brock's Grit (EVO 107)",
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: "Misty's Determination",
    tcgApiId: 'xy12-108',
    number: '108',
    rarity: 'Rare Ultra',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/108.png","large":"https://images.pokemontcg.io/xy12/108_hires.png"}',
    searchName: "Misty's Determination (EVO 108)",
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'ナッシー[Exeggutor]',
    tcgApiId: 'xy12-109',
    number: '109',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/109.png","large":"https://images.pokemontcg.io/xy12/109_hires.png"}',
    searchName: 'ナッシー[Exeggutor] (EVO 109)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Flying Pikachu',
    tcgApiId: 'xy12-110',
    number: '110',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/110.png","large":"https://images.pokemontcg.io/xy12/110_hires.png"}',
    searchName: 'Flying Pikachu (EVO 110)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Surfing Pikachu',
    tcgApiId: 'xy12-111',
    number: '111',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/111.png","large":"https://images.pokemontcg.io/xy12/111_hires.png"}',
    searchName: 'Surfing Pikachu (EVO 111)',
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: "Imakuni?'s Doduo",
    tcgApiId: 'xy12-112',
    number: '112',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/112.png","large":"https://images.pokemontcg.io/xy12/112_hires.png"}',
    searchName: "Imakuni?'s Doduo (EVO 112)",
  },
  {
    tcgId: 'pokemon',
    setId: 'xy12',
    name: 'Here Comes Team Rocket!',
    tcgApiId: 'xy12-113',
    number: '113',
    rarity: 'Rare Secret',
    images:
      '{"small":"https://images.pokemontcg.io/xy12/113.png","large":"https://images.pokemontcg.io/xy12/113_hires.png"}',
    searchName: 'Here Comes Team Rocket! (EVO 113)',
  },
];
