export const setSeed = [
  {
    tcgId: "one-piece",
    name: "Memorial collection",
    id: "eb01",
    series: "Extra booster",
    printedTotal: 80,
    total: 80,
    ptcgoid: "-",
    releaseDate: new Date("2024-05-02T22:00:00.000Z"),
  },
  {
    tcgId: "one-piece",
    name: "Romance Dawn",
    id: "op01",
    series: "Booster",
    printedTotal: 121,
    total: 121,
    ptcgoid: "-",
    releaseDate: new Date("2022-12-01T22:00:00.000Z"),
    logoUrl: "https://en.onepiece-cardgame.com/images/products/expansions/op01.png",
    symbolUrl: "https://en.onepiece-cardgame.com/images/products/expansions/op01.png",
  },
  {
    tcgId: "one-piece",
    name: "Paramount War",
    id: "op02",
    series: "Booster",
    printedTotal: 120,
    total: 120,
    ptcgoid: "-",
    releaseDate: new Date("2023-03-02T22:00:00.000Z"),
    logoUrl: "https://en.onepiece-cardgame.com/images/products/expansions/op02.png",
    symbolUrl: "https://en.onepiece-cardgame.com/images/products/expansions/op02.png",
  },
  {
    tcgId: "one-piece",
    name: "Pillars of Strength",
    id: "op03",
    series: "Booster",
    printedTotal: 131,
    total: 131,
    ptcgoid: "-",
    releaseDate: new Date("2023-05-25T22:00:00.000Z"),
    logoUrl: "https://en.onepiece-cardgame.com/images/products/expansions/op03.png",
    symbolUrl: "https://en.onepiece-cardgame.com/images/products/expansions/op03.png",
  },
  {
    tcgId: "one-piece",
    name: "Alabasta Kingdom",
    id: "op07",
    series: "Booster",
    printedTotal: 131,
    total: 131,
    ptcgoid: "-",
    releaseDate: new Date("2024-05-23T22:00:00.000Z"),
    logoUrl: "https://en.onepiece-cardgame.com/images/products/expansions/op07.png",
    symbolUrl: "https://en.onepiece-cardgame.com/images/products/expansions/op07.png",
  },
];
