export const setSeed = [
  {
  tcgId: "digimon",
  name: "BT-01: Booster New Evolution",
  id: "BT-01",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.551Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-01_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-01_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-02: Booster Ultimate Power",
  id: "BT-02",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.551Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-02_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-02_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-03: Booster Union Impact",
  id: "BT-03",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.551Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-03_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-03_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-04: Booster Great Legend",
  id: "BT-04",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.551Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-04_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-04_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-05: Booster Battle Of Omni",
  id: "BT-05",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.551Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-05_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-05_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-06: Booster Double Diamond",
  id: "BT-06",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-06_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-06_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-01: Theme Booster Classic Collection",
  id: "EX-01",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-01_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-01_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-07: Booster Next Adventure",
  id: "BT-07",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-07_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-07_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-08: Booster New Awakening",
  id: "BT-08",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-08_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-08_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-02: Theme Booster Digital Hazard",
  id: "EX-02",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-02_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-02_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-09: Booster X Record",
  id: "BT-09",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-09_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-09_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-10: Booster Xros Encounter",
  id: "BT-10",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-10_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-10_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-03: Theme Booster Draconic Roar",
  id: "EX-03",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-03_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-03_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-11: Booster Dimensional Phase",
  id: "BT-11",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-11_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-11_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-12: Booster Across Time",
  id: "BT-12",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-12_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-12_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-04: Theme Booster Alternative Being",
  id: "EX-04",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-04_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-04_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-13: Booster Versus Royal Knights",
  id: "BT-13",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-13_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-13_symbol.png",
},
  {
  tcgId: "digimon",
  name: "RB-01: Resurgence Booster",
  id: "RB-01",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:RB-01_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:RB-01_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-14: Booster Blast Ace",
  id: "BT-14",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-14_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-14_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-05: Theme Booster Animal Colosseum",
  id: "EX-05",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-05_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-05_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-15: Booster Exceed Apocalypse",
  id: "BT-15",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-15_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-15_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-16: Booster Beginning Observer",
  id: "BT-16",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-16_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-16_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-06: Theme Booster Infernal Ascension",
  id: "EX-06",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-06_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-06_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-17: Booster Secret Crisis",
  id: "BT-17",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-17_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-17_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-07: Extra Booster Digimon Liberator",
  id: "EX-07",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-07_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-07_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-18: Booster Elemental Successor",
  id: "BT-18",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-18_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-18_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-19: Booster Xros Evolution",
  id: "BT-19",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-19_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-19_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-08: Extra Booster Chain of Liberation",
  id: "EX-08",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-08_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-08_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-20: Booster Over the X",
  id: "BT-20",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-20_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-20_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-21: Booster World Convergence",
  id: "BT-21",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-21_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-21_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-09: Extra Booster Versus Monsters",
  id: "EX-09",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-09_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-09_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-22: Booster Cyber Eden",
  id: "BT-22",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-22_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-22_symbol.png",
},
  {
  tcgId: "digimon",
  name: "EX-10: Extra Booster Sinister Order",
  id: "EX-10",
  series: "Expert Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-10_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:EX-10_symbol.png",
},
  {
  tcgId: "digimon",
  name: "BT-23: Booster Hackers Slumber",
  id: "BT-23",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:20.552Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-23_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:BT-23_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-1: Starter Deck Gaia Red",
  id: "ST-1",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-1_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-1_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-2: Starter Deck Cocytus Blue",
  id: "ST-2",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-2_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-2_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-3: Starter Deck Heaven's Yellow",
  id: "ST-3",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-3_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-3_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-4: Starter Deck Giga Green",
  id: "ST-4",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-4_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-4_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-5: Starter Deck Machine Black",
  id: "ST-5",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-5_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-5_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-6: Starter Deck Venomous Violet",
  id: "ST-6",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-6_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-6_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-7: Starter Deck Gallantmon",
  id: "ST-7",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-7_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-7_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-8: Starter Deck UlforceVeedramon",
  id: "ST-8",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-8_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-8_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-9: Starter Deck Ultimate Ancient Dragon",
  id: "ST-9",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-9_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-9_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-10: Starter Deck Parallel World Tactician",
  id: "ST-10",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-10_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-10_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-11: Starter Deck Special Entry Deck",
  id: "ST-11",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-11_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-11_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-12: Starter Deck Jesmon",
  id: "ST-12",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-12_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-12_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-13: Starter Deck RagnaLoardmon",
  id: "ST-13",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-13_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-13_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-14: Advanced Deck Set Beelzemon",
  id: "ST-14",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-14_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-14_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-15: Starter Deck Dragon of Courage",
  id: "ST-15",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-15_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-15_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-16: Starter Deck Wolf of Friendship",
  id: "ST-16",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-16_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-16_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-17: Advanced Deck Set Double Typhoon",
  id: "ST-17",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-17_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-17_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-18: Starter Deck Guardian Vortex",
  id: "ST-18",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-18_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-18_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-19: Starter Deck Fable Waltz",
  id: "ST-19",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-19_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-19_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-20: Starter Deck Protector of Light",
  id: "ST-20",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-20_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-20_symbol.png",
},
  {
  tcgId: "digimon",
  name: "ST-21: Starter Deck Hero of Hope",
  id: "ST-21",
  series: "Starter Deck",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:21.839Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-21_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:ST-21_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-04: Digimon Card Game Tamer's Set 2",
  id: "PB-04",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-04_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-04_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-08: Digimon Tamers Playmat",
  id: "PB-08",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-08_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-08_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-09: Memorial Collection 01 Playmat",
  id: "PB-09",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-09_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-09_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-12: Digimon Frontier 20th Memorial Set",
  id: "PB-12",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-12_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-12_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-14: Digimon Card Game Tamer's Set EX2",
  id: "PB-14",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-14_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-14_symbol.png",
},
  {
  tcgId: "digimon",
  name: "GB-01: Digimon Card Game Gift Box",
  id: "GB-01",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:GB-01_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:GB-01_symbol.png",
},
  {
  tcgId: "digimon",
  name: "AB-01: Digimon Card Game Adventure Box",
  id: "AB-01",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:AB-01_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:AB-01_symbol.png",
},
  {
  tcgId: "digimon",
  name: "GB-02: Digimon Card Game Gift Box 2",
  id: "GB-02",
  series: "Booster",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:GB-02_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:GB-02_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-01: Tamer's Evolution Box",
  id: "PB-01",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-01_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-01_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-02: Digimon Card Game Tamer's Set",
  id: "PB-02",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-02_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-02_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-03: WarGreymon Playmat",
  id: "PB-03",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-03_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-03_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-05: Digimon Card Game Tamer's Set 3",
  id: "PB-05",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-05_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-05_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-06: Tamer's Evolution Box 2",
  id: "PB-06",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-06_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-06_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-07: Digimon Card Game Tamer's Set EX",
  id: "PB-07",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-07_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-07_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-10: Digimon Card Game Tamer's Set 4",
  id: "PB-10",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-10_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-10_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-11: Digimon Card Game Tamer's Set 5",
  id: "PB-11",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-11_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-11_symbol.png",
},
  {
  tcgId: "digimon",
  name: "PB-13: Digimon Card Game Royal Knights Binder Set",
  id: "PB-13",
  series: "Promo",
  printedTotal: 0,
  total: 0,
  ptcgoid: "-",
  releaseDate: new Date("2025-04-01T08:40:23.096Z"),
  logoUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-13_logo.png",
  symbolUrl: "https://digimoncardgame.fandom.com/wiki/File:PB-13_symbol.png",
},
];
