export const cardSeed = [
  {
    tcgId: "magic-the-gathering",
    setId: "fic",
    name: "Celes, Rune Knight",
    searchName: "celes, rune knight",
    tcgApiId: "d30dd823-9a04-4e3d-89c6-0fc5afc9efa4",
    number: "201",
    rarity: "mythic",
    metadata: {
      colors: ["B", "R", "W"],
      type: "Legendary Creature — Human Wizard Knight",
      manaCost: "{1}{R}{W}{B}",
      cmc: 4,
      oracleText: "When Celes enters, discard any number of cards, then draw that many cards plus one.\nWhenever one or more other creatures you control enter, if one or more of them entered from a graveyard or was cast from a graveyard, put a +1/+1 counter on each creature you control.",
      flavorText: "",
    },
    images: {
      large: "https://cards.scryfall.io/large/front/d/3/d30dd823-9a04-4e3d-89c6-0fc5afc9efa4.jpg?1741592436",
      small: "https://cards.scryfall.io/small/front/d/3/d30dd823-9a04-4e3d-89c6-0fc5afc9efa4.jpg?1741592436",
    },
  },
  {
    tcgId: "magic-the-gathering",
    setId: "fic",
    name: "Cloud, Ex-SOLDIER",
    searchName: "cloud, ex-soldier",
    tcgApiId: "07b4e4f8-6a31-4533-be51-668ce3ddc84f",
    number: "2",
    rarity: "mythic",
    metadata: {
      colors: ["G", "R", "W"],
      type: "Legendary Creature — Human Soldier Mercenary",
      manaCost: "{2}{R}{G}{W}",
      cmc: 5,
      oracleText: "Haste\nWhen Cloud enters, attach up to one target Equipment you control to it.\nWhenever Cloud attacks, draw a card for each equipped attacking creature you control. Then if Cloud has power 7 or greater, create two Treasure tokens.",
      flavorText: "",
    },
    images: {
      large: "https://cards.scryfall.io/large/front/0/7/07b4e4f8-6a31-4533-be51-668ce3ddc84f.jpg?1739887346",
      small: "https://cards.scryfall.io/small/front/0/7/07b4e4f8-6a31-4533-be51-668ce3ddc84f.jpg?1739887346",
    },
  },
  {
    tcgId: "magic-the-gathering",
    setId: "fic",
    name: "Terra, Herald of Hope",
    searchName: "terra, herald of hope",
    tcgApiId: "5aa1a2d7-6133-41a9-9662-9008d1309935",
    number: "4",
    rarity: "mythic",
    metadata: {
      colors: ["B", "R", "W"],
      type: "Legendary Creature — Human Wizard Warrior",
      manaCost: "{R}{W}{B}",
      cmc: 3,
      oracleText: "Trance — At the beginning of combat on your turn, mill two cards. Terra gains flying until end of turn.\nWhenever Terra deals combat damage to a player, you may pay {2}. When you do, return target creature card with power 3 or less from your graveyard to the battlefield tapped.",
      flavorText: "",
    },
    images: {
      large: "https://cards.scryfall.io/large/front/5/a/5aa1a2d7-6133-41a9-9662-9008d1309935.jpg?1740035706",
      small: "https://cards.scryfall.io/small/front/5/a/5aa1a2d7-6133-41a9-9662-9008d1309935.jpg?1740035706",
    },
  },
  {
    tcgId: "magic-the-gathering",
    setId: "fic",
    name: "Tidus, Yuna's Guardian",
    searchName: "tidus, yuna's guardian",
    tcgApiId: "2cfd4494-346c-4cbc-8072-e267254cefcc",
    number: "5",
    rarity: "mythic",
    metadata: {
      colors: ["G", "U", "W"],
      type: "Legendary Creature — Human Warrior",
      manaCost: "{G}{W}{U}",
      cmc: 3,
      oracleText: "At the beginning of combat on your turn, you may move a counter from target creature you control onto a second target creature you control.\nCheer — Whenever one or more creatures you control with counters on them deal combat damage to a player, you may draw a card and proliferate. Do this only once each turn.",
      flavorText: "",
    },
    images: {
      large: "https://cards.scryfall.io/large/front/2/c/2cfd4494-346c-4cbc-8072-e267254cefcc.jpg?1741089326",
      small: "https://cards.scryfall.io/small/front/2/c/2cfd4494-346c-4cbc-8072-e267254cefcc.jpg?1741089326",
    },
  },
  {
    tcgId: "magic-the-gathering",
    setId: "fic",
    name: "Y'shtola, Night's Blessed",
    searchName: "y'shtola, night's blessed",
    tcgApiId: "c7f2c2d5-e052-49e8-b5de-712858c2ea78",
    number: "7",
    rarity: "mythic",
    metadata: {
      colors: ["B", "U", "W"],
      type: "Legendary Creature — Cat Warlock",
      manaCost: "{1}{W}{U}{B}",
      cmc: 4,
      oracleText: "Vigilance\nAt the beginning of each end step, if a player lost 4 or more life this turn, you draw a card.\nWhenever you cast a noncreature spell with mana value 3 or greater, Y'shtola deals 2 damage to each opponent and you gain 2 life.",
      flavorText: "",
    },
    images: {
      large: "https://cards.scryfall.io/large/front/c/7/c7f2c2d5-e052-49e8-b5de-712858c2ea78.jpg?1739887258",
      small: "https://cards.scryfall.io/small/front/c/7/c7f2c2d5-e052-49e8-b5de-712858c2ea78.jpg?1739887258",
    },
  },
];
